### PR TITLE
Memory: Fix bug in previous commit that introduced 1k buffers

### PR DESCRIPTION
**Pull request by singalsu**
This patch fixes a regression caused by commit
b5308ee8e6eff51b0a2fea5a39a88d0de10edcfd. The HEAP_RUNTIME_SIZE
calculation equation macro missed this buffer totally.

Signed-off-by: Seppo Ingalsuo <seppo.ingalsuo@linux.intel.com>

### CODE REVIEW

**Comment by singalsu** [comment]
I need to update this PR. Please wait.

**Comment by singalsu** [comment]
@tlauda @lgirdwood The PR is updated now. With 4x 1kB buffers the DSP panic is avoided.

**Comment by mmaka1** [comment]
@singalsu @lgirdwood The question is if the global common memory map should be changed for apl platforms just to w/a some specific topology that includes eq. It impacts all the configurations where those buffers will never be consumed.

Another thing to re-consider in eq modules is the flow in new() where both device and data objects are allocated and then the input parameters (blob size) are validated. In case of failure, both are freed. Swapping those operations would help to avoid the allocations in case of bad params. This does not have much impact with the current limited flows but changes are coming to make things more dynamic.

**Comment by mmaka1** [comment]
@singalsu @lgirdwood I agree that having a pool of larger buffers might be required in general and that eventually eq becomes a part of most of the topologies. And the apl might need to allocate this by default. I was a bit concerned seeing a comment that its just to w/a potential mem leak being debugged.

**Comment by singalsu** [comment]
@tlauda @mmaka1 @lgirdwood I'm no more able to repeat the crash that I got with 1x 1024 bytes buffers. Both 1x (my 1st proposal) and 4x (this proposal) work. I'm now testing again with 1x version and changing EQs during idle and playing music works. I'm suspecting I was testing on Friday accidentally with FW version that missed the 1k buffers consumption in HEAP_RUNTIME_SIZE and made wrong conclusion.

So the 1kB version of this PR would be OK for now to test the EQ but 4kB total available for allocation (for the max 1kB buffers would be better for DSP application developers. What's your proposal?

Something need to be done urgently since the HEAP_RUNTIME_SIZE is wrong.

**Comment by lgirdwood** [comment]
@singalsu I think @mmaka1 has some API updates for allocator coming at some point soon, but the block mappings should be configurable by the user if necessary. HEAP_RUNTIME_SIZE should be calculated based on MEMORY_SIZE - stack, other heaps - text - data etc.. Please send a PR if we are missing something out from the calculation.

**Comment by lgirdwood** [comment]
@singalsu oh, can you also confirm CI failure are harmless

**Comment by singalsu** [comment]
@lgirdwood Currently it shows that all checks have passed. It makes me wonder if all the other PR fails I get are due to lack of this memory definitions fix patch.

**Comment by singalsu** [comment]
@mmaka1 @lgirdwood Could you please merge this PR to avoid the random FW crashes that everyone experiences (and bisects).

**Pull request merged**
