### PR TITLE
rtnr: Fix log formatting for unsigned parameters

### PR DESCRIPTION
**Pull request by MingJenTai**
This PR fixes the format for logging unsigned parameters.

### CODE REVIEW

**Comment by marc-hb** [comment]
Which toolchain found this?

**Comment by MingJenTai** [comment]
> Which toolchain found this?

Hi @yaochunhung, are you able to answer this? Thanks!

**Comment by yaochunhung** [comment]
@MingJenTai I just think it should be %u for unsigned int, not found any issue on any toolchian. thanks.

**Comment by marc-hb** [comment]
I'm not sure this change is a good idea.

As the C language has no `None` special value, sometimes people use negative values as error codes. Example: `unsigned size = -1`. In that case it's much more readable to display these negatives values as `-1` or `-2`; especially in an error message like here.

Of course it would be better to change the type and switch to `int size = -1` to formerly support error values without trying to understand C's impenetrable conversion rules but that may require many more changes all across the code.

**Comment by yaochunhung** [comment]
Thanks. I know your concern now. But I have a little bit confusion because I see there is example used uint32_t  and print %u,
https://github.com/thesofproject/sof/blob/main/src/audio/buffer.c#L38

**Comment by lgirdwood** [comment]
@MingJenTai I assume both are unsigned types then this is good for me. Fwiw, Zephyr build can be strict here, but I dont think we have tried RTNR with Zephyr config yet.

**Comment by marc-hb** [comment]
> But I have a little bit confusion because I see there is example 

I'm pretty sure you can find an example for anything.

**Comment by MingJenTai** [comment]
> @MingJenTai I assume both are unsigned types then this is good for me. Fwiw, Zephyr build can be strict here, but I dont think we have tried RTNR with Zephyr config yet.

Yes both are unsigned types. Not sure about what's the common formatting of unsigned variables should be used here but at least the compiler will not report warning/error about this.

**Review by lgirdwood — APPROVED** [review]

**Pull request merged**
