### PR TITLE
topology: add a development topology for HDA without HDMI

### PR DESCRIPTION
**Pull request by xiulipan**
some platform do not have HDMI codec support, need to fallback to use
HDA without HDMI codec.

Signed-off-by: Pan Xiuli <xiuli.pan@linux.intel.com>

### CODE REVIEW

**Comment by plbossart** [comment]
IIRC there is already a machine driver workaround where HDMI is disabled on such platforms w/ e.g. NVIDIA HDMI. I don't see why we should care and add even more topology files?

@kv2019i can you confirm?

**Comment by mengdonglin** [comment]
@plbossart @kv2019i The test topology is for CI. It can take a long time for i915 support for leading platforms to be ready in upstream mainline kernel. Although the SOF can tolerate i915 failure and go ahead to create sound card, CI test will failure with multiple test cases involving display audio PCMs defined by production topology files.

**Comment by plbossart** [comment]
NAK. You can disable HDMI with a kernel parameter.

````
static int hda_codec_mask = -1;
module_param_named(codec_mask, hda_codec_mask, int, 0444);
MODULE_PARM_DESC(codec_mask, "SOF HDA codec mask for probing");

	if (hda_codec_mask != -1) {
		bus->codec_mask &= hda_codec_mask;
		dev_dbg(bus->dev, "filtered codec_mask = 0x%lx\n",
			bus->codec_mask);
	}
````

**Comment by kv2019i** [comment]
I guess the problem is the PCM nodes get created even if i915 is not available. In case i915 is not available, playback will fail. For end-user systems, this is not a problem as HDMI PCMs are advertized only when a monitor is connected, but in CI this issue can be hit.

You can check availability of i915 via various way (e.g. checking presence of "/proc/asound/card0/codec#2", but for a test case that goes through all available ALSA PCMs in a generic way, this won't help. You could have some additional logic:
   - given PCM number X -> PCMX
   - look for mixer control "HDMI/DP,pcm=X Jack"
   - if mixer control exists AND /proc/asound/card0/codec#2 is not present -> i915 is not loaded and test on this PCM should be skipped

This can be a bit dangerous as well, as if there would be a regression in i915 init, above logic could hide a real error. So in that sense, a separate topology file without HDMI entries, might be a safer option. Then running the full test is expected to pass.

**Comment by xiulipan** [comment]
@plbossart @kv2019i So this PR is create as a development TPLG to hide HDMI PCM to enable CI test.

And a quick question about **hda_codec_mask**, can this mask solve the 1min timeout for i915 probe?
```
	if (!acomp->ops) {
		if (!IS_ENABLED(CONFIG_MODULES) ||
		    !request_module("i915")) {
			/* 60s timeout */
			wait_for_completion_timeout(&acomp->master_bind_complete,
						    msecs_to_jiffies(60 * 1000));
		}
```
https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/hda/hdac_i915.c#L159-L165

Anyway I will do a quick test now.

**Comment by xiulipan** [comment]
@plbossart I did a quick test with `mask_codec` by adding `options snd_sof_intel_hda_common dyndbg=+p codec_mask=1`

And SOF indeed only probe HDA codec
```
[186040.429845] sof-audio-pci 0000:00:1f.3: HDA codec #0 probed OK: response: 10ec0711
[186040.432634] hdaudio ehdaudio0D0: loading codec module: hdaudio:v10EC0711r00100002a01

[186040.440098] sof-audio-pci 0000:00:1f.3: hda codecs found, mask 1
[186040.440142] sof-audio-pci 0000:00:1f.3: using HDA machine driver skl_hda_dsp_generic now
```
But skl_hda_dsp_generic seems not support no HDMI codec mode.
https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/soc/intel/boards/skl_hda_dsp_generic.c#L137-L166
```
	if (codec_mask == IDISP_CODEC_MASK) {
		/* topology with iDisp as the only HDA codec */
		num_links = IDISP_DAI_COUNT + DMIC_DAI_COUNT;
		num_route = IDISP_ROUTE_COUNT;


		/*
		 * rearrange the dai link array and make the
		 * dmic dai links follow idsp dai links for only
		 * num_links of dai links need to be registered
		 * to ASoC.
		 */
		for (i = 0; i < DMIC_DAI_COUNT; i++) {
			skl_hda_be_dai_links[IDISP_DAI_COUNT + i] =
				skl_hda_be_dai_links[IDISP_DAI_COUNT +
					HDAC_DAI_COUNT + i];
		}
	} else {
		/* topology with external and iDisp HDA codecs */
		num_links = ARRAY_SIZE(skl_hda_be_dai_links);
		num_route = ARRAY_SIZE(skl_hda_map);
		card->dapm_widgets = skl_hda_widgets;
		card->num_dapm_widgets = ARRAY_SIZE(skl_hda_widgets);
		if (!ctx->idisp_codec) {
			for (i = 0; i < IDISP_DAI_COUNT; i++) {
				skl_hda_be_dai_links[i].codecs = dummy_codec;
				skl_hda_be_dai_links[i].num_codecs =
					ARRAY_SIZE(dummy_codec);
			}
		}
	}
```

**Comment by kv2019i** [comment]
@xiulipan wrote:
> But skl_hda_dsp_generic seems not support no HDMI codec mode.
> https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/soc/intel/boards/skl_hda_dsp_generic.c#L137-L166

? But it does. If codec_mask==1 (due to i915 missing or manually set codec_mask), we go to following code path:

```
} else {
		/* topology with external and iDisp HDA codecs */
...
		if (!ctx->idisp_codec) {
			for (i = 0; i < IDISP_DAI_COUNT; i++) {
...
````

And the dai links are hooked to the dummy codec.

The generic hda mach driver does not support topologies that do not have iDisp links as this will never be the case in production topologies.

**Comment by kv2019i** [comment]
@xiulipan wrote:
> And a quick question about **hda_codec_mask**, can this mask solve the 1min timeout for i915 probe?

No, unfortunately no, the timeout will always be there as w eneed to establish acomp before we query the bus for codecs.

To avoid the timeout, one needs to disable CONFIG_SND_HDA_I915 in kernel config.

**Comment by xiulipan** [comment]
@kv2019i I mean skl_hda_dsp_generic seems does not support the no-hdmi codec_mask. I am thinking do we need to create support for that?
What is legacy HDA behavior when codec_mask=1

**Comment by kv2019i** [comment]
@xiulipan wrote:
> @kv2019i I mean skl_hda_dsp_generic seems does not support the no-hdmi codec_mask. I am thinking do we need to create support for that?

No, no, it does support that. If codec_mask==1, ctx->idisp_codec is set to false and the code path I quoted above is taken. You just need to use the production topology. 

What does not work is if you try a topology file that does not have iDisp codecs. That doesn't work with this machine driver.

> What is legacy HDA behavior when codec_mask=1

Similarly as SOF generic driver, it disables the iDisp codec.

**Comment by plbossart** [comment]
just to be clear: this PR just makes the job of maintaining topologies harder when there is a solution at the kernel level.
we really need to *reduce* the number of topologies to a strict/supported minimum. Test topologies should go somewhere else if needed.

**Comment by xiulipan** [comment]
@plbossart This TPLG is used to hide HDMI PCM and now goes into `topology/development` which is used for development now.
@kv2019i Also if we have https://github.com/thesofproject/linux/pull/2726 in future , do you think if it is possible that we can try to dynamically load this topology with some change in our driver (I see we can load HDMI only topology now and we can patch topology name with -1ch/2ch/3ch/4ch)?

**Comment by plbossart** [comment]
> @plbossart This TPLG is used to hide HDMI PCM and now goes into `topology/development` which is used for development now.

still not convinced. Are you also going to do this for SoundWire devices? where do we stop?

> @kv2019i Also if we have [thesofproject/linux#2726](https://github.com/thesofproject/linux/pull/2726) in future , do you think if it is possible that we can try to dynamically load this topology with some change in our driver (I see we can load HDMI only topology now and we can patch topology name with -1ch/2ch/3ch/4ch)?

we have had a kernel parameter to change to topology default path for a very long time. The dmic patch is already provided for HDaudio, it's also been a very long time.

**Comment by lgirdwood** [comment]
@plbossart btw, just wondering how this sort of topology will fit into your aux bus HDA/HDMI separation. Should we have a generic HDMI topology and a custom SSP/DMIC machine topology loaded by drivers ?

**Comment by xiulipan** [comment]
@plbossart @lgirdwood I think if we will spilt the HDA codec and HDMI codec later, this would be a good experiment and code base for future aux bus.
PS: this is what we want in the development folder.

**Comment by lgirdwood** [comment]
@plbossart @ranj063 @kv2019i does this fit into the aux bus plans ?

**Comment by plbossart** [comment]
> @plbossart @ranj063 @kv2019i does this fit into the aux bus plans ?

not really.
If we do a split, I would expect that the topology is split in two files, but we can merge them for legacy as needed. This PR duplicates the HDaudio+DMIC parts instead of moving HDMI out, so to me it's the wrong direction. It's like cutting a cake horizontally instead of vertically.

**Comment by gkbldcig** [comment]
Can one of the admins verify this patch?

**Comment by lgirdwood** [comment]
We can close this now and re-open if it's needed.

**Comment by aiChaoSONG** [comment]
@kv2019i as I have a patch in sof-test to exclude HDMI pipelines on platform where i915 is not ready, the test topology is not required any more, even in the future. You don't need to negotiate with Pierre anymore. thanks
 https://github.com/thesofproject/sof-test/pull/644.

**Pull request closed without merging**
