### PR TITLE
platform/posix: Unbreak fuzzer support

### LINKED ISSUE #9101: [BUG] IPC3/4 fuzzer build broken with Zephyr PR 71378
**Describe the bug**
As discussed in https://github.com/zephyrproject-rtos/zephyr/pull/71378#pullrequestreview-2011374611 , recent changes in Zephyr mainline break the SOF fuzzer builds and the github CI checks using these builds.

**To Reproduce**
https://github.com/thesofproject/sof/actions/runs/8972185189/job/24639608648?pr=9098

**Reproduction Rate**
100%

**Expected behavior**
Fuzzer build works.

**Impact**
Fuzzer not usable with SOF.

**Environment**
https://sof-ci.01.org/sofpr/PR9098/build4470/build/index.html

```
Parsing /home/runner/work/sof/sof/workspace/zephyr/Kconfig
/home/runner/work/sof/sof/workspace/build-fuzz/zephyr/misc/generated/extra_kconfig_options.conf:2: warning:
      attempt to assign the value '100' to the undefined symbol ARCH_POSIX_FUZZ_TICKS

error: Aborting due to Kconfig warnings

Loaded configuration '/home/runner/work/sof/sof/workspace/zephyr/boards/native/native_posix/native_posix_defconfig'
Merged configuration '/home/runner/work/sof/sof/workspace/sof/app/prj.conf'
Merged configuration '/home/runner/work/sof/sof/workspace/sof/app/stub_build_all_ipc3.conf'
Merged configuration '/home/runner/work/sof/sof/workspace/build-fuzz/zephyr/misc/generated/extra_kconfig_options.conf'
CMake Error at /home/runner/work/sof/sof/workspace/zephyr/cmake/modules/kconfig.cmake:391 (message):
  command failed with return code: 1
Call Stack (most recent call first):
  /home/runner/work/sof/sof/workspace/zephyr/cmake/modules/zephyr_default.cmake:132 (include)
  /home/runner/work/sof/sof/workspace/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:[66](https://github.com/thesofproject/sof/actions/runs/8972185189/job/24639608648?pr=9098#step:7:67) (include)
  /home/runner/work/sof/sof/workspace/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)
  CMakeLists.txt:5 (find_package)
```

### PR DESCRIPTION
**Pull request by andyross**
Upstream Zephyr moved the LLVM fuzzer entry point out of the arch layer and made it an app responsibility, so we broke.  Add back the support here that got removed.

Fixes #9101

### CODE REVIEW

**Comment by andyross** [comment]
Put this together in a rush, please review carefully.  Not complicated, just code motion.

**Review by kv2019i — COMMENTED** [review]
Thanks @andyross , that was quick! I think the sof/scripts/fuzz.sh needs updates to use the renamed Kconfig options (now defined on SOF side).

**Comment by marc-hb** [comment]
> I think the sof/scripts/fuzz.sh needs updates to use the renamed Kconfig options (now defined on SOF side).

Yes, @andyross please try `sof/scripts/fuzz.sh [-h]`. Since you already have all the dependencies installed, it must work out of the box. It's a very simple script; there is no "CI secret" here.

**Comment by andyross** [comment]
Heh, indeed.  The fuzz.sh delta was sitting un-git-added in my tree still.  Oops.

**Comment by andyross** [comment]
(Oh, and the checkpatch whine isn't really fixable: the symbols in question don't appear in Zephyr headers, they're still whitebox entry points in the native_posix arch.  In the medium term we'll need to move to "native_sim", which is evolved architecture, and it has a better specified API.)

**Review by kv2019i — APPROVED** [review]
Thanks, looks good now! The previously passing CI checks now pass, so expectation is the remaining checks will pass as well (as the fuzz changes won't affect the on-device SOF tests).

**Comment by kv2019i** [comment]
@andyross Can you rebase, there's a small conflict with in CMakeLists.txt as one of the posix platform files was removed in another PR today. We need to get clean run of the CI to merge, but I checked the faiiling case and it's a fail in "16_00_TestSdwTransferLoopback" test case, so cannot possibly be related to your PR. If the case fails after rebase, I'll ping our CI folks to check.

**Review by lgirdwood — APPROVED** [review]
Thanks @andyross
@marc-hb btw - do we have a build test to build POSIX Zephyr + SOF in CI ?

**Comment by kv2019i** [comment]
@lgirdwood wrote:
> Thanks @andyross @marc-hb btw - do we have a build test to build POSIX Zephyr + SOF in CI ?

Yes, that's how this was discovered -> https://github.com/thesofproject/sof/actions/runs/8972185189/job/24639608648?pr=9098 when doing a Zephyr update

**Comment by andyross** [comment]
Rebased.

**Comment by kv2019i** [comment]
And the tests now pass as expected, merging!

**Pull request merged**
