### PR TITLE
cherry pick module_adapter changes from main to amd_rn_dts

### PR DESCRIPTION
**Pull request by johnylin76**
b3106c396e540c260bba3b08c218f6598ea74726 module_adapter: get the actual period_bytes
b9889d52d0e1b6002ee016b55fa0487544fc0593 module_adapter: Modify reset API
53b3bc6a956ae5957966336f88980438f1f85a88 module_adapter:Fix dangling pointer issue in module reset

### CODE REVIEW

**Comment by johnylin76** [comment]
Back-port b9889d52d0e1b6002ee016b55fa0487544fc0593 for #6331

**Comment by lgirdwood** [comment]
@thesofproject/amd pls review. Cherry-picks from main.

**Comment by gkbldcig** [comment]
Can one of the admins verify this patch?

**Comment by lgirdwood** [comment]
@thesofproject/amd pls review/merge.

**Review by balakishorepati — APPROVED** [review]
LGTM

**Pull request merged**
