### PR TITLE
topology: byt: fix media pipeline period for nocodec

### PR DESCRIPTION
**Pull request by tlauda**
Fixes media pipeline period for nocodec byt and cht topologies.
Now codec and nocodec topologies are aligned in regards to pipe
configurations.

Signed-off-by: Tomasz Lauda <tomasz.lauda@linux.intel.com>

### CODE REVIEW

**Comment by xiulipan** [comment]
@tlauda Can you give some simple explanation about how this change fix the issue?
The arecord can work again after aplay, so what happen inside FW that suddenly have enough memory?

**Comment by tlauda** [comment]
@xiulipan It's a little bit tricky and to be honest this is rather a workaround instead of a real fix. The real rootcause of the issue is the fact, that m4 scripts are unpredictable (at least for me) and setting period of media pipe to 4 ms has also changed period of capture pipeline to 4 ms. It worked after initial playback, because format played hasn't used the whole buffer reserved, so it resized it to smaller one and freed some extra space. That way capture pipe could allocate bigger buffers.

@lgirdwood @plbossart Do you have any idea, why m4 scripts work this way? It seems that changing sequence of definitions changes parameters for all the pipelines. Also why do we need to separately define the same parameters in both PCM and DAI? I feel that DAI macro overwrites everything anyway.

**Comment by xiulipan** [comment]
@tlauda Thanks for the explanation, I will have a look about this m4 issue it would be related to variable.

**Comment by xiulipan** [comment]
@tlauda Thanks for the hint, root cause to the m4 variable name changing not completed.
Fix the wrongly m4 with https://github.com/thesofproject/sof/pull/1818.

Can you change this PR to clean up the tplg m4 files?

**Comment by xiulipan** [comment]
@tlauda @lgirdwood 
For the media pipeline workaroud 4000=>1000 is no longer need as I have fixed with root cause #1818 

But the removing patches is indeed needed. We have changed the logic to generate some similar tplg and those m4 is no one used files. This should be some merge caused issue, some very old code base merged with file removed branch and bring the removed files back. But in our makefile system, those m4 is no longer used.

@tlauda Can you confirm do we still need the 4000=>1000 change for byt nocodec media pipeline?

**Comment by tlauda** [comment]
@xiulipan Still needed as we currently don't support different periods in connected pipelines (media pipeline isn't scheduled separately, but the copy is propagated from the dai pipe).

**Comment by lgirdwood** [comment]
@tlauda Jenkins CI issue is realted to kernel bug, but can you look at QB I assume they are false positives.

**Comment by tlauda** [comment]
@lgirdwood QB is passing.

**Pull request merged**
