### PR TITLE
trace: Remove metaprogramming from trace implementation

### PR DESCRIPTION
**Pull request by ktrzcinx**
Functions written with metaprogramming are hard to read and debug,
so newly introduced version should be easier to understand for
new developers. Moreover introduced version is more generic and
compact because of usage one logging function implementation
regardless of given parameters number.

### CODE REVIEW

**Comment by lgirdwood** [comment]
@ktrzcinx good work - I found it hard to debug too.

**Comment by dbaluta** [comment]
@ktrzcinx this is a very good change, it was almost impossible to debug. One question to understand the change better: so you basically replaced macros with functions?

**Comment by mmaka1** [comment]
@ktrzcinx Any data about performance impact? (Just curious, not saying this is no go since code simplification,  improves maintenance and has to cost sometimes but this is one very frequently called functions, so would be nice to know how the cost increased).
I just briefly compared the binary code "before" and "after". It seems that the code (cnl configuration, info level so not too many calls) takes ~4KB more and data too (~4KB). Seems that each call to new trace_log needs more preparation than the old _trace_event<n>. The function is 2x longer than old ones, however it just a single instance this time (btw, a call to put_header could be inlined in the new version because there is just one reference now).

**Comment by mmaka1** [comment]
> One question to understand the change better: so you basically replaced macros with functions?

@dbaluta Actually 5 fixed func _trace_event<n> functions generated by macros replaced with a single var arg trace_log function.

**Comment by ktrzcinx** [comment]
@mmaka1 perf_cnt shows putting one log message in old version takes about 113 (+- 2) cycles and version with va takes about 116 (+-2) cycles. Once measuring time of putting 100 messages it is 8500(+-500) and 8800 (+-100), in table:

| cnt  | 1             | 100              |
|------|---------------|------------------|
| meta | 113\(\+\-2\)  | 8500\(\+\-500\)  | 
| va   | 116 \(\+\-2\) | 8800 \(\+\-100\) |

So I think time performance isn't an issue.

> The function is 2x longer than old ones,

In which sense? I claim that there is one more runtime `if` (+ second for mbox version) and filling parameters in for loop instead of unfolded previous version.

**Comment by mmaka1** [comment]
@ktrzcinx I just listed symbols and binary code of new one is 3x bigger, I quickly looked at disasm code to compare and it seemed ~2x longer (lines -> instructions), but the size is a bit misleading since there are a lot of nop-s inserted into flix instructions which do parallel ops quickly thus asked about real cycles measured).

**Comment by lgirdwood** [comment]
@ktrzcinx can you look at the UT failures. It's possible cmocka needs an update for this too.

**Comment by lgirdwood** [comment]
Jenkins known issues.

**Pull request merged**
