### PR TITLE
pm: cavs: no need to switch IRQs when setting PM state variable.

### PR DESCRIPTION
**Pull request by lgirdwood**
This variable is only used to enable and disable the CPU residency
counters. No need to  switch IRQs OFF when setting it's value.

Signed-off-by: Liam Girdwood <liam.r.girdwood@linux.intel.com>

### CODE REVIEW

**Comment by lgirdwood** [comment]
@kkarask which IPC is the DONE bit referring to here ? Fwiw, this test is passing on TGL.
```

17:29:00.898         ipc_sent
17:29:00.898         Sending PmSetD0ix (C8000000, 00000010)
                     Payload:
                     00000008 00000000 

17:29:03.953         ipc_notif
17:29:03.953         Notification CompNotification (50050000, 00000000)
                     Payload:
                     00000000 50050009  received!

17:29:03.963         Timed out after 0.001 seconds. Cause:
                     Done bit not cleared after IPC received
```

**Comment by lgirdwood** [comment]
@lyakh @kv2019i fyi - this keeps IRQs ON for an extra 15uS per 1ms tick.

**Review by lyakh — COMMENTED** [review]
Could you please explain a bit about the second commit - is the 15us delay only due to locking interrupts or because we actually busy loop for `PLATFORM_FORCE_L1_EXIT_TIME` ticks on each HDA DMA transfer in `cavs_pm_runtime_force_host_dma_l1_exit()`?..

**Comment by lgirdwood** [comment]
> Could you please explain a bit about the second commit - is the 15us delay only due to locking interrupts or because we actually busy loop for `PLATFORM_FORCE_L1_EXIT_TIME` ticks on each HDA DMA transfer in `cavs_pm_runtime_force_host_dma_l1_exit()`?..

It's the ```PLATFORM_FORCE_L1_EXIT_TIME``` delay with IRQs OFF that happens at the end of LL work on every tick.

**Comment by kv2019i** [comment]
Not updated in more than a year, closing.

**Pull request closed without merging**
