### PR TITLE
[TEST] Volume LLEXT

### PR DESCRIPTION
**Pull request by lyakh**
this includes #9151 and depends on not yet merged Tephyr PRs, collected as a test in https://github.com/zephyrproject-rtos/zephyr/pull/73274

### CODE REVIEW

**Comment by lyakh** [comment]
Zephyr LLEXT regression caused by https://github.com/zephyrproject-rtos/zephyr/pull/73949 lead to https://sof-ci.01.org/sofpr/PR9172/build5783/devicetest/index.html?model=MTLP_RVP_HDA&testcase=check-playback-10sec

**Comment by lyakh** [comment]
Sparse failures seem to be caused by #8919 @andyross

**Comment by marc-hb** [comment]
> Sparse failures seem to be caused by https://github.com/thesofproject/sof/pull/8919 @andyross

Yes, this was merged broken. Fixup from Andy: #9265

**Comment by lyakh** [comment]
superseded by multiple other PRs e.g. #9453

**Pull request closed without merging**
