### PR TITLE
platform: imx: Do not perform early get/init of the DAI

### PR DESCRIPTION
**Pull request by paulstelian97**
It isn't necessary to do a dai_get this early for the ESAI; the SAI
doesn't even have one.

Calling dai_probe() after dai_get() is pointless since dai_probe() was
already called from a previous dai_get() with CREAT flag (in particular
the one which incremented sref from 0 to 1).

Signed-off-by: Paul Olaru <paul.olaru@nxp.com>

I wonder if the last thing I said above doesn't also apply to other instances
of this that I have noticed (calling dai_probe() after dai_get() ).

### CODE REVIEW

**Comment by paulstelian97** [comment]
The additional instances are removed within https://github.com/paulstelian97/sof/tree/dont_call_probe_after_get . Should I include those in this PR?

**Comment by dbaluta** [comment]
@paulstelian97 yes please do include them to get more feedback on why the probe was necessary after dai_get().

But please mind that dai_get() does call probe only when sref = 0.

**Comment by paulstelian97** [comment]
> @paulstelian97 yes please do include them to get more feedback on why the probe was necessary after dai_get().
> 
> But please mind that dai_get() does call probe only when sref = 0.

Yeah, but still if sref is >0 then probe was still called on ANOTHER call of dai_get. Will get them here.

**Comment by paulstelian97** [comment]
On-device test failures due to special case with BSW (ending test early because of hang). So this should be safe to merge once it receives the approvals.

**Pull request merged**
