### PR TITLE
smp: remove dedicated stacks for medium lvl interrupts

### PR DESCRIPTION
**Pull request by tlauda**
Removes dedicated stacks for medium lvl interrupts
as switching between different levels of irq doesn't
work correctly and requires more complicated
context switch implementation. We already have stack
per core used for runtime and level 1 interrupts and
currently its size is enough to also support other
irq levels (see UP arch).

Signed-off-by: Tomasz Lauda <tomasz.lauda@linux.intel.com>

### CODE REVIEW

**Comment by tlauda** [comment]
@lgirdwood It's totally xtensa arch specific. Won't IMX intoduce the separate arch?

**Comment by dbaluta** [comment]
@lgirdwood I'm not sure I can emit an opinion on this.

 I have looked for example inside our internal audio framework src/arch/xtensa/include/xtensa/xtruntime-frames.h file and the following snippet of code

```
STRUCT_BEGIN
STRUCT_FIELD(void*,4,XTOS_PTR_TO_,xtos_enabled)
STRUCT_FIELD(void*,4,XTOS_PTR_TO_,xtos_intstruct)
STRUCT_FIELD(void*,4,XTOS_PTR_TO_,xtos_interrupt_table)
STRUCT_FIELD(void*,4,XTOS_PTR_TO_,xtos_interrupt_mask_table)
STRUCT_FIELD(void*,4,XTOS_PTR_TO_,xtos_stack_for_interrupt_2)
STRUCT_FIELD(void*,4,XTOS_PTR_TO_,xtos_stack_for_interrupt_3)
STRUCT_FIELD(void*,4,XTOS_PTR_TO_,xtos_stack_for_interrupt_4)
STRUCT_FIELD(void*,4,XTOS_PTR_TO_,xtos_stack_for_interrupt_5)
STRUCT_END(xtos_structures_pointers)
```

simply doesn't exist. 

So, I assume we use the same stack for all IRQ prios (?).

**Comment by lgirdwood** [comment]
@dbaluta ok, if you dont have it then it's likely you dont need it. Fwiw, @tlauda has improved the xtensa HAL/xtos to fully support SMP so you will probably see some differences at HAL/xtos level compared to the legacy HAL/xtos.

**Comment by dbaluta** [comment]
> @dbaluta ok, if you dont have it then it's likely you dont need it. Fwiw, @tlauda has improved the xtensa HAL/xtos to fully support SMP so you will probably see some differences at HAL/xtos level compared to the legacy HAL/xtos.

I noticed the SMP part. For the moment all our Xtensa configurations are UP.

**Comment by dbaluta** [comment]
@tlauda all IMX boards so far use Xtensa DSPs with UP configuration.

**Comment by tlauda** [comment]
> @tlauda all IMX boards so far use Xtensa DSPs with UP configuration.

@ dbaluta Thanks for clarification.

**Comment by lgirdwood** [comment]
@dbaluta ok, UP is well supported atm on BYT, CHT, HSW and BDW.

**Pull request merged**
