### PR TITLE
Wov tplg updates

### PR DESCRIPTION
**Pull request by keyonjie**
This is the topology update needed for cml kwd feature:
1. add dmic16k PCM and dai for sof-cml-rt5682, this is companion with https://github.com/thesofproject/linux/pull/1035.
2. add a m4 file for cml kwd platforms.

### CODE REVIEW

**Comment by keyonjie** [comment]
please merge this with https://github.com/thesofproject/linux/pull/1035 together to avoid regression on sof-rt5682 platforms.

**Comment by plbossart** [comment]
the kernel PR needs more work.

**Comment by plbossart** [comment]
And if by upgrading the kernel we break userspace if they didn't update the topology file something is very wrong here. Sounds like an ABI change to me.

**Comment by jajanusz** [comment]
@plbossart I guess you meant you suspect some weird bug, because I didn't notice intentional ABI changes here.

**Comment by keyonjie** [comment]
> And if by upgrading the kernel we break userspace if they didn't update the topology file something is very wrong here. Sounds like an ABI change to me.

@plbossart good point here, actually I thought about this. This is actually alignment for topology file and machine driver(the BE dailink id changed), it do will break another one if we update one only, but I didn't want to bump ABI here as this may lead to infinite bumping of *SOF* ABI if customer's are updating their tplg/machine driver back and forth during developing. I also considered about moving this dmic16k BE dai_link to the end of the list to keep it backward compatible, but splitting dmic arrays looks somewhat odd to me.

I think the good thing here is that we can treat the machine driver here still in development(no formal customer release yet), so changing them to be the one that near the release version in one shot looks legit and is the easiest way to me. @plbossart what do you think about it?

**Comment by jajanusz** [comment]
@keyonjie 
```
08:55:36,896 INFO  - [ 6%] Generating sof-icl-rt5682.tplg
08:55:36,898 WARN  - ALSA lib conf.c:1877:(snd_config_load1) _toplevel_:3991:0:Unexpected char
08:55:36,898 WARN  - ALSA lib parser.c:250:(tplg_load_config) error: could not load configuration file sof-icl-rt5682.conf
08:55:36,898 WARN  - ALSA lib parser.c:328:(snd_tplg_build_file) error: failed to load topology file sof-icl-rt5682.conf
08:55:36,898 WARN  -
08:55:36,898 WARN  - failed to compile context sof-icl-rt5682.conf
```

**Comment by keyonjie** [comment]
> @keyonjie
> 
> ```
> 08:55:36,896 INFO  - [ 6%] Generating sof-icl-rt5682.tplg
> 08:55:36,898 WARN  - ALSA lib conf.c:1877:(snd_config_load1) _toplevel_:3991:0:Unexpected char
> 08:55:36,898 WARN  - ALSA lib parser.c:250:(tplg_load_config) error: could not load configuration file sof-icl-rt5682.conf
> 08:55:36,898 WARN  - ALSA lib parser.c:328:(snd_tplg_build_file) error: failed to load topology file sof-icl-rt5682.conf
> 08:55:36,898 WARN  -
> 08:55:36,898 WARN  - failed to compile context sof-icl-rt5682.conf
> ```

let me check, thanks.

**Comment by keyonjie** [comment]
@jajanusz it is because of api change, let me rebase to use the latest one.

**Comment by keyonjie** [comment]
@jajanusz fixed.

**Comment by lgirdwood** [comment]
@keyonjie can you link the kernel PR so we can check it's state.

**Comment by keyonjie** [comment]
> @keyonjie can you link the kernel PR so we can check it's state. EDIT,: I see it we are now merged. @plbossart so nothing blocking merge now ?

@lgirdwood here it is, merged:
https://github.com/thesofproject/linux/pull/1035

**Comment by keyonjie** [comment]
@lgirdwood @jajanusz please consider merge this ASAP as driver side is already merged to avoid mismatch.

**Comment by jajanusz** [comment]
> > And if by upgrading the kernel we break userspace if they didn't update the topology file something is very wrong here. Sounds like an ABI change to me.
> 
> @plbossart good point here, actually I thought about this. This is actually alignment for topology file and machine driver(the BE dailink id changed), it do will break another one if we update one only, but I didn't want to bump ABI here as this may lead to infinite bumping of _SOF_ ABI if customer's are updating their tplg/machine driver back and forth during developing. I also considered about moving this dmic16k BE dai_link to the end of the list to keep it backward compatible, but splitting dmic arrays looks somewhat odd to me.
> 
> I think the good thing here is that we can treat the machine driver here still in development(no formal customer release yet), so changing them to be the one that near the release version in one shot looks legit and is the easiest way to me. @plbossart what do you think about it?

@plbossart Need your input on that before merging.

**Pull request merged**
