### PR TITLE
xtensa-build-zephyr.py: stop calling west sign, rely on west build

### PR DESCRIPTION
**Pull request by marc-hb**
Move rimage parameters to `west config` instead of passing them to `west sign` directly.

Final part closing #6917

\+ 1 other commit. See commit messages.

### CODE REVIEW

**Comment by marc-hb** [comment]
https://github.com/thesofproject/sof/actions/runs/5074180192/jobs/9114081700?pr=7684 is known issue https://github.com/thesofproject/sof/pull/7675, work in progress

**Review by kv2019i — APPROVED** [review]
Looks great, thanks, just in time for v2.6.

**Comment by wszypelt** [comment]
SOFCI TEST

**Comment by marc-hb** [comment]
> Looks great, thanks, just in time for v2.6.

Apparently got beaten by a concurrent west.yml uprev, need to rebase.

> SOFCI TEST

Only sof-ci/jenkins (which I did NOT ask you about :-) cares about these magic keywords

> @marc-hb in python tests i see a problem with sdw ;/

Do you mean this below ? Totally different from quickbuild, should be fixed now.
- https://github.com/thesofproject/sof-test/pull/1039

https://sof-ci.01.org/sofpr/PR7684/build8467/devicetest/index.html
```
RMMOD	regmap_sdw
rmmod: ERROR: Module regmap_sdw is in use by: snd_soc_rt712_sdca_dmic snd_soc_rt712_sdca
```

**Comment by marc-hb** [comment]
Old IPC fuzzer failure https://github.com/thesofproject/sof/actions/runs/5083146240/jobs/9133786204?pr=7684 is known, will be fixed by 7675

**Comment by marc-hb** [comment]
Wow, https://sof-ci.01.org/sofpr/PR7684/build8556/devicetest/index.html is all green and https://sof-ci.01.org/sofpr/PR7684/build8555/devicetest is looking great too except for one MODEL missing.

Maybe Kai's #7660 is making an even bigger difference than expected?

**Review by juimonen — APPROVED** [review]

**Comment by kv2019i** [comment]
FYI @abonislawski @aborisovich . Looks good, proceeding with merge.

**Pull request merged**
