### PR TITLE
audio: base_fw: do not use platform interface for vendor extensions

### PR DESCRIPTION
**Pull request by kv2019i**
In commit 14c4e8675730 ("audio: base_fw: add platform layer to IPC4 hw_config data"), the platform specific code was moved to platform layer.

This commit implements a lighter weight abstraction for the moved code. Instead of using the platform layer, the Intel specific vendor code is added directly in base_fw_intel.c and guarded by a Kconfig. All other IPC4 build targets will use an empty implementation.

This avoids the need to add a platform definition for all IPC4 targets. The common implementation in base_fw.c is sufficient to cover all mandatory functionality required e.g. by the upstream SOF Linux driver's IPC4 implementation.

The interfaces are renamed to refer to "vendor" instead of "platform", to avoid any confusion with the platform layer with the new implementation.

### CODE REVIEW

**Comment by kv2019i** [comment]
For background, this is a follow-up agreed in https://github.com/thesofproject/sof/pull/9060#pullrequestreview-2014651135 

@lgirdwood more in line now? this requires addition of new build time conditionals (Kconfig in this PR) as we can't use the platform selection to choose the implemetnation, but given we only have two implementations, this is pretty light. If longterm, there are not going to be many build targets that need to variate this, this approach will be better. If we end up having customizations for majority of build targets, then (re)using platform layer would be better.

@thesofproject/nxp please chime in, you are the first non-intel target this affects.

**Comment by kv2019i** [comment]
V2:
- added on trivial patch to align indentationin src/audio/Kconfig in spirit of https://arstechnica.com/gadgets/2024/04/linus-torvalds-reiterates-his-tabs-versus-spaces-stance-with-a-kernel-trap/

**Comment by kv2019i** [comment]
CI fails are caused by https://github.com/thesofproject/sof/issues/9101 , rest are good. Waiting for reviews...

**Review by lyakh — APPROVED** [review]

**Review by gbernatxintel — APPROVED** [review]
Looks good to me

**Review by dnikodem — APPROVED** [review]

**Review by lgirdwood — APPROVED** [review]

**Pull request merged**
