### PR TITLE
zephyr: move lib-zephyr/cpu.c to toplevel zephyr/cpu.c

### PR DESCRIPTION
**Pull request by lgirdwood**
Further reduce the RTOS code specific locations to toplevel zephyr and xtos directories. The long term goal is that src/ will be generic code and RTOS abstractions will live in top level rtos directories.

This is a pure code move - no code changes except to Cmakefile.

Signed-off-by: Liam Girdwood <liam.r.girdwood@linux.intel.com>

### CODE REVIEW

**Comment by marc-hb** [comment]
Should we start having top-level subdirectories like `sof/zephyr/arch/cpu.c`? Before the top-level `sof/zephyr/` gets too crowded and too late.

**Review by iuliana-prodan — APPROVED** [review]

**Comment by lgirdwood** [comment]
> Should we start having top-level subdirectories like `sof/zephyr/arch/cpu.c`? Before the top-level `sof/zephyr/` gets too crowded and too late.

I'm fine with having a sof/zephyr/lib/ sof/zephyr/arch etc too (just want everything RTOS specific in one top level dir)

**Comment by lgirdwood** [comment]
> > Should we start having top-level subdirectories like `sof/zephyr/arch/cpu.c`? Before the top-level `sof/zephyr/` gets too crowded and too late.
> 
> I'm fine with having a sof/zephyr/lib/ sof/zephyr/arch etc too (just want everything RTOS specific in one top level dir)

@mmaka1 any comments  ?
@marcinszkudlinski I'm good to update this PR and move cpu.c to ```sof/zephyr/lib/cpu.c``` to classify this as Zephyr library code ?

**Comment by marcinszkudlinski** [comment]
sof/zephyr/lib looks fine to me

**Pull request closed without merging**
