### PR TITLE
topology: sof-adl-max98360a-rt5682-waves: add new topology

### PR DESCRIPTION
**Pull request by malik-hsu**
Add support for max98360a speaker amplifiers with waves function.

Signed-off-by: Malik_Hsu <malik_hsu@wistron.corp-partner.google.com>

### CODE REVIEW

**Comment by gkbldcig** [comment]
Can one of the admins verify this patch?

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by lgirdwood** [comment]
Try CI again, some recent faults have been fixed.

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by lgirdwood** [comment]
@malik-hsu can you force push this again. I think the CI has got stuck (there were some CI updates and this could have been pushed during the update). Lets try again. Thanks !

**Review by malik-hsu — COMMENTED** [review]
please review changes, thanks.

**Comment by lgirdwood** [comment]
@malik-hsu can you ```git rebase``` the PR, this removes the merge commit. Thanks

**Pull request closed without merging**
