### PR TITLE
rimage: mtl: add copier and eq-iir CPC cases

### PR DESCRIPTION
**Pull request by btian1**
Copier missed ibs(384)/obs(192) case, and eq-iir missed ibs(384)/obs(384) case, adding it to current CPC config.

### CODE REVIEW

**Review by kv2019i — APPROVED** [review]
Thank you @btian1 for fast update! Can you fix the commit prefix to "rimage: mtl: add copier and eq-iir CPC cases"

This will be racing with https://github.com/thesofproject/sof/pull/8490 , one needs to be udpated after another, FYI @lyakh

**Review by kv2019i — CHANGES_REQUESTED** [review]
Wrong button, adding request changes to fix the git commit.

**Comment by lgirdwood** [comment]
> Thank you @btian1 for fast update! Can you fix the commit prefix to "rimage: mtl: add copier and eq-iir CPC cases"
> 
> This will be racing with #8490 , one needs to be udpated after another, FYI @lyakh

@btian1  fyi TOML PR now merged

**Review by singalsu — APPROVED** [review]
Thanks! I can't decode the numbers in my head but looks assuring. Yep I know you got the numbers from tool so they are right :)

**Review by kv2019i — APPROVED** [review]
Thanks!

**Pull request merged**
