### PR TITLE
Tools: Topology2: Add nocodec topology to test google-rtc-aec

### PR DESCRIPTION
**Pull request by singalsu**
The first playback PCM is for AEC mic input via SSP0 LBM. The second playback PCM is for AEC reference via SSP2 LBM. The first capture PCM is the AEC output.

The AEC (mockup) can be run and tested with the topology like this:

$ aplay -Dhw:0,0 mic_clip.wav &
$ aplay -Dhw:0,2 ref_clip.wav &
$ arecord -Dhw:0,0 -f dat -d 10 output.wav

With AEC mockup version output.wav is mix of microphone and reference.

### CODE REVIEW

**Comment by ranj063** [comment]
@singalsu can we integrate the mock AEC into our regular nocodec tplg instead of this? That way we will be testing the 2 simultaneous capture DAIs configuration with our kernel

**Comment by singalsu** [comment]
> @singalsu can we integrate the mock AEC into our regular nocodec tplg instead of this? That way we will be testing the 2 simultaneous capture DAIs configuration with our kernel

I'd prefer to have this as well, this also goes to development directory only so it won't be relased. This is so simple that it can run in testbench by developers.

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
> > @singalsu can we integrate the mock AEC into our regular nocodec tplg instead of this? That way we will be testing the 2 simultaneous capture DAIs configuration with our kernel
> 
> I'd prefer to have this as well, this also goes to development directory only so it won't be relased. This is so simple that it can run in testbench by developers.
> 
> Also this approach is simple to extend for other formats like s32 that is being added to be able to check them all somehow.

If this is intended for testbench, we can name it or add commentary to state this.  The topology looks OK to me but needs @ranj063 to approve.

**Comment by lgirdwood** [comment]
@ranj063 good for you ?

**Review by RanderWang — APPROVED** [review]
4ch AEC is supported now, do you plan to support it ?

**Comment by singalsu** [comment]
> 4ch AEC is supported now, do you plan to support it ?

I did this to test the module conversion but it should be possible to create variants. Is the 4ch such that reference is 2ch, AEC is 4ch mic and 4ch out?

**Comment by RanderWang** [comment]
> > 4ch AEC is supported now, do you plan to support it ?
> 
> I did this to test the module conversion but it should be possible to create variants. Is the 4ch such that reference is 2ch, AEC is 4ch mic and 4ch out?

we need 4ch ref.

**Comment by plbossart** [comment]
@RanderWang @singalsu can we clarify the comments above? The echo reference cannot have more channels than what is actually rendered? The number of channels in the echo reference is not correlated with the number of channels in the microphone input, and it's not clear how reference channels might be created out of thin air?

**Comment by singalsu** [comment]
Yep, 4ch reference would make sense only with four separate speakers channels, not even 2-way stereo with woofer & tweeter should normally require such.

**Comment by RanderWang** [comment]
> @RanderWang @singalsu can we clarify the comments above? The echo reference cannot have more channels than what is actually rendered? The number of channels in the echo reference is not correlated with the number of channels in the microphone input, and it's not clear how reference channels might be created out of thin air?

Sure we only need 2ch ref. We support 4ch dmic  https://github.com/thesofproject/sof/commit/351fe7e3efa66e4d468290938eb018459a508029 so I mentioned it.

**Comment by RanderWang** [comment]
> @ranj063 ping?
> 
> Others, @RanderWang @singalsu is this ready to go or not? It's hard to tell when you press approve but have comments asking for changes. :)

sure, it is ready for me

**Comment by lgirdwood** [comment]
4 channels can be added incrementally.

**Pull request merged**
