### PR TITLE
[MTL-003-drop stable] Removed sof-logger

### PR DESCRIPTION
**Pull request by aborisovich**
Sof logger is used for legacy platforms and is not used for Meteorlake.
Static analysis tool issued many errors related to the logger - removed the project.

Signed-off-by: Andrey Borisovich <andrey.borisovich@intel.com>

### CODE REVIEW

**Comment by aborisovich** [comment]
What is going on on the CI? `West clone` fails to clone Zephyr?

**Comment by aborisovich** [comment]
Builds correctly MTL on local setup with `python sof\scripts\xtensa-build-zephyr.py mtl`. Something is fishy with failing Zephyr build here...

**Comment by paulstelian97** [comment]
I'm going to still ask (but not block) if going out of sync with main for this reason is really what you want. People from Intel can take this into consideration and approve anyway (in which case I'll just say go ahead). I believe I brought this up in a previous PR as well.

**Comment by lgirdwood** [comment]
@aborisovich fwiw, the logger static analysis issues fixed in main, you can cherry-pick now if needed and drop this ?

**Comment by aborisovich** [comment]
> @aborisovich fwiw, the logger static analysis issues fixed in main, you can cherry-pick now if needed and drop this ?

Well I saw that commit and from my perspective it does not fix all the issues with logger. You can compare pr that went to main to PR I created on MTL002 and closed. There were also file access issues like not calling fclose in some situations. I'll make experimental run with main cherry pick.

**Comment by marcinszkudlinski** [comment]
Not a part of MTL release. Copying static analysis issue status (not an issue) from TGL release

**Pull request closed without merging**
