### PR TITLE
More coding style fixes

### PR DESCRIPTION
**Pull request by crazoes**

### CODE REVIEW

**Comment by paulstelian97** [comment]
PR titles like "Patch2" that aren't descriptive aren't a good idea. I edited it, the commits themselves are alright.

**Comment by crazoes** [comment]
> PR titles like "Patch2" that aren't descriptive aren't a good idea. I edited it, the commits themselves are alright.

Sorry, that happened by mistake. Thanks for changing it

**Comment by crazoes** [comment]
> @crazoes you already had the first patch in #2602?

yes. I am not sure why it came back again in this new branch which I created :(

**Comment by lgirdwood** [comment]
Both patches fine, can you remove the duplicate.

**Comment by plbossart** [comment]
> > @crazoes you already had the first patch in #2602?
> 
> yes. I am not sure why it came back again in this new branch which I created :(

probably because your branch was created on top of the previous commit. Just to a git rebase --interactive HEAD~2 and remove the first commit, then force push.

**Comment by crazoes** [comment]
> > > @crazoes you already had the first patch in #2602?
> > 
> > 
> > yes. I am not sure why it came back again in this new branch which I created :(
> 
> probably because your branch was created on top of the previous commit. Just to a git rebase --interactive HEAD~2 and remove the first commit, then force push.

Thanks @plbossart 
@lgirdwood I have removed the duplicate one.

**Pull request merged**
