### PR TITLE
ipc4: invalidate HOSTBOX for comp_new

### PR DESCRIPTION
**Pull request by abonislawski**
This will allow to remove invalidate calls for each component init

### CODE REVIEW

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
@abonislawski looks like CI failed, not sure why as it's not running IPC4 check yet ?

**Review by ranj063 — APPROVED** [review]

**Comment by abonislawski** [comment]
> looks like CI failed, not sure why as it's not running IPC4 check yet ?

Not sure, at the moment ipc4 build is broken on main anyway, can we rerun?

**Comment by lgirdwood** [comment]
@wszypelt @kkarask could someone check CI, may need a reboot ?

**Comment by kkarask** [comment]
@lgirdwood We have some platform issue today and queue to rebuild is longer than usual.

**Comment by lgirdwood** [comment]
CI unrelated.

**Pull request merged**
