### PR TITLE
Tgl 013 drop stable hot fix

### PR DESCRIPTION
**Pull request by keyonjie**
back port memory management fixes from the main branch.

### CODE REVIEW

**Comment by lgirdwood** [comment]
@mwasko fyi - just to make sure this is on your radar.

**Comment by lgirdwood** [comment]
@keyonjie are some of these back ported from main ? Do some still need merged into main ?

**Comment by keyonjie** [comment]
> @keyonjie are some of these back ported from main ? Do some still need merged into main ?

yes, besides of https://github.com/thesofproject/sof/pull/4521 and https://github.com/thesofproject/sof/issues/4568, one new added commit (memory: tigerlake: use bigger buffer zone on TGL-U/LP) needed for the main branch also, I am waiting #4521 and #4568 got merged first, then the last PR to enlarge the buffer zone will be submitted on top of that on platforms including TGL-U/LP.

**Comment by lgirdwood** [comment]
@mwasko @bkokoszx can you guys review here for tgl-013 ? Please merge if you approve for tgl 013.

**Comment by mwasko** [comment]
> @mwasko @bkokoszx can you guys review here for tgl-013 ? Please merge if you approve for tgl 013.

@lgirdwood we are waiting for FW full scope validation. As soon as we get the positive (hopefully) results I will proceed with the merge.

**Review by mwasko — APPROVED** [review]

**Pull request merged**
