### PR TITLE
[WIP][RFC]mux: make mux/demux produce zeros in paused state

### PR DESCRIPTION
**Pull request by juimonen**
Align mux/demux with mixer implementation.

Signed-off-by: Jaska Uimonen <jaska.uimonen@intel.com>

### CODE REVIEW

**Comment by juimonen** [comment]
@plbossart absolutely not tested at all, will continue/test tomorrow

**Comment by lgirdwood** [comment]
@juimonen ping

**Comment by juimonen** [comment]
@lgirdwood @plbossart I was thinking that this would help, but my initial tests didn't make any difference to current functionality -> I think we have a "feature" in the scheduler not to schedule this pipeline in paused state -> doesn't matter if it produces zeros or not.

**Comment by lgirdwood** [comment]
@juimonen I'm going to hold off here until we have your rules ready.

**Pull request closed without merging**
