### PR TITLE
cavs: clk: add Kconfig option to select default ro clock

### PR DESCRIPTION
**Pull request by lbetlej**
The change allows to select at a configuration time default clock for
cavs 2.x platforms (Icelake, Jasperlake, Tigerlake) on top of already enabled
support for cavs 1.8. By default the LP clock is set (120 MHz - platform
dependent). In case of workloads that require HP clock (400 MHz) system
integrator shall select the right clock as a part of FW configuration
process.

Signed-off-by: Lech Betlej <lech.betlej@linux.intel.com>

### CODE REVIEW

**Comment by lbetlej** [comment]
@lgirdwood The rationale is that this will work as a canary (alarm) to indicate problems with FW components implementation. If for quite simple use cases w/o 3rd party modules there are observed xruns then we need to review component implementation. I'm aware that power wise the rule of thumb is to use the highest clock possible (except some corner cases like keyword detection scenario) and that would be product recommended configuration. @mmaka1 is working on infrastructure support for measurements of compute utilization at a component granularity .

**Comment by jajanusz** [comment]
@lbetlej please change kConfig to Kconfig in commit message

**Comment by lgirdwood** [comment]
@lbetlej ok, sounds good - btw can you wrap the complex macros with (). checkpatch is complaining.

**Comment by jajanusz** [comment]
"Internal Intel CI System/merge/build" - red cos of known issue with test, it's ok, good to merge

**Pull request merged**
