### PR TITLE
[STABLE-v2.2] topology1: tgl: add Waves-integrated topology builds

### PR DESCRIPTION
**Pull request by johnylin76**
Adds topology builds with Waves codec integrated for Intel TGL Google devices.

### CODE REVIEW

**Review by cujomalainey — APPROVED** [review]

**Comment by cujomalainey** [comment]
@johnylin76 these are cherry picks from main right?

**Comment by marc-hb** [comment]
@cujomalainey I don't about this specifically but I know that most (if not all) Intel topology1 has been deleted from the main branch.

**Comment by johnylin76** [comment]
That's correct. topology1 is no longer lived on mainstream. From my understanding the branch `stable-v2.2` plays the role of mainstream for IPC3 platform builds, e.g. `cavs2.5-001-drop-stable`, so the attempt is first-landing on `stable-v2.2`, then cherry-picking on `cavs2.5-001-drop-stable`.

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
Internal CI west is not used on stable -v2.2 branch so can be ignored.

**Pull request merged**
