### PR TITLE
Enable BT Offload for Intel ADL devices

### PR DESCRIPTION
**Pull request by brentlu**
Enable BT offload pipeline for following two topologies:
1. sof-adl-max98360a-rt5682-2way.tplg
2. sof-adl-max98360a-rt5682-4ch.tplg

Will work with ODM later to enable the coreboot and ucm part.

### CODE REVIEW

**Comment by lgirdwood** [comment]
@kv2019i @juimonen

**Review by cujomalainey — COMMENTED** [review]
do all platforms that ship these topologies use BT offload or just some?

**Review by plbossart — APPROVED** [review]
Approving with the understanding that these devices have BT offload enabled in their Linux machine drivers. Can you confirm @brentlu ?

**Review by lgirdwood — APPROVED** [review]

**Comment by brentlu** [comment]
> do all platforms that ship these topologies use BT offload or just some?

Right now only one Chrome project is using this topology. We will enable it since the feature is available and can improve some power consumption.

**Comment by brentlu** [comment]
> Approving with the understanding that these devices have BT offload enabled in their Linux machine drivers. Can you confirm @brentlu ?

Yes, I tested it on a Chrome device. The machine driver is sof_rt5682.c

	{
		.name = "adl_mx98360_rt5682",
		.driver_data = (kernel_ulong_t)(SOF_RT5682_MCLK_EN |
					SOF_RT5682_SSP_CODEC(0) |
					SOF_SPEAKER_AMP_PRESENT |
					SOF_MAX98360A_SPEAKER_AMP_PRESENT |
					SOF_RT5682_SSP_AMP(1) |
					SOF_RT5682_NUM_HDMIDEV(4) |
					SOF_BT_OFFLOAD_SSP(2) |
					SOF_SSP_BT_OFFLOAD_PRESENT),
	},

**Review by kv2019i — APPROVED** [review]

**Pull request merged**
