### PR TITLE
west.yml: upgrade rimage to d32db50

### PR DESCRIPTION
**Pull request by keqiaozhang**
Pull in following rimage changes:

d32db50 mtl: add Aria module to extended manifest
5bc2010 rimage: fix build error
35bc644 mtl: add eq-iir and fir support
6fad356 rimage: Removed hash context from image structure
6c7a151 hash: Remove old hash functions
d258ea2 manifest: pkcs1_5: Use new hash functions
2bd8be3 hash: New hash functions
93c5e8b misc_utils: Move byte_swap function to new misc_utils.c file
9ce1cc8 ext_manifest: Fix fw_ext_man_cavs_header version
a4ca53c toml_utils: Adding support for decimal numbers in hex parser
5ebbd65 rimage: use hex number
36c0c90 elf: Use the get_file_size function
98c7f7b manifest: Use the get_file_size function
6a64cb9 file_utils: Add a new get_file_size function
055ea7e file_utils: manifest: ext_manifest: Add new create_file_name function
fed69d4 toml_utils: adsp_config: Moved generic parser functions to toml_utils
0931d9c main: heap_adsp release fix
3aa199f config: mtl: set init_config for micsel
d48ad6b adsp_config: add dump for init_config
ffd0542 adsp_config: make the default value zero for init_config
cb9c880 config: tgl-cavs: add kpb, selector and kd support
bf23b5e config: mtl: set KDTEST module_type to 8

### CODE REVIEW

**Comment by keqiaozhang** [comment]
Test passed:https://sof-ci.ostc.intel.com/#/result/planresultdetail/21709.  This can fix issue https://github.com/thesofproject/sof/issues/7204

**Review by kv2019i — APPROVED** [review]

**Comment by kv2019i** [comment]
Hmm,  KD test is failing on MTL in Internal Intel CI (quickbuild 11552526 ).

Could the problem be in https://github.com/thesofproject/rimage/pull/119 .. @libinyang ?

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by marc-hb** [comment]
> SOFCI TEST

https://sof-ci.01.org/sofpr/PR7220/build4371/devicetest/index.html passed again.

SOFCI TEST does not restart quickbuild but someone did? https://sof-ci.01.org/sof-pr-viewer/#/build/PR7220/build11552447 is still failing.


I checked the logs on the internal site but once again the logs are empty, there's only:


```
21:37:08,979 ERROR - Step 'master>SCANS>TESTS>TRIGGER PYTHON SMOKE_IPC4 TESTS' is failed:
Step is failed since the triggered build is failed, cancelled, or timed out.
```

and nothing else.


@mwasko , @aborisovich , @wszypelt we cannot make any progress with empty test logs, this is not sustainable.

**Review by marc-hb — APPROVED** [review]

**Review by softwarecki — APPROVED** [review]

**Comment by wszypelt** [comment]
@marc-hb today I'm checking how data is transferred to sof-ci, I'll try to fix it today. as for the logs from the internal site, it seems to me that you looked in the wrong place, I managed to find information about timeout '''07:36:44,663 INFO - E TimeoutError: FW status on IPC timeout after 5.0 seconds: 07:36:44,663 INFO - E FW status: 0x00000005 07:36:44,663 INFO - E Last error code: 0x00000000 (ADSP_SUCCESS)''' if I can't fix the automatic log forwarding today, I'll send those interested at the end of the day instructions to check the logs manually.

**Comment by wszypelt** [comment]
@keqiaozhang @marc-hb I'm not sure why, but this time after a manual rebuild, the tests passed correctly, but it doesn't change my plans today to fix the test logs

**Comment by kv2019i** [comment]
Thanks @wszypelt ! This was important to unblock daily testing again.

**Pull request merged**
