### PR TITLE
rimage: Update to version with toml devices description

### PR DESCRIPTION
**Pull request by ktrzcinx**
This allow to add new platform with old version of rimage tool.

Signed-off-by: Karol Trzcinski <karolx.trzcinski@linux.intel.com>

Test for https://github.com/thesofproject/rimage/pull/21
Linked to private rimage repo for testing purpose.

### CODE REVIEW

**Comment by lgirdwood** [comment]
@ktrzcinx can you check CI - looks like a crash
```
 Total pages text 36 data 14 bss 62 module file limit: 0x36000
Firmware completing manifest v1.5
 meta: completing ADSP manifest
Segmentation fault (core dumped)
src/arch/xtensa/CMakeFiles/run_rimage.dir/build.make:57: recipe for target 'src/arch/xtensa/CMakeFiles/run_rimage' failed
make[3]: *** [src/arch/xtensa/CMakeFiles/run_rimage] Error 139
CMakeFiles/Makefile2:1504: recipe for target 'src/arch/xtensa/CMakeFiles/run_rimage.dir/all' failed
make[2]: *** [src/arch/xtensa/CMakeFiles/run_rimage.dir/all] Error 2
CMakeFiles/Makefile2:1624: recipe for target 'src/arch/xtensa/CMakeFiles/bin.dir/rule' failed
make[1]: *** [src/arch/xtensa/CMakeFiles/bin.dir/rule] Error 2
Makefile:658: recipe for target 'bin' failed
```

**Comment by ktrzcinx** [comment]
Yea, it's quite suspicious because manifest fields in old and new way of platform defining are identical, so there shouldn't be any difference in the following steps. Interesting.

**Comment by lgirdwood** [comment]
@ktrzcinx do you think this should be fixable for tomorrow before lunchtime. Will try and get this in v1.6 too sine it's a nice and notable feature.

**Comment by ktrzcinx** [comment]
@lgirdwood builds are green, after merges in rimage repo I change referenced commit hash here and it should be ready to go

**Comment by lgirdwood** [comment]
@zrombel are you able to update QB today with --recursive flag for git submodules ?

**Comment by ktrzcinx** [comment]
Link changed to thesofproject/rimage repo

**Comment by lgirdwood** [comment]
@ktrzcinx thanks - btw let me know if QB update is in progress or not for today.

**Comment by ktrzcinx** [comment]
@lgirdwood it's should be done within a while, @zrombel currently re-run build after applying changes.

**Comment by ktrzcinx** [comment]
@lgirdwood QB already send build results - pass

**Review by lgirdwood — APPROVED** [review]

**Pull request merged**
