### PR TITLE
topology: Update tplg file name for tgl system with max98373-rt5682

### PR DESCRIPTION
**Pull request by sathya-nujella**
Changed the tplg file name in kernel driver according to Maintainers
feedback. So, topology file name here needs the corresponding change.

As part of the below PR, Pierre suggested us to change the name:
https://github.com/thesofproject/linux/pull/2345

### CODE REVIEW

**Review by ranj063 — APPROVED** [review]

**Comment by plbossart** [comment]
in https://github.com/thesofproject/linux/pull/2345#issuecomment-671443663 I suggested that all the configurations start with the codec first and then the amp. Here there's only one line that is changed, it's inconsistent.

**Comment by keyonjie** [comment]
@sathya-nujella so we are generating 2 tplg files: sof-tgl-max98373-rt5682(should be sof-tgl-rt5682-ssp0-max98373-ssp1?) and sof-tgl-rt5682-ssp0-max98373-ssp2, are they both used by machine driver?

**Comment by sathya-nujella** [comment]
> in [thesofproject/linux#2345 (comment)](https://github.com/thesofproject/linux/pull/2345#issuecomment-671443663) I suggested that all the configurations start with the codec first and then the amp. Here there's only one line that is changed, it's inconsistent.

Hi @plbossart 
Yes, wanted to change all tplg's as per your suggestion.. but I see different ODM's in different phases. So, I was worried if we do now and co-coordinating will be a problem with many of them. As this tplg is specifically for new board, I added this only.
Is it ok to do this change alone now and later do all changes for others. Thanks!

**Comment by sathya-nujella** [comment]
> @sathya-nujella so we are generating 2 tplg files: sof-tgl-max98373-rt5682(should be sof-tgl-rt5682-ssp0-max98373-ssp1?) and sof-tgl-rt5682-ssp0-max98373-ssp2, are they both used by machine driver?

ODM's are in different phases. So, for existing ones do not want to change for now. Please suggest if ok for now.. only do for newer ones.

**Review by keyonjie — APPROVED** [review]
Since it is already merged on the driver side, agree to go with this now.

**Comment by lgirdwood** [comment]
@sathya-nujella can you create a BUG for changing the remaining topologies after ODM alignment and link the issue # here. I will merge now for v1.6 but we will need the updates after ODM work is done here.

**Comment by sathya-nujella** [comment]
> @sathya-nujella can you create a BUG for changing the remaining topologies after ODM alignment and link the issue # here. I will merge now for v1.6 but we will need the updates after ODM work is done here.

sure @lrgirdwo , thanks!

**Pull request merged**
