### PR TITLE
Add $SOF_CC_BASE variable for building XTOS with clang-based, Cadence toolchains

### PR DESCRIPTION
**Pull request by marc-hb**
As required by ACP_7_0 addition submitted in #9351

Other related cleanups, see commit messages.

Switch rebuild-testbench.sh to new variable.

### CODE REVIEW

**Comment by marc-hb** [comment]
There is a synchronization outage following some VM migration (internal issue DIO 18204) but I checked the test results on the internal site and they are all fine, just the known LNL failures and that's it.

**Comment by marc-hb** [comment]
@lrudyX , @wszypelt there was some network problem in https://sof-ci.01.org/sof-pr-viewer/#/build/PR9358/build14153658 for "Copy build to DUT?DUT_CONFIG=LNL)"

```
15:31:01,392 INFO  -   Started : Sunday, August 11, 2024 12:30:39 AM
15:31:01,392 INFO  - 2024/08/11 00:31:01 ERROR 53 (0x00000035) Getting File System Type of Destination \\10.B.C.D\Builds\pull-9358-merge_2209331\
15:31:01,392 INFO  - The network path was not found.
15:31:01,392 INFO  -
15:31:01,392 INFO  -    Source : D:\qba1\workspace\44988\pull-9358-merge_2209331\INSTALL\
15:31:01,392 INFO  -      Dest - \\10.B.C.D\Builds\pull-9358-merge_2209331\
```

The LNL build was fine so this is not related:
```
15:25:08,967 INFO  - in current dir: /buildagent/workspace/24733; running command:
15:25:08,967 INFO  -     /root/xtensa/XtDevTools/install/tools/RI-2022.10-linux/XtensaTools/bin/xt-objcopy --remove-section .comment /buildagent/workspace/24733/build-lnl/zephyr/main-stripped.mod /buildagent/workspace/24733/build-sof-staging/sof-info/lnl/stripped-main.elf
15:25:10,526 INFO  - build-sof-staging  
15:25:10,526 INFO  - |-- sof  
15:25:10,526 INFO  - |   +-- intel  
15:25:10,526 INFO  - |       |-- sof-ipc4  
15:25:10,526 INFO  - |       |   +-- lnl  
15:25:10,526 INFO  - |       |       +-- community  
15:25:10,526 INFO  - |       |           +-- sof-lnl.ri      sha256=4951abf4024a2ead52d85579844439c90cd83831058ea3db9770dd852a1ad787
15:25:10,526 INFO  - |       +-- sof-ipc4-lib  
15:25:10,526 INFO  - |           +-- lnl  
15:25:10,526 INFO  - |               +-- community  
15:25:10,526 INFO  - |                   |-- B36EE4DA-006F-47F9-A06D-FECBE2D8B6CE.bin  -> drc.llext 
15:25:10,526 INFO  - |                   +-- drc.llext      sha256=45ec1eb6e0dd2827424505e9c46bbe6c89079a67d14ced5605867a715cd72a97
```

**Comment by wszypelt** [comment]
@marc-hb Unfortunately, there was an error with the LNL machine, the tests are being repeated now

**Review by saisurya-ch — APPROVED** [review]
works fine with all compilers for AMD platforms.

**Review by kv2019i — APPROVED** [review]

**Pull request merged**
