### PR TITLE
Rename panic() and increase timestamp accuracy in SOF Zephyr build

### PR DESCRIPTION
**Pull request by kv2019i**
Fixes https://github.com/thesofproject/sof/issues/6617

### CODE REVIEW

**Review by iuliana-prodan — APPROVED** [review]

**Comment by greg-intel** [comment]
SOFCI TEST

**Review by RanderWang — APPROVED** [review]

**Review by lgirdwood — APPROVED** [review]
@kv2019i are you saying long term Zephyr panic needs extended to support arch/platfom specific logic ?

**Comment by lgirdwood** [comment]
@kv2019i could be a build problem.

**Review by dbaluta — APPROVED** [review]

**Comment by kv2019i** [comment]
@lgirdwood We are good with Zephyr panic. There's actually infra to plug any custom app specific panic handling to Zephyr and one thing we do need to do with SOF is to plug a "send panic IPC on panic" handler. But othewire, we are good with Zephyr panic. One alternative would be to change everybody to use k_panic() directly (and skip the sof_panic() intermediate). I now went for sof_panic() instead to keep the PR simpler.

**Comment by lgirdwood** [comment]
@kv2019i ok, we can do k_panic after v2.4 stable branch is done.

**Comment by kv2019i** [comment]
V2 update:
- all build issues hopefully addressed now

**Comment by kv2019i** [comment]
V3 update:
- ok, so V2 wasn't even close to building, I missed the XTOS IPC3 build in my local test
- there's one remianing checkpatch error but this is existing warning in the code

**Pull request merged**
