### PR TITLE
installer: change default destination to /lib/firmware/updates

### PR DESCRIPTION
**Pull request by marc-hb**
Kudos to Pierre-Louis for advertising this cool feature

Signed-off-by: Marc Herbert <marc.herbert@intel.com>

### CODE REVIEW

**Comment by marc-hb** [comment]
The doxygen failure at https://github.com/thesofproject/sof/pull/4020/checks?check_run_id=2309363054 is of course unrelated, fix in progress in PR 4010.

**Review by fredoh9 — APPROVED** [review]
Looks good. Thank you for quick update.

**Review by lgirdwood — APPROVED** [review]

**Comment by marc-hb** [comment]
Ouch, I just realized this is not compatible with `sof-test` which has `/lib/firmware/` hardcoded in a few places. I would usually submit a revert but:
- The very simple "workaround" is of course to have the `/lib/firmware/intel/` location configured in `installer/config.mk` and then everything works fine again.
- In the all default configuration, the installer now fails with a very clear error message stating that `/lib/firmware/updates/ directory must exist` which draws attention on `installer/config.mk`
- Other potential errors include the logger complaining about a mismatch which is pointing the user in the right direction too.

So I'm tempted not to revert and focus on adding sof-test support for `/lib/firmware/updates/` instead. Thoughts?

**Comment by lgirdwood** [comment]
> So I'm tempted not to revert and focus on adding sof-test support for `/lib/firmware/updates/` instead. Thoughts? EDIT: [thesofproject/sof-test#645](https://github.com/thesofproject/sof-test/pull/645)

Ack, please fix in sof-test and / or CI.

**Comment by plbossart** [comment]
@marc-hb I am not convinced it's such a great idea to hard-code this 'updates' path as the default
What happens if a distribution uses this 'updates' path as their default as well? that would remove the possibility of installing files that have precedence over the default path.
not to mention that there are other cases with even more precedence https://www.kernel.org/doc/html/latest/driver-api/firmware/fw_search_path.html

Should this be based on a command-line parameter or an environment variable?

**Comment by marc-hb** [comment]
> @marc-hb I am not convinced it's such a great idea to hard-code this 'updates' path as the default

This PR did change the default destination but it didn't "hardcode" anything. The sample config.mk file lists a small number of variables and one of them invites the user to change the destination.

> Should this be based on a command-line parameter or an environment variable?

Both should already work, see below. If not please let me know.
```shell
FW_DESTDIR=dut.local:/lib/firmware/something make -C installer/ ...
# or
make -C installer/ FW_DESTDIR=dut.local:/lib/firmware/something ...
```

> What happens if a distribution uses this 'updates' path as their default as well?

https://www.kernel.org/doc/html/latest/driver-api/firmware/fw_search_path.html is short on guidelines and recommendations but I don't see why a distribution would start to use `updates`. As I understand it `updates` is designed to override something else without having to (re)move it; why would a distribution want to override _themselves_? I don't think they'd want to use it for "firmware version control" because version control with only two versions version1 and version2 is very limiting; what happens when version3 is released? Rotate like log files? In that world I think it's more typical to download and re-install an older `.deb` or `.rpm` package.

> not to mention that there are other cases with even more precedence

I'm guessing that the `UTS_RELEASE` subdirectory in `/lib/firmware/*/UTS_RELEASE/` is designed to help with ABI incompatibilities between kernel and firmware versions (hi @kv2019i) so that seems IMHO off-topic in this CI and development context.

**Comment by cujomalainey** [comment]
@plbossart if you are truly worried about a distro accidentally using the updates path we could utilize the sysfs path `/sys/module/firmware_class/parameters/path` and udev rules to inject the new path before the driver loads. We should keep the udev rule outside the installer but well documented. That would avoid any possible loading of paths that are considered test.

**Comment by plbossart** [comment]
Marc's scripts has a command line option so I am not too worried any longer. I mean, someone will screw-up eventually, but it'll be their fault and not the script designer's ;-)

**Comment by marc-hb** [comment]
Note if a distro uses `/updates`/ then our current deployment and test scripts will be "defeated" on it already :-/

(a reminder that we validate only Ubuntu for now, WIP)

**Comment by marc-hb** [comment]
A completely different alternative spotted by @plbossart : udev. Example:

https://chromium-review.googlesource.com/c/chromiumos/overlays/board-overlays/+/2786610/3/overlay-volteer/chromeos-base/chromeos-bsp-volteer/files/udev/79-sof-dmic.rules

```
SUBSYSTEM=="pci", ATTR{vendor}=="0x8086", etc. etc., \
  RUN+="/sbin/modprobe snd_sof_pci tplg_path=intel/sof-tplg-test"
```

 -------

What all these seem to miss badly: `request_firmware()` recording in the logs the exact location of every firmware that "taints" the kernel. It should do this at a high log level, that seems like a pretty basic security requirement.

I always keep this hack in my workspace:
```diff
diff --git a/drivers/base/firmware_loader/main.c b/drivers/base/firmware_loader/main.c
index 78355095e00d..f4cd48b6e4bf 100644
--- a/drivers/base/firmware_loader/main.c
+++ b/drivers/base/firmware_loader/main.c
@@ -840,6 +840,10 @@ _request_firmware(const struct firmware **firmware_p, const char *name,
                fw = NULL;
        }
 
+       dev_info(device, "XXXX MARC %s firmware=%s, ret=%d\n",
+                __func__, name, ret);
+
        *firmware_p = fw;
        return ret;
 }
```

**Comment by plbossart** [comment]
credits to @cujomalainey for the pointer on what Chome does, I was only the messenger.

**Comment by cujomalainey** [comment]
True credits go to @dtor :+1:

**Pull request merged**
