### PR TITLE
coherent: WIP: poison the uncache alias when object is locked.

### PR DESCRIPTION
**Pull request by lgirdwood**
Have a Kconfig option that will poison uncache alias and lock cache lines of a coherent object.

The intention is to

1) crash any deref of the uncache alias when its locked 
2) detect any uncache changes made when locked.

We cannot yet check any reuse of local cache alias after release as it means keeping lines locked.

Signed-off-by: Liam Girdwood <liam.r.girdwood@linux.intel.com>

### CODE REVIEW

**Comment by lgirdwood** [comment]
@kv2019i @lyakh @mwasko @nashif @cujomalainey - all, thinking we can have some basic cache poisoning option on our platforms. This is a high level application level implementation (and would need a Kconfig), but would also be good to have a low level checker too. 

This PR is WIP and it's missing some cache locking APIs for Zephyr support. @lyakh - heads up, I may need you to help finish this or to prove it does not work (as this is based on my understanding of the xtensa manual).

**Review by lyakh — COMMENTED** [review]
Looks like it could be done in principle. This would only work on objects, actually shared between cores, marked as shared, of course.
BTW, thinking about this, maybe another way to debug the coherent API would be to mark all such objects as shared to force the use of locking and cache synchronisation for each object on each access.

**Comment by lgirdwood** [comment]
> Looks like it could be done in principle. This would only work on objects, actually shared between cores, marked as shared, of course. BTW, thinking about this, maybe another way to debug the coherent API would be to mark all such objects as shared to force the use of locking and cache synchronisation for each object on each access.

Locking has perf impact as we cant evict cache lines for other users. I suspect this Kconfig option will also slow down FW where we may not be able to reach high MCPS..

**Comment by mwasko** [comment]
@marcinszkudlinski fyi

**Comment by lyakh** [comment]
> > Looks like it could be done in principle. This would only work on objects, actually shared between cores, marked as shared, of course. BTW, thinking about this, maybe another way to debug the coherent API would be to mark all such objects as shared to force the use of locking and cache synchronisation for each object on each access.
> 
> Locking has perf impact as we cant evict cache lines for other users. I suspect this Kconfig option will also slow down FW where we may not be able to reach high MCPS..

@lgirdwood oh, of course, sorry, I should've mentioned - only as a debug option. As a debug option you'd be able to mark all coherent API objects as shared to check if that breaks anything.

**Comment by lgirdwood** [comment]
> @lgirdwood oh, of course, sorry, I should've mentioned - only as a debug option. As a debug option you'd be able to mark all coherent API objects as shared to check if that breaks anything.

Absolutely - that could be an extra Kconfig debug. This would then blow up (and give us an assert()) if anyone attempted to use an unlocked cache object.

**Comment by lgirdwood** [comment]
@marcinszkudlinski fwiw, the Zephyr team are working on a new cache API that we can use to do stuff like this. You may want to align with @nashif for details (and search for the upstream Zephyr cache PR to comment and review).

**Pull request closed without merging**
