### PR TITLE
Add Waves codec into adl-003-drop-stable branch

### PR DESCRIPTION
**Pull request by CyKuei**
Add Waves codec into adl-003-drop-stable branch

Add Waves override config for tigerlake_chrome.
Enable codec_adapter and Waves codec.

Signed-off-by: CY Kuei <cyk@waves.com>

### CODE REVIEW

**Comment by sofci** [comment]
Can one of the admins verify this patch?
> reply **test&nbsp;this&nbsp;please** to run this test once

**Comment by CyKuei** [comment]
There's already a PR requesting an override config for the main branch, please refer to:
https://github.com/thesofproject/sof/pull/4954

**Comment by gkbldcig** [comment]
Can one of the admins verify this patch?

**Comment by lgirdwood** [comment]
test this please

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by lgirdwood** [comment]
@CyKuei look like the CI run correctly, rerunning it. I dont usually see testbench failures with topology updates. Please check the test results if the same results persist.

**Review by cujomalainey — APPROVED** [review]

**Comment by CyKuei** [comment]
Can someone merge this PR? This override config already existed in the main branch:
https://github.com/thesofproject/sof/commit/94517163580d666fa8fa62b96f5de24dbf70008c
Thanks.

**Pull request merged**
