### PR TITLE
logger: use fopen binary mode

### PR DESCRIPTION
**Pull request by bkokoszx**
Signed-off-by: Bartosz Kokoszko <bartoszx.kokoszko@linux.intel.com>

### CODE REVIEW

**Comment by lyakh** [comment]
according to the fopen(3) man page https://linux.die.net/man/3/fopen "the 'b' is ignored on all POSIX conforming systems, including Linux." Are we building on any non POSIX-conforming systems?

**Comment by lyakh** [comment]
sorry, closed by mistake :-/

**Comment by lyakh** [comment]
hm, seems to be for windows builds, ok, nm, sorry for the noise

**Comment by bkokoszx** [comment]
@lyakh 
Yes, here is a PR #914  :)

**Pull request merged**
