### PR TITLE
west: test rimage with only ssl 3 support

### PR DESCRIPTION
**Pull request by juimonen**
Test rimage version that supports only ssl 3 upwards.

### CODE REVIEW

**Comment by marc-hb** [comment]
https://github.com/thesofproject/sof/actions/runs/4701641680/jobs/8337938948?pr=7444 fails because (among others?) https://github.com/zephyrproject-rtos/docker-image/pkgs/container/zephyr-build is still based on Ubuntu 20.04

**Comment by marc-hb** [comment]
https://sof-ci.01.org/sofpr/PR7444/build5899/build/mtl_zph_ipc4_error.txt should be more recent but it fails the same

**Comment by juimonen** [comment]
SOFCI TEST

**Comment by gkbldcig** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
