### PR TITLE
[SKIP CI] Minor docker-run.sh fixes

### PR DESCRIPTION
**Pull request by marc-hb**
See commit messages.

Fixes recent #6232

### CODE REVIEW

**Comment by marc-hb** [comment]
I'm really puzzled by the **many** (and unrelated) testbench memory corruptions reported by valgrind in https://github.com/thesofproject/sof/runs/8141544041

I tried both Ubuntu 20 and 22 and I could not reproduce the ... @singalsu,  @pjdobrowolski any idea? How multithreaded and non-deterministic is this?

Only recent change I see that _could_ be related is library manager
- #5796

```
==19983== Thread 3:
==19983== Invalid read of size 1
==19983==    at 0x5FD5E9C: fprintf (stdio2.h:105)
==19983==    by 0x5FD5E9C: module_adapter_copy (module_adapter.c:599)
==19983==    by 0x486BF09: pipeline_for_each_comp (pipeline-graph.c:453)
==19983==    by 0x486CB4F: pipeline_comp_copy (pipeline-stream.c:101)
==19983==    by 0x486CB4F: pipeline_copy (pipeline-stream.c:139)
==19983==    by 0x486E487: pipeline_task (pipeline-schedule.c:203)
==19983==    by 0x4861C45: ll_thread (ll_schedule.c:131)
==19983==    by 0x4951B42: start_thread (pthread_create.c:442)
==19983==    by 0x49E2BB3: clone (clone.S:100)
```

```
==19983== Invalid read of size 8
==19983==    at 0x5FD53F8: module_adapter_copy (module_adapter.c:606)
==19983==    by 0x486BF09: pipeline_for_each_comp (pipeline-graph.c:453)
==19983==    by 0x486CB4F: pipeline_comp_copy (pipeline-stream.c:101)
==19983==    by 0x486CB4F: pipeline_copy (pipeline-stream.c:139)
==19983==    by 0x486E487: pipeline_task (pipeline-schedule.c:203)
==19983==    by 0x4861C45: ll_thread (ll_schedule.c:131)
==19983==    by 0x4951B42: start_thread (pthread_create.c:442)
==19983==    by 0x49E2BB3: clone (clone.S:100)

\+ many more.

```

**Comment by marc-hb** [comment]
And now re-run https://github.com/thesofproject/sof/runs/8142429253 is passing. Scary.

**Comment by pjdobrowolski** [comment]
@marc-hb library manager won't work unless it is turned on. I will look at this...

**Comment by lgirdwood** [comment]
@ranj063 please see the valgrind warning above, could be a race as it's occasional. It may need a ```if()``` check in the code.

**Comment by pjdobrowolski** [comment]
@marc-hb after short analysis failure is caused by not freeing comp https://github.com/thesofproject/sof/runs/8141544041#step:6:585 what leads to memory corruption. Issue is not related to library_manager, similar problem with freeing modules was being fixed on UpDownMixer however I'm not sure if it is connected. From my perspective issue is on TGL machine. FYI @jxstelter

**Comment by lgirdwood** [comment]
@wszypelt @lrudyX good to merge ? Not expecting docker update to fail a DMIC test ?

**Review by lgirdwood — APPROVED** [review]

**Comment by wszypelt** [comment]
@lgirdwood To be sure, I turned on the tests again

**Comment by marc-hb** [comment]
> @marc-hb after short analysis failure is caused by not freeing comp https://github.com/thesofproject/sof/runs/8141544041#step:6:585 what leads to memory corruption.

Thanks @pjdobrowolski for the preliminary analysis. Would you be able to go one extra step and `git blame` the corresponding code?

Also, does it look like a race to you?

**Pull request merged**
