### PR TITLE
audio: add UT_STATIC to crossover and smart_amp

### PR DESCRIPTION
**Pull request by kv2019i**
Still a few component in main without UT_STATIC.

### CODE REVIEW

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
@kv2019i looks like a fuzzer build error
```
[ 14%] Building C object CMakeFiles/sof.dir/src/ipc/helper-ipc3.c.o
[ 15%] Building C object src/audio/CMakeFiles/sof_multiband_drc_fma.dir/crossover/crossover.c.o
[ 15%] Building C object src/audio/CMakeFiles/sof_eq-fir_avx2.dir/eq_fir/eq_fir_generic.c.o
/home/runner/work/sof/sof/src/audio/crossover/crossover.c:871:10: error: expected ‘;’ before ‘void’
  871 | UT_STATIC void sys_comp_crossover_init(void)
      |          ^~~~~
      |          ;
/home/runner/work/sof/sof/src/audio/crossover/crossover.c:871:16: error: no previous prototype for ‘sys_comp_crossover_init’ [-Werror=missing-prototypes]
  871 | UT_STATIC void sys_comp_crossover_init(void)
      |                ^~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[6]: *** [src/audio/CMakeFiles/sof_multiband_drc_fma.dir/build.make:107: src/audio/CMakeFiles/sof_multiband_drc_fma.dir/crossover/crossover.c.o] Error 1
make[5]: *** [CMakeFiles/Makefile2:738: src/audio/CMakeFiles/sof_multiband_drc_fma.dir/all] Error 2
```

**Comment by marc-hb** [comment]
It looks like UT_STATIC is not defined in this case.

To reproduce copy/paste the commands in `.github/workflows/scant_fuzzer.yml`.

Note @cujomalainey is working on proper fuzzer build in #4132

**Comment by marc-hb** [comment]
Just found that `src/audio/crossover/crossover.c` is not compiled in any default configuration! So maybe the fuzzer build is just the messenger, I mean nothing fuzzer-specific in this failure.

**Comment by cujomalainey** [comment]
My hope is to turn the fuzzer build into also a `make allyesconfig` build (as much as possible at least without platform specific code). My guess is likely this is just missing the header since this was code from an intern and therefore no UTs were written.

**Comment by kv2019i** [comment]
Ok, fixed the issue now. Even if crossover is not part of UT tests yet, better to align the declarations with the rest of the components.

We do need to come back to the UT_STATIC definition. It's no longer just about UT, so sof/ut.h doesn't make as much sense anymore. E.g. we use this for non-UT zephyr builds as well. So this should be turned into a more generic macro how one declare a component init function.

**Review by cujomalainey — APPROVED** [review]

**Comment by kv2019i** [comment]
@marc-hb wrote:
> Is this explained somewhere in the source?

No, but if you check git history for UT_STATIC, it's pretty obvious.

> I'm also wondering how you came to this crossover change, did that involve Zephyr? It was clearly not when trying to unit test it...

I found a few issues with the Zephyr build (and fixed them). Then I was curious why this had slipped through the cracks and did a grep of the whole codebase, to all component init calls. Crossover and the smart-amp were the only component inits without UT_STATIC, so thus this patch.

**Review by marc-hb — APPROVED** [review]
> No, but if you check git history for UT_STATIC, it's pretty obvious.

Wait, that sounds like... work? :-)

> did a grep of the whole codebase, to all component init calls. 

That too!

More seriously: a couple comments in `ut.h` (or any better place) would not hurt. I (ab)use git history all the time but it should IMHO not be required for information like this.

**Pull request merged**
