### PR TITLE
app: boards: intel boards, disable winstream console

### PR DESCRIPTION
**Pull request by kv2019i**
Disable CONFIG_WINSTREAM_CONSOLE in all Intel configs that enable SOF mtrace for logging. Also disable CONFIG_LOG_BACKEND_ADSP that uses winstream as backend. No need to have two memory window based logging backends enabled at the same time.

### CODE REVIEW

**Comment by kv2019i** [comment]
FYI @tobonex and @jsarha , I know you are working with related changes touching the debug window/slot configuration. This gets rid of one user of window3. Note that Zephyr unit tests still rely on winstream console and the location of the buffer is hardcoded in many places.

**Comment by kv2019i** [comment]
@tobonex @lyakh @marcinszkudlinski @jsarha .. ping?

**Review by lyakh — APPROVED** [review]

**Comment by tobonex** [comment]
If it just removes some content from memory window 3 then it probably won't affect my changes.

**Review by jsarha — APPROVED** [review]
Fine by me, if nobody uses it.

**Pull request merged**
