### PR TITLE
[Don't Merge] Dell Olympic MIC LED support

### PR DESCRIPTION
**Pull request by libinyang**
Please don't merge.
Patches for Dell Olympic MIC LED support

### CODE REVIEW

**Comment by plbossart** [comment]
this branch should really be using the high-pass filter we added to remove the capture DC component.

**Comment by lgirdwood** [comment]
@libinyang please also align with @singalsu on the correct topology filters to use.

**Comment by gkbldcig** [comment]
Can one of the admins verify this patch?

**Comment by lgirdwood** [comment]
@libinyang is this PR still valid ?

**Comment by libinyang** [comment]
@lgirdwood This patch has already been merged into the master. I will close it.

**Pull request closed without merging**
