### PR TITLE
Stable v1.9 refine

### PR DESCRIPTION
**Pull request by libinyang**
Add the support for NO MIC platforms.

The previous PR missed some patches when backing port, which caused compile failure.
Revert the patches and resubmit them.

This PR passes the compile and the BE ID matches expectation.

### CODE REVIEW

**Review by lgirdwood — APPROVED** [review]
@libinyang pls let me know when this backport PR is validated.

**Comment by libinyang** [comment]
@lgirdwood As the CI system fails build the old tplg, I built the tplg and trigger the CI system manually. The test passes.

**Comment by marc-hb** [comment]
Topologies build fix submitted in #5632

**Comment by marc-hb** [comment]
It's impossible to find what exactly fails to build in https://github.com/thesofproject/sof/runs/5717552879 and others. 


Fixed by small but impactful change #5640, please review.

**Pull request merged**
