### PR TITLE
selector: fix priv data passed wrong issue

### PR DESCRIPTION
**Pull request by keyonjie**
We should get config data of selector component from priv data of
process component, here correct it.

Signed-off-by: Keyon Jie <yang.jie@linux.intel.com>

### CODE REVIEW

**Comment by ranj063** [comment]
@keyonjie the changes look good but we encapsulate the kcontrol binary data with the ABI header and check for ABI compatibility but we dont seem to care about the ABI here. Should we?

**Comment by keyonjie** [comment]
@ranj063 I didn't add any ABI compatibility check at this PR yet, we only aim to fix issues and make it go forward. I closed another PR which bumping the ABI version, I plan to settle down and finalize all the interface for KWD and then do the ABI updates in one shot.

**Comment by ranj063** [comment]
@keyonjie ok let's add a comment to check for ABI so it doesn't get forgotten

**Comment by lgirdwood** [comment]
@keyonjie can you check CI scan.

**Comment by lgirdwood** [comment]
@keyonjie merge is pending CI scan here, cant merge until it passes.

**Comment by lgirdwood** [comment]
@keyonjie @michalgrodzicki confirms CI scan passes so good to merge.

**Pull request merged**
