### PR TITLE
scripts: xtensa-build-all: fix TGL build with customized key

### PR DESCRIPTION
**Pull request by xiulipan**
When use MEU as sign tool, PRIVATE_KEK_OPTION should also use
MEU_PRIVATE_KEY.

Signed-off-by: Pan Xiuli <xiuli.pan@linux.intel.com>

### CODE REVIEW

**Review by marc-hb — CHANGES_REQUESTED** [review]
This commit is called "fix TGL build with custom key" but people  are _already_ building TGL with custom keys! I think you missed the discussion in https://github.com/thesofproject/sof/pull/3187#issuecomment-696273531
I'm not blaming you: that discussion was long and confusing!

The long story short: the `-k` option should not be used with MEU. That's because `-k` would require more code in this script (not just this line) to support MEU correctly. Use `-m` and the new, pass-through environment variable instead as shown in https://github.com/thesofproject/sof/pull/3187#issuecomment-696273531
```
PRIVATE_KEY_OPTION='-DMEU_PRIVATE_KEY=...'  ./xtensa-build-all.sh ...
```
I will submit a `print_usage()` fix instead.

**Comment by marc-hb** [comment]
> I will submit a print_usage() fix instead.

Done in #3512 3512

**Comment by xiulipan** [comment]
@marc-hb Oh, I did not notice the method you provide, but my fix here can solve the situation with. Could you have a try?

**Comment by marc-hb** [comment]
I don't think a "unified" method using the same RIMAGE_PRIVATE_KEY name for both rimage and MEU is a good idea. I think `-k` was never a good idea and should be deprecated, see #3512 why.

**Pull request closed without merging**
