### PR TITLE
Make SOF works with bluetooth on imx8ulp

### PR DESCRIPTION
**Pull request by TangleZ**

### CODE REVIEW

**Review by paulstelian97 — COMMENTED** [review]
Is imx8ulp only used with Bluetooth? We don't want to break other existing configurations.

**Comment by TangleZ** [comment]
@paulstelian97 Yes, it only connected to Bluetooth.

**Review by dbaluta — APPROVED** [review]

**Comment by dbaluta** [comment]
I'm OK with this patches. We need to have a better look at support SAI dynamic configuration in Q4.

**Comment by dbaluta** [comment]
@TangleZ please always check and fix trivial checkpatch.pl errors.

Right now we have:

```
WARNING: 'configration' may be misspelled - perhaps 'configuration'?
```

**Review by paulstelian97 — APPROVED** [review]

**Pull request merged**
