### PR TITLE
Audio: Google RTC Audio Proc: fixed repeated word

### PR DESCRIPTION
**Pull request by LaurentiuM1234**
This makes code easier to read and fixes checkpatch.pl warning:
WARNING: Possible repeated word: 'on'

Signed-off-by: Laurentiu Mihalcea <laurentiu.mihalcea@nxp.com>

### CODE REVIEW

**Comment by sofci** [comment]
Can one of the admins verify this patch?
> reply **test&nbsp;this&nbsp;please** to run this test once

**Comment by gkbldcig** [comment]
Can one of the admins verify this patch?

**Comment by dbaluta** [comment]
thanks @LaurentiuM1234 !

@lgirdwood can you please add Laurentiu to SOF Developers. He started last week at NXP as an intern!

**Review by dbaluta — APPROVED** [review]

**Comment by dbaluta** [comment]
test this please

**Comment by dbaluta** [comment]
SOFCI TEST

**Review by paulstelian97 — APPROVED** [review]

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
@wszypelt looks like CI may be stuck. Can you unblock. Thanks.

**Comment by lgirdwood** [comment]
@LaurentiuM1234 pls see email - I've sent project invite that will help with CI. @dbaluta I guess you will add @LaurentiuM1234 to the NXP team. Thanks.

**Comment by wszypelt** [comment]
@lgirdwood Sure, testing in progress

**Pull request merged**
