### PR TITLE
Audio: SRC: Add IPC4 full conversions matrix

### PR DESCRIPTION
**Pull request by singalsu**

### CODE REVIEW

**Review by lgirdwood — COMMENTED** [review]
Can you say what the SRC differences are in the commit message.

**Comment by marcinszkudlinski** [comment]
@kfrydryx please take a look

**Comment by kfrydryx** [comment]
@singalsu @marcinszkudlinski Are those coefficient generated with -1dB gain? As far as I know this is supposed to mitigate distortion on full scale signals? For ipc4 version we'd need the output amplitude to match the input one.

**Comment by singalsu** [comment]
> @singalsu @marcinszkudlinski Are those coefficient generated with -1dB gain? As far as I know this is supposed to mitigate distortion on full scale signals? For ipc4 version we'd need the output amplitude to match the input one.

Yes, same 1 dB attenuation. The -1 dB attenuation was result from subjective tests in our team with challenging CD material. The problem is common to all SRCs where signal is reconstructed at new rate. The loudness war in music has created for recording engineers tools for making sound loud. E:g. tool called SOX for rate conversions warns of clipping with same material that we used to test.

In theory if the passband ripple is 0.1 dB (+/- 0.05 dB) or 0.2 dB in two-stage conversions the attenuation could be 0.05 dB or 0.1 dB while ensuring that steady-state full-scale sine wave does not clip. If I would set the gain to 0 dB exactly some frequencies where gain is 0 - 0.05 dB would distort a bit.

I would be OK to have 0.05 dB attenuation. But there's the risk with some music material since there's no soft-clipping in SRC. If fractional value of raw output sample is |x| > 1 it is limited to 1 or -1. Would that be an OK compromise? In SOF the user can at least set the PGAs in FW to avoid the SRC to clip.

**Comment by marcinszkudlinski** [comment]
@singalsu 
we do need to have SRC without any attenuation, at least for IPC4. 
As you said, ripple is no more than  0.2dB, that can be easily handled by sample clipping and it is completely acceptable. We just need to ensure that it is done properly - I mean when output sample exceeds 0dBFS it is clipped to 0dBFS (not to some negative numbers etc.)
SRC module for closed source firmware (windows) works in the same way - 0dB att and sample clipping.

**Comment by sys-pt1s** [comment]
Can one of the admins verify this patch?

**Comment by singalsu** [comment]
> @singalsu we do need to have SRC without any attenuation, at least for IPC4. As you said, ripple is no more than 0.2dB, that can be easily handled by sample clipping and it is completely acceptable. We just need to ensure that it is done properly - I mean when output sample exceeds 0dBFS it is clipped to 0dBFS (not to some negative numbers etc.) SRC module for closed source firmware (windows) works in the same way - 0dB att and sample clipping.

OK, I'll recompute the coefficients for exact 0 dB gain (means passband can be -ripple..+ripple). But there needs to be some other component in processing before SRC that attenuates the signal to get clean playback with any content. Modern music is mixed to full scale and even above (exceed full scale when reconstructed).

**Comment by singalsu** [comment]
@marcinszkudlinski Here's an example of a filter, the 0 dB gain is at 0 Hz point. The ripple in the passband is not symmetrical around 0 dB with this filter type (kaiser). Please let me know if still OK.

image

**Comment by marcinszkudlinski** [comment]
@singalsu 
Yes, the FIR model is fine.
I undestand that there may be clipping when a modern music pushed to 0dBFS (or even higher with a soft clip limiters that utilizes inter-sample peaks - like PSP Audioware Xenon or Waves L3), yet it should be handled by a pipeline construction - by putting a -1dB gain module just before resampling. 
SRC is going to be used in a variety of places, not only in a main sound stream but also in a number of sidechains, like providing a reference signal for echo cancellation etc. 1dB att will likely lead to incorrect results.

**Comment by marcinszkudlinski** [comment]
BTW:
The "good practices" for mastering engineer is to limit up to -0.2dBFS, just because many poor DACs cannot handle 0FS without distortion
even waves L3 presets suggest this
image

**Comment by singalsu** [comment]
> The "good practices" for mastering engineer is to limit up to -0.2dBFS, just because many poor DACs cannot handle 0FS without distortion

Yep, my development device UP2 + HifiBerry DAC+ has this issue, it rattles with some music clips. I hope the worst examples of too loud mixing are past with better mastering tools like your example!

I'll turn this PR to proposal now. The needed SRC bug fixes PR is now merged.

**Review by lgirdwood — APPROVED** [review]

**Pull request merged**
