### PR TITLE
[RFC] Topology for synchronize playback

### PR DESCRIPTION
**Pull request by bardliao**
The PR is to implement a topology for synchronize playback. We use demux to duplicate audio data for two DAIs. I need people's input for the two HACK commits. 

@slawblauciak Could you check the "set alh channel = 2 by default" commit?

### CODE REVIEW

**Comment by slawblauciak** [comment]
@bkokoszx the hack in question seems to involve the PCM params mechanism, which you introduced. I'm not sure how exactly that is supposed to work, does it look alright to you?

**Comment by bardliao** [comment]
> so you could just create a new m4 file with different coeffs...? I think you are not doing anything bad with this as probably no one is using this atm, but the correct way would be just to create new m4 with new coeffs (just pipeline ids changed).

Yes, I could create a new m4 with different coeffs. But can we define a macro or something to use demux_coef_default.m4 with correct pipeline ids? So we don't need to maintain one more demux_coef m4 with the same coeffs.

**Comment by juimonen** [comment]
@bardliao creating binary hex blobs with m4 could be hairy.... but maybe doable. I would create a tool for the demux to generate the blobs. Like we have for eq's in matlab/octave scripts. This could be python or C. Just changing the pipeline id's in existing blob sounds like a hack. Actually I don't know why pipelineID's need to be defined explicitly for demux conncetions (isn't this embedded in the graph anyway?)

**Comment by bardliao** [comment]
> Actually I don't know why pipelineID's need to be defined explicitly for demux conncetions (isn't this embedded in the graph anyway?)

I have the same question. But I don't know if FW can get the graph or not.

**Comment by lgirdwood** [comment]
@bardliao can you split this into several PR's once you are happy with it. i.e. we need a sepearet discussion/PRs for the HACK patches.

**Comment by bardliao** [comment]
> @bardliao can you split this into several PR's once you are happy with it. i.e. we need a separate discussion/PRs for the HACK patches.

Yes, split it to #2539 #2540 #2541 and #2542

**Pull request closed without merging**
