### PR TITLE
xtensa-build-zephyr: add support to build with xtensa XCC

### PR DESCRIPTION
**Pull request by kv2019i**
Add support to build with XCC compiler by setting XTENSA_TOOLS_ROOT
env variable. The interface follows xtensa-build-all.sh, so existing
CI scripts for SOF builds can easily update to build with XCC.

Signed-off-by: Kai Vehmanen <kai.vehmanen@linux.intel.com>

### CODE REVIEW

**Comment by kv2019i** [comment]
Following Zephyr PR is needed to successfully complete the XCC build (one recent regressions in Zephyr main):
https://github.com/zephyrproject-rtos/zephyr/pull/37580

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
@kv2019i can you check, is this intentional ?
```
-- Found west (found suitable version "0.11.1", minimum required is "0.7.1")
-- Board: intel_adsp_cavs25
-- Cache files will be written to: /srv/home/jenkins/.cache/zephyr
-- Found dtc: /usr/bin/dtc (found suitable version "1.5.0", minimum required is "1.4.6")
-- Found toolchain: xcc (/srv/home/jenkins/xcc)
CMake Error at /srv/home/jenkins/workspace/sof_generic_build/zephyrproject/zephyr/cmake/compiler/xcc/generic.cmake:8 (message):
  Zephyr was unable to find the toolchain.  Is the environment misconfigured?

  User-configuration:

  ZEPHYR_TOOLCHAIN_VARIANT: xcc
```

**Comment by kv2019i** [comment]
@lgirdwood We may need to hold off a bit, I'm discussing with @aiChaoSONG  and @keqiaozhang  on the failure. They explained the current build script does not set XCC toolchain variable. But it is unknown at this point, why the build still goes to this path (and then fails when no proper toolchain is set). 

The Zephyr side PR was just merged, so we just need to address the jenkins build issue and then we are good to go.

**Comment by aiChaoSONG** [comment]
@kv2019i You can first test this on your local machine. Normally, CI servers have XCC tool chain and zephyr tool chain installed just as your development machine.Once it worked on your local machine, you can share what you have configured, and we can add it to CI easily

**Comment by kv2019i** [comment]
@aiChaoSONG wrote:
> Edit: if it already worked with several env variable setup, we can start the CI config now.

Ack, I did test this locally and confirmed I can switch between gcc (using Zephyr SDK 0.13) and xcc by setting XTENSA_TOOLS_ROOT, XTENSAD_LICENSE_FILE and nothing else.

I also checked that "set |grep XT" shows no other variables set.

```
$ export XTENSA_TOOLS_ROOT=/home/kvehmane/xtensa/XtDevTools
$ ./scripts/xtensa-build-zephyr.sh tgl-h 
...
-- Using toolchain: zephyr 0.13.0 (/home/kvehmane/zephyr-sdk)
-- Found dtc: /home/kvehmane/zephyr-sdk/sysroots/x86_64-pokysdk-linux/usr/bin/dtc (found suitable version "1.6.0", minimum required is "1.4.6")
-- Found toolchain: xcc (/home/kvehmane/xtensa)
[...]
-- The C compiler identification is GNU 4.2.0
-- The CXX compiler identification is GNU 4.2.0
-- The ASM compiler identification is unknown
-- Found assembler: /home/kvehmane/xtensa/XtDevTools/install/tools/RG-2017.8-linux/XtensaTools/bin/xt-xcc
```

And gcc:
```
$ unset XTENSA_TOOLS_ROOT
$ ./scripts/xtensa-build-zephyr.sh tgl-h 
-- Using toolchain: zephyr 0.13.0 (/home/kvehmane/zephyr-sdk)
-- Found dtc: /home/kvehmane/zephyr-sdk/sysroots/x86_64-pokysdk-linux/usr/bin/dtc (found suitable version "1.6.0", minimum required is "1.4.6")
8...]
-- The C compiler identification is GNU 10.3.0
-- The CXX compiler identification is GNU 10.3.0
-- The ASM compiler identification is GNU
```

I also tested with "export XTENSA_TOOLS_ROOT=" and works as well (selects gcc as it should).

**Comment by kv2019i** [comment]
Uh, sorry, @aiChaoSONG , I found at least one bug in my PR. WIll update this PR later today.

**Comment by kv2019i** [comment]
Hmm, still no success. I've now double-checked locally and it should be good now. Can you @aiChaoSONG  try manual on a CI machine and check what happens? Maybe the env variables are wrong (see my comment above showing the env variables I used in my local test).

**Comment by lgirdwood** [comment]
@aiChaoSONG any update here ?

**Comment by aiChaoSONG** [comment]
> @aiChaoSONG any update here ?

As Kai have validate the change locally, I think we can merge the PR first, CI support will be next. CI folks are fully occupied by other key features and bug fix, include me.

**Comment by lgirdwood** [comment]
Thank @aiChaoSONG got you. Now merged for CI developers.

**Comment by aiChaoSONG** [comment]
@kv2019i  CI servers don't have UI, so we write a script to install xcc toolchain to ~/xcc, so CI will do `export XTENSA_TOOLS_ROOT=$(eval echo ~$USER)/xcc`. could you please do a quick fix to support this option, too?

The `XtDevTools` option should also be supported, because this is where developers install xcc
```
xcc
├── install
    ├── builds
    └── tools
```

**Comment by aiChaoSONG** [comment]
@kv2019i  With this change, I can manually build zephyr SOF with xcc toolchain in CI environment, but jenkins report failed, seems there is a CI bug, I am looking into it, before it can be resolved, I will let CI build gcc version.

**Comment by kv2019i** [comment]
@aiChaoSONG wrote:
> @kv2019i CI servers don't have UI, so we write a script to install xcc toolchain to ~/xcc, so CI will do export 
> XTENSA_TOOLS_ROOT=$(eval echo ~$USER)/xcc. could you please do a quick fix to support this option, too?

Ack, I'll make a PR for this.

**Comment by aiChaoSONG** [comment]
@kv2019i I add a link like this, everything is good, too. If you find it hard or tedious to support `~/xcc` and  `XtDevTools` in the build script, we can have the link as the workaround in CI.
```
xcc
├── install
└── XtDevTools -> .
```

**Pull request merged**
