### PR TITLE
zephyr: use system cache API

### PR DESCRIPTION
**Pull request by kv2019i**
Use zephyr cache APIs instead of xtensa specific ones.

### CODE REVIEW

**Comment by kv2019i** [comment]
Refers to a unmerged pull request, so marking as DNM -> https://github.com/zephyrproject-rtos/zephyr/pull/57298

**Comment by marc-hb** [comment]
https://github.com/thesofproject/sof/actions/runs/4810733024/jobs/8563770147?pr=7520 still complains about `implicit declaration of function 'sys_cache_data_flush_and_invd_all'` because  `zmain` checks ignore the manifest by design and https://github.com/zephyrproject-rtos/zephyr/pull/57298 is not merged yet. So this is expected.

All the `manifest` checks are compiling which is great.

**Comment by greg-intel** [comment]
SOFCI TEST

**Comment by marc-hb** [comment]
Only a couple suspend/resume failures in https://sof-ci.01.org/sofpr/PR7520/build6601/devicetest/index.html

https://sof-ci.01.org/sofpr/PR7520/build6602/devicetest and everything else is all green.

Ship it!

**Review by ranj063 — APPROVED** [review]

**Review by andyross — APPROVED** [review]

**Review by tmleman — APPROVED** [review]

**Pull request merged**
