### PR TITLE
zephyr: Test zephyr pr affecting SoF

### PR DESCRIPTION
**Pull request by ceolin**
Test Zephyr #70394 pr on SoF CI.

### CODE REVIEW

**Comment by ceolin** [comment]
DO NOT MERGE :)

**Comment by lyakh** [comment]
> Can one of the admins verify this patch?
> 
> > reply **test this please** to run this test once

test this please

**Comment by kv2019i** [comment]
@marc-hb I think this highlights a practical problem in running Zephyr PRs through SOF is that the CI results are not so easy to parse at the moment. IOW you need SOF maintainer help. It's still a net win to have this PR from SOF point of view, so I' glad to help parse the reports, but I worry how this scales to something that can be done by "any Zephyr developer".

@ceolin The on-device results in "sof-ci/jenkins" look good. There are failures but this are known issues in CI infra now.

I have no idea why the "Internal Intel CI" have not reported anything back. @wszypelt ?

**Comment by marc-hb** [comment]
>  IOW you need SOF maintainer help. It's still a net win to have this PR from SOF point of view, so I' glad to help parse the reports, but I worry how this scales to something that can be done by "any Zephyr developer".

Yes our validation has issues. I hope the answer is not less validation.

**Comment by wszypelt** [comment]
@kv2019i The issue needs to be investigated. Now I have manually queued the build and tests, the results should be available within 40 minutes

**Comment by marc-hb** [comment]
>  IOW you need SOF maintainer help. It's still a net win to have this PR from SOF point of view, so I' glad to help parse the reports, 

Agreed 200%: it's still a huge win compared to trying to bisecting and debugging a Zephyr change that was merged (and... forgotten) 2 or 3 weeks ago.

> but I worry how this scales to something that can be done by "any Zephyr developer".

This does not have to scale to "any Zephyr developer" but only to any developer who makes _Audio DSP changes in Zephyr_. 90% of these are also SOF developers anyway, so it's only the matter of helping the 10% left (e.g.: @ceolin) with decyphering failures.

It would be great to have too many developers and an actual scalability issue. Let's talk if/when we get there

Of course it's also the matter of having fewer failures in the first place - but which sane developer would not want that anyway in 2024? https://www.martinfowler.com/articles/continuousIntegration.html#FixBrokenBuildsImmediately

**Comment by ceolin** [comment]
Thank you folks ! The original pr was merged. Closing this one.

**Pull request closed without merging**
