### PR TITLE
topology: sof-adl-rt5682: backport to adl-003-drop-stable branch

### PR DESCRIPTION
**Pull request by brentlu**
Backport topology to adl-003-drop-stable branch for chrome devices. Has been tested by ODM.

### CODE REVIEW

**Comment by brentlu** [comment]
Mainline PR: https://github.com/thesofproject/sof/pull/5218

**Review by cujomalainey — APPROVED** [review]

**Comment by cujomalainey** [comment]
also hit adl-004

**Comment by lgirdwood** [comment]
@mwasko fyi

**Comment by brentlu** [comment]
ADL already migrated to adl-004-drop-stable so drop this PR.

**Pull request closed without merging**
