### PR TITLE
NEX topology changes for v2.8.1 release

### PR DESCRIPTION
**Pull request by CBala21**

### CODE REVIEW

**Comment by lgirdwood** [comment]
@CBala21 I assume these are all in the main branch and this is a cherry-pick ?

**Comment by kv2019i** [comment]
@CBala21 Can you cherry-pick with "cherry-pick -x" so that the commit-id where these come from is visible in the git commit message?

**Comment by CBala21** [comment]
> @CBala21 Can you cherry-pick with "cherry-pick -x" so that the commit-id where these come from is visible in the git commit message? (example here https://github.com/thesofproject/sof/pull/8858/commits )

@kv2019i : Do you want to create the new PR with the option you have suggested?

**Comment by CBala21** [comment]
Closing this PR and Please continue with new PR #8873

**Pull request closed without merging**
