### PR TITLE
codec_adapter: correct the way to get the scheduling period

### PR DESCRIPTION
**Pull request by CyKuei**
Scheduling period should be acquired from dev->pipeline->period

Signed-off-by: CY Kuei <cyk@waves.com>

### CODE REVIEW

**Comment by sofci** [comment]
Can one of the admins verify this patch?
> reply **test&nbsp;this&nbsp;please** to run this test once

**Comment by gkbldcig** [comment]
Can one of the admins verify this patch?

**Comment by lyakh** [comment]
test this please

**Review by lgirdwood — APPROVED** [review]
@mwasko fyi non topology backport from main.

**Pull request merged**
