### PR TITLE
Unify setup and runtime config in DTS related topology

### PR DESCRIPTION
**Pull request by joechengxperi**
Following PR#5190 to unify setup and runtime in DTS related topologies.

### CODE REVIEW

**Review by dbaluta — APPROVED** [review]

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
@joechengxperi can you check the topology compile
```
/usr/bin/make -f topology/topology1/CMakeFiles/topology1_sof-rn-rt5682-rt1019-dts.dir/build.make topology/topology1/CMakeFiles/topology1_sof-rn-rt5682-rt1019-dts.dir/build
make[2]: Entering directory '/home/sof/work/sof.git/tools/build_tools'
[ 13%] Generating production/sof-rn-rt5682-rt1019-dts.conf
cd /home/sof/work/sof.git/tools/build_tools/topology/topology1 && m4 --fatal-warnings "-DDTS=\`DTS'" -I /home/sof/work/sof.git/tools/topology/topology1/m4 -I /home/sof/work/sof.git/tools/topology/topology1/common -I /home/sof/work/sof.git/tools/topology/topology1/platform/common -I /home/sof/work/sof.git/tools/topology/topology1 -I /home/sof/work/sof.git/tools/build_tools/topology/topology1 /home/sof/work/sof.git/tools/topology/topology1/common/abi.m4 /home/sof/work/sof.git/tools/topology/topology1/sof-rn-rt5682-rt1019.m4 > production/sof-rn-rt5682-rt1019-dts.conf
[ 13%] Generating production/sof-rn-rt5682-rt1019-dts.tplg
cd /home/sof/work/sof.git/tools/build_tools/topology/topology1 && alsatplg ${VERBOSE:+-v 1} -c production/sof-rn-rt5682-rt1019-dts.conf -o production/sof-rn-rt5682-rt1019-dts.tplg
ALSA lib pcm.c:1471:(tplg_parse_hw_config) deprecated bclk value 'codec_slave', use 'codec_consumer'
ALSA lib pcm.c:1523:(tplg_parse_hw_config) deprecated fsync value 'codec_slave', use 'codec_consumer'
ALSA lib dapm.c:158:(tplg_build_widget) cannot find 'CA_RUNTIME_CONTROLBYTES_NAME_PIPE' referenced by widget 'CODEC_ADAPTER1.0'
ALSA lib parser.c:284:(tplg_build) failed to check topology integrity
failed to compile context production/sof-rn-rt5682-rt1019-dts.conf: Invalid argument
make[2]: *** [topology/topology1/CMakeFiles/topology1_sof-rn-rt5682-rt1019-dts.dir/build.make:61: topology/topology1/production/sof-rn-rt5682-rt1019-dts.tplg] Error 1
make[2]: Leaving directory '/home/sof/work/sof.git/tools/build_tools'
make[1]: *** [CMakeFiles/Makefile2:764: topology/topology1/CMakeFiles/topology1_sof-rn-rt5682-rt1019-dts.dir/all] Error 2
make[1]: Leaving directory '/home/sof/work/sof.git/tools/build_tools'
make: *** [Makefile:130: all] Error 2
Error: Process completed with exit code 2.
```

**Comment by joechengxperi** [comment]
@lgirdwood I missed one file to update. I've already added it.

**Review by lgirdwood — APPROVED** [review]

**Comment by johnylin76** [comment]
Sorry for the late review. LGTM.
If you would like to merge back to older branch, e.g. amd-rn-prod-001. Just be careful for the removal of "Runtime Config" byte-control, which was used in ALSA UCM config on ChromeOS projects.

**Comment by joechengxperi** [comment]
@johnylin76 
I've already tested it on amd-rn-prod-001. After we complete the audio tuning, I'll provide the ALSA UCM config as well.

**Pull request merged**
