### PR TITLE
[WIP][DO NOT MERGE] Soft merge

### PR DESCRIPTION
**Pull request by cujomalainey**
WIP to merge SOFT into SOF to make versioning of ABI files easier.

### CODE REVIEW

**Comment by lgirdwood** [comment]
@cujomalainey looks almost ready ?

**Comment by cujomalainey** [comment]
Will try again when I have a better understanding of the build system, window has now been missed

**Comment by lgirdwood** [comment]
@cujomalainey if retaining history is becoming a PITA then I'm good to just copy files and commit.

**Comment by cujomalainey** [comment]
@lgirdwood retaining history is the easy part, its the build system that is the problem. I can SOFT into its own directory which isn't as elegant but should be easier to merge in. Ideally I was thinking we would put topologies and tools in their own top level dirs and adjust the build system accordingly.

**Comment by lgirdwood** [comment]
@cujomalainey It should be possible to put soft tool and topologies in toplevel, adjusting makefile.am to conditionally build should work like it does for testbench,

Fwiw, this should be a whole lot easier once we have moved to kconfig.

**Comment by cujomalainey** [comment]
Ok will do my best to do a mock run of that myself this week and then if it is successful retry it again on the weekend and just cherry-pick the script patches over so we can archive SOFT

**Comment by cujomalainey** [comment]
Now that GLK is merged into our branch I will get back to this. I am unavailable to do it this weekend. Next weekend is a long weekend for us which will give me time to do a mock run before hand.

**Pull request closed without merging**
