### PR TITLE
Fix legacy Zephyr builds with non-Zephyr native drivers

### PR DESCRIPTION
**Pull request by lyakh**
This fixes breakage introduced by #6951 to legacy driver builds

### CODE REVIEW

**Comment by lyakh** [comment]
CI failures: both on-device tests https://sof-ci.01.org/sofpr/PR7443/build5936/devicetest/index.html and https://sof-ci.01.org/sofpr/PR7443/build5935/devicetest/index.html are suspend-resume failures. Moreover, this PR only introduces functional changes to non-native builds `CONFIG_ZEPHYR_NATIVE_DRIVERS=n` and such builds aren't tested by CI ATM.

**Review by kv2019i — APPROVED** [review]

**Comment by kv2019i** [comment]
Needs a second review, @btian1 @juimonen @paulstelian97 @ranj063 ?

**Comment by paulstelian97** [comment]
Question: how does this affect xtos builds? Is this file common to both?

**Comment by btian1** [comment]
can you specify which build will have copier + host_legacy combination? does CONFIG_ZEPHYR_NATIVE_DRIVERS=n + zephyr build cover this case?

**Comment by lyakh** [comment]
> can you specify which build will have copier + host_legacy combination? does CONFIG_ZEPHYR_NATIVE_DRIVERS=n + zephyr build cover this case?

@btian1 IPC4 with Zephyr with `CONFIG_ZEPHYR_NATIVE_DRIVERS=n`

**Comment by lyakh** [comment]
> Question: how does this affect xtos builds? Is this file common to both?

@paulstelian97 directly, obviously, with XTOS builds you cannot have native Zephyr drivers, so if you use IPC4 with XTOS - you'd be using this code and presumably it's broken without this PR

**Comment by btian1** [comment]
> > can you specify which build will have copier + host_legacy combination? does CONFIG_ZEPHYR_NATIVE_DRIVERS=n + zephyr build cover this case?
> 
> @btian1 IPC4 with Zephyr with `CONFIG_ZEPHYR_NATIVE_DRIVERS=n`

With zephyr and CONFIG_ZEPHYR_NATIVE_DRIVERS=n?

if CI does not cover this test, how can we know it is an issue and it is fixed by this PR?
Also, if this config is not POR, then we should not support this, if need support, we need ask CI to add this configuration.

when I work on #6951, I deliberately avoid to change host-legacy code, and only change copier and host-zephyr to avoid introduce more regression.

**Comment by lyakh** [comment]
> > > can you specify which build will have copier + host_legacy combination? does CONFIG_ZEPHYR_NATIVE_DRIVERS=n + zephyr build cover this case?
> > 
> > 
> > @btian1 IPC4 with Zephyr with `CONFIG_ZEPHYR_NATIVE_DRIVERS=n`
> 
> With zephyr and CONFIG_ZEPHYR_NATIVE_DRIVERS=n?

yes

> if CI does not cover this test, how can we know it is an issue and it is fixed by this PR? Also, if this config is not POR, then we should not support this, if need support, we need ask CI to add this configuration.

The CI doesn't cover all possible configurations and I'd say it wouldn't be possible or feasible to try that. We don't even have analogs of Linux kernel's "allyesconfig" and "randconfig." Still it doesn't mean that we're free to break those untested configurations.  Particularly since the CI only tests on Intel hardware, we still shouldn't break non-Intel configurations. And this kind of a configuration with Zephyr, legacy drivers and IPC4 might well be used by somebody at least as a transitional phase. Still we can rather easily test this PR - try that configuration on Intel hardware before that breaking PR, the current "main" and after this PR.

> when I work on #6951, I deliberately avoid to change host-legacy code, and only change copier and host-zephyr to avoid introduce more regression.

Yes, I remember, we even discussed those legacy stubs for new functions and we briefly discussed the possibility of breakage. But it is indeed difficult to analyse all possibilities "in your head" and without CI testing no wonder we broke it. Still I think it would be good to fix it and to try to avoid and future unintended breakage.

**Comment by paulstelian97** [comment]
> > Question: how does this affect xtos builds? Is this file common to both?
> 
> @paulstelian97 directly, obviously, with XTOS builds you cannot have native Zephyr drivers, so if you use IPC4 with XTOS - you'd be using this code and presumably it's broken without this PR

Understood, so when we migrate i.MX8 platforms to IPC4 we're going to have to only migrate the Zephyr port as opposed to both of them (currently Zephyr is functional and XTOS is more stable/more tested). @dbaluta fyi

**Comment by lyakh** [comment]
> > > Question: how does this affect xtos builds? Is this file common to both?
> > 
> > 
> > @paulstelian97 directly, obviously, with XTOS builds you cannot have native Zephyr drivers, so if you use IPC4 with XTOS - you'd be using this code and presumably it's broken without this PR
> 
> Understood, so when we migrate i.MX8 platforms to IPC4 we're going to have to only migrate the Zephyr port as opposed to both of them (currently Zephyr is functional and XTOS is more stable/more tested). @dbaluta fyi

@paulstelian97 well theoretically you can have IPC4+XTOS but only with "legacy" (current SOF tree) drivers. Since you're talking about an IPC4 migration I assume that's your goal. Then yes, I'd say it would make more sense to go for Zephyr+IPC4. And also for Zephyr-native drivers. So, you'd have to migrate both drivers and the IPC implementation. Then you can choose which one you migrate first. Maybe the easiest would be from
1. Zephyr + IPC3 + SOF drivers
2. to Zephyr + IPC3 + Zephyr native drivers
3. to Zephyr + IPC4 + Zephyr native drivers

Then you avoid that awkward place with IPC4 + SOF drivers where you'd need to use host-legacy with compier.

**Comment by dbaluta** [comment]
@lyakh question about Intel state with native zephyr drives. How does one enable one native driver instead of a SOF driver? What native drivers Intel already has enabled?

We are looking on enabling PDM microphone for IMX and we noticed that Zephyr already supports this via MCU SDK and we want to avoid rewriting it.

Is Intel DMIC supported via native driver for Zephyr?

**Comment by kv2019i** [comment]
@dbaluta  wrote: 
> @lyakh question about Intel state with native zephyr drives. How does one enable one native driver instead of a SOF driver? > What native drivers Intel already has enabled?

We used CONFIG_ZEPHYR_NATIVE_DRIVERS for the transition, but now all drivers are moved over (hd-dma and dw for DMA; dmic,/ssp/hda/sdw DAI drivers), clock/interrupts were moved already earlier.

**Pull request merged**
