### PR TITLE
Revert trace changes to fix CML suspend resume

### PR DESCRIPTION
**Pull request by plbossart**
Experiments with https://github.com/thesofproject/sof/pull/4566 show that the va_args usage and/or the indirection from using log_func() to calling log_func() within _log_sofdict() causes surprising DMA issues and timeouts on CML.

There is just no explanation so far, and after 4 days of shooting in the dark it's time to consider a revert of e7e1eb674dd32f53a9371907bc8138e123897d15 "trace: move CONFIG_TRACEM implementation up a couple levels"

### CODE REVIEW

**Review by marc-hb — APPROVED** [review]
I'm pretty sure this is just "shooting the messenger", not the least because:
- the much older v1.8 tag compiled with GCC fails the same (not "about the same" but exactly the same
- why would this super generic change fail only on CML and only on suspend/resume?

However getting the tests to pass is important so: approved.

Unfortunately I'm on long vacation abroad for the next 3 weeks so I won't have time to investigate this #4558 issue soon. People who need sof-logger on Zephyr should re-apply these locally.

@keqiaozhang don't enable sof-logger in Zephyr CI yet, after these reverts it won't work.

**Review by ranj063 — APPROVED** [review]

**Comment by plbossart** [comment]
rather spectacular failure on CML_HELIOS https://sof-ci.01.org/sofpr/PR4573/build9818/devicetest/

wow. just wow. let's redo the tests....

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
The failing tests on CML_HELIOS are due to the addition of a new test for PRs (multiple_pause_resume) added by @fredoh9. This test fails because of another issue described in https://github.com/thesofproject/sof/issues/4560 and likely introduced by https://github.com/thesofproject/sof/commit/9a7a5ce17dcb

We should probably revert this commit as well to bring CML back to normal.

**Comment by ranj063** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
replaced by PR #4578

**Pull request closed without merging**
