### PR TITLE
 [Stable v1.7] backport for v1.7 final release.

### PR DESCRIPTION
**Pull request by keyonjie**
cherry-picks all fixes I think needed, the mux/demux optimization is not here as it looks uncompleted yet (at least from the kernel side), not quite sure about NXP parts.

### CODE REVIEW

**Comment by keyonjie** [comment]
SOFCI TEST

**Comment by keyonjie** [comment]
@dbaluta can you help to check if it is fine for NXP v1.7?

**Comment by dbaluta** [comment]
@keyonjie I can do a run with your PR on Thursday. @iuliana-prodan @paulstelian97 @ViorelSuman if you guys have some spare cycles today can you give it a quick test?

**Review by cujomalainey — APPROVED** [review]
from my view my patches are fine

**Review by dbaluta — APPROVED** [review]

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by lgirdwood** [comment]
Double check the multiple stream on BYT

**Comment by lgirdwood** [comment]
@zrombel can you confirm if internal CI supports stable branches ?

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by lgirdwood** [comment]
Try CI again, @iuliana-prodan please wait for this to merge first (to reduce conflicts). ASAP after CI passes.

**Comment by lgirdwood** [comment]
Jenkins showing docker rate limit and known issue on BDW.
@zrombel good to merge - Internal CI showing all red on PR_CODEC regression ?

**Comment by dbaluta** [comment]
@lgirdwood is there a way to have access to codec unit tests?

**Comment by lgirdwood** [comment]
> @lgirdwood is there a way to have access to codec unit tests?

@zrombel  can you help here ? Thanks !

**Comment by zrombel** [comment]
@lgirdwood To run codec test QB applies code patch and provide codec library. Due to recent changes in codec code in master branch at this point branch stable-v1.7 is not aligned with master and patch can't be applied. For this PR i've turned of the codec build and testing. If it's necessary I can run manual codec tests on this PR and give feedback.

This patch can be a problem when lot of changes will be introduced to codec regarding codec so maybe is't a good time to find better solution.

**Comment by lgirdwood** [comment]
@zrombel thanks, we may just have to ignore the codec PR for v1.7.

**Pull request merged**
