### PR TITLE
nxp: imx8/imx8x: switch to Zephyr native drivers

### PR DESCRIPTION
**Pull request by LaurentiuM1234**
Note: cleanup will be done in separate PRs after this is merged

### CODE REVIEW

**Comment by paulstelian97** [comment]
Hi there, I thought of checking what's happening around here. I noticed that there may be an opportunity to break bisection (though I may misunderstand something) between the last two commits (a place where you no longer initialise a DMA domain, yet the topology still specifies one). Did you consider swapping the last two commits to avoid this?

Other than that I like how this looks!

**Comment by LaurentiuM1234** [comment]
> I noticed that there may be an opportunity to break bisection (though I may misunderstand something) between the last two commits (a place where you no longer initialise a DMA domain, yet the topology still specifies one)

yep, you're right

> Did you consider swapping the last two commits to avoid this?

that will also break git bisect since the timer domain doesn't work right without the native switch. I think the solution would be to just squash the last 2 commits.

**Comment by iuliana-prodan** [comment]
> > I noticed that there may be an opportunity to break bisection (though I may misunderstand something) between the last two commits (a place where you no longer initialise a DMA domain, yet the topology still specifies one)
> 
> yep, you're right
> 
> > Did you consider swapping the last two commits to avoid this?
> 
> that will also break git bisect since the timer domain doesn't work right without the native switch. I think the solution would be to just squash the last 2 commits.

And use in commit message "switch to native drivers _and timer domain_", since a lot of changes are also related to timer domain.
IMO you should do the same in PR https://github.com/thesofproject/sof/pull/8859

**Review by lgirdwood — APPROVED** [review]
LGTM, giving my +1 so NXP can schedule the merging after validation is complete.

**Comment by LaurentiuM1234** [comment]
**V2 changes**

1. Commit that changes the topologies to timer domain and commit that does transition to native drivers have been squashed into a single one.
2. Adapted to HWMv2.

**Comment by LaurentiuM1234** [comment]
**V3 changes**

1. Rebased
2. All Zephyr dependencies merged. Added zephyr hash bump.

Opening this up for reviews. Will remove the [DNM] tag when testing is done.

**Comment by marc-hb** [comment]
This PR introduces a surprising, `imx8/zephyr.lst` disassembly difference between the Linux and Windows build:

https://github.com/thesofproject/sof/actions/runs/8552063499?pr=8863
```diff
--- win/build-sof-staging/sof-info/imx8x/zephyr.lst	2024-04-04 09:13:44
+++ lin/build-sof-staging/sof-info/imx8x/zephyr.lst	2024-04-04 09:12:34
@@ -81127,20 +81127,26 @@
 92433b0e:	430c                          	movi.n	a3, 4
 #if !(defined(FSL_SDK_DISABLE_DRIVER_CLOCK_CONTROL) && FSL_SDK_DISABLE_DRIVER_CLOCK_CONTROL)
 
         uint32_t instance = LPUART_GetInstance(base);
 
         /* Enable lpuart clock */
         (void)CLOCK_EnableClock(s_lpuartClock[instance]);
 92433b10:	833441                      	l32r	a4, 924147e0 <_stext+0x1598> (92413034 <s_lpuartClock>)
 92433b13:	a03340                      	addx4	a3, a3, a4
 92433b16:	03a8                          	l32i.n	a10, a3, 0
+ * @param name  Which clock to enable, see \ref clock_ip_name_t.
+ * @return true for success, false for failure.
+ */
+static inline bool CLOCK_EnableClock(clock_ip_name_t name)
+{
+    return CLOCK_EnableClockExt(name, 0);
 92433b18:	31e9                          	s32i.n	a14, a1, 12
 92433b1a:	00a0b2                      	movi	a11, 0
 92433b1d:	ffcfa5                      	call8	92433818 <CLOCK_EnableClockExt>
     base->GLOBAL |= LPUART_GLOBAL_RST_MASK;
 92433b20:	0020c0                      	memw
 92433b23:	2238                          	l32i.n	a3, a2, 8
 92433b25:	240c                          	movi.n	a4, 2
 92433b27:	203340                      	or	a3, a3, a4
 92433b2a:	0020c0                      	memw
 92433b2d:	2239                          	s32i.n	a3, a2, 8
```

It is triggered by this PR because daily builds are ok:
https://github.com/thesofproject/sof/actions/runs/8563182403

In light of recent events I hope everything understands the importance of reproducible builds.

The first thing is to submit the `west.yml` separately:
https://docs.zephyrproject.org/latest/contribute/contributor_expectations.html#defining-smaller-prs
Not just for reviewers but also for _Continous_ integration.

Then, if you don't have BOTH one Linux and one Windows build system, could you please submit draft/throw-away PRs with subsets of this (pretty big) PR to isolate the trigger?

**Comment by marc-hb** [comment]
> The first thing is to submit the west.yml separately:

... unless there is a two-way dependency between this west.yml bump and some of the code changes in this PR. In that case they must be part of the same commit so every commit works.

**Comment by LaurentiuM1234** [comment]
Rebased

**Comment by lgirdwood** [comment]
@LaurentiuM1234 is building on Windows priority for you, it seems the compiler has different behavior here for this platform only. I would say here that this is a second order test vs the 1st order runtime functional test for this platform.

I would suggest we comment this platform out from the OS reproducability test and comment in the test that the compiler is generating different code here on Windows vs Linux. You can reference the GH PR and BUG in the comment. We can then move on. @dbaluta this also good with you ?

**Comment by marc-hb** [comment]
Comparing Windows and Linux is the only way the reproducibility test work.

**Comment by lgirdwood** [comment]
> Comparing Windows and Linux is the only way the reproducibility test work.

That fine when the tools are deterministsic and align when used on different OSes, in this case effort is being spent to workaround a compiler bug for a second order test. Today we need to comment out this platform in the test (or report and ignore result for this platform). The compiler will update over time and may align in a future version (when we can re-enable).

**Comment by marc-hb** [comment]
The fix is tested and ready:
- https://github.com/zephyrproject-rtos/zephyr/pull/71535

**Comment by LaurentiuM1234** [comment]
Rebased. Let's see the repro builds results after https://github.com/thesofproject/sof/pull/9071.

**Comment by LaurentiuM1234** [comment]
Repro builds are green. Dropping the `DNM` tag.

**Review by lgirdwood — APPROVED** [review]

**Pull request merged**
