### PR TITLE
zephyr: Support cmake args. Add -Werror in CI

### PR DESCRIPTION
**Pull request by marc-hb**
4 commits. Main ones:
- support CMake arguments
- Add -Werror in CI

### CODE REVIEW

**Comment by marc-hb** [comment]
https://github.com/thesofproject/sof/pull/4733/checks?check_run_id=3548978888 with both `-Werror` and `-Wextra` failed as expected.

**Comment by marc-hb** [comment]
No CML_SKU0955_HDA device was available in https://sof-ci.01.org/sofpr/PR4733/build10246/devicetest/. Everything else is green on that page and everywhere else (it's almost suspicious)

Zephyr builds were all successful (there's no Zephyr testing in PR at the moment, only in daily tests)

**Review by lgirdwood — APPROVED** [review]
@marc-hb what's the long term plan here ? It seem like ```-Werror``` and also ```--std=c99``` need to be default arguments in the build. I would assume these would need to be in Zephyr cmake and be inherited by SOF cmake ? @andyross ?

**Comment by marc-hb** [comment]
> what's the long term plan here ? It seem like -Werror and also --std=c99 need to be default arguments in the build (automatically defined in cmake rules)

I don't know about `-std=c99` and Zephyr. I heard some C99 features are missing from XCC.

In general -Werror by default in the build can be productive because it slows down iterative development, see one of my commit messages here. In upstream Zephyr `-Werror` is not in the build by default, it's added in the test suite (in twister).

Anyway this PR adds flexibility to add any flag anywhere later (and I have another, unrelated PR textually depending on it)

**Review by iuliana-prodan — APPROVED** [review]

**Pull request merged**
