### PR TITLE
ipc4: using xtensa-build-all.sh to build ipc4 firmware

### PR DESCRIPTION
**Pull request by bardliao**
This PR allow us to use xtensa-build-all.sh to build ipc4 firmware.
This PR is an updated version of https://github.com/thesofproject/sof/pull/4325

### CODE REVIEW

**Comment by marc-hb** [comment]
This is not what I suggested in #4325 and seems to add even more duplication and complexity.

**Comment by lgirdwood** [comment]
> This is not what I suggested in #4325 and seems to add even more duplication and complexity.

This is not all for upstream - just to get us all building and working together.

**Comment by marc-hb** [comment]
Apologies I totally missed the target branch.

I'm still curious about the different signing scheme and about who is going to get IPC4 and when in the longer term.

(Speaking of TGL defconfig, not recent #4322 )

**Comment by RanderWang** [comment]
@marc-hb  TGL is always based on SOF not cavs and it is just a development platform before the real IPC4 platform, so sof-tgl-cavs will not be for upstream.

**Pull request merged**
