### PR TITLE
topology: imx8: kwd: use s32le format instead of s16le

### PR DESCRIPTION
**Pull request by ViorelSuman**
Use s32le format instead of s16le.

Signed-off-by: Viorel Suman <viorel.suman@nxp.com>

### CODE REVIEW

**Review by paulstelian97 — APPROVED** [review]
Looks good, is it tested?

**Comment by iuliana-prodan** [comment]
@ViorelSuman can you, please, explain a bit why this change is needed?

**Comment by ViorelSuman** [comment]
> 
> 
> Looks good, is it tested?

Yes, works.

**Comment by ViorelSuman** [comment]
> @ViorelSuman can you, please, explain a bit why this change is needed?

This is just a fast way to fix KWD noise issue on 8QM/QXP platforms using WM8960 codec. All 8QM/QXP related topologies are currently configured to use s32le, so it make sense to have KWD topology configured same way.

On 8MP KWD topology is configured to use s16le, but we do have SDMA + SAI + WM8960 hw config on 8MP board,
while on 8QM/QXP board we do have EDMA + SAI + WM8960 - it appears that EDMA driver has issues with s16le support.

**Review by lgirdwood — APPROVED** [review]
Change is correct, but lets get another IMX approver before merge.

**Review by dbaluta — APPROVED** [review]

**Pull request merged**
