### PR TITLE
alloc: Match alignment with open parenthesis

### PR DESCRIPTION
**Pull request by crazoes**
Match alignment with open parenthesis to
maitain the coding style.

Signed-off-by: Shreeya Patel <shreeya.patel23498@gmail.com>

### CODE REVIEW

**Comment by paulstelian97** [comment]
> can't trust github view on alignment too much, but change is good if commit message is fixed

Yeah, I have verified locally and this looks good. Checkpatch should complain if the fix is wrong anyway.

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by lgirdwood** [comment]
Weird build errors coming from XCC on CNL. Looks like CC error. Try CI again.

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by jajanusz** [comment]
> > can't trust github view on alignment too much, but change is good if commit message is fixed
> 
> Yeah, I have verified locally and this looks good. Checkpatch should complain if the fix is wrong anyway.

No need to check locally, you can 'view raw' in browser :)

**Pull request merged**
