### PR TITLE
Audio: 3rd-party lib integration

### PR DESCRIPTION
**Pull request by fuyuntsuo**
Intelligo NR component integration.

### CODE REVIEW

**Comment by sofci** [comment]
Can one of the admins verify this patch?
> reply **test this please** to run this test once.

**Comment by dbaluta** [comment]
@fuyuntsuo are you still working on this?

**Comment by fuyuntsuo** [comment]
Hi Daniel,

We are doing an internal code review. After passing I will send another PR
for review.

Thanks,
Fu-Yun

**Comment by dbaluta** [comment]
oh, great! thanks.

**Comment by lgirdwood** [comment]
@dbaluta do I need to add @fuyuntsuo to the project for auto CI ?

**Comment by dbaluta** [comment]
@lgirdwood  we could add him. He seems to be friendly. I don't know him :) but I'm interested in Noise Reduction algorithm if this is all about :).

**Comment by lgirdwood** [comment]
@fuyuntsuo feel free to introduce yourself, I assumed you were working with @dbaluta at NXP.

**Comment by fuyuntsuo** [comment]
Hi Liam, dbaluta,

We are Intelligo Corp. based in Taiwan. We are good at developing in-house
NN-based audio algorithm such as noise reduction, keyword spotting,
beamforming, etc.

We've worked with Google Curtis for a while. Now we are integrating our NR
algorithm to SOF with Intel and him.

Nice meeting you guys and hope we will have chance working closely soon!

Thanks,
Fu-Yun

Liam Girdwood ***@***.***> 於 2021年3月17日 週三 20:14 寫道：

**Comment by lgirdwood** [comment]
Thanks @fuyuntsuo - nice to meet you - I will send you invite.

**Pull request closed without merging**
