### PR TITLE
cherry pick module_adapter changes from amd_rn_dts to amd-rn-prod-001

### PR DESCRIPTION
**Pull request by johnylin76**
9d0ffb294b53a8b2907515040b035a190f149409 module_adapter: Modify reset API
3f03b75c3a1b00c57b2c1d4124c22a70ed3cbb9d module_adapter:Fix dangling pointer issue in module reset

### CODE REVIEW

**Comment by johnylin76** [comment]
Back-port https://github.com/thesofproject/sof/commit/b9889d52d0e1b6002ee016b55fa0487544fc0593 for https://github.com/thesofproject/sof/issues/6331

**Comment by lgirdwood** [comment]
@thesofproject/amd pls review.

**Review by balakishorepati — APPROVED** [review]
LGTM

**Comment by johnylin76** [comment]
Oops I should mention the following words earlier:
```
Please be noted that we may want this PR be merged along with the fix on 3P vendors' side (DTS/Waves).
Merging this without 3P fixes may cause other issues when 3P module is applied.
```
Since it is already merged, the only thing need to be cautious is:
Before the fixes from 3P vendors are landed, please revert https://github.com/thesofproject/sof/commit/b9889d52d0e1b6002ee016b55fa0487544fc0593 locally to build firmware binary for 3P-module-integrated devices.

**Pull request merged**
