### PR TITLE
audio: base_fw: move platform specific code from base_fw.c

### PR DESCRIPTION
**Pull request by kv2019i**
Continue from https://github.com/thesofproject/sof/pull/9059 (first 2 patches here are from #9059) and move more implementation out from the generic file.
UPDATE: 9059 closed, let's review the whole set in one go.

Addressing https://github.com/thesofproject/sof/issues/8391 and https://github.com/thesofproject/sof/issues/7549

### CODE REVIEW

**Comment by kv2019i** [comment]
Fuzzing fails to apt get problem -> https://github.com/thesofproject/sof/actions/runs/8739094489/job/23979620908?pr=9060

Checkpatch fail is from existing code I'm moving around -> https://github.com/thesofproject/sof/actions/runs/8739094514/job/23979621326?pr=9060

**Comment by kv2019i** [comment]
@abonislawski @softwarecki @tmleman @tobonex can you take a look?

**Review by lgirdwood — APPROVED** [review]
LGTM, but we need to remove ```src/platform/intel/``` and put this data into a ```src/ipc/ipc4/manifest.c```, ```src/ipc/ipc4/intel.c``` etc  - maybe just a```git mv``` as the final step here.

**Comment by kv2019i** [comment]
@lgirdwood wrote:
> LGTM, but we need to remove `src/platform/intel/` and put this data into a `src/ipc/ipc4/manifest.c`, `src/ipc/ipc4/intel.c` etc - maybe just a`git mv` as the final step here.

I thought we concluded on this already, this is essentially one of the options I proposed in https://github.com/thesofproject/sof/pull/9012#issuecomment-2051309908 (but not the one that was merged). Oh well, I can make a follow-up PR that folds the Intel specific code and drops the platform abstractions.

**Comment by kv2019i** [comment]
V2: 
- rebased due to conflicts (multiple other PRs merged)
- no other changes

**Review by gbernatxintel — APPROVED** [review]
Looks good for me

**Pull request merged**
