### PR TITLE
topology1: Undefine after in DAI & PIPELINE macros

### PR DESCRIPTION
**Pull request by lkoenig**
In order to ease comprehension and avoid side-effect of constants being
defined after calling a macro, this change undefined the locally define
constants for pipelines and dai macros.

Signed-off-by: Lionel Koenig <lionelk@google.com>

### CODE REVIEW

**Comment by ranj063** [comment]
@lkoenig are you seeing the side effect of leaving these defined? I'm a bit nervous about undefining because iirc, there are a couple not cases where we actually reply on these definitions not be used by other macros.

**Comment by lkoenig** [comment]
@ranj063  I was chasing a bug with a too big buffer in a pipeline which was caused by DAI_PERIODS not being undefined in the previous one. I needed the expected size.
Personaly, I feel it is  easier to deal with m4 when macros have no side effects of leave definition around.
I haven't tested on all boards. On the board I tested I (based on tigerlake) I did not find any unexpected behaviour but I did not go through an extensive testing.

**Comment by lgirdwood** [comment]
@lkoenig topology1 does have a lot of short comings with M4. Can you describe the issue you have hit. Btw, I've found it easier to debug topology1 by inspecting the alsaconf output after M4 preprocessing if this helps.
Fwiw, topology2 (fixes all the issues in topology1, but I dont know if we have all the classes upstream yet to try in your case. @ranj063 ?

**Comment by lgirdwood** [comment]
CI looks like it did not run correctly. Rerun

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by lkoenig** [comment]
@lgirdwood We are targeting Tigerlake and still using topology 1. Indeed I used a lot the the intermediate representation to debug. 
I also recommend: https://www.gnu.org/software/m4/manual/html_node/Dumpdef.html

**Comment by lgirdwood** [comment]
Looks like CI is failing
```
Scanning dependencies of target topology1_sof-cml-da7219-max98357a
[  2%] Generating production/sof-cml-da7219-max98357a.conf
m4:/quickbuild/workspace1/24733/SOF_FW/tools/topology/topology1/sof/pipe-kfbm-capture.m4:61: bad expression in eval (bad input): (PCM_MAX_RATE * SCHEDULE_PERIOD) / 1000000
m4:/quickbuild/workspace1/24733/SOF_FW/tools/topology/topology1/sof/pipe-kfbm-capture.m4:60: bad expression in eval: DAI_PERIODS * 4 * PIPELINE_CHANNELS * 
m4:/quickbuild/workspace1/24733/SOF_FW/tools/topology/topology1/sof/pipe-kfbm-capture.m4:65: bad expression in eval (bad input): (PCM_MAX_RATE * SCHEDULE_PERIOD) / 1000000
m4:/quickbuild/workspace1/24733/SOF_FW/tools/topology/topology1/sof/pipe-kfbm-capture.m4:64: bad expression in eval (bad input): 2 * 4 * PIPELINE_CHANNELS * 
topology/topology1/CMakeFiles/topology1_sof-cml-da7219-max98357a.dir/build.make:64: recipe for target 'topology/topology1/production/sof-cml-da7219-max98357a.conf' failed
make[2]: *** [topology/topology1/production/sof-cml-da7219-max98357a.conf] Error 1
make[2]: *** Deleting file 'topology/topology1/production/sof-cml-da7219-max98357a.conf'
CMakeFiles/Makefile2:452: recipe for target 'topology/topology1/CMakeFiles/topology1_sof-cml-da7219-max98357a.dir/all' failed
make[1]: *** [topology/topology1/CMakeFiles/topology1_sof-cml-da7219-max98357a.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by lkoenig** [comment]
> Looks like CI is failing

Sorry I did a oops when making the PR from my local copy. I fixed it now.

**Comment by lgirdwood** [comment]
@ranj063 I'm thinking if these are undefined then we should fail to build the ALSAconf output as DAI and PIPELINE would be strings ? Or would they silently default to 0 ?

**Review by cujomalainey — APPROVED** [review]

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
CI showing some untested TGL tests, but changes working across all other DUTs and topologies.

**Pull request merged**
