### PR TITLE
smp: fix slave cores initialization

### PR DESCRIPTION
**Pull request by tlauda**
Fixes slave cores initialization by moving interrupt
init before any interrupt registration.

Signed-off-by: Tomasz Lauda <tomasz.lauda@linux.intel.com>

### CODE REVIEW

**Comment by lgirdwood** [comment]
@tlauda I guess CI is a false positive here ?

**Comment by michalgrodzicki** [comment]
+ @zrombel could you check CI results?

**Comment by zrombel** [comment]
Earlier tests fail because of platform error. After rerun basic tests have passed. I run additional multikernel tests on ICL and WHL and this PR only fixes test case on WHL where playback and capture pipeline are on the same core (no 1), when pipelines are on different cores the streams doesn't start. On ICL streams doesn't start in any of mentioned cases.

**Comment by jajanusz** [comment]
@lgirdwood @tlauda  I merged it because it looks like a fix for right order of instructions and even fixes something, but looks like there are some cases that still need some fixes as @zrombel  wrote.

**Pull request merged**
