### PR TITLE
[Do Not Merge][Requires Rework] TGL: enable CONFIG_INCOHERENT correctly

### PR DESCRIPTION
**Pull request by lyakh**
Kconfig options with no description cannot be selected from defconfig. They can only be selected from other Kconfig options. This means, that CONFIG_INCOHERENT doesn't get selected on TGL. Move it to Kconfig to fix this.

### CODE REVIEW

**Comment by marc-hb** [comment]
Only TGL failed in https://sof-ci.01.org/sof-pr-viewer/#/build/PR5312/build8490295

Only TGL and ADL failed in https://sof-ci.01.org/sofpr/PR5312/build11914/devicetest/

**Comment by lgirdwood** [comment]
host_params() is getting a buffer but not acquiring it. @lyakh can you try this (needs a cleanup)
```diff
diff --git a/src/audio/host.c b/src/audio/host.c
index 8f0495723..fd0790362 100644
--- a/src/audio/host.c
+++ b/src/audio/host.c
@@ -741,15 +741,6 @@ static int host_params(struct comp_dev *dev,
 
 	comp_dbg(dev, "host_params()");
 
-	if (dev->direction == SOF_IPC_STREAM_PLAYBACK)
-		hd->local_buffer = list_first_item(&dev->bsink_list,
-						   struct comp_buffer,
-						   source_list);
-	else
-		hd->local_buffer = list_first_item(&dev->bsource_list,
-						   struct comp_buffer,
-						   sink_list);
-
 	err = host_verify_params(dev, params);
 	if (err < 0) {
 		comp_err(dev, "host_params(): pcm params verification failed.");
@@ -788,12 +779,23 @@ static int host_params(struct comp_dev *dev,
 		return -EINVAL;
 	}
 
+	if (dev->direction == SOF_IPC_STREAM_PLAYBACK)
+		hd->local_buffer = list_first_item(&dev->bsink_list,
+						   struct comp_buffer,
+						   source_list);
+	else
+		hd->local_buffer = list_first_item(&dev->bsource_list,
+						   struct comp_buffer,
+						   sink_list);
+	hd->local_buffer = buffer_acquire(hd->local_buffer);
+
 	period_bytes = dev->frames *
 		audio_stream_frame_bytes(&hd->local_buffer->stream);
 
 	if (!period_bytes) {
 		comp_err(dev, "host_params(): invalid period_bytes");
-		return -EINVAL;
+		err = -EINVAL;
+		goto out;
 	}
 
 	/* determine source and sink buffer elements */
@@ -822,14 +824,15 @@ static int host_params(struct comp_dev *dev,
 		if (err < 0) {
 			comp_err(dev, "host_params(): buffer_set_size() failed, buffer_size = %u",
 				 buffer_size);
-			return err;
+			goto out;
 		}
 	} else {
 		hd->dma_buffer = buffer_alloc(buffer_size, SOF_MEM_CAPS_DMA,
 					      addr_align);
 		if (!hd->dma_buffer) {
 			comp_err(dev, "host_params(): failed to alloc dma buffer");
-			return -ENOMEM;
+			err = -ENOMEM;
+			goto out;
 		}
 
 		buffer_set_params(hd->dma_buffer, params, BUFFER_UPDATE_FORCE);
@@ -838,7 +841,7 @@ static int host_params(struct comp_dev *dev,
 	/* create SG DMA elems for local DMA buffer */
 	err = create_local_elems(dev, period_count, buffer_size / period_count);
 	if (err < 0)
-		return err;
+		goto out;
 
 	/* set up DMA configuration - copy in sample bytes. */
 	config->src_width =
@@ -859,7 +862,8 @@ static int host_params(struct comp_dev *dev,
 	hd->chan = dma_channel_get(hd->dma, hd->stream_tag);
 	if (!hd->chan) {
 		comp_err(dev, "host_params(): hd->chan is NULL");
-		return -ENODEV;
+		err = -ENODEV;
+		goto out;
 	}
 
 	err = dma_set_config(hd->chan, &hd->config);
@@ -867,7 +871,7 @@ static int host_params(struct comp_dev *dev,
 		comp_err(dev, "host_params(): dma_set_config() failed");
 		dma_channel_put(hd->chan);
 		hd->chan = NULL;
-		return err;
+		goto out;
 	}
 
 	err = dma_get_attribute(hd->dma, DMA_ATTR_COPY_ALIGNMENT,
@@ -876,7 +880,7 @@ static int host_params(struct comp_dev *dev,
 	if (err < 0) {
 		comp_err(dev, "host_params(): dma_get_attribute()");
 
-		return err;
+		goto out;
 	}
 
 	/* minimal copied data shouldn't be less than alignment */
@@ -894,7 +898,9 @@ static int host_params(struct comp_dev *dev,
 		pcm_get_conversion_function(hd->local_buffer->stream.frame_fmt,
 					    hd->local_buffer->stream.frame_fmt);
 
-	return 0;
+out:
+	hd->local_buffer = buffer_release(hd->local_buffer);
+	return err;
 }
 
 static int host_prepare(struct comp_dev *dev)
```

**Comment by sys-pt1s** [comment]
Can one of the admins verify this patch?

**Comment by lgirdwood** [comment]
@lyakh still for merge ?

**Comment by lyakh** [comment]
> @lyakh still for merge ?

@lgirdwood not in this form, no. Unfortunately I don't see a way to make it a draft again. I modified the subject and I can give it a negative review too to make sure it doesn't get merged by accident. But that's still our goal of course - enabling `CONFIG_INCOHERENT` on TGL

**Comment by lyakh** [comment]
the first of these is now in #6084 , the second one probably shouldn't be used. It is correct, that switching between cached and uncached access can cause problems in single-core configurations too, but forcing cache synchronisation on each such potential switch is too expensive, we're trying to identify and fix only those paths, where this is really required

**Comment by marc-hb** [comment]
>  Unfortunately I don't see a way to make it a draft again. 

The link is under the reviewers list, check any open and non-draft PR.

**Pull request closed without merging**
