### PR TITLE
.github/pull-request.yml: watch "main" branch instead of master

### PR DESCRIPTION
**Pull request by marc-hb**
Will hopefully fix mysterious CI hangs.

Signed-off-by: Marc Herbert <marc.herbert@intel.com>

### CODE REVIEW

**Review by fredoh9 — APPROVED** [review]

**Review by cujomalainey — APPROVED** [review]

**Comment by cujomalainey** [comment]
CI recovered in this PR, expediting due to impact.

**Comment by cujomalainey** [comment]
Looks like everyone has to rebase on top of this PR to get the fix. I re-ran a PR and it didn't pick up the change. I rebased #3974 and that seems to have fixed it, @marc-hb can you confirm and put out a PSA on sof-dev group?

**Comment by cujomalainey** [comment]
Likely that would work too, rebase just seemed easier

**Comment by marc-hb** [comment]
> So a fake commit --amend + force push to merely change the git SHA should be enough. Let me try.

Confirmed with (unrelated) #3993 .

Of course rebasing works too but that creates useless `git range-diff` noise. Useless because CI tests `pull/12345/merge` anyway.

> Maybe some github button in the web UI is enough. Let me try.

Found nothing there unfortunately.

**Pull request merged**
