### PR TITLE
ipc: add complete task callback

### PR DESCRIPTION
**Pull request by tlauda**
Changes ipc task implementation, so it accepts new messages from
host in a complete task callback. This way we will avoid the
situation, where host will send another message before we
truly complete current ipc task.

Signed-off-by: Tomasz Lauda <tomasz.lauda@linux.intel.com>

### CODE REVIEW

**Comment by tlauda** [comment]
@wenqingfu @mengdonglin @aiChaoSONG Should fix #1812 and #1830.

**Comment by dbaluta** [comment]
@tlauda let me give it a try today

**Comment by tlauda** [comment]
SOFCI TEST

**Comment by dbaluta** [comment]
> @dbaluta You can approve once you test it ;)

@jajanusz done.

**Comment by tlauda** [comment]
SOFCI TEST

**Pull request merged**
