### PR TITLE
Tools: Topology: Add a development topology to RUN SRC on UP2

### PR DESCRIPTION
**Pull request by singalsu**
Add this topology to be able to test SRC playback and capture.

Signed-off-by: Seppo Ingalsuo <seppo.ingalsuo@linux.intel.com>

### CODE REVIEW

**Comment by singalsu** [comment]
I wonder how this could break unit tests...

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
> I wonder how this could break unit tests...

CI failure - will rerun tomorrow.

**Comment by marc-hb** [comment]
> I wonder how this could break unit tests...

You mean https://sof-ci.01.org/sof-pr-viewer/#/build/PR5644/build9011277, not https://github.com/thesofproject/sof/runs/5814116581, correct? Always save the links to failures as they become very hard to find after a force push (Github only tolerates force pushes)

Actually the build failed in https://sof-ci.01.org/sof-pr-viewer/#/build/PR5644/build9011277, the tests did not even run. Clearly unrelated.

@singalsu to re-run just do an empty `git commit --amend -C HEAD` and force-push.

**Comment by lgirdwood** [comment]
@marc-hb it was the internal CI outage, seems to be fixed now though, red -> green.

**Pull request merged**
