### PR TITLE
Zephyr manifest update and fix for repro build issue

### PR DESCRIPTION
**Pull request by LaurentiuM1234**
Pulls in the following patches relevant to SOF:

94d156c9c84c nxp: imx8ulp: enable serial interface
bc63835ba240 dts: xtensa: intel_adsp_cavs25_tgph: correct SSP definition
aecf19c3c1be dts: xtensa: intel_adsp_ace15: correct SSP definition
45205f865e18 dts: xtensa: intel_adsp_ace20: correct SSP definition
17081222e2e7 drivers: dai: intel: ssp: fix LOG_ERR level / false positive
fb7e9379e137 cmake: add control over inline source code disassembly

and fixes https://github.com/thesofproject/sof/issues/9034

### CODE REVIEW

**Comment by marc-hb** [comment]
compare-linux-win https://github.com/thesofproject/sof/actions/runs/8787360472/job/24112815169?pr=9071 is green but... I can still see source code in the .lst files?!?

**Comment by LaurentiuM1234** [comment]
> compare-linux-win https://github.com/thesofproject/sof/actions/runs/8787360472/job/24112815169?pr=9071 is green but... I can still see source code in the .lst files?!?

Mind having another look pls? Previous version of this PR was setting `CONFIG_OUTPUT_DISASSEMBLY_WITH_SOURCE` to `y` so perhaps the artifacts were outdated? Briefly checked 8ulp's `.lst` and no source code.

**Comment by marc-hb** [comment]
I was of course looking at the wrong .zip file... sincere apologies and thank you so much for doing all this, much appreciated.

**Review by marc-hb — APPROVED** [review]

**Comment by marc-hb** [comment]
SOFCI TEST

**Review by dbaluta — APPROVED** [review]

**Review by cujomalainey — APPROVED** [review]

**Review by kv2019i — APPROVED** [review]
Thanks @LaurentiuM1234 !

**Pull request merged**
