### PR TITLE
topology: tgl-sdw-max98373: Add UUID for Maxim DSM component

### PR DESCRIPTION
**Pull request by yongzhi1**
Add UUID for Maxim DSM component, define SMART_UUID to use MAXIM_DSM.

Signed-off-by: Yong Zhi <yong.zhi@intel.com>

### CODE REVIEW

**Comment by yongzhi1** [comment]
Hi, @bkokoszx, can you merge this patch to tgl-011-drop-stable? Thanks!!

cc @sathya-nujella

**Review by plbossart — CHANGES_REQUESTED** [review]
NAK. we can't do this in the SOF tree. We can only use public components in the public tree, otherwise we break CI/tests.

@lgirdwood this needs your attention.

**Comment by lgirdwood** [comment]
> NAK. we can't do this in the SOF tree. We can only use public components in the public tree, otherwise we break CI/tests.
> 
> @lgirdwood this needs your attention.

Lets figure this out fully at next TSC. We need a way to include 3rd party binary components whilst not breaking CI. @cujomalainey fyi.

Does it make sense to have a ```tools/topology/nonfree/``` directy to upstream nonfree topologies. Would this work for the kernel ?

**Comment by cujomalainey** [comment]
I'm ok with leaving this out of tree since we carry this in our fork since we need to carry other non public code. Not sure what license implications would be about the DSM, that being said it is tied to hardware so I would think that wouldnt be an issue. Other closed components that are not tied to hardware might be more of an issue. @dbaluta might have some thoughts on this.

**Comment by yongzhi1** [comment]
Thanks everyone for your response, since a consensus was reached, let me close the PR.

**Pull request closed without merging**
