### PR TITLE
topology1: imx8ulp: overwrite CHANNELS_MIN

### PR DESCRIPTION
**Pull request by iuliana-prodan**
On 8ULP SAI is connected to BT which supports
only 1 channel for both playback and record.

Fixes: aaff3523144e ('topology1: pipe-volume-capture.m4: Set minimum number of channels to 2')

### CODE REVIEW

**Review by dbaluta — APPROVED** [review]

**Review by LaurentiuM1234 — APPROVED** [review]

**Comment by dbaluta** [comment]
@lgirdwood  there are some CI failures but not related to this PR. 

Someone at Intel should really look at the compilation errors.

**Comment by dbaluta** [comment]
SOFCI TEST

**Comment by dbaluta** [comment]
@lgirdwood can you please help merge this. CI failures are not related to this.

**Comment by kv2019i** [comment]
Checked offline, the build has passed (build id 2762), but reporting to github has not completed. As this has waited for a while, let me merge this. FYI @marc-hb and @fredoh9

**Pull request merged**
