### PR TITLE
git: Remove temporary checkpatch file from repository

### PR DESCRIPTION
**Pull request by ktrzcinx**
This file is generate by checkpatch run, any temporary file shouldn't
be tracked by git. It was added to git by:
538eb6a: ("host: stub about required functions")

Moreover file is problematic for developers working on Windows,
now try to pull changes from remote repository ends up with:
```
  $ git pull
  error: invalid path '.checkpatch-camelcase.git.'
  Updating 6e85152..7709924`
```

cloning repository ends up with:
```
   $ git clone https://github.com/thesofproject/sof.git
   Cloning into 'sof'...
   remote: Enumerating objects: 97, done.
   remote: Counting objects: 100% (97/97), done.
   remote: Compressing objects: 100% (96/96), done.
   remote: Total 67251 (delta 49), reused 4 (delta 1), pack-reused 67154
   Receiving objects: 100% (67251/67251), 13.41 MiB | 2.62 MiB/s, done.
   Resolving deltas: 100% (49768/49768), done.
   error: invalid path '.checkpatch-camelcase.git.'
   fatal: unable to checkout working tree
   You can inspect what was checked out with 'git status'
   and retry with 'git restore --source=HEAD :/'
```

Signed-off-by: Karol Trzcinski <karolx.trzcinski@linux.intel.com>

### CODE REVIEW

**Review by lgirdwood — CHANGES_REQUESTED** [review]
@ktrzcinx do you know what this file is used for and is there any drawback here ? The commit message is missing why it's a problem and subject should be "gitignore: remove blah because blah" otherwise it make me think something is wrong with git.
@marc-hb @xiulipan any comments ?

**Review by xiulipan — APPROVED** [review]
The fix looks good @lgirdwood this kind of cache file is generate by software and exist already on most user's repo, there will be conflict when do pulling and we need always do some reset.
And this is why we need to put it into gitignore to avoid accidently add it back again with a `git add -a`

**Comment by dbaluta** [comment]
@ktrzcinx I would prefer to do this in two patches:

- 1. remove hidden file added by accident
- 2. add .checkpatch file to gitignore so that we can avoid this problem in the future

Other than that change looks good to me.

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
@fredoh9 @marc-hb @xiulipan can someone reboot CI - looks like multiple different failures for an unrelated patch

**Comment by plbossart** [comment]
> @fredoh9 @marc-hb @xiulipan can someone reboot CI - looks like multiple different failures for an unrelated patch

cross-dependencies between linux, sof-test and kconfig, should be sorted out this morning. Sorry about that.

**Review by dbaluta — APPROVED** [review]

**Comment by marc-hb** [comment]
I agree generated files (and only generated files) should be in `.gitignore.` They should also be "make cleaned" but that doesn't seem possible with CMake in this particular case.

`git add -a` is evil. Never `git add -a`.

The only checkpatch warnings are the usual and relatively stupid `A patch subject line should describe the change not the tool that found it`. I found a very simple trick to fool these: 
```
Remove temporary check patch file from repository
```
Note the space between "check" and "patch.


PS: I have no idea what's going with CI today

**Review by cujomalainey — APPROVED** [review]
Thanks for catching that

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by marc-hb** [comment]
SOFCI TEST

**Comment by marc-hb** [comment]
The BYT_MB_NOCODEC failure in https://sof-ci.01.org/sofpr/PR3540/build7494/devicetest
is maybe https://github.com/thesofproject/sof-test/issues/379 ?

**Comment by cujomalainey** [comment]
I don't see why we need to rely on CI for this since these are meta project files

**Comment by marc-hb** [comment]
> I don't see why we need to rely on CI for this since these are meta project files

We simply don't have any database of "meta project files".

Maintainers are generally smart enough to ignore CI errors on purely "meta" changes but a reminder like yours is always useful!

**Comment by lgirdwood** [comment]
> The BYT_MB_NOCODEC failure in https://sof-ci.01.org/sofpr/PR3540/build7494/devicetest
> is maybe [thesofproject/sof-test#379](https://github.com/thesofproject/sof-test/issues/379) ?

Looks like the bandpass for the test is not wide enough or there is jitter in the DUT or tester clocking.

**Pull request merged**
