### PR TITLE
byt: bdw: disable agent by default

### LINKED ISSUE #2585: [BUG][BDW]“DSP panic” when test "Check-playback: Stress - 100x"
Describe the bug
“DSP panic” when test "Check-playback: Stress - 100x",error occured when aplay via (0,0),after error occured,all the pipeline can not work,reboot can recovery

used device: sh-bdw-wsb-rt286-03
```
ubuntu@sh-bdw-wsb-rt286-03:~$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: sofbroadwellrt2 [sof-broadwell-rt286], device 0: Low Latency (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofbroadwellrt2 [sof-broadwell-rt286], device 1: Media Playback 1 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: Device [USB Audio Device], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

To Reproduce
1.sudo reboot
2.cd sof-test
3.cd test-case
4. export TPLG=/lib/firmware/intel/sof-tplg/sof-bdw-rt286.tplg
5. ./check-playback.sh -d 1 -l 100 -r 1(https://github.com/thesofproject/sof-test/blob/master/test-case/check-playback.sh)

Reproduction Rate
2/2
1.failed at 55th of 100
2.failed at 43th of 100

Expected behavior
There is no DSP panic when aplay/arecord

Actual result
DSP panic,all the pipeline can not work

Capture

<details>
 <summary>dmesg_error.log</summary>

````
kernel: [ 3047.127793] sof-audio-acpi INT3438:00: ipc tx: 0x60030000: GLB_STREAM_MSG: PCM_FREE
kernel: [ 3047.127878] sof-audio-acpi INT3438:00: ipc tx succeeded: 0x60030000: GLB_STREAM_MSG: PCM_FREE
kernel: [ 3047.128065] sof-audio-acpi INT3438:00: pcm: free stream 0 dir 0
kernel: [ 3047.128206] sof-audio-acpi INT3438:00: pcm: close stream 0 dir 0
kernel: [ 3050.353860] sof-audio-acpi INT3438:00: error : DSP panic!
kernel: [ 3050.353875] sof-audio-acpi INT3438:00: panic: dsp_oops_offset 649216 offset 649216
kernel: [ 3050.353953] sof-audio-acpi INT3438:00: error: can't enter idle
kernel: [ 3050.353959] sof-audio-acpi INT3438:00: error: trace point 00000800
kernel: [ 3050.353965] sof-audio-acpi INT3438:00: error: panic at src/lib/agent.c:56
kernel: [ 3050.353971] sof-audio-acpi INT3438:00: error: DSP Firmware Oops
kernel: [ 3050.353978] sof-audio-acpi INT3438:00: EXCCAUSE 0x0000003f EXCVADDR 0x00000000 PS       0x00060125 SAR     0x00000000
kernel: [ 3050.353984] sof-audio-acpi INT3438:00: EPC1     0x00000000 EPC2     0x00000000 EPC3     0x00017e25 EPC4    0x00000000
kernel: [ 3050.353989] sof-audio-acpi INT3438:00: EPC5     0x00000000 EPC6     0x00000000 EPC7     0x00000000 DEPC    0x00000000
kernel: [ 3050.354036] sof-audio-acpi INT3438:00: EPS2     0x00000000 EPS3     0x00060520 EPS4     0x00000000 EPS5    0x00000000
kernel: [ 3050.354045] sof-audio-acpi INT3438:00: EPS6     0x00000000 EPS7     0x00000000 INTENABL 0x00000000 INTERRU 0x00002440
kernel: [ 3050.354051] sof-audio-acpi INT3438:00: stack dump from 0x0040a600
kernel: [ 3050.354071] sof-audio-acpi INT3438:00: 0x0040a600: 00409710 00000000 0040a620 00000028
kernel: [ 3050.354092] sof-audio-acpi INT3438:00: 0x0040a604: 00000000 00000000 00000038 00014b4c
kernel: [ 3050.354116] sof-audio-acpi INT3438:00: 0x0040a608: 3e9de000 6b3f1450 c541e828 ffff9da2
kernel: [ 3050.354133] sof-audio-acpi INT3438:00: 0x0040a60c: c541e828 ffff9da2 00000000 00000000
kernel: [ 3050.354145] sof-audio-acpi INT3438:00: 0x0040a610: c4882d80 ffff9da2 b9ec0960 ffffffff
````
</details>

<details>
 <summary>sof_errorttace.log</summary>

````
[4371599927.500000] (             nan) c0 SA                          src/lib/agent.c:56    ERROR validate(), ll drift detected, delta = 354913
[4818066074.583334] (446466144.000000) c0 SA                          src/lib/agent.c:56    ERROR validate(), ll drift detected, delta = 347508
[6038898830.416667] (             nan) c0 SA                          src/lib/agent.c:56    ERROR validate(), ll drift detected, delta = 336420
[6125800810.416667] ( 86901984.000000) c0 SA                          src/lib/agent.c:56    ERROR validate(), ll drift detected, delta = 374436
[6212368490.625000] ( 86567680.000000) c0 SA                          src/lib/agent.c:56    ERROR validate(), ll drift detected, delta = 393896
[6298767831.250000] ( 86399344.000000) c0 SA                          src/lib/agent.c:56    ERROR validate(), ll drift detected, delta = 381236
[6388049174.166667] ( 89281344.000000) c0 SA                          src/lib/agent.c:56    ERROR validate(), ll drift detected, delta = 343020
[6934499291.458334] (546450112.000000) c0 SA                          src/lib/agent.c:56    ERROR validate(), ll drift detected, delta = 345272
[7119266683.750000] (184767392.000000) c0 SA                          src/lib/agent.c:56    ERROR validate(), ll drift detected, delta = 355043
[7402368547.500000] (283101856.000000) c0 SA                          src/lib/agent.c:56    ERROR validate(), ll drift detected, delta = 394988
[10386215637.916668] (             nan) c0 SA                          src/lib/agent.c:56    ERROR validate(), ll drift detected, delta = 339124
[11593300504.583334] (             nan) c0 SA                          src/lib/agent.c:56    ERROR validate(), ll drift detected, delta = 368592
[12410784228.541668] (817483712.000000) c0 SA                          src/lib/agent.c:56    ERROR validate(), ll drift detected, delta = 376064
[12500565530.625000] ( 89781304.000000) c0 SA                          src/lib/agent.c:56    ERROR validate(), ll drift detected, delta = 337064
[12595849933.750000] ( 95284400.000000) c0 SA                          src/lib/agent.c:56    ERROR validate(), ll drift detected, delta = 355700
[12694565994.375000] ( 98716064.000000) c0 SA                          src/lib/agent.c:56    ERROR validate(), ll drift detected, delta = 345968
[13998015600.416668] (             nan) c0 SA                          src/lib/agent.c:56    ERROR validate(), ll drift detected, delta = 338404
[14488317418.750000] (490301824.000000) c0 SA                          src/lib/agent.c:56    ERROR validate(), ll drift detected, delta = 373316
[19137451285.625000] (             nan) c0 SA                          src/lib/agent.c:56    ERROR validate(), ll drift detected, delta = 383560
[20864297975.052086] (             nan) c0 SA                          src/lib/agent.c:56    ERROR validate(), ll drift detected, delta = 639998
[21193166382.083336] (328868416.000000) c0 SA                          src/lib/agent.c:56    ERROR validate(), ll drift detected, delta = 353279
[21539017612.291668] (345851232.000000) c0 SA                          src/lib/agent.c:56    ERROR validate(), ll drift detected, delta = 377032
[22322800935.416668] (783783296.000000) c0 SA                          src/lib/agent.c:56    ERROR validate(), ll drift detected, delta = 376836
[22496117468.541668] (173316528.000000) c0 SA                          src/lib/agent.c:56    ERROR validate(), ll drift detected, delta = 374272
[22755901743.541668] (259784272.000000) c0 SA                          src/lib/agent.c:56    ERROR validate(), ll drift detected, delta = 392352
[22841934745.625000] ( 86033000.000000) c0 SA                          src/lib/agent.c:56    ERROR validate(), ll drift detected, delta = 385992
[25757584428.281250] (             nan) c0 DAI          1.0   ..../intel/haswell/ssp.c:504   ssp_trigger()
[25757584488.281250] (       60.000000) c0 DAI          1.0   ..../intel/haswell/ssp.c:475   ssp_stop(), TX stop
[25757584541.302086] (       53.020832) c0 DAI          1.0   ..../intel/haswell/ssp.c:482   ssp_stop(), SSP port disabled
[25757584603.854168] (       62.552082) c0 SCHEDULE_LL        ./schedule/ll_schedule.c:378   task cancel 0x415d00
[25757584663.229168] (       59.375000) c0 SCHEDULE_LL        ./schedule/ll_schedule.c:245   num_tasks 0 total_num_tasks 0
[25757584715.364586] (       52.135418) c0 SCHEDULE_LL        /dma_multi_chan_domain.c:215   dma_multi_chan_domain_unregister()
[25757584789.218750] (       73.854164) c0 SCHEDULE_LL        /dma_multi_chan_domain.c:191   dma_multi_chan_domain_irq_unregister()
[25757586479.791668] (     1690.572876) c0 IPC                       src/ipc/handler.c:357   ipc: comp 1 -> free
[25757586530.833336] (       51.041668) c0 PIPE         1.10      src/audio/pipeline.c:719   pipe reset
[25757586615.677086] (       84.843750) c0 DMA                    src/drivers/dw/dma.c:245   dw_dma_channel_put(): dma 1 channel 3 put
````
</details>

Platform: BDW  with onboard codec RT286 in WSB mode
Firmware: f1fa3be9 https://github.com/thesofproject/sof/commits/master
Kernel: e4ba562e https://github.com/thesofproject/linux/commits/topic/sof-dev
Topology: file: tools/topolog/ sof-bdw-rt286.tplg same as firmware

[dmesg.txt](https://github.com/thesofproject/sof/files/4353940/dmesg.txt)
[slogger.txt](https://github.com/thesofproject/sof/files/4353942/slogger.txt)

### PR DESCRIPTION
**Pull request by tlauda**
Disables system agent for BYT/CHT and HSW/BDW platforms.
System agent is supposed to track drift between timer ticks,
but it's only valid for the platforms with timer based scheduling.
Platforms with DMA based scheduling have asynchronous interrupts,
which can potentially starve the agent and cause system panic.

Signed-off-by: Tomasz Lauda <tomasz.lauda@linux.intel.com>

Fixes #2585.

### CODE REVIEW

**Comment by paulstelian97** [comment]
Add imx8 and imx8x please, they are also DMA based and have trouble with the agent.

**Comment by tlauda** [comment]
> Add imx8 and imx8x please, they are also DMA based and have trouble with the agent. imx8m will probably be DMA based as well but I need to figure it out if it works first; if it's the case I will add it manually.

Done.

**Comment by lgirdwood** [comment]
> The justification provided in the commit message would look good in KConfig as an extension to the current description:
> 
> ```
> config HAVE_AGENT
> 	bool "Enable system agent"
> 	default y
> 	help
> 	  Enables system agent. It can be disabled on systems
> 	  which are still unstable and cannot assure that
> 	  system agent will always execute on time.
> ```

I think the problem here is not FW stability on this platform, but more of the drift between DAI DMA IRQs and the agent time domains.

**Comment by tlauda** [comment]
> > The justification provided in the commit message would look good in KConfig as an extension to the current description:
> > ```
> > config HAVE_AGENT
> > 	bool "Enable system agent"
> > 	default y
> > 	help
> > 	  Enables system agent. It can be disabled on systems
> > 	  which are still unstable and cannot assure that
> > 	  system agent will always execute on time.
> > ```
> 
> I think the problem here is not FW stability on this platform, but more of the drift between DAI DMA IRQs and the agent time domains.

@mmaka1 @lgirdwood  Commit explanation appended to Kconfig description.

**Pull request merged**
