### PR TITLE
oss-fuzz: add ipc fuzzer

### PR DESCRIPTION
**Pull request by cujomalainey**
Add shim to fuzz the full ipc space with oss-fuzz

related to #3388

### CODE REVIEW

**Comment by cujomalainey** [comment]
Still finishing out build infra and testing this, will be followed up by a commit to oss-fuzz

**Review by lgirdwood — COMMENTED** [review]
LGTM, I guess the commit message will be updated to include usage details ?

**Comment by cujomalainey** [comment]
We won't use it, an external service pulls our code in a docker file and I will have scripting in their repo to build this correctly

**Comment by cujomalainey** [comment]
going to close this while I debug another compile failure in oss-fuzz that will require me to force push a bunch of times

**Pull request closed without merging**
