### PR TITLE
sof: trace: Remove error prefix from logs

### PR DESCRIPTION
**Pull request by ktrzcinx**
This prefix is added in logger converter, so it shouldn't be
added manually.

Signed-off-by: Karol Trzcinski <karolx.trzcinski@linux.intel.com>

### CODE REVIEW

**Comment by dbaluta** [comment]
Looks good to me. Lets hope that there aren't people looking for the "exact" error message in their tests.

**Comment by lgirdwood** [comment]
@ktrzcinx please confirm if internal CI is good.

**Comment by ktrzcinx** [comment]
@lgirdwood It looks good, all green on internal CI

**Comment by lgirdwood** [comment]
Jenkins known issues.

**Pull request merged**
