### PR TITLE
[RFC] tools: add python blob generator

### PR DESCRIPTION
**Pull request by juimonen**
Provide a general tool for creating binary blobs for sof process
components.

Signed-off-by: Jaska Uimonen <jaska.uimonen@intel.com>

### CODE REVIEW

**Comment by juimonen** [comment]
just something as my python skills are not that good... based on python's "struct" module.

**Comment by juimonen** [comment]
@lgirdwood, so this tool is generating the whole blob for you (not just abi header). So it is not for fir/iir where you need to use complex math design tools for getting the filter coeffs, unless you are very good doing math in your head :). It is more for those components where you build the blob from multiple structs having quite simple parameters in the end.

I'm not sure the mux/demux we have is usable with enums only. It is more complicated than mux/demux envisaged in asoc.

Anyway, @keyon and @mmaka1 are suggesting to move totally to blobs in processing components: 
https://github.com/orgs/thesofproject/teams/sof-developers/discussions/32, we would need someone else than me commenting on that.

Also, having this tool around would not close any options, but you could actually create the mux/demux blob (which was never possible before in public).

**Comment by lgirdwood** [comment]
@juimonen I want rid of any blob that is used for runtime config unless it's loading coefficients

**Comment by plbossart** [comment]
Even for coefficients we should have a header and a syntax that identifies blob type/versions/etc. There's nothing worse than a random set of bytes, it's unmanageable.

**Comment by juimonen** [comment]
@plbossart so all the blobs we are sending have sof_abi_hdr with component specific data after it. That has abi versions etc. If you are talking about for example fir/iir specific structs, they are in sof includes and removed from kernel uapi. So if you'd like to use those in user space software, you need to somehow include sof headers.

Anyway I made this tool to help someone to create a blob, as it is requested from me all the time and as there is currently nothing more public than @singalsuo eq matlab scripts, and they are specific to eq.

I'm not trying to promote use of blobs here, I will try to modify the demux out of blob (and var array), the intent of you and @lgirdwood is now pretty clear to me. I've been just little bit hesitant to touch the demux on fw side as it is not written by me. But it seems nothing happens unless I try to do it myself :) people are busy...

**Comment by lgirdwood** [comment]
> I've been just little bit hesitant to touch the demux on fw side as it is not written by me. But it seems nothing happens unless I try to do it myself :) people are busy...

Please feel free to touch anything you like on FW side. :-)

**Comment by xiulipan** [comment]
@juimonen Would you mind add one more feature here to have another option to create a simple snd_ctl_tlv wrapper outside sof headers?

https://github.com/alsa-project/alsa-lib/blob/fb48ad9e4f6b84fd4ade689bd79e3a3c37d3e034/include/sound/uapi/asound.h#L1057-L1061
```
struct snd_ctl_tlv {
	unsigned int numid;	/* control element numeric identification */
	unsigned int length;	/* in bytes aligned to 4 */
	unsigned int tlv[0];	/* first TLV */
};
```

This will help to make the blob directly usable with alsaucm with cset-tlv

**Comment by juimonen** [comment]
@xiulipan sure will do!

**Comment by juimonen** [comment]
@xiulipan so you want this to replace the sof header, or as extra around sof header + blob?

**Comment by juimonen** [comment]
@xiulipan and btw where is this cset-tlv? Can't seem to find it? is it some chromium specific thing?

**Comment by xiulipan** [comment]
@juimonen From my test using byte blob with UCM, I found the binary accepted by SOF should be looks like
```
snd_ctl_tlv Header
sof blob Header
blob binary
```
So I would like to have another option to append a snd_ctl_tlv header.

The `cset-tlv` is something from alsaucm. 
https://github.com/alsa-project/alsa-lib/blob/fb48ad9e4f6b84fd4ade689bd79e3a3c37d3e034/src/ucm/parser.c#L537-L545
```
		if (strcmp(cmd, "cset-tlv") == 0) {
			curr->type = SEQUENCE_ELEMENT_TYPE_CSET_TLV;
			err = parse_string(n, &curr->data.cset);
			if (err < 0) {
				uc_error("error: cset-tlv requires a string!");
				return err;
			}
			continue;
		}
```

**Comment by juimonen** [comment]
@xiuli new version updated. with specifying argument -c "control_id", the tool should create snd_ctl_tlv around the blob.

**Comment by paulstelian97** [comment]
Please resubmit with "main" as PR base branch.

**Pull request closed without merging**
