### PR TITLE
RTNR: Modify used static libraries

### PR DESCRIPTION
**Pull request by MingJenTai**
With the version released in 20220728, some libraries are removed or renamed.

### CODE REVIEW

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by lgirdwood** [comment]
@wszypelt fyi - not expecting this PR to fail copier/IPC4 test as this updates the RTNR version (so could fail any test that uses RTNR).

**Comment by wszypelt** [comment]
@lgirdwood I turned on the re-tests, I will watch what goes wrong now.

**Pull request merged**
