### PR TITLE
cavs: update xtensa headers

### PR DESCRIPTION
**Pull request by tlauda**
Updates xtensa headers to match real core capabilities.

Signed-off-by: Tomasz Lauda <tomasz.lauda@linux.intel.com>

### CODE REVIEW

**Comment by tlauda** [comment]
@lgirdwood I think there are some registers missing from overlays.

**Comment by lgirdwood** [comment]
@tlauda looks like some HIFI registers are being restored when GCC is used
```
/home/sof/work/sof.git/src/arch/xtensa/up/xtos/core-restore.S: Assembler messages:
/home/sof/work/sof.git/src/arch/xtensa/up/xtos/core-restore.S:233: Error: unknown opcode or format name 'wur.ae_cw_sd_no'
/home/sof/work/sof.git/src/arch/xtensa/up/xtos/core-restore.S:233: Error: unknown opcode or format name 'wur.ae_cend0'
/home/sof/work/sof.git/src/arch/xtensa/up/xtos/core-restore.S:233: Error: unknown opcode or format name 'ae_l64.i'
/home/sof/work/sof.git/src/arch/xtensa/up/xtos/core-restore.S:233: Error: unknown opcode or format name 'ae_l64.i'
/home/sof/work/sof.git/src/arch/xtensa/up/xtos/core-restore.S:233: Error: unknown opcode or format name 'ae_l64.i'
/home/sof/work/sof.git/src/arch/xtensa/up/xtos/core-restore.S:233: Error: unknown opcode or format name 'ae_l64.i'
/home/sof/work/sof.git/src/arch/xtensa/up/xtos/core-restore.S:233: Error: unknown opcode or format name 'ae_l64.i'
/home/sof/work/sof.git/src/arch/xtensa/up/xtos/core-restore.S:233: Error: unknown opcode or format name 'ae_l64.i'
/home/sof/work/sof.git/src/arch/xtensa/up/xtos/core-restore.S:233: Error: unknown opcode or format name 'ae_l64.i'
/home/sof/work/sof.git/src/arch/xtensa/up/xtos/core-restore.S:233: Error: unknown opcode or format name 'ae_l64.i'
/home/sof/work/sof.git/src/arch/xtensa/up/xtos/core-restore.S:233: Error: unknown opcode or format name 'ae_l64.i'
/home/sof/work/sof.git/src/arch/xtensa/up/xtos/core-restore.S:233: Error: unknown opcode or format name 'ae_l64.i'
/home/sof/work/sof.git/src/arch/xtensa/up/xtos/core-restore.S:233: Error: unknown opcode or format name 'ae_l64.i'
/home/sof/work/sof.git/src/arch/xtensa/up/xtos/core-restore.S:233: Error: unknown opcode or format name 'ae_l64.i'
/home/sof/work/sof.git/src/arch/xtensa/up/xtos/core-restore.S:233: Error: unknown opcode or format name 'ae_l64.i'
/home/sof/work/sof.git/src/arch/xtensa/up/xtos/core-restore.S:233: Error: unknown opcode or format name 'ae_l64.i'
/home/sof/work/sof.git/src/arch/xtensa/up/xtos/core-restore.S:233: Error: unknown opcode or format name 'ae_l64.i'
/home/sof/work/sof.git/src/arch/xtensa/up/xtos/core-restore.S:233: Error: unknown opcode or format name 'ae_l64.i'
/home/sof/work/sof.git/src/arch/xtensa/up/xtos/core-restore.S:233: Error: unknown opcode or format name 'ae_lalign64.i'
/home/sof/work/sof.git/src/arch/xtensa/up/xtos/core-restore.S:233: Error: unknown opcode or format name 'ae_lalign64.i'
/home/sof/work/sof.git/src/arch/xtensa/up/xtos/core-restore.S:233: Error: unknown opcode or format name 'ae_lalign64.i'
/home/sof/work/sof.git/src/arch/xtensa/up/xtos/core-restore.S:233: Error: unknown opcode or format name 'ae_lalign64.i'
```
We probably want to surround this with XCC check.

**Comment by jajanusz** [comment]
@lgirdwood Are you sure gcc toolchain is ok this time? Few months ago it didn't even support threadptr, it has some totally weird core definition for apl.

**Comment by lgirdwood** [comment]
@jajanusz does the same code build for CNL ? if so, GGC needs updated else it's HIFI

**Comment by jajanusz** [comment]
> @jajanusz does the same code build for CNL ? if so, GGC needs updated else it's HIFI

When I look at travis CI only APL is red. The one gcc toolchain that has problems usually ;p

**Comment by jajanusz** [comment]
@lgirdwood It may be also because CNL is using SMP and APL is UP and problem is in files related to up arch...

**Comment by jajanusz** [comment]
> @lgirdwood It may be also because CNL is using SMP and APL is UP and problem is in files related to up arch...

Nvm, CNL works for both UP & SMP, so it's more likely something with a toolchain.

**Comment by tlauda** [comment]
@jajanusz @lgirdwood This patch actually uncovered some other issue with missing hal state definitions for cAVS >= 1.8 platforms (see #1369). Now it will fail for every platform for gcc. The missing registers are probably HiFi 3 specific, but it doesn't change the fact, that similar HiFi 2 registers are properly detected by gcc e.g. `ae_sp24x2s.i`. I'm still suspecting toolchain issue.

**Comment by tlauda** [comment]
@lgirdwood @jajanusz Still failed only for APL, so it seems gcc issue.

**Comment by lgirdwood** [comment]
@jajanusz @tlauda just checked gas and APL uses older version from Cadence compared to CNL version. Will update both to use latest version (and headers in this PR).
@tlauda can you do a temporary XCC check for APL so we dont break CI, we can then remove after APL GCC is fixed and updated in next few days.

**Pull request merged**
