### PR TITLE
Dw dma cosmetic

### PR DESCRIPTION
**Pull request by lyakh**

### CODE REVIEW

**Comment by wenqingfu** [comment]
BYT and APL is not in good shape to verify new things on top of it are good. @stevyan @markyang to see if they can build/test out of the cycle of daily regression test in their own environment.

**Comment by lgirdwood** [comment]
@lyakh can you check CI errors.

**Comment by lyakh** [comment]
@lgirdwood you mean check this link https://quickbuild.igk.intel.com/build/3418777 ? I'm not authorised to open it.

**Comment by lyakh** [comment]
@lgirdwood The CI error, reported in this PR is because version.h was missing. I wasn't able to identify what exactly kind of build was attempted. I know, that I get that error when I try to configure and build rimage separately, then I have to run version.sh manually to work around it. Is that also what happened here?

**Comment by lgirdwood** [comment]
@lyakh version.h is not connected with this PR so not sure why it may fail. Have you tried restarting CI. @zrombel any comments on the CI ?

**Comment by lgirdwood** [comment]
@lyakh please don't close PRs and repush the same code as a new PR. Just force push any updates, that way we can keep the history prior to merge.

**Comment by lyakh** [comment]
@lgirdwood yep, sorry, as explained in the ML - my mistake, I thought deleting+repushing would have the same effect as "--force." Now I know it doesn't...

**Pull request closed without merging**
