### PR TITLE
[TEST ONLY] Use SRC DP module

### PR DESCRIPTION
**Pull request by yongzhi1**

### CODE REVIEW

**Review by lgirdwood — COMMENTED** [review]
@singalsu pls review.
@yongzhi1 good stuff, should we keep the volume too ?

**Comment by yongzhi1** [comment]
> @yongzhi1 good stuff, should we keep the volume too ?
The two gain module are kept, since SRC is the only DP-compatible module right now, I am using it as a ref for DP multi-core support.

**Comment by lgirdwood** [comment]
@marcinszkudlinski I assume the topology usage above is good for you ?

**Comment by marcinszkudlinski** [comment]
yes, topology looks good, but some issues found, working with @yongzhi1 to resolve.

**Review by singalsu — APPROVED** [review]

**Comment by yongzhi1** [comment]
Thanks @marcinszkudlinski for the great support, SRC as DP scheduling module tested working on core 2 now, so this PR served its purpose. Let me close and move the focus to https://github.com/thesofproject/sof/pull/8308, thanks!!

**Pull request closed without merging**
