### PR TITLE
dw_dma: Remove redundant write pointer increment

### PR DESCRIPTION
**Pull request by ktrzcinx**
Function dw_dma_increment_pointer is called in each
dw_dma_copy and moves write pointer by number of passed
bytes a priori. Its why this function shouldn't be called
after dma stops before whole transmission ends.
It leads to misalignment in data stored in any queue between
source buffer and output, with data written to this interface
and glitch when first data after release command come.

Signed-off-by: Karol Trzcinski <karolx.trzcinski@linux.intel.com>

### CODE REVIEW

**Comment by paulstelian97** [comment]
You have split your PR but, given that I don't understand exactly how the hardware works, I'll ask if this one even makes sense as standalone. Just to be sure.

**Comment by ktrzcinx** [comment]
@paulstelian97 After split each PR should have sense as standalone, in sense any of them should brake  code functionality, but only after merging each of them bug will be fix'ed (except one PR with code readability improvements)

**Comment by paulstelian97** [comment]
Alright, maybe I could learn how to do proper pause/release for the i.MX DAIs as well from this :)

**Comment by lgirdwood** [comment]
@xiulipan @fredoh9 for some reason I'm seeing lots of not tested in CI. Can we fix.

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by ktrzcinx** [comment]
SOFCI TEST

**Comment by jajanusz** [comment]
jenkins CI just only failed on kmod load/unload that are not related to this pr, so it can be merged

**Pull request merged**
