### PR TITLE
Topology: Add support for MAX98390 echo reference capture

### PR DESCRIPTION
**Pull request by macchian**
codec chip playback loopback to capture stream.

Signed-off-by: Mac Chiang <mac.chiang@intel.com>

### CODE REVIEW

**Review by plbossart — APPROVED** [review]

**Review by lgirdwood — APPROVED** [review]

**Comment by marc-hb** [comment]
Github Actions hang fixed by #3992, please git commit --amend and force push if you want to re-trigger.

**Comment by plbossart** [comment]
@lgirdwood the matching kernel patch is upstream, can we merge this?

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by lgirdwood** [comment]
@plbossart we had a CI timeout yesterday and had to restart some CI jobs.

**Comment by plbossart** [comment]
> @plbossart we had a CI timeout yesterday and had to restart some CI jobs.

fails on the kernel side as well, what a mess.

**Comment by lgirdwood** [comment]
@zrombel are we good to merge, CI seems to be pending a long time ?

**Pull request merged**
