### PR TITLE
Revert 1 master

### PR DESCRIPTION
**Pull request by mh12gx2825**
Reverting the last wrong merge.

### CODE REVIEW

**Comment by cujomalainey** [comment]
Please provide a more detailed title and description, such as "what are you reverting" and "why it is broken"

**Comment by mh12gx2825** [comment]
I think I did a merge from upstream/master into one of my local branches instead of local master and then ended up pushing that as a change into my repo along with the other code change I did. That completely got my branches out of sync and I can no more create a clean new branch.
I got a new repo setup now and would send in the code changes afresh that are being lost.

**Comment by cujomalainey** [comment]
@mh12gx2825 I recommend learning some git workflows, here is an example source https://learngitbranching.js.org/?locale=en_US

Then reopen this once you get your branches inorder.

**Comment by lgirdwood** [comment]
@mh12gx2825 dont worry, you cant break master. I will close this sine it's local to you and not on master. Sounds like you need to locally rebase.

**Pull request closed without merging**
