### PR TITLE
zephyr: Test Zephyr pm changes [DNM]

### PR DESCRIPTION
**Pull request by ceolin**
Test Zephyr changes in intel-adsp pm.

### CODE REVIEW

**Comment by ceolin** [comment]
Please DO NOT MERGE. It is for testing purpose.

**Comment by sofci** [comment]
Can one of the admins verify this patch?
> reply **test&nbsp;this&nbsp;please** to run this test once

**Comment by kv2019i** [comment]
Thanks @ceolin . The error with https://github.com/thesofproject/sof/actions/runs/9100669691/job/25016037131?pr=9126 can be ignored, that's caused by regression in the Zephyr baseline you used (https://github.com/thesofproject/sof/issues/9101 , now fixed in Zephyr main).

Let's wait for the on-device tests to complete.

**Comment by ceolin** [comment]
@kv2019i I have rebased my PR and fixed `sparse` complains. Can you trigger CI again ?

**Comment by ceolin** [comment]
@marc-hb ^

**Comment by marc-hb** [comment]
> Can you trigger CI again ?

The only way to re-run _everything_ again is to (force)push and only you @ceolin can push to the branch `ceolin:zephyr/pm`.

So the fastest way to re-run everything is:

```
git checkout your_remote/zephyr/pm
git commit --amend -C HEAD # bump the date and SHA1
git push -f ...
```

**Comment by kv2019i** [comment]
SOFCI TEST

**Comment by kv2019i** [comment]
@ceolin @marc-hb Something else wrong as well, the "sof-ci/jenkins/pr-build" did not compelte (no error either). Let me try to rekick parts of the CI. If this fails, please @ceolin re-push this SOF PR to rekick the whole thing.

**Comment by kv2019i** [comment]
Ok, now looks better, no need to repush. The "sof-ci/jenkins/pr-device-test/*" tests look good. Known issue on LNL (in https://sof-ci.01.org/sofpr/PR9126/build4706/devicetest/index.html ) , but otherwise looks good as on par with SOF mainline results.

The "Intel CI System/merge/*" tests still running, so let's see their results, but if those are also good, seems the Zephyr PR is good to go.

**Comment by marc-hb** [comment]
> Ok, now looks better, no need to repush. 

There's a ton of red on the last run. Some known issues which have been fixed, others more mysterious.

A fresh push would provide a much clearer picture.

https://github.com/thesofproject/sof/actions/runs/9100669711/job/25016041801?pr=9126

```
/zep_workspace/sof/src/audio/base_fw_intel.c:132:39: error: implicit declaration of function 'HPSRAM_REGS' [-Werror=implicit-function-declaration]
  132 |                 tuple_data[index++] = HPSRAM_REGS(i)->HSxPGCTL;
      |                                       ^~~~~~~~~~~
```

**Pull request closed without merging**
