### PR TITLE
Revert the EQ IIR conversion

### PR DESCRIPTION
**Pull request by ranj063**
Will be resubmitted after rootcausing the failures

FIxes https://github.com/thesofproject/sof/issues/6020

### CODE REVIEW

**Comment by fredoh9** [comment]
I quickly checked on my ADLP_RVP_NOCODEC, with this revert, it works fine (as expected)

**Review by fredoh9 — APPROVED** [review]

**Review by plbossart — APPROVED** [review]

**Comment by marc-hb** [comment]
> FIxes https://github.com/thesofproject/sof/issues/6020

Not #6022?

**Comment by ranj063** [comment]
> > FIxes #6020
> 
> Not #6022?

yes, probably also #6022

**Comment by marc-hb** [comment]
While this reverts seems to help a lot (many more tests passing), there is still a severe firmware crash in:

https://sof-ci.01.org/softestpr/PR930/build98/devicetest?model=ADLP_RVP_NOCODEC&testcase=multiple-pause-resume-5

Disclaimer: I haven't look at the regressions #6020 and #6022 in detail nor any difference between them.

**Comment by ranj063** [comment]
> While this reverts seems to help a lot (many more tests passing), there is still a severe firmware crash in:
> 
> https://sof-ci.01.org/softestpr/PR930/build98/devicetest?model=ADLP_RVP_NOCODEC&testcase=multiple-pause-resume-5
> 
> Disclaimer: I haven't look at the regressions #6020 and #6022 in detail nor any difference between them.

@marc-hb my suspicion is we likely 2 separate regressions. One due to my PR and these ones likely due to something else.

**Comment by marc-hb** [comment]
And now https://sof-ci.01.org/sofpr/PR6031/build925/devicetest/ is all green... go figure.

**Pull request merged**
