### PR TITLE
topology: sof-adl-max98360a-rt5682-waves: add new topology

### PR DESCRIPTION
**Pull request by malik-hsu**
Add support for max98360a speaker amplifiers with waves function.

Signed-off-by: Malik_Hsu <malik_hsu@wistron.corp-partner.google.com>

### CODE REVIEW

**Comment by sofci** [comment]
Can one of the admins verify this patch?
> reply **test&nbsp;this&nbsp;please** to run this test once

**Comment by gkbldcig** [comment]
Can one of the admins verify this patch?

**Comment by lgirdwood** [comment]
SOFCI TEST

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
test this please

**Comment by lgirdwood** [comment]
Lest see if CI will retest and run. Not sure why it was partial result.

**Comment by lgirdwood** [comment]
@kkarask @wszypelt CI seems to be blocked, can you check. I've tried to run the test manually and with the "test please this" reply. Thanks !

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by lgirdwood** [comment]
ADL RVP failed to load PCMs - rerun since this topology is ADL.

**Pull request merged**
