### PR TITLE
Dmic 16k capture with vol

### PR DESCRIPTION
**Pull request by libinyang**
This PR add support dmic 16khz recording. this is to fix https://github.com/thesofproject/sof/issues/1278

### CODE REVIEW

**Comment by libinyang** [comment]
This PR is an enhancement of https://github.com/thesofproject/sof/pull/1271

**Comment by jajanusz** [comment]
@libinyang Sorry I got a bit lost.
Is this the only fix needed for #1278 ?
If that's enchancement of #1271 why is it closed? 
If you change something that is already addressed in 1 PR please keep it here, because I don't know if it needs previous one of it is total replacement + something more.

**Comment by jajanusz** [comment]
@libinyang Also #1278 notes that there is no vol for 16&32 and this PR fixes 16b, so it's not full fix for #1278 right?

**Comment by libinyang** [comment]
@jajanusz There are 2 DMICs. One is 48KHz and 32bit. Another is 16KHz and 16bit (maybe we still need support 32bit @RanderWang is working on it) and the patch for 48KHz and 32bit has already been merged into sof.

> @libinyang Also #1278 notes that there is no vol for 16&32 and this PR fixes 16b, so it's not full fix for #1278 right?

**Comment by libinyang** [comment]
@jajanusz  I should not close that PR. Sorry for the inconvenience. 

> @libinyang Sorry I got a bit lost.
> Is this the only fix needed for #1278 ?
> If that's enchancement of #1271 why is it closed?
> If you change something that is already addressed in 1 PR please keep it there, because I don't know if it needs previous one of it is total replacement + something more.

**Comment by libinyang** [comment]
@jajanusz updated. Thanks.

**Comment by jajanusz** [comment]
@xiulipan I see here on GH: `sof-ci/jenkins/pr-device-test — On-device Test Failed:Test Execption` but when I click **Details** there is SUCCESS everywhere, so I guess that's just some reporting issue

**Comment by jajanusz** [comment]
@xiulipan I see that message is right and Tester itself failed because there are only 1 column for last category of tests

**Comment by xiulipan** [comment]
@jajanusz 
I think something wrong inside CI steps is there. Will check and try to fix it then re-trigger the test.

**Comment by lgirdwood** [comment]
@zrombel could you check code scan, not sure why it would fail for topologies

**Pull request merged**
