### PR TITLE
topology: sof-adl-max98360a-rt5682-waves: add new topology

### PR DESCRIPTION
**Pull request by malik-hsu**
Add support for max98360a speaker amplifiers with waves function.

Signed-off-by: Malik_Hsu <malik_hsu@wistron.corp-partner.google.com>

### CODE REVIEW

**Comment by sofci** [comment]
Can one of the admins verify this patch?
> reply **test&nbsp;this&nbsp;please** to run this test once

**Comment by gkbldcig** [comment]
Can one of the admins verify this patch?

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
test this please

**Comment by lgirdwood** [comment]
Not sure why we get 2 message to approve this PR for CI to test, but test request sent above to CI.

**Comment by lgirdwood** [comment]
@mwasko fyi
@malik-hsu is this in main branch ? If not we will need a PR for main. Thanks.

**Comment by malik-hsu** [comment]
> No, this is in adl-003-drop-stable branch. I will send another PR for the main branch.

**Comment by lgirdwood** [comment]
Restarted CI for main branch PR.

**Comment by lgirdwood** [comment]
@mwasko @abonislawski fyi to merge.

**Pull request merged**
