### PR TITLE
component: do not reset component status in the case of xrun

### PR DESCRIPTION
**Pull request by ranj063**
Do not reset component status in the case of xrun.
An irrecoverable xrun will lead to the pipeline being
stopped by the host and resetting the status will result
in an error stating invalid current state during the STOP
trigger.

Signed-off-by: Ranjani Sridharan <ranjani.sridharan@linux.intel.com>

### CODE REVIEW

**Review by lgirdwood — APPROVED** [review]
Good find, how did this show up ?

**Comment by ranj063** [comment]
> Good find, how did this show up ?

its been around for a while @lgirdwoo. Every single xrun has shown this error so far but we just didnt fix it before

**Comment by lgirdwood** [comment]
@ranj063 looks like the UT is failing (but I suspect the UT also needs updated in this case).
```

98% tests passed, 1 tests failed out of 40

Total Test time (real) =  13.46 sec

The following tests FAILED:
	  5 - comp_set_state (Failed)
Errors while running CTest
```
Btw you should be able to run this UT on host uisng ```./scripts/run-mocks.sh``` and this will allow you to test the UT fix.

**Review by lgirdwood — APPROVED** [review]
Btw, does this change the pipeline finite state machine ?

**Comment by plbossart** [comment]
I was hoping this PR would clarify my understanding of how XRUNS are handled in the firmware, but nope it looks we are still in special case and dead code territory?

````
static int ipc_stream_trigger(uint32_t header)
{
[...]
	/* XRUN is special case- TODO */ <<<<<<<???
	case SOF_IPC_STREAM_TRIG_XRUN:
		return 0;


/*
 * This flag disables firmware-side xrun recovery.
 * It should remain enabled in the situation when the
 * recovery is delegated to the outside of firmware.
 */
#define NO_XRUN_RECOVERY 1

[...]

#if NO_XRUN_RECOVERY
/* recover the pipeline from a XRUN condition */
int pipeline_xrun_recover(struct pipeline *p)
{
	return -EINVAL;
}

#else
/* recover the pipeline from a XRUN condition */ <<< Dead code.
int pipeline_xrun_recover(struct pipeline *p)
{
	int ret;

	pipe_err(p, "pipeline_xrun_recover()");

	/* prepare the pipeline */
	ret = pipeline_prepare(p, p->source_comp);
	if (ret < 0) {
		pipe_err(p, "pipeline_xrun_recover(): pipeline_prepare() failed, ret = %d",
			 ret);
		return ret;
	}

	/* reset xrun status as we already in prepared */
	p->xrun_bytes = 0;

	/* restart pipeline comps */
	ret = pipeline_trigger(p, p->source_comp, COMP_TRIGGER_START);
	if (ret < 0) {
		pipe_err(p, "pipeline_xrun_recover(): pipeline_trigger() failed, ret = %d",
			 ret);
		return ret;
	}

	return 0;
}
#endif


````

**Comment by lgirdwood** [comment]
@plbossart fwiw this is on my and @juimonen todo list for v1.8+ and codec adapter integration.

**Review by plbossart — APPROVED** [review]
Approving since it's confirmed this PR fixes https://github.com/thesofproject/sof/issues/4066

**Comment by ranj063** [comment]
> Approving since it's confirmed this PR fixes #4066

@plbossart this wont fix #4066. But it will prevent IPC error during the STOP trigger in the case of an xrun. Why the xrun happened is the next question.

**Comment by plbossart** [comment]
> > Approving since it's confirmed this PR fixes #4066
> 
> @plbossart this wont fix #4066. But it will prevent IPC error during the STOP trigger in the case of an xrun. Why the xrun happened is the next question.

oh well. I understood the bug report as 'something is broken', but it's really 'it's more broken than before'. I am not very good with  multi-level logic...

**Comment by lgirdwood** [comment]
@zrombel @kkarask @wszypelt anything wrong with CI here ? the failed test logs are not loading ?

**Comment by wszypelt** [comment]
@lgirdwood we had a network issue, rebuild success.

**Comment by lgirdwood** [comment]
Jenkins showing a DUT that has failed to boot.

**Pull request merged**
