### PR TITLE
Topology: Add ASRC capture pipe for WM8804 SPDIF input

### PR DESCRIPTION
**Pull request by singalsu**
This patch adds capture PCM with ASRC for capturing from SPDIF
input of WM8804 codec. This topology is used mainly for testing
of a bi-directional ASRC connected slave-DAI.

Signed-off-by: Seppo Ingalsuo <seppo.ingalsuo@linux.intel.com>

### CODE REVIEW

**Comment by plbossart** [comment]
@singalsu do you have a mechanism for this duplex case to have a single drift tracking loop?

**Comment by singalsu** [comment]
> @singalsu do you have a mechanism for this duplex case to have a single drift tracking loop?

No there isn't such. In fact I think now simultaneous play and capture compete of the same HW resource. The ASRC instances on same DAI should use common drift tracking, the one who started first should be the "server" and there should be task handover when the first quits and second needs to continue. Probably the server ASRC could just update the drift factor to DAI timestamp handle. If it's being updated the other ASRC can just grab it.

This has been on my list of things to do but I've held while no real ASRC usage has shown up. Should I increase priority to do that?

**Comment by lgirdwood** [comment]
> This has been on my list of things to do but I've held while no real ASRC usage has shown up. Should I increase priority to do that?

No objection from me. Btw, will this help BT use cases with different time domains  ?

**Comment by lgirdwood** [comment]
Looks like a Travis timeout on qemu boot test.

**Comment by singalsu** [comment]
> > This has been on my list of things to do but I've held while no real ASRC usage has shown up. Should I increase priority to do that?
> 
> No objection from me. Btw, will this help BT use cases with different time domains ?

Yes, it's needed if BT is on different time domain. The amount of work is small. Though for current/next platforms it looks like BT is slave so no ASRC need with it.

**Comment by lgirdwood** [comment]
> > > This has been on my list of things to do but I've held while no real ASRC usage has shown up. Should I increase priority to do that?
> > 
> > 
> > No objection from me. Btw, will this help BT use cases with different time domains ?
> 
> Yes, it's needed if BT is on different time domain. The amount of work is small. Though for current/next platforms it looks like BT is slave so no ASRC need with it.

Please proceed with adding this feature. I'll pencil in for v1.6

**Comment by singalsu** [comment]
Yep, I can start after I've solved the ASRC capture glitch issue that I'm doing now.

**Pull request merged**
