### PR TITLE
scripts: update sof_builder docker with imx8m support

### PR DESCRIPTION
**Pull request by dbaluta**
Add imx8m cross compiler in sof_builder docker build file.

Signed-off-by: Daniel Baluta <daniel.baluta@nxp.com>

### CODE REVIEW

**Comment by mihaix** [comment]
@lgirdwood can you also update the docker hub image? Thanks.

**Comment by dbaluta** [comment]
@xiulipan can you help us on updating the docker hub image?

**Comment by xiulipan** [comment]
@dbaluta I am working on it now. I will test locally before I update the docker image on docker hub.

**Comment by xiulipan** [comment]
@dbaluta could you try to add Travis patch for imx8m build and test? The docker image is updated.

**Comment by dbaluta** [comment]
@xiulipan done https://github.com/thesofproject/sof/pull/2437

**Pull request merged**
