### PR TITLE
Revert accidental rimage downgrade in "topology: mirror CML topologie…

### PR DESCRIPTION
**Pull request by marc-hb**
…s for TGL"

Supersedes #3200 with more details.

This partially reverts commit 1a8ed6dfd08971642 PR #3184,
merged on Wed Jul 15 15:22:50 2020 +0100. This reverts just the
rimage part of it.

Commit 1a8ed6dfd08 downgraded rimage from:
from most recent   7317f2af39019 ("manifest: set feature mask to 0xffff")
to 3 commits older 9f3f2d7d7149  ("headers: Use full path to header")

This upgrades rimage again to newer 7317f2af39019

Hopefully fixes (again): #3173

Useful command for these situations:
```shell
  cd sof; git log -p -- rimage
```
Signed-off-by: Marc Herbert <marc.herbert@intel.com>

### CODE REVIEW

**Comment by marc-hb** [comment]
checkpatch is unsurprisingly not happy to see so many SHA1s. No other checkpatch warning.

Thanks  for expediting this review but please do review it carefully because of the following pain scale:

- medium submodule pain level: normal submodule usage
- high pain submodule pain level: a fix like this one
- unbearable submodule pain level: _failing_ a fix like this one

**Comment by marc-hb** [comment]
sof-ci/jenkins/pr-device-test has only failure of one test on one device: the test that reloads the driver. I don't think that can be caused by some rimage changes.

**Comment by lgirdwood** [comment]
@xiulipan good for you ? Is riamge now aligned for TGL ?

**Comment by lgirdwood** [comment]
CI known issue.

**Pull request merged**
