### PR TITLE
Zephyr sched

### PR DESCRIPTION
**Pull request by lyakh**
Fixes corrupted HDMI audio with underruns on Up2 with Zephyr

### CODE REVIEW

**Review by lgirdwood — COMMENTED** [review]
It looks like all the changes are contained within ``` __ZEPHYR__``` conditional ? Can you confirm ?

**Comment by lyakh** [comment]
> It looks like all the changes are contained within ` __ZEPHYR__` conditional ? Can you confirm ?

@lgirdwood that's correct.

**Comment by lgirdwood** [comment]
Looks like Jenkins has stalled - restart CI

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by lgirdwood** [comment]
SOFCI TEST

**Review by lgirdwood — APPROVED** [review]

**Pull request merged**
