### PR TITLE
rimage: change feature mask to 0x1ff to support CML

### PR DESCRIPTION
**Pull request by sathyap-chrome**
Signed-off-by: Sathya Prakash M R <sathya.prakash.m.r@intel.com>

### CODE REVIEW

**Comment by sathyap-chrome** [comment]
I think this needs to be verified on all platforms supported earlier - ICL, GLK.

**Comment by xiulipan** [comment]
@lgirdwood 
It seems for BYT and APL there is no influence to change mask from 0xFF to 0x1FF, they can both boot from the on-device test. They may just ignore the highest bit. 
If in that case, we will need some configurable mask for different platforms rather than change them all to a static value.

**Comment by lgirdwood** [comment]
@xiulipan yep, just needs validated on CAVS 1.8+

**Comment by xiulipan** [comment]
@stevyan @DarrenxWang @xun2z 
Could you help to check the binary from this PR on one of CNL, WHL, ICL.

@lgirdwood 
I still think this should be configurable value instead of static value. It will confusing people that we set it to be 0x1ff

**Comment by plbossart** [comment]
Is this an ABI change?

**Comment by RanderWang** [comment]
> Is this an ABI change?

This patch changes the version number of  FW format. @xiulipan   am I right ?

**Comment by tlauda** [comment]
It changes feature mask which is internal thing between fw and rom.

**Comment by RanderWang** [comment]
> It changes feature mask which is internal thing between fw and rom.

@tlauda   Thank you!

**Comment by xiulipan** [comment]
@RanderWang @plbossart 
It more like some manifest value change only influence the signing. And I still insist to make it a variable or a platform specific value.

**Comment by jajanusz** [comment]
> Please make this a platform specific value as it is only changed to 0x1FF on CML only.

It's not even platform-family specific - you have cavs 1.8 that has values from 1f to 1ff.
Maybe it should be just a parameter to RIMAGE ?

**Comment by lgirdwood** [comment]
@sathyap-chrome @jajanusz rather than a rimage cmd line parameter or hard code mask, we should hard code it into our rimage machine/platform table and automatically use the correct mask i.e.
```c
const struct adsp machine_apl = {
	.name = "apl",
	.mem_zones = {
		[SOF_FW_BLK_TYPE_ROM] = {
			.base = ADSP_APL_DSP_ROM_BASE,
			.size = ADSP_APL_DSP_ROM_SIZE,
		},
		[SOF_FW_BLK_TYPE_SRAM] = {
			.base = APL_DSP_BASE_ENTRY,
			.size = 0x100000,
		},
	},
	.image_size = 0x100000,
	.dram_offset = 0,
	.machine_id = MACHINE_APOLLOLAKE,
	.write_firmware = man_write_fw_v1_8,
	.write_firmware_meu = man_write_fw_meu_v1_8,
	.man_v1_8 = &apl_manifest,
        .feature_mask = XXXXX   <<<<<<<<<<<<<<<<<<<<<< Add here
};
```

**Comment by sathyap-chrome** [comment]
Thanks for suggestion @lgirdwood 
Will update tomorrow.

**Comment by jajanusz** [comment]
@lgirdwood Problem is that for something that is the same platform functionally like CNL==CML,  you have 2 different feature masks.
To be 100% fine you should use 1f for CNL and 1ff for CML, we had 1f globally before ICL, in ICL we changed it to ff, now we change it to 1ff, also for all.
Feature mask went in the bad direction and is misused, so if it's not respected anyway as it should.

TBH you can be kinda future-proof and set it to 0xFFFFFFFF ;)
It will work for all current roms... Because it's masked in the rom code before comparing.
So if it's not respected anyway we can use what Sathya propsed or even extend it to set all bits to 1 no matter what, but IDK if I missed something what HW designers inteded to achieve.

**Comment by lgirdwood** [comment]
@jajanusz ok, thanks for the explanation of usage. So if ROM is also masking the we are good we are good to merge this as it stands ?

**Comment by jajanusz** [comment]
> @jajanusz ok, thanks for the explanation of usage. So if ROM is also masking, then we are good to merge this as it stands ?

It is good to merge because this field doesn't work as intended by hw/fw/rom designers. If it was working as intended we would HAVE TO pass it as argument, now it just doesn't matter so there is no point in making process more complicated for things that don't work anyway.

**Comment by lgirdwood** [comment]
@jajanusz fair enough

**Pull request merged**
