### PR TITLE
xtensa-build-zephyr.py: don't pass -c $plat.toml to rimage 

### PR DESCRIPTION
**Pull request by marc-hb**
3 commits; separately tested in TEST PRs #8600 and #8601

This is a preliminary step for .toml modularization (#8490)

### CODE REVIEW

**Comment by marc-hb** [comment]
@wszypelt , @lrudyX , all TGL tests failed with "connection refused" in https://sof-ci.01.org/sof-pr-viewer/#/build/PR8602/build13255103, can you please take a look?

Same errors in https://sof-ci.01.org/sof-pr-viewer/#/build/PR8601/build13254936

(the build was fine)

```
...
20:33:59,018 INFO  - INTERNALERROR> File "/usr/local/lib/python3.10/dist-packages/execnet/multi.py", line 138, in makegateway
20:33:59,018 INFO  - INTERNALERROR> io = gateway_socket.create_io(spec, self, execmodel=self.execmodel)
20:33:59,018 INFO  - INTERNALERROR> File "/usr/local/lib/python3.10/dist-packages/execnet/gateway_socket.py", line 92, in create_io
20:33:59,018 INFO  - INTERNALERROR> sock.connect((host, port))
20:33:59,018 INFO  - INTERNALERROR> ConnectionRefusedError: [Errno 111] Connection refused
```

**Review by lyakh — APPROVED** [review]

**Review by kv2019i — APPROVED** [review]
Wondering a bit if we need to bring some of this back later for other vendors to add IPC4 builds (on the side). Oh well, probably better do this in more generic way than this version.

This PR looks good, one mandatory CI check failing that needs to be clarified before merge.

**Comment by wszypelt** [comment]
@marc-hb we had a problem with tgl over the weekend, we managed to fix it, and the PR run shows that everything went well

**Comment by marc-hb** [comment]
Thanks @wszypelt , https://sof-ci.01.org/sof-pr-viewer/#/build/PR8602/build13257497 is now green.

> Wondering a bit if we need to bring some of this back later for other vendors to add IPC4 builds (on the side). Oh well, probably better do this in more generic way than this version.

Good point and... good point.

**Comment by marc-hb** [comment]
> Oh well, probably better do this in more generic way than this version.

With the pre-processing of .toml files, a simple `xtensa-build-zephyr.py -o myIPC4.conf` will allow adjusting their content.

**Pull request merged**
