### PR TITLE
[SKIP SOF-TEST] .github: fuzz IPC4 too

### PR DESCRIPTION
**Pull request by marc-hb**
3 commits

### CODE REVIEW

**Comment by marc-hb** [comment]
https://github.com/thesofproject/sof/actions/runs/4929778823/jobs/8809848778?pr=7579 is a known imx8m rename https://github.com/zephyrproject-rtos/zephyr/pull/57084, unrelated.

https://github.com/thesofproject/sof/actions/runs/4929778825/jobs/8809847628?pr=7579 is fuzzing IPC4!

**Review by cujomalainey — APPROVED** [review]
Thank you!

**Comment by iuliana-prodan** [comment]
> https://github.com/thesofproject/sof/actions/runs/4929778823/jobs/8809848778?pr=7579 is a known imx8m rename [zephyrproject-rtos/zephyr#57084](https://github.com/zephyrproject-rtos/zephyr/pull/57084), unrelated.
> 

@marc-hb can you please, help me a bit with this failure?

I see [here](https://github.com/thesofproject/sof/actions/runs/4929778823/jobs/8809848778?pr=7579) that is using Zephyr's revision: HEAD is now at 3e02d48e4 ("driver: adc: infineon: Adding ADC driver"), which doesn't have the commits from https://github.com/zephyrproject-rtos/zephyr/pull/57084, but it complaints on` "fatal error: nxp/nxp_imx/mimx8ml8dvnlz-pinctrl.dtsi: No such file or directory"` - this dtsi is added in [this commit](https://github.com/zephyrproject-rtos/zephyr/commit/b2f1f64f57574eb89f155f92079b93e9aed5a29f), part of the aforementioned PR.

Also, the hal_xtensa is HEAD is now at 63f6553 ("soc: rename SoCs to be consistent and match zephyr/sof"), which, the same as zephyr, doesn't have the renaming for imx8m.

I've compiled SOF with zephyr for imx8m, both with `xtensa-build-zephyr.py` from SOF (here's the [imx8m build log](https://github.com/thesofproject/sof/files/11441329/imx8m.build.log) - I have the same `zephyr `revision and `xtensa_hal `as seen [here](https://github.com/thesofproject/sof/actions/runs/4929778823/jobs/8809848778?pr=7579)) and from zephyr repo (on latest main - here's the [imx8m build log - latest zephyr.txt](https://github.com/thesofproject/sof/files/11441336/imx8m.build.log.-.latest.zephyr.txt)). 
Either way, I don't get any failures.

So, what's different here? Am I missing something?

Thank you!

**Comment by marc-hb** [comment]
"zmain" checks like https://github.com/thesofproject/sof/actions/runs/4929778823/jobs/8809848778?pr=7579 ignore the manifest, they test for compatibility with the zephyr main branch. They should be warnings not errors but Github supports only two colors.

**Comment by marc-hb** [comment]
https://sof-ci.01.org/sof-pr-viewer/#/build/PR7579/build11962909 failed with the network error below. This can be ignored, this pure Github Actions PR does not affect other tests in any way.

```
13:40:39,247 INFO  - west update
13:40:39,427 INFO  - === updating zephyr (zephyr):
13:40:39,428 INFO  - --- zephyr: initializing
13:40:39,438 INFO  - Initialized empty Git repository in /buildagent/workspace/24733/zephyr/.git/
13:40:39,445 INFO  - --- zephyr: fetching, need revision 3e02d48e4ead9978d10ee760c640bf55873f6e95
14:04:35,056 INFO  - fatal: the remote end hung up unexpectedly
14:04:35,057 INFO  - fatal: early EOF
14:04:35,058 INFO  - fatal: index-pack failed
14:04:35,069 INFO  - FATAL ERROR: command exited with status 128: fetch -f --tags -- https://github.com/zephyrproject-rtos/zephyr 'refs/heads/*:refs/west/*'
```

**Comment by iuliana-prodan** [comment]
> "zmain" checks like https://github.com/thesofproject/sof/actions/runs/4929778823/jobs/8809848778?pr=7579 ignore the manifest, they test for compatibility with the zephyr main branch. They should be warnings not errors but Github supports only two colors.
> 
> The "fix" is to not leave `sof/west.yml` trailing too far behind.

I see in CI we are doing a "select zephyr revision", but I don't see a "`west update`" after this.
There might be some modifications, in zephyr, on `west.yml` that we are not taking into consideration.
So we are changing zephyr revision, but not the hals. 

I believe we should have a `west update` after modifying the zephyr version.

**Comment by marc-hb** [comment]
> I believe we should have a west update after modifying the zephyr version.

Well spotted. However I did that in #7586 and on my workstation and it still fails the same.

This is off-topic here, let's discuss this imx8m issue in #7586

**Pull request merged**
