### PR TITLE
topology: add mandatory param checks to pcm macros

### PR DESCRIPTION
**Pull request by kv2019i**
@ranj063 Ranjani (and others) would this be close to what you had in mind? If the general approach is ok, I can extend to other APIs. For others, we had a chat about this with Ranjani and thought this could be a good general enhancement to the topology macros.

Add check on correct number of parameters to PCM macros.
This should help to catch invalid usage.

Signed-off-by: Kai Vehmanen <kai.vehmanen@linux.intel.com>

### CODE REVIEW

**Comment by ranj063** [comment]
@kv2019i Thank you, this is perfect. Only one comment, could also fix https://github.com/thesofproject/sof/issues/1165.

**Comment by kv2019i** [comment]
Ok, I think I'll do these with separate PRs as the new macro checks may trigger issues in existing topology files, so better do these one by one. 

There was a genuine bug in the first version, this second patch should be good to go. I'll do other main interfaces separately (plus address #1165)

**Comment by lgirdwood** [comment]
@kv2019i does this mean you wish to close the PR ?

**Comment by kv2019i** [comment]
@lrgirdwo wrote:
> @kv2019i does this mean you wish to close the PR ?

I was actually planning to have these merged as multiple small pull-reqs (to make it easier to tackle the CI issues), but now looking at the actual CI results and seeing how the process works, doesn't seem like such a good idea after all.

So I'll close this, and use PR1193 to merge the full set I have so far.

**Pull request closed without merging**
