### PR TITLE
Tools: Topology: Change occurrences of codec_master and codec_slave

### PR DESCRIPTION
**Pull request by singalsu**
Avoids a lot of warnings prints in topologies build.

### CODE REVIEW

**Review by ujfalusi — APPROVED** [review]
@singalsu, thank you!

**Comment by plbossart** [comment]
Last time @marc-hb did the conversion we had to revert it, I can't recall why exactly (maybe results with older alsa-lib or alsa-utils packages). Let's me sure this doesn't break anything.

**Comment by marc-hb** [comment]
This was previously reverted in #5192 because the new terms basically "crash" the older ALSA versions in a very subtle and time consuming way, see #5192 for details.

Transitions like this normally have some "overlap" period where the new term is accepted while the old one is not spamming yet. Too late I guess?

**Comment by plbossart** [comment]
with the topology2 dependency on latest bleeding alsa-lib/alsa-utils, I think we should add a dependency check on the alsa-lib package and fail the build early, rather than allow for old versions to proceed and generate bad results silently. It may annoy people who don't have the latest stuff installed but that will be safer than allowing for uncontrolled older versions to be used.

**Comment by plbossart** [comment]
@ranj063 @juimonen would you happen to know which alsa-utils/alsa-lib versions are required for the NHLT and topology2 stuff?

**Comment by singalsu** [comment]
@plbossart Topology2 build is passed by scripts/build-tools.sh if alsa-lib and alsatplg version is < 1.2.7.

**Comment by ranj063** [comment]
> @ranj063 @juimonen would you happen to know which alsa-utils/alsa-lib versions are required for the NHLT and topology2 stuff?

@plbossart we need a minimum of 1.2.7 for alsatplg for topology2 to build. In fact we have annoying problem with topology2 builds that we skip building all topology2 files if the alsatplg version is older but the warning gets lost in the sea of other build messages. Maybe we should just enforce 1.2.7 for all topology builds and force users to upgrade. What do you think?

**Comment by plbossart** [comment]
@ranj063 alsa-lib 1.2.7 was released on 2022/05/31. I have 1.2.6 on the latest Ubuntu 22.04. It'd be pushing it to *require* this dependency unilaterally.

If we require the use of 1.2.7, we also provide a solution with Docker or share the Debian packages for 1.2.7 IMHO.

**Comment by ranj063** [comment]
> @ranj063 alsa-lib 1.2.7 was released on 2022/05/31. I have 1.2.6 on the latest Ubuntu 22.04. It'd be pushing it to _require_ this dependency unilaterally.
> 
> If we require the use of 1.2.7, we also provide a solution with Docker or share the Debian packages for 1.2.7 IMHO.

I think we have updated the docker image @fredoh9 please correct me if I am wrong

**Comment by marc-hb** [comment]
> I think we should add a dependency check on the alsa-lib package and fail the build early, ... 

This can be done but it would be quite a disruptive change. This was already discussed in #5192 BTW

topology2 also requires a recent ALSA but just a reminder that is a totally unrelated problem.

> ... rather than allow for old versions to proceed and generate bad results silently. It may annoy people who don't have the latest stuff installed but that will be safer than allowing for uncontrolled older versions to be used.

Bad results are generated only with the new terms `codec_consumer`, otherwise older versions have been fine so far.

> If we require the use of 1.2.7, we also provide a solution with Docker or share the Debian packages for 1.2.7 IMHO.

Our ALSA debian packaging story "never went anywhere":
- https://github.com/thesofproject/linux/issues/2211

> I think we have updated the docker image @fredoh9 please correct me if I am wrong

Yes the container has 1.2.7, this can be checked with a single-line:

`./scripts/docker-run.sh alsatplg --version`

I find it worrying to recommend solutions that we either don't have or don't use ourselves.

I guess the 3rd option is what most current developers use:
https://thesofproject.github.io/latest/getting_started/build-guide/build-from-scratch.html#build-alsa-lib-and-alsa-utils-from-source

```
If you run into alsa-lib linking errors, try (?!) to re-build it with the libdir parameter.
...
If the gitcompile script does not work, refer to the INSTALL file for manual build instructions.
```
Not a smooth developer experience either.

**Comment by marc-hb** [comment]
What compounds the issue is the lack of incremental build. Change one topology and they ALL get rebuilt. Wait, even "better": change zero topology and they all get rebuilt. I've been wanting to fix that for a long time, should a relatively small CMake fix. Because of this issue and other incoming topology changes I will do it now.

**Comment by fredoh9** [comment]
SOF docker always up-to-date with SOF toolchain required. Last update was done on Aug 9th. ALSA version is v1.2.7

**Review by fredoh9 — APPROVED** [review]
wow, most anticipated fix. thanks!

**Review by marc-hb — CHANGES_REQUESTED** [review]
Sorry I don't think we should do this until we offer a clearer and safer ALSA experience. A couple of us wasted a lot of time last time I did this.

**Comment by singalsu** [comment]
OK, I'll close this!

> What compounds the issue is the lack of incremental build. Change one topology and they ALL get rebuilt. Wait, even "better": change zero topology and they all get rebuilt. I've been wanting to fix that for a long time, should a relatively small CMake fix. Because of this issue and other incoming topology changes I will do it now. Among others this will make the topology2 warning much more visible.

Yep. Simple command line "make" should always work from build directory

**Comment by marc-hb** [comment]
> What compounds the issue is the lack of incremental build. Change one topology and they ALL get rebuilt. Wait, even "better": change zero topology and they all get rebuilt. I've been wanting to fix that for a long time, should a relatively small CMake fix. Because of this issue and other incoming topology changes I will do it now.

Submitted in #6342 : 
>  Run ./scripts/build-tools.sh twice: the second time builds the minimum required and prints almost nothing when nothing changed.

**Comment by marc-hb** [comment]
The previous revert was 7 months ago. Since then Ubuntu 22.04 LTS got ALSA 1.2.6 as noted by @plbossart and Fedora was upgraded a long time ago. The requirement for codec_consumer is 1.2.5, so we could make 1.2.5 a hard requirement to block alsatplg corruption. It would also block debian _stable_ but who's using that? :-) And there's still our container and compiling from source.

- https://github.com/thesofproject/sof/pull/5192#issuecomment-1010724225
- https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=libatopology&searchon=names

But first please help test and review incremental build fix #6342, you should like it whatever happens here.

**Pull request closed without merging**
