### PR TITLE
numbers.h: downgrade MIN() and MAX() to unsafe versions

### PR DESCRIPTION
**Pull request by marc-hb**
_[#4002 was a completely different and rejected solution to this problem , please start the review there]_ 
 
For compatibility with Zephyr, MIN and MAX macros are downgraded to the
basic, compile-time, standard compliant and unsafe implementation.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/33567

See much longer commit messages.

### CODE REVIEW

**Comment by marc-hb** [comment]
https://sof-ci.01.org/sofpr/PR4119/build8880/devicetest is all green

The checkpatch warnings about unsafe macros are... valid https://sof-ci.01.org/sofpr/PR4119/build8880/checkpatch

**Review by lgirdwood — APPROVED** [review]
Thanks @marc-hb this moves us closer and closer to Zephyr. One thing that is also needed here is that we should have  in numbers.h and other places.
```c
#if !__ZEPHYR__
#define MIN and MAX sof version
#endif 
```
This will make sure we really are using Zephyr versions. These checks can all be removed when we remove xtos.

**Comment by marc-hb** [comment]
```
#if !__ZEPHYR__
#define MIN and MAX sof version
#endif
```
The current `#ifdef #undef` looked strange to me, I wasn't sure about it so thanks for clarifying that it should go.

I will replace it with the above after one successful daily test run on this merged PR.

**Comment by marc-hb** [comment]
Of course when https://sof-ci.01.org/sof-pr-viewer/#/build/PR4119/build6380518 is green then it's the turn of one system in https://sof-ci.01.org/sofpr/PR4119/build8897/devicetest/ to have a glitch. Can't have all planets aligned at the same time!
CML_HEL_RT5682 did not boot at all, cannot be related to this PR. Moreover the older https://sof-ci.01.org/sofpr/PR4119/build8880/devicetest with just a typo difference was all green.

=> Test are all passing.

**Review by lgirdwood — APPROVED** [review]

**Pull request merged**
