### PR TITLE
tplg parser refactoring to support other IPC versions

### PR DESCRIPTION
**Pull request by lgirdwood**
Continue with tplg parser and testbench refactoring to support multiple IPC versions.

### CODE REVIEW

**Comment by lgirdwood** [comment]
@fredoh9 @marc-hb @greg-intel do the CI containers carry the alsa-lib kernel ABI headers ?
```
-- Build files have been written to: /home/runner/work/sof/sof/tools/testbench/build_testbench/sof_parser/build
[ 52%] Performing build step for 'parser_ep'
[  7%] Building C object CMakeFiles/sof_tplg_parser.dir/tokens.c.o
-- Found Python3: /usr/bin/python3.8 (found version "3.8.10") found components: Interpreter 
-- The C compiler identification is GNU 9.4.0
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Detecting C compiler ABI info
In file included from /home/runner/work/sof/sof/tools/tplg_parser/tokens.c:19:
/home/runner/work/sof/sof/tools/tplg_parser/include/tplg_parser/tokens.h:21:10: fatal error: alsa/sound/uapi/asoc.h: No such file or directory
   21 | #include <alsa/sound/uapi/asoc.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[5]: *** [CMakeFiles/sof_tplg_parser.dir/build.make:76: CMakeFiles/sof_tplg_parser.dir/tokens.c.o] Error 1
make[4]: *** [CMakeFiles/Makefile2:83: CMakeFiles/sof_tplg_parser.dir/all] Error 2
make[3]: *** [Makefile:136: all] Error 2
make[2]: *** [CMakeFiles/parser_ep.dir/build.make:86: sof_parser/src/parser_ep-stamp/parser_ep-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:1[40](https://github.com/thesofproject/sof/runs/7931859525?check_suite_focus=true#step:6:41): CMakeFiles/parser_ep.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by marc-hb** [comment]
I have no idea sorry. @juimonen and/or @fredoh9 should know.

You can explore the image interactively with a simple `sof/scripts/docker-run.sh /bin/bash`

The list of packages in the docker image is here: https://github.com/thesofproject/sof/tree/main/scripts/docker_build/sof_builder

**Comment by lgirdwood** [comment]
Container has the headers
```
sof@f7a3cfc83173:~/work/sof.git$ ls -l /usr/include/alsa/sound/uapi/asoc.h 
-rw-r--r-- 1 root root 22550 Jun  6 15:22 /usr/include/alsa/sound/uapi/asoc.h
```
and I can locally build in my container. @fredoh9 any idea why CI container failed ?

**Comment by lgirdwood** [comment]
@fredoh9 for info Ubuntu docker is using the overlay FS by default.
```
docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 8
  Running: 3
  Paused: 0
  Stopped: 5
 Images: 5
 Server Version: 20.10.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
```
Can you check the CI container for asoc.h header ?

**Comment by marc-hb** [comment]
Mystery solved, the testbench is NOT built inside the container right now:
https://github.com/thesofproject/sof/blob/141efbd7b0e924/.github/workflows/pull-request.yml#L120

Until now there was no need to use the container.

Let me look into the various options.

**Comment by marc-hb** [comment]
- #6188 should fix it

**Comment by marc-hb** [comment]
After merging #6188 (thx!) https://github.com/thesofproject/sof/runs/8015585901 is failing with a "real" issue found by `valgrind`

**Comment by lgirdwood** [comment]
@wszypelt @lrudyX not sure why CI is reporting failure, this PR is for testbench only, so it should not impact the FW ?

**Comment by lgirdwood** [comment]
Jenkins not run. Rerun CI.

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by wszypelt** [comment]
@lgirdwood 
The problem is on the side of our machine, I have already clicked rerun and it is in the queue for execution, I think within an hour, it will be green;)

**Comment by wszypelt** [comment]
@lgirdwood 
There were still some difficulties, I hope you will get results within 30 minutes

**Review by singalsu — APPROVED** [review]
The testbench works OK for current components and I could not spot issues in the code.

**Pull request merged**
