### PR TITLE
dma: hda: playback preload phase synced with logical buffer state

### PR DESCRIPTION
**Pull request by mmaka1**
Removed dma/dsp race condition that happened within preload phase.

Min buffer size set to entire buffer to avoid dma and dsp
pointers misalignmen in case the period size is not multiple
of the hda dma burst size.

Signed-off-by: Marcin Maka <marcin.maka@linux.intel.com>

### CODE REVIEW

**Comment by mmaka1** [comment]
Full regression w/ SSP tested.
There is a limitation, when running a pipeline from hd/a to ssp, 24k,16/16,1ch and 8k,16/16,1ch works with another component (volume) inside. Pass-through option does not work due to burst size / period size misalignment on a shared buffer.

**Comment by lgirdwood** [comment]
@mmaka1 I cant read the CI failure for QB. Still good to merge ?

**Comment by jajanusz** [comment]
make[3]: *** No rule to make target '../../src/platform/apollolake/memory.c', needed by '../../src/platform/apollolake/memory.o'. Stop.

I guess it's because it's on branch that don't have fixes for UTs (after next+master merge).

**Comment by lgirdwood** [comment]
@jajanusz ok is there a pr pending ? Or is this cherry pick enough. Sorry traveling now.

**Comment by jajanusz** [comment]
@lgirdwood there is no PR it is merged already to master just not-updated branch are missing it. You can try cherry-pick and maybe trigger CI rerun for this PR

**Comment by mmaka1** [comment]
> Still good to merge ?

@lgirdwood Asked for more test of hd/a playback scenarios.

**Comment by mmaka1** [comment]
#330 fixes UT check for glk-003

**Comment by lgirdwood** [comment]
@mmaka1 just a thought, we could probably still do a passthrough pipeline if we have > 2 periods in our buffer ? This would give overlap for DMA burst size.

**Comment by ranj063** [comment]
@mmaka1 this PR fixes the metallic noise issue on my Yorp board. Thank you!

**Comment by mmaka1** [comment]
@lgirdwood Yes, being one more period ahead in the dai comp would enable unaligned formats in the pass through topology.

**Comment by lgirdwood** [comment]
@mmaka1 ok, we should enforce that in the hda gw and link drivers. i.e. they should reject any pass through ping/pong buffers

**Pull request merged**
