### PR TITLE
move test scripts to sof-test

### PR DESCRIPTION
**Pull request by xiulipan**
move test scripts that used by CI and QA to sof-test repo
https://github.com/thesofproject/sof-test

### CODE REVIEW

**Comment by plbossart** [comment]
@xiulipan this is a broken process. You don't have the same functionality in the test files, e.g. missing SoundWire support, so please make sure ALL supported modules are handled in your test repo before removing those files from the sof repo.

Make then break please.

**Comment by xiulipan** [comment]
@plbossart thanks for the reminder. It seems we missed the update for sdw support.
PR created for the missing part: https://github.com/thesofproject/sof-test/pull/38

**Comment by lgirdwood** [comment]
@xiulipan ok, please update this PR once all functionality is merged into test repo.

**Comment by jajanusz** [comment]
@xiulipan How can we know when we are ready to merge this?

**Comment by xiulipan** [comment]
@fredoh9 @keqiaozhang can we clean the scripts in sof now. I think we have them all covered in sof-test now.

**Pull request merged**
