### PR TITLE
topology: Modify RTNR to work with KWD on TGL and ADL.

### PR DESCRIPTION
**Pull request by MingJenTai**
This PR modifies RTNR to work with KWD on TGL and ADL, and removes unused RTNR 16kHz topology.
It also adds RTNR support to max98390 on ADL.

### CODE REVIEW

**Review by lgirdwood — COMMENTED** [review]
Looks like this needs to be 3 patches since the commit message say we are doing 3 different things. 
@macchian @plbossart any comments. ?

**Comment by macchian** [comment]
> Looks like this needs to be 3 patches since the commit message say we are doing 3 different things. @macchian @plbossart any comments. ?

@lgirdwood , same thoughts.  
remove 16k RTNR topology unused relevant codes as one,
then another: add 'RTNR' support in intel-generic-dmic-kwd.m4,
the other: add 'RTNR' macro for TGL and ADL.
@plbossart , any comments?

**Comment by MingJenTai** [comment]
Hi, @lgirdwood and @macchian thanks for the opinion. I created 3 separate PRs to make it clearer. Please review them instead, thank you!
https://github.com/thesofproject/sof/pull/5008
https://github.com/thesofproject/sof/pull/5009
https://github.com/thesofproject/sof/pull/5010

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
Zephyr build failure already fixed.

**Pull request merged**
