### PR TITLE
build-tools.sh: fix wrong variable names as reported by shellcheck

### PR DESCRIPTION
**Pull request by marc-hb**
2 commits

Seriously, use shellcheck.

The only reason it's not in this travis yet is because I hate copy/paste
https://github.com/marc-hb/sof-test/commit/faadb20a854834

### CODE REVIEW

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
@marc-hb can you check CI, I'm guessing it's unrelated.

**Comment by marc-hb** [comment]
Not related, they don't use these scripts and have been unfortunately failing the same in other PRs.

**Comment by lgirdwood** [comment]
@zrombel this seems unrelated - are we good to merge ?

**Comment by zrombel** [comment]
There was a platform issue. After rerun all tests result are green so this PR is good to merge.

**Pull request merged**
