### PR TITLE
tools: test: some possible minor fixes

### PR DESCRIPTION
**Pull request by keyonjie**
@singalsu I am not sure if they are correct, please help to review.

### CODE REVIEW

**Comment by keyonjie** [comment]
@singalsu without the first commit, the step is actually > 1 octave per my observation. Without the 2nd commit, the start index is actually from the 2nd and the end index is overflow.

**Review by singalsu — COMMENTED** [review]
Thanks, good catches! Your fixes look correct to me. E.g. logarithmic sweep from 1 kHz to 2 kHz with one octave step needs to have two frequencies. The previous code has computed one frequency too little. Other is change clear, the mixed tone length was off by one.

**Review by singalsu — APPROVED** [review]

**Review by ShriramShastry — APPROVED** [review]
Change looks good

**Review by ShriramShastry — APPROVED** [review]
Change looks good

**Review by aiChaoSONG — APPROVED** [review]

**Comment by keyonjie** [comment]
Thanks for review, let's merge this.

**Pull request merged**
