### PR TITLE
Topology: Add HDA config

### PR DESCRIPTION
**Pull request by bardliao**
We need to config HDA rate and channels.

This PR is similar to  https://github.com/thesofproject/sof/pull/2675 . @slawblauciak @singalsu Could you work on the FW change?

### CODE REVIEW

**Comment by lgirdwood** [comment]
@bardliao this should be the fist minor 16, can you link the kernel PR here too.

**Comment by bardliao** [comment]
> @bardliao this should be the fist minor 16, can you link the kernel PR here too.

Sure, I will do it.

**Comment by bardliao** [comment]
> @bardliao this should be the fist minor 16, can you link the kernel PR here too.

@lgirdwood It is https://github.com/thesofproject/linux/pull/2007. Thanks.

**Comment by bardliao** [comment]
> > @bardliao this should be the fist minor 16, can you link the kernel PR here too.
> 
> @lgirdwood It is [thesofproject/linux#2007](https://github.com/thesofproject/linux/pull/2007). Thanks.

BTW, we still need a corresponding FW PR. @slawblauciak @singalsu Can you work on it? Thanks

**Comment by mengdonglin** [comment]
SOF CI TEST

**Comment by lgirdwood** [comment]
CI passed previously, but now offline.

**Pull request merged**
