### PR TITLE
boards: ace30: fix SOF log level

### PR DESCRIPTION
**Pull request by abonislawski**
This will fix SOF logs build, previously INF log level was ON but at the same time log level OFF was ON

### CODE REVIEW

**Review by kv2019i — APPROVED** [review]

**Review by marcinszkudlinski — APPROVED** [review]

**Review by gbernatxintel — APPROVED** [review]

**Comment by kv2019i** [comment]
@wszypelt @abonislawski Can you check the quickbuild fail, this would otherwise be good to merge now.

**Review by ujfalusi — CHANGES_REQUESTED** [review]
this for some reason breaks ssp0 loopback

**Comment by lgirdwood** [comment]
> this for some reason breaks ssp0 loopback

Hmm, sounds like a race - have we isolated the "important" log messages needed for SSP yet ?

**Comment by kv2019i** [comment]
@ujfalusi @abonislawski update on this?

**Review by ujfalusi — APPROVED** [review]
@kv2019i, yes, this is good, the issue was in other place and a coincident

**Comment by kv2019i** [comment]
@wszypelt Can you check quickbuild?

**Comment by wszypelt** [comment]
@kv2019i quality issue in SRC at PTL_FPGA
test_01_04_src[24000-48000-32-2] 
test_01_04_src[48000-16000-32-2]
`Quality issues in 25% of audio: LowQuality (25% C1, 25% C2).`

**Comment by kv2019i** [comment]
Ack @wszypelt thank you. @dnikodem can you take a look at above? Could be a perf issue when logs are enabled, so maybe we need to keep logs disabled in the overlay for FPGA.

**Comment by kv2019i** [comment]
Merged via https://github.com/thesofproject/sof/pull/9436 instead.

**Pull request closed without merging**
