### PR TITLE
ipc4: add CMake file for topology 2.0 build

### PR DESCRIPTION
**Pull request by RanderWang**
Signed-off-by: Rander Wang <rander.wang@intel.com>

### CODE REVIEW

**Comment by marc-hb** [comment]
@ranj063 I thought you had prepared this already?

**Comment by ranj063** [comment]
> @ranj063 I thought you had prepared this already?

Thanks @marc-hb . @RanderWang this is not based on the lates tplg2.0 version that's up stream isnt it? Can you please align wih @aiChaoSONG

**Comment by RanderWang** [comment]
@aiChaoSONG where is the latest one ?

**Comment by aiChaoSONG** [comment]
@RanderWang Ranjani alrealdy has the CMake files, but not upstreamed, check the CMake files here https://github.com/ranj063/sof/tree/topic/topology2-wip/tools/topology

**Comment by RanderWang** [comment]
it is not a good time to upstream

**Pull request closed without merging**
