### PR TITLE
hda-dma: remove embedded spin_lock usage to avoid dead lock

### PR DESCRIPTION
**Pull request by keyonjie**
It has embedded lock to dma->lock in hda_dma_post_copy() and
hda_dma_start() where may lead to dead lock, here remove them.

Signed-off-by: Keyon Jie <yang.jie@linux.intel.com>

### CODE REVIEW

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by lgirdwood** [comment]
@keyonjie ping, any update ? This is a fix so P1

**Comment by keyonjie** [comment]
@lgirdwood sorry, let me update it today.

**Comment by keyonjie** [comment]
@lgirdwood updated.

**Pull request merged**
