### PR TITLE
Refine xtensa-build-zephyr.py

### PR DESCRIPTION
**Pull request by aiChaoSONG**
Rename the overlay config from "tgl_ipc4_overlay.conf"
to "ipc4_overlay.conf" because it is in tgl folder.

PosixPath doesn't convert to string automatically, and
it is not acceptable in sign_cmd, convert it to string
explicitly.

Signed-off-by: Chao Song <chao.song@linux.intel.com>

### CODE REVIEW

**Comment by aiChaoSONG** [comment]
I did test the previous version, I have no idea why after the zephyr fix for xcc build merged, it can not work any more, and need this fixup.

**Comment by aiChaoSONG** [comment]
test failures are unrelated to this PR.

**Review by lgirdwood — COMMENTED** [review]
Can you fix the patch subject to remove "fixup!".

**Comment by marc-hb** [comment]
Also, this should be two different commits. Renames are very often painful so it is best not to mix them with unrelated bug fixes.

Otherwise LGTM.

**Comment by marc-hb** [comment]
https://sof-ci.01.org/sofpr/PR5451/build12197/devicetest is mostly empty. Re-running

**Comment by marc-hb** [comment]
SOFCI TEST

**Review by marc-hb — APPROVED** [review]

**Comment by lgirdwood** [comment]
@aborisovich any comments ?

**Comment by aborisovich** [comment]
Yes you need to be extra careful with those pathlib.path casts to string. Good catch.

**Pull request merged**
