### PR TITLE
rtnr: Add audio stream layer between sof and RTNR

### PR DESCRIPTION
**Pull request by MingJenTai**
This PR adds an audio stream layer between sof and RTNR for consistency.

### CODE REVIEW

**Review by lgirdwood — APPROVED** [review]
@mwasko @sathya-nujella fyi - code change for ADL004

**Comment by MingJenTai** [comment]
> @MingJenTai pls confirm the validation for this PR on this branch. Thanks.

Yes I've tested and verified this PR on this branch. Thank you.

**Comment by lgirdwood** [comment]
@greg-intel fwiw - another product branch that PR fails on Zephyr build
```
CMake Error at /workdir/zephyrproject/zephyr/cmake/compiler/gcc/target.cmake:10 (message):
  C compiler
  /opt/toolchains/zephyr-sdk-0.14.1/xtensa/intel_apl_adsp/xtensa-intel_apl_adsp_zephyr-elf/bin/xtensa-intel_apl_adsp_zephyr-elf-gcc
  not found - Please check your toolchain installation
Call Stack (most recent call first):
  /workdir/zephyrproject/zephyr/cmake/target_toolchain.cmake:57 (include)
  /workdir/zephyrproject/zephyr/cmake/app/boilerplate.cmake:599 (include)
  /workdir/zephyrproject/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:24 (include)
  /workdir/zephyrproject/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:35 (include_boilerplate)
  CMakeLists.txt:5 (find_package)
```

**Comment by greg-intel** [comment]
> @greg-intel fwiw - another product branch that PR fails on Zephyr build

These failures look different @lgirdwood .  They passed the build step, but seem to have a variety of test failures, I'm not sure why there are so many additional failures for the zephyr tests.  The internal link to the generic test job is [here](https://sof-jenkins.ostc.intel.com/job/generic_test/793/). You can view the individual results more easily from there.

**Pull request merged**
