### PR TITLE
arch: multicore xtos

### PR DESCRIPTION
**Pull request by tlauda**
Support for multiple cores executing the same code with the new arch xtensa-smp:
- Updated xtos to the latest version (2017.8).
- Modified xtos to handle interrupts per core.
- Added interrupt structures and stacks per core.

Signed-off-by: Tomasz Lauda <tomasz.lauda@linux.intel.com>

### CODE REVIEW

**Comment by lgirdwood** [comment]
Does this create a src/arch/xtensa and src/arch/xtensa-smp ?
 It may be better to go one level down and do src/arch/xtensa/xtos-smp | xtos and likewise for HAL, that way we can reuse Makefiles and top level code.

Btw, it looks like a binary file sneaked in the PR - boot_ldr.

**Comment by tlauda** [comment]
I went one level below and reused common files.
Now we have xtensa/up and xtensa/smp with xtos, hal and include in both of them.

**Comment by tlauda** [comment]
De-duplicated arch and xtensa headers.
APL/CNL code should stay in the UP - they are still supported with this arch.

**Comment by tlauda** [comment]
Small change in structs.

**Comment by lgirdwood** [comment]
I've created a next branch now since code freeze is Monday. Can you redo the pull request to next and I will merge. Thanks.

**Comment by tlauda** [comment]
Pull request changed base to next.

**Pull request merged**
