### PR TITLE
Use new '-DREM=#' prefix to preserve comments in pre-processed .toml

### PR DESCRIPTION
**Pull request by marc-hb**
Having to find source files to read comments is not convenient.

This depends on https://github.com/zephyrproject-rtos/zephyr/pull/67019 which was merged a while ago.

### CODE REVIEW

**Comment by marc-hb** [comment]
Really unlucky with this one, I'm tempted to just re-run everything :-)

IPC timeout during basic playback in https://sof-ci.01.org/sofpr/PR8956/build3484/devicetest/index.html?model=MTLP_RVP_NOCODEC&testcase=check-playback-3times

This seems to put the system in a bad state and all consecutive tests fail. The (lack of) errors does not ring any bell. @kv2019i maybe?

**Comment by marc-hb** [comment]
SOFCI TEST

**Comment by marc-hb** [comment]
SOFCI TEST

**Comment by marc-hb** [comment]
3rd time's the charm.

ACE https://sof-ci.01.org/sofpr/PR8956/build3506/devicetest/index.html has only pause/resume issues. Luckier this time?

CAVS https://sof-ci.01.org/sofpr/PR8956/build3507/devicetest/index.html has only 2 suspend/resume failures

Good to go.

**Review by lyakh — APPROVED** [review]

**Review by kv2019i — APPROVED** [review]

**Pull request merged**
