### PR TITLE
rimage: Update rimage revision

### PR DESCRIPTION
**Pull request by softwarecki**
Changed rimage submodule revision to 25804e7dc8ee37f3cb87b0a96b58300478cd3cff

lib_manager: Use correct manifest header from rimage

By mistake, the lib_manager module used a private manifest header from the rimage project. It included other private headers. Switched to the public header.

### CODE REVIEW

**Comment by sys-pt1s** [comment]
Can one of the admins verify this patch?

**Comment by sys-pt1s** [comment]
Can one of the admins verify this patch?

**Comment by lgirdwood** [comment]
@softwarecki does this have your latest fix ?

**Comment by softwarecki** [comment]
@lgirdwood CI in this PR helped me discover the error. It now includes the latest fix.

**Review by lgirdwood — APPROVED** [review]

**Review by tmleman — APPROVED** [review]

**Review by dnikodem — APPROVED** [review]

**Comment by kv2019i** [comment]
@wszypelt CI seems stuck.

Also multiple failures https://sof-ci.01.org/sofpr/PR7414/build5600/devicetest/index.html . Curiously the failures are only seen on one cavs2.5 nocodec device, but still I don't think I've seen these before.

**Comment by wszypelt** [comment]
@kv2019i There was a problem with the internal service, we managed to fix it, I will rerun PR

**Review by marcinszkudlinski — APPROVED** [review]

**Review by aborisovich — CHANGES_REQUESTED** [review]
@softwarecki please confirm whether this PR contains fix that prevents segmantation fault on Windows.

**Comment by marc-hb** [comment]
You mean this one?
- https://github.com/thesofproject/rimage/issues/115

**Review by aborisovich — APPROVED** [review]
This PR is not related to bugfixing, it only brings loadable modules support, approving.

**Comment by aborisovich** [comment]
> You mean this one?
> 
> * [Error status 34304, crash in function: man_copy_sram rimage#115](https://github.com/thesofproject/rimage/issues/115)

Not this one, we have other sporadicalls not reported yet.

**Comment by kv2019i** [comment]
There are failures in https://sof-ci.01.org/sofpr/PR7414/build5599/devicetest/index.html and https://sof-ci.01.org/sofpr/PR7414/build5600/devicetest/index.html but all seem to match existing bugs. Proceeding with merge.

**Pull request merged**
