### PR TITLE
Audio: Fix the ramp gain setting.

### PR DESCRIPTION
**Pull request by andrula-song**
Fix the ramp gain setting bug to start ramp from the previous gain instead of zero.

### CODE REVIEW

**Comment by andrula-song** [comment]
IPC timeout of TestKDTopologies test, other PRs failed in this case too. @wszypelt, can you help to trigger again? Thanks.

**Comment by singalsu** [comment]
Mute (key 0 in alsamixer) is still not working with this version, other volume steps seem to be OK now.

**Comment by andrula-song** [comment]
SOFCI TEST

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
@singalsu pls review.

**Review by singalsu — APPROVED** [review]
Thanks! It works now perfectly, very smooth sounding mute/unmute and volume transitions!

**Review by pblaszko — APPROVED** [review]

**Review by dnikodem — APPROVED** [review]

**Review by tmleman — APPROVED** [review]

**Pull request merged**
