### PR TITLE
[NOT TESTED]byt: ssp: refine the RX FIFO flushing logic

### LINKED ISSUE #3520: [BUG] BYT: Random stereo channels swaps happen with sof-byt-nocodec.tplg
**Describe the bug**
I have developed a test that plays different frequency sine waves in each channel to PCM0P and captures from PCM0C. The purpose of the test is volume control testing but it detects also basic issues like channel swap. The reported error indicates that the playback, ssp-loopback, or capture channels got swapped.

The topology contains also volume components and mixer in the playback path. Though since a similar topology passes in APL platform the bug in those components is unlikely. But I'll try to replicate with a minimized topology later.

**To Reproduce**
With PR https://github.com/thesofproject/sof-test/pull/410 (to add the test) and sof PR #3509 (add the volume switch to nocodec topologies) run:
`sof-test/test-case/check-volume-levels.sh
`
**Reproduction Rate**
For one sub-test (play-capture) about 50% occurrence. Below 2 of 3  sub-tests failed. 

**Expected behavior**
No channels swapped, the test passed as it does in cAVS platforms. 

**Impact**
Annoyance for stereo music, showstopper for applications where channels order is critical.

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: {SHA}
    * SOF: {SHA}
2) Name of the topology file
    * Topology: sof-byt-nocodec.tplg
3) Name of the platform(s) on which the bug is observed.
    * Platform: Baytrail

**Screenshots or console output**

```
2020-10-14 11:20:57 UTC [INFO] Measuring volume gains
File /tmp/tmp.iat6kH01et.wav:
pass (1/3)
File /tmp/tmp.EIsHmXIzcE.wav:
Channel 1 failed lower gain limit at  0.5 -  0.9s, gain -47.2 dB, min -10.5 dB
Channel 2 failed lower gain limit at  0.5 -  0.9s, gain -27.1 dB, min   9.5 dB
Channel 2 failed lower gain limit at  1.5 -  1.9s, gain -37.1 dB, min  -0.5 dB
fail (2/3)
Note: The test would pass with swapped channels.
File /tmp/tmp.3pEPEAF8DL.wav:
Channel 1 failed lower gain limit at  2.5 -  2.9s, gain -37.2 dB, min  -0.5 dB
Channel 1 failed lower gain limit at  3.5 -  3.9s, gain -37.2 dB, min  -0.5 dB
Channel 2 failed lower gain limit at  3.5 -  3.9s, gain -37.1 dB, min  -0.5 dB
fail (3/3)
Note: The test would pass with swapped channels.
FAIL
2020-10-14 11:21:11 UTC [ERROR] Error: Failed one or more tests in volume levels check.
2020-10-14 11:21:11 UTC [ERROR] Please inspect files: /tmp/tmp.iat6kH01et.wav, /tmp/tmp.EIsHmXIzcE.wav, and /tmp/tmp.3pEPEAF8DL.wav.
2020-10-14 11:21:11 UTC [ERROR] Starting func_exit_handler(), exit status=1, FUNCNAME stack:
2020-10-14 11:21:11 UTC [ERROR]  die()  @  /home/singalsu/git/sof-test/case-lib/lib.sh
2020-10-14 11:21:11 UTC [ERROR]  measure_levels()  @  sof-test/test-case/check-volume-levels.sh:328
2020-10-14 11:21:11 UTC [ERROR]  main()  @  sof-test/test-case/check-volume-levels.sh:84
2020-10-14 11:21:11 UTC [ERROR]  main()  @  sof-test/test-case/check-volume-levels.sh:336
2020-10-14 11:21:11 UTC [INFO] Test Result: FAIL!

```

Please also include the relevant sections from the firmware log and kernel log in the report (and attach the full logs for complete reference). Kernel log is taken from *dmesg* and firmware log from *sof-logger*. See https://thesofproject.github.io/latest/developer_guides/debugability/logger/index.html

### PR DESCRIPTION
**Pull request by keyonjie**
Mimid the SSP RX FIFO flushing logic which verified work on CNL/WHL.

We need to read out entries every time the FIFO is not empty. This
flushing may need take place several rounds, and we need to wait 1
sample time between 2 flushing rounds.

Fixes #3520

Signed-off-by: Keyon Jie <yang.jie@linux.intel.com>

### CODE REVIEW

**Comment by singalsu** [comment]
Thanks Keyon, I'll test this.

**Comment by singalsu** [comment]
I've run this test. It failed 2 of 3 runs, but this was the first time ever to see a single pass on BYT with sof-test check-volume-levels.sh so there is possibly improvement.

I tried to check your new traces added but even with trace verbose and my attempt to change dai_dbg() to dai_info() I still don't see traces from you patch. I wonder if the DAI drivers tracing is no more working? As sanity check I even added a custom trace print to volume component and it appeared, so there's likely something wrong in tracing.

**Comment by keyonjie** [comment]
> I've run now the tests. It failed 2 of 3 runs, but this was the first time ever to see a single pass on BYT with sof-test check-volume-levels.sh so there is possibly improvement.

Thanks for testing it.

> 
> I tried to check your new traces added but even with trace verbose and my attempt to change dai_dbg() to dai_info() I still don't see traces from you patch. I wonder if the DAI drivers tracing is no more working? As sanity check I even added a custom trace print to volume component and it appeared, so there's likely something wrong in tracing.

do you mean it *dis*appeared for volume tracing neither?

I need to get an Minnow board to test and debug it more, if tracing doesn't work for BYT thoroughly, it could take more effort to fix it.

**Comment by singalsu** [comment]
@keyonjie The traces looked normal except that none of your traces from ssp_empty_rx_fifo() appeared. My added trace elsewhere was a sanity check that I'm running the correct image with your patch included. Maybe the dai_info() and dai_dbg() are not defined for BYT SSP driver? Or this driver code wasn't running?

I would have liked to see what the before and after traced values were.

**Comment by keyonjie** [comment]
> @keyonjie The traces looked normal except that none of your traces from ssp_empty_rx_fifo() appeared. My added trace elsewhere was a sanity check that I'm running the correct image with your patch included. Maybe the dai_info() and dai_dbg() are not defined for BYT SSP driver? Or this driver code wasn't running?

The dai tracing issue is addressed, UUID and TR_CTX is missed in baytail/ssp.c, it will be fixed after added those. 

> 
> I would have liked to see what the before and after traced values were.

But unfortunately, after several hours debugging, it looks to me that the external wired mode looks quite similar to internal LBM for BYT SSP, the capture can't be stopped separately so the RX FIFO watermark(RFL) keep increasing even we have cleared the RSRE (while SSE is set), so, to me, this issue looks is not easy to be fixed.

Let me change this PR to draft one, I may not pay extra effort to work on this anymore.

**Comment by singalsu** [comment]
@keyonjie Thanks for the effort! It's unfortunate that the SSP registers bits specification is not friendly for FW/SW.

Nice that you were able to fix the trace.

**Review by lgirdwood — COMMENTED** [review]
Any update ? you are all green.

**Comment by keyonjie** [comment]
@lgirdwood @singalsu let me close this as it doesn't fix the issue.

**Pull request closed without merging**
