### PR TITLE
Glk 011 drop stable

### PR DESCRIPTION
**Pull request by yongzhi1**
https://github.com/thesofproject/sof/commit/e4c1651b3609decde51b908cc43433f882c0a532

### CODE REVIEW

**Comment by lgirdwood** [comment]
@yongzhi1 some/all of this has already been merged into master, please check with @tlauda

**Comment by tlauda** [comment]
@yongzhi1 @lgirdwood All of them already on master. What is the purpose of this PR?

**Comment by yongzhi1** [comment]
I created a draft pull request with the intention to cherry-pick 092eb61781 to https://github.com/thesofproject/sof/tree/glk-011-drop-stable? sorry about using the wrong tool.

**Comment by tlauda** [comment]
@yongzhi1 The commits are already on the branch. Next time please ask owner of the branch to just do the cherry-pick directly.

**Pull request closed without merging**
