### PR TITLE
west.yml: update zephyr to 740d7f735e2

### PR DESCRIPTION
**Pull request by tmleman**
Total of 369 commits.

Changes include:

46b356a6b0e intel-adsp: fix ACE power-off assembly
fb53d2ef8dd ace: power: replace pseudo-assembly movi

### CODE REVIEW

**Comment by kv2019i** [comment]
@lyakh  I don't think the power_down assembly changes are working out -- lot of fails on ACE20

**Review by kv2019i — APPROVED** [review]

**Comment by kv2019i** [comment]
Good to go, waiting for second +1 review so we can merge.

**Review by lyakh — APPROVED** [review]

**Comment by marc-hb** [comment]
This Zephyr upgrade is likely part of the reasons that caused MTL to stop working entirely: #9308

**Comment by plbossart** [comment]
I don't fully get how this Zephyr upgrade was successful CI-wise, but somehow post-merge we are in the weeds.

Does this point to a testing problem or an obsolete configuration used in tests @kv2019i ?

**Comment by kv2019i** [comment]
@plbossart I think this is a feature of the current system. We can have cases where two PRs pass the tests independetly, but when they are both in the tree, the test fails. I think this happened here. To catch these, we'd have to trigger CI again for all other PRs, when we merge a PR and this would be very costly. @marc-hb can comment much better on the options we have.

**Comment by marc-hb** [comment]
> We can have cases where two PRs pass the tests independetly, but when they are both in the tree, the test fails

This is well known CI issue and Gitlab and Github have a solution for it:

https://about.gitlab.com/blog/2020/01/30/all-aboard-merge-trains/
https://github.blog/2023-07-12-github-merge-queue-is-generally-available/

The Chrome project also had some project-specific "merge queue" concept for a very long time.

I don't know whether Jenkins has something like this. Even if it has, this would be a major effort not worth the effort for something that happens very rarely in SOF. We have much more frequent problems to solve first (for instance: merging known broken PRs). The solution above are designed for repos with a much higher churn, like Zephyr for instance. But even Zephyr does not use this; they just revert very quickly when this happens.

**Pull request merged**
