### PR TITLE
fix incoherent buffer regression #6075

### PR DESCRIPTION
**Pull request by lyakh**
The DMA buffer in dai.c has to use cached alias for access. Besides the pointer can be NULL, which has to be checked for.

### CODE REVIEW

**Comment by marc-hb** [comment]
> This reverts commit
> https://github.com/lyakh/sof/commit/9d37a33335d4a68e0433f6bca6cb5739b06500d5.
> The regression is fixed, so CONFIG_INCOHERENT can be re-enabled.

Avoid double-negations and cherry-pick -x the original commit instead. `Restore CONFIG_INCOHERENT...`

**Review by lgirdwood — COMMENTED** [review]
LGTM, agree with @marc-hb the double revert looks a little funny so best to cherry-pick !

**Comment by lyakh** [comment]
CI: the only failure is a WHL suspend-resume timeout https://sof-ci.01.org/sofpr/PR6084/build1119/devicetest/?model=WHL_UPEXT_HDA_ZEPHYR&testcase=check-suspend-resume-with-playback-5

**Comment by lyakh** [comment]
> LGTM, agree with @marc-hb the double revert looks a little funny so best to cherry-pick !

@lgirdwood @marc-hb I thought having revert-revert would add context but ok, replaced with a cherry-pick

**Review by lgirdwood — APPROVED** [review]

**Pull request merged**
