### PR TITLE
[SKIP SOF-TEST] .github: add LNL compilation

### PR DESCRIPTION
**Pull request by marc-hb**

### CODE REVIEW

**Comment by marc-hb** [comment]
https://github.com/thesofproject/sof/actions/runs/5074246280/jobs/9114224057?pr=7685 is known fuzzer build issue 7675

**Review by btian1 — COMMENTED** [review]
should submit with separate PR? any relation with this PRs two patches?
1. remove code that not did in previous merge.
2. add LNL to build config.

**Comment by marc-hb** [comment]
I don't understand, multiple commits in a single PR is OK, everyone (including you!) does it. These two commits are clearly related to each other: the second one depends on the first one.

**Comment by marc-hb** [comment]
@wszypelt , https://sof-ci.01.org/sof-pr-viewer/#/build/PR7685/build12059479 failed with the usual

```
17:09:46,637 INFO  - Running step...
17:42:10,237 INFO  - Executing post-execute action...
17:42:10,237 ERROR - Step 'master>SCANS>TESTS>TRIGGER PYTHON SMOKE_IPC4 TESTS' is failed: Step is failed since the triggered build is failed, cancelled, or timed out. 
```

**Review by kv2019i — APPROVED** [review]

**Pull request merged**
