### PR TITLE
Topology: Fix DAI_ADD function call in sof-cml-rt1011-rt5682 topology

### PR DESCRIPTION
**Pull request by wwittbrx**
This patch fixes DAI_ADD function call for speaker pipeline.
The function call had incorrect number of agruments passed which was causing issues with playback.

### CODE REVIEW

**Comment by wwittbrx** [comment]
Should fix https://github.com/thesofproject/sof/issues/2107

**Comment by sathyap-chrome** [comment]
Thanks for the fix.

**Comment by sathyap-chrome** [comment]
Hi, This change wont impact the issue we are seeing with 008.
As 008 topology doesnt have TIME_DOMAIN changes.

Can we look at why the issue is on 008.

**Comment by keyonjie** [comment]
@sathyap-chrome We need this fix for no sound on 008 issue, @aiChaoSONG is fixing the no sound issue with an extra kernel patch, good news is that it is done, PR will be sent out soon.

**Comment by sathyap-chrome** [comment]
great thanks

**Pull request merged**
