### PR TITLE
topology1: make all cavs nocodec topologies dynamic

### PR DESCRIPTION
**Pull request by ranj063**
All platforms can use dynamic pipelines for nocodec topology.

Signed-off-by: Ranjani Sridharan <ranjani.sridharan@linux.intel.com>

### CODE REVIEW

**Review by lgirdwood — APPROVED** [review]

**Review by plbossart — APPROVED** [review]

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by lgirdwood** [comment]
CI showing what appears to be a script timeout ?
https://sof-ci.01.org/sofpr/PR4600/build9901/devicetest/?model=TGLH_RVP_HDA&testcase=check-suspend-resume-with-capture

**Comment by ranj063** [comment]
> CI showing what appears to be a script timeout ?
> https://sof-ci.01.org/sofpr/PR4600/build9901/devicetest/?model=TGLH_RVP_HDA&testcase=check-suspend-resume-with-capture

yes, this topology is not modified in this PR anyway.

**Comment by plbossart** [comment]
@lgirdwood @ranj063 I think we should merge this today (before 2pm PDT), this would leave us one business day before the week-end to damage-control, if needed, by looking at more test results.

**Comment by lgirdwood** [comment]
Sorry for the delay, hopefully @XiaoyunWu6666 can check tomorrow.

**Comment by XiaoyunWu6666** [comment]
look this PR is merged after today's daily test starts so inner daily 5738 did not reflect its effects

**Pull request merged**
