### PR TITLE
[SKIP SOF-TEST] Add new file: app/overlays/repro-build.conf

### PR DESCRIPTION
**Pull request by marc-hb**
Passing options one by one in .github/workflows/zephyr.yml was becoming
unwieldy. Reduces Windows/Linux duplication. This also makes local
testing easier; less typing and guess work.

This should also help with https://github.com/thesofproject/sof/pull/9116.

### CODE REVIEW

**Comment by marc-hb** [comment]
@andyross can you please help fix these (totally unrelated) sparse warning? 

```
/zep_workspace/sof/src/audio/google/google_rtc_audio_processing.c:529:76: warning: incorrect type in argument 1 (different address spaces)
/zep_workspace/sof/src/audio/google/google_rtc_audio_processing.c:557:40: warning: incorrect type in assignment (different address spaces)
/zep_workspace/sof/src/audio/google/google_rtc_audio_processing.c:558:39: warning: incorrect type in assignment (different address spaces)
/zep_workspace/sof/src/audio/google/google_rtc_audio_processing.c:807:17: warning: incorrect type in argument 1 (different address spaces)
```

`git blame` points at you but this code isn't new; so I don't know why this just showed up recently. Someone changed some CONFIG_ somewhere?

Last passing daily test: https://github.com/thesofproject/sof/actions/runs/9606358628

First failing daily test 5 days ago: https://github.com/thesofproject/sof/actions/runs/9621445375

cc: @eddy1021

**Comment by andyross** [comment]
> @andyross can you please help fix these (totally unrelated) sparse warning?

Looking right now.  Are there docs on running sparse locally?

FWIW that code did change: it used to be getting the big block from the heap (where it would have been returned as a cached pointer) and now it's doing the conversion itself from a static pointer into .data, which is uncached.   Never thought about the sparse interaction until this error showed up, but it's likely real enough and needs an appropriate cast/whitelist/whatever.

**Comment by marc-hb** [comment]
> Looking right now. Are there docs on running sparse locally?

Better than documentation: the specific command can be found in `.github/workflows/sparse-zephyr.yml`. No CI secret for this one!

As you submitted fixup #9265, I assume you already found it.

**Comment by marc-hb** [comment]
A single "updownmixer" test failed in https://sof-ci.01.org/sof-pr-viewer/#/build/PR9264/build14068938, all other tests passed so this PR is clearly not to blame.

**Review by lyakh — APPROVED** [review]
for my understanding: this alone won't be enough to resolve the difference between Windows and Linux SOF builds when using LLEXT as in https://github.com/thesofproject/sof/actions/runs/9550440753/job/26323025134?pr=9116 ?
EDIT: just saw https://github.com/thesofproject/sof/pull/9116#issuecomment-2192715597 - got the idea. Maybe even `CONFIG_MODULES=n`

**Review by kv2019i — APPROVED** [review]

**Pull request merged**
