### PR TITLE
[v2.7] Disable IMR context save for MTL [alternative comment wording]

### PR DESCRIPTION
**Pull request by kv2019i**
We really need this for v2.7 and rc1 cut-off is planned on Friday, so let me propose an alternative comment wording for
https://github.com/thesofproject/sof/pull/8156

We can merge either that PR or this, but we really need to get this forward (as we agree on the code and this is now about the comment).

### CODE REVIEW

**Review by ranj063 — APPROVED** [review]

**Comment by marc-hb** [comment]
The only two MTL tests that failed in https://sof-ci.01.org/sof-pr-viewer/#/build/PR8170/build12739722 are called `test_00_08_start_paused_stream_after_d3` and `test_02_09_memory_with_modules_d0_d3_state` so I'm afraid this code change is guilty. See error messages below.

Same test results, failures and error messages in earlier version of this PR at https://sof-ci.01.org/sof-pr-viewer/#/build/PR8156/build12735262 so these failures are deterministic.

Other PRs do not fail like this, for instance this very recent one is all green:
https://sof-ci.01.org/sof-pr-viewer/#/build/PR8163/build12738280


```
10:36:23,866 INFO  - cavs_scripts-py\utilities\ipc_driver.py:175: in raise_or_save
10:36:23,866 INFO  - raise error
10:36:23,866 INFO  - E utilities.ipc_driver_exceptions.AvsIpcErrorResponseException: FW responded with error
10:36:23,866 INFO  - E FW status: 0x00000005
10:36:23,866 INFO  - E IPC error: 9 (ADSP_IPC_INVALID_RESOURCE_ID)
10:36:23,866 INFO  - E ADSP mailbox error: 108 (ADSP_FREE_SHARED_VAR_FAILED_BAD_ALIGNMENT)
```

```
10:36:32,097 INFO  - cavs_scripts-py\utilities\ipc_driver.py:175: in raise_or_save
10:36:32,097 INFO  - raise error
10:36:32,097 INFO  - E utilities.ipc_driver_exceptions.AvsIpcErrorResponseException: FW responded with error
10:36:32,097 INFO  - E FW status: 0x00000005
10:36:32,097 INFO  - E IPC error: 9 (ADSP_IPC_INVALID_RESOURCE_ID)
10:36:32,097 INFO  - E ADSP mailbox error: 1 (ADSP_ERROR_INVALID_PARAM)
```

**Comment by marc-hb** [comment]
I read #7994 (two layers of indirections...) and realized this is only for the 2.7 branch and will never be submitted for main. So maybe the test failures are expected and OK.

**Comment by kv2019i** [comment]
@marc-hb ack, so tests "test_00_08_start_paused_stream_after_d3 and test_02_09_memory_with_modules_d0_d3_state" test exactly the feature that is disabled in this PR, so the tests are expected to fail. Thus this is ok (for SOF2.7 as this feature is not used by Linux SOF driver).

**Review by RanderWang — APPROVED** [review]
LGTM

**Review by ujfalusi — APPROVED** [review]

**Review by mengdonglin — APPROVED** [review]

**Review by lyakh — APPROVED** [review]

**Review by tmleman — APPROVED** [review]
test_00_08_start_paused_stream_after_d3 and test_02_09_memory_with_modules_d0_d3_state use disabled feature so fail is expected. The first commit should be cherry-pick to main branch.

**Comment by kv2019i** [comment]
Thanks all, proceeding with merge!

**Pull request merged**
