### PR TITLE
FIX gcc10 linker errors

### PR DESCRIPTION
**Pull request by fredoh9**
fixes: https://github.com/thesofproject/sof/issues/3880

WIthout this fix, error snippet is like this.

```
Scanning dependencies of target sof
-- The C compiler identification is GNU 7.5.0
-- The C compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
/home/sof/work/xtensa-apl-elf/lib/gcc/xtensa-apl-elf/10.2.0/../../../../xtensa-apl-elf/bin/ld: CMakeFiles/bootloader.dir/__/__/platform/intel/cavs/boot_loader.c.o: in function `strcmp':
/home/sof/work/sof.git/src/platform/intel/cavs/boot_loader.c:206: undefined reference to `memset'
/home/sof/work/xtensa-apl-elf/lib/gcc/xtensa-apl-elf/10.2.0/../../../../xtensa-apl-elf/bin/ld: CMakeFiles/bootloader.dir/__/__/platform/intel/cavs/boot_loader.c.o: in function `bbzero':
/home/sof/work/sof.git/src/platform/intel/cavs/boot_loader.c:79: undefined reference to `memset'
collect2: error: ld returned 1 exit status
-- Check for working C compiler: /usr/bin/cc
src/arch/xtensa/CMakeFiles/bootloader.dir/build.make:136: recipe for target 'src/arch/xtensa/bootloader' failed
make[3]: *** [src/arch/xtensa/bootloader] Error 1
CMakeFiles/Makefile2:1502: recipe for target 'src/arch/xtensa/CMakeFiles/bootloader.dir/all' failed
make[2]: *** [src/arch/xtensa/CMakeFiles/bootloader.dir/all] Error 2
---------------------
[100%] Linking C executable sof
/home/sof/work/xtensa-apl-elf/lib/gcc/xtensa-apl-elf/10.2.0/../../../../xtensa-apl-elf/bin/ld: CMakeFiles/sof.dir/src/audio/mux/mux.c.o: in function `mux_prepare':
/home/sof/work/sof.git/src/audio/mux/mux.c:657: undefined reference to `memmove'
/home/sof/work/xtensa-apl-elf/lib/gcc/xtensa-apl-elf/10.2.0/../../../../xtensa-apl-elf/bin/ld: CMakeFiles/sof.dir/src/audio/mux/mux.c.o: in function `mux_mix_check':
/home/sof/work/sof.git/src/audio/mux/mux.c:62: undefined reference to `memmove'
collect2: error: ld returned 1 exit status
CMakeFiles/sof.dir/build.make:2740: recipe for target 'sof' failed
make[3]: *** [sof] Error 1
CMakeFiles/Makefile2:428: recipe for target 'CMakeFiles/sof.dir/all' failed
make[2]: *** [CMakeFiles/sof.dir/all] Error 2
CMakeFiles/Makefile2:1587: recipe for target 'src/arch/xtensa/CMakeFiles/bin.dir/rule' failed
make[1]: *** [src/arch/xtensa/CMakeFiles/bin.dir/rule] Error 2
Makefile:658: recipe for target 'bin' failed
make: *** [bin] Error 2
```

### CODE REVIEW

**Comment by fredoh9** [comment]
From the CI result, current GCC build(ver 9.x) build fine too.

**Comment by dbaluta** [comment]
Please create better commit messages. Explain why this happens with newer compiler :). The purpose of a commit message is not to tell *what the code does (that should be obvious from the code) but *why*:)

**Comment by lgirdwood** [comment]
> I think we can do better with the commit message. Explain why this happens with newer compiler :). The purpose of a commit message is not to tell **what** the code does (that should be obvious from the code) but **why**:)

@fredoh9 please also state that the new API calls are POSIX compliant. i.e. they comply to usage and calling conventions in the man pages.

**Comment by fredoh9** [comment]
@lgirdwood I saw your comments after pushing my patch. :) but I don't get your comment. Can you elaborate more?

**Comment by marc-hb** [comment]
> Explain why this happens with newer compiler :).

`memset` optimization, can happen with any version of any compiler, see examples (and the start of a commit message?) in https://github.com/thesofproject/sof/issues/3880#issuecomment-796537478

**Review by marc-hb — CHANGES_REQUESTED** [review]
According to https://gcc.gnu.org/onlinedocs/gcc/Standards.html gcc takes 4 functions for granted: `memcpy, memmove, memset and memcmp.` See more details in bug #3880 

Whatever we do (static inlines in `string.h`?) we should treat these 4 functions the same. 

I don't know about clang but I know it tries hard to mimic gcc (with much less documentation).

**Comment by lgirdwood** [comment]
@fredoh9 can you try the following diff agiast your various complier configs and submit as PR if it works.
```diff
diff --git a/src/arch/xtensa/CMakeLists.txt b/src/arch/xtensa/CMakeLists.txt
index 1ae3f88b9..1d58be9b3 100644
--- a/src/arch/xtensa/CMakeLists.txt
+++ b/src/arch/xtensa/CMakeLists.txt
@@ -216,7 +216,7 @@ else()
        target_link_libraries(sof_static_libraries INTERFACE reset)
 endif()
 
-target_link_libraries(sof_ld_flags INTERFACE "-Wl,-Map=sof.map")
+target_link_libraries(sof_ld_flags INTERFACE "-Wl,-Map=sof.map -lc")
 target_link_libraries(sof_ld_flags INTERFACE "-T${PROJECT_BINARY_DIR}/${platform_ld_script}")
 
 add_custom_target(
diff --git a/src/arch/xtensa/include/arch/compiler_info.h b/src/arch/xtensa/include/arch/compiler_info.h
index 49ee8f0cc..20f1423b5 100644
--- a/src/arch/xtensa/include/arch/compiler_info.h
+++ b/src/arch/xtensa/include/arch/compiler_info.h
@@ -29,6 +29,11 @@
 #define CC_MINOR __GNUC_MINOR__
 #define CC_MICRO __GNUC_PATCHLEVEL__
 #define CC_NAME "GCC"
+
+#if CC_MAJOR >= 10
+#define CC_USE_LIBC
+#endif
+
 #endif
 
 #define CC_DESC " " XCC_TOOLS_VERSION
index 09a1adec6..f84cd6c98 100644
--- a/src/lib/lib.c
+++ b/src/lib/lib.c
@@ -5,12 +5,14 @@
 // Author: Liam Girdwood <liam.r.girdwood@linux.intel.com>
 
 #include <sof/string.h>
+#include <sof/compiler_info.h>
 
 #include <stddef.h>
 #include <stdint.h>
 
-/* Not needed for host or Zephyr */
-#if !CONFIG_LIBRARY && !__ZEPHYR__
+/* Not needed for host or Zephyr or CC uses LIBC */
+#if !CONFIG_LIBRARY && !__ZEPHYR__ && !defined (CC_USE_LIBC)
+
 /* used by gcc - but uses arch_memcpy internally */
 void *memcpy(void *dest, const void *src, size_t n)
 {
@@ -30,6 +32,22 @@ void *memset(void *s, int c, size_t n)
 
        return s;
 }
+
+int memcmp(const void *p, const void *q, size_t count)
+{
+       uint8_t *s1 = (uint8_t *)p;
+       uint8_t *s2 = (uint8_t *)q;
+
+       while (count) {
+               if (*s1 != *s2)
+                       return *s1 < *s2 ? -1 : 1;
+               s1++;
+               s2++;
+               count--;
+       }
+       return 0;
+}
+
 #endif
 
 int memcpy_s(void *dest, size_t dest_size,
@@ -55,23 +73,6 @@ void *__vec_memset(void *dest, int data, size_t src_size)
 }
 #endif
 
-#if !CONFIG_LIBRARY && !__ZEPHYR__
-int memcmp(const void *p, const void *q, size_t count)
-{
-       uint8_t *s1 = (uint8_t *)p;
-       uint8_t *s2 = (uint8_t *)q;
-
-       while (count) {
-               if (*s1 != *s2)
-                       return *s1 < *s2 ? -1 : 1;
-               s1++;
-               s2++;
-               count--;
-       }
-       return 0;
-}
-#endif
-
 /* generic strlen - TODO: can be optimsed for ARCH ? */
 int rstrlen(const char *s)
 {
```

**Comment by lgirdwood** [comment]
@fredoh9 pplease see https://github.com/thesofproject/sof/pull/3930, can you check this PR against the older compilers.

**Comment by fredoh9** [comment]
https://github.com/thesofproject/sof/pull/3930 is merged

**Pull request closed without merging**
