### PR TITLE
[WIP] drivers: imx: EDMA driver

### PR DESCRIPTION
**Pull request by paulstelian97**
There are two ways to use the ESAI -- either manually put the samples in
ETDR or read them from ERDR, or use the EDMA0 controller to have it do
this for you. This commit implements the EDMA driver so I can do the
latter and use the ESAI in an easy way.

Signed-off-by: Paul Olaru <paul.olaru@nxp.com>

Draft due to lack of testing and due to the usecase together with the ESAI driver not currently working.

See also: #1803, #1806 (related, currently WIP pull requests for this platform)

### CODE REVIEW

**Comment by paulstelian97** [comment]
@tlauda This is what I sent the mails on sof-list today about. The flow that I understood:

-> pipeline_copy() is called for preloading. This eventually gets into dai.c in dai_copy(), that then calls dma_start() which ends up in the function edma_start(). In here, I get the interrupt before there is a chance for the stack to fully unwind (the 384 bytes are transferred in 96 transfers) and then the DAI callback for IRQ calls pipeline_schedule_copy() which fails to actually schedule anything new.

For reference: https://mailman.alsa-project.org/pipermail/sound-open-firmware/2019-September/003531.html

**Comment by tlauda** [comment]
@paulstelian97 Where does the DMA copy data? Is it some kind of internal FIFO? I'm just wondering if you getting the interrupt so fast is expected or not. Maybe ESAI has the wrong format/clock settings?

**Comment by paulstelian97** [comment]
The ESAI does have an internal FIFO indeed (see the ESAI commit). It is supposed to trigger a hardware request whenever the fifo ends up having little content.

With the current size the FIFO might be overrun; the behavior of the ESAI is to discard the extra samples, according to documentation.

I'm not 100% sure of the format and clock settings, though I tried to simply set the same as in the proprietary firmware that supports this board (and works). I'll still work on adjusting that, though I need to figure out why the FIFO low interrupt doesn't trigger.

The EDMA will copy as fast as allowed. The ESAI has an internal FIFO exposed as a register at the destination address (or source in case of recording, though I'm not testing that; in that case it will return the last sample again). And 96 transfers can be pretty fast if there is nothing to actually limit their speed.

**Comment by dbaluta** [comment]
@paulstelian97 thanks a lot for taking care of this! Can you please squash all the new patches, so that reviewing can be done easier?

**Comment by paulstelian97** [comment]
I suppose it is cleaner for the moment, although I still need to incorporate a few suggestions (such as moving the IRQ and channel decision somewhere else, for example storing them in the handshake field) before considering this one ready.

**Comment by paulstelian97** [comment]
Replaced by #1813

**Pull request closed without merging**
