### PR TITLE
Un-harcode rimage master branch and URL

### PR DESCRIPTION
**Pull request by marc-hb**
2 commits, see commit messages

### CODE REVIEW

**Comment by marc-hb** [comment]
doxygen, testbench and yamllint will hang until #3992 is merged.

**Review by cujomalainey — APPROVED** [review]

**Review by iuliana-prodan — APPROVED** [review]

**Review by lgirdwood — APPROVED** [review]

**Comment by marc-hb** [comment]
The previous https://sof-ci.01.org/sof-pr-viewer/#/build/PR3993/build6239588 on former commit dbb643882d5ff was all green. Newer commit c6b6d74 is identical, it was a fake commit to workaround other, unrelated CI issue (!) #3992 

For c6b6d74 github still shows `Internal Intel CI System/merge/build Expected — Waiting for status to be reported` 10 hours later.

**Comment by lgirdwood** [comment]
@zrombel are we good to merge here ?

**Comment by marc-hb** [comment]
https://sof-ci.01.org/sof-pr-viewer/#/build/PR3993/build6245042 PASSed

The more recent  https://sof-ci.01.org/sof-pr-viewer/#/build/PR3993/build6244689 was incomplete for some unknown reason. It did build and use rimage though; it stopped later. So from the selfish perspective of this PR it's also a PASS.

They both ran on the same commit c6b6d74aef3f652c6. Quickbuild (and others) test pull/3993/merge so the `main` branch could have been different. I doubt this mattered.

**Comment by zrombel** [comment]
This PR is good to be merge.
QB have some problem with force-push. I'm already investigating this issue.

**Pull request merged**
