### PR TITLE
qemu: use kconfig instead of sed

### PR DESCRIPTION
**Pull request by jajanusz**

### CODE REVIEW

**Comment by xiulipan** [comment]
@lgirdwood The agent feature is now enabled with QEMU, but random accuracy issue with timer will result in a DSP panic. Could you help to check why the timer we used will have some error. Will create a issue in QEMU later.

@jajanusz That would be some nice trick, but as it is a workaround for now. We may need to make the QEMU to be real time simulator.

**Comment by jajanusz** [comment]
> We should not be fixing firmware to work around missing features in qemu, but instead add these features to qemu.

What about performance issues? Agent was failing because of timing.
BTW now you have it disabled anyway but in a *hackish* way with seding repo sources...
This one is cleaner at least.

**Comment by tlauda** [comment]
@lgirdwood Let's not block any new features on QEMU. With agent we've already proved it has it's own problems. I would say lack of clock register is nothing compared to unpredictable irq triggering.

**Comment by jajanusz** [comment]
@lgirdwood @xiulipan If you don't want this solution, please propose something else - I'm open to suggestions, because using sed on sources like it's now is bad imho.

**Comment by lgirdwood** [comment]
@jajanusz @tlauda not sure why you guys are modifying sources with sed? Qemu CI is only testing for boot, qemu fuzzing is testing IPC but is not a CI blocker yet ??
Unpredicatble IRQ triggering is actually a "good thing" that helps us make sure our code is **solid** and not some flimsy built on sand logic that falls over if we IRQ out of sync/order.
@xiulipan the solution (for timing ratios) is to synchronously tie the qemu external timers to CCOUNT updates. i.e. eveytime qemu updates CCOUNT then we update timers correspondingly, we use system timer atm. CCOUNT is updated on DSP core clock, whilst external timers are updated on an audio clock like SSP on BYT.

**Comment by xiulipan** [comment]
@jajanusz The sed is just some hack to make kconfig chagne more esay with CI. It actually does not that matter.

@lgirdwood The problem now we face with QEMU boot test is the agent will try to have a scheduled task in every 1ms. It will make DSP panic if the task time drift to 1.5ms. The QEMU now will get some random failure with the time drift.  So now we add some workaround to disable agent when test with QEMU.

**Comment by lgirdwood** [comment]
> @jajanusz The sed is just some hack to make kconfig chagne more esay with CI. It actually does not that matter.
>

Ok, so I guess you are adding and removing individual features for test ?
 
> @lgirdwood The problem now we face with QEMU boot test is the agent will try to have a scheduled task in every 1ms. It will make DSP panic if the task time drift to 1.5ms. The QEMU now will get some random failure with the time drift. So now we add some workaround to disable agent when test with QEMU.

Please align the EXT DSP clocks with CCOUNT as suggested above.

**Comment by jajanusz** [comment]
> > @jajanusz The sed is just some hack to make kconfig chagne more esay with CI. It actually does not that matter.
> 
> Ok, so I guess you are adding and removing individual features for test ?

That's the part that I don't like:
```
      script:
        - sed -i $(($(grep "config HAVE_AGENT" -n src/platform/Kconfig | cut -f1 -d:)+2))"s/default y/default n/" src/platform/Kconfig
        - ./scripts/docker-run.sh ./scripts/xtensa-build-all.sh -r -j $PLATFORM
```

**Comment by jajanusz** [comment]
@lgirdwood @xiulipan So we gonna leave sed here? If so please close this one. I don't know if proposed solution is the best, but seding sources on the fly is bad for sure.

**Comment by xiulipan** [comment]
@jajanusz Let keep it here. I think we should try to fix the workaroud from QEMU side later.

**Comment by zrombel** [comment]
Due to merge of PR#2303 this PR must be rebased or test results for KD tests with audio format 24b/32b ignored.

**Comment by jajanusz** [comment]
Stalled PR. Sed is still practice, but didn't break in meantime, so can live with it.

**Pull request closed without merging**
