### PR TITLE
stable-v2.0: set default value instead of hardcoding Zephyr commit 

### PR DESCRIPTION
**Pull request by marc-hb**
2 clean cherry-picks from main + unhardcoding the Zephyr commit. Review commits separately.

Zero functional change when you don't (try to) pass a zephyr commit on the command line.

### CODE REVIEW

**Comment by marc-hb** [comment]
This is a preliminary step before fixing stable-v2.0 compatibility with the latest Zephyr SDK, long story in #5654

**Comment by marc-hb** [comment]
https://github.com/thesofproject/sof/runs/5892208159 shows the expected Zephyr commit fd089b361d8aebbcb49cca989444aaeb0b6fbb4d

However https://sof-ci.01.org/sofpr/PR5672/build12674/build/tgl_zph.txt shows the most Zephyr commit c11b7852d15c29
```
[2/258] Generating include/generated/version.h
-- Zephyr version: 3.0.99 (/srv/home/jenkins/workspace/sof_generic_build/zephyrproject/zephyr), build: c11b7852d15c
```

@keqiaozhang can you please restrict your (very useful) "STABLE Zephyr cooldown" to the main SOF branch? It should not apply to other SOF branches.

**Review by lgirdwood — APPROVED** [review]

**Comment by sys-pt1s** [comment]
Can one of the admins verify this patch?

**Comment by marc-hb** [comment]
and now I'm not "whitelisted" in https://quickbuild.igk.intel.com/build/9120013. Never a dull moment.

**Comment by lgirdwood** [comment]
@marc-hb yeah, CI does not fully support and work on older branches. Happy to merge if you see it essential since this is all build.

**Comment by marc-hb** [comment]
OK let's merge this then.

**Pull request merged**
