### PR TITLE
ipc4: return ipc4 error status instead of posix error

### PR DESCRIPTION
**Pull request by RanderWang**
Convert posix error to ipc4 error and return ipc4 error for
functions in ipc4 directory.

fixes https://github.com/thesofproject/sof/issues/5737

### CODE REVIEW

**Review by lgirdwood — APPROVED** [review]
@tmleman @marcinszkudlinski fyi.

**Review by marcinszkudlinski — APPROVED** [review]

**Review by tmleman — APPROVED** [review]

**Review by lyakh — COMMENTED** [review]
also `return 0` in `ipc4_create_pipeline()`, in `ipc_comp_connect()`, `ipc_comp_disconnect()` should be `return IPC4_SUCCESS`. Also a bit strange, that a static function `process_dma_index()` in that file returns POSIX error codes, although they're replaced with IPC4 codes later, so, it isn't really a bug

**Comment by lgirdwood** [comment]
> also `return 0` in `ipc4_create_pipeline()`, in `ipc_comp_connect()`, `ipc_comp_disconnect()` should be `return IPC4_SUCCESS`. Also a bit strange, that a static function `process_dma_index()` in that file returns POSIX error codes, although they're replaced with IPC4 codes later, so, it isn't really a bug

@RanderWang can you make this a new PR to align these other functions with correct IPC4 return codes.

**Comment by RanderWang** [comment]
@lgirdwood  @lyakh  updated according to your comments. Thanks!

**Review by lyakh — APPROVED** [review]

**Review by lgirdwood — APPROVED** [review]

**Pull request merged**
