### PR TITLE
[WIP] [DO NOT MERGE] topology: keyword detection

### PR DESCRIPTION
**Pull request by lgirdwood**
This series add initial and compile tested keyword detection topology and support pipelines. Not for merging yet, but for information and testing purposes only. 

```
 PCM 0 <-------+- Mux 0 <-- B0 <-- DMIC6 (DMIC01)
               |
 Keyword <-----+
```

**NOTE: needs latest sof/alsa-lib git master branch to build**

### CODE REVIEW

**Comment by lgirdwood** [comment]
@lbetlej @tlauda @mmaka1 updated.

**Comment by ranj063** [comment]
@lgirdwood I'm going to leave this one open but submit new smaller PR's with my updates.

**Comment by lgirdwood** [comment]
@ranj063 sounds good to me. Thanks ! Btw, you will notice that the keyword detect mux that switches between the PCM device and KD component only uses one  buffer and should not incur and extra copy.

**Comment by ranj063** [comment]
> @ranj063 sounds good to me. Thanks ! Btw, you will notice that the keyword detect mux that switches between the PCM device and KD component only uses one buffer and should not incur and extra copy.

@lgirdwood sorry I didnt get this part. Where is this handled?

**Comment by ranj063** [comment]
@lgirdwood i've included all but the 2 logger commits in this PR in my new PR's

**Comment by ranj063** [comment]
@lgirdwood I think this one can be closed too.

**Pull request closed without merging**
