### PR TITLE
topology: sof-tgl-nocodec-ci: change to run smart_amp on core 1

### PR DESCRIPTION
**Pull request by keyonjie**
Change to run smart_amp pipelines on DSP core 1, this will help reduce
the core 0 usage and add multi-core to the CI coverage.

Signed-off-by: Keyon Jie <yang.jie@linux.intel.com>

### CODE REVIEW

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
@keyonjie is the TGL CI expected to fail here ?

**Comment by plbossart** [comment]
> @keyonjie is the TGL CI expected to fail here ?

I think this is putting the cart before the horse. @keyonjie the premise of CI tests is that they are used for non-regressions. Here the multi-core does not work and will systematically throw an error, that's not useful. We need to enable this configuration when multi-core does work. Otherwise you will add noise to every PR review and decrease the attention people put on CI results.

**Comment by marc-hb** [comment]
https://sof-ci.01.org/sofpr/PR4028/build8669/devicetest/ failed because TGLU_SKU0A32_SDCA was added to PR testing before being ready, sorry for the inconvenience. I removed it.

The other error is just the usual suspend/resume TIMEOUT

**Comment by marc-hb** [comment]
SOFCI TEST

**Comment by lgirdwood** [comment]
@marc-hb thanks for aligning us here and retesting.

**Comment by keyonjie** [comment]
yes @plbossart @lgirdwood @marc-hb , the TGLU-RVP-NOCODEC is not in the PR test model yet so we are not seeing error for PRs. It is in the daily pool so hopefully we will see it in today's daily report, we can add it to PR pool once the issue is fixed.

**Pull request merged**
