### PR TITLE
[SKIP CI] docker: upgrade to ubuntu 22.04 as a base image

### PR DESCRIPTION
**Pull request by fredoh9**
Upgrade Ubuntu to latest LTS version, 22.04.

This one line change is supposed to be enough but there is permission issue when UID is not matching with local UID.

```diff
-FROM ubuntu:20.04
+FROM ubuntu:22.04
```

All other lines are the fix for the permission issue.

### CODE REVIEW

**Comment by fredoh9** [comment]
There is initial permission issue. ID sof is created with UID 1000, but it actually has different UID. Looking at the problem.

`
sof:x:1011:1011::/home/sof:/bin/sh
`

**Comment by marc-hb** [comment]
Try my new sudo-cwd.sh script: https://github.com/thesofproject/sof/commit/c28400baaa383030f0e6860e922365a79e51c31a

**Comment by sys-pt1s** [comment]
Can one of the admins verify this patch?

**Comment by lgirdwood** [comment]
@fredoh9 btw why are we using LTS ? We need latest and greatest Ubuntu for current tooling that users and devs will use.

**Comment by marc-hb** [comment]
In this particular case I think it does not really matter because this image is just a container for the latest and greatest ALSA

In general, if it works with the latest LTS then it works with more recent Ubuntu versions. The converse is not always true.

Also, we don't really have the time to debug Ubuntu.

**Comment by fredoh9** [comment]
yes, sof docker image is mainly being used for tools and topologies. And alsa-lib and alsa-utils are updated with building a docker image. I think it doesn't matter of Ubuntu version.

The other use cases are building GCC toolchains and QEMU test, this might need greatest and latest Ubuntu for build tools. Like Marc said every Ubuntu upgrade introduces new problems to debug.

**Comment by lgirdwood** [comment]
Sorry @fredoh9 @marc-hb disagree - LTS will just mean we are out of date re compiler and any build/run time dependecies for ALSA. Developers will be working on the leading edge release and our environment should align. Distro's are also not going to be deploying our new FW/drivers and tooling to old/current LTS versions.

**Comment by marc-hb** [comment]
> Developers will be working on the leading edge release and our environment should align

https://arstechnica.com/information-technology/2020/05/ubuntu-20-04-welcome-to-the-future-linux-lts-disciples/ "Perhaps not surprisingly, Canonical estimates that 95 percent of all Ubuntu installations are LTS releases."

I never use non-LTS releases, the vast majority of my time is already spent with audio-related bugs and even some LTS bugs ( https://github.com/thesofproject/sof-test/discussions ) so I really don't have time for more non-audio bugs. I know some SOF developers upgrade more frequently but that difference never caused any issue so far.

> Distro's are also not going to be deploying our new FW/drivers and tooling to old/current LTS versions.

Yes and that's why @fredoh9 maintains this docker image: because ALSA is always too old even in latest, non-LTS which means upgrading more frequently gives nothing useful.

> LTS will just mean we are out of date re compiler and any build/run time dependecies for ALSA.

Could you please be more specific here, what sort of ALSA dependency? We've always been using LTS releases here so far and I don't remember any issue so I don't understand what problem(s) this extra work will solve.

**Comment by marc-hb** [comment]
https://ubuntu.com/about/release-cycle

> **Interim** releases will introduce new capabilities from Canonical and upstream open source projects, they serve as a **proving ground** for these new capabilities.

It's fantatistic to have some SOF developers testing and finding the latest Ubuntu bugs and incompatibilities and reporting them to Ubuntu but this particular docker image does not need to do that too.

Interim releases are maintained for 9 months. After 9 months, Ubuntu deletes all the binaries! https://www.releases.ubuntu.com/ Then interim releases become literally unusable overnight. This means an urgent ALSA upgrade can be delayed because now @fredoh9 or @juimonen has to debug some Ubuntu issue instead of releasing new ALSA binaries.

**Comment by fredoh9** [comment]
tested with thesofproject/sof:20230413_ubuntu22.04

@lgirdwood @marc-hb
In this PR, I'm still based on Ubuntu 22.04 LTS. Ubuntu 23.04 will come out soon. I will evaluate more when new Ubuntu is available. I will submit a another PR with newer Ubuntu.

**Review by marc-hb — APPROVED** [review]
Nice job, this is an area where each line changed tends to represent a LOT of work.

**Comment by fredoh9** [comment]
For my curiosity, I check build tools version

* Ubuntu 20.04 image
- gcc/g++ 9.4.0
- ld 2.34
- make 4.2.1
- cmake 3.16.3

* Ubuntu 22.04 image
- gcc/g++ 11.3.0
- ld 2.38
- make 4.3
- cmake 3.22.1

**Comment by fredoh9** [comment]
@lgirdwood can you approve this? I have a plan to upgrade to the latest Ubuntu.

**Comment by marc-hb** [comment]
> @fredoh9 I think we should stop pointing at the latest and moving tag in the docker shell script, we need to start pointing at a fixed version that you update in PRs like this one.

At least during this backwards-incompatible `sudo-cwd.sh` transition. Then maybe switch back to `latest` later.

**Comment by fredoh9** [comment]
A bit trickier than I thought. Good point. I will point a specific tag rather than latest for now

**Comment by fredoh9** [comment]
Looks good.

https://github.com/thesofproject/sof/actions/runs/4789961866/jobs/8518460013?pr=7169

Digest: sha256:6e65eb281ae7560c6c89f34ce73c77fbec60ca1b22a6ff922d3db51d8651edf5

Errors are due missing 'xtensa-cnl-elf-gcc', which is not part of the docker image any more.

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
@wszypelt @lrudyX docker not tested by internal CI. Can we merge ?

**Comment by wszypelt** [comment]
@lgirdwood Internal Intel CI System/merge/build tests green, ready to merge on my part

**Pull request merged**
