### PR TITLE
Topology2: sdw-amp-generic: add missing num_input_pins

### PR DESCRIPTION
**Pull request by bardliao**
num_input_pins was missing in passthrough mode.

Fixes: #7899

### CODE REVIEW

**Review by plbossart — APPROVED** [review]
Thanks @bardliao 

@ranj063 can't we flag such errors at build time with a mandatory property?

**Comment by ranj063** [comment]
> Thanks @bardliao
> 
> @ranj063 can't we flag such errors at build time with a mandatory property?

@plbossart unfortunately not with this one because num_input_pins is not mandatory for the copier.

**Review by ranj063 — APPROVED** [review]

**Comment by plbossart** [comment]
> @plbossart unfortunately not with this one because num_input_pins is not mandatory for the copier.

What prevents us from making it mandatory? I thought the two sides are needed for DMA config and buffer config.

**Comment by ranj063** [comment]
> > @plbossart unfortunately not with this one because num_input_pins is not mandatory for the copier.
> 
> What prevents us from making it mandatory? I thought the two sides are needed for DMA config and buffer config.

I can look into it in a follow up PR

**Pull request merged**
