### PR TITLE
topology: fix apl-demux-pcm512x HDMI dai id

### PR DESCRIPTION
**Pull request by xiulipan**
The HDMI DAI id changed, update the demux topology.

Signed-off-by: Pan Xiuli <xiuli.pan@linux.intel.com>

### CODE REVIEW

**Comment by juimonen** [comment]
was also here: https://github.com/thesofproject/sof/pull/2344, but got caught in some debate...

**Comment by lgirdwood** [comment]
@xiulipan can you check CI

**Comment by xiulipan** [comment]
SOFCI TEST

**Comment by jajanusz** [comment]
Jenkins - known logger issue

**Pull request merged**
