### PR TITLE
[SKIP CI] docker: add valgrind package for more advanced testing

### PR DESCRIPTION
**Pull request by fredoh9**
The Valgrind tool suite provides a number of debugging and profiling tools
that we could used for debugging/testing.

Signed-off-by: Fred Oh <fred.oh@linux.intel.com>

### CODE REVIEW

**Comment by fredoh9** [comment]
> Btw, @fredoh9 we will need "valgind" to be added to CI docker image for more advanced testing, just giving you a heads up.

_Originally posted by @lgirdwood in https://github.com/thesofproject/sof/pull/4476#issuecomment-879142756_

**Comment by marc-hb** [comment]
@lgirdwood  I don't see why we need this in our docker image. Our docker image is for Xtensa cross-compiling, AFAIK valgrind does not support Xtensa and we do all user-space natively - as we should. So we should not run valgrind in our docker image for simplicity and CI performance reasons.

The only other reason we need the docker image is to get a more recent version of alsa-lib than provided by Linux distributions. Do we need alsa-lib to valgrind SOF?

**Comment by lgirdwood** [comment]
> @lgirdwood I don't see why we need this in our docker image. Our docker image is for Xtensa cross-compiling, AFAIK valgrind does not support Xtensa and we do all user-space natively - as we should. So we should not run valgrind in our docker image for simplicity and CI performance reasons.
> 
> The only other reason we need the docker image is to get a more recent version of alsa-lib than provided by Linux distributions. Do we need alsa-lib to valgrind SOF?

My understanding is that the GH CI actions run in the docker container ? if so we do need Docker as I intend to run testbench under valgrind as a CI job to validate infrastructure and modules.

**Comment by marc-hb** [comment]
Github actions run anyhow we like and we've been using both docker and not in Github actions. However it's much more painful to run them in our Docker because of
- the acrobatics required to pass arguments, examples: commit 9938a66db4c07, 014a386dfb539, ...
- the huge performance impact, testing is much much slower
- The risk of being throttled by docker.com

Everything that can be done without docker should be done without docker.

**Comment by lgirdwood** [comment]
> Github actions run anyhow we like and we've been using both docker and not in Github actions. However it's much more painful to run them in our Docker because of
> 
> * the acrobatics required to pass arguments, examples: commit [9938a66](https://github.com/thesofproject/sof/commit/9938a66db4c07104576bce03156d4f8764d3d0e3), [014a386](https://github.com/thesofproject/sof/commit/014a386dfb5391124231a7221149f62c4923bae6), ...
> * the huge performance impact, testing is much much slower because downloading the docker image every time takes minutes
> * The risk of being throttled by docker.com, happened a lot with Travis.
> 
> Everything that can be done without docker should be done without docker.

I assume you are saying GH actions can support valgrind without Docker ?

**Comment by marc-hb** [comment]
> I assume you are saying GH actions can support valgrind without Docker ?

Yes, GH Actions provide a fairly standard Ubuntu image. Worst case it's `apt-get update && apt-get install valgrind` and done.; much faster than downloading a docker image. https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md

**Comment by lgirdwood** [comment]
> > I assume you are saying GH actions can support valgrind without Docker ?
> 
> Yes, GH Actions provide a fairly standard Ubuntu image. Worst case it's `apt-get update && apt-get install valgrind` and done.; much faster than downloading a docker image. https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md

Ok, this can be closed.

**Pull request closed without merging**
