### PR TITLE
debug: debug_stream: Access debug slot directly using cavstool.py

### PR DESCRIPTION
**Pull request by jsarha**
Access debug slot directly using cavstool.py, by specifying the debug slot number where the debug_stream data is transferred.

Adds one command line parameter for selecting the debug slot directly, adds an alternative mainloop for polling the slot through cavstool.py direct access, and relaxes some often occurring warning print. The warning prints happen when the FW boots and the cavstool code wakes up before the init code has initialized the slot.

NOTE:
This code depends from this PR: https://github.com/zephyrproject-rtos/zephyr/pull/78753 . However, since the import line is in the function that is only called if the --direct-access-slot flag is present, the old code will still work without cavstool.py, but that would in turn need this PR: https://github.com/thesofproject/linux/pull/5154

### CODE REVIEW

**Comment by jsarha** [comment]
My latest cleanups were still un committed, thus the last update.

**Review by lgirdwood — APPROVED** [review]

**Review by kv2019i — CHANGES_REQUESTED** [review]
Let's sync with the version of cavstool.py that will get merged. Current version fails to

AttributeError: module 'cavstool' has no attribute 'fw_is_alive_dsp'. Did you mean: 'fw_is_alive'?

**Comment by jsarha** [comment]
Latest push added some robustness improvements to the python script and config overlay for building debug_stream_thread_info.

**Comment by jsarha** [comment]
The important part of this PR - the debug_stream.py direct access - is now split in two:

1. The basic functionality that depends on: https://github.com/zephyrproject-rtos/zephyr/pull/78753
   - Some more cleaning up usability improvements on top of previous version

2. A usability improvement to always just work if at all possible, depends on: https://github.com/zephyrproject-rtos/zephyr/pull/79061


Then there is the debug_stream_overlay.conf added that is identical to the previous version and on simple typo fix commit.

**Comment by jsarha** [comment]
Fixed couple of simple codestyle issues found by checkpatch.

**Comment by jsarha** [comment]
> @jsarha does this PR depend on the Zephyr PRs ? if so , lets mark as DNM until Zephyr parts merged.

The script actually does not stop from working even if the cavstool.py changes are not available, that is, if the debugfs file is there. But maybe the error messages if trying to use -c flag are too confusing. I'll add the tag.

**Comment by jsarha** [comment]
> 
> @jsarha Both Zephyr PRs look very similar - best to close one PR if its been deprecated by a new PR.

@lgirdwood , the first PR [1] is the base of the second PR [2]. Actually the second [2] has only one commit on top of [1]. I was expecting the first PR to get merged soon as it already had two approvals (and I did not want it to get back to square one). Once the first is merged, I'll rebase the second, and it becomes only one commit PR.

[1] https://github.com/zephyrproject-rtos/zephyr/pull/78753
[2] https://github.com/zephyrproject-rtos/zephyr/pull/79061

**Review by kv2019i — APPROVED** [review]
The main Zephyr cavstool.py change is merged, so I thnk this can be merged now as the interface is settled. The other Zephyr change seems nice-to-have and not a strict dependency to this one, so I don't think this PR needs to block on that either.

**Comment by jsarha** [comment]
I dropped the commit that depends on https://github.com/zephyrproject-rtos/zephyr/pull/79061 so this should be good for merging now. I'll make another PR that depends on the above PR. The new PR will be rebased on top of this, so it will contain the same commit as this.

**Comment by jsarha** [comment]
zephyrproject-rtos/zephyr#79061 was merged last night, picking "tools: debug_stream.py: Use cavstool.debug_slot_offset_by_type()" back on board of this PR again.

**Comment by lgirdwood** [comment]
> [zephyrproject-rtos/zephyr#79061](https://github.com/zephyrproject-rtos/zephyr/pull/79061) was merged last night, so picking "tools: debug_stream.py: Use cavstool.debug_slot_offset_by_type()" back on board of this PR again.

Do we need a west update now ?

**Comment by kv2019i** [comment]
@lgirdwood wrote:
> Do we need a west update now ?

I don't think that's needed. This is a debug tool that is not compiled so there's no hard dependency. So if CI is good (not yet the case), I'd just proceed and merge this as it is now.

**Comment by kv2019i** [comment]
Problem with Windows builds in github flows, but now passing. Proceeding to merge.

**Pull request merged**
