### PR TITLE
sof: change approach to including platform and arch headers

### PR DESCRIPTION
**Pull request by tlauda**
Right now we have headers spread across main sof include
directory, arch include directory and platform include
directory. The same header e.g. cpu needs to be included
from sof, arch and platform. This creates long inclusion
lists and often we are missing many headers, but since
they are already included in some other headers, we don't
see the issue. This patch changes the approach to including
platform headers. It allows for inclusion only from main
header e.g. sof/cpu.h will include arch/cpu.h and platform/cpu.h.
If we want to use some cpu functionality we only need to include
sof/cpu.h and don't worry about the rest. If we have platform
header, which is only used inside of platform code, then
it can be directly accessed within.

### CODE REVIEW

**Comment by tlauda** [comment]
I know that method for checking if parent header has been already defined doesn't give us 100% confidence, but it's just to catch at least some mistakes during development. I believe, that the header misplacement should be caught during review process.

**Comment by jajanusz** [comment]
@tlauda I think approach is right in general - f.e. audio stuff shouldn't include arch/platform specific headers etc, but I don't know if these checks are really what we want. Imho platform code can include platform specific headers - at long as it stays at the same scope it is ok, just calling platform/arch specific code from general/abstract parts should be forbidden.

**Comment by jajanusz** [comment]
@tlauda However if we can choose only between having no checks at all or your checks that permit only specific header to be included, I prefer to have your checks.

**Comment by tlauda** [comment]
@jajanusz Of course you're right, that platform code should be able to include platform headers, but the same code also needs something defined also in the same generic header. This kind of approach is supposed to simplify things and easily identify the header we need. And in the end I've decided that some checks are better than no checks.

**Pull request merged**
