### PR TITLE
scripts: pre update sof docker for cmake covert

### PR DESCRIPTION
**Pull request by xiulipan**
Update the sof docker to support cmake to pre test cmake build system
change.

Signed-off-by: Pan Xiuli <xiuli.pan@linux.intel.com>

pre test for https://github.com/thesofproject/sof/pull/845

### CODE REVIEW

**Comment by lgirdwood** [comment]
@xiulipan @jajanusz lets merge this and build PR tomorrow, unless there are any blockers now ?

**Comment by jajanusz** [comment]
> @xiulipan @jajanusz lets merge this and build PR tomorrow, unless there are any blockers now ?

There are no blockers for this one. For #845 just need CI team to fix something.
Anyway this PR won't break anything cos it just installs cmake and python.

**Comment by xiulipan** [comment]
@jajanusz @lgirdwood 
let me check with sof-ci build log and give some feedback later.

**Comment by lgirdwood** [comment]
@jajanusz @xiulipan applied with false positive CI warning

**Pull request merged**
