### PR TITLE
[TEST][DO NOT REVIEW] Test Zephyr PR

### PR DESCRIPTION
**Pull request by iuliana-prodan**
Do not review, is just for testing imx8m build with zephyr

### CODE REVIEW

**Comment by iuliana-prodan** [comment]
@marc-hb I need your help.. again :)
Why is CI changing the Zephyr revision?
```
Run cd workspace/zephyr/
From https://github.com/zephyrproject-rtos/zephyr
 * branch                main       -> FETCH_HEAD
Previous HEAD position was ec5b0f09d boards: xtensa: nxp_adsp_imx8m: include pinctrl dtsi in overlay
HEAD is now at b452[16](https://github.com/thesofproject/sof/actions/runs/4949365332/jobs/8851421514?pr=7591#step:4:17)a0a dts: arm: nxp: Fix PINT base address for LPC51xxx and 54xxxx
* b45216a0a474c62f1e1a647c8f9806492e6f3b45 (HEAD) dts: arm: nxp: Fix PINT base address for LPC51xxx and 54xxxx
* 2dbccf065429836bc311a5deef1ba9782725a0f9 usb: device_next: do not set alternate 0 for non-existent interfaces
* aa5b6db0f4092c823caded44db3d89d7fd5727d3 usb: device_next: correct return type of get/set alternate value helper
* e3b[17](https://github.com/thesofproject/sof/actions/runs/4949365332/jobs/8851421514?pr=7591#step:4:18)aa5ed3f9848898031abe3cdff54fd65494d usb: host: improve robustness of descriptors print
* 0a5b682461e6a8a631fa007411f6eae1b7d1a1d8 drivers: udc_virtual: fix bus SUSPEND, RESUME, RESET event handling 
```

I want to test SOF with a specific Zephyr PR, but the CI is switching the Zephyr version.

**Comment by marc-hb** [comment]
There are multiple checks and the "zmain" checks ignore indeed the manifest and test the Zephyr main branch = exactly how we found these compilation issues in the first place. Ignore "zmain" in this test PR and focus on the other ones.

**Comment by marc-hb** [comment]
Always provide a direct link when discussing test results.

**Comment by iuliana-prodan** [comment]
> There are multiple checks and the "zmain" checks ignore indeed the manifest and test the Zephyr main branch = exactly how we found these compilation issues in the first place. Ignore "zmain" in this test PR and focus on the other ones.

So, I should look for [build-linux (mnfst, imx8 imx8x imx8m)](https://github.com/thesofproject/sof/actions/runs/4949365332/jobs/8851420386?pr=7591#logs)], instead of [build-linux (zmain, imx8 imx8x imx8m)](https://github.com/thesofproject/sof/actions/runs/4949365332/jobs/8851421514?pr=7591#logs)

Got it! Thank you!

**Comment by marc-hb** [comment]
> So, I should look for [build-linux (mnfst, imx8 imx8x imx8m)](https://github.com/thesofproject/sof/actions/runs/4949365332/jobs/8851420386?pr=7591#logs)], instead of [build-linux (zmain, imx8 imx8x imx8m)](https://github.com/thesofproject/sof/actions/runs/4949365332/jobs/8851421514?pr=7591#logs)

Exactly yes because this test PR is changing the "mnfst" (manifest).

https://github.com/zephyrproject-rtos/zephyr/pull/57795 is now merged, closing this TEST PR.

**Pull request closed without merging**
