### PR TITLE
version.cmake: make XTOS and Zephyr .ldc file different from each other + other cleanups.

### PR DESCRIPTION
**Pull request by marc-hb**
5 commits. The main one:

[version.cmake: make XTOS and Zephyr .ldc file different from each other](https://github.com/thesofproject/sof/commit/dced4400f9e8e062e6de97d59b0af56c04e625c8) 

This is especially important considering some sof-bin releases are now
"hybrid": with a mix of XTOS and Zephyr.

### CODE REVIEW

**Comment by marc-hb** [comment]
Only ICL failed inhttps://sof-ci.01.org/sof-pr-viewer/#/build/PR5485/build8760913 and there's absolutely nothing specific to ICL in this PR. The ICL build was successful. I'm afraid one ICL system has been flaky, @kkarask ?

**Comment by marc-hb** [comment]
https://sof-ci.01.org/sofpr/PR5485/build12238/devicetest/?model=CML_RVP_SDW&testcase=check-kmod-load-unload-after-playback is:
- https://github.com/thesofproject/linux/issues/3012

https://sof-ci.01.org/sofpr/PR5485/build12238/devicetest/?model=APL_UP2_NOCODEC_ZEPHYR&testcase=multiple-pipeline-playback and consecutive are
- #4414

The other failures are the usual (but worryingly more frequent) suspend/resume timeouts. None is related to this build fix.

**Review by kv2019i — APPROVED** [review]

**Review by lgirdwood — APPROVED** [review]
@aborisovich good for Windows build ?

**Comment by lgirdwood** [comment]
Taking this for v2.1 branch

**Comment by marc-hb** [comment]
> Taking this for v2.1 branch

@lgirdwood, in general who cherry-picks fixes to stable branches? I can do this one (not all commits are required) but I'm wondering about the "process" in general.

**Comment by lgirdwood** [comment]
> > Taking this for v2.1 branch
> 
> @lgirdwood, in general who cherry-picks fixes to stable branches? I can do this one (not all commits are required) but I'm wondering about the "process" in general.

I do, but PRs can also be sent. I think this is in the stable-v2.1 branch as it made the cut prior to the branch creation.

**Comment by marc-hb** [comment]
> I do, but PRs can also be sent.

Thanks.

>  I think this is in the stable-v2.1 branch as it made the cut prior to the branch creation.

Indeed - barely but it did, I just checked.

**Comment by aborisovich** [comment]
> @aborisovich good for Windows build ?

Sorry could not check was out of office some time.
The only part that made me wonder about Windows build are those paths with forward slashes in
`execute_process(COMMAND git ls-files src/ scripts/ ${_sof_zephyr_dir}`
As they are passed as is to underlying process. But I guess git should recognize forward slashes syntax.
I will verify and submit an issue if it fails.

**Comment by marc-hb** [comment]
> The only part that made me wonder about Windows build are those paths with forward slashes in
> execute_process(COMMAND git ls-files src/ scripts/ ${_sof_zephyr_dir}

Note there were some forward slashes there already, this PR merely added one to the list.

BTW PowerShell and pretty much everything in Windows supports forward slashes, it's basically just CMD.EXE that does not - which could admittedly be a problem here, I don't know what CMake and ninja work on Windows. Maybe they silently convert them? What is the best CMake practice for filenames and directories?

**Comment by marc-hb** [comment]
This is a reminder that we really need some Windows CI. Is there one in Quickbuild? Github has Windows environments but I'm afraid there is a toolchain availability issue on Windows
https://github.com/actions/virtual-environments#available-environments
https://docs.zephyrproject.org/latest/guides/beyond-GSG.html#gs-toolchain

**Comment by aborisovich** [comment]
> This is a reminder that we really need some Windows CI. Is there one in Quickbuild? Github has Windows environments but I'm afraid there is a toolchain availability issue on Windows https://github.com/actions/virtual-environments#available-environments https://docs.zephyrproject.org/latest/guides/beyond-GSG.html#gs-toolchain

It should be fine Marc. We use MSYS2 for windows gcc and it may be installed on Windows Server.
I do not know whether Xtensa Xplorer along with toolchains may be installed on Windows Server but I am pretty sure it can.
The ZephyrSDK xtensa toolchain is under development for Windows as far as I know.
So for now it would be working only for people who bought commercial Xtensa (not ZephyrSDK).

**Comment by aborisovich** [comment]
> > The only part that made me wonder about Windows build are those paths with forward slashes in
> > execute_process(COMMAND git ls-files src/ scripts/ ${_sof_zephyr_dir}
> 
> Note there were some forward slashes there already, this PR merely added one to the list.
> 
> BTW PowerShell and pretty much everything in Windows supports forward slashes, it's basically just CMD.EXE that does not - which could admittedly be a problem here, I don't know what CMake and ninja work on Windows. Maybe they silently convert them? What is the best CMake practice for filenames and directories?

Yes you summed it up pretty well, its all about not calling cmd directly. I was worried there may be something like shell=True by default as in python but there is no such think so we are ok.

**Pull request merged**
