### PR TITLE
Topology: Create 1ch and 3ch microphones sof-hda-generic topologies

### PR DESCRIPTION
**Pull request by singalsu**
This patch adds to CMakeLists.txt build of duplicate one and three
channels dmic capture topologies. They are needed to match the driver
that loads a topology that matches the number of microphones based on
configured microphones count in device BIOS.

This is an intermediate solution to enable microphones on such
devices. The mono audio will appear as double mono for user space. A
true mono topology and firmware will be created later.

Signed-off-by: Seppo Ingalsuo <seppo.ingalsuo@linux.intel.com>

### CODE REVIEW

**Comment by juimonen** [comment]
related kernel PR: https://github.com/thesofproject/linux/pull/2350

**Comment by lgirdwood** [comment]
@singalsu can you confirm that userspace will drop the duplicated channel data ? and how does it know to do this ? UCM flag ?

**Comment by singalsu** [comment]
@lgirdwood The userspace does not know about duplication. It appears like a stereo microphones array that produces the same signal for both channels. And for a 3 mic device it will appear like ch4 is duplicate of ch3. I thought it's better option than forcing the device to 2ch mode to omit mic3. This is the best we can do now without upgrading the firmware.

I'm working with true mono firmware & topology that will be available later. A 3 mic device may need add of channel select component (4 to 3) to pipeline since there's no 3ch FIFO mode. Though I'm not aware of such devices, I've seen only 1/2/4 microphones.

Ideally this could have been a topology only update but unfortunately there's some similar hard coding to 2ch in firmware as there was in kernel.

**Comment by lgirdwood** [comment]
The root of information will be the DMI name (or similar) and come from the kernel (kernel is source of Mic count information). We can be clever here and use the kernel to limit the PCM capabilities for DMIC PCMS so that userspace sees the correct DMIC count and the FW gets this count too i.e.
```c
static struct snd_pcm_hardware snd_mychip_capture_hw = {
        .info = (SNDRV_PCM_INFO_MMAP |
                 SNDRV_PCM_INFO_INTERLEAVED |
                 SNDRV_PCM_INFO_BLOCK_TRANSFER |
                 SNDRV_PCM_INFO_MMAP_VALID),
        .formats =          SNDRV_PCM_FMTBIT_S16_LE,
        .rates =            SNDRV_PCM_RATE_8000_48000,
        .rate_min =         8000,
        .rate_max =         48000,
        .channels_min =     2,   <<<<<<<<<<<<<<<<<<<<<<
        .channels_max =     2, <<<<<<<<<<<<<<<<<<<<<<<<
        .buffer_bytes_max = 32768,
        .period_bytes_min = 4096,
        .period_bytes_max = 32768,
        .periods_min =      1,
        .periods_max =      1024,
};
```
This would be able to limit userspace to the correct number of mics and would also mean the FW would know MIC count on stream open.

**Comment by singalsu** [comment]
@lgirdwood If DAI configuration does not match PCM there will be a pipeline error. Currently there can't be 1ch DMIC DAI. The 1ch PCM topology would need to contain a channel selector in the pipeline. I think it can do in current FW 2 to 1 so it should be possible. Would the above need more code to @juimonen 's kernel patch or is it for UCM and/or ALSA configuration files?

**Comment by lgirdwood** [comment]
> @lgirdwood If DAI configuration does not match PCM there will be a pipeline error. Currently there can't be 1ch DMIC DAI. The 1ch PCM topology would need to contain a channel selector in the pipeline. I think it can do in current FW 2 to 1 so it should be possible. Would the above need more code to @juimonen 's kernel patch or is it for UCM and/or ALSA configuration files?

If we duplicate 1 -> 2 ch and 3 - > 4 chan today then we forover have to do this since it will become the new "standard". @singalsu has already quoted about how this is bad for beamforming, so my concern here is the path forward. We can do 1 channel and 3 channel pipelines today, so can we not create the correct 1/3 chan topologies today and use them if we detect the correct machine.

**Comment by plbossart** [comment]
> > @lgirdwood If DAI configuration does not match PCM there will be a pipeline error. Currently there can't be 1ch DMIC DAI. The 1ch PCM topology would need to contain a channel selector in the pipeline. I think it can do in current FW 2 to 1 so it should be possible. Would the above need more code to @juimonen 's kernel patch or is it for UCM and/or ALSA configuration files?
> 
> If we duplicate 1 -> 2 ch and 3 - > 4 chan today then we forover have to do this since it will become the new "standard". @singalsu has already quoted about how this is bad for beamforming, so my concern here is the path forward. We can do 1 channel and 3 channel pipelines today, so can we not create the correct 1/3 chan topologies today and use them if we detect the correct machine.

I don't see your point @lgirdwood. The current fix is just to identify separate topologies, what happens in those topologies can be changed at a later time. I don't get why this would be a 'standard' that we have to deal with forever.

**Comment by keyonjie** [comment]
Why we need some many separated tplg files, what stops us to use a unified one and treat those channel numbers, formats, sample rates as capabilities and configurable at run-time?

**Comment by juimonen** [comment]
@keyonjie @lgirdwood we made separate 1 & 3 ch topology files (in kernel) exactly because then we have the possibility in the future to separate those topologies from 2 & 4. Currently we just copy the 1&3 from 2&4 because we get "dual mono" setup with minimal changes, as this is needed fast.

Yes, there are probably better solution, like doing automatic runtime configuration, unfortunately that doesn't work out of the box. Also true mono doesn't work out of the box.

Separate 1&3 files also make sure we can for example remove beamforming from those dmic topologies that don't support it. However I still understand that making this automatic would be nicer. So this is fast, "least harm for everyone", engineering solution. So I'm trying to fix the fact that we have hard coded sof dmic configuration for 2 & 4 dmics.

For the future we have:
- Make runtime configuration possible
- Enable true mono pipeline up until user space
- Make user space understand the real dmic count

**Comment by juimonen** [comment]
@lgirdwood so ok with this if I make an enhancement issue about the additional features?

**Comment by singalsu** [comment]
@lgirdwood The 1ch capture pipeline does not work, we can't do that yet. Also if it had worked I would hesitate to use it before checking how pulseaudio and clients work with it. I need to contribute a proper test topology so an issue can be filed for the problem that I got. I fixed one DMIC DAI specific bug for myself, a PR later, but it wasn't sufficient. 

Also current SOF headset capture from HDA codec is double mono in stereo container so the 1ch DMIC case with this PR does not differ from it. The headset mono mic is due to 4-pole headset pins allocation.

However since we have for DMIC case unique topologies for every channel count we can address the proper processing later for 1ch and other unusual channel counts.

**Comment by lgirdwood** [comment]
> I don't see your point @lgirdwood. The current fix is just to identify separate topologies, what happens in those topologies can be changed at a later time. I don't get why this would be a 'standard' that we have to deal with forever.

@plbossart other parts of this series also turned 1 ch -> 2 ch DMIC and 3 ch -> 4 ch DMIC by duplicating data and had userspace dumping the unused channel data. There was also no clear path forwards, but that has now been aligned with @singalsu and @juimonen

**Pull request merged**
