### PR TITLE
[SKIP CI] .github: switch to new xtensa-build-zephyr.py

### PR DESCRIPTION
**Pull request by marc-hb**
Switch Github Actions away from older shell script.

Signed-off-by: Marc Herbert <marc.herbert@intel.com>

### CODE REVIEW

**Review by cujomalainey — APPROVED** [review]

**Review by aborisovich — APPROVED** [review]
Looks legit to me. I think arg -a could also stay in the docker-build.sh but this does not matter.
You could also delete xtensa-build-zephyr.sh counterpart in this changeset so people stop make changes to it in other PRs?
Yeah I think it makes sense so they don't modify a script that no longer takes part in the CI.

**Review by aiChaoSONG — APPROVED** [review]

**Comment by marc-hb** [comment]
> I think arg -a could also stay in the sof/zephyr/docker-build.sh but this does not matter.

It would be less flexible. It is possible to run sof/zephyr/docker-build.sh locally for testing it (with some minor tweaks)

**Comment by marc-hb** [comment]
https://quickbuild.igk.intel.com/build/8659921 is `unable to access 'https://github.com/thesofproject/sof/': gnutls_handshake() failed: The TLS connection was non-properly terminated.`, unrelated to this

https://sof-ci.01.org/sof-pr-viewer/#/build/PR5408/build8658824 is all green. It looks like one platform (ICL?) is entirely missing. Either way unrelated to this PR

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
@wszypelt @kkarask fwiw - Internal CI showing all green but reporting red.

**Comment by kkarask** [comment]
@lgirdwood The reason for build was marked as red is problem with running codec regression test.  (I tested it internally - all green)

**Pull request merged**
