### PR TITLE
[mtl-008] topology2: mtl: update flags for alignments

### PR DESCRIPTION
**Pull request by macchian**
The default string for BT_NAME has set to "SSP2-BT" in bt-default.conf. So remove BT_NAME string assignment.

Enable bluetooth offload for power saving since the SKU
has the cnvi module enabled.

Add deepbuffer pipeline support on I2S Speaker playback.
Note: The headset deepbuffer has enabled in I2S/HD-A/SDW conf.

### CODE REVIEW

**Review by lgirdwood — COMMENTED** [review]
@bardliao @ranj063 pls review, LGTM but I'm not up to date on naming.

**Review by bardliao — APPROVED** [review]

**Comment by bardliao** [comment]
This PR is cherry-picked from https://github.com/thesofproject/sof/pull/9531

**Review by lgirdwood — APPROVED** [review]
@abonislawski pls review/merge

**Comment by kv2019i** [comment]
@abonislawski , one for mtl-008

**Review by abonislawski — APPROVED** [review]

**Pull request merged**
