### PR TITLE
20201028 v1.6

### PR DESCRIPTION
**Pull request by lyakh**
this should replace #3563 which was mistakenly created against a wrong branch

### CODE REVIEW

**Comment by lgirdwood** [comment]
@lyakh can you check CI.
@zrombel do you know if CI results/tests are valid for stable branch (it may be missing some platforms or features that are in master) as I've seen some unexpected CI failures for stable.

**Comment by lyakh** [comment]
> @lyakh can you check CI.

@lgirdwood sure:
- device test failure, claimed to fail on APL UP2 nocodec. The detailed view shows the last test check-suspend-resume-with-capture.sh on APL_UP2_NOCODEC as "NotTested" which is a link, leading to a 404 "not found."
- checkpatch complains about moved CONFIG_* entries for lacking descriptions, but the patch only moves them from one place to another. It also complains about too long a patch title. And in any case those patches are already in "master."
- build failed on TGL with "make: *** No rule to make target 'tgph_defconfig'.  Stop."

**Comment by lgirdwood** [comment]
@lyakh thanks, @zrombel looks like TGL CI failure is due to target being in master and not in stable-v1.6. I will merge this since it's already in master unless any objections ?

**Comment by zrombel** [comment]
@lgirdwood I have run this PR without TGL-H configuration and all builds and tests PASSED so it's good to merge.

**Review by lgirdwood — APPROVED** [review]

**Pull request merged**
