### PR TITLE
Tools: Topology2: Add widget class RTNR

### PR DESCRIPTION
**Pull request by singalsu**

### CODE REVIEW

**Review by lgirdwood — APPROVED** [review]
LGTM, but @ranj063 needs to approve.

**Comment by lgirdwood** [comment]
@kv2019i any comments ?

**Review by kv2019i — APPROVED** [review]

**Comment by kv2019i** [comment]
@ranj063 @jsarha ping, will merge later this week if no further comments.

**Review by jsarha — APPROVED** [review]
Looks syntactically correct. Would be helpful, if it would at least once be written somewhere what RTNR stands for. I had to use Google to know what this for 😅.

**Comment by singalsu** [comment]
> Looks syntactically correct. Would be helpful, if it would at least once be written somewhere what RTNR stands for. I had to use Google to know what this for 😅.

True, I could have added same pointer as in firmware. This was min. effort to get component to run with supplied stubs library. We have now two <company name>NR solutions in SOF, though closed library licensing is needed to use them. Hope the companies can contribute to these files e.g. links to their products web pages for their new customers.

**Pull request merged**
