### PR TITLE
cherry-pick: module_adapter: free memory resource

### PR DESCRIPTION
**Pull request by johnylin76**
Cherry-pick this commit now in case it gets omitted in the future.

Since the reset API commits for module_adapter were merged on this branch.  This one will be necessary for running Waves in module_adapter.

@barry-waves @Zames-Chang PTAL

### CODE REVIEW

**Review by barry-waves — APPROVED** [review]

**Review by lgirdwood — APPROVED** [review]
@ranj063 can we update the module API free() to accept NULL pointers ? This would avoid the checks in clients.

**Comment by lgirdwood** [comment]
@thesofproject/mediatek pls review/merge

**Review by yaochunhung — APPROVED** [review]

**Review by kuanhsuncheng — APPROVED** [review]

**Comment by ranj063** [comment]
> @ranj063 can we update the module API free() to accept NULL pointers ? This would avoid the checks in clients.

@lgirdwood that check already exists. So no need to check if the pointer is valid

**Review by cujomalainey — APPROVED** [review]

**Comment by cujomalainey** [comment]
@yaochunhung @kuanhsuncheng who is the MTK release owner? If there is none please merge this.

**Comment by kuanhsuncheng** [comment]
@Zames-Chang 

Hi Whale,
Are you ok for this PR?

**Comment by cujomalainey** [comment]
Ill sign off on behalf of Whale to close this out

**Pull request merged**
