### PR TITLE
arch: xtensa: fix unaligned pointer in irq dispatcher

### PR DESCRIPTION
**Pull request by kuanhsuncheng**
In 8186 mtk dsp (hifi5), we meet a system exception when irq is rasied.

The panic is LoadStoreAlignmentCause.

We found the problem is in int-xxx-dispatcher.S 

#if (XCHAL_CP_MASK & CP1_MASK)
	mov	a11, a1
	addi	a11, a11, UEXC_cp1
	xchal_cp1_store a11, a12, a13, a14, a15
#endif

For xchal_cp1_store macro, ptr must a certain byte aligned address

In the 8186 mtk dsp Xtensa header, we have

    /* 
     *  Macro to store the state of TIE coprocessor AudioEngineLX.
     *  Required parameters:
     *      ptr         Save area pointer address register (clobbered)
     *                  (register must contain a 16 byte aligned address).
     *      at1..at4    Four temporary address registers (first XCHAL_CP1_NUM_ATMPS
     *                  registers are clobbered, the remaining are unused).
     *  Optional parameters are the same as for xchal_ncp_store.
     */
#define xchal_cp_AudioEngineLX_store	xchal_cp1_store
    .macro	xchal_cp1_store  ptr at1 at2 at3 at4  continue=0 ofs=-1 select=XTHAL_SAS_ALL alloc=0

In xtruntime-frames.h, the UEXC_cp1 macro is
STRUCT_AFIELD (long,4,UEXC_,cp1, XCHAL_CP1_SA_SIZE / 4)

I have checked history and found the original UEXC_cp1 define is using STRUCT_AFIELD_A

But after the blew commit merge,
https://github.com/thesofproject/sof/commit/3e1eebe92c2f535c9905721d1f4ce074372ae1e4

I not not sure this is a good solution to fix issue.

please give me some advice if there is anything unconsidered, thanks.

### CODE REVIEW

**Comment by lgirdwood** [comment]
@kuanhsuncheng looks good to me, but lets a quick check first
@mwasko do you have any background here on the change above from Tomek ? CI is showing a good result and this is restoring to original HAL.
@dbaluta good for IMX ?

**Comment by lgirdwood** [comment]
CI is issue unrelated and since this aligns to "upstream" HAL it's probably good to merge.
@kuanhsuncheng quite a lot of the test/validation folks are on vacation now so we may not get information from validation on non Mediatek platforms until early January. Is it OK to wait for you ?

**Comment by kuanhsuncheng** [comment]
> 

@lgirdwood It's fine for me. January is ok.

**Comment by kuanhsuncheng** [comment]
@lgirdwood Hi,

Do we start testing on other non Mediatek platform now?

**Comment by dbaluta** [comment]
@kuanhsuncheng @kuanhsuncheng tested this on imx8 and looks fine. 

@kuanhsuncheng can you please copy the entire message from PR description into git commit description?

PR description will be burried under github and readers will not understand the reasons for this change when inspecting 'git log'

**Comment by lgirdwood** [comment]
> @lgirdwood Hi,
> 
> Do we start testing on other non Mediatek platform now?

Think we are good to merge once commit message is updated. Fwiw, the Intel CI has tested this on all Intel platforms so I know its good for Intel.

**Comment by cujomalainey** [comment]
those who tested should probably give github approval for records sake

**Comment by kuanhsuncheng** [comment]
@lgirdwood  @dbaluta 

I update the commit message. thanks.

**Review by dbaluta — APPROVED** [review]

**Comment by lgirdwood** [comment]
@andyross fyi - something to check for Zephyr.

**Comment by lgirdwood** [comment]
@bhiregou @sunilkumardommati  good for AMD ?

**Comment by sunilkumardommati** [comment]
> @bhiregou @sunilkumardommati good for AMD ?

Tested on our platform and looks good to me.

**Pull request merged**
