### PR TITLE
Use Zephyr SDK 0.16.4

### PR DESCRIPTION
**Pull request by dbaluta**
This updates docker container version and zephyr workflows to support new Zephyr SDK (0.16.4).

### CODE REVIEW

**Review by lgirdwood — APPROVED** [review]

**Comment by dbaluta** [comment]
Looks like there is some problems with Intel builds:

```
/zep_workspace/zephyr/soc/xtensa/intel_adsp/common/include/intel_adsp_hda.h: In function 'intel_adsp_force_dmi_l0_state':
/zep_workspace/zephyr/soc/xtensa/intel_adsp/common/include/intel_adsp_hda.h:448:30: error: 'ADSP_FORCE_DECOUPLED_HDMA_L1_EXIT_BIT' undeclared (first use in this function)
  448 |         ACE_DfPMCCH.svcfg |= ADSP_FORCE_DECOUPLED_HDMA_L1_EXIT_BIT;
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/zep_workspace/zephyr/soc/xtensa/intel_adsp/common/include/intel_adsp_hda.h:448:30: note: each undeclared identifier is reported only once for each function it appears in
/zep_workspace/zephyr/soc/xtensa/intel_adsp/common/include/intel_adsp_hda.h: In function 'intel_adsp_allow_dmi_l1_state':
/zep_workspace/zephyr/soc/xtensa/intel_adsp/common/include/intel_adsp_hda.h:455:32: error: 'ADSP_FORCE_DECOUPLED_HDMA_L1_EXIT_BIT' undeclared (first use in this function)
  455 |         ACE_DfPMCCH.svcfg &= ~(ADSP_FORCE_DECOUPLED_HDMA_L1_EXIT_BIT);
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[149/371] Building C object zephyr/drivers/dma/CMakeFiles/drivers__dma.dir/dma_intel_adsp_hda_host_out.c.obj
[150/371] Building C object zephyr/drivers/dma/CMakeFiles/drivers__dma.dir/dma_intel_adsp_hda_link_in.c.obj
[151/371] Building C object zephyr/drivers/dai/intel/dmic/CMakeFiles/drivers__dai__intel__dmic.dir/dmic.c.obj
[152/371] Building C object zephyr/drivers/dai/intel/dmic/CMakeFiles/drivers__dai__intel__dmic.dir/dmic_nhlt.c.obj
[153/371] Building C object zephyr/drivers/dai/intel/ssp/CMakeFiles/drivers__dai__intel__ssp.dir/ssp.c.obj
ninja: build stopped: subcommand failed.
FATAL ERROR: command exited with status 1: /ho

```

**Comment by kv2019i** [comment]
@fkwasowi can you check, it seems LNL build is failing after the L1_EXIT PR was merged to Zephyr.

**Review by marc-hb — APPROVED** [review]
Thank you @dbaluta ! I can reproduce the LNL issue with the Zephyr main branch, it's unrelated, we know where it comes from and it can be ignored.

The comparison between Linux and Windows builds is especially good news:
https://github.com/thesofproject/sof/actions/runs/7196263630/job/19601262153?pr=8618

It proves that the two toolchains are identical.

Let's merge this ASAP!

**Comment by marc-hb** [comment]
https://sof-ci.01.org/sof-pr-viewer/#/build/PR8618/build13273192 has only one error in only one test and again that CI does NOT use the Zephyr SDK

@lrudyX , @wszypelt I've never seen that error before:
```
07:24:43,755 INFO  - ### Quality verification for test_0_hda_codec_loopback_dma_(0, 0)_channels_2.wav ###
07:24:43,755 INFO  -
07:24:43,755 INFO  -
07:24:43,755 INFO  - ### VerifyQuality output ###
07:24:43,755 INFO  -
07:24:43,755 INFO  -
07:24:43,755 INFO  - Unhandled Exception: System.BadImageFormatException: Could not load file or assembly 'CoreAudioAPI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format. ---> System.BadImageFormatException: Could not load file or assembly '210429 bytes loaded from VerifyQuality, Version=2.4.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format. ---> System.BadImageFormatException: Bad IL format.
07:24:43,755 INFO  - --- End of inner exception stack trace ---
07:24:43,755 INFO  - at System.Reflection.RuntimeAssembly.nLoadImage(Byte[] rawAssembly, Byte[] rawSymbolStore, Evidence evidence, StackCrawlMark& stackMark, Boolean fIntrospection, Boolean fSkipIntegrityCheck, SecurityContextSource securityContextSource)
07:24:43,755 INFO  - at System.Reflection.Assembly.Load(Byte[] rawAssembly, Byte[] rawSymbolStore)
07:24:43,755 INFO  - at Costura.AssemblyLoader.ReadFromEmbeddedResources(Dictionary`2 assemblyNames, Dictionary`2 symbolNames, AssemblyName requestedAssemblyName)
07:24:43,755 INFO  - at Costura.AssemblyLoader.ResolveAssembly(Object sender, ResolveEventArgs e)
07:24:43,755 INFO  - at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
07:24:43,755 INFO  - --- End of inner exception stack trace ---
07:24:43,755 INFO  - at VerifyQuality.Program.Main(String[] args)
```

**Review by kv2019i — APPROVED** [review]

**Comment by dbaluta** [comment]
@lgirdwood  @marc-hb I think this is good to merge, right?

**Comment by kv2019i** [comment]
As this does not affect the Intel CI builds, I'll ignore the internal CI errors and proceed with merge.

**Comment by wszypelt** [comment]
@marc-hb @kv2019i 
Sporadic errors with Verify Quality have started appearing on TGL, we are currently working on what could be the cause. Currently, all tests have been passed successfully on this PR

**Pull request merged**
