### PR TITLE
[Draft] Revert/pr7700 tdfb

### PR DESCRIPTION
**Pull request by fredoh9**
https://github.com/thesofproject/sof/pull/7700 reverted

### CODE REVIEW

**Comment by fredoh9** [comment]
I have checked the device test result, still ongoing but it looks good so far.

**Comment by andrula-song** [comment]
can you share the log of exception? as I know, in our default pipeline it should not contain TDFB component right know. I'am afraid it is another issue has not been exposed before.

**Comment by fredoh9** [comment]
Kernel driver caught DSP Exeption but mtrace doesn't have the exception.

Intel internal test result link: planresultdetail/28228

[mtl-nocodec-mtrace.txt](https://github.com/thesofproject/sof/files/11890657/mtl-nocodec-mtrace.txt)
[mtl-nocodec-dmesg.txt](https://github.com/thesofproject/sof/files/11890658/mtl-nocodec-dmesg.txt)

**Comment by andrula-song** [comment]
I tested on device by my own, it seems the error not happens every time. And the ipc timeout first appeared here https://sof-ci.ostc.intel.com/#/result/planresultdetail/28182?model=MTLP_RVP_NOCODEC&testcase=check-suspend-resume-with-playback-5. So I tried to keep my code and revert the commit 73cd960e0ed4d0594dd3a974bec816d261b1fc14(https://github.com/thesofproject/sof/pull/7857), I never met this anymore.
Since there is no TDFB in our pipeline, I think the root cause may not be the TDFB optimization, can you @fredoh9 double check?

**Comment by ranj063** [comment]
> I tested on device by my own, it seems the error does not happen every time. And the ipc timeout first appeared here https://sof-ci.ostc.intel.com/#/result/planresultdetail/28182?model=MTLP_RVP_NOCODEC&testcase=check-suspend-resume-with-playback-5. So I tried to keep my code and revert the commit [73cd960](https://github.com/thesofproject/sof/commit/73cd960e0ed4d0594dd3a974bec816d261b1fc14)(#7857), and I never met this anymore. Since there is no TDFB in our pipeline, I think the root cause may not be the TDFB optimization, can you @fredoh9 double check?

I Have to agree that the tdfb optimization cannot possibly result in the PM regression. @fredoh9 Can you pleae check if #7857 is the culprit?

**Comment by fredoh9** [comment]
#7857 has included multiple commits but it was tested in yesterday daily.
Let me revert it while keeping TDFB changes.

**Comment by marc-hb** [comment]
> https://github.com/thesofproject/sof/pull/7857 has included multiple commits but it was tested in yesterday daily.
> Let me revert it while keeping TDFB changes.

You will have to revert #7325 first because 7325 depends on 7857

**Comment by fredoh9** [comment]
And https://github.com/thesofproject/sof/pull/7857 was daily tested. It alone doesn't create the crash.

Yesterday's daily test link: planresultdetail/28254
SOF Branch: main
SOF Commit: [73cd960e0ed4](https://github.com/thesofproject/sof/commit/73cd960e0ed4)

**Comment by fredoh9** [comment]
To double checking the result, submitted https://github.com/thesofproject/sof/pull/7873

**Comment by marc-hb** [comment]
Discussion moved to new bug filed by @fredoh9 (thx):
- #7875

**Comment by fredoh9** [comment]
closing this, discussion in https://github.com/thesofproject/sof/issues/7875

**Pull request closed without merging**
