### PR TITLE
Enable dynamic pipelines for HDA and some nocodec topologies

### PR DESCRIPTION
**Pull request by ranj063**

### CODE REVIEW

**Comment by plbossart** [comment]
IPC error with APL nocodec -> likely still something fishy?

**Comment by ranj063** [comment]
> IPC error with APL_UP2_NOCODEC > likely still something fishy?

@plbossart it looks like the kernel commit that the device test uses is 93d91f00 which doesnt include my fix. @fredoh9 do you know why it didnt pick up the tip of sof-dev?

**Comment by ranj063** [comment]
> IPC error with APL_UP2_NOCODEC > likely still something fishy?

the test passed locally for me on the up2. looks like I have to wait until today's daily build to get the latest fixes on sof-dev

**Comment by ranj063** [comment]
SOFCI TEST

**Comment by ranj063** [comment]
@plbossart the device tests look good now

**Comment by keyonjie** [comment]
@ranj063 How will we proceed converting existed pipelines to dynamic ones?
Will the change happen in topology file level or in pipeline level (similar to what the PR change here)?

**Comment by ranj063** [comment]
> @ranj063 How will we proceed converting existed pipelines to dynamic ones?
> Will the change happen in topology file level or in pipeline level (similar to what the PR change here)?

Depends on the tplg. For topologies with volatile kcontrols, it will be per pipeline. For others, we can switch the whole topology.

**Review by lgirdwood — APPROVED** [review]
CI showing unrelated Zephyr container failure.

**Comment by marc-hb** [comment]
> @plbossart it looks like the kernel commit that the device test uses is 93d91f00 which doesnt include my fix. @fredoh9 do you know why it didnt pick up the tip of sof-dev?

For CI performance reasons only `thesofproject/linux` pull requests rebuild the kernel from scratch. Pull requests on other repos use a daily build of the kernel. Keep in mind CI does not use `ktest` or similar, it builds an "atomic" kernel distribution package for automation reliability reasons: https://thesofproject.github.io/latest/getting_started/build-guide/build-from-scratch.html#build-linux-kernel

**Comment by marc-hb** [comment]
For regressions and temporary revert on `apl-nocodec` see #4199 and #4273

**Pull request merged**
