### PR TITLE
xtensa-build-zephyr.py: compress sof-info files in parallel

### PR DESCRIPTION
**Pull request by marc-hb**
On my system this brings the `install_platform()` duration down from about 3 seconds to less than 1 second.

Signed-off-by: Marc Herbert <marc.herbert@intel.com>

### CODE REVIEW

**Review by paulstelian97 — APPROVED** [review]

**Review by kv2019i — APPROVED** [review]
Would be good to have ack from someone that this works in non-Linux build hosts.

**Comment by marc-hb** [comment]
What we need is some basic Windows automation:

- https://github.com/actions/runner-images/blob/main/images/win/Windows2019-Readme.md
- https://docs.zephyrproject.org/latest/develop/getting_started/index.html#install-zephyr-sdk , Windows Tab

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
@aborisovich good for Windows, this and other recent python updates ?

**Comment by aborisovich** [comment]
> @aborisovich good for Windows, this and other recent python updates ?

Hold on I'll make a run in a moment

**Pull request merged**
