### PR TITLE
west.yml: update zephyr to b2f7ea0523

### PR DESCRIPTION
**Pull request by tmleman**
Zepych update: total of 763 commits.

492517b918 west.yml: Update NXP HAL SDK to 2.14
a5d1fd9857 soc: adsp: clk: update clock switch flow
9656056b19 dts: adsp: ace20: remove lp clock
50f0e223e8 dts: adsp: ace15: remove lp clock
cf6d5f95b6 adsp: clk: ace: select ipll if wovrco is unavailable
2d835e1b29 dts: adsp: ace20: replace hp with ipll clock
dcecda859c dts: adsp: ace15: replace hp with ipll clock
2f2689e3d3 intel_adsp: ace15: shim: update wovrco request bit
ea9dd59460 yamllint: bindings: add ipll clock index
1ddabfa8d8 dai: intel: dmic: fix shadow variable
b26921d776 dai: intel: dmic: New functions for writing fir coefficients
cba9ec10c3 dai: intel: tgl: dmic: Refactor of dai_nhlt_dmic_dai_params_get function
c28e8ba9ba dai: intel: dmic: Add pdm_base and pdm_idx variables in blob parser
2452aaad50 dai: intel: dmic: Separate fir configuration code into function
f74fd8edaf dai: intel: ace: dmic: Add dai_dmic_start_fifo_packers function
76d03e798f dai: intel: ace: dmic: Using the WAIT_FOR macro in waiting functions
3fbaed4de9 dai: intel: ace: dmic: Refactor of dai_nhlt_dmic_dai_params_get function
d7672af838 dai: intel: dmic: Combine PDM registers definitions
8ea53d49b6 dai: intel: dmic: nhlt: Move debug print code to a separate functions
81944c5c62 dai: intel: dmic: Move definitions of nhlt structures to a new file

### CODE REVIEW

**Comment by tmleman** [comment]
Known issues:

- **checkpatch**: commit titles for dmic in zephyr are too long, but I would keep them in original form.
- **build-linux (-d, mnfst, mtl)** e.t.c: [issue](https://github.com/thesofproject/sof/actions/runs/6318484925/job/17157568480?pr=8268) already [fixed](https://github.com/zephyrproject-rtos/zephyr/commit/b4998c357e43ff99714dc9f33ea5721e397557b1).

I can't tell how serious are those fails [1](https://sof-ci.01.org/sofpr/PR8268/build13504/devicetest/index.html) [2](https://sof-ci.01.org/sofpr/PR8268/build13505/devicetest/index.html) but it doesn't look bad.

**Comment by tmleman** [comment]
@lgirdwood internal CI is passing in this configuration

@iuliana-prodan fyi

**Review by marcinszkudlinski — APPROVED** [review]

**Review by iuliana-prodan — APPROVED** [review]

**Comment by iuliana-prodan** [comment]
> @lgirdwood internal CI is passing in this configuration
> 
> @iuliana-prodan fyi

Great!
Let's merge this :)

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
@tmleman I'm seeing a build error in some CI configs
```
zephyr/CMakeFiles/zephyr.dir/drivers/mm/mm_drv_intel_adsp_mtl_tlb.c.obj.d -o zephyr/CMakeFiles/zephyr.dir/drivers/mm/mm_drv_intel_adsp_mtl_tlb.c.obj -c /zep_workspace/zephyr/drivers/mm/mm_drv_intel_adsp_mtl_tlb.c
In file included from /zep_workspace/zephyr/include/zephyr/sys/mem_manage.h:104,
                 from /zep_workspace/zephyr/include/zephyr/sys/device_mmio.h:47,
                 from /zep_workspace/zephyr/include/zephyr/device.h:15,
                 from /zep_workspace/zephyr/drivers/mm/mm_drv_intel_adsp.h:17,
                 from /zep_workspace/zephyr/drivers/mm/mm_drv_intel_adsp_mtl_tlb.c:23:
/zep_workspace/zephyr/drivers/mm/mm_drv_intel_adsp_mtl_tlb.c: In function 'sys_mm_drv_mm_init':
/zep_workspace/zephyr/include/zephyr/sys/__assert.h:44:52: error: format '%p' expects argument of type 'void *', but argument 2 has type 'long unsigned int' [-Werror=format=]
   44 | #define __ASSERT_MSG_INFO(fmt, ...) __ASSERT_PRINT("\t" fmt "\n", ##__VA_ARGS__)
      |                                                    ^~~~
/zep_workspace/zephyr/include/zephyr/sys/__assert.h:36:47: note: in definition of macro '__ASSERT_PRINT'
   36 | #define __ASSERT_PRINT(fmt, ...) assert_print(fmt, ##__VA_ARGS__)
      |                                               ^~~
/zep_workspace/zephyr/include/zephyr/sys/__assert.h:118:25: note: in expansion of macro '__ASSERT_MSG_INFO'
  118 |                         __ASSERT_MSG_INFO(fmt, ##__VA_ARGS__);            \
      |                         ^~~~~~~~~~~~~~~~~
/zep_workspace/zephyr/drivers/mm/mm_drv_intel_adsp_mtl_tlb.c:669:17: note: in expansion of macro '__ASSERT'
  669 |                 __ASSERT(false,
      |                 ^~~~~~~~
cc1: all warnings being treated as errors
[80/384] Linking C static library zephyr/arch/common/libarch__common.a
[81/384] Building ASM object zephyr/arch/arch/xtensa/core/CMakeFiles/arch__xtensa__core.dir/wind
```

**Comment by tmleman** [comment]
> @tmleman I'm seeing a build error in some CI configs
> 
> ```
> zephyr/CMakeFiles/zephyr.dir/drivers/mm/mm_drv_intel_adsp_mtl_tlb.c.obj.d -o zephyr/CMakeFiles/zephyr.dir/drivers/mm/mm_drv_intel_adsp_mtl_tlb.c.obj -c /zep_workspace/zephyr/drivers/mm/mm_drv_intel_adsp_mtl_tlb.c
> In file included from /zep_workspace/zephyr/include/zephyr/sys/mem_manage.h:104,
>                  from /zep_workspace/zephyr/include/zephyr/sys/device_mmio.h:47,
>                  from /zep_workspace/zephyr/include/zephyr/device.h:15,
>                  from /zep_workspace/zephyr/drivers/mm/mm_drv_intel_adsp.h:17,
>                  from /zep_workspace/zephyr/drivers/mm/mm_drv_intel_adsp_mtl_tlb.c:23:
> /zep_workspace/zephyr/drivers/mm/mm_drv_intel_adsp_mtl_tlb.c: In function 'sys_mm_drv_mm_init':
> /zep_workspace/zephyr/include/zephyr/sys/__assert.h:44:52: error: format '%p' expects argument of type 'void *', but argument 2 has type 'long unsigned int' [-Werror=format=]
>    44 | #define __ASSERT_MSG_INFO(fmt, ...) __ASSERT_PRINT("\t" fmt "\n", ##__VA_ARGS__)
>       |                                                    ^~~~
> /zep_workspace/zephyr/include/zephyr/sys/__assert.h:36:47: note: in definition of macro '__ASSERT_PRINT'
>    36 | #define __ASSERT_PRINT(fmt, ...) assert_print(fmt, ##__VA_ARGS__)
>       |                                               ^~~
> /zep_workspace/zephyr/include/zephyr/sys/__assert.h:118:25: note: in expansion of macro '__ASSERT_MSG_INFO'
>   118 |                         __ASSERT_MSG_INFO(fmt, ##__VA_ARGS__);            \
>       |                         ^~~~~~~~~~~~~~~~~
> /zep_workspace/zephyr/drivers/mm/mm_drv_intel_adsp_mtl_tlb.c:669:17: note: in expansion of macro '__ASSERT'
>   669 |                 __ASSERT(false,
>       |                 ^~~~~~~~
> cc1: all warnings being treated as errors
> [80/384] Linking C static library zephyr/arch/common/libarch__common.a
> [81/384] Building ASM object zephyr/arch/arch/xtensa/core/CMakeFiles/arch__xtensa__core.dir/wind
> ```

This is already [fixed](https://github.com/zephyrproject-rtos/zephyr/commit/b4998c357e43ff99714dc9f33ea5721e397557b1) by @dbaluta but the zephyr update will not include this patch.

**Comment by dbaluta** [comment]
@tmleman so can we merge this ? and then you will later do another zephyr sha update?

**Comment by tmleman** [comment]
> @tmleman so can we merge this ? and then you will later do another zephyr sha update?

2 x Yes

**Pull request merged**
