### PR TITLE
init: compile out slave_core_init on UP arch

### PR DESCRIPTION
**Pull request by tlauda**
Compiles out slave_core_init on UP architecure.

Signed-off-by: Tomasz Lauda <tomasz.lauda@linux.intel.com>

### CODE REVIEW

**Comment by plbossart** [comment]
@tlauda I may have missed something, but what does the 'UP architecture' refer to? Not the UP boards I hope?

**Comment by lgirdwood** [comment]
@plbossart uni processor, not SMP

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by tlauda** [comment]
@lgirdwood @singalsu increased the SOF_TEXT_SIZE in #761, so there shouldn't be any additional CI failures.

**Pull request merged**
