### PR TITLE
cmake: fix build without traces

### PR DESCRIPTION
**Pull request by abonislawski**
Both patches will allow to build FW with traces disabled

### CODE REVIEW

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by lgirdwood** [comment]
Looks like a timeout on CI

**Comment by lgirdwood** [comment]
@abonislawski can you check the CI, build error still showing.

**Comment by abonislawski** [comment]
@lgirdwood fixed few issues with testbench cmake options which was hidden by traces

**Pull request merged**
