### PR TITLE
west.yml: update Zephyr to 1f55be8b42df

### PR DESCRIPTION
**Pull request by LaurentiuM1234**
Zephyr PR#70219 changes i.MX8ULP's SOC name to MIMX8UD7. As such, we need to update the board configuration file and the SOC name inside `xtensa-build-zephyr.py` to use the new SOC name.

This is just a clone of https://github.com/zephyrproject-rtos/sof/pull/43.

**EDIT**: also added changes from https://github.com/zephyrproject-rtos/sof/pull/44 to this PR.

### CODE REVIEW

**Comment by LaurentiuM1234** [comment]
FYI @kv2019i @marc-hb in case any 8ULP-related CI build failures creep their way in because of https://github.com/zephyrproject-rtos/zephyr/pull/70219

**Review by iuliana-prodan — APPROVED** [review]

**Review by marc-hb — CHANGES_REQUESTED** [review]
Thanks, this Zephyr upgrade should fix the daily tests where `zmain` just started failing:

https://github.com/thesofproject/sof/actions/runs/8475478210

A few changes requested though:

- Please squash everything in a single commit so every SOF commit still builds.
- For the commit message please keep re-using the same format, run `git log -- west.yml` for examples. A short summary of Zephyr changes that affect SOF is desired. It does not have to be perfect and exhaustive but please try.
- The current PR title is about the SOC name change but for most users the biggest change is probably the `west.yml` change. Yet they will ignore a PR that seems very NXP-specific.

**Comment by LaurentiuM1234** [comment]
> Thanks, this Zephyr upgrade should fix the daily tests where `zmain` just started failing:
> 
> https://github.com/thesofproject/sof/actions/runs/8475478210
> 
> A few changes requested though:
> 
> * Please squash everything in a single commit so every SOF commit still builds.
> * For the commit message please keep re-using the same format, run `git log -- west.yml` for examples. A short summary of Zephyr changes that affect SOF is desired. It does not have to be perfect and exhaustive but please try.
> * The current PR title is about the SOC name change but for most users the biggest change is probably the `west.yml` change. Yet they will ignore a PR that seems very NXP-specific.

Changes should be addressed in this new version. LMK if there's still stuff left to address.

FYI @kv2019i. This hash bump should also contain changes from https://github.com/thesofproject/sof/pull/8981

**Comment by marc-hb** [comment]
@wszypelt , @lrudyX : MTL and LNL tests did not run in https://sof-ci.01.org/sof-pr-viewer/#/build/PR8945/build13803550 because of some "connection refused", can you please take a look?

MTL was all green in https://sof-ci.01.org/sofpr/PR8945/build3704/devicetest/index.html and whatever cAVS we have left in https://sof-ci.01.org/sofpr/PR8945/build3705/devicetest/index.html was green too.

**Review by marc-hb — APPROVED** [review]

**Comment by LaurentiuM1234** [comment]
Included changes from https://github.com/thesofproject/sof/pull/9000

**Pull request merged**
