### PR TITLE
Readme: add gitter badge

### PR DESCRIPTION
**Pull request by cujomalainey**
Add badge to make finding the chat room a bit easier

Signed-off-by: Curtis Malainey <cujomalainey@chromium.org>

### CODE REVIEW

**Comment by marc-hb** [comment]
_[To "test" this change open the "Rich Diff" or click on "View file" in the "Files Changed" menu]_

I don't think this belong to the "Status" section,  how about the very top before any section?

BTW the other, "build status" badge is misleading: it reflects the last PR submission. I would remove it. I digress.

**Comment by cujomalainey** [comment]
@marc-hb the build badge does not reflect last PR, it reflects last build of master.

I tested using grip personally.

Also typical standard on github is to have all your badges together at the top of your readme
https://github.com/Shougo/deoplete.nvim
https://github.com/sunrise-php/vin

**Comment by marc-hb** [comment]
> > BTW the other, "build status" badge is misleading: it reflects the last PR submission. I would remove it. I digress.

> @marc-hb the build badge does not reflect last PR, it reflects last build of master.

Sometimes yes, sometimes not. For instance at this very moment 
https://travis-ci.org/github/thesofproject/sof shows this which is not merged yet:
https://travis-ci.org/github/thesofproject/sof/builds/689867879

> I tested using grip personally.

What is grip?


> Also typical standard on github is to have all your badges together at the top of your readme

That's what I suggested:

> > I don't think this belong to the "Status" section, how about the very top before any section?

**Comment by cujomalainey** [comment]
> > > BTW the other, "build status" badge is misleading: it reflects the last PR submission. I would remove it. I digress.
> 
> > @marc-hb the build badge does not reflect last PR, it reflects last build of master.
> 
> Sometimes yes, sometimes not. For instance at this very moment
> [travis-ci.org/github/thesofproject/sof](https://travis-ci.org/github/thesofproject/sof) shows this which is not merged yet:
> [travis-ci.org/github/thesofproject/sof/builds/689867879](https://travis-ci.org/github/thesofproject/sof/builds/689867879)
I'm not sure how you are verifying that. The query to travis literally passes in the branch to check. `https://travis-ci.org/thesofproject/sof.svg?branch=master`
The link on the other hand is general to the SOF travis page.
> 
> > I tested using grip personally.
> 
> What is grip?
https://github.com/joeyespo/grip
Local markdown previewer
> 
> > Also typical standard on github is to have all your badges together at the top of your readme
> 
> That's what I suggested:
> 
> > > I don't think this belong to the "Status" section, how about the very top before any section?

**Comment by marc-hb** [comment]
> I'm not sure how you are verifying that. 

I don't see why a tool is needed to test this. The "Build status" badge has been merged for some time to I simply go to https://github.com/thesofproject/sof. The "build passing" badge  is a link to https://travis-ci.org/thesofproject/sof which for some Travis reason seems to show the most recent (and not merged) PR submission of the moment.

Looking at the code (at last) I think I understand the confusion now: looks like the badge itself and what it links to are disconnected from each other.

**Comment by cujomalainey** [comment]
Yes, the link to the image and the general link to the build page are two separate markdown entities. If you prefer, we can switch to show the master build branch as the link, the main page is simply the default.

**Comment by marc-hb** [comment]
Yes I think it would less confusing. Or maybe even better, how about https://travis-ci.org/github/thesofproject/sof/branches ?

**Comment by marc-hb** [comment]
> Or maybe even better, how about https://travis-ci.org/github/thesofproject/sof/branches ?

Submitted in PR #3033

**Pull request merged**
