### PR TITLE
tools: topology: Fix runtime controlbytes name

### PR DESCRIPTION
**Pull request by dbaluta**
This was a copy paste error in the initial commit.

Signed-off-by: Daniel Baluta <daniel.baluta@nxp.com>

### CODE REVIEW

**Review by iuliana-prodan — APPROVED** [review]

**Review by juimonen — APPROVED** [review]

**Comment by dbaluta** [comment]
@stolx maybe this is related with what you are saying at the meeting yesterday. that sometimes runtime config gets loaded before setup config.

**Review by paulstelian97 — APPROVED** [review]

**Review by lgirdwood — APPROVED** [review]
@juimonen I'm assuming there is no UCM impact - can you check please. Thanks.

**Review by cujomalainey — APPROVED** [review]

**Comment by juimonen** [comment]
> @juimonen I'm assuming there is no UCM impact - can you check please. Thanks.

@lgirdwood AFAIK this name is not used yet in any public UCM I could find.

**Review by stolx — COMMENTED** [review]
> @stolx maybe this is related with what you are saying at the meeting yesterday. that sometimes runtime config gets loaded before setup config.

@dbaluta thanks, will check.
Since I did my own custom codec topology it might be that I made the same mistake.

**Pull request merged**
