### PR TITLE
lib_manager: Fix compilation if MM_DRV is not enabled

### PR DESCRIPTION
**Pull request by ujfalusi**
The module allocate/free uses APIs from MM_DRV but it does not declare dependency on it.
Make the code compile in the case when MM_DRV is not selected by only providing a reduced allocate/free functions with a print only.

Use a local define (PAGE_SZ) to store the page size to be used in the library manager code and in case of !MM_DRV set it to a default 4096 which is also used by the rimage when creating the manifest for the libraries.

### CODE REVIEW

**Comment by ujfalusi** [comment]
Changes since v1:
- Revert the MM_DRV dependency requirement as it is no longer needed for compilation

**Review by lgirdwood — APPROVED** [review]

**Review by kv2019i — APPROVED** [review]

**Review by lyakh — APPROVED** [review]

**Comment by kv2019i** [comment]
SOFCI TEST

**Comment by lgirdwood** [comment]
@wszypelt @lrudyX this PR fixes a build fix for a broken Kconfig so not expecting a failure (tried twice). Good to merge ?

**Comment by kv2019i** [comment]
@ujfalusi  One mandatory check failing....

**Comment by ujfalusi** [comment]
Changes since v2:
- fix miss typed CONFIG_MM_DRV (typed as MEM_DRV) causing internal CI failure

**Pull request merged**
