### PR TITLE
Tools: Test: Audio: Add sound direction test for TDFB

### PR DESCRIPTION
**Pull request by singalsu**
This patch adds Matlab script tdfb_direction_test.m. The test
simulates acoustical microphone array capture with 360 degrees
rotated noise source. The test topologies build adds an array
identifier to component name in topology file name. That
allows the scripts to simulate with several arrays. Now a
basic 2 mic array (no array suffix, just tdfb), 4 mic line,
and 8 mic circular are tested. Test pass/fail is so far only
visual check from plot.

The existing tdfb_test.c is extended to perform test with the
three test array configurations.

Signed-off-by: Seppo Ingalsuo <seppo.ingalsuo@linux.intel.com>

### CODE REVIEW

**Comment by singalsu** [comment]
This depends on new topology macros for TDFB, need to keep as draft for now.

**Comment by gkbldcig** [comment]
Can one of the admins verify this patch?

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by lgirdwood** [comment]
@singalsu testbench CI failed.

**Comment by singalsu** [comment]
> @singalsu testbench CI failed.

Yes, it can't be merged before #5288 due to dependences.

**Comment by singalsu** [comment]
SOFCI TEST

**Pull request merged**
