### PR TITLE
Cherry-pick RTNR commits from main branch

### PR DESCRIPTION
**Pull request by MingJenTai**

### CODE REVIEW

**Comment by cujomalainey** [comment]
@mwasko you are correct, in theory validation should be isolated to the RTK component and can be left to RTK

@MingJenTai please cherry-pick commits from main and don't add custom commits, also please remove your merge commits, we do not merge in this tree. It is better to amend your original commits so they work on the current branch (and state after a cherry pick line) rather than attempting to patch code that is not relevant to the branch or the feature

**Review by cujomalainey — APPROVED** [review]
@mwasko do have any idea why everything is failing?

**Comment by MingJenTai** [comment]
> 
> 
> @mwasko you are correct, in theory validation should be isolated to the RTK component and can be left to RTK
> 
> @MingJenTai please cherry-pick commits from main and don't add custom commits, also please remove your merge commits, we do not merge in this tree. It is better to amend your original commits so they work on the current branch (and state after a cherry pick line) rather than attempting to patch code that is not relevant to the branch or the feature

@cujomalainey I've created a new PR( https://github.com/thesofproject/sof/pull/4952 ) that picks the same commits, but with original commits and modification stated in commit message. Please use that one instead, thank you!

@mwasko There are build errors on current HEAD of adl-003-drop-stable. It should be the cause of CI build errors.

**Review by mwasko — APPROVED** [review]

**Comment by CliffsDover** [comment]
Thanks for the review. Please merge new PR  https://github.com/thesofproject/sof/pull/4952 instead. I’ll close this PR.

**Pull request closed without merging**
