### PR TITLE
topology1: Add CHANNELS_MIN macro for playback pipeline

### PR DESCRIPTION
**Pull request by dbaluta**
This will users to configure channels_min. The default
behavior is not changed.

Signed-off-by: Daniel Baluta <daniel.baluta@nxp.com>

### CODE REVIEW

**Review by ranj063 — APPROVED** [review]

**Comment by dbaluta** [comment]
I wonder if ``` sof-ci/jenkins/pr-device-test — On-device Test Failed:CML_HEL_RT5682 ``` is a legit fail or not.

**Comment by dbaluta** [comment]
SOFCI TEST

**Review by plbossart — APPROVED** [review]

**Comment by dbaluta** [comment]
@lgirdwood Please don't merge this yet, I'm investigating the Ci failure. It might happen that this change have a nasty side effect on capture pipelines. 

Because CHANNELS_MIN will remain defined after it is used.

**Comment by plbossart** [comment]
@dbaluta it could be that your branch is based on an older commit, we reverted a bunch of patches that broke CML (CometLake) devices on Friday. Maybe rebasing would help, if CI tests your branch and not the merged version?

**Comment by dbaluta** [comment]
All good now.

**Review by lgirdwood — APPROVED** [review]

**Pull request merged**
