### PR TITLE
rebuild-testbench.sh: remove CMAKE_VERBOSE_MAKEFILE

### PR DESCRIPTION
**Pull request by marc-hb**
2 commits, see commit messages

Default is verbose enough. VERBOSE=1 can still be used later at make
time.

Also change nproc to nproc --all because we don't care about offline
processors.

### CODE REVIEW

**Comment by ymdatta** [comment]
LGTM.

**Review by ymdatta — APPROVED** [review]

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
Looks like DUT HW issue on Jenkins.

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by jajanusz** [comment]
Shouldn't we be more consistent in scripts? After this PR we will have some with CMAKE_VERBOSE_MAKEFILE and some without.

**Comment by lgirdwood** [comment]
@jajanusz we should be consistent. @ymdatta can you update the other Cmake files.
@zrombel fyi - CI failure looks unrelated.

**Comment by marc-hb** [comment]
> After this PR we will have some with CMAKE_VERBOSE_MAKEFILE and some without.

Which scripts still have CMAKE_VERBOSE_MAKEFILE on by default? I haven't spotted any recently besides the deprecated one this replaces (so it doesn't really count)

PS: don't get me wrong, I think the default log level in automation should generally be quite high because it's unfortunately sometimes difficult to reproduce the exact CI environment and failure(s) locally. However:
- automation can/should increase the log level only for itself, not by default otherwise developers stop looking at logs. Recent example of developers not looking at too verbose logs and missing an error for months and months: #2656 
- CMAKE_VERBOSE_MAKEFILE is IMHO not just verbose, it's crazy verbose and I found it rarely ever useful when you're not debugging CMake code.
- I always found CMake issues easy to reproduce locally (reproduce != fix)

**Comment by lgirdwood** [comment]
Ok, lets merge this and fix any other VERBOSE settings in a new PR

**Pull request merged**
