### PR TITLE
platform: remove platform/drivers/idc.h for Intel platforms

### PR DESCRIPTION
**Pull request by kv2019i**
For Zephyr builds, only definition needed from platform/drivers/idc.h was prototype for idc_send_msg(). There's no need to keep the platform layer just for this, so add the definition to rtos/idc.h for Zephyr builds, and remove the platform/drivers/idc.h for all Intel platforms.

### CODE REVIEW

**Comment by kv2019i** [comment]
@thesofproject/nxp This should be good for all IMX platforms as we link zephyr_idc.c for all Zephyr SOF platforms. So I think the dummy definition of idc_send_msg() you have in many IMX idc.h platform headers, could be removed as well. I was not sure which platforms are Zephyr-only already. so didn't add this change to this PR yet.

**Review by lgirdwood — APPROVED** [review]

**Review by abonislawski — APPROVED** [review]

**Review by tmleman — APPROVED** [review]

**Comment by kv2019i** [comment]
V2:
- posix/library Zephyr builds failed -> fix by keeping the platform header for these targets
- compiler warning on multiple platform.c files, fix

**Comment by kv2019i** [comment]
V3: 
- fix link error on non-smp IMX platforms when building for Zephyr

**Comment by kv2019i** [comment]
V4:
- stub the IDC interface so to make both fuzzer and SOF plugin happy

**Pull request merged**
