### PR TITLE
[DNM] west.yml: upgrade Zephyr to 8f34181e3dd73fa7 + PR54900 backport

### PR DESCRIPTION
**Pull request by kv2019i**
Follow-up to #7102 with fixes to Zephyr and SOF to make the SOF testsi using DW-DMA to pass.

### CODE REVIEW

**Comment by kv2019i** [comment]
@lyakh sparse-mtl check passing! :)

**Comment by aiChaoSONG** [comment]
@marc-hb any idea what the github action build failure
```
fatal: expected 'acknowledgments'
Error: Process completed with exit code 128.
```
 is.

**Comment by marc-hb** [comment]
You forgot the link: https://github.com/thesofproject/sof/actions/runs/4196943245/jobs/7278612315

> @marc-hb any idea what the github action build failure `fatal: expected 'acknowledgments'`

Yes that's because we use west fetch --narrow to speed things up and it's unfortunately incompatible with SHA1s :-( 

The alternative is to use a branch name. This can be `pull/12345/head` or `pull/12345/merge` if there is a pull request (but it does not have to be).

**Comment by sys-pt1s** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
