### PR TITLE
mailboxes: added sizes and offsets values to IPC

### PR DESCRIPTION
**Pull request by smakows**

### CODE REVIEW

**Comment by xiulipan** [comment]
@smakows 
You may need also to change the uapi in kernel part.
https://github.com/thesofproject/linux/blob/b87a468a5bf1863b3d371cb9dfe2c718225feb68/include/uapi/sound/sof-ipc.h#L771

**Comment by mengdonglin** [comment]
CI observed building failure.

Failed Platform: baytrail apollolake cannonlake

configure: error: in `/build/sof/src':
configure: error: C compiler cannot create executables

**Comment by smakows** [comment]
Please do not merge until proper PR in linux repo is approved

**Comment by plbossart** [comment]
@smakows I don't see a PR in linux repo?

**Comment by xiulipan** [comment]
@smakows
would you rebase your PR branch to recommit with the right descriptions with the patch really did?
I think this PR is for some deprecated code clean up now.
People will be confuse with your previous commit
`mailboxes: added sizes and offsets values to IPC`
and later `review fixes`
once the patch is merged in.

**Comment by plbossart** [comment]
@smakows can you close this PR or provide an update, it's been 20 days without activity

**Pull request closed without merging**
