### PR TITLE
LLEXT: Minor improvements

### PR DESCRIPTION
**Pull request by lyakh**
Several minor fixes and improvements from #9688

### CODE REVIEW

**Comment by lyakh** [comment]
https://sof-ci.01.org/sofpr/PR9703/build9630/devicetest/index.html unfortunately only tested SDW, we need HDA tested, restart SOF CI

**Comment by lyakh** [comment]
SOFCI TEST

**Comment by lyakh** [comment]
A few failures on LNL, but supposedly all known https://sof-ci.01.org/sofpr/PR9703/build9638/devicetest/index.html

**Review by kv2019i — APPROVED** [review]
Good fixes and easy to follow commit messages!

**Review by lgirdwood — APPROVED** [review]

**Comment by kv2019i** [comment]
sof-docs fail and Intel LNL fails all known and tracked in https://github.com/thesofproject/sof/issues?q=is%3Aissue+is%3Aopen+label%3A%22Known+PR+Failures%22+

**Pull request merged**
