### PR TITLE
audio: move hifi implementations to arch/xtensa

### PR DESCRIPTION
**Pull request by tlauda**
Moves HiFi implementations of processing components to the arch/xtensa directory, where they belong. There is no point in keeping arch dependent implementations in generic layer.

### CODE REVIEW

**Comment by tlauda** [comment]
@lgirdwood I strongly disagree. This change makes even more sense for the integrator, where he just want to touch his "own" architecture implementation. It has already happened twice for me, when going through the code, that people has asked why xtensa specific component processing is not in the arch directory.

Major pros of such solution:
- This way we avoid one large directory with all the implementations for different architectures.
- Usage of the generic implementation based on !CONFIG_<COMP_NAME>_ARCH definition (it can be done even more generic than right now).
- We can truly compile out the implementation since we use entirely different architecture. XCHAL_* definitions cannot be resolved during Kconfig phase, so we still build object files for every implementation.

Cons:
- Implementations spread across different directories (which already happens for things in lib, drivers etc. so really no difference here).

**Comment by lgirdwood** [comment]
@tlauda I agree that spreading infrastructure makes sense to align architecture specific code, but algorithms, modules, components need to stay put since most will be 3rd party, binary only and break this model anyway. The engineers who will be mostly working on algos will also not be SOF experts (and will not have time to care about internals, or directory structure), so keeping all their code in one place makes it really simple for them.

**Comment by tlauda** [comment]
@lgirdwood Agree, but that's the reason why it makes even more sense. If they are no experts, then they are going to ask where to put their implementation anyway, so it makes no difference for them. Components' control layer will need to be done by SOF familiar engineers, who understand the flows.

**Comment by lgirdwood** [comment]
@tlauda It make no sense for algos. I just want to tell algo integrations, please look at component/module X in src/audio/x.c|.h and copy. Why would they want to do extra work and move code around for zero net value ? The component/module development surface should have near to minimal learning curve as possible, this proposal just adds unessessary extra effort.

This probably also splits component/module TEXT across different archives too, making any runtime module loading and unloading far more complex.

**Comment by dbaluta** [comment]
@tlauda it doesn't make sense to move hifi algo implementtion to arch. Arch should only contain intrinsic dsp platform code. 

Would make more sense to create src/audio/xtensa , src/audio/generic, etc.

**Pull request closed without merging**
