### PR TITLE
topology: define PIPELINE_FORMAT from DAI_ADD

### LINKED ISSUE #5193: [BUG] [Topology1] Macro "PIPELINE_FORMAT" and "PCM_ID" not expanded
**Describe the bug**
The macro `PIPELINE_FORMAT` is not replaced with its value, for example, s32le, in the generated conf by m4.

**To Reproduce**
Run script to build topology: `./script/build-tools.sh -T`
Search the keyword `PIPELINE_FORMAT` from sof/tools/build-tools/topology/\*.conf

Issue introduced by c687815185948d49350e4b58d59e786ac16339e1, confirmed.

PCM_ID is not expanded, `PIPELINE_FORMAT` and `PCM_ID` are the only two macro that not expanded after c68781518

### PR DESCRIPTION
**Pull request by lkoenig**
Pipeline extects PIPELINE_FORMAT to be defined. When including a
pipeline using DAI_ADD, DAI_FORMAT is defined but no PIPELINE_FORMAT.
Prior c687815, the last previously defined PIPELINE_FORMAT was used.
This change ensure the requested DAI_FORMAT is used in the pipeline.

This resolve #5193.

Signed-off-by: Lionel Koenig <lionelk@google.com>

### CODE REVIEW

**Review by lgirdwood — APPROVED** [review]
Thanks @lkoenig

**Comment by lgirdwood** [comment]
@aiChaoSONG pls confirm this fixes for you and we can merge.

**Review by aiChaoSONG — APPROVED** [review]

**Comment by aiChaoSONG** [comment]
This PR only fix the PIPELINE_FORMAT issue introduced by c687815, @miRoox  also found an issue with KWD, I compared the conf file, the stream name is wrong.
```
	stream_name "Sound Trigger Capture PCM_ID"
```

@lkoenig I think you should search all the macro undefined in c687815, and check what's missing.

**Review by dbaluta — APPROVED** [review]

**Comment by lkoenig** [comment]
I ensure PCM_ID is also defined by using PIPELINE_PCM_ADD when adding a detect pipeline.
@dbaluta and @aiChaoSONG could you check if that solves the issue for you ?

**Comment by aiChaoSONG** [comment]
@miRoox  Please help to verify if the KWD issue is fix with this PR.

**Review by miRoox — COMMENTED** [review]
According to the inner test result 9416, the KWD issue is fixed by this PR

**Pull request merged**
