### PR TITLE
Removed sof-logger

### PR DESCRIPTION
**Pull request by aborisovich**
Sof logger is used for legacy platforms and is not used for Meteorlake. Static analysis tool issued many errors related to the logger - removed the project.

Signed-off-by: Andrey Borisovich <andrey.borisovich@intel.com>

### CODE REVIEW

**Review by marcinszkudlinski — APPROVED** [review]

**Comment by marc-hb** [comment]
Any idea why MTL does not build? https://github.com/thesofproject/sof/actions/runs/3650616164/jobs/6166821755

**Comment by lgirdwood** [comment]
Hang on - sof-logger will still be used by xtos users. Needs to be reverted unless this is now in a tools repo. @marcinszkudlinski @aborisovich any comments ?

**Comment by dbaluta** [comment]
Wait a second we are still heavily using sof-looger? What is the alternative for it? Or what's the plan here?

**Comment by marcinszkudlinski** [comment]
this relase is for mtl-zephyr only. Mtrace python script should be used there. 
As security fixes was a little problematic and time is very short, we just removed binary that is not a part of the release. Main branch, of course, requires a valid fix.

**Comment by paulstelian97** [comment]
This PR was merged with a single approval. Yes, it was merged in a feature branch rather than the main one, but I do feel it was a rush job, which I believe should raise some red flags about how things are done. Honestly.

This, plus the incident from yesterday... Who is demanding that static analysis tools are to be obeyed with _such_ an urgency that proper review is skipped, even if it's strictly for a platform-specific branch?

**Comment by lgirdwood** [comment]
> This PR was merged with a single approval. Yes, it was merged in a feature branch rather than the main one, but I do feel it was a rush job, which I believe should raise some red flags about how things are done. Honestly.
> 
> This, plus the incident from yesterday... Who is demanding that static analysis tools are to be obeyed with _such_ an urgency that proper review is skipped, even if it's strictly for a platform-specific branch?

That's a good point - on Intel side we are working out how we can do a more frequent scan with static analysis tools and how this can be more automated and frequent. We still need to work quite a few things out. Unfortunately the tooling is very manual and cumbersome atm and this was a work item for this sprint.  We are working to improve this though, but this sounds like a good topic for next TSC as its for everyone's benefit.

**Comment by marc-hb** [comment]
> Wait a second we are still heavily using sof-logger. 

@dbaluta there was at least one obvious bug reported in #6738, would you mind fixing it in the main branch? We stopped using sof-logger in the main branch.

**Pull request merged**
