### PR TITLE
cannonlake: keep run in waiti loop for power_down

### PR DESCRIPTION
**Pull request by keyonjie**
To align with apollolake, keep run in the waiti while(1) loop for power
down.

Signed-off-by: Keyon Jie <yang.jie@linux.intel.com>

### CODE REVIEW

**Comment by keyonjie** [comment]
> @keyonjie Are you observing any improvement with this change? I found in the code that all interrupts are disabled before entering this routine, so the waiti here is to fire pg transition (if pg is activated correctly before).

@mmaka1 not tested yet, so here it is just an alignment to apl when I reading to it. You are right if all interrupts are disabled successfully, we should be trapped in waiti for ever, but with that actually we don't need the 'while(1)' loop neither?

**Comment by paulstelian97** [comment]
> > @keyonjie Are you observing any improvement with this change? I found in the code that all interrupts are disabled before entering this routine, so the waiti here is to fire pg transition (if pg is activated correctly before).
> 
> @mmaka1 not tested yet, so here it is just an alignment to apl when I reading to it. You are right if all interrupts are disabled successfully, we should be trapped in waiti for ever, but with that actually we don't need the 'while(1)' loop neither?

There is no guarantee `waiti` will remain even if it doesn't respond to interrupts. Hardware is allowed to be finnicky in this sense so the loop is required (unless you know something about your particular DSP that the Xtensa architecture itself doesn't guarantee)

**Comment by keyonjie** [comment]
> > > @keyonjie Are you observing any improvement with this change? I found in the code that all interrupts are disabled before entering this routine, so the waiti here is to fire pg transition (if pg is activated correctly before).
> > 
> > 
> > @mmaka1 not tested yet, so here it is just an alignment to apl when I reading to it. You are right if all interrupts are disabled successfully, we should be trapped in waiti for ever, but with that actually we don't need the 'while(1)' loop neither?
> 
> There is no guarantee `waiti` will remain even if it doesn't respond to interrupts. Hardware is allowed to be finnicky in this sense so the loop is required (unless you know something about your particular DSP that the Xtensa architecture itself doesn't guarantee)

@paulstelian97 good to know about that, then we need this change, otherwise, the loop could end at here but waiti, isn't it?
```
1:
goto 1b;
```

**Comment by paulstelian97** [comment]
> > > > @keyonjie Are you observing any improvement with this change? I found in the code that all interrupts are disabled before entering this routine, so the waiti here is to fire pg transition (if pg is activated correctly before).
> > > 
> > > 
> > > @mmaka1 not tested yet, so here it is just an alignment to apl when I reading to it. You are right if all interrupts are disabled successfully, we should be trapped in waiti for ever, but with that actually we don't need the 'while(1)' loop neither?
> > 
> > 
> > There is no guarantee `waiti` will remain even if it doesn't respond to interrupts. Hardware is allowed to be finnicky in this sense so the loop is required (unless you know something about your particular DSP that the Xtensa architecture itself doesn't guarantee)
> 
> @paulstelian97 good to know about that, then we need this change, otherwise, the loop could end at here but waiti, isn't it?
> 
> ```
> 1:
> goto 1b;
> ```

The difference between:

```
1:
  waiti 0
  goto 1b
```

and

```
1:
  goto 1b
```

is power usage, really. The waiti instruction will suspend the CPU. It's just that transient hardware flukes will still wake up the CPU (and cause it to continue after the `waiti`) even if there isn't a real interrupt. I have in fact seen that on my own hardware, a huge amount of wakes without actually entering the interrupt handler, whenever I enabled a certain interrupt that is extremely transient and turns off either before the DSP checks for a handler on its own or before IRQ_STEER has a chance to figure out that there was an interrupt for that IRQ number.

If the interrupts are disabled we should in theory not require the loop. But what about NMIs? I'm not 100% sure but I think there is the possibility for NMI, and we can have (again due to quantum fluctuations or other misconfiguration) the possibility of getting very transient NMIs, so transient that we don't even enter the handler. But it will still exit the waiti instruction. Or, actual real NMIs.

**Comment by ranj063** [comment]
@paulstelian97 on an unrelated note, may I ask what the difference is between the 2 scenarios below:
1. while(1) wait_for_interrupt();
2. while();

I'd like to understand what happens when the FW does one of the above and the host driver resets the CPU after the FE does the above. 

What is the difference between doing a CPU reset when the DSp is suspended with a waiti vs when it is just busy with a while(1)?

**Comment by keyonjie** [comment]
> @paulstelian97 on an unrelated note, may I ask what the difference is between the 2 scenarios below:
> 
> 1. while(1) wait_for_interrupt();
> 2. while(1);
> 
> I'd like to understand what happens when the FW does one of the above and the host driver resets the CPU after the FE does the above.
> 
> What is the difference between doing a CPU reset when the DSp is suspended with a waiti vs when it is just busy with a while(1)?

@ranj063 I think "waiti" will put the DSP cores at low power state until interrupts arrive, and "while(1){}" runs as how it does with running normal instructs.

**Comment by ranj063** [comment]
> @ranj063 I think "waiti" will put the DSP cores at low power state until interrupts arrive, and "while(1){}" runs as how it does with running normal instructs.

@keyonjie yes, I understand this but my question is what happens when the CPU is reset after either a waiti or a while(1)

**Comment by paulstelian97** [comment]
> > @ranj063 I think "waiti" will put the DSP cores at low power state until interrupts arrive, and "while(1){}" runs as how it does with running normal instructs.
> 
> @keyonjie yes, I understand this but my question is what happens when the CPU is reset after either a waiti or a while(1)

In the case where it's inside a waiti it may take slightly longer due to being in a low power state when the actual reset happens. If a reset during waiti isn't possible that's a hardware flaw.

In both cases after reset the usual bootup code occurs in a similar fashion to power on. That is, the actual reset shouldn't be affected, except if it's very timing sensitive.

**Comment by ranj063** [comment]
> > > @ranj063 I think "waiti" will put the DSP cores at low power state until interrupts arrive, and "while(1){}" runs as how it does with running normal instructs.
> > 
> > 
> > @keyonjie yes, I understand this but my question is what happens when the CPU is reset after either a waiti or a while(1)
> 
> In the case where it's inside a waiti it may take slightly longer due to being in a low power state when the actual reset happens. If a reset during waiti isn't possible that's a hardware flaw.
> 
> In both cases after reset the usual bootup code occurs in a similar fashion to power on. That is, the actual reset shouldn't be affected, except if it's very timing sensitive.

@paulstelian97 the reason I asked this question was because what I'm noticing with the cht platform is that after the reset and stall with waiti, sometimes FW boot fails because the DSP cannot be unstalled.

But if I just use while(1); then there are no such problems.

**Comment by paulstelian97** [comment]
> > > > @ranj063 I think "waiti" will put the DSP cores at low power state until interrupts arrive, and "while(1){}" runs as how it does with running normal instructs.
> > > 
> > > 
> > > @keyonjie yes, I understand this but my question is what happens when the CPU is reset after either a waiti or a while(1)
> > 
> > 
> > In the case where it's inside a waiti it may take slightly longer due to being in a low power state when the actual reset happens. If a reset during waiti isn't possible that's a hardware flaw.
> > In both cases after reset the usual bootup code occurs in a similar fashion to power on. That is, the actual reset shouldn't be affected, except if it's very timing sensitive.
> 
> @paulstelian97 the reason I asked this question was because what I'm noticing with the cht platform is that after the reset and stall with waiti, sometimes FW boot fails because the DSP cannot be unstalled.
> 
> But if I just use while(1); then there are no such problems.

Ah, hardware specific quirks. I don't know that platform that well (I only know i.MX well) so I'll agree that it could be a bad idea on that hardware. But normally stuff like this shouldn't happen. Can you just check that a larger timeout allows the unstalling to work from that point?

**Comment by lbetlej** [comment]
SOFCI TEST

**Comment by lgirdwood** [comment]
@keyonjie any update ? Is there any change or improvement ?

**Comment by keyonjie** [comment]
@lgirdwood let me close this as I don't have chance to prove it is necessary.

**Pull request closed without merging**
