### PR TITLE
west.yml: update Zephyr to ceff785434b

### PR DESCRIPTION
**Pull request by kv2019i**
Patches affecting SOF:

fb54eb5ab133 llext: symbol.h: Explicit typecast in EXPORT_SYMBOL macros
ce243944375e llext: add object test case
33c6bdab9ad1 llext: add STT_OBJECT relocation
41b3c7158687 drivers: dma: intel_adsp_hda: Fix L1 exit condition
5cac834bb651 llext: arch_elf_relocate: pass opval unmodified

### CODE REVIEW

**Comment by kv2019i** [comment]
Submitting this right away. This might trigger CI fails as https://github.com/thesofproject/sof/pull/8936 is not yet merged, but let's see the results, we may need to merge that on an expedited schedule.

For Intel platforms, this brings potential fixes to https://github.com/thesofproject/sof/issues/8770 and https://github.com/thesofproject/sof/issues/8761 . But let's see the results.

**Review by serhiy-katsyuba-intel — APPROVED** [review]

**Comment by marc-hb** [comment]
ACE all green except MTLP_RVP_HDA unavailable in https://sof-ci.01.org/sofpr/PR8954/build3460/devicetest/index.html

CAVS https://sof-ci.01.org/sofpr/PR8954/build3461/devicetest/index.html has a DSP panic which is probably multicore panic #8942. But multicore was just turn off by 6bdbf7186ea12082.

Re-running these tests.

**Comment by marc-hb** [comment]
SOFCI TEST

**Review by lyakh — APPROVED** [review]

**Comment by kv2019i** [comment]
One system pm fail in https://sof-ci.01.org/sofpr/PR8954/build3482/devicetest/index.html 

In https://sof-ci.01.org/sofpr/PR8954/build3481/devicetest/index.html
There's a MOD_SET_DX  time out which matches fingerprints of https://github.com/thesofproject/sof/issues/8642 . So not a new issue. Proceeding with merge.

**Pull request merged**
