### PR TITLE
Mixin: fix binding

### PR DESCRIPTION
**Pull request by lyakh**
.bind() is called twice, in the order this is currently done in SOF, the second call overwrites with 0 the valid configuration from the first call. Remove that overwrite.

### CODE REVIEW

**Comment by lyakh** [comment]
@marcinszkudlinski @mwasko this fixes the problem, but I'm not sure whether this is really a correct fix

**Review by serhiy-katsyuba-intel — APPROVED** [review]
Great work, @lyakh!

**Comment by serhiy-katsyuba-intel** [comment]
> @marcinszkudlinski @mwasko this fixes the problem, but I'm not sure whether this is really a correct fix.

Why are you not sure? This looks exactly like a proper fix :)

**Comment by lyakh** [comment]
> > @marcinszkudlinski @mwasko this fixes the problem, but I'm not sure whether this is really a correct fix.
> 
> Why are you not sure? This looks exactly like a proper fix :)

@serhiy-katsyuba-intel I'm not sure because I don't quite understand why it was there initially and I don't know all possible scenarios when that path can be entered. So at least in theory this change, while fixing my case, can break something, that I'm not aware of.

**Comment by lyakh** [comment]
CI: two tests https://sof-ci.01.org/sofpr/PR6138/build1174/devicetest/?model=ADLP_RVP_NOCODEC_ZEPHYR&testcase=verify-tplg-binary and https://sof-ci.01.org/sofpr/PR6138/build1174/devicetest/?model=ADLP_RVP_NOCODEC_ZEPHYR&testcase=verify-pcm-list on ADLP_RVP_NOCODEC_ZEPHYR fail with
```
dd if=/dev/zero of=/home/ubuntu/HD_TEST_DELETE_ME bs=1M count=100 conv=fsync
```
timing out. An SSD problem? Additionally two suspend-resume tests timed out on APL_UP2_NOCODEC_ZEPHYR: https://sof-ci.01.org/sofpr/PR6138/build1174/devicetest/?model=APL_UP2_NOCODEC_ZEPHYR&testcase=check-suspend-resume-5 and https://sof-ci.01.org/sofpr/PR6138/build1174/devicetest/?model=APL_UP2_NOCODEC_ZEPHYR&testcase=check-suspend-resume-with-capture-5

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
> CI: two tests https://sof-ci.01.org/sofpr/PR6138/build1174/devicetest/?model=ADLP_RVP_NOCODEC_ZEPHYR&testcase=verify-tplg-binary and https://sof-ci.01.org/sofpr/PR6138/build1174/devicetest/?model=ADLP_RVP_NOCODEC_ZEPHYR&testcase=verify-pcm-list on ADLP_RVP_NOCODEC_ZEPHYR fail with
> 
> ```
> dd if=/dev/zero of=/home/ubuntu/HD_TEST_DELETE_ME bs=1M count=100 conv=fsync
> ```

looks like SSD issue ? @marc-hb any idea what this is doing other than wearing out the SSD ? I assume we want to flush VFS ?

**Review by ujfalusi — APPROVED** [review]
Tested and works!

Thanks @lyakh !!!

**Pull request merged**
