### PR TITLE
Remove data duplication between mailbox and extended manifest - save memory

### PR DESCRIPTION
**Pull request by ktrzcinx**
After merge #2957, extended manifest is included in each firmware image. Data structs from `fw_ready_metadata` has already been ported to extended manifest so there's no need to duplicate the same data in mailbox in the `fw_ready_metadata` section. Kernel code scan has support for both data location, so it shouldn't be an issue.
After changes 448 bytes has been saved from .TEXT segment and 536 bytes from .DATA and data duplication has been deleted.

I didn't delete `fw_ready_metadata` mechanism to keep possibility of passing eg. hardware related information (doesn't known at compilation time) to kernel, at start-up. 

Kernel can parse:
  - windows, compiler and firmware version/ABI after merge https://github.com/thesofproject/linux/pull/1903.
  - debug ABI after https://github.com/thesofproject/linux/pull/2155

### CODE REVIEW

**Comment by paulstelian97** [comment]
You claim extended manifest is enabled by default, not force-enabled. So what's gonna happen on systems where it is disabled?

I'd say this patch is welcome when extended manifest loses its kconfig and is always available.

**Comment by ktrzcinx** [comment]
@paulstelian97 there's no kconfig option for extended manifest on/off, after #2957 merge each build should contain this part.

**Review by paulstelian97 — APPROVED** [review]

**Review by lgirdwood — COMMENTED** [review]
@kv2019i fyi - does the kernel still read some items from mailbox ?

**Review by kv2019i — APPROVED** [review]
Looks good from kernel point of view. SOF1.7 will anyways require a recent kernel to load the FW, and these kernels can parse the info from ext_manifest, so we have no strict need to keep this around.

And as far as I can see, the IPC message ABI is not modified (which is good).

**Comment by lgirdwood** [comment]
@kv2019i just to confirm, this is good to merge today with no kernel update ?

**Comment by ktrzcinx** [comment]
@lgirdwood kernel is prepared for this for a long time (it was introduced with extended manifest support) - jenkins CI results are good proof of it. Internal Intel CI must updated, this work is in progress (near finish).

**Comment by lgirdwood** [comment]
@ktrzcinx ok, please ping when CI is finished. jenkins looks like a HW DUT is not booting.

**Comment by zrombel** [comment]
CI is ready, all tests are PASS, PR is good to merge.

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
CI jenkins looks like DUT HW issues as it's not booting.

**Comment by lyakh** [comment]
@lgirdwood @ktrzcinx this broke Zephyr boot

**Pull request merged**
