### PR TITLE
topology2: use pass-through pipeline for multicore test on cavs

### PR DESCRIPTION
**Pull request by RanderWang**
platforms

Fix daily CI issuse: failed to load multicore topology

It is caused by : https://github.com/thesofproject/sof/pull/7847. Currently DMIC is not enabled by daily CI test on CAVS platforms, so we need to set pass-though = true.

fix https://github.com/thesofproject/sof/issues/7931

### CODE REVIEW

**Review by kv2019i — APPROVED** [review]

**Comment by fredoh9** [comment]
Daily CI broker is for MTL, how will this fix MTL issue?

**Comment by RanderWang** [comment]
> Daily CI broker is for MTL, how will this fix MTL issue?

Thanks! updated for MTL.

**Comment by aiChaoSONG** [comment]
I don't think this will work, because define PASSTHROUGH to true is the same as not defining it or define it to any value other than false. 

Possible fix of issue #7931

**Comment by RanderWang** [comment]
> I don't think this will work, because define PASSTHROUGH to true is the same as not defining it or define it to any value other than false.
> 
> Possible fix of issue #7931 is #7960

No, the default PASSTHROUGH is false.

**Comment by RanderWang** [comment]
Attach topology build warning: why CI can't detect it ?
````
cmake --build /home/rander/Workspace/sof/tools/build_tools -- -j 20
[0/1] Re-running CMake...
-- Configuring done (0.1s)
-- Generating done (0.0s)
-- Build files have been written to: /home/rander/Workspace/sof/tools/build_tools
[0/3] Generating sof-mtl-nocodec-multicore.tplg
saving nhlt as binary in nhlt-sof-mtl-nocodec-multicore.bin
ALSA lib dapm.c:247:(tplg_build_routes) undefined source widget/stream 'module-copier.21.2'
[2/3] Generating sof-mtl-nocodec-multicore-ssp0-ssp2.tplg
saving nhlt as binary in nhlt-sof-mtl-nocodec-multicore-ssp0-ssp2.bin
ALSA lib dapm.c:247:(tplg_build_routes) undefined source widget/stream 'module-copier.21.2'

WARNING: building tools/ is now incremental by default!
         To build from scratch delete: /home/rander/Workspace/sof/tools/build_tools
         or use the -C option.
````

**Comment by RanderWang** [comment]
the original PR:https://github.com/thesofproject/sof/pull/7847 change PASSTHROUGH=true to false but forgot to add it to other MTL topology build, so It is unified to to set PASSTHROUGH=true for other MTL build.

**Comment by aiChaoSONG** [comment]
@RanderWang But do we really want use PASSTHROUGH=true, this will cause every pipeline to  host_copier->dai_copier connection, everything in the middle is removed. 

Of course, there is a gap between cavs-nocodec.conf and cavs-nocodec-multicore.conf, for cavs-nocodec.conf PASSTHROUGH=true makes every host->dai connection passthrough, but for cavs-nocodec-multicore.conf, PASSTHROUGH=true only makes DMIC passthrough.

**Comment by RanderWang** [comment]
> > I don't think this will work, because define PASSTHROUGH to true is the same as not defining it or define it to any value other than false.
> > Possible fix of issue #7931 is #7960
> 
> No, the default PASSTHROUGH is false.



> @RanderWang But do we really want use PASSTHROUGH=true, this will cause every pipeline to host_copier->dai_copier connection, everything in the middle is removed.
> 
> Of course, there is a gap between cavs-nocodec.conf and cavs-nocodec-multicore.conf, for cavs-nocodec.conf PASSTHROUGH=true makes every host->dai connection passthrough, but for cavs-nocodec-multicore.conf, PASSTHROUGH=true only makes DMIC passthrough.
> 
> @ranj063 I think we need get cavs-nocodec.conf and cavs-nocodec-multicore.conf aligned?

@aiChaoSONG  the cavs-nocodec-multicore.conf is for CI to validate multicore in simplest case, so we just use passthrough.

**Comment by kv2019i** [comment]
@RanderWang @aiChaoSONG @ranj063 It of course really depends what this tplg is supposed to do. It's a fair point from @aiChaoSONG  that if this is not aligned with the baseline cavs-nocodec, it's going to be harder and harder to maintain this when the baseline tplg is developed further.

**Comment by RanderWang** [comment]
> @RanderWang @aiChaoSONG @ranj063 It of course really depends what this tplg is supposed to do. It's a fair point from @aiChaoSONG that if this is not aligned with the baseline cavs-nocodec, it's going to be harder and harder to maintain this when the baseline tplg is developed further.

@kv2019i We don't need to align cavs-nocodec.tplg and cavs-nocodec-multicore.tplg. A simple and better method is to add core setting in cavs-nocodec.tplg then we can discard cavs-nocodec-multicore.tplg and avoid any more maintain effort.

The cavs-nocodec-multicore.tplg is a simple pass-through pipeline when we validated multicore feature at first. At that time we had many bugs include hw hang. Now we can drop it since everything is stable now. If we still want to keep cavs-nocodec-multicore.tplg for feature validation on LNL or later chip,  I will want to make it a simple pass-through one to make debug easier.

**Comment by RanderWang** [comment]
@kv2019i  In my opinion, developer should add core setting to the really used topology like hda or sdw topology, not the case that port some pipelines to cavs-nocodec-multicore.tplg and make it complex more and more.

**Comment by aiChaoSONG** [comment]
>We don't need to align cavs-nocodec.tplg and cavs-nocodec-multicore.tplg. 

@RanderWang we are aligning the behavior of PASSTHROUGH, it is designed to do one-key passthrough for all host->dai connections, not only for DMIC. it should behave the same in whatever topology conf.

**Comment by RanderWang** [comment]
> > We don't need to align cavs-nocodec.tplg and cavs-nocodec-multicore.tplg.
> 
> @RanderWang we are aligning the behavior of PASSTHROUGH, it is designed to do one-key passthrough for all host->dai connections, not only for DMIC. it should behave the same in whatever topology conf.

I don't want any PASSTHROUGH code in cavs-nocodec-multicore.tplg since It is designed to use pass-through pipeline.

**Comment by RanderWang** [comment]
I suggest two options: (1) add multicore setting in cavs-nocodec.conf and remove cavs-nocodec-multicore.conf
(2) make cavs-nocodec-multicore.conf simple and remove the added PASSTHROUGH code

**Comment by kv2019i** [comment]
Thanks @RanderWang and @aiChaoSONG . Rander's proposal seems good to me.

**Comment by RanderWang** [comment]
thanks!

**Pull request closed without merging**
