### PR TITLE
topology1: i.MX: Add topology with DRC component

### PR DESCRIPTION
**Pull request by iuliana-prodan**
Dynamic range compression (DRC) or simply compression is an
audio signal processing operation that reduces the volume of
loud sounds or amplifies quiet sounds, thus reducing or
compressing an audio signal's dynamic range.

This enables the DRC component for i.MX8QM/i.MX8QXP/i.MX8MP
with wm8960 codec.

Signed-off-by: Iuliana Prodan <iuliana.prodan@nxp.com>

### CODE REVIEW

**Review by paulstelian97 — APPROVED** [review]

**Review by paulstelian97 — CHANGES_REQUESTED** [review]
I don't see the .m4 files.

**Comment by iuliana-prodan** [comment]
> I don't see the .m4 files.

The .m4 files are here - https://github.com/thesofproject/sof/tree/main/tools/topology/topology1/m4 (one can use the default [drc_coef_default.m4](https://github.com/thesofproject/sof/blob/main/tools/topology/topology1/m4/drc_coef_default.m4)).

If somebody wants to generate other coefficients have to modify `params` in .m files [here](https://github.com/thesofproject/sof/tree/main/tools/tune/drc).
For example, when running [`example_drc.m`](https://github.com/thesofproject/sof/blob/main/tools/tune/drc/example_drc.m) you obtain new `drc_coef_default.m4`. Next, you'll need to compile the topologies and you get a new DRC topology with your custom coefficients.

So, there is no special .m4 file for DRC, for i.MX. One can custom his/hers using .m file.

**Comment by paulstelian97** [comment]
Oh, so there's a single sof-imx8-wm8960.m4 and -DPROC is used to select the processing component?

**Review by paulstelian97 — APPROVED** [review]

**Comment by iuliana-prodan** [comment]
> Oh, so there's a single sof-imx8-wm8960.m4 and -DPROC is used to select the processing component?

Yes, there's one for 8QM/QXP and one for 8MP. 
And we use `-DPROC` for component.

**Review by dbaluta — APPROVED** [review]

**Pull request merged**
