### PR TITLE
platform: mtk: fixup the wrong register definitions for mtk mt8188

### PR DESCRIPTION
**Pull request by tracy209**
Fixup the wrong register definition of Timer and
remove some unnecessary ones for mt8188.

### CODE REVIEW

**Comment by sofci** [comment]
Can one of the admins verify this patch?
> reply **test&nbsp;this&nbsp;please** to run this test once

**Comment by gkbldcig** [comment]
Can one of the admins verify this patch?

**Review by kv2019i — APPROVED** [review]

**Comment by lgirdwood** [comment]
test this please

**Comment by lgirdwood** [comment]
SOFCI TEST

**Review by lgirdwood — APPROVED** [review]

**Comment by kv2019i** [comment]
Ignoring the Intel checks and merging as this only touches vendor specific code.

**Pull request merged**
