### PR TITLE
memory: apl: extend system heap

### PR DESCRIPTION
**Pull request by tlauda**
Extends system heap for core 0 to match other platforms.
Needed as total size of objects allocated on system heap
constantly changes and causes out of memory during slave
core enablement.

Signed-off-by: Tomasz Lauda <tomasz.lauda@linux.intel.com>

### CODE REVIEW

**Comment by tlauda** [comment]
@mmaka1 Some structs are allocated for slave cores by master core before boot.

**Comment by mmaka1** [comment]
@tlauda Perhaps we want to make all these slave core data to be allocated from the slave core's heap in order to free them all when the slave core goes down as a future improvement? Freeing the slave core's sys heap by powering assigned memory bank(s) down would be possible on some platforms.

**Comment by lgirdwood** [comment]
@mmaka1 do you still approve or do you want slave core data change before merge ?

**Comment by tlauda** [comment]
@mmaka1 Sounds good. I will do it as the next improvement.

**Pull request merged**
