### PR TITLE
gitignore: remove autotools ignore files

### PR DESCRIPTION
**Pull request by lgirdwood**
Signed-off-by: Liam Girdwood <liam.r.girdwood@linux.intel.com>

### CODE REVIEW

**Comment by lgirdwood** [comment]
@jajanusz  Ok, sounds like you are in a better position to fix gitignore wrt CMake runtime files ?  Fwiw, there were some files outside the build dir that showed up with git.

I can send a subsequent PR to remove all the gitignore autotools files once CMake gitignore is merged. This sound OK ?

**Comment by jajanusz** [comment]
@lgirdwood 
Sounds good.

What files were there? AFAIK when you do out-of-source build the only files that will be added outside of builddir are `__pycache__` files (what can be disabled with cmdline args). Maybe they were files from autotools? - Also please note that tools/ folder has separate buildsystem that I didn't touch - I guess we want to remove autotools everywhere so I'll port tools/ buildsystem soon too.

**Comment by lgirdwood** [comment]
if you run git clean -f -d -x and then build for any target git gui will show some files in arch/.

**Comment by lgirdwood** [comment]
@jajanusz this looks good for after autotools remove for tools. Do you have an ETA for this ?

**Comment by jajanusz** [comment]
> @jajanusz this looks good for after autotools remove for tools. Do you have an ETA for this ?

I'll try to do it this week.

**Comment by jajanusz** [comment]
I guess it's not longer needed because of #899

**Pull request merged**
