### PR TITLE
xtensa: ADL-S defconfig

### PR DESCRIPTION
**Pull request by jajanusz**
Add default config for Alderlake-S platform.

Signed-off-by: Janusz Jankowski <janusz.jankowski@linux.intel.com>

### CODE REVIEW

**Comment by lgirdwood** [comment]
CI usual suspects.

**Comment by jajanusz** [comment]
> @jajanusz would you also be able to add a patch to include ADL in xtensa-buildall.sh. @xiulipan can you make sure we are building this for CI. Thanks

I'd like to have rimage upgraded first - I don't like the fact that for new prefix we have to add whole new machine definition to rimage.

For example for 'jsl' that is just 'icl' with different defconfig, there is new machine def (there are more cases like this). Rimage should just take *sign/composition schema* and decouple it from concrete machines and binary suffixes.

I don't want to add another definition to just have `sof-adls.ri` binary as output.

There is no need to have ADL-S in CI yet, as we haven't even got chance to test it on real HW so IDK if it works.

**Comment by lgirdwood** [comment]
@jajanusz ok, so are you suggesting rimage just takes the cavs version in the cmd line instead of platform name ? The kernel is expecting the platform in the naming.

**Comment by jajanusz** [comment]
> @jajanusz ok, so are you suggesting rimage just takes the cavs version in the cmd line instead of platform name ? The kernel is expecting the platform in the naming.

CAVS version is not enough, we need manifest version (we have now 1.5/1.8/2.5) + some configs (like ROM address).

Actually I can fix it on buildsystem side, cos I see rimage doesn't care about names that much and it uses it only to find machine definition. So we may keep using it like *sign like tgl, but output sof-adls*.
Anyway need to clean up redundancy in rimage, cos we have too many machine definitions, that were used only to have out binary named differently ...

**Comment by xiulipan** [comment]
@lgirdwood Like @jajanusz said, we do not have rimage support for cAVS 2.5 platforms. So no scripts support can be added here.

Aggreed with @jajanusz update for rimage. The name is not matter, the key is cAVS version. In rimage we have a table to bind cavs version with platform. But with cavs version options we can generate any platform name we would like with future update if we have enabled cAVS version.

**Pull request merged**
