### PR TITLE
pull-request.yml: fix typo in comment.

### PR DESCRIPTION
**Pull request by greg-intel**
A small typo, but irrelevant as this PR doesn't need to be merged.

### CODE REVIEW

**Comment by greg-intel** [comment]
SOFCI TEST

**Review by cujomalainey — APPROVED** [review]

**Comment by kv2019i** [comment]
Maybe mark with "DNM" (Do Not Merge) or something to indicate whether this needs to be reviewed or merged?

**Comment by cujomalainey** [comment]
I read the DNM statement as this is a "nit/nonfunctional"

**Comment by marc-hb** [comment]
Even a typo fix needs a better commit title than "update". "Fix typo in comment" is enough.

We had some very time-consuming issues with Jenkins last week and I suspect this was an indirect way to test Jenkins, @greg-intel confirm?

This should probably have been a Github draft.

**Review by lgirdwood — APPROVED** [review]

**Pull request merged**
