### PR TITLE
Mixer-based pipelines for APL and BYT

### PR DESCRIPTION
**Pull request by ranj063**
This PR does the following:
1. Modifies the BYT topology to pass the scheduling component for the media pipeline
2. Adds mixer based pipelines for APL nocodec and pcm512x topologies.

Todo: update more topologies to use the low latency pipeline

### CODE REVIEW

**Comment by tlauda** [comment]
@ranj063 BYT nocodec topology is failing.

**Comment by ranj063** [comment]
> @ranj063 BYT nocodec topology is failing.

@tlauda fixed it too but I still see the Intel CI failing and I cant seem to figure out whats wrong from the log

**Comment by tlauda** [comment]
@ranj063 It's server issue.
@zrombel Will fix it today.

**Comment by ranj063** [comment]
@keqiaozhang just a heads up that this is a big change for APL and BYT topologies.

**Comment by tlauda** [comment]
@juimonen Can you check if it fixes hw:0,1 on BYT?

**Pull request merged**
