### PR TITLE
Add 24bit msb support

### PR DESCRIPTION
**Pull request by RanderWang**
This patch was merged by https://github.com/thesofproject/sof/pull/7959  but revert by https://github.com/thesofproject/sof/pull/8089 for a internal CI issue. Now the CI issue has been resovled so add it again. please check issue https://github.com/thesofproject/sof/issues/8086 for detail

### CODE REVIEW

**Review by kv2019i — APPROVED** [review]
Thanks @RanderWang , let's see the CI results.

**Comment by kv2019i** [comment]
One system-PM fail in https://sof-ci.01.org/sofpr/PR8151/build12561/devicetest/index.html , rest is good.

Sparse fail in https://github.com/thesofproject/sof/actions/runs/6080655526/job/16494931901?pr=8151 and will be fixed in https://github.com/thesofproject/sof/pull/8147

Waiting for further reviews, we can then merge.

**Review by btian1 — APPROVED** [review]
please fix code style issue.

**Comment by kv2019i** [comment]
The checkpatch is about Kconfig documentation and this patch matches the other entries, so we can let this go.

Given this was already reviewed in https://github.com/thesofproject/sof/pull/7959 , I'm proceeding to merge this so we can get this into 2.7.

**Pull request merged**
