### PR TITLE
Testbench: Update for file component new()

### PR DESCRIPTION
**Pull request by singalsu**
This patch updates the IPC check, allocation and copy for new()
to similar as in normal SOF components. The previous code caused
pipeline_comp_params() in pipeline.c to get uninitialized data.

Signed-off-by: Seppo Ingalsuo <seppo.ingalsuo@linux.intel.com>

### CODE REVIEW

**Comment by ranj063** [comment]
@singalsu looks good. Just one comment unrelated to this PR. Can we please align the sys_comp_*_init() signature for the file component to align with others for consistency?

**Comment by singalsu** [comment]
@ranj063 Sure, good catch, I'll add it to this PR.

**Comment by singalsu** [comment]
@ranj063 I tried to do for file "DECLARE_COMPONENT(sys_comp_file_init);" but ran into problems. Since file is statically linked into testbench it causes sys_comp_file_init() to be executed first before testbench has even initialized SOF. With normal SOF components the same works in testbench because the load of dynamic libraries for components is done later.

The error appears as segfault. When at comp_register() function for file the &cd->list that's passed to list_item_prepend() is null. To make it work I guess the macro DECLARE_COMPONENT would need to be changed to handle initialization or alternatively move file component into a dynamic library. However since testbench still works can we just leave it as is?

**Comment by jajanusz** [comment]
@ranj063 @singalsu is mostly right. It's designed to work with dlopen, because DECLARE_COMPONENT adds initializing function to constructors section. What means it's going to be executed on dlopen or in case of shared/static libs perma linked with linker flags - run before main function. What will fail because these comps touch global variables (spinlocks etc) that are set up later.

To make it work at any time we would have make registration mechanism for adding functions that are executed later but I thought it's not worth the effort atm, because I'm going to refactor host probably this week.

**Pull request merged**
