### PR TITLE
Revert "topology: hdmi-generic: change HDMI PCM id"

### PR DESCRIPTION
**Pull request by lgirdwood**
Reverts thesofproject/sof#6787

### CODE REVIEW

**Comment by marc-hb** [comment]
Should fix regression #6787

Devices unfortunately not available in https://sof-ci.01.org/sofpr/PR6953/build3368/devicetest/index.html, restarting hardware testing

**Comment by marc-hb** [comment]
SOFCI TEST

**Comment by marc-hb** [comment]
Lots of devices missing again in https://sof-ci.01.org/sofpr/PR6953/build3370/devicetest/index.html again, this is starting to look suspicious... @greg-intel , @fredoh9 ?

**Comment by marc-hb** [comment]
SOFCI TEST

**Comment by greg-intel** [comment]
@marc-hb I saw three instances of "ERROR: Failed to retrieve Topology resource from..." for testplan 19889

**Comment by marc-hb** [comment]
So https://sof-ci.01.org/sofpr/PR6953/build3371/devicetest/index.html is mostly empty again

As mentioned by Greg, job/testflow/61036 tries to download `tplg/topology2/avs-tplg/sof-adl-rt711-4ch.tplg` but it's NOT in the  `sof/PR6953-3370/build3370/tplg/topology2/avs-tplg/ folder` in storage.

**Review by marc-hb — APPROVED** [review]
Just to be on the safe side I fetched this and made sure it reverts #6787 exactly. So from that perspective: approved.

Obviously can't be merged as long as all tests are failing.

**Comment by marc-hb** [comment]
I built both/after this revert and yes the revert does remove `topology/topology2/avs-tplg/sof-adl-rt711-4ch.tplg`. So there's likely a "revert" required on the CI side too.

**Comment by bardliao** [comment]
https://github.com/thesofproject/sof/pull/6946 will fix https://github.com/thesofproject/sof/issues/6947 and https://github.com/thesofproject/sof/pull/6957 will fix the topology issue on ADL RVP. There is no need to revert https://github.com/thesofproject/sof/pull/6787

**Pull request closed without merging**
