### PR TITLE
app: boards: imx93: updates for zephyr hwmv2

### PR DESCRIPTION
**Pull request by iuliana-prodan**
Update config and overlay for hwmv2.
Also, update SOC config based on changes made in
Zephyr for hwmv2.

### CODE REVIEW

**Review by marc-hb — CHANGES_REQUESTED** [review]
Looks good but @kv2019i this should be added to #8913 (or whichever updates sof/west.yml first)

Everything should be in the same commit to avoid intermediate, broken states.

**Comment by marc-hb** [comment]
> Looks good but @kv2019i this should be added to https://github.com/thesofproject/sof/pull/8913 (or whichever updates sof/west.yml first)

Done and passing in https://github.com/thesofproject/sof/actions/runs/8193558383/job/22407570268?pr=8913
@kv2019i was 15 minutes ahead of me.

**Review by lgirdwood — APPROVED** [review]
@kv2019i @iuliana-prodan are all dependencies now merged ?

**Comment by dbaluta** [comment]
Closing this as it was squashed into https://github.com/thesofproject/sof/pull/8913/commits

**Pull request closed without merging**
