### PR TITLE
[SKIP SOF-TEST] fuzz.sh: add -jobs parameter. Switch to built-in -max_total_time.

### PR DESCRIPTION
**Pull request by marc-hb**
There was no need to use the external "timeout" command + some complicated exit code logic, libFuzzer has that feature built-in. Switch to it and delete a few good line.

Add an option to use the built-in, concurrent -jobs feature which saves a massive amount of time. It has some quirks so do not enable it by default.

Decrease verbosity by default.

Add in the help message the magic replay command that saves a ton of time.

cc:
- #8832
- https://github.com/zephyrproject-rtos/zephyr/pull/68494
- #8886

### CODE REVIEW

**Comment by marc-hb** [comment]
Outputs in https://github.com/thesofproject/sof/actions/runs/7851518795/job/21428707809?pr=8851 look great.

**Comment by marc-hb** [comment]
Brand new failure in https://github.com/thesofproject/sof/actions/runs/7868973600/job/21467150473?pr=8851? Demoting to draft for now.

**Comment by cujomalainey** [comment]
> Brand new failure in https://github.com/thesofproject/sof/actions/runs/7868973600/job/21467150473?pr=8851? Demoting to draft for now.

@andyross is that another panic being masked?

**Comment by marc-hb** [comment]
> @andyross is that another panic being masked?

No I think it was just the original #8832 that was not fixed yet at the time and very poorly reported.

Reporting fixed in brand new #8886  just submitted, please review. Magnificient stack trace there!

Promoting this -j PR to "ready" too.

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
@marc-hb are all the dependencies in the PR message now met ?

**Comment by marc-hb** [comment]
I did submit a few PRs to make debugging fuzzing issues significantly easier and faster but they are all independent of each other and can be merged in any order. This can be merged.


When there are dependencies between commits I either put them in the same PR or if too big then I hold back depending PRs as a draft.

**Pull request merged**
