### PR TITLE
Tools: Topology1: Add IIR and IIR+FIR HDA generic playback topologies

### PR DESCRIPTION
**Pull request by singalsu**
This patch removes non-practical sof-hda-generic-loud topologies and generates instead IIR and IIR+FIR topologies for headphone/speaker path for no-DMIC/2ch-DMIC/4ch-DMIC platforms. The IIR and FIR are by default programmed for pass-through without any processing.

sof-hda-generic-iir.tplg
sof-hda-generic-iir-2ch.tplg
sof-hda-generic-iir-4ch.tplg
sof-hda-generic-iir-fir.tplg
sof-hda-generic-iir-fir-2ch.tplg
sof-hda-generic-iir-fir-4ch.tplg

The custom topologies can be used e.g. copying them to /lib/firmware/intel/sof-tplg-custom/ and by adding to /etc/modprobe.d/sof.conf the following lines with desired configuration un-commmented.

#options snd_sof_pci tplg_filename="sof-hda-generic-iir.tplg" tplg_path="intel/sof-tplg-custom"
#options snd_sof_pci tplg_filename="sof-hda-generic-iir-fir.tplg" tplg_path="intel/sof-tplg-custom"
#options snd_sof_pci tplg_filename="sof-hda-generic-iir-2ch.tplg" tplg_path="intel/sof-tplg-custom"
#options snd_sof_pci tplg_filename="sof-hda-generic-iir-fir-2ch.tplg" tplg_path="intel/sof-tplg-custom"
#options snd_sof_pci tplg_filename="sof-hda-generic-iir-4ch.tplg" tplg_path="intel/sof-tplg-custom"
#options snd_sof_pci tplg_filename="sof-hda-generic-iir-fir-4ch.tplg" tplg_path="intel/sof-tplg-custom"

The patch contains a fix for pipeline with FIR to undefine the related macros to avoid them to possibly impact another FIR instance.

### CODE REVIEW

**Comment by keqiaozhang** [comment]
SOFCI TEST

**Comment by singalsu** [comment]
> @singalsu do we need to be working on topology1 development topologies ? Should we be using topology2 for dev work ?

This is for SOFv2.2 signed firmware users to enable equalizers in their notebook. I should make a PR for 2.2 branch too (or only there). Should I close this for main?

**Comment by lgirdwood** [comment]
> > @singalsu do we need to be working on topology1 development topologies ? Should we be using topology2 for dev work ?
> 
> This is for SOFv2.2 signed firmware users to enable equalizers in their notebook. I should make a PR for 2.2 branch too (or only there). Should I close this for main?

no, we can merge here since its ready, also cherry-pick to v2.2 and of course topology 2 version.

**Comment by singalsu** [comment]
> > > @singalsu do we need to be working on topology1 development topologies ? Should we be using topology2 for dev work ?
> > 
> > 
> > This is for SOFv2.2 signed firmware users to enable equalizers in their notebook. I should make a PR for 2.2 branch too (or only there). Should I close this for main?
> 
> no, we can merge here since its ready, also cherry-pick to v2.2 and of course topology 2 version.

Good! There's in topology2 similar sof-hda-efx-generic-Xch.tplg set that is even better with with the added DRC. I will add to it some customization to it to build variants for various needs.

**Review by kv2019i — APPROVED** [review]

**Pull request merged**
