### PR TITLE
Sparse: draft - all commits on top of Zephyr base sparse implementation

### PR DESCRIPTION
**Pull request by lyakh**
Testing to see if enabling `CONFIG_INCOHERENT` still fails tests
Update: using this now for a full set of `__cache` sparse annotation patches, that can be enabled by using https://github.com/zephyrproject-rtos/zephyr/pull/43776

### CODE REVIEW

**Comment by lgirdwood** [comment]
@lyakh can you split this into global sparse definitions and then subsystem by subsystem changes. Lets get the basics in first

**Comment by lyakh** [comment]
> @lyakh can you split this into global sparse definitions and then subsystem by subsystem changes. Lets get the basics in first

@lgirdwood sure, we can use #5324 for the first lot then

**Comment by lyakh** [comment]
This version now actually works, which means, that when `CONFIG_INCOHERENT` is enabled per https://github.com/thesofproject/sof/pull/5312/commits/00f9311372607b9b940f74dac9d9b6d7de2ff4a0 at least playback and capture still work.

**Comment by lgirdwood** [comment]
> This version now actually works, which means, that when `CONFIG_INCOHERENT` is enabled per [00f9311](https://github.com/thesofproject/sof/commit/00f9311372607b9b940f74dac9d9b6d7de2ff4a0) at least playback and capture still work.

ok, so what are we depending on to merge in Zephyr ?
We can then align our definitions and then merge this PR.

**Comment by lyakh** [comment]
> > This version now actually works, which means, that when `CONFIG_INCOHERENT` is enabled per [00f9311](https://github.com/thesofproject/sof/commit/00f9311372607b9b940f74dac9d9b6d7de2ff4a0) at least playback and capture still work.
> 
> ok, so what are we depending on to merge in Zephyr ? We can then align our definitions and then merge this PR.

@lgirdwood first of all we depend on https://github.com/zephyrproject-rtos/zephyr/pull/43776 Once that's merged we need one more patch / PR for Zephyr to add the `__cache` annotation. After that we can begin merging ours. But you requested to split this PR and its first part is now available as #5324 When we have merged all that, we can rebase, split and merge the rest - i.e. everything from this set

**Comment by lyakh** [comment]
> > > This version now actually works, which means, that when `CONFIG_INCOHERENT` is enabled per [00f9311](https://github.com/thesofproject/sof/commit/00f9311372607b9b940f74dac9d9b6d7de2ff4a0) at least playback and capture still work.
> > 
> > 
> > ok, so what are we depending on to merge in Zephyr ? We can then align our definitions and then merge this PR.
> 
> @lgirdwood first of all we depend on [zephyrproject-rtos/zephyr#43776](https://github.com/zephyrproject-rtos/zephyr/pull/43776) Once that's merged we need one more patch / PR for Zephyr to add the `__cache` annotation. After that we can begin merging ours. But you requested to split this PR and its first part is now available as #5324 When we have merged all that, we can rebase, split and merge the rest - i.e. everything from this set

Now that https://github.com/zephyrproject-rtos/zephyr/pull/43776 got merged, we only need https://github.com/zephyrproject-rtos/zephyr/pull/45225 and then we can start merging SOF sparse patches

**Comment by lgirdwood** [comment]
@marc-hb @wszypelt @marcinszkudlinski @mwasko - heads up, we will soon have sparse support upstream and should plan to include this as a build time test within CI as an extra layer of PR correctness/validation.

**Comment by lyakh** [comment]
all commits either already merged or in the last push on the way to be merged

**Pull request closed without merging**
