### PR TITLE
[RFC] Enable building SOF with Zephyr for arbitrary architectures

### PR DESCRIPTION
**Pull request by lyakh**
This PR together with https://github.com/andyross/zephyr/pull/4 makes it possible to build Zephyr with SOF for any architecture

### CODE REVIEW

**Review by lgirdwood — CHANGES_REQUESTED** [review]
Can you send this to master first. This will make it into v1.7

**Comment by lyakh** [comment]
> Can you send this to master first. This will make it into v1.7

@lrgirdwo sure, I just wanted to get some opinions about this first. Are we ok with this approach - using `CONFIG_LIBRARY` for such builds?

**Comment by lgirdwood** [comment]
I think this should be fine for the moment.

**Comment by lyakh** [comment]
closing this in favour of #3591

**Pull request closed without merging**
