### PR TITLE
scripts: replace alsa-lib with sof mirror

### PR DESCRIPTION
**Pull request by xiulipan**
Use local version that still in review stage that we can have test
before final merge in upstream.

Signed-off-by: Pan Xiuli <xiuli.pan@linux.intel.com>

### CODE REVIEW

**Comment by plbossart** [comment]
@xiulipan it would be good to add precisions on what exactly this alsa-lib "mirror" is and who maintains it? If it's just a mirror there is no real point in this. If it's intended to test alsa-lib patches before they are contributed upstream, then we need a maintainer and a clear understanding on how this repository tracks upstream.

**Comment by xiulipan** [comment]
@lgirdwood 
Would you answer @plbossart's problem? I just make some switch and did not know more context here.

**Comment by lgirdwood** [comment]
@plbossart we now have non upstream fixes in topology compiler for keyword detect widgets. These will be upstreamed when fully tested.

**Comment by plbossart** [comment]
On 1/31/19 2:21 PM, Liam Girdwood wrote:
>
> @plbossart <https://github.com/plbossart> we now have non upstream 
> fixes in topology compiler for keyword detect widgets. These will be 
> upstreamed when fully tested.
>
ok, but then you maintain this repo, right?
>

**Comment by lgirdwood** [comment]
Yes.

**Pull request merged**
