### PR TITLE
topology2: Add support for cs42l43 SKU with four host DMICs

### PR DESCRIPTION
**Pull request by simontrimmer**
Add support for another Lenovo SKU that uses cs42l43 and four host side DMICs rather than the CODECs DMICs.

### CODE REVIEW

**Comment by lgirdwood** [comment]
@bardliao pls review.

**Comment by bardliao** [comment]
The main question is that is the SoundWire DMIC used or not. If not, we need to add a quirk in the machine driver. Like [Remove CODEC DMIC for specific SKUs by charleskeepax · Pull Request #5186 · thesofproject/linux](https://github.com/thesofproject/linux/pull/5186/commits/80d019ad26e5b7c8664f50b99516e027d62b7500) And, 'SDW_DMIC_STREAM=Capture-SmartMic' is not needed in that case.
If the SoundWire DMIC and the host DMIC coexist, we need to add `SDW_DMIC=1`

**Comment by simontrimmer** [comment]
@charleskeepax  - I've been having some fun with this today, I'll bother you about it more tomorrow

**Comment by simontrimmer** [comment]
Hey @bardliao 
> The main question is that is the SoundWire DMIC used or not. If not, we need to add a quirk in the machine driver. Like [Remove CODEC DMIC for specific SKUs by charleskeepax · Pull Request #5186 · thesofproject/linux](https://github.com/thesofproject/linux/pull/5186/commits/80d019ad26e5b7c8664f50b99516e027d62b7500) And, 'SDW_DMIC_STREAM=Capture-SmartMic' is not needed in that case. If the SoundWire DMIC and the host DMIC coexist, we need to add `SDW_DMIC=1`

I'm pretty certain that we don't have the SoundWire DMIC so will be adding the SOC_SDW_CODEC_MIC quirk when updating the sof_sdw_quirk_table

**Review by lgirdwood — APPROVED** [review]
@bardliao pl review.

**Review by bardliao — APPROVED** [review]

**Pull request merged**
