### PR TITLE
ipc4: mixin: Restore back gain support

### PR DESCRIPTION
**Pull request by serhiy-katsyuba-intel**
Restore back gain support which was accidentally removed during previous HIFI optimization/refactoring.

This PR implements gain for "generic" and "HIFI3" mixin versions. Implementation for "HIFI5" version is a TODO.

### CODE REVIEW

**Comment by serhiy-katsyuba-intel** [comment]
Separate draft PR tests "generic" impl https://github.com/thesofproject/sof/pull/9039 and "HIFI3" impl https://github.com/thesofproject/sof/pull/9040.

**Review by lgirdwood — COMMENTED** [review]
@singalsu pls review
@serhiy-katsyuba-intel I have a suspicion that some of the gains may have been removed to improve MCPS as they were always 0dB.  It probably makes sense to do the gain only if gain != 0dB to save the MCPS since mixin/mixout are used in lots of places. This may be best performed with a ```mix_s16()``` and a ```mix_s16_gain()``` and we decide which to use at ```process()``` time.

**Comment by serhiy-katsyuba-intel** [comment]
@lgirdwood , if we choose to have separate mix_s16() and mix_s16_gain() we'll have to maintain 6 functions instead of 3. I though applying gain to mixin sources might be quite popular use case as without it there is a chance for saturation and so "gain feature" should be used almost always. Do we have any assumptions how typical is using "gain feature" when mixing? If it is not needed most of the time -- I can redo to have separate mix_sXX() and mix_sXX_gain() versions.

**Comment by lgirdwood** [comment]
> @lgirdwood , if we choose to have separate mix_s16() and mix_s16_gain() we'll have to maintain 6 functions instead of 3. I though applying gain to mixin sources might be quite popular use case as without it there is a chance for saturation and so "gain feature" should be used almost always. Do we have any assumptions how typical is using "gain feature" when mixing? If it is not needed most of the time -- I can redo to have separate mix_sXX() and mix_sXX_gain() versions.

@singalsu can you comment here on usage.

@serhiy-katsyuba-intel I know its 6 funcs, but its not really 6 different funcs, they will be the same in pairs except for the gain block (and this could be explained in the comment blocks). e.g. duplication of ```mix_s16()``` for MCPS reasons.

**Comment by abonislawski** [comment]
If there are many use cases without gain then its better to separate them.

@lgirdwood @singalsu is someone able to do this also for HiFi5 files?

**Review by kv2019i — COMMENTED** [review]
Interesting. Digging into this, the gain support was added with remapping support with
commit 9fc0badb4d7cd55f743568784bfb9ad85f2a5ff8 ("ipc4: add mixin/mixout channel remapping support"). This had special casing was IPC4_MIXIN_UNITY_GAIN. Then when remapping feature was removed, applying gain was removed as well.

The Linux driver and topologies are not using non-unity gains (there is assumption these are only used in remapping mode, but I guess that's the wrong assumption).

**Comment by serhiy-katsyuba-intel** [comment]
> The Linux driver and topologies are not using non-unity gains (there is assumption these are only used in remapping mode, but I guess that's the wrong assumption).

Thank you. So I will re-do to have separate mixing function implementations: with and without gain.

**Pull request closed without merging**
