### PR TITLE
zephyr: kconfig: rename CONFIG_SMP -> CONFIG_MULTICORE

### PR DESCRIPTION
**Pull request by lgirdwood**
This kconfig collides with one of the same name in Zephyr.  Rename it
for clarity ("MULTICORE" was picked for symmetry with the existing
"CORE_COUNT", though it's admittedly a little long...).

Signed-off-by: Andy Ross <andrew.j.ross@intel.com>

### CODE REVIEW

**Comment by dbaluta** [comment]
@lgirdwood but then what's the difference between CONFIG_SMP / CONFIG_MULTICORE. No objection about the PR, but want to understand better the issue.

**Comment by lgirdwood** [comment]
@dbaluta The meaning is exactly the same. it's to align the Kconfig menu and config files. i.e we can build the SOF Kconfig as submenu under Zephyr kconfig and share the same .config file.

**Comment by dbaluta** [comment]
@lgirdwood I see. So we can build Zephyr with CONFIG_SMP=y and then SOF with CONFIG_MULTICORE=n

**Comment by lgirdwood** [comment]
@zrombel can we rerun CI on Monday - I'm not seeing any logs and I guess it's due to the maintenance.

**Comment by zrombel** [comment]
I was updating QB and made this PR fail. Rebuild already scheduled.

**Comment by lgirdwood** [comment]
CI unrelated failures on UP systems.

**Pull request merged**
