### PR TITLE
CI testing for v1.6.1 patches.

### PR DESCRIPTION
**Pull request by lgirdwood**
Pending patches for v1.6.1 for CI testing.
@lyakh anything pending for Zephyr in v1.6 stable ?

### CODE REVIEW

**Comment by lyakh** [comment]
> @lyakh anything pending for Zephyr in v1.6 stable ?

@lgirdwood you mean whether any of these patches are relevant tor Zephyr? Obviously the last one, eventually two more for generic compilation
- pcm_converter: fix type mismatch
- kpb: fix logging cast issue

maybe also
- cavs: power_down: move IPC_HOST_BASE literal into register
- apl: power_down: move IPC_HOST_BASE literal into register

**Comment by lgirdwood** [comment]
@lyakh sorry - I mean am I missing any other PRs needed fro Zephyr ?

**Comment by lgirdwood** [comment]
CI showing APL no codec DUT failed to boot.

**Comment by lyakh** [comment]
> @lyakh sorry - I mean am I missing any other PRs needed fro Zephyr ?

@lgirdwood I tried this branch with https://github.com/zephyrproject-rtos/zephyr/pull/29952, I needed https://github.com/thesofproject/sof/pull/3544/commits/b86a6122b6ac47ad43ec12a2669c259e83f85007 in SOF and I had to cherry-pick one more commit (updating for a new rimage version and integrating extended metadata) and fix a defconfig import. After that it worked. So, don't know what your approach to https://github.com/thesofproject/sof/pull/3544/commits/b86a6122b6ac47ad43ec12a2669c259e83f85007 would be, I guess since we have it in "master" we should also pull it here. Otherwise I haven't found anything for SOF + Zephyr on UP2

**Pull request merged**
