### PR TITLE
topology: tgl-nocodec-ci: add multicore support

### PR DESCRIPTION
**Pull request by keyonjie**
Generate sof-tgl-nocodec-ci-multicore.tplg for multicore validation
coverage.

Signed-off-by: Keyon Jie <yang.jie@linux.intel.com>

### CODE REVIEW

**Comment by keyonjie** [comment]
Hi all, we still want to provide possibility to run CI with multi-core configured, this is aim for that, e.g. run mainline kernel (without dynamic pipeline implementation) with multi-core support.

**Comment by lgirdwood** [comment]
@keyonjie whats the difference between this and #4075 ?

**Comment by keyonjie** [comment]
> @keyonjie whats the difference between this and #4075 ?

This will generate 2 different .tplg, keep default one unchanged (core 0) but we can use -multicore.tplg (core1) for validation when needed, while the #4705 only generate the default core0 one.

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
@keyonjie thanks got you.
@plbossart @kv2019i good for the kernel ?

**Comment by plbossart** [comment]
> @keyonjie thanks got you.
> @plbossart @kv2019i good for the kernel ?

This solution will force CI to have rules on which files they use for validation, and override the same file for different purposes.
That doesn't seem to be a very good practice, e.g. to provide test reports.

**Comment by marc-hb** [comment]
@plbossart could you please elaborate? AFAICT this PR only adds the generation of a new `.tplg` file for multicore, so how this file will be used by CI and how validation will present test reports is still completely open, isn't it? I mean @keyonjie gave some ideas you don't seem to like but these ideas are independent from this PR, correct?

In an ideal world, where and how would you like multicore to be configured and tested? Should single and multicore tested and presented both in the same test report?

**Comment by plbossart** [comment]
@marc-hb the kernel only knows about sof-tgl-nocodec.tplg. If you have two or more topology files that need to be expose with the same name, be it through symlinks or file override, then it becomes difficult to know what you are testing.

**Comment by marc-hb** [comment]
I understand confusion will happen but what are the alternatives? Are you suggesting to never validate single and multicore with the same git version, not even for some transition period?

**Comment by plbossart** [comment]
@marc-hb I don't see the point of testing single-core configurations indeed. This is a transition period, and it's not clear what's breaking. Once we have the multi-core configuration working for CI purposes, why would we test the single-core version?

I think there is really a confusion of what CI is. The purpose is to catch regressions on working configurations. There seems to be a confusion with WIP configurations aiming at fixing bugs. This is not a CI activity but a developer/debug one.

Different problems really.

**Comment by keyonjie** [comment]
OK @plbossart @marc-hb @lgirdwood To avoid back and forth, let me close this and roll back to the version of https://github.com/thesofproject/sof/pull/4028 as the multi-core will be supported soon after the simple fix from https://github.com/thesofproject/linux/pull/2873 get merged.

**Pull request closed without merging**
