### PR TITLE
ipc: dai: remove unused hdr field in params

### PR DESCRIPTION
**Pull request by plbossart**
We don't use this field, move back to reserved.

Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>

### CODE REVIEW

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by lgirdwood** [comment]
Rerun CI with latest CI fixes.

**Comment by plbossart** [comment]
> Given the CI results I'm thinking this is being used somewhere via pointer arithmetic and a cast ?

well duh, the unused header is just a single u32, not an array of 2 as I was told before...

**Comment by lgirdwood** [comment]
So it is, the naming is very similar for both headers. Not sure why it's flagging up on internal CI fir WHL though so lets rerun.

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
CI tests are ok, and checkpatch.pl errors are 'normal'. Anything you need from me @lgirdwood

**Pull request merged**
