### PR TITLE
Fix sparse build by using our own sparse branch

### PR DESCRIPTION
**Pull request by marc-hb**
Use our own sparse branch, we cannot wait for critical sparse fixes like @lyakh's
`xtensa: switch to little endianness` https://marc.info/?l=linux-sparse&m=166861736724543
and others to be merged

### CODE REVIEW

**Comment by marc-hb** [comment]
https://github.com/thesofproject/sof/actions/runs/3519164757/jobs/5898822295 is passing for TGL and showing `different address space` errors for MTL. Both show the complete log.

**Review by lyakh — APPROVED** [review]
looks good, thanks @marc-hb . Just one idea: would it be better to use the sparse fork from thesofproject directly? We could make a branch there for our waiting-to-be-merged patches. Although I don't expect many of them, after merging this one. Would we switch back to upstream sparse after this patch is merged?

**Review by lgirdwood — APPROVED** [review]

**Comment by marc-hb** [comment]
> Just one idea: would it be better to use the sparse fork from thesofproject directly?

Absolutely yes, in fact I wrote a `TODO` in the `sparse-zephyr.yml` file about that. But first can you help update the https://github.com/thesofproject/sparse main branch with what you know we need?

**Comment by marc-hb** [comment]
> Would we switch back to upstream sparse after this patch is merged?

Any switch is possible and easy in the future. Note both https://github.com/lucvoo/sparse and the version in the `zephyr-build` image usually lag behind https://git.kernel.org/pub/scm/devel/sparse/sparse.git

cc: @stephanosio, @tejlmand

**Comment by marc-hb** [comment]
https://github.com/thesofproject/sparse does not have ANY patch right now because I'm not sure how we should manage it. So it can't be used yet. Are force-pushes to the main branch OK? Probably not, maybe we should use a non-default branch.

**Pull request merged**
