### PR TITLE
codec_adpater: fix stray errors

### PR DESCRIPTION
**Pull request by CyKuei**
Fixed by removing invalid characters.
Signed-off-by: CY Kuei <cyk@waves.com>

### CODE REVIEW

**Comment by sofci** [comment]
Can one of the admins verify this patch?
> reply **test&nbsp;this&nbsp;please** to run this test once

**Comment by gkbldcig** [comment]
Can one of the admins verify this patch?

**Comment by dbaluta** [comment]
It looks like PR description contains more information that actual commit message. Can you please fix this. 

Also, what's the deal with stray characters? Did this made the compilation fail. Please make the  commit message more clear.

**Comment by lgirdwood** [comment]
please test this

**Comment by lgirdwood** [comment]
SOFCI TEST

**Review by lgirdwood — COMMENTED** [review]
@CyKuei can you upstream this in main first then we can cherry-pick to adl-004 branch. Thanks.

**Comment by CyKuei** [comment]
@lgirdwood The main branch does not have this issue. I think it's because I copied the changes from the main branch to the adl-004-drop-stable branch via the Windows system.

**Comment by lgirdwood** [comment]
> @lgirdwood The main branch does not have this issue. I think it's because I copied the changes from the main branch to the adl-004-drop-stable branch via the Windows system.

ok, got you.  The best flow for this is to use the ```git cherry-pick``` command as this will directly copy the commit. i.e. it cant be opened in an editor (and have spaces/tabs or CR/LF changes made).

**Review by lgirdwood — COMMENTED** [review]
@CyKuei can you paste the build error in the commit message to show what the PR fixes.
@mwasko fyi - it seems some non printable control characters were inserted which breaks build for adl-004

**Comment by CyKuei** [comment]
The build error is now in the commit message.

**Review by dbaluta — APPROVED** [review]

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
@mwasko fyi - merging as build fix.

**Pull request merged**
