### PR TITLE
add dmic probe for apl and cnl

### PR DESCRIPTION
**Pull request by xiulipan**
apl and cnl have 2 dmic dai but only probe 1.
Probe all these 2 dmic dais.

### CODE REVIEW

**Comment by plbossart** [comment]
Maybe I am mistaken, but I remember Seppo mentioning 4mics worked before this PR - was this with a similar change? @singalsu, can you comment?

**Comment by lgirdwood** [comment]
@singalsu are you approving ?

**Comment by singalsu** [comment]
I need to test this first.

**Comment by xiulipan** [comment]
@lgirdwood @singalsu I asked seppo about this dmic[1] and it seems we need more work done before it could work. We may kept it not probe before we finish the work.

**Pull request closed without merging**
