### PR TITLE
xtensa-build-zephyr.py: resolve relative --key arguments

### PR DESCRIPTION
**Pull request by marc-hb**
2 commits, please review separately. Main commit:

`xtensa-build-zephyr.py: resolve relative --key arguments`

Fixes commit https://github.com/thesofproject/sof/commit/a769d3941d81f6d487e1a2bb6c3f99a193ebdcae ("xtensa-build-zephyr.py: stop calling west
sign, rely on west build")

Before that commit, `xtensa-build-zephyr.py` used to invoke `west sign`
directly and in the same current directory. This allowed relative key
paths to just work. Now that `west sign` is indirectly invoked by `west
build`, there is no possible way to make relative key paths work. So we
must resolve them before using them.

Fixes https://github.com/thesofproject/sof/issues/7718

### CODE REVIEW

**Comment by marc-hb** [comment]
1 suspend/resume timeout in MTL https://sof-ci.01.org/sofpr/PR7721/build8784/devicetest/index.html
1 suspend/resume timeout in cavs25
https://sof-ci.01.org/sofpr/PR7721/build8785/devicetest/index.html

Everything else green.

**Review by aiChaoSONG — APPROVED** [review]
Changes looks good

**Review by juimonen — APPROVED** [review]

**Review by aborisovich — APPROVED** [review]
Tested PR, fixes #7718.
Thanks @marc-hb for the quick correction.

**Comment by kv2019i** [comment]
Good to go, but need to have the mandatory CI checks to pass.

**Review by softwarecki — APPROVED** [review]

**Comment by marc-hb** [comment]
> Good to go, but need to have the mandatory CI checks to pass.

I spent time looking at all the (rare and isolated) test failures, none is related. See summary above. This is a pure build script change.

**Review by abonislawski — APPROVED** [review]

**Comment by lgirdwood** [comment]
@lrudyX @wszypelt pls confirm if we are good to merge. Thanks.

**Comment by marc-hb** [comment]
I did an empty `git commit --amend -C HEAD` + force push and now EVERYTHING is unbelievably green, including https://sof-ci.01.org/sof-pr-viewer/#/build/PR7721/build12109911, https://sof-ci.01.org/sofpr/PR7721/build8840/devicetest and https://sof-ci.01.org/sofpr/PR7721/build8841/devicetest

It's so green that it is actually suspicious so I opened all these links and the logs look fine.

**Pull request merged**
