### PR TITLE
[REBASE] [TGL] KWD: performance improvements

### PR DESCRIPTION
**Pull request by slawblauciak**
Rebased version of https://github.com/thesofproject/sof/pull/3186

### CODE REVIEW

**Comment by slawblauciak** [comment]
@lgirdwood this is the rebased PR as you requested

**Comment by mrajwa** [comment]
Why separate PR? https://github.com/thesofproject/sof/pull/3186 should be rebased right?

**Comment by slawblauciak** [comment]
@mrajwa I can't update your PR

**Comment by mrajwa** [comment]
@slawblauciak  ohh ok, I have rebased the original PR a minute ago.

**Pull request closed without merging**
