### PR TITLE
memory: changed memcpy_s error handling

### PR DESCRIPTION
**Pull request by dabekjakub**
Failing to copy will now result in FW panic

Signed-off-by: Jakub Dabek <jakub.dabek@intel.com>

### CODE REVIEW

**Comment by lgirdwood** [comment]
@mmaka1 I assume you now approve ?

**Comment by tlauda** [comment]
@zrombel Could we rerun CodeCheck?
@dabekjakub I think you are using the wrong email?

**Comment by lgirdwood** [comment]
@mengdonglin jenkins CI pending for ages, can someone reset it for this PR.

**Comment by tlauda** [comment]
SOFCI TEST

**Comment by xiulipan** [comment]
@lgirdwood 
Sometimes the RSET API for GitHub just got some 40X behind proxy :( Maybe need some rerun method for this also

**Pull request merged**
