### PR TITLE
topology2: hdmi-default: shift pipeline id

### PR DESCRIPTION
**Pull request by bardliao**
The max number of pipelines is 24 for some platforms.

Signed-off-by: Bard Liao <yung-chuan.liao@linux.intel.com>

### CODE REVIEW

**Review by lgirdwood — APPROVED** [review]
@bardliao I think the platforms with less memory have this pipeline count limitation, but this should probably be a Kconfig.

**Comment by bardliao** [comment]
> @bardliao can you show in FW where this is a hard limit, I do remember having this a long time ago for BYT, but we could remove ?

This is from the closed source FW. I am not sure if I can share in public.

**Comment by bardliao** [comment]
> > > @bardliao I don't think this is the right solution to fix the problem. The pipeline ID's coming from topology should only be a guideline to associate widgets that are part of the same pipeline. The actual pipeline ID that is assigned in the FW should be generated in the kernel using the same method we use for assigning module ID's for example. @plbossart what do you think?
> > 
> > 
> > Good question @ranj063. this is a difficult one. The problem is that the pipeline ID is used to create control names, so that creates a user-space ABI and needs to be constant or tracked between generations. Having the pipeline ID generated with an IDA or something would create a mess or a need for a mapping table, wouldn't it?
> 
> @plbossart controls names are assigned based on the topology pipeline ID's but they are not assiciated with pipeline ID's in the FW but rather with the widget that it is attached to. I'm don't think that the mismatch between the pipeline ID in topology and the FW would cause any problems. But yes, there would a way to map the 2 in the kernel but I do not think we need a table at all. A pipeline widget will have 2 pipeline ID's, one assigned in the firmware and the one set in topology and we can look up one or the other from the widget's structure

I sounds doable. Let me work on it and see what problem will I meet.

**Comment by bardliao** [comment]
@plbossart @ranj063 I tried to use ida to assign pipeline's instance id on kernel side and confirmed that is doable. I will create a PR for it. So close this one.

**Pull request closed without merging**
