### PR TITLE
logger: use more specific format specifiers

### PR DESCRIPTION
**Pull request by Johnnynator**
related to #4902

### CODE REVIEW

**Comment by sofci** [comment]
Can one of the admins verify this patch?
> reply **test&nbsp;this&nbsp;please** to run this test once

**Comment by gkbldcig** [comment]
Can one of the admins verify this patch?

**Comment by lyakh** [comment]
test this please

**Comment by lgirdwood** [comment]
test this please

**Comment by lgirdwood** [comment]
try again, not sure why CI got stuck.

**Comment by lgirdwood** [comment]
SOFCI TEST

**Review by lgirdwood — APPROVED** [review]

**Pull request merged**
