### PR TITLE
toolschain: update header files to support newer toolschain

### PR DESCRIPTION
**Pull request by mrajwa**
This patch updates XTENSA toolschain from version RG-2017.7 to RI-2020.5.

Signed-off-by: Marcin Rajwa <marcin.rajwa@linux.intel.com>

### CODE REVIEW

**Comment by paulstelian97** [comment]
@dbaluta This may help us with our woes with the old toolchains. @mrajwa Would this allow us to use 2020 Xtensa toolchain?

**Comment by mrajwa** [comment]
@paulstelian97, yes it should. Could you please verify on your end?

**Comment by lgirdwood** [comment]
@mrajwa build looks good (zephyr ICL is a new issue and there is a Zephyr fix PR is pending).
@aiChaoSONG @fredoh9 can we still run the CI tests for xtos if the Zephyr build fails ? Ideally we should run the test for every platform that builds.

**Comment by dbaluta** [comment]
@mrajwa Thanks a lot! It looks like now we can compile SOF with RI-2020.4! 

Care to provide a little bit more details in the commit message about what Xtensa tools version did you used :) .

**Review by lgirdwood — COMMENTED** [review]
@mrajwa is there any version info we could add in the commit message i.e. HAL update from version X to version Y ?

**Comment by mrajwa** [comment]
The commit message updated to reflect version update.

**Review by dbaluta — APPROVED** [review]

**Review by paulstelian97 — APPROVED** [review]

**Review by lgirdwood — APPROVED** [review]
Good work @mrajwa !

**Comment by lgirdwood** [comment]
SOFCI TEST

**Pull request merged**
