### PR TITLE
west.yml: update zephyr to 9852e8e15bc8

### PR DESCRIPTION
**Pull request by kv2019i**
Total of 287 commits with no known impact to SOF to builds.

### CODE REVIEW

**Comment by kv2019i** [comment]
Pretty good results (as expected). There's one fail in https://sof-ci.01.org/sofpr/PR8797/build2328/devicetest/index.html?model=MTLP_RVP_NOCODEC&testcase=multiple-pipeline-playback that is unexpected. No errors in kernel or mtrace logs, but data does not start moving to the SSP1/PCM1, so aplay times out. Given we need to wait for tomorrow for reviews, let me re-kick the SOF CI to get more data.

**Comment by kv2019i** [comment]
SOFCI TEST

**Comment by marc-hb** [comment]
> SOFCI TEST

You just lost the URLs to the previous runs :-(

**Review by marc-hb — APPROVED** [review]

**Review by lyakh — APPROVED** [review]

**Comment by kv2019i** [comment]
Test results now look ok, one system-PM fail in https://sof-ci.01.org/sofpr/PR8797/build2334/devicetest/index.html but this is a known thing. I'll proceed to merge this smaller increment and we can continue to take a bite of the more controversial Zephyr upstream changes in next.

**Pull request merged**
