### PR TITLE
sof_ri_info: add ADL Intel prod key to list of known keys

### PR DESCRIPTION
**Pull request by xanthein**
Extracted from
https://github.com/thesofproject/sof-bin/blob/main/v1.9.x/sof-v1.9.2/intel-signed/sof-adl.ri

### CODE REVIEW

**Comment by sofci** [comment]
Can one of the admins verify this patch?
> reply **test&nbsp;this&nbsp;please** to run this test once

**Comment by gkbldcig** [comment]
Can one of the admins verify this patch?

**Comment by marc-hb** [comment]
test this please

**Review by marc-hb — APPROVED** [review]
Successfully tested with both intel-signed/sof-adl.ri and sof-adl-s.ri. Thanks!

Missing Signed-Off:

**Review by lgirdwood — COMMENTED** [review]
@xanthein will be good to merge once we have your Signed-off-by: in the commit message.

**Review by marc-hb — APPROVED** [review]
Thanks for adding your Signed-Off! Sorry I missed the force push.

**Comment by lgirdwood** [comment]
Some CI seems to have got stuck, but this PR is not run as part of runtime CI testing.

**Pull request merged**
