### PR TITLE
topology: Add IIR support for jsl topology

### PR DESCRIPTION
**Pull request by yongzhi1**
Backport 3 patches from stable-v1.8 to jsl-004-drop-stable for IIR support.

### CODE REVIEW

**Comment by yongzhi1** [comment]
cc @macchian

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
@mwasko @bkokoszx looks fine to me for JSL 004. Btw, the CI is not fully working on older branches so may need manual validation.

**Comment by mwasko** [comment]
> @mwasko @bkokoszx looks fine to me for JSL 004. Btw, the CI is not fully working on older branches so may need manual validation.

Intel FW validation does not support maintenance and backport changes validation on legacy platform release branches. I am ok with merge but I need confirmation that changes were verified by the submitter. 

@yongzhi1 did you verified the backported changes on your end?

**Comment by lgirdwood** [comment]
@mwasko same patch to main passed CI.

**Comment by yongzhi1** [comment]
Hi, @mwasko @bkokoszx , can you approve this PR to be merged? jdl-004-drop-stable is still the current branch being referenced to add new features for Chrome products.

**Comment by yongzhi1** [comment]
Hi @mwasko ,

Yes, @macchian and Quanta have verified, thanks!

**Comment by cujomalainey** [comment]
CI is stuck and this is blocking a key release, merging

**Review by cujomalainey — APPROVED** [review]

**Pull request merged**
