### PR TITLE
[RFC] Add Dummy codec to slove dai issue of echo-ref

### PR DESCRIPTION
**Pull request by gongjun-song**
For codec max98357, it is not reasonable to use it as capture dai for
echo reference, because it only supports playback.

Set dummy codec for echo reference to solve this issue.

Signed-off-by: Gongjun Song <gongjun.song@intel.com>

### CODE REVIEW

**Comment by gongjun-song** [comment]
the sof-dev PR associated with this PR: https://github.com/thesofproject/linux/pull/3753

**Review by dbaluta — APPROVED** [review]

**Review by lgirdwood — COMMENTED** [review]
@gongjun-song sorry not following the commit message. I assume you are looking to enable echo ref PCM ?
@plbossart fyi, not sure how the kernel is working with max98357

**Comment by plbossart** [comment]
@lgirdwood The problem is for simple amplifiers that don't provide an echo reference. On some devices, the echo reference is generated by the firmware, but in that case we don't have a physical SSP that's tied to the echo reference pipeline. All the attempts I've seen do a silly inclusion of a pretend SSP just to get the job done, and there were multiple attempts that were never validated and it's been broken for a while.

The real fix would be to stop using a pretend SSP - and have some way of modeling the loopback done before rendering data on the playback SSP.

I don't have time to look into this, it's been broken for a very very long time I am afraid.

**Comment by lgirdwood** [comment]
> I don't have time to look into this, it's been broken for a very very long time I am afraid.

understood - I guess we will have to live with this in the short term until a valid solution can be upstreamed.

**Review by lgirdwood — APPROVED** [review]
@gongjun-song stiil RFC ?

**Comment by gongjun-song** [comment]
Thanks @lgirdwood, Let's wait a suitable solution, I will closed this PR

**Pull request closed without merging**
