### PR TITLE
Codec adapter fixes

### PR DESCRIPTION
**Pull request by dbaluta**
This fixes commit 771db86de29 which broke simple codec adapter pipelines. We introduce a new pipeline configuration named pipe-host-codec-adapter.m4 and use it for mixer pipeline. And getting back to using pipe-codec-adapter.m4 for simple codec adapter pipelines.

### CODE REVIEW

**Review by lgirdwood — APPROVED** [review]
@markbartonxperi fyi - can you also give this a try.

**Comment by markbartonxperi** [comment]
@lgirdwood Thanks for the heads-up.
I pulled latest `main` and had a go with the changes (I wasn't sure if these changes were intended to address anything in my issue, or not? https://github.com/thesofproject/sof/issues/4901)
Either way, using sof-hda-generic, inserting my pipeline on to PCM1 and directly including `sof/pipe-codec-adapter-playback.m4` from my `pipe-eq-iir-dts-codec-playback.m4` file - everything works fine.
If I include `sof/pipe-host-codec-adapter-playback.m4` from my `pipe-eq-iir-dts-codec-playback.m4` file then I get topology load errors on startup - not sure is this is expected.

Not sure if this helps!! Apologies if not. Let me know if there's anything else you want me to test.

**Comment by dbaluta** [comment]
@markbartonxperi if you topology uses a mixer or some sort then you should use sof/pipe-host-codec-adapter-playback.m4. Otherwise, ou should stay with the initial including of sof/pipe-codec-adapter-playback.m4

**Comment by lgirdwood** [comment]
@markbartonxperi ok, lets chat tomorrow about it. Fwiw, @singalsu has spotted a regression in mixer which he is fixing atm.

**Pull request merged**
