### PR TITLE
Fix RTNR dmic usage by including generic dmic with kwd

### PR DESCRIPTION
**Pull request by MingJenTai**
This PR fixes RTNR dmic usage by including generic dmic with kwd.

### CODE REVIEW

**Comment by lgirdwood** [comment]
@sathya-nujella @macchian any comments ?

**Comment by sathya-nujella** [comment]
Adding @jairaj-arava for checking.

**Comment by lgirdwood** [comment]
@jairaj-arava any update ?

**Comment by jairaj-arava** [comment]
> @jairaj-arava any update ?

Hi @lgirdwood sorry for the delay. Yes, the changes seems to be good.

**Comment by gkbldcig** [comment]
Can one of the admins verify this patch?

**Comment by lgirdwood** [comment]
@MingJenTai can you rebase as we have a conflict. Thanks !

**Comment by MingJenTai** [comment]
@lgirdwood Hi, I rebased the commit and there is no modifications in the PR so the PR is closed automatically.

**Comment by jairaj-arava** [comment]
@lgirdwood is this expected?

**Pull request closed without merging**
