### PR TITLE
ssp: move SSP blck enablement to ssp_set_config

### PR DESCRIPTION
**Pull request by plbossart**
The SSP clocks are currently started in the trigger phase.

This is problematic for multiple reasons:

a) we should *NEVER* change clock sources in a trigger
phase. Switching clocks in and out based on start/stop is asking for
trouble.
b) we should enable the clocks in the prepare phase
c) we are missing a hw_free (dual of prepare) for DAIs. We should stop
the SSP and switch clocks in a hw_free

This patch moves some of the configuration to the prepare phase (which
internally calls ssp_set_config).

Initial results show that we can start the bclk 6+ms before starting
the transfers.

FIXME:
1. the bclk signal is zeroed out at some point. that's not normal
2. the fsync signal should start at the same time as the bclk
according to the hardware documentation. It's not clear what causes
the fsync to remain high for ~6ms.
3. there is a ~4.2ms delay between the fsync activation and the actual data
transfers. This may be due to buffering in the DSP, but that's clearly
not good at all.

Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>

### CODE REVIEW

**Comment by plbossart** [comment]
Logic pro grab before the changes:

Up2-nocodec-original

Logic Pro grab with this PR:

ssp-enabled-in-set-config

**Comment by plbossart** [comment]
This is a WIP to try and see what can be done to address https://github.com/thesofproject/sof/issues/4156

**Comment by plbossart** [comment]
To help with the debug of the SSP settings, if I just take the SOF main branch and add a 15ms before enabling the DMA, both the SSP blck and fsync start at the same time, and I measure a delay of 19.2 ms (=15 + the constant 4.2ms that seems to come from firmware)

````diff
iff --git a/src/drivers/intel/ssp/ssp.c b/src/drivers/intel/ssp/ssp.c
index d03efb4e0..9d116dd5c 100644
--- a/src/drivers/intel/ssp/ssp.c
+++ b/src/drivers/intel/ssp/ssp.c
@@ -765,6 +765,9 @@ static void ssp_start(struct dai *dai, int direction)
                                             ssp->params.bclk_delay));
        }
 
+       wait_delay(clock_ms_to_ticks(PLATFORM_DEFAULT_CLOCK,
+                                    15));
+       
        /* enable DMA */
        if (direction == DAI_DIR_PLAYBACK) {
                ssp_update_bits(dai, SSCR1, SSCR1_TSRE, SSCR1_TSRE);
````

[ssp-delay-in-trigger.diff.txt](https://github.com/thesofproject/sof/files/6475852/ssp-delay-in-trigger.diff.txt)

trigger-15ms-delay

**Comment by uhs987** [comment]
I thought ssp_set_config is called when receiving SOF_IPC_DAI_CONFIG command in the initialization? There is no IPC command sent to DSP during the PREPARE stage.

The SOF_IPC_STREAM_PCM_PARAMS may be a better place to turn on clocks since it's sent in HW_PARAMS stage.

**Review by lgirdwood — COMMENTED** [review]
Could it be the SSP port config during hw_params ? or prepare() that's enabling some SSP logic ?? We could try and validate the params only at hw_params() and program them at trigger(start) ?

**Comment by plbossart** [comment]
@lgirdwood @uhs987 this is super confusing
hw_params is called *before* ssp_set_config for some reason. the flow I reversed-engineer is component_prepare>ssp_set_config.
But we have no hw_free.

And no we need to enable the clock at the hw_params or prepare level, this is the ask to start the clock BEFORE transfering data.

**Comment by lgirdwood** [comment]
> @lgirdwood @uhs987 this is super confusing
> hw_params is called _before_ ssp_set_config for some reason. the flow I reversed-engineer is component_prepare>ssp_set_config.
> But we have no hw_free.

hw_free() on ALSA is aligned reset() ordering here.

> 
> And no we need to enable the clock at the hw_params or prepare level, this is the ask to start the clock BEFORE transfering data.

I also cant quite remember when ssp_config() is called, it could be during DAI config IPC ? However, the dai ops should support a prepare() callback to enable any clocks if needed prior to start ?>

**Comment by plbossart** [comment]
@lgirdwood the dai_driver doesn't have a prepare or a reset

````c
struct dai_ops {
	int (*set_config)(struct dai *dai, struct sof_ipc_dai_config *config);
	int (*trigger)(struct dai *dai, int cmd, int direction);
	int (*pm_context_restore)(struct dai *dai);
	int (*pm_context_store)(struct dai *dai);
	int (*get_hw_params)(struct dai *dai,
			     struct sof_ipc_stream_params *params, int dir);
	int (*hw_params)(struct dai *dai, struct sof_ipc_stream_params *params);
	int (*get_handshake)(struct dai *dai, int direction, int stream_id);
	int (*get_fifo)(struct dai *dai, int direction, int stream_id);
	int (*probe)(struct dai *dai);
	int (*remove)(struct dai *dai);
````

I reverse-engineered that hw_params is called BEFORE set_config. There is no 'unset_config' or hw_free, this is really not so good IMHO.

**Comment by brentlu** [comment]
> I thought ssp_set_config is called when receiving SOF_IPC_DAI_CONFIG command in the initialization? There is no IPC command sent to DSP during the PREPARE stage.
> 
> The SOF_IPC_STREAM_PCM_PARAMS may be a better place to turn on clocks since it's sent in HW_PARAMS stage.
> 
> Regards,
> Brent

Sorry I've been working on old branch for too long. In latest kernel, a DAI_CONFIG and a PCM_PARAMS command will be sent during HW_PARAMS stage. However, DAI_CONFIG will also be sent during FW initialization and HW_FREE stage.

[   61.295508] sound pcmC0D0p: snd_pcm_playback_open:
...
[   61.451634] sound pcmC0D0p: snd_pcm_common_ioctl: HW_PARAMS
[   61.452782] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
[   61.453103] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
...
[   61.455415] sound pcmC0D0p: snd_pcm_common_ioctl: START
[   61.455961] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x60040000: GLB_STREAM_MSG: TRIG_START
...
[  188.229744] sound pcmC0D0p: snd_pcm_common_ioctl: DROP
[  188.231064] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
[  188.231281] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x60030000: GLB_STREAM_MSG: PCM_FREE
...
[  188.231530] sound pcmC0D0p: snd_pcm_common_ioctl: HW_FREE
[  188.232732] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
...
[  188.233064] sound pcmC0D0p: snd_pcm_release:
[  192.020313] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x40010000: GLB_PM_MSG: CTX_SAVE


[  224.595405] sound pcmC0D1c: snd_pcm_capture_open:
...
[  224.595850] sound pcmC0D1c: snd_pcm_common_ioctl: HW_PARAMS
[  224.596816] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
[  224.597078] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
...
[  224.600195] sound pcmC0D1c: snd_pcm_common_ioctl: START
[  224.602506] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x60040000: GLB_STREAM_MSG: TRIG_START
...
[  250.843818] sound pcmC0D1c: snd_pcm_common_ioctl: DROP
[  250.843839] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
[  250.844114] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x60030000: GLB_STREAM_MSG: PCM_FREE
...
[  250.846574] sound pcmC0D1c: snd_pcm_common_ioctl: HW_FREE
[  250.849241] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG


The log is captured from a TGL Ubuntu 20.04 LTS machine.
SOF: main, f510435a253373c806c49fbc32d876287bcbe801
Linux: topic/sof-dev, 0e1e5072818cfd37c80010d2889f629ccb74c7ca

[dmesg.txt](https://github.com/thesofproject/sof/files/6498941/dmesg.txt)


Regards,
Brent

**Pull request closed without merging**
