### PR TITLE
Pipeline 3 periods

### PR DESCRIPTION
**Pull request by libinyang**
This patch set supports to set 3 period buffers in the pipeline. And sof-icl-rt711-rt1308-rt715 uses 3 period buffers in muxdemux pipelines. With 3 period buffers, FW can have more buffer to process the mux/demux.

### CODE REVIEW

**Comment by plbossart** [comment]
Someone will have to explain to me why we keep adding buffers. Why would a demux need 3 periods, and not a mixer then?

**Comment by libinyang** [comment]
> Someone will have to explain to me why we keep adding buffers. Why would a demux need 3 periods, and not a mixer then?

To be honest, I don't have much knowledge about this. This patch is based on @lgirdwood 's suggestion. @lgirdwood Could you please help answer @plbossart 's question? Thanks.

**Comment by libinyang** [comment]
Jaska has another patch to fix the issue https://github.com/thesofproject/sof/pull/3586. @juimonen Could you please help comments?

**Comment by juimonen** [comment]
@libinyang @plbossart this 3 periods was helping us to pinpoint the issue for demux. So basically this was giving more "time" for the demux to do its thing (which in 8 channels set in matrix is currently doing something strange). 

Quick fix for topology is here:
https://github.com/thesofproject/sof/pull/3586

Proper fix for demux is here:
https://github.com/thesofproject/sof/pull/3583

so both above PR's can go in, they should not mess with each other and they are 
both individually fixing the issue.

so I think we can close this, thanks.

**Comment by libinyang** [comment]
@juimonen If we are using more channels than 2, let's say, 8 channels. We still need similar patch like this, right?

**Comment by juimonen** [comment]
@libinyang not sure... I'm not totally on top of what happened when the distortion appeared... so was it actually a performance limit issue or something that demux was just writing to wrong place and causing it, or perhaps something else. it should be tested after @bkokoszx demux fix with maximum 8 channel streams.

**Comment by lgirdwood** [comment]
@juimonen do we still need this workaround ?

**Comment by juimonen** [comment]
@lgirdwood no, let's close

**Pull request closed without merging**
