### PR TITLE
Revert "topologies: switch all .m4 files to codec_provider and codec_consumer

### PR DESCRIPTION
**Pull request by marc-hb**
This reverts commit f50b6fe0adc440a5b0d93054372adec74f0a013f.

I discovered the hard way that this change causes alsatplg version
1.2.2 (the default version in the current LTS Ubuntu) to corrupt just
a few bytes in .tplg output in an incredibly discrete and
time-consuming way: no error message at build time and same file size.
See example at https://github.com/thesofproject/sof/pull/5162.

We could/should just require a minimum alsatplg version at the CMake
level but at this moment we don't even know which minimum version is
needed and we would also need to take some time to test a few alsatplg
versions. If version 1.2.2 would just fail with an decent error
message that can be searched and discussed then everything would be
fine but silent corruption is really not OK.

So users of recent versions will unfortunately have to live with the
huge number of warnings for now.

Signed-off-by: Marc Herbert <marc.herbert@intel.com>

### CODE REVIEW

**Review by ranj063 — APPROVED** [review]

**Comment by aiChaoSONG** [comment]
Confirmed the issue is caused by https://github.com/thesofproject/sof/commit/c687815185948d49350e4b58d59e786ac16339e1, don't revert this one.

**Comment by marc-hb** [comment]
> Confirmed the issue is caused by c687815, don't revert this one.

You're looking at something different. To test this use a revert only, don't involve other commits.

**Comment by marc-hb** [comment]
I spent more time looking at the recursive diffoscope output (awesome tool, use it). What happens is very simple:

```
             codec_slave  codec_consumer
1.2.2        0101                0000
1.2.6        0101                0101
```

Example:

```diff
├── sof-acp.conf
@@ -844,9 +844,9 @@
 	format          "I2S"
        mclk              "codec_mclk_in"
         mclk_freq         "49152000"
-       bclk              "codec_consumer"
+       bclk              "codec_slave"
         bclk_freq         "3072000"
-       fsync              "codec_consumer"
+       fsync              "codec_slave"
         fsync_freq         "48000"
               tdm_slots       "2"
        tdm_slot_width  "32"
├── sof-acp.tplg
 000015d0  00 00 00 00 00 00 00 78  00 00 00 00 00 00 00 01  |.......x........|
-000015e0  00 00 00 00 00 00 01 01  01 00 00 00 00 ee 02 00  |................|
+000015e0  00 00 00 00 00 00 00 00  01 00 00 00 00 ee 02 00  |................|
 000015f0  e0 2e 00 80 bb 00 00 02  00 00 00 20 00 00 00 03  |........... ....|
 00001600  00 00 00 03 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 00001610  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|

```

All topologies show the same difference.

**Comment by marc-hb** [comment]
Usual `rtcwake` timeout in https://sof-ci.01.org/sofpr/PR5192/build11581/devicetest/?model=CML_SKU0955_HDA&testcase=check-suspend-resume-with-capture-5, everything else green.

**Review by aiChaoSONG — APPROVED** [review]
The inclusive words **codec_consumer** and  **codec_provider** are added after the alsa-lib 1.2.2 by Pierre. With #5162,  the alsa-lib 1.2.2 cannot recognize the inclusive words, so the code goes to the ELSE part and will assign wrong value to bclk_provider(was bclk_master) and fsync(was fsync_master).

#5162 should be merged into the code once alsa-lib 1.2.2 becomes deprecated and no one uses it, but not now.

**Comment by marc-hb** [comment]
Thanks @aiChaoSONG ! So every alsatplg version before https://github.com/alsa-project/alsa-lib/commits/706192341d1d0bbb906 will silently corrupt the .tplg output, correct? If yes did you find (maybe with `git describe --contains`) which is the first alsatplg release after https://github.com/alsa-project/alsa-lib/commits/706192341d1d0bbb906 ?

The alternative to this revert is to (loudly) fail the build and force developers to upgrade ALSA to the minimum version required. @ranj063 recently added such a version check for topology2, we could easily add another one.

**Comment by aiChaoSONG** [comment]
@marc-hb  It's alsa-lib 1.2.5

**Comment by marc-hb** [comment]
> @marc-hb It's alsa-lib 1.2.5

So I think 1.2.5 is too recent and we should merge this revert.

While Fedora is tracking ALSA very closely thanks to @perexg , other distributions are lagging behind
https://packages.fedoraproject.org/pkgs/alsa-lib/alsa-lib/

The latest Ubuntu 21.10 is still on 1.2.4 (the next one will have at least 1.2.5)
https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=libatopology&searchon=names

The latest Debian release is less than one month old and it still has 1.2.4
https://packages.debian.org/bullseye/libatopology2

https://build.opensuse.org/request/show/899947 upgrade to 1.2.5 in June 2021

**Comment by perexg** [comment]
It not easier to check the alsatplg version before the call (in the build system) rather than to revert the whole change?

Also, the code should be improved to fail when an unknown value is set.

**Comment by marc-hb** [comment]
> It not easier to check the alsatplg version before the call (in the build system) rather than to revert the whole change?

Considered above.

> Also, the code should be improved to fail when an unknown value is set.

Which code? I don't think any distro would make any emergency 1.2.4.1 ALSA upgrade just for this.

This rename is simply too early, that's all.

When made this rename I realized the corresponding ALSA change was only 1 year old. However:
- I underestimated the distro lag
- much more importantly, I didn't expect any silent corruption.

It's unfortunate the deprecation warning was added at the same time than the feature without any transition period.

**Comment by perexg** [comment]
> > It not easier to check the alsatplg version before the call (in the build system) rather than to revert the whole change?
> 
> Considered above.

It looks like a bit bad workflow if you don't run your tests against the latest alsa-utils (alsatplg). The code is in upstream really long time enough for the verification and you can do the verification right now.

Alternate way is to replace the clock strings back for the older alsatplg binaries (use sed in the build system or so).

> > Also, the code should be improved to fail when an unknown value is set.
> 
> Which code? I don't think any distro would make any emergency 1.2.4.1 ALSA upgrade just for this.

The upstream code to avoid such situations in future.

**Comment by perexg** [comment]
Note - I believe that the generated ,tplg binaries between alsatplg 1.2.2 and recent should be identical (so the verification can compare the .tlpg binaries only - no hw tests are required). It should be a quick job.

**Comment by lgirdwood** [comment]
@ranj063 can you confirm the topology2 fails for unknown values ?
@marc-hb any reason why we are using the older ALSA releases in our validation ? We should be using the latest version that will ship with current Fedora/Ubuntu. I dont think there is any point testing LTS when newer non LTS releaese are current (as LTS will probably never upgrade ALSA, FW or kernel releases AFAICT).

**Comment by perexg** [comment]
> > any reason why we are using the older ALSA releases in our validation ?
> 
> Validation is using ALSA 1.2.6 now, this revert is for developers.

In this case, the developers should be informed to use the new ALSA release (and the build system should fail). It's quite easy to develop things using docker/podman, if they want to use the distro without regular upstream updates. Only my two cents. I won't comment this more.

**Review by greg-intel — APPROVED** [review]
I approved the original, and am disappointed that this didn't work out. 
The warnings are very noisy.

**Comment by marc-hb** [comment]
Good developer experience is entirely about removing as much friction as possible. 

From https://thesofproject.github.io/latest/getting_started/build-guide/build-from-scratch.html?highlight=alsa#build-alsa-lib-and-alsa-utils-from-source
> Installing alsa-lib systemwide may break some audio applications. Only perform this if you know what you are doing. We recommend that you install it locally (under $HOME) or use Docker (see Build SOF with Docker.)

Compiling gcc toolchains is also a huge amount of friction but _only once_.

Docker is relatively easy to use but it's not frictionless either. For instance:
https://linuxnatives.net/2019/align-user-ids-inside-and-outside-docker-with-subuser-mapping
https://medium.com/@mccode/the-misunderstood-docker-tag-latest-af3babfd6375
etc.

In fact in related #5202  I asked some (experienced) developers to test with https://thesofproject.github.io/latest/getting_started/build-guide/build-with-docker.html#build-firmware-binaries-with-docker and even when these instructions are very short, those who have never used docker yet were... not interested! Friction. https://www.google.com/search?q=friction+habits

**Comment by marc-hb** [comment]
> While Fedora is tracking ALSA very closely thanks to @perexg , other distributions are lagging behind
https://packages.fedoraproject.org/pkgs/alsa-lib/alsa-lib/

Actually, even Fedora 35 does not work out of the box. It's supposed to work:
```
rpm -qa alsa*
alsa-lib-1.2.6.1-3.fc35.x86_64
alsa-topology-1.2.6.1-3.fc35.noarch
alsa-ucm-1.2.6.1-3.fc35.noarch
alsa-firmware-1.2.4-5.fc35.noarch
alsa-tools-firmware-1.2.5-2.fc35.x86_64
alsa-utils-1.2.6-1.fc35.x86_64
alsa-lib-devel-1.2.6.1-3.fc35.x86_64
alsa-topology-utils-1.2.6-1.fc35.x86_64
alsa-lib-1.2.6.1-3.fc35.i686
alsa-sof-firmware-1.9.3-1.fc35.noarch
```

Yet the `-I, --inc-dir=DIR` is missing from some unknown reason:

```
alsatplg --help
Usage: alsatplg [OPTIONS]...

-h, --help              help
-c, --compile=FILE      compile configuration file
-p, --pre-process       pre-process Topology2.0 configuration file before compilation
-P, --pre-process=FILE  pre-process Topology2.0 configuration file
-d, --decode=FILE       decode binary topology file
-n, --normalize=FILE    normalize configuration file
-u, --dump=FILE         dump (reparse) configuration file
-v, --verbose=LEVEL     set verbosity level (0...1)
-o, --output=FILE       set output file
-D, --define=ARGS       define variables (VAR1=VAL1[,VAR2=VAL2] ...)
-s, --sort              sort the identifiers in the normalized output
-g, --group             save configuration by group indexes
-x, --nocheck           save configuration without additional integrity checks
-z, --dapm-nosort       do not sort the DAPM widgets
-V, --version           print version
```

So `./scripts/build-tools.sh -T` fails with a cryptic:

```
Generating cavs-gain-hda.tplg
alsatplg: invalid option -- 'I'
```

What a poor experience.

I found this suspicious bit https://github.com/alsa-project/alsa-utils/blob/40202a522aa86599bffaabf8097bf9bf1cef4f61/topology/topology.c#L59

```C
"-o, --output=FILE       set output file\n"
#if SND_LIB_VER(1, 2, 5) < SND_LIB_VERSION
"-D, --define=ARGS       define variables (VAR1=VAL1[,VAR2=VAL2] ...)\n"
"-I, --inc-dir=DIR       set include path\n"
#endif
"-s, --sort              sort the identifiers in the normalized output\n"
```

(funny how the default branch name is still "master")

**Comment by marc-hb** [comment]
https://sof-ci.01.org/sofpr/PR5192/build12056/devicetest/?model=APL_UP2_NOCODEC_ZEPHYR&testcase=multiple-pause-resume-5 looks like unrelated #5257, everything else passed.

**Review by fredoh9 — APPROVED** [review]

**Comment by marc-hb** [comment]
- Submitted PR to require alsatplg 1.2.5 or above
https://github.com/thesofproject/sof/pull/8377

Note another, unrelated and much more recent silent corruption with `alsatplg`:
- https://github.com/thesofproject/sof/issues/8357

**Pull request merged**
