### PR TITLE
xtensa-build-zephyr: temporarily exclude ICL 

### PR DESCRIPTION
**Pull request by marc-hb**
Because ICL fails to build, .noinit/.cached section overlap since
revert zephyrproject-rtos/zephyr#40319

Signed-off-by: Marc Herbert <marc.herbert@intel.com>

### CODE REVIEW

**Review by kv2019i — APPROVED** [review]

**Comment by lgirdwood** [comment]
@marc-hb I assume you have aligned with @andyross for upstream fix ?

**Review by lgirdwood — APPROVED** [review]

**Comment by marc-hb** [comment]
> @marc-hb I assume you have aligned with @andyross for upstream fix ?

No I haven't. @kv2019i  said something should be coming.

**Comment by kv2019i** [comment]
@lgirdwood Andy's adsp cleanup PR set might fix this. Let's see after that is merged, whether this is stillan issue and file a bug. But for now I'd say this is low priority.

**Comment by lgirdwood** [comment]
Not a blocker for v2.0-rc1, but will need to fix for 2.0-rc2

**Comment by marc-hb** [comment]
I believe @kv2019i is referring to cleanup https://github.com/zephyrproject-rtos/zephyr/pull/39603

**Pull request merged**
