### PR TITLE
topology: sof-adl-nau8825: backport to adl-004-drop-stable branch

### PR DESCRIPTION
**Pull request by brentlu**
Backport PR https://github.com/thesofproject/sof/pull/6579 to adl-004-drop-stable.

### CODE REVIEW

**Comment by cujomalainey** [comment]
Probably better to land this on rpl-001, we are dropping this branch very soon

**Comment by brentlu** [comment]
> Probably better to land this on rpl-001, we are dropping this branch very soon

You mean ADL is moving to rpl-001 branch?

**Comment by brentlu** [comment]
Another PR is created for rpl-001 branch

https://github.com/thesofproject/sof/pull/6596

**Comment by cujomalainey** [comment]
> > Probably better to land this on rpl-001, we are dropping this branch very soon
> 
> You mean ADL is moving to rpl-001 branch?
> 

That is correct

**Comment by brentlu** [comment]
@cujomalainey  not sure if we also need this branch because customer is about to power-on their device soon.

**Comment by lgirdwood** [comment]
@mwasko any advice on the target branch ?

**Comment by mwasko** [comment]
> @mwasko any advice on the target branch ?

I would strongly recommend the rpl-001, this is what we want to use as a base branch for maintenance for tgl, adl and rpl targets. Most likely we will branch from rpl-001 and create sth with more generic name like cavs-2.5, but we need to align it first with adl-004.

**Comment by brentlu** [comment]
The topology already merged to rpl-001. We also need it on adl-004 for current on-going Chrome projects as my understanding.

**Comment by brentlu** [comment]
Could someone merge this PR so we can continue the work for ODM pilot run?

**Comment by brentlu** [comment]
rebase for adl-004 changes

**Comment by lgirdwood** [comment]
> Could someone merge this PR so we can continue the work for ODM pilot run?

Best to keep @mwasko in the loop for production branches as he is the owner.

**Comment by mwasko** [comment]
> > Could someone merge this PR so we can continue the work for ODM pilot run?
> 
> Best to keep @mwasko in the loop for production branches as he is the owner.

thank you Liam, @brentlu please ping me whenever the PR merge is delayed

**Comment by cujomalainey** [comment]
> @cujomalainey  not sure if we also need this branch because customer is about to power-on their device soon.

It will be needed as it will break when we update

**Pull request merged**
