### PR TITLE
component: do no modify blob data size until new data is ready

### PR DESCRIPTION
**Pull request by ranj063**
If new blob data arrives while the component is active and using
the current blob data, we should not modify the current blob size
with the new size until the new data has been applied. So,
introduce a new field, new_data-size, that will hold the size
of the new blob until the new blob is applied.

While we're at this, also clean up setting the data_ready flag.

Signed-off-by: Ranjani Sridharan <ranjani.sridharan@linux.intel.com>

### CODE REVIEW

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
@singalsu this good for you ?

**Review by singalsu — APPROVED** [review]

**Comment by singalsu** [comment]
Looks good, seems like no change need for processing components, right?

**Comment by lgirdwood** [comment]
> Looks good, seems like no change need for processing components, right?

Yes, that's correct.

**Comment by lgirdwood** [comment]
One ADL not tested by CI, but the other passed.

**Pull request merged**
