### PR TITLE
test: reinstated some of turned off unit tests

### PR DESCRIPTION
**Pull request by dabekjakub**
Signed-off-by: Jakub Dabek <jakub.dabek@linux.intel.com>

### CODE REVIEW

**Comment by lgirdwood** [comment]
@jajanusz no idea yet, I think ordering is important but not sure why it missed you. Its not like GH has assigned anybody else either apart from top level reviewers ?

**Comment by dabekjakub** [comment]
This change does not turn on the buffer volume stress tests. I will wait with those until after your buffer size changes.

**Comment by lgirdwood** [comment]
@dabekjakub ok great, will apply after @jajanusz approves and CI is resolved.

**Comment by lgirdwood** [comment]
@dabekjakub still seeing CI error, can you check.

**Comment by dabekjakub** [comment]
@lgirdwood Ci passed

**Pull request merged**
