### PR TITLE
ssp: add LBM quirk

### PR DESCRIPTION
**Pull request by emilchudzik**
Signed-off-by: Emil Chudzik <emil.chudzik@intel.com>

### CODE REVIEW

**Comment by jajanusz** [comment]
There is 'ssp_set_loopback_mode' implemented but it's used nowhere - looks like someone wanted to add it to DAI or somewhere - I think we can finish that (it that's true) or use this PR.

**Comment by lgirdwood** [comment]
@jajanusz LBM mode was used in the past, but it would be best to hook this up to component set/get data and hence use a kcontrol to change it at runtime via a kcontrol.

**Comment by jajanusz** [comment]
@lgirdwood I guess @emilchudzik  needs it for python tests. Our validators have windows setups so they can't use kcontrol, I don't know if there is some equivalent for windows

**Comment by lgirdwood** [comment]
@jajanusz ah ok, I see. Makes sense for validation.
@emilchudzik this will nee equivalent PR for kernel to add the quirk in the header.

**Comment by lgirdwood** [comment]
@plbossart any input ?

**Comment by plbossart** [comment]
> @plbossart any input ?

I don't think it makes sense to make this available through a kcontrol. There is a dependency on a topology to make use of this, and you probably don't want to expose this to a user.

This was discussed a long time back, see https://github.com/thesofproject/linux/pull/10
This was prior to my sabbatical break so I don't recall anything beyond the fact that a kcontrol was not recommended.

**Comment by xiulipan** [comment]
@lgirdwood @plbossart 
Seems the LBM ghost is coming back. I did not think kcontrol is a good idea.
I think a single debugfs with a hookt to send some IPC would be better both for developer and end user.

**Comment by lgirdwood** [comment]
Whether it's kcontrol or not, it has to be in topology. The current PR is for validation and means a validation topology change to enable the LBM.

**Comment by emilchudzik** [comment]
> @emilchudzik this will nee equivalent PR for kernel to add the quirk in the header.

Issue raised, please assign it to proper person.
https://github.com/thesofproject/linux/issues/621

**Comment by emilchudzik** [comment]
As Janusz wrote before method 'ssp_set_loopback_mode' is implemented but is nowhere to be used. In my opinion adding LBM quirk and call it is better and easier way to use (e.g. in validation) than creating new IPC specifically for LBM.
From Swarm documents "SIP_cAVS1.8_Programming_Reference_rev1.0b.docx", page 172, table for SSP Control 1:
image

If method "ssp_set_loopback_mode" is never used so do we still need it?
@lgirdwood @xiulipan what do you think?

**Comment by lgirdwood** [comment]
@emilchudzik it can be dropped, we can deal with LBM via quirk. Can you include a patch that drops it in this PR ? Thanks

**Comment by plbossart** [comment]
if you drop the loopback mode for SSP, you should do it for all interfaces and remove all remaining code related to this:

````
src/drivers/intel/cavs/dmic.c:static inline int dmic_set_loopback_mode(struct dai *dai, uint32_t lbm)
src/drivers/intel/cavs/dmic.c:  .set_loopback_mode      = dmic_set_loopback_mode,
src/drivers/intel/cavs/hda.c:static int hda_set_loopback_mode(struct dai *dai, uint32_t lbm)
src/drivers/intel/cavs/hda.c:   .set_loopback_mode      = hda_set_loopback_mode
src/include/sof/dai.h:  int (*set_loopback_mode)(struct dai *dai, uint32_t lbm);
src/include/sof/dai.h:static inline int dai_set_loopback_mode(struct dai *dai, uint32_t lbm)
src/include/sof/dai.h:  return dai->ops->set_loopback_mode(dai, lbm);
````

**Pull request merged**
