### PR TITLE
platform: imx: Fix interrupt numbers

### PR DESCRIPTION
**Pull request by paulstelian97**
Signed-off-by: Paul Olaru <paul.olaru@nxp.com>

### CODE REVIEW

**Comment by dbaluta** [comment]
@paulstelian97 thanks! It seems that my counting abilities are as good as my copy paste skills!

**Comment by dbaluta** [comment]
SOFCI TEST

**Comment by dbaluta** [comment]
@jajanusz @tlauda what's the approach here? We have several CI test failing but this obviously is not the offending commit. Can we merge?

**Comment by michalgrodzicki** [comment]
> @jajanusz @tlauda what's the approach here? We have several CI test failing but this obviously is not the offending commit. Can we merge?

@xiulipan - I think CI question is for you, please help.

**Comment by jajanusz** [comment]
> @jajanusz @tlauda what's the approach here? We have several CI test failing but this obviously is not the offending commit. Can we merge?

The CI that failed doesn't test code that you toched and jenkins is unstable anyway, so it's safe to ignore if you don't touch code that  can affect failing platforms.

**Comment by xiulipan** [comment]
@jajanusz @michalgrodzicki @dbaluta 
The CI failure are all some known issues. We may need to get some configuration about ignore test model and test case.

**Pull request merged**
