### PR TITLE
Reverts to fix trace/scheduling issues

### PR DESCRIPTION
**Pull request by plbossart**
blind reverts to try and root cause https://github.com/thesofproject/sof/issues/4706. I took the most likely suspects applied since August 30 (problems appeared on August 31 Intel daily test 6244)

last known working SHA1: 6b650bd95fe0
first error reported SHA1: 8fa5ff579351
 
I don't see any issues with all the reverts in this branch. 
Additional testing would be needed by the 'firmware team' to find the issues.

This is serious stuff impact the work of several developers, we can't afford this sort of regressions. @lgirdwood @keyonjie @lyakh @ranj063

### CODE REVIEW

**Comment by plbossart** [comment]
500 iterations and no problems reported with those reverts....

**Comment by lgirdwood** [comment]
@lyakh is working on the fix, so I wont be reverting atm. This will be in rc1 so I want it to go through several rounds of daily testing.

**Comment by plbossart** [comment]
> @lyakh is working on the fix, so I wont be reverting atm. This will be in rc1 so I want it to go through several rounds of daily testing.

I see nothing wrong with revert and redo. That's why CI exists. Please don't treat this lightly, it's has a material impact on others and prevented me from moving forward with my own work.

**Comment by marc-hb** [comment]
> so I want it to go through several rounds of daily testing.

I just double checked with @aiChaoSONG (thanks!) and while it requires a bit of practice it is definitely possible with a few clicks to run any test plan on any non-main branch or tag. Even more tests than the daily testing if desired.

Using the main branch for testing work in progress is effectively enrolling the entire rest of the project in the testing effort for some specific feature. Quite disruptive indeed and of course not scalable.

**Pull request closed without merging**
