### PR TITLE
west.yml: update Zephyr to f9f44b6dcdd (Mar 07)

### PR DESCRIPTION
**Pull request by kv2019i**
Switch back to main Zephyr repository and commit 0d5a670f4f073.

This includes multiple changes to fix compilation with Zephyr commit "hwmv2: Introduce Hardware model version 2 and convert devices".

### CODE REVIEW

**Comment by kv2019i** [comment]
@iuliana-prodan Is https://github.com/zephyrproject-rtos/sof/pull/40 mandatory update for IMX, or can we do these incrementally? For Intel targets, some targets work with transitionary definitions, but at least INtel MTL targets were broken with the update as some of the SOC series Kconfig options were renamed in the process and SOF was using these in multiple places.

**Comment by kv2019i** [comment]
I guess we need to cherry-pick IMX changes when updating as I can see some IMX builds failing https://github.com/thesofproject/sof/actions/runs/8171751130/job/22340660139?pr=8913 

In local test, I still managed to hit https://github.com/zephyrproject-rtos/zephyr/issues/69807 so this can be also a problem for merge (but lets' see whether CI agrees with my local tests or not).

**Comment by kv2019i** [comment]
Let me submit again, I didn't realize https://github.com/zephyrproject-rtos/sof/commits/zephyr/ has the patches. Let me squash them up and merge.

**Comment by kv2019i** [comment]
The "sof-ci/jenkins/pr-buld" fail requires actions on SOF CI jenkins jobs, the changed path with HWMv2 trigger errors in the tools build.

There's also additional error in the imx build -> https://github.com/thesofproject/sof/actions/runs/8175491141/job/22352725234?pr=8913 ? Something with imx.toml file. Can you check @iuliana-prodan ?

**Comment by iuliana-prodan** [comment]
> The "sof-ci/jenkins/pr-buld" fail requires actions on SOF CI jenkins jobs, the changed path with HWMv2 trigger errors in the tools build.
> 
> There's also additional error in the imx build -> https://github.com/thesofproject/sof/actions/runs/8175491141/job/22352725234?pr=8913 ? Something with imx.toml file. Can you check @iuliana-prodan ?

I'm sorry, I forgot about this.. actually I thought is merged: https://github.com/zephyrproject-rtos/zephyr/pull/69776

@kv2019i  if you can merge it, it will be great!

**Comment by marc-hb** [comment]
In https://sof-ci.01.org/sof-pr-viewer/#/build/PR8913/build13681617, the same test failed the same way on both MTL and LNL (other tests passed). That would be too much of a coincidence so it is most likely caused by this PR

```
TestKDTopologies.test_003_01_kd_topology_host_gw[2ch-24in32bit-]


10:47:28,560 INFO  - E TimeoutError: FW status on IPC timeout after 5.0 seconds:
10:47:28,560 INFO  - E FW status: 0x00000005
10:47:28,560 INFO  - E Last error code: 0x00000000 (ADSP_SUCCESS)
```

**Comment by marc-hb** [comment]
SOFCI TEST

**Comment by marc-hb** [comment]
> The "sof-ci/jenkins/pr-buld" fail requires actions on SOF CI jenkins jobs, the changed path with HWMv2 trigger errors in the tools build.

Done, https://sof-ci.01.org/sofpr/PR8913/build3193/build was successful.

Now the tests are running and you can move to the next step: looking at DSP panics...

**Comment by kv2019i** [comment]
V3 attempt:
- SOF CI jenkins job fixed -> thanks @marc-hb and @keqiaozhang !
- backported https://github.com/zephyrproject-rtos/zephyr/pull/69776 (not yet merged although reviews ready)
- apply the PM revert to address https://github.com/thesofproject/sof/issues/8908
 
I'll mark this as DNM for now, but let's see if CI all passes (they should).

**Comment by kv2019i** [comment]
@iuliana-prodan can you check, there seems to be still something left, I see two failures with IMX targets. Hopefully I picked the right patches.

**Comment by kv2019i** [comment]
@marc-hb It seems the HWMv2 (or some change that came here as well) has broken the Linux-windows build check
https://github.com/thesofproject/sof/actions/runs/8184833177/job/22380383895?pr=8913
```
 + diff -qr 'linux-build -d mtl' 'windows-build -d mtl'
Files linux-build -d mtl/build-sof-staging/sof-info/mtl/generated_configs.c and windows-build -d mtl/build-sof-staging/sof-info/mtl/generated_configs.c differ
```

**Comment by iuliana-prodan** [comment]
> @iuliana-prodan can you check, there seems to be still something left, I see two failures with IMX targets. Hopefully I picked the right patches.

From the error `/zep_workspace/sof/tools/rimage/config/imx.toml:	error: unable to open file for reading. No such file or directory (errno = 2)` seems [PR ](https://github.com/zephyrproject-rtos/zephyr/pull/69776) is missing. 
I see now that PR was merged.

**Comment by kv2019i** [comment]
@iuliana-prodan wrote:
> From the error `/zep_workspace/sof/tools/rimage/config/imx.toml: error: unable to open file for reading. No such file or directory (errno = 2)` seems [PR ](https://github.com/zephyrproject-rtos/zephyr/pull/69776) is missing. I see now that PR was merged.

You are right, thanks for checking! It seems our github checks do not work correctly when the remote is overridden. I can see the extra commits are fetched, but the actual test is still run with Zephyr main (and it fails):
https://github.com/thesofproject/sof/actions/runs/8184833177/job/22380013144?pr=8913
FYI @marc-hb 

Oh well, your patches is merged to Zephyr now, so I can update the PR using the merged commit.

**Comment by kv2019i** [comment]
Looking better but failure seen in https://sof-ci.01.org/sofpr/PR8913/build3197/devicetest/index.html 
This seems to be a SET_DX fail https://github.com/thesofproject/sof/issues/8642 ... a known issue with fixes in pipeline on Zephyr side.

**Comment by kv2019i** [comment]
V4:
- newer Zephyr to include fix for imx.toml fail
- drop the Zephyr branch, so we can remove the DNM tag

**Review by iuliana-prodan — APPROVED** [review]

**Review by dbaluta — APPROVED** [review]

**Comment by kv2019i** [comment]
ARM64 build is failing, seems PLATFORM definition is missing:
https://github.com/thesofproject/sof/actions/runs/8187912559/job/22389417387?pr=8913

The expected fails for Intel targets in https://sof-ci.01.org/sofpr/PR8913/build3203/devicetest/index.html

The fail in Internal Intel CI System/merge/build  is problematic as that's a required CI check, will investigate.

**Comment by kv2019i** [comment]
FYI @serhiy-katsyuba-intel this is a bit strange. The KD test is failing to (id 13685882):
```
[    0.198605] <inf> pipe: pipeline_trigger: pipe:2 0x0 pipe trigger cmd 7
[    0.198611] <inf> ll_schedule: zephyr_ll_task_schedule_common: task add 0xa01ceb80 0x20210U priority 0 flags 0x0
[    0.199401] <inf> host_comp: host_get_copy_bytes_normal: comp:2 0x10004 no bytes to copy, available samples: 0, free_samples: 384
[    0.200385] <inf> host_comp: host_get_copy_bytes_normal: comp:2 0x10004 no bytes to copy, available samples: 0, free_samples: 384
[    0.201386] <inf> host_comp: host_get_copy_bytes_normal: comp:2 0x10004 no bytes to copy, available samples: 0, free_samples: 384
```

This is with today's Zephyr main. This looks a lot like a case of https://github.com/thesofproject/sof/issues/8770 but why it's triggering herein the quickbuild test I have no idea.

**Comment by kv2019i** [comment]
V5:
- cherry-picked https://github.com/thesofproject/sof/pull/8918 for the 64bit build

**Comment by marc-hb** [comment]
> You are right, thanks for checking! It seems our github checks do not work correctly when the remote is overridden. I can see the extra commits are fetched, but the actual test is still run with Zephyr main (and it fails):
https://github.com/thesofproject/sof/actions/runs/8184833177/job/22380013144?pr=8913
FYI @marc-hb

This was run 1h and 6 minutes **before** @iuliana-prodan's Zephyr PR was merged so it looks good to me.



```
Thu, 07 Mar 2024 08:08:30 GMT === updating zephyr (zephyr):
Thu, 07 Mar 2024 08:08:30 GMT --- zephyr: fetching, need revision main
Thu, 07 Mar 2024 08:08:30 GMT From https://github.com/zephyrproject-rtos/zephyr
Thu, 07 Mar 2024 08:08:30 GMT  * branch                main       -> FETCH_HEAD
Thu, 07 Mar 2024 08:08:31 GMT  Warning: you are leaving 2 commits behind, not connected to
Thu, 07 Mar 2024 08:08:31 GMT any of your branches:
Thu, 07 Mar 2024 08:08:31 GMT
Thu, 07 Mar 2024 08:08:31 GMT  457476a12 boards: nxp: set correct rimage target for ADSP
Thu, 07 Mar 2024 08:08:31 GMT   5d6d2c19d Revert "pm: Remove CURRENT_CPU macro"

export TZ=UTC
git show --format=fuller 7a0398e65711

commit 7a0398e65711a980e4e3eec328754d4dd0a34adf
Author:     Iuliana Prodan <iuliana.prodan@nxp.com>
AuthorDate: Tue Mar 5 01:23:14 2024 +0200
Commit:     Alberto Escolar <alberto.escolar.piedras@nordicsemi.no>
CommitDate: Thu Mar 7 09:24:22 2024 +0100

    boards: nxp: set correct rimage target for ADSP
```

**Comment by marc-hb** [comment]
> Files linux-build -d mtl/build-sof-staging/sof-info/mtl/generated_configs.c
> and windows-build -d mtl/build-sof-staging/sof-info/mtl/generated_configs.c differ

generated_configs.c used to be in a deterministic order. It's not any more but the content is still the same. Someone probably started using a non-deterministic Python set, it's typical. I'll bisect and fix as usual.

As long as ONLY the `generated_configs.c` is different, then do not let that block this PR. The binaries are still identical which is what really matters.

Now racing to quickly fix this while other, much harder failures hold this for longer...

**Comment by kv2019i** [comment]
@wszypelt Can you check? The quickbuild run (13687837) failed again what seems to like result copying issue, and not the actual test case.

**Comment by kv2019i** [comment]
https://sof-ci.01.org/sofpr/PR8913/build3216/devicetest/index.html looks pretty bad. Submitted https://github.com/zephyrproject-rtos/zephyr/pull/69937 as it likes solving this (without revert) will take more time.

**Comment by wszypelt** [comment]
@kv2019i sure, There was a problem with the LNL testing machine, I've already added this PR to the queue. I think there will be new results within an hour

**Comment by kv2019i** [comment]
https://sof-ci.01.org/sofpr/PR8913/build3216/devicetest/index.html is not great, but we have to progress with the HWMv2 changes and the problem on MTL has to be fixed at the source (i.e. Zephyr upstream), so I'll proceed and merge this.

**Comment by marc-hb** [comment]
< https://sof-ci.01.org/sofpr/PR8913/build3216/devicetest/index.html is not great,

It's mostly red...

**Pull request merged**
