### PR TITLE
zephyr: move memory allocation code 1:1 from wrapper.c to alloc.c

### PR DESCRIPTION
**Pull request by marcinszkudlinski**
to have more order in the code - move memory code from a huge common wrapper.c to specific lib/alloc.c
Note there is NO changes in the code

Signed-off-by: Marcin Szkudlinski <marcin.szkudlinski@intel.com>

### CODE REVIEW

**Review by lgirdwood — APPROVED** [review]
Nice - we could probably split out wrapper.c into feature files and delete it soon.

**Comment by lgirdwood** [comment]
@marcinszkudlinski build issue
```
modules/sof/CMakeFiles/modules_sof.dir/lib/alloc.c.obj.d -o modules/sof/CMakeFiles/modules_sof.dir/lib/alloc.c.obj -c /zep_workspace/sof/zephyr/lib/alloc.c
In file included from /zep_workspace/sof/zephyr/include/sof/trace/trace.h:22,
                 from /zep_workspace/sof/zephyr/include/rtos/alloc.h:11,
                 from /zep_workspace/sof/zephyr/lib/alloc.c:8:
/zep_workspace/sof/zephyr/lib/alloc.c: In function 'rbrealloc_align':
/zep_workspace/sof/zephyr/lib/alloc.c:220:25: error: 'zephyr_tr' undeclared (first use in this function)
  220 |                 tr_err(&zephyr_tr, "realloc failed for 0 bytes");
      |                         ^~~~~~~~~
/zep_workspace/sof/zephyr/include/sof/trace/../../../../src/include/sof/trace/trace.h:283:52: note: in definition of macro '_log_message'
  283 |         _log_sofdict(log_func, atomic, &log_entry, ctx, lvl, id_1, id_2, \
      |                                                    ^~~
/zep_workspace/sof/zephyr/include/sof/trace/../../../../src/include/sof/trace/trace.h:355:9: note: in expansion of macro '_trace_error_with_ids'
  355 |         _trace_error_with_ids(class, ctx, id_1, id_2, format, ##__VA_ARGS__)
      |         ^~~~~~~~~~~~~~~~~~~~~
/zep_workspace/sof/zephyr/include/sof/trace/../../../../src/include/sof/trace/trace.h:[483](https://github.com/thesofproject/sof/actions/runs/3514311133/jobs/5888171068#step:5:484):9: note: in expansion of macro 'trace_error_with_ids'
  483 |         trace_error_with_ids(_TRACE_INV_CLASS, ctx, \
      |         ^~~~~~~~~~~~~~~~~~~~
/zep_workspace/sof/zephyr/lib/alloc.c:220:17: note: in expansion of macro 'tr_err'
  220 |                 tr_err(&zephyr_tr, "realloc failed for 0 bytes");
      |                 ^~~~~~
/zep_workspace/sof/zephyr/lib/alloc.c:220:25: note: each undeclared identifier is reported only once for each function it appears in
  220 |                 tr_err(&zephyr_tr, "realloc failed for 0 bytes");
      |                         ^~~~~~~~~
/zep_workspace/sof/zephyr/include/sof/trace/../../../../src/include/sof/trace/trace.h:283:52: note: in definition of macro '_log_message'
  283 |         _log_sofdict(log_func, atomic, &log_entry, ctx, lvl, id_1, id_2, \
      |                                                    ^~~
/zep_workspace/sof/zephyr/include/sof/trace/../../../../src/include/sof/trace/trace.h:355:9: note: in expansion of macro '_trace_error_with_ids'
  355 |         _trace_error_with_ids(class, ctx, id_1, id_2, format, ##__VA_ARGS__)
      |         ^~~~~~~~~~~~~~~~~~~~~
/zep_workspace/sof/zephyr/include/sof/trace/../../../../src/include/sof/trace/trace.h:483:9: note: in expansion of macro 'trace_error_with_ids'
  483 |         trace_error_with_ids(_TRACE_INV_CLASS, ctx, \
      |         ^~~~~~~~~~~~~~~~~~~~
/zep_workspace/sof/zephyr/lib/alloc.c:220:17: note: in expansion of macro 'tr_err'
  220 |                 tr_err(&zephyr_tr, "realloc failed for 0 bytes");
      |                 ^~~~~~
[180/295] Building C object modules/sof/CMakeFiles/modules_sof.dir/zep_workspace/sof/src/schedule/dma_single_chan_domain.c.obj
[181/295] Building C object modules/sof/CMakeFiles/modules_sof.dir/zep_workspace/sof/src/audio/data_blob.c.obj
ninja: build stopped: subcommand failed.
FATAL ERROR: command exited with status 1: /usr/local/bin/cmake --build /zep_workspace/build-apl
Traceback (most recent call last):
```

**Comment by marcinszkudlinski** [comment]
yeah, MTL is fine, looking why it fails for TGL. 
Question: are we going to drop other platforms? So why they're still in build check?

**Comment by lgirdwood** [comment]
> yeah, MTL is fine, looking why it fails for TGL. Question: are we going to drop other platforms (CNL? etc?) ? So why they're still in build check?

I think everyone was too busy on MTL / Zephyr / IPC4 work as P1. Should be doable soon.

**Comment by marcinszkudlinski** [comment]
changes in wrapper.c from 79a51819fc95028b7a6ddccd2803b97ae1cbf430 imported to alloc.c

**Comment by marcinszkudlinski** [comment]
TGL fixed, external access to trace zephyr_tr declared in wrapper.c added

**Pull request merged**
