### PR TITLE
[test] Verbose rimage run in windows

### PR DESCRIPTION
**Pull request by ktrzcinx**
Signed-off-by: Karol Trzcinski <karolx.trzcinski@linux.intel.com>

### CODE REVIEW

**Review by lgirdwood — COMMENTED** [review]
Commit message ?

**Comment by marc-hb** [comment]
Is this really specific to Windows?

**Comment by lgirdwood** [comment]
@ktrzcinx ping ?

**Comment by ktrzcinx** [comment]
Rimage run on windows platform ends up with failure on CI, I hope to get some clue after verbose run and it looks like this:

```
12:43:42,156 INFO  - sof-apl section-18:     type     0x00000001
12:43:42,156 INFO  - sof-apl section-18:     flags     0x00000003
12:43:42,234 INFO  - sof-apl section-18:     addr     0xbe043cdFAILED: src/arch/xtensa/CMakeFiles/run_rimage
12:43:42,234 INFO  - cmd.exe /C "cd /D D:\qba1\workspace\24733\SOF_FW\build_fw\src\arch\xtensa && D:\qba1\workspace\24733\SOF_FW\build_fw\rimage_ep\build\rimage -o sof-apl.ri -c D:/qba1/workspace/24733/SOF_FW/rimage/config/apl.toml -s 1088 -k D:/qba1/workspace/24733/SOF_FW/keys/otc_private_key.pem -i 3 -f 0.0 -b 1 -v bootloader-apl sof-apl"
12:43:42,234 INFO  - ninja: build stopped: subcommand failed.
```

But it didn't get me any idea, and I don't have valid toolchain setup for windows build to make more tests locally - I can't find a time for it :)

**Comment by marc-hb** [comment]
I missed the [test] tag and "draft" status, sorry.

> But it didn't get me any idea, and I don't have valid toolchain setup for windows build to make more tests locally - I can't find a time for it :)

Surely there are some developers who use Windows and CI is not the only Windows user!?

After "fixing" a few memory corruption crashes with asserts (!) it seems clear to me that rimage is really lacking input validation, which considering the use of an old and unsafe programming language like C is almost always leading to obscure crashes that always required valgrind or better. The verbose flag was worth a quick try but beyond that debugging through CI seems very inefficient and futile, I bet it can only go nowhere fast. This issue requires a Windows developer.

**Comment by marc-hb** [comment]
> Rimage run on windows platform ends up with failure on CI,

Is that Windows CI not reported on Github?

**Comment by ktrzcinx** [comment]
>Is that Windows CI not reported on Github?

As I know, rimage run on windows platform is performed, but possible fail here is ignored.


After updating rimage version, logs looks little less obscure:
```
13:04:31,074 INFO  - [220/224] SOF_FW\build_fw\rimage_ep\build\rimage -o sof-jsl.ri -c SOF_FW/rimage/config/jsl.toml -s 1088 -k SOF_FW/keys/otc_private_key.pem -i 3 -f 0.0 -b 1 -e bootloader-jsl sof-jsl"
13:04:31,093 WARN  -
13:04:31,093 WARN  - This application has requested the Runtime to terminate it in an unusual way.
13:04:31,093 WARN  - Please contact the application's support team for more information.
13:04:31,155 INFO  -
13:04:31,155 INFO  - Module Reading bootloader-jsl
13:04:31,155 INFO  - info: ignore .bss section for bootloader module
13:04:31,155 INFO  - Found 18 sections, listing valid sections......
13:04:31,155 INFO  -     No    LMA        VMA        End        Size    Type    Name
13:04:31,155 WARN  - error: segment TEXT [0xbe00c000:0xbefe1000] overlaps with DATA [0xbe03b000:0xbe05f000]
13:04:31,155 INFO  -     0    0x00000000    0x00000000    0x00000000    0x0
13:04:31,155 INFO  -     1    0xb0038000    0xb0038000    0xb00380fe    0xfe    TEXT    .boot_entry.text
13:04:31,155 WARN  - Assertion failed!
13:04:31,155 INFO  -     2    0xb0038120    0xb0038120    0xb0038140    0x20    TEXT    .boot_entry.literal
13:04:31,155 INFO  -     3    0xb0038150    0xb0038150    0xb0038c59    0xb09    TEXT    .text
13:04:31,155 WARN  -
13:04:31,155 INFO  -     4    0xb0039000    0xb0039000    0xb0039010    0x10    DATA    .rodata
13:04:31,155 INFO  -
13:04:31,155 WARN  - Program: D:\qba1\workspace\24733\SOF_FW\build_fw\rimage_ep\build\rimage.exe
13:04:31,155 INFO  - module: input size 3127 (0xc37) bytes 4 sections
13:04:31,155 INFO  - module: text 3111 (0xc27) bytes
13:04:31,155 INFO  - data 16 (0x10) bytes
13:04:31,155 INFO  - bss 0 (0x0) bytes
13:04:31,155 WARN  - File: D:/qba1/workspace/24733/SOF_FW/rimage/src/hash.c, Line 86
13:04:31,155 INFO  -
13:04:31,155 INFO  - Module Reading sof-jsl
13:04:31,155 WARN  -
13:04:31,155 INFO  - Found 39 sections, listing valid sections......
13:04:31,155 INFO  -     No    LMA        VMA        End        Size    Type    Name
13:04:31,155 WARN  - Expression: (uint64_t)size + offset <= image->adsp->image_size
```

**Comment by marc-hb** [comment]
I added this assert to "beautify" the rimage crash reported in  https://github.com/thesofproject/sof/issues/3423

**Review by lgirdwood — COMMENTED** [review]
@ktrzcinx ping ?

**Comment by marc-hb** [comment]
@lgirdwood this is a github draft, it's not meant to be reviewed unless you have a special interest in it. It also has a `[test]` tag in the subject.

Please do not waste your precious and limited maintainer time reviewing drafts. They appear with a grey icon in the lists and they can very easily be excluded with `draft:none`, example:
https://github.com/thesofproject/sof/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse

**Comment by ktrzcinx** [comment]
@lgirdwood it's exactly as @marc-hb said. I close this PR until there's no more ideas hot to fix it.

**Comment by lgirdwood** [comment]
Thank you for closing, I do have special interest in rimage hence the ping.

**Pull request closed without merging**
