### PR TITLE
build: disable asrc xcc defconfig for byt cht

### PR DESCRIPTION
**Pull request by xiulipan**
Need to disable asrc support for BYT and CHT for xcc build.

Signed-off-by: Pan Xiuli <xiuli.pan@linux.intel.com>

Fix missed change from https://github.com/thesofproject/sof/pull/1908 to https://github.com/thesofproject/sof/pull/2024 for xcc build

### CODE REVIEW

**Comment by jajanusz** [comment]
@singalsu @xiulipan Why is ASRC anyway 'yes' by default? Shouldn't we have just src+vol in default components and all other optional?

**Comment by xiulipan** [comment]
> @singalsu @xiulipan Why is ASRC anyway 'yes' by default? Shouldn't we have just src+vol in default components and all other optional?

@jajanusz Good point. @singalsu any idea here?

**Comment by singalsu** [comment]
In my view the idea has been in generic builds to enable everything by default (make sure the features do not break due to other development) and disable only features those are not feasible for a platform.

**Comment by singalsu** [comment]
@xiulipan Should the "CONFIG_COMP_ASRC=n" be done for HSW and BDW too? When I did the ASRC PR I didn't know that xcc build uses separate defconfig files.

**Comment by xiulipan** [comment]
@singalsu For bdw/hsw, they share the same defconfig.
But for BYT/CHT the xcc have special optimization level for the FW size issue.

**Comment by singalsu** [comment]
Thanks for explanation @xiulipan !

**Pull request merged**
