### PR TITLE
topology2: set sdw amp feedback pcm channel number

### PR DESCRIPTION
**Pull request by bardliao**
Assume an amplifier will provide 2 channels feedback.

Signed-off-by: Bard Liao <yung-chuan.liao@linux.intel.com>

### CODE REVIEW

**Review by lgirdwood — APPROVED** [review]

**Review by RanderWang — APPROVED** [review]

**Review by kv2019i — APPROVED** [review]
Seems good, but great if @plbossart can take a look before merge.

**Review by plbossart — APPROVED** [review]

**Review by ranj063 — APPROVED** [review]

**Comment by lgirdwood** [comment]
Rerun CI, looks like a test timeout. https://sof-ci.01.org/sofpr/PR6854/build3029/devicetest/index.html?model=TGLU_RVP_SDW_IPC4ZPH&testcase=check-playback-3times

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by bardliao** [comment]
SOFCI TEST

**Comment by bardliao** [comment]
@lgirdwood the new CI test result looks good now. https://sof-ci.01.org/sofpr/PR6854/build3261/devicetest/index.html

**Comment by bardliao** [comment]
@lgirdwood Can we merge this PR now?

**Pull request merged**
