### PR TITLE
probe: Convert to module API

### PR DESCRIPTION
**Pull request by jsarha**
This commit converts probe debug feature from component to module API.

With this PR the probes does not work without this fix in the Linux side: https://github.com/thesofproject/linux/pull/5221

So its maybe better to wait a bit before merging this? Or what do you say @lgirdwood ?

### CODE REVIEW

**Comment by lgirdwood** [comment]
> This commit converts probe debug feature from component to module API.
> 
> With this PR the probes does not work without this fix in the Linux side: [thesofproject/linux#5221](https://github.com/thesofproject/linux/pull/5221)
> 
> So its maybe better to wait a bit before merging this? Or what do you say @lgirdwood ?

@jsarha kernel fix now merged - pls convert to non draft if ready. Btw, do we need any tooling changes ?

**Comment by jsarha** [comment]
> > This commit converts probe debug feature from component to module API.
> > With this PR the probes does not work without this fix in the Linux side: [thesofproject/linux#5221](https://github.com/thesofproject/linux/pull/5221)
> > So its maybe better to wait a bit before merging this? Or what do you say @lgirdwood ?
> 
> @jsarha kernel fix now merged - pls convert to non draft if ready. Btw, do we need any tooling changes ?

Nope, the functionality has not changed.

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
@jsarha can you check CI build results. Breaking Zephyr configs.

**Review by kv2019i — COMMENTED** [review]
Looks good. Some build errors that need to get address before merge, but no blockers otherwise.

**Comment by jsarha** [comment]
> Looks good. Some build errors that need to get address before merge, but no blockers otherwise.

The unused variable warning is now fixed, so compile test should be Ok. There is still some device test failures that hardly have anything to do with this PR (the probes are not used in CI tests AFAIK).

**Comment by kv2019i** [comment]
sof-docs fail and Intel LNL fails all known and tracked in https://github.com/thesofproject/sof/issues?q=is%3Aissue+is%3Aopen+label%3ACI

**Review by kv2019i — APPROVED** [review]

**Pull request merged**
