### PR TITLE
Update rimage to a version, that doesn't need Zephyr ELF mangling

### PR DESCRIPTION
**Pull request by lyakh**
Upgrade rimage but keep Zephyr for now

### CODE REVIEW

**Comment by lyakh** [comment]
Both https://sof-ci.01.org/sofpr/PR7250/build4899/devicetest and https://sof-ci.01.org/sofpr/PR7250/build4900/devicetest failed some suspend-resume tests

**Review by kv2019i — APPROVED** [review]
Given this also works with current manifest-rev of Zephyr in SOF, I see no reason why not to upgrade.

**Review by lgirdwood — APPROVED** [review]

**Comment by kv2019i** [comment]
D'oh, I think we missed the rimage submodule :( @lyakh @marc-hb @lgirdwood  @lyakh Can you do a follow-up?

**Comment by lyakh** [comment]
> D'oh, I think we missed the rimage submodule :( @lyakh @marc-hb @lgirdwood @lyakh Can you do a follow-up?
> 
> EDIT: done in #7316

arrgh, forgot it again, sorry :-( Thanks for fixing!

**Pull request merged**
