### PR TITLE
zephyr/cmake: fix llext.uuid growing from the last build

### PR DESCRIPTION
**Pull request by marc-hb**
3 small LLEXT fixes. Main one:

Reset the llext.uuid file so it does not start with content from the
previous build.

Fixes incremental builds.

### CODE REVIEW

**Comment by marc-hb** [comment]
- Only 1 suspend/resume failure in https://sof-ci.01.org/sofpr/PR9159/build4833/devicetest/index.html

- Known LNL failures in https://sof-ci.01.org/sofpr/PR9159/build4831/devicetest/index.html

- Unrelated LNL error in https://sof-ci.01.org/sof-pr-viewer/#/build/PR9159/build13991832 
MTL passed.
```

19:43:42,018 INFO  - INTERNALERROR> File "/usr/local/lib/python3.12/dist-packages/execnet/gateway_socket.py", line 92, in create_io
19:43:42,018 INFO  - INTERNALERROR> sock.connect((host, port))
19:43:42,018 INFO  - INTERNALERROR> ConnectionRefusedError: [Errno 111] Connection refused
```

**Review by lyakh — APPROVED** [review]
thanks for fixing my crude file-removal code ;-)

**Review by kv2019i — APPROVED** [review]

**Comment by kv2019i** [comment]
Pending pass from mandatory CI jobs, otherwise good to go.

**Comment by marc-hb** [comment]
> Pending pass from mandatory CI jobs, otherwise good to go.

@wszypelt , @lrudyX can you please re-run https://sof-ci.01.org/sof-pr-viewer/#/build/PR9159/build13991832 where LNL failed with unrelated "connection refused"? This PR should not affect these tests in any way.

**Comment by wszypelt** [comment]
@marc-hb all green :)

**Pull request merged**
