### PR TITLE
backport installer/ to stable-v1.7

### PR DESCRIPTION
**Pull request by marc-hb**
Straight cherry-pick -x, no conflict.

### CODE REVIEW

**Comment by marc-hb** [comment]
https://sof-ci.01.org/sof-pr-viewer/#/build/PR3925/build6158955 fails to build CNL, ICL and TGL because it tries do apply changes that are clearly compatible only with the current `master` branch and not with the older `stable-v1.7`:
```shell
rm -fr override.config
echo "CONFIG_COMP_CODEC_ADAPTER=y" >> override.config
echo "CONFIG_CADENCE_CODEC=y" >> override.config
echo "CONFIG_CADENCE_CODEC_WRAPPER=y" >> override.config
make overrideconfig
make bin -j8 VERBOSE=1 |& tee -a CMakeFiles/stdout.log
cp generated/.config config
Command return code: 2
Command error output: error: patch failed: src/audio/codec_adapter/codec/cadence.c:21
error: src/audio/codec_adapter/codec/cadence.c: patch does not apply
error: patch failed: src/include/sof/audio/codec_adapter/codec/cadence.h:20
error: src/include/sof/audio/codec_adapter/codec/cadence.h: patch does not apply
```

These CONFIG_ were added in commit 9fcfd751c9, after branching 1.7

**Comment by marc-hb** [comment]
https://sof-ci.01.org/sofpr/PR3925/build8314/devicetest/?model=BYT_MB_NOCODEC&testcase=check-alsabat-headset-playback fails like this. I don't know what to think of it.
```
2021-03-11 22:29:12 UTC [REMOTE_INFO] check the PCMs before alsabat test
2021-03-11 22:29:14 UTC [REMOTE_COMMAND] alsabat -Phw:sofnocodec,0 --standalone -n 240000 -r 48000 -c 2 -F 997
2021-03-11 22:29:15 UTC [REMOTE_COMMAND] alsabat -Chw:sofnocodec,0 -c 2 -r 48000 -F 997
WARNING: Signal overflow!
 FAIL: Peak freq too high 2991.21 Hz
 FAIL: Peak freq too high 6979.25 Hz
...
Channel 1 - Checking for target frequency 997.00 Hz
Amplitude: 37014.4; Percentage: [112]
Detected peak at 996.83 Hz of 37.48 dB
 Total 41.1 dB from 990.97 to 1004.88 Hz
 PASS: Peak detected at target frequency
Detected peak at 2991.21 Hz of 28.81 dB
 Total 41.5 dB from 2989.75 to 2991.21 Hz
Detected peak at 6979.25 Hz of 20.72 dB
 Total 41.5 dB from 6979.25 to 6979.25 Hz
Detected at least 3 signal(s) in total

Return value is -1003
```

**Comment by marc-hb** [comment]
https://sof-ci.01.org/sofpr/PR3925/build8314/devicetest/?model=BDW_WSB_RT286&testcase=multiple-pipeline-playback failed like this. Maybe #3462?
```
2021-03-11 22:24:24 UTC [REMOTE_INFO] /home/ubuntu/sof-test/test-case/multiple-pipeline.sh will use topology /lib/firmware/intel/sof-tplg/sof-bdw-rt286.tplg to run the test case
2021-03-11 22:24:24 UTC [REMOTE_INFO] Pipeline list to ignore is specified, will ignore 'pcm=HDA Digital' in test case
2021-03-11 22:24:24 UTC [REMOTE_INFO] Run command to get pipeline parameters
2021-03-11 22:24:24 UTC [REMOTE_COMMAND] sof-tplgreader.py /lib/firmware/intel/sof-tplg/sof-bdw-rt286.tplg -f 'type:capture' -b ' pcm:HDA Digital' -s 0 -e
2021-03-11 22:24:24 UTC [REMOTE_INFO] Testing: Low Latency [hw:0,0]
2021-03-11 22:24:24 UTC [REMOTE_COMMAND] arecord   -D hw:0,0 -c 2 -r 48000 -f S16_LE /dev/null -q
2021-03-11 22:24:24 UTC [REMOTE_INFO] sleep 5s for sound device wakeup
aplay: pcm_write:2061: write error: Input/output error
aplay: pcm_write:2061: write error: Input/output error
2021-03-11 22:24:29 UTC [REMOTE_INFO] checking pipeline status
2021-03-11 22:24:29 UTC [REMOTE_ERROR] Running process count is 1, but 3 is expected
6870 arecord -D hw:0,0 -c 2 -r 48000 -f S16_LE /dev/null -q
```

**Comment by marc-hb** [comment]
This PR changes build scripts only so it can't be causing the failures above. Everything else is green.

**Review by aiChaoSONG — APPROVED** [review]

**Review by dbaluta — APPROVED** [review]

**Comment by lgirdwood** [comment]
@zrombel any comment here ? The build is working on Jenkins so are we missing anything for internal CI here ?

**Comment by marc-hb** [comment]
> @zrombel any comment here ? The build is working on Jenkins so are we missing anything for internal CI here ?

As I described above, @zrombel has confirmed that QB tries to make some unversioned, master-specific changes on the fly before building and does not know it does not support branches.

Other failures are clearly unrelated.

**Pull request merged**
