### PR TITLE
github: add xiulipan as some field owner

### PR DESCRIPTION
**Pull request by xiulipan**
Add some field owner and have some structure for CODEOWNER.

[skip ci]

### CODE REVIEW

**Comment by xiulipan** [comment]
@keyonjie @RanderWang @bardliao @zhuyingjiang @libinyang 
You can follow this PR to assin yourselves as owner.
PS: You can use `skip ci` to skip the ci tests

**Comment by jajanusz** [comment]
> PS: You can use `skip ci` to skip the ci tests

Does it always have to be last line? Let's say I write in the middle of commit message `you should not skip ci on this PR`, will it skip Ci or not?

**Comment by xiulipan** [comment]
@jajanusz 
I test the and find the correct magic word is `[skip ci]` in the commit message for both all CIs.
`[skip ci]github: add xiulipan as some field owner`

**Comment by xiulipan** [comment]
@jajanusz 
https://github.com/orgs/thesofproject/teams/sof-developers/discussions/4
Here are the summary for all tiggers to CIs

**Pull request merged**
