### PR TITLE
tools: moving rimage and logger to tools directory

### PR DESCRIPTION
**Pull request by bkokoszx**
I've moved rimage and logger (from soft repo) to tools
directory. Cmds for building tools:
./autogen.sh
./configure --enable-tools
make
sudo make install

Signed-off-by: Bartosz Kokoszko <bartoszx.kokoszko@linux.intel.com>

### CODE REVIEW

**Comment by bkokoszx** [comment]
CI fails because of changing ./configure --enable-rimage to ./configure --enable-tools.

**Comment by lgirdwood** [comment]
@bkokoszx, Ok, will merge it tonight so that @xiulipan can update CI.

**Comment by cujomalainey** [comment]
I was going to do the merge this weekend, this will preserve this history of the files if that is of importance

**Comment by lgirdwood** [comment]
@cujomalainey ok, if you are good to go we can take your PR over the weekend otherwise we can merge this one on Monday and forget the history. @bkokoszx  this OK with you ?

**Comment by xiulipan** [comment]
@bkokoszx 
Please update the `scripts/xtensa-build-all.sh` and `scripts/rimage-build.sh`
@lgirdwood 
The CI did not call the configure directly, update the scripts will automatic fix the issues.

**Comment by bkokoszx** [comment]
@lgirdwood @cujomalainey 
Ok, no problem. We can wait until Monday

**Comment by bkokoszx** [comment]
@lgirdwood @xiulipan 
I've updated CI scripts.

**Comment by xiulipan** [comment]
@jajanusz 
good idea, can we duplicate one `tools-build.sh` at first. And after we solve the CI dependency issue, I will remove the old one in the CI update PR.

**Comment by bkokoszx** [comment]
@jajanusz @xiulipan 
I've added `tools-build.sh`

**Comment by bkokoszx** [comment]
Do you mean only makefile changes and build script without logger in tools directory?

**Comment by bkokoszx** [comment]
https://github.com/thesofproject/sof/pull/624 was merged.

I close this PR.

**Comment by xiulipan** [comment]
@bkokoszx 
will we later move rimage into tools?

**Pull request closed without merging**
