### PR TITLE
Fix cavs-gain-hda topology

### PR DESCRIPTION
**Pull request by ranj063**

### CODE REVIEW

**Comment by RanderWang** [comment]
Tested error on TGL HDA
[   20.523637]  HDA Analog: ASoC: prepare FE HDA Analog
[   20.523641]  HDA Analog: ASoC: no backend DAIs enabled for HDA Analog
[   20.523647]  HDA Analog: ASoC: dpcm_fe_dai_prepare() failed (-22)
[   20.523736]  HDA Analog: ASoC: hw_free FE HDA Analog

**Comment by plbossart** [comment]
@ranj063 how are the topology 2.0 files tested by CI, if at all?

**Comment by ranj063** [comment]
> @ranj063 how are the topology 2.0 files tested by CI, if at all?

Not yet @plbossart. We need to update alsautils in CI with my PR before I add build support

**Comment by ranj063** [comment]
> no backend DAIs enabled for HDA Analog

@RanderWang can you please check with the new changes?

**Comment by RanderWang** [comment]
@ranj063 I can't build it since you delete header file include.

**Comment by ranj063** [comment]
> @ranj063 I can't build it since you delete header file include in [d9c191c](https://github.com/thesofproject/sof/commit/d9c191c63855947f910f6aac4ff8747de187815c)

@RanderWang you have to build cavs-gain.conf not cavs-gain-hda.conf. And please use my PR 117 from alsautils

**Comment by RanderWang** [comment]
> > @ranj063 I can't build it since you delete header file include in [d9c191c](https://github.com/thesofproject/sof/commit/d9c191c63855947f910f6aac4ff8747de187815c)
> 
> @RanderWang you have to build cavs-gain.conf not cavs-gain-hda.conf. And please use my PR 117 from alsautils
> 
> The command would be:
> 
> alsatplg -p -c cavs-gain.conf -o cavs-gain-hda.tplg or for HDMI only
> 
> alsatplg -D HDMI_ONLY=1 cavs-gains.conf -0 cavs-gain-hdmi.tplg

Can you help to share the link for PR117 ?  I only tested HDMI

**Comment by ranj063** [comment]
> Can you help to share the link for PR117 ? I only tested HDMI

https://github.com/alsa-project/alsa-utils/pull/117

**Comment by RanderWang** [comment]
I still get error. please check my processed config file. No BE for HDA Analog. I used your alsatplg
````
[  131.144184]  HDA Analog: ASoC: prepare FE HDA Analog
[  131.144185]  HDA Analog: ASoC: no backend DAIs enabled for HDA Analog
[  131.144188]  HDA Analog: ASoC: dpcm_fe_dai_prepare() failed (-22)
[  131.144232]  HDA Analog: ASoC: hw_free FE HDA Analog

```
[g.txt](https://github.com/thesofproject/sof/files/7562912/g.txt)
`

**Comment by plbossart** [comment]
> > I still get error. please check my processed config file. No BE for HDA Analog. I used your alsatplg
> > ```
> > [  131.144184]  HDA Analog: ASoC: prepare FE HDA Analog
> > [  131.144185]  HDA Analog: ASoC: no backend DAIs enabled for HDA Analog
> > [  131.144188]  HDA Analog: ASoC: dpcm_fe_dai_prepare() failed (-22)
> > [  131.144232]  HDA Analog: ASoC: hw_free FE HDA Analog
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [g.txt](https://github.com/thesofproject/sof/files/7562912/g.txt)
> 
> @RanderWang do you need to set a mixer control maybe?

yes that's a clear message that you need to use alsamixer to move some mixer from 'm' to 'oo'

**Comment by ranj063** [comment]
> I still get error. please check my processed config file. No BE for HDA Analog. I used your alsatplg
> 
> ```
> [  131.144184]  HDA Analog: ASoC: prepare FE HDA Analog
> [  131.144185]  HDA Analog: ASoC: no backend DAIs enabled for HDA Analog
> [  131.144188]  HDA Analog: ASoC: dpcm_fe_dai_prepare() failed (-22)
> [  131.144232]  HDA Analog: ASoC: hw_free FE HDA Analog
> ```
> 
> [g.txt](https://github.com/thesofproject/sof/files/7562912/g.txt)

@RanderWang Im not sure how you're building this. The attached config file only has the pipelines, DAI and pcm's for HDMI. You shouldnt even be seeing the HDA Analog option

**Comment by RanderWang** [comment]
> > I still get error. please check my processed config file. No BE for HDA Analog. I used your alsatplg
> > ```
> > [  131.144184]  HDA Analog: ASoC: prepare FE HDA Analog
> > [  131.144185]  HDA Analog: ASoC: no backend DAIs enabled for HDA Analog
> > [  131.144188]  HDA Analog: ASoC: dpcm_fe_dai_prepare() failed (-22)
> > [  131.144232]  HDA Analog: ASoC: hw_free FE HDA Analog
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [g.txt](https://github.com/thesofproject/sof/files/7562912/g.txt)
> 
> @RanderWang Im not sure how you're building this. The attached config file only has the pipelines, DAI and pcm's for HDMI. You shouldnt even be seeing the HDA Analog option

alsatplg -p -c cavs_gain.conf -o gain.tplg

**Comment by RanderWang** [comment]
@ranj063  for your reference about CPC in real case. The default value is 5000, and the following CPC are adjusted by some algorithm
````
CopierModule BS=384 BS=384 CPC=3146 CPS=3146000 sByes=0.
PeakVolModule BS=384 BS=384 CPC=7572 CPS=7572000 sByes=0.
MixModule BS=384 BS=384 CPC=2964 CPS=2964000 sByes=0.
MixuModule BS=384 BS=384 CPC=4202 CPS=4202000 sByes=0.
PeakVolModule BS=384 BS=384 CPC=7572 CPS=7572000 sByes=0. 
CopierModule BS=384 BS=384 CPC=2213 CPS=2213000 sByes=0.
CopierModule BS=384 BS=384 CPC=5000 CPS=5000000 sByes=0.
````

**Review by bardliao — APPROVED** [review]
I tested all of them and all work on my side.

**Review by RanderWang — APPROVED** [review]

**Pull request merged**
