### PR TITLE
ipc4: use IMR_BOOT_LDR_MANIFEST_BASE definition from adsp_memory.h

### PR DESCRIPTION
**Pull request by kv2019i**
Start migrating to use Zephyr definitions for the memory layout. As we cannot move all users of legacy memory.h, selectively mark the definitions that have already moved to make.

Signed-off-by: Kai Vehmanen <kai.vehmanen@linux.intel.com>

### CODE REVIEW

**Comment by kv2019i** [comment]
@marcinszkudlinski This is overlapping with your https://github.com/thesofproject/sof/pull/6613/ , so if you are quick with that, we can just go ahead and merge that. But here's just the build fixes in a separate PR.

**Review by juimonen — APPROVED** [review]
lgtm. and removes the warning from mtl build.

**Review by marcinszkudlinski — APPROVED** [review]
proceed with this, warnings are really annoying
my PR need to wait for build system changes

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
@kv2019i looks like one config needs a fix
```
[ 35%] Building C object CMakeFiles/sof.dir/src/ipc/ipc4/helper.c.o
/home/sof/work/xtensa-cnl-elf/bin/xtensa-cnl-elf-gcc -DBLD_COUNTERS=0 -DRELATIVE_FILE=\"src/ipc/ipc4/helper.c\" -I/home/sof/work/sof.git/src/platform/intel/cavs/include -I/home/sof/work/sof.git/src/arch/xtensa/include -I/home/sof/work/sof.git/src/arch/xtensa/xtos -I/home/sof/work/sof.git/xtos/include -I/home/sof/work/sof.git/src/platform/tigerlake/include -I/home/sof/work/sof.git/src/platform/tigerlake/include/arch -I/home/sof/work/sof.git/../xtensa-root/xtensa-cnl-elf/include -I/home/sof/work/sof.git/rimage/src/include -I/home/sof/work/sof.git/src/include -I/home/sof/work/sof.git/installer-builds/build_tgl_gcc/generated/include -I/home/sof/work/sof.git/third_party_include  -nostdlib -fno-inline-functions -mlongcalls -O2 -g -Wall -Werror -Wl,-EL -Wmissing-prototypes -Wpointer-arith -mtext-section-literals -imacros/home/sof/work/sof.git/installer-builds/build_tgl_gcc/generated/include/autoconfig.h -o CMakeFiles/sof.dir/src/ipc/ipc4/helper.c.o   -c /home/sof/work/sof.git/src/ipc/ipc4/helper.c
/home/sof/work/sof.git/src/ipc/ipc4/helper.c:22:10: fatal error: adsp_memory.h: No such file or directory
   22 | #include <adsp_memory.h> /* for IMR_BOOT_LDR_MANIFEST_BASE */
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [CMakeFiles/sof.dir/build.make:330: CMakeFiles/sof.dir/src/ipc/ipc4/helper.c.o] Error 1
make[3]: *** [CMakeFiles/Makefile2:1335: CMakeFiles/sof.dir/all] Error 2
make[2]: *** [CMakeFiles/Makefile2:2866: src/arch/xtensa/CMakeFiles/bin.dir/rule] Error 2
make[1]: *** [Makefile:957: bin] Error 2
make: *** [GNUmakefile:203: /home/sof/work/sof.git/installer/../installer-builds/build_tgl_gcc/sof.ri] Error 2
make: Leaving directory '/home/sof/work/sof.git/installer'
Error: Process completed with exit code 2.

```

**Review by tmleman — APPROVED** [review]

**Comment by kv2019i** [comment]
CI checks ok, proceeding with merge.

**Pull request merged**
