### PR TITLE
zephyr: fix issues with init.h include

### PR DESCRIPTION
**Pull request by gmarull**

### CODE REVIEW

**Comment by sofci** [comment]
Can one of the admins verify this patch?
> reply **test&nbsp;this&nbsp;please** to run this test once

**Review by dabekjakub — APPROVED** [review]

**Review by kv2019i — APPROVED** [review]
Thanks @gmarull !

**Review by lyakh — APPROVED** [review]

**Comment by marc-hb** [comment]
Thanks!

Sparse error in https://github.com/thesofproject/sof/actions/runs/6082149977/job/16499306627?pr=8154 is known and should be fixed by #8147

**Comment by marc-hb** [comment]
SOFCI TEST

**Review by btian1 — APPROVED** [review]

**Comment by marc-hb** [comment]
test this please

**Comment by kv2019i** [comment]
@wszypelt  This seems to got stuck, can you check?

**Comment by wszypelt** [comment]
@kv2019i Sure thing, the PR is already in the queue to be done, I think the results will be in an hour

**Pull request merged**
