### PR TITLE
app: intel_adsp_ace15_mtpm.conf: clean up board config file

### PR DESCRIPTION
**Pull request by kv2019i**
Group the configuration options per theme and order entries in alphabetical order within each group. This makes the board config file much more readable and easy to maintain.

No functional change, just shuffling options around and adding comments. Probably easier to review the resulting file without any diffs:
https://github.com/thesofproject/sof/tree/9996a21a04f617ce1b4517167aa33b67b25533c2/app/boards/intel_adsp_ace15_mtpm.conf

### CODE REVIEW

**Comment by kv2019i** [comment]
If this seems good, I can do the same for other Intel board files.

**Review by lgirdwood — APPROVED** [review]

**Review by lyakh — APPROVED** [review]
Thanks for doing this! Haven't checked every single line of course (can be easily done automatically by sorting and diffing the two versions), but, assuming there are no changes, this is a welcome change!

**Review by abonislawski — APPROVED** [review]

**Review by tmleman — APPROVED** [review]
Thanks for doing a great job. I wanted to do it myself and have it on my to-do list. When I thought about it earlier, I also thought that it would be a good idea to separate the configs coming from Zephyr from those that are purely SOF (but I'm not sure if that would be better).

**Comment by kv2019i** [comment]
@tmleman wrote:
> Thanks for doing a great job. I wanted to do it myself and have it on my to-do list. When I thought about it earlier, I also > thought that it would be a good idea to separate the configs coming from Zephyr from those that are purely SOF (but 

Thanks Tomasz for feedback! Some of the Zephyr/non-zephyr split is already done as the audio pipeline/component part of the options is by definition SOF-side settings. Then we have a bit more unclear parts like debug and logging where we have SOF and Zephyr settings around the same topic, but maybe there's not too many. Let's do so that I'll have a go at this when I make the LNL version (early next week). If that (clear Zephyr option split) looks better, then I can return to MTL and align it as well before converting the others.

**Pull request merged**
