### PR TITLE
rimage: Style fixes to make code more readable

### PR DESCRIPTION
**Pull request by DianaGabriela27**
This series tries to make checkpatch.pl happy and also it makes the coding style more consistent.

### CODE REVIEW

**Comment by jajanusz** [comment]
Code itself is ok, but you should associate your e-mail with github account, so github will be able to link every your commit to (instead just pull request)

**Comment by dbaluta** [comment]
@jajanusz  thanks for the comments. @DianaGabriela27 go to upper-right corner -> Settings  -> Email -> Add email account. Then you will receive an email and you will need to confirm this association.

@jajanusz should we resend?

**Comment by jajanusz** [comment]
> @jajanusz should we resend?

Resend what? Do you mean force push branch for some kind of update trigger? I think that changing it in profile settings may be enough, if not then you can amend commit

**Comment by dbaluta** [comment]
> > @jajanusz should we resend?
> 
> Resend what? Do you mean force push branch for some kind of update trigger? I think that changing it in profile settings may be enough, if not then you can amend commit

Ok, I understand. Exactly force push branch to update some kind of trigger. But, I think just adding the email to github account should be fine. Thanks!

**Comment by DianaGabriela27** [comment]
@jajanusz @dbaluta I've added the email to my github account. It should be fine now

**Comment by plbossart** [comment]
Thanks @DianaGabriela27

**Pull request merged**
