### PR TITLE
topology: add echo reference to sof-tgl-rt711-rt1308

### PR DESCRIPTION
**Pull request by xiulipan**
Add echo reference with demux into sof-tgl-rt711-rt1308 for
TGL SDW platforms.

For SDW ALH dai, use existing headset BE dai for the echo reference
virtual dai used for DAPM.

Signed-off-by: Pan Xiuli <xiuli.pan@linux.intel.com>

### CODE REVIEW

**Comment by xiulipan** [comment]
@keqiaozhang @ClarexZhou Please help to verify the echo reference on TGL SDW platforms.
```
aplay -Dhw:0,2 MUSIC.wav -vvv
arecord -Dhw:0,9 -f s32_le -r 48000 -c 2 /dev/null -vvv
```

**Comment by plbossart** [comment]
@xiulipan why is this necessary or what are you trying to enable? Why do this only for TGL? I just don't get the story here.

**Comment by xiulipan** [comment]
@lgirdwood I will check the buffer cap setting.
@plbossart We would like to test the echo reference feature on more TGL platforms for release validation.

**Comment by plbossart** [comment]
> @lgirdwood I will check the buffer cap setting.
> @plbossart We would like to test the echo reference feature on more TGL platforms for release validation.

can you clarify for me where the echo reference comes from? is this extracted from the stream being played on amplifiers, or is this coming from the amplifiers.

**Comment by Liviali155** [comment]
Test on TGL SDW RVP,echo reference  can work normally

**Comment by plbossart** [comment]
> > @lgirdwood I will check the buffer cap setting.
> > @plbossart We would like to test the echo reference feature on more TGL platforms for release validation.
> 
> can you clarify for me where the echo reference comes from? is this extracted from the stream being played on amplifiers, or is this coming from the amplifiers.

@xiulipan ping?

**Comment by xiulipan** [comment]
@plbossart The echo reference is this extracted from the stream being played on amplifiers. No related with BE dai.

**Comment by lgirdwood** [comment]
@xiulipan are you saying the PR is complete or are there more changes or tests pending ?

**Pull request closed without merging**
