### PR TITLE
pipeline: split pipeline up by function.

### PR DESCRIPTION
**Pull request by lgirdwood**
Split the pipeline logic up into stream, params, graph, scheduling and xrun
so that it easier to follow and understand. This is to help on the TSC work
to integrate the codec adaptor into core logic.

This PR is all mechanical code moves. There are NO functional changes. Some
function that were static are now public.

Followup patches will add more documentation updates alongside.

Signed-off-by: Liam Girdwood <liam.r.girdwood@linux.intel.com>

### CODE REVIEW

**Review by dbaluta — APPROVED** [review]

**Comment by lgirdwood** [comment]
@dbaluta @cujomalainey fyi more cleanup, still more to come from TSC codec work to sit on top of.

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by cujomalainey** [comment]
random question, do we still use src/audio/pipeline_static.c or can we remove that?

**Comment by cujomalainey** [comment]
> random question, do we still use src/audio/pipeline_static.c or can we remove that?

ignore me, somehow missed it in the diff

**Comment by cujomalainey** [comment]
I'm guessing error logic is WIP? I don't see any walkback code on error yet

**Comment by lgirdwood** [comment]
> I'm guessing error logic is WIP? I don't see any walkback code on error yet

Yes, this PR has no functional changes so it's the same logic we have today.

**Comment by dbaluta** [comment]
@lgirdwood I would have kept pipeline_static as in the future we might want to have it as an example on how to run SOF with a Host core. 

So, SOF will run independently on a micro-controller

**Comment by lgirdwood** [comment]
> @lgirdwood I would have kept pipeline_static as in the future we might want to have it as an example on how to run SOF with a Host core.
> 
> So, SOF will run independently on a micro-controller

The best way to do this is by stitching in a topology binary blob to the FW image and parsing this as IPC messages. That way we can use exosting topologies and have a Kconfig option "Built in Topology File". Hard coding this as C would be time consuming and mean two different topology methods.

**Comment by dbaluta** [comment]
@lgirdwood I see. Good point.

**Comment by cujomalainey** [comment]
that is why we have the tplg_parser correct?

**Comment by marc-hb** [comment]
SOFCI TEST

**Pull request merged**
