### PR TITLE
platform: remove support for Broadwell and Haswell

### PR DESCRIPTION
**Pull request by lyakh**
Remove all support for Broadwell and Haswell platforms, they aren't supported any more.

### CODE REVIEW

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
@lyakh can you check the failures, not expecting unrelated platforms to fail.

**Review by RanderWang — APPROVED** [review]

**Comment by lyakh** [comment]
> @lyakh can you check the failures, not expecting unrelated platforms to fail.

@lgirdwood none related. qemu icl / cnl failures are a known regression from a couple of days ago, waiting for icl and cnl to be removed, device test failure https://sof-ci.01.org/sofpr/PR7080/build3882/devicetest/index.html is one of the known bugs, quickbuild also looks unrelated although there it's much more difficult to parse... But at least we see QB failures in multiple unrelated PRs

**Review by kv2019i — APPROVED** [review]

**Comment by lgirdwood** [comment]
@wszypelt looks like the DUT could be playing up again as we expect this PR is unrelated to current tests.

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by wszypelt** [comment]
@lgirdwood all green

**Pull request merged**
