### PR TITLE
smart amp: Update smart amp test changes to maxim dsm component.

### PR DESCRIPTION
**Pull request by ryans-lee**
There have been several patches applied to [smart_amp_test.c](https://github.com/thesofproject/sof/blob/master/src/audio/smart_amp_test.c) which is smart amp reference code.

Applied same changes to smart_amp.c[](https://github.com/thesofproject/sof/blob/master/src/audio/smart_amp/smart_amp.c)
which is for Maxim DSM(Dynamic Speaker Management) component.

### CODE REVIEW

**Review by lgirdwood — APPROVED** [review]
@RDharageswari @keyonjie any comments ?

**Comment by RDharageswari** [comment]
@lgirdwood: I am testing the patches

**Comment by lgirdwood** [comment]
@RDharageswari thanks, we will get the fixes in v1.6

**Comment by lgirdwood** [comment]
@RDharageswari any update ?

**Comment by RDharageswari** [comment]
@lgirdwood, I am facing issues with these patches. Debugging WIP.

**Comment by lgirdwood** [comment]
@bkokoszx @jdrzaszcz fyi

**Comment by ryans-lee** [comment]
@RDharageswari Could you please specify the issues you discover?

**Comment by RDharageswari** [comment]
Hi Ryan,
It is the S24_LE issue that we are debugging right now. 
I believe we can hold the patches, till we get into conclusion on the issue.
S24_LE hw_params failure issue/ capturing 0 data. It could be the issue with smart_amp_test component also.
Lets have the right fix in.

**Comment by lgirdwood** [comment]
@RDharageswari any update ? Would like to merge these for v1.6

**Comment by RDharageswari** [comment]
Hi Liam,
Sorry for being late on this.
I was lost in the debug of context save ipc failure with dsm library.
i will verify these patches early tomorrow and update.
Hope its ok!

**Comment by lgirdwood** [comment]
@RDharageswari thanks, tomorrow is good

**Comment by RDharageswari** [comment]
Hi Liam,
Looks good to me, verified on my set up.

**Comment by lgirdwood** [comment]
@RDharageswari thanks and appreciated.
CI for ICL is a test start timeout for unrelated test.

**Pull request merged**
