### PR TITLE
cached buffer: part one of #5976

### PR DESCRIPTION
**Pull request by lyakh**
#5976 fails several tests on 2 devices, let's test the first 9 commits from that PR. These commits shouldn't break anything.

### CODE REVIEW

**Comment by lyakh** [comment]
A CI run https://sof-ci.01.org/sofpr/PR6027/build920/devicetest/ ended with 3 suspend-resume failures, which I presume are unrelated.

**Comment by lyakh** [comment]
2 multiple pause-resume CI failures with Zephyr HDA configurations: https://sof-ci.01.org/sofpr/PR6027/build921/devicetest/?model=WHL_UPEXT_HDA_ZEPHYR&testcase=multiple-pause-resume-5 and https://sof-ci.01.org/sofpr/PR6027/build921/devicetest/?model=TGLU_UP_HDA_ZEPHYR&testcase=multiple-pause-resume-5 - are these known? Cannot find in other PRs so far

**Comment by lyakh** [comment]
the first 4 commits are fine then: https://sof-ci.01.org/sofpr/PR6027/build931/devicetest/ Continue bisecting...

**Comment by lgirdwood** [comment]
@lyakh it looks like some of the DUTS could be down here as one DUT is passing (I would expect all to fail). @wszypelt can you check here, I would expect all DUTs to fail given this PR so not sure if this is a CI failure or PR failure. Thanks !

**Comment by wszypelt** [comment]
@lgirdwood It is very possible that it is CI fault, I have run tests again, the results should be there within an hour

**Comment by lyakh** [comment]
The CI device test https://sof-ci.01.org/sofpr/PR6027/build934/devicetest/ has two suspend-resume and one "verify kernel boot log" failures, which very much seem unrelated to me. @lgirdwood would be great if we could merge this. Then I think we already could enable sparse checking - after this we shouldn't have any more "address space" sparse warnings. Then I'll make sure to push and debug the actual enabling of `CONFIG_INCOHERENT`

**Review by lgirdwood — APPROVED** [review]

**Pull request merged**
