### PR TITLE
memory: apollolake: refine the heap sections size

### PR DESCRIPTION
**Pull request by keyonjie**
Reduce the system and system_runtime size, fine tune the size of runtime
and runtime_shared sections.

Signed-off-by: Keyon Jie <yang.jie@linux.intel.com>

### CODE REVIEW

**Comment by keyonjie** [comment]
Though @singalsu has changed to de-select beamformer and done for APL to reduce the .text size, let's still try to keep .bss size with the new PR, where we will have more sections for runtime shared heap on APL.

**Review by lgirdwood — APPROVED** [review]
Thank you @keyonjie this should align each platform better now with usage.

**Review by singalsu — COMMENTED** [review]
It looks OK but it maybe need to have that one 4096 size slot for larger algorithms than very basic ones. It has been changed back and forth in platforms. 4096 bytes is only 20ms worth of 16 bit stereo audio. It's not much of history buffer for signal processing.

**Comment by keyonjie** [comment]
> It looks OK but it maybe need to have that one 4096 size slot for larger algorithms than very basic ones. It has been changed back and forth in platforms. 4096 bytes is only 20ms worth of 16 bit stereo audio. It's not much of history buffer for signal processing.

Yes, but on most of our scenarios on APL, the 4KB section is actually not used, on one hand, we can still get a 4KB contiguous memory from 8 * 512B sections, on the other hand, leave it as 4KB one could be a big waste when we have about 64KB runtime heap memory in total only. 

Maybe let me change the 2KB one to 2 * 1KB together, @lgirdwood comments?

**Comment by keyonjie** [comment]
@singalsu @lgirdwood anyway I will work on calculate the .bss section size at run time next, which means all the remained banks will be used for runtime sections.

**Comment by lgirdwood** [comment]
> > It looks OK but it maybe need to have that one 4096 size slot for larger algorithms than very basic ones. It has been changed back and forth in platforms. 4096 bytes is only 20ms worth of 16 bit stereo audio. It's not much of history buffer for signal processing.
> 
> Yes, but on most of our scenarios on APL, the 4KB section is actually not used, on one hand, we can still get a 4KB contiguous memory from 8 * 512B sections, on the other hand, leave it as 4KB one could be a big waste when we have about 64KB runtime heap memory in total only.
> 
> Maybe let me change the 2KB one to 2 * 1KB together, @lgirdwood comments?

If this is not a problem today (i.e. its not being used atm) on this platform then we are fine as the Zephyr allocator has no such restrictions. i.e. happy to have this as a known configuration change.

**Review by singalsu — APPROVED** [review]

**Comment by keyonjie** [comment]
Let's align APL with other cAVS platforms first, more refinement will come next.

**Pull request merged**
