### PR TITLE
west.yml: update Zephyr to 5689916a70ad

### PR DESCRIPTION
**Pull request by kv2019i**
Contains 367 commits, including following directly affecting SOF targets:

ffd2121c65d3 soc: xtensa: intel_adsp: cavs: fix power_down_cavs() signature
a1d7ffdc374d soc: xtensa: intel_adsp: cavs: fix incorrect cached/uncached cast
ce7c30c12978 soc: intel_adsp/ace: use WAIT_FOR for core power transitions
3f0ee7f6db7a power_domain: intel_adsp: initialize after DMA
ca23a5f0cf75 xtensa: mmu: allow SoC to do additional MMU init steps
088a31e2bffa xtensa: mmu: preload ITLB for VECBASE before restoring...
40f2486b685c xtensa: mmu: rename MMU_KERNEL_RING to Z_XTENSA_KERNEL_RING...
18eb17f4cd69 xtensa: mmu: add arch_reserved_pages_update
4778c13bbeab xtensa: mmu: handle all data TLB misses in double exception
c723d8b8d3ac xtensa: Add missing synchronization
24148718fc6e xtensa: mmu: cache common data and heap if !XTENSA_RPO_CACHE
b6ccbae58dc4 xtensa: mmu: use _image_ram_start/end for data region
257404a14327 xtensa: mmu: init: only clear enough entries in way 6
614e64325d48 xtensa: mmu: no longer identity map the first 512MB
b5016714b082 xtensa: mmu: handle TLB misses during user exception
98ffd1addd6a xtensa: crt1: call z_xtensa_mmu_init
38d4b7872401 xtensa: mmu: remove printing vaddr registers during exception
3d63e2060edf dts: cpu: add cdns,tensilica-xtensa-lx3

### CODE REVIEW

**Review by tmleman — APPROVED** [review]

**Comment by kv2019i** [comment]
Yay, sparse tests green again!

The IPC3 stub build fails to some clang issue. Any idea @marc-hb ?

**Review by lgirdwood — APPROVED** [review]

**Comment by kv2019i** [comment]
Doh, we seem to have a regression:

https://sof-ci.01.org/sofpr/PR8126/build12358/devicetest/index.html?model=TGLU_UP_HDA_IPC4ZPH&testcase=check-kmod-load-unload
```
[  780.342019] kernel: snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx      : 0x47000000|0x0: MOD_SET_DX [data size: 8]
[  780.342766] kernel: snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc rx      : 0x1b0a0000|0x0: GLB_NOTIFICATION|EXCEPTION_CAUGHT
[  780.342775] kernel: snd_sof:sof_ipc4_rx_msg: sof-audio-pci-intel-tgl 0000:00:1f.3: Unhandled DSP message: 0x1b0a0000|0x0
[  780.342780] kernel: snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc rx done : 0x1b0a0000|0x0: GLB_NOTIFICATION|EXCEPTION_CAUGHT
[  780.846234] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc timed out for 0x47000000|0x0
```

**Comment by kv2019i** [comment]
Regression found, caused by a patch by certain @kv2019i :( Fixed in https://github.com/zephyrproject-rtos/zephyr/pull/62180

Marking as DNM and will reupload this PR once the fix is merged upstream.

**Comment by kv2019i** [comment]
V3 upload:
- fix for the regression on cAVS2.5
- included fix for Intel ACE1.5 L1 exit logc

**Review by lgirdwood — APPROVED** [review]

**Comment by kv2019i** [comment]
One system PM fail in 
https://sof-ci.01.org/sofpr/PR8126/build12401/devicetest/index.html - can be ignored, not related to audio. 

And one one system PM fail in
https://sof-ci.01.org/sofpr/PR8126/build12402/devicetest/index.html - this also seems safe to ignore as only affects one DUT 

We have a new sparse fail introduce by the L1 exit code:
https://github.com/thesofproject/sof/actions/runs/6046303049/job/16407636771?pr=8126

... but that's already in merged Zephyr code, so this has to be (again) handled in a separate PR.

Proceeding with merge.

**Comment by marc-hb** [comment]
> We have a new sparse fail introduce by the L1 exit code:
https://github.com/thesofproject/sof/actions/runs/6046303049/job/16407636771?pr=8126

Fix submitted in
- https://github.com/zephyrproject-rtos/zephyr/pull/62232

**Pull request merged**
