### PR TITLE
topology m4 parameter checks, dai, pcm and widgets

### PR DESCRIPTION
**Pull request by kv2019i**
Extend checks to dai.m4. This has variable argument count, so required a bti different approach.

### CODE REVIEW

**Comment by kv2019i** [comment]
Closed PR1187, and will use this PR to submit all three patches I have so far. These now cover checks for all main top-level macros. If this proves useful, it's easy to extend to cover more macros and make it a common practise to have the checks in place in any new macros added.

**Comment by xiulipan** [comment]
@lgirdwood @ranj063 
It seems this caused some regression in test topology related to **tone generator** and the CI failed to caught it due to some bug in the build scripts.
https://github.com/thesofproject/sof/pull/1206 fix the scripts issue
#1205 fix the remaining tone related topology in test topology.

Here I would like to ask again about if we need to use some test topology anymore.
We need virtual routes or virtual widgets for most codec topology now, and we may not be able to add them all in the test topology.

**Comment by ranj063** [comment]
@xiulipan I think we should archive the test topologies.

**Comment by xiulipan** [comment]
@ranj063 
I agree with you.
@singalsu 
Any idea? I think you used a lot of typologies from test.

**Comment by lgirdwood** [comment]
@xiulipan ok, test topologies can be deleted. So no need for CI update either now.

**Comment by singalsu** [comment]
We need for testbench simple host -> comp -> dai type topologies. I've done some similar topologies for apl + pcm512x so the test topologies delete is not a problem at the moment.

**Comment by lgirdwood** [comment]
@singalsu ok, so this means we need a subset of tests (can you name them) that @xiulipan can build with the test bench target. i.e. the test bench and test bench topologies will be built together (and validated by CI).

**Pull request merged**
