### PR TITLE
topology: use DMIC gain boost similar to HDAudio topologies

### PR DESCRIPTION
**Pull request by plbossart**
We used the same macros in .m4 files but missed the additional
configuration needed in CMakeLists.txt

Reported-by: Seppo Ingalsuo <seppo.ingalsuo@linux.intel.com>
Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>

### CODE REVIEW

**Comment by plbossart** [comment]
Hold on for merge for @aigilea 's feedback on https://github.com/thesofproject/linux/issues/2700#issuecomment-771794675

**Comment by plbossart** [comment]
> Hold on for merge for @aigilea 's feedback on [thesofproject/linux#2700 (comment)](https://github.com/thesofproject/linux/issues/2700#issuecomment-771794675)

results are ok, can be merged if reviewers agree

**Review by juimonen — APPROVED** [review]
lgtm

**Review by singalsu — APPROVED** [review]
Thanks Pierre!

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
Jenkins unrelated PM module unload timeout.

**Pull request merged**
