### PR TITLE
LNL: modular TOML

### PR DESCRIPTION
**Pull request by lyakh**

### CODE REVIEW

**Review by kv2019i — APPROVED** [review]
Let's see how the CI fares...

**Comment by lyakh** [comment]
@wszypelt looks like the QB is hanging?

**Review by lgirdwood — APPROVED** [review]

**Comment by wszypelt** [comment]
@lyakh  new results should be available within an hour

**Comment by lyakh** [comment]
> @lyakh new results should be available within an hour

@wszypelt thanks! The results are there but I don't quite like them :-) There's one failure and it's in an up-donw mixer test, i.e. a loadable module, so it sounds "potentially related," but the failure there is with actual audio performance, while this PR only modifies TOML files. Are TOML files used in that test? Maybe LNL TOML files aren't preprocessed for that test?

**Comment by lgirdwood** [comment]
> > @lyakh new results should be available within an hour
> 
> @wszypelt thanks! The results are there but I don't quite like them :-) There's one failure and it's in an up-donw mixer test, i.e. a loadable module, so it sounds "potentially related," but the failure there is with actual audio performance, while this PR only modifies TOML files. Are TOML files used in that test? Maybe LNL TOML files aren't preprocessed for that test?

All green now for Internal CI, thanks @wszypelt and @lyakh

**Pull request merged**
