### PR TITLE
topology: add echo reference with DEMUX for tgl max98357a

### PR DESCRIPTION
**Pull request by xiulipan**
Add echo reference pipeline for the tgl speaker max98357a
with demux.

Signed-off-by: Pan Xiuli <xiuli.pan@linux.intel.com>

### CODE REVIEW

**Comment by sathya-nujella** [comment]
Adding @RDharageswari  for review.

**Comment by sathya-nujella** [comment]
1)
Max98373 is capable of giving feedback from Amp using I2S.
So, we don't need this "sof-tgl-demux-max98373-rt5682". For this amp, we need real feedback, which is under enabling as part of DSM.

2)
max98357a: this is a dumb amp.. so demux feedback helps.

**Comment by xiulipan** [comment]
@sathya-nujella I will remove the demux for the 373 codec. This is a fallback plan if 357a is not working.

**Comment by lgirdwood** [comment]
CI usual issues.

**Pull request merged**
