### PR TITLE
topology: cavs-nocodec: Add deepbuffer pipeline to SSP0

### PR DESCRIPTION
**Pull request by ranj063**
Add a deepbuffer pipeline connected to the the mixer-dai
pipeline. The pipeline deadline is left at 1ms for now
and will be changed later after the mixer pipeline
is validated.

Signed-off-by: Ranjani Sridharan <ranjani.sridharan@linux.intel.com>

### CODE REVIEW

**Comment by ranj063** [comment]
Updated topology:

tplg

**Comment by plbossart** [comment]
@ranj063 Looks like SOF CI or the server is in the weeds, I can't see the results...

**Comment by plbossart** [comment]
> Updated topology:
> 
> tplg

@ranj063 is this possible to add the mixer for SSP_IDX2 on APL, but keep it with SSP_IDX0 on other platforms? That would allow us to check the data on the HAT connector for Up2 and UpExtreme.

Or alternatively add the mixer for both SSP_IDX0 and SSP_IDX2. The additional memory should be liimited.

**Comment by ranj063** [comment]
> Or alternatively add the mixer for both SSP_IDX0 and SSP_IDX2. The additional memory should be liimited.

@plbossart this is simpler to do but out of curiosity why do we add SSP0/1 in the nocodec tplg if SSP5 is the only on visible on Up2. Does it also matter for nocodec at all?

**Comment by plbossart** [comment]
> > Or alternatively add the mixer for both SSP_IDX0 and SSP_IDX2. The additional memory should be liimited.
> 
> @plbossart this is simpler to do but out of curiosity why do we add SSP0/1 in the nocodec tplg if SSP5 is the only on visible on Up2. Does it also matter for nocodec at all?

we added 3 SSPs just to stress-test the systems a bit with more pipelines and opportunities to break things, but in most cases we can only see one SSP on the connector. It just happens that the SSPs are different on Up2 and UpExtreme - not sure why. The 'visible' SSP is really used to grab waveforms and 'prove' that the settings are correct, the other SSPs are just there for scalability/more tests.

**Comment by ranj063** [comment]
> > > Or alternatively add the mixer for both SSP_IDX0 and SSP_IDX2. The additional memory should be liimited.
> > 
> > 
> > @plbossart this is simpler to do but out of curiosity why do we add SSP0/1 in the nocodec tplg if SSP5 is the only on visible on Up2. Does it also matter for nocodec at all?
> 
> we added 3 SSPs just to stress-test the systems a bit with more pipelines and opportunities to break things, but in most cases we can only see one SSP on the connector. It just happens that the SSPs are different on Up2 and UpExtreme - not sure why. The 'visible' SSP is really used to grab waveforms and 'prove' that the settings are correct, the other SSPs are just there for scalability/more tests.

Thanks for the explanation @plbossart . Updated now like this:
tplg

**Comment by plbossart** [comment]
looks good @ranj063. We may see some alsa-bat failures if the PGA 7.0 and 8.0 volume and switch are not initialized?

**Comment by plbossart** [comment]
@ranj063 I see the same failure as CI on APL UP2 NOCODEC

````
[    7.063353] sof-audio-pci-intel-apl 0000:00:0e.0: loading topology:intel/sof-tplg/sof-apl-nocodec.tplg
[    7.067499] sof-audio-pci-intel-apl 0000:00:0e.0: Topology: ABI 3:19:0 Kernel ABI 3:18:0
[    7.067524] sof-audio-pci-intel-apl 0000:00:0e.0: warn: topology ABI is more recent than kernel
[    7.067549] sof-audio-pci-intel-apl 0000:00:0e.0: tplg: ready widget id 0 pipe 1 type 23 name : PCM0P stream Playback 0
[    7.067567] sof-audio-pci-intel-apl 0000:00:0e.0: loaded host PCM0P
[    7.067574] sof-audio-pci-intel-apl 0000:00:0e.0:  config: periods snk 2 src 0 fmt 0
[    7.067602] sof-audio-pci-intel-apl 0000:00:0e.0: tplg: load control type 1 name : 1 Playback Volume
[    7.067626] sof-audio-pci-intel-apl 0000:00:0e.0: tplg: load kcontrol index 1 chans 2
[    7.067640] sof-audio-pci-intel-apl 0000:00:0e.0: tplg: ready widget id 1 pipe 1 type 6 name : PGA1.0 stream none
[    7.067654] sof-audio-pci-intel-apl 0000:00:0e.0:  config: periods snk 2 src 2 fmt 2
[    7.067671] sof-audio-pci-intel-apl 0000:00:0e.0: tplg: ready widget id 2 pipe 1 type 31 name : BUF1.0 stream none
[    7.067685] sof-audio-pci-intel-apl 0000:00:0e.0: buffer BUF1.0: size 768 caps 0x71
[    7.067702] sof-audio-pci-intel-apl 0000:00:0e.0: tplg: ready widget id 3 pipe 1 type 31 name : BUF1.1 stream none
[    7.067715] sof-audio-pci-intel-apl 0000:00:0e.0: buffer BUF1.1: size 768 caps 0x71
[    7.067733] sof-audio-pci-intel-apl 0000:00:0e.0: tplg: ready widget id 4 pipe 1 type 32 name : PIPELINE.1.SSP0.OUT stream SSP0.OUT
[    7.067746] sof-audio-pci-intel-apl 0000:00:0e.0: error: widget PIPELINE.1.SSP0.OUT refers to non existent widget SSP0.OUT
[    7.067835] sof-audio-pci-intel-apl 0000:00:0e.0: error: failed to add widget id 0 type 32 name : PIPELINE.1.SSP0.OUT stream SSP0.OUT
[    7.067924] sof-audio-pci-intel-apl 0000:00:0e.0: ASoC: failed to load widget PIPELINE.1.SSP0.OUT
[    7.067988] sof-audio-pci-intel-apl 0000:00:0e.0: ASoC: topology: could not load header: -22
[    7.068055] sof-audio-pci-intel-apl 0000:00:0e.0: error: tplg component load failed -22
[    7.068139] sof-audio-pci-intel-apl 0000:00:0e.0: error: failed to load DSP topology -22
[    7.068229] sof-audio-pci-intel-apl 0000:00:0e.0: ASoC: error at snd_soc_component_probe on 0000:00:0e.0: -22
[    7.068424] sof-nocodec sof-nocodec: ASoC: failed to instantiate card -22
````

**Comment by ranj063** [comment]
> @ranj063 I see the same failure as CI on APL UP2 NOCODEC

@plbossart sorry about that. The pipeline indices have to be incremental . FIxed now

**Comment by ranj063** [comment]
> looks good @ranj063. We may see some alsa-bat failures if the PGA 7.0 and 8.0 volume and switch are not initialized?

PGA7.0 and 8.0 dont have a switch @plbossart. Should I add them? We always initialize PGA's to 0dB gain in the FW right?

**Comment by lgirdwood** [comment]
CI is looking good, I'm assuming that its testing PCM0P (not sure about PCM2, 3 or 4P) ?
@ranj063 btw, I'm assuming the topology CC can be made to output text debug data as it compiles ? I'm thinking it would be nice for CI to parse this and say "PCM0P has a mixer, therefore I run my mixer-test.sh on PCM0P and PCM3P" etc.

**Comment by plbossart** [comment]
> CI is looking good, I'm assuming that its testing PCM0P (not sure about PCM2, 3 or 4P) ?
> @ranj063 btw, I'm assuming the topology CC can be made to output text debug data as it compiles ? I'm thinking it would be nice for CI to parse this and say "PCM0P has a mixer, therefore I run my mixer-test.sh on PCM0P and PCM3P" etc.

Our CI scripts are not at that level unfortunately, as measured by the addition of a platform without the associated mixer settings.

**Comment by plbossart** [comment]
SOFCI TEST

**Review by plbossart — APPROVED** [review]
Looks good @ranj063. 

I would prefer it if we merged on Monday so that we don't impact the last daily test of the week and have some redundancy on the current nocodec tests. So far it's all pass but we have stress-tests also this week-end.

**Comment by plbossart** [comment]
The good news is that the stress tests didn't expose new issues with this topology, though there is a clear issue with suspend-resume (a DSP panic logged as https://github.com/thesofproject/sof/issues/4480)

@lgirdwood we should merge this and start testing this configuration.

**Review by lgirdwood — APPROVED** [review]

**Pull request merged**
