### PR TITLE
config: disable alh in jasperlake_defconfig

### PR DESCRIPTION
**Pull request by yongzhi1**
Since soundwire is not enabled on any jsl+ product,
it's safe to turn it off by default.

Signed-off-by: Yong Zhi <yong.zhi@intel.com>

### CODE REVIEW

**Comment by xiulipan** [comment]
@zrombel Looks like the Internal Intel CI System need to remove ALH test if this update merged.

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
@zrombel ping - good to merge ?

**Comment by gkbldcig** [comment]
Can one of the admins verify this patch?

**Review by ranj063 — APPROVED** [review]

**Comment by lgirdwood** [comment]
please test this

**Comment by lgirdwood** [comment]
CI jenkins showing unrelated issue on BDW

**Pull request merged**
