### PR TITLE
codec_adapter: passthrough: fix typo

### PR DESCRIPTION
**Pull request by cujomalainey**
logging as process in prepare step

### CODE REVIEW

**Comment by cujomalainey** [comment]
Gah i forgot the signed off by as i made the change via the web interface, will fix that later

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
> Gah i forgot the signed off by as i made the change via the web interface, will fix that later

changes are good, looks like CI needs to be rerun again anyway.

**Review by mrajwa — APPROVED** [review]
Looks ok, thanks.

**Comment by cujomalainey** [comment]
Ok i think i fixed the build failures and the sign off tags being missed.

**Review by lgirdwood — APPROVED** [review]

**Review by dbaluta — APPROVED** [review]

**Comment by cujomalainey** [comment]
3 approvals, going ahead and merging

**Pull request merged**
