### PR TITLE
Compile ESAI/SDMA support as separate modules

### PR DESCRIPTION
**Pull request by Potochi**

### CODE REVIEW

**Comment by sofci** [comment]
Can one of the admins verify this patch?
> reply **test&nbsp;this&nbsp;please** to run this test once

**Review by paulstelian97 — APPROVED** [review]

**Review by lgirdwood — APPROVED** [review]

**Review by dbaluta — APPROVED** [review]

**Review by iuliana-prodan — APPROVED** [review]

**Comment by gkbldcig** [comment]
Can one of the admins verify this patch?

**Comment by lgirdwood** [comment]
test this please

**Comment by lgirdwood** [comment]
@Potochi please check your mail for a project developer invite.

**Comment by dbaluta** [comment]
test this please

**Comment by dbaluta** [comment]
@lgirdwood this looks good on our side. not sure why some Intel tests are failing.

**Comment by lgirdwood** [comment]
@kkarask @wszypelt are we good to merge, the CI failure looks unrelated ?

**Comment by wszypelt** [comment]
@lgirdwood @dbaluta tests successful :)

**Pull request merged**
