### PR TITLE
audio: google: Fix AEC mock

### PR DESCRIPTION
**Pull request by mtrulsson**
Backport from main to fix aec mock

### CODE REVIEW

**Comment by sofci** [comment]
Can one of the admins verify this patch?
> reply **test&nbsp;this&nbsp;please** to run this test once

**Review by lgirdwood — COMMENTED** [review]
@mtrulsson can you confirm we have this in main branch ?
@mwasko fyi.

**Comment by lgirdwood** [comment]
test this please

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by mtrulsson** [comment]
Main branch commit
https://github.com/thesofproject/sof/commit/74fd2914991a59eeb7229aeed321294434ce03e9

**Review by lgirdwood — APPROVED** [review]

**Comment by cujomalainey** [comment]
Please switch this to cavs2.5-001-drop-stable

**Comment by mtrulsson** [comment]
I switched the PR to cavs2.5-001-drop-stable.

**Pull request closed without merging**
