### PR TITLE
platform: imx8: Fix exception mailbox offset

### PR DESCRIPTION
**Pull request by paulstelian97**
Tried to diagnose a DSP panic, did not work due to this wrong offset (was reading invalid data).

Signed-off-by: Paul Olaru <paul.olaru@nxp.com>

### CODE REVIEW

**Comment by dbaluta** [comment]
good catch! thanks Paul!

**Comment by tlauda** [comment]
@dbaluta I know it was a trivial change, but it was agreed to only merge PRs with full CI completed. This one had only 3 checks done.

**Comment by dbaluta** [comment]
@tlauda Sorry for this! I only looked to see if there are any failures. I saw all green and pushed merge! Any idea idea how to trigger all CI tests? I mean how many checks are in total and what to do if they do not appear in the github interface. Here it is how it looks on my side: https://screenshots.firefox.com/YughhQBW73pohPRp/github.com

**Comment by paulstelian97** [comment]
@dbaluta I noticed that @tlauda sometimes posts comments with the content "SOFCI TEST", presumably to trigger all tests and there are 8 in total (some of them taking half a day or something), at least from what I see from other merged PRs. If I did a force-push I would have also triggered all the tests.

**Pull request merged**
