### PR TITLE
topology: add smart_amp support to sof-tgl-nocodec

### PR DESCRIPTION
**Pull request by keyonjie**
Add nocodec mode smart_amp support to sof-tgl-nocodec-ci, which will help
to verify smart_amp feature on nocodec platforms.

Signed-off-by: Keyon Jie <yang.jie@linux.intel.com>

### CODE REVIEW

**Comment by lgirdwood** [comment]
@keyonjie not sure how useful this is ? Unless it's helpful for the CI or kernel folks ? @aiChaoSONG @plbossart ?

**Comment by keyonjie** [comment]
> we shouldn't do this. nocodec is supposed to be a very simple solution. Put this in a different topology.

Ok, let me create a new .m4 file for it.

**Comment by keyonjie** [comment]
> @keyonjie not sure how useful this is ? Unless it's helpful for the CI or kernel folks ? @aiChaoSONG @plbossart ?

Yes, it is useful for CI daily automation test, we will use a test tplg file with nocodec machine driver together on TGL RVP, to verify I2S playback/capture, DMIC capture, WoV, smart_amp, (FW)Echo Ref features in CI daily test.

**Comment by keyonjie** [comment]
> > we shouldn't do this. nocodec is supposed to be a very simple solution. Put this in a different topology.
> 
> Ok, let me create a new .m4 file for it.

@plbossart updated now.

**Comment by xiulipan** [comment]
Close as merged into https://github.com/thesofproject/sof/pull/3212

**Pull request closed without merging**
