### PR TITLE
topology update for KD feature

### PR DESCRIPTION
**Pull request by keyonjie**
This is based on @ranj063's #999 , switch using MUX component to channel selector and key phrase buffer manager component.

image

It is only compile tested.

@lbetlej @mrajwa please check if it is what you want for FW.

### CODE REVIEW

**Comment by lgirdwood** [comment]
@keyonjie this can be merged quicker if split into several PRs. i.e. we have generic code to add new features with KD specific code in this PR that could be split.

**Comment by ranj063** [comment]
@lgirdwood I'll work with @keyonjie today to close this open smaller ones.

**Comment by keyonjie** [comment]
OK, let me update PR today.

**Comment by keyonjie** [comment]
@lgirdwood could you check this prerequisite PR for topology change firstly here:
https://github.com/thesofproject/sof/pull/1079
I will send the follow kwd specific changes after that is merged.

**Comment by keyonjie** [comment]
@lgirdwood https://github.com/thesofproject/sof/pull/1082 is the KWD specific changes needed for topology.

**Comment by lgirdwood** [comment]
@keyonjie thanks, so should this PR now be closed ?

**Comment by ranj063** [comment]
@keyonjie @lgirdwood I'm closing this to avoid confusion

**Pull request closed without merging**
