### PR TITLE
ipc4: set sink sample rate before verifying params

### PR DESCRIPTION
**Pull request by RanderWang**
Fix src issue on windows. Need to update sink format before
src_verify_params which uses it to generate dev->frame.

### CODE REVIEW

**Comment by singalsu** [comment]
The params() code was earlier like this but it was changed when pipeline params started to get HW parameters from playback DAI. Have you been able to check what IPC4 DAI returns to pipeline. Also I changed in #5622 some rates logic from params to prepare to ensure params walk is complete before initializing SRC for conversion.

**Review by lgirdwood — APPROVED** [review]
@marcinszkudlinski @tmleman

**Comment by lgirdwood** [comment]
> The params() code was earlier like this but it was changed when pipeline params started to get HW parameters from playback DAI. Have you been able to check what IPC4 DAI returns to pipeline? Also I changed in #5622 some rates logic from params to prepare to ensure params walk is complete before initializing SRC for conversion.
> 
> Edit: I think the change was [de73e60](https://github.com/thesofproject/sof/commit/de73e60a8c627debeb93f040d7aa3d1cfc2b04aa) .

We may need to update the SRC and others as the module API update is rolled out by @ranj063 - this should align us for IPC3/4.If there is a difference today we should capture if in an ifdef in SRC (like we have for mixer).

**Review by singalsu — APPROVED** [review]
Approved since it solves the issue and patch looks OK. This works as long as in topology the rates are set up correct but this may need revisit since it reverts earlier architecture change. The issue may be elsewhere in the IPC4 system.

**Pull request merged**
