### PR TITLE
topology: sof-glk-cs42l42: using 24-bit sample on SSP2

### PR DESCRIPTION
**Pull request by brentlu**
Changing SSP2 configuration to use 24-bit sample bitwidth.

Signed-off-by: Brent Lu <brent.lu@intel.com>

### CODE REVIEW

**Review by lgirdwood — APPROVED** [review]
LGTM, but will wait on @plbossart inputs.

**Comment by plbossart** [comment]
It's good but this will conflicts with the PR #4288 which should go in first @brentlu

**Comment by lgirdwood** [comment]
@plbossart do you mind if this is merged after conflict fixed before early BCLK ? Looks like we still have an open for BCLK. @brentlu can you fix conflict.

**Comment by plbossart** [comment]
> @plbossart do you mind if this is merged after conflict fixed before early BCLK ? Looks like we still have an open for BCLK. @brentlu can you fix conflict.

I don't have time to fix anything related to SSP at this point. If a conflict is generated someone else needs to take over this PR.

**Comment by brentlu** [comment]
Conflict has been resolved but @bardliao will need to rebase his branch for https://github.com/thesofproject/sof/pull/4391 after this PR is merged

**Pull request merged**
