### PR TITLE
TEST IGNORE good rimage SHA, bad rimage code

### PR DESCRIPTION
**Pull request by marc-hb**
This is not a commit message

Signed-off-by: Marc Herbert <marc.herbert@intel.com>

### CODE REVIEW

**Comment by marc-hb** [comment]
https://sof-ci.01.org/sofpr/PR4778/build10372/build is all empty but the internal page has the expected rimage failure.

**Comment by marc-hb** [comment]
https://sof-ci.01.org/sof-pr-viewer/#/build/PR4778/build7292890 is perfect: Unit Tests are green and compilation is red with the expected rimage error.

**Comment by aiChaoSONG** [comment]
SOFCI TEST

**Comment by aiChaoSONG** [comment]
SOFCI TEST

**Comment by lgirdwood** [comment]
> https://sof-ci.01.org/sof-pr-viewer/#/build/PR4778/build7292890 is perfect: Unit Tests are green and compilation is red with the expected rimage error.

Just to confirm, this PR is expected to break CI. Is there a subsequent update needed in CI ?

**Comment by marc-hb** [comment]
This PR had two purposes:
1. Testing the submodule testing process newly documented in https://github.com/thesofproject/rimage/pull/71 . To make sure no CI system ignores rimage changes, nothing like breaking rimage. Breaking stuff is a really underrated testing technique. For instance breaking a C macro is the only convenient way to visualize a complex stack of macros: just ask the compiler. I digress sorry.
1. Take that opportunity to test how good or bad CI is at reporting build failures. For instance https://sof-ci.01.org/sofpr/PR4778/build10372/build rates "very bad" cause all empty. Then @aiChaoSONG performed some magic behind the scenes to give us https://sof-ci.01.org/sofpr/PR4778/build10377/build/ instead which rates as "excellent" - thank you @aiChaoSONG !

**Pull request closed without merging**
