### PR TITLE
ssp: Use *BIT* macros instead of raw bit operations

### PR DESCRIPTION
**Pull request by ktrzcinx**
Introduced solution is more elegant and reliable because of
masking given argument in SET_BITS.
Moreover remove unused masks which usability is taken by SET_BITS
macro with given bits range.

Signed-off-by: Karol Trzcinski <karolx.trzcinski@linux.intel.com>

This patch needs changes from https://github.com/thesofproject/sof/pull/2446

### CODE REVIEW

**Comment by paulstelian97** [comment]
HSW/BDW seem finnicky because BIT(31) suddenly creates a 64-bit value? The error message says it's turning 0xffffffff80000030 to 0x80000030 -- but we need to figure out why we're even getting those ff's... Undefined behavior from BIT(31) which those compilers handle differently?

Is it possible to make the BIT macro do something like 1u << x in C code and 1 << x in assembler? (I think you have tried this before but forgot why it wouldn't work)

**Comment by paulstelian97** [comment]
I think you need to add "bit: Upgrade BIT macro to use 1UL instead of 1" in this PR as well as they are dependent.

**Comment by dbaluta** [comment]
why is the building failing on hsw?

**Comment by paulstelian97** [comment]
> why is the building failing on hsw?

See my replies and the comment that it requires #2446 in order to build on HSW/BDW.

**Comment by lgirdwood** [comment]
@ktrzcinx can you resolve the conflict, we need to kick the CI license server again...

**Comment by paulstelian97** [comment]
(rebasing should also fix the build failures as prerequisite is merged)

**Comment by lgirdwood** [comment]
@ktrzcinx it still seems we are failing on BYT with DMA channel freeing
```
 CORE  LEVEL      COMP_ID                TIMESTAMP            DELTA                FILE_NAME	CONTENT
    0      1         WAIT         148002358.541667 148002352.000000       src/lib/wait.c:39  	ewt
    0      1          DMA         148002365.520833         6.979167 src/drivers/dw/dma.c:413 	dw_dma_stop() error: dma 1 channel 1 timeout
    0      2          IPC         148000990.312500              nan    src/ipc/handler.c:441 	ipc: comp 2 -> trigger cmd 0x50000
    0      2         PIPE 1.11    148000992.604167         2.291667 src/audio/pipeline.c:642 	pipeline_trigger()
    0      2         COMP 1.2     148000995.052083         2.447917     src/audio/host.c:276 	host_trigger()
    0      2         COMP 1.3     148000998.020833         2.968750 udio/volume/volume.c:631 	volume_trigger()
    0      2         COMP 1.5     148001000.989583         2.968750    src/audio/mixer.c:237 	mixer_trigger()
    0      2         COMP 1.4     148001004.062500         3.072917 udio/volume/volume.c:631 	volume_trigger()
    0      2         COMP 1.10    148001007.031250         2.968750      src/audio/dai.c:555 	dai_comp_trigger(), command = 0
    0      2         COMP 1.10    148001009.479167         2.447917      src/audio/dai.c:614 	dai_comp_trigger(), PAUSE/STOP
    0      2          DMA         148001011.718750         2.239583 src/drivers/dw/dma.c:391 	dw_dma_stop(): dma 1 channel 1 stop
    0      1         WAIT         148002358.541667      1346.822876       src/lib/wait.c:39  	ewt
    0      1          DMA         148002365.520833         6.979167 src/drivers/dw/dma.c:413 	dw_dma_stop() error: dma 1 channel 1 timeout
```
In theory there should be no differences in the ELF binary (and dissassembly) before and after this PR. Can you check this, perhaps its working by accident or this bit is different on BYT DMAC.

**Comment by ktrzcinx** [comment]
@lgirdwood Now it looks good.

**Pull request merged**
