### PR TITLE
rtnr: merge period settings for rtnr back to adl-004-drop-stable branch

### PR DESCRIPTION
**Pull request by MingJenTai**
This PR merges the following modifications of periods settings from main branch to adl-004-drop-stable branch:

8496d585d1cf1ce75a84680de91a9fed92bcf1b6 [Modify periods setting for RTNR capturing pipeline](https://github.com/thesofproject/sof/commit/8496d585d1cf1ce75a84680de91a9fed92bcf1b6) 

1. With the  release of RTNR version 20220728, period for capturing pipeline requires at least 5ms.
2. Periods setting for 16KHz capturing pipeline is also removed since RTNR is currently running in 48KHz capturing pipeline only.

### CODE REVIEW

**Review by johnylin76 — APPROVED** [review]
LGTM

**Review by lgirdwood — APPROVED** [review]
@MingJenTai is this already on main ?

**Comment by MingJenTai** [comment]
> @MingJenTai is this already on main ?

Yes, it was cherry picked from commit https://github.com/MingJenTai/sof/commit/8496d585d1cf1ce75a84680de91a9fed92bcf1b6

**Comment by MingJenTai** [comment]
> @MingJenTai is this already on main ?

I'll modify the commit message of this PR.

**Comment by lgirdwood** [comment]
@mwasko fyi - topology only update from main.

**Pull request merged**
