### PR TITLE
[RFC]: topology: demux_coef_default: Define demux pipeline id variable

### PR DESCRIPTION
**Pull request by bardliao**
Use DEMUX_PIPE1 and DEMUX_PIPE2 to replace fixed pipeline ids.
So we can define DEMUX_PIPE1 and DEMUX_PIPE2 for each project.

Signed-off-by: Bard Liao <yung-chuan.liao@linux.intel.com>

### CODE REVIEW

**Comment by lgirdwood** [comment]
@bardliao  fyi @juimonen iw working on improving mux/demux config and init.

**Comment by juimonen** [comment]
@bardliao just add similar struct to your pipeline with modified values, I mean it can be in the top level pipeline also if you don't want to create extra file. Or then this should come the new "default", which is a bad name as the pipeline id's are fixed.

**Comment by bardliao** [comment]
@juimonen @lgirdwood Update PR. How about this? I can define DEMUX_PIPE1 and DEMUX_PIPE2 in sof-icl-rt711-rt1308-rt715-hdmi.m4 and won't break others.

**Comment by bardliao** [comment]
> @bardliao sorry but looks still bad to me :)
> 
> So just changing 1 hex value in the middle of the blob looks really hackish, I should have not shown you this :)
> 
> I mean just copy this file into different name, or include the changed blob directly to your pipeline file. it would be much cleaner that way.

Yeah, I know your point. But my intent is to reuse the default coef. I don't want to create whole coef if possible. My point is it is better to set pipeline ids only rather than a whole coef in each topology m4 file . The best solution to me is FW can get pipeline id from topology graph, but I don't know is it doable or not.

**Comment by lgirdwood** [comment]
> > @bardliao sorry but looks still bad to me :)
> > So just changing 1 hex value in the middle of the blob looks really hackish, I should have not shown you this :)
> > I mean just copy this file into different name, or include the changed blob directly to your pipeline file. it would be much cleaner that way.
> 
> Yeah, I know your point. But my intent is to reuse the default coef. I don't want to create whole coef if possible. My point is it is better to set pipeline ids only rather than a whole coef in each topology m4 file . The best solution to me is FW can get pipeline id from topology graph, but I don't know is it doable or not.

@bardliao this will be fixed by @juimonen soon, is it blocking you today ?
@juimonen do you have a rough ETA for enum kcontrol for mux/demux ?

**Comment by bardliao** [comment]
> @bardliao this will be fixed by @juimonen soon, is it blocking you today ?

No, it is not too urgent. I can wait :)

**Comment by juimonen** [comment]
@lgirdwood @bardliao I'll start looking at it now, but I really can't say how long it will take... I need o read the demux code etc. understand how it really works. hopefully something end of this week.

**Comment by bardliao** [comment]
replaced by #2594

**Pull request closed without merging**
