### PR TITLE
west.yml: update zephyr to e59289d89999

### PR DESCRIPTION
**Pull request by kv2019i**
Total of 252 commits.

Changes include:

58df2533bbbf drivers: dma: intel-adsp-hda: coding style fix
1bafbf4f1d11 drivers: dma: intel-adsp-hda: optimize L1 exit handling in ISR

### CODE REVIEW

**Comment by kv2019i** [comment]
Fast-forward Zephyr to 26th Nov. After this, there are regressions in Zephyr upstream and latest attempt with all known fixes failed in SOF CI -> https://github.com/thesofproject/sof/pull/9705 . 
Let's try to update to known good point.

**Review by tmleman — APPROVED** [review]

**Review by lgirdwood — APPROVED** [review]

**Comment by kv2019i** [comment]
sof-docs fail and Intel LNL fails all known and tracked in https://github.com/thesofproject/sof/issues?q=is%3Aissue+is%3Aopen+label%3A%22Known+PR+Failures%22+

**Comment by kv2019i** [comment]
@lgirdwood FYI, I'm getting "Merge attempt failed" trying to merge this.

**Comment by lgirdwood** [comment]
> @lgirdwood FYI, I'm getting "Merge attempt failed" trying to merge this.

Same here. Looks like a GH issue....try later.

**Pull request merged**
