### PR TITLE
ipc: moving src/ipc/*-ipc.c files to drivers dir

### PR DESCRIPTION
**Pull request by bkokoszx**
I've moved src/ipc/\*-ipc.c to src/drivers/intel directory each for specific platform. I've merged apl-ipc.c and cnl-ipc.c using CONFIG_\* defines and placed the resultfile ipc.c in src/drivers/intel/cavs.

Signed-off-by: Bartosz Kokoszko <bartoszx.kokoszko@linux.intel.com>

### CODE REVIEW

**Comment by lgirdwood** [comment]
@jajanusz I agree, lets get the build systemd and dependencies sorted first. @bkokoszx good job btw, fwiw we also need to move dw-dma to top level drivers too since it's generic IP

**Comment by bkokoszx** [comment]
kw error was marked as not a problem.
@jajanusz @bkokoszx 
I've moved all apl-ipc, byt-ipc, cnl-ipc, hsw-ipc, sue-ipc to src/drivers/intel.
I've merged apl-ipc and cnl-ipc into one ipc.c in cavs dir (sue-ipc.c has not been marged).

**Comment by bkokoszx** [comment]
@lgirdwood 
I can move dw-dma.c to top level drivers dir in another PR.

**Comment by lgirdwood** [comment]
@jajanusz ok do you mean it should be merged now or after your build update ?

**Comment by jajanusz** [comment]
@lgirdwood 
Go on and merge it. Don't worry about cmake, I can rebase everything

**Pull request merged**
