### PR TITLE
[skip ci] .github/checkpatch: do not stop on the first failure

### PR DESCRIPTION
**Pull request by marc-hb**
... and a couple other fixes. 3 commits.

Checkpatch failure left as a test/demo.

### CODE REVIEW

**Comment by marc-hb** [comment]
All the PR_CODEC_REGRESSION tests in https://sof-ci.01.org/sof-pr-viewer/#/build/PR3908/build6146349 failed like this:
```
21:33:33.030         ipc_notif
21:33:33.030         Notification TraceDmaPosition (90020000, 00000018)
                     Payload:
                     00000018 90020000 00000000 000002A0 
                     00000000 0000001B  received!

21:33:36.426         Timed out after 4 seconds.

21:33:36.599   => Exception in test.
21:33:36.599     Exception SofIpcErrorResponseException occurred at 
                        'C:\\work\\tools\\pyexecnetcache\\cavs_scripts-py\\utilities\\ipc_driver.py':666
                 FW replied with error.
                 Error code: -22
                 0x00000005 0x00000000 0x00004000
```
This absolutely cannot be related to this pure Github Actions PR.

This looks like a very recent test change (less than 20 minutes ago) because all these unrelated PRs just failed the same:


https://sof-ci.01.org/sof-pr-viewer/#/build/PR3906/build6145378
https://sof-ci.01.org/sof-pr-viewer/#/build/PR3907/build6146378
https://sof-ci.01.org/sof-pr-viewer/#/build/PR3867/build6145520

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
@marc-hb I'm assuming all the other CI results are as expected for this given the skip ci and checkpatch changes ?

**Comment by zrombel** [comment]
QB is not looking at [skip ci] in PR title, but i've added '.github' folder to list that testing will be skipped for.

**Comment by marc-hb** [comment]
https://sof-ci.01.org/sof-pr-viewer/#/build/PR3908/build6149842 shows no PR_ test at all. @zrombel is this how the `.github/` "skipping" works, skipping only the testing but not the build? If yes it's very confusing because it does not say why.

Anyway this is not related to this PR which can be merged.

**Comment by lgirdwood** [comment]
@zrombel thanks !

**Pull request merged**
