### PR TITLE
[DRAFT] Revert/pr7857 pr7325 test

### PR DESCRIPTION
**Pull request by fredoh9**
Reverting 
https://github.com/thesofproject/sof/pull/7857
https://github.com/thesofproject/sof/pull/7325

### CODE REVIEW

**Comment by fredoh9** [comment]
@aborisovich https://github.com/thesofproject/sof/pull/7857 is suspected of causing DSP exception. Can you double check?

**Comment by marc-hb** [comment]
https://sof-ci.01.org/sofpr/PR7873/build10183/devicetest looks really good.

The manifest change in #7857 moved Zephyr about 100 commits forward. I think the next step should be to bisect these 100 Zephyr commits - assuming a high enough reproduction rate. Bisecting _while_ paying attention to the API change also in #7857

**Comment by aborisovich** [comment]
> @aborisovich #7857 is suspected of causing DSP exception. Can you double check?

Can you please provide me with repro steps?
What OS what scenario etc?
We tested those PRs pretty carefully (full scope tests 3 times) and I did not encountered any DSP exception...
Last revision which was merged in SOF brings ~3% improvement in Windows tests we have.
I would look for Zephyr commits as @marc-hb indicated we had a big jump.

**Comment by marc-hb** [comment]
> I would look for Zephyr commits as @marc-hb indicated we had a big jump.

Sorry I gave the wrong impression. 100 commits is actually a very small number in Zephyr because the majority of these commits are totally unrelated to anything we do.

There seems to be only 9 relevant commit:

```
git log --stat e2e3dc07..23b3cae1b1  *adsp*

    23b3cae1b1d9 andrey.borisovich@intel.com // inte_adsp: ipc: prevent ipc message send during Device power transition

 soc/xtensa/intel_adsp/common/include/intel_adsp_ipc.h | 14 ++++++++------
 soc/xtensa/intel_adsp/common/ipc.c                    | 25 +++++++++++++++++++------
 subsys/logging/backends/log_backend_adsp_hda.c        | 22 ++++++++++++----------
 tests/boards/intel_adsp/hda/src/tests.h               |  5 +++--
 tests/boards/intel_adsp/hda_log/src/tests.h           |  5 +++--
 tests/boards/intel_adsp/smoke/src/cpus.c              |  2 +-
 tests/boards/intel_adsp/smoke/src/hostipc.c           | 12 ++++++------
 7 files changed, 52 insertions(+), 33 deletions(-)
    355f8cfe4fbf andrey.borisovich@intel.com // intel_adsp: ipc: device support D3 power state change

 soc/xtensa/intel_adsp/common/include/intel_adsp_ipc.h |  38 ++++++++++++++++++++++++++
 soc/xtensa/intel_adsp/common/ipc.c                    | 123 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++---
 2 files changed, 157 insertions(+), 4 deletions(-)
    1d58b1b83f5d andrey.borisovich@intel.com // intel_adsp: mem_window: reinitialize after idle exit

 soc/xtensa/intel_adsp/ace/power.c                 | 2 ++
 soc/xtensa/intel_adsp/common/include/mem_window.h | 6 ++++++
 soc/xtensa/intel_adsp/common/mem_window.c         | 8 ++++++++
 3 files changed, 16 insertions(+)
    7595cafb0245 andrey.borisovich@intel.com // intel_adsp: timer: implemented sys_clock_idle_exit function

 drivers/timer/intel_adsp_timer.c  | 9 +++++++++
 soc/xtensa/intel_adsp/ace/power.c | 2 ++
 2 files changed, 11 insertions(+)
    2958a407f8f1 adrian.warecki@intel.com // adsp: dmic: Add source clock selection support

 tests/boards/intel_adsp/ssp/src/main.c | 11 +++++++++++
 1 file changed, 11 insertions(+)
    64b2246dbcb9 adrian.warecki@intel.com // soc: adsp: clk: Add multiple clock sources support for dai

 soc/xtensa/intel_adsp/common/clk.c              | 39 +++++++++++++++++++++++++++++++++++++++
 soc/xtensa/intel_adsp/common/include/adsp_clk.h | 58 ++++++++++++++++++++++++++++++++++++++++++++++------------
 2 files changed, 85 insertions(+), 12 deletions(-)
    1a4bc7580bab adrian.warecki@intel.com // adsp: Rename cpu clock related functions

 drivers/clock_control/clock_control_adsp.c        |  2 +-
 soc/xtensa/intel_adsp/common/clk.c                | 28 ++++++++++++++--------------
 soc/xtensa/intel_adsp/common/include/adsp_clk.h   | 24 ++++++++++++------------
 tests/drivers/clock_control/adsp_clock/src/main.c | 30 +++++++++++++++---------------
 4 files changed, 42 insertions(+), 42 deletions(-)
    b9e5cf5110ac adrian.warecki@intel.com // adsp: ace: ace_dfpmccu structure field description

 soc/xtensa/intel_adsp/ace/include/intel_ace15_mtpm/adsp_shim.h | 48 ++++++++++++++++++++++++++++++++++++++++++++++++
 soc/xtensa/intel_adsp/ace/include/intel_ace20_lnl/adsp_shim.h  | 48 ++++++++++++++++++++++++++++++++++++++++++++++++
 2 files changed, 96 insertions(+)
    faadbc42eedc Jaroslaw.Stelter@intel.com // mm_drv: tlb: Fix mapped page in bank calculation

 drivers/mm/mm_drv_intel_adsp_mtl_tlb.c | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

```

PS: we should really move all this discussion to a new bug.

**Comment by marc-hb** [comment]
Discussion moved to new bug filed by @fredoh9 (thx):
- #7875

**Pull request closed without merging**
