### PR TITLE
Audio: Volume: Add state clear to reset() operation

### PR DESCRIPTION
**Pull request by singalsu**
This patch adds clear of all component data in reset() component
operation except state variables those are set by control
commands.

Note: If a new stream starts after reset() without free() and
new(), the clear of all component data would result to wrong
gain and wrong mute state. The driver commands are not re-sent
in such case.

Signed-off-by: Seppo Ingalsuo <seppo.ingalsuo@linux.intel.com>

### CODE REVIEW

**Comment by singalsu** [comment]
This patch passed check-volume-levels.sh with normal and dynamic pipeline (different life cycle). The commit that I shared earlier failed that so I removed it from pull request. This PR contributes to issue #4488 fixes.

**Comment by lgirdwood** [comment]
@singalsu looks like some test failures still.

**Comment by singalsu** [comment]
> @singalsu looks like some test failures still.

Not it's 22 success checks. Maybe it was a temporary issue in CI?

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
@singalsu yeah, I think the CI folks have fixed it for us :)

**Pull request merged**
