### PR TITLE
[DEMO] new elf-size-range.py to monitor ELF sections sizes

### PR DESCRIPTION
**Pull request by marc-hb**
This is a _demo_ to start a discussion following yet another
```
  RD-2012.5-linux/XtensaTools/bin/xt-ld:
    sof section `.text' will not fit in region sof_text_start`
```
... error in #3452

Do _not_ waste your time reviewing code style details yet, not before
the high-level approach has been discussed and agreed. This is just to
show what's possible in less than 75 lines of Python.

The purpose of this script is to address situations like this one:

Maximum size before the linker breaks is say 80,000 bytes

- Developer A adds new feature which increases usage from 70,000 bytes
  to 79,800 bytes. No one notices.
- One month later, developer B submits a small and urgent fix which
  requires 300 extra bytes and that can't be merged because it goes over
  the limit and breaks the build.

This commit implements two "soft limit", optional features to address
this issue. They can catch developer A red-handed LONG before the linker
fails.  If needed, the soft limits can be raised and/or a new Kconfig
created but all only after code review and discussion.

1. Relative limit: compare ELF section sizes with a reference (e.g.:
nightly) build + some max_increase tolerance to allow minor fixes and
other small changes.

2. Absolute limits to stop "feature creep" of multiple minor changes
under max_increase tolerance.

For completeness the implementation also supports "min" values so
anything that reduces code size (compiler flags, compiler versions,
heroes,...) can be flagged too. When they get noticed, soft limits can
be brought down.

Signed-off-by: Marc Herbert <marc.herbert@intel.com>

### CODE REVIEW

**Comment by marc-hb** [comment]
SOFCI TEST

**Review by lgirdwood — COMMENTED** [review]
This is good, but we should allow code growth and it's expected for new features. 
It would be good if a new feature or change size is reported by CI (e.g. to add 4k bytes), the maintainers can then decide if this features deserves a Kconfig option to enable/disable it (with a kconfig help that says "this feature adds N bytes").

**Comment by plbossart** [comment]
> This is good, but we should allow code growth and it's expected for new features.

Not on legacy platforms. we should really stay in the ballpark of the existing footprint. If there is code growth due to a new feature, it needs to be restricted to new platforms.

> It would be good if a new feature or change size is reported by CI (e.g. to add 4k bytes), the maintainers can then decide if this features deserves a Kconfig option to enable/disable it (with a kconfig help that says "this feature adds N bytes").

yes exactly, we need to follow kernel procedures to avoid adding code by default, when a new large feature show up it has to be opt-in and selected only as needed.

**Comment by marc-hb** [comment]
I FINALLY managed to coerce the (non-persistent) docker image to install elftools so Travis  can run this demo, so here's an example of the new check in action: https://travis-ci.org/github/thesofproject/sof/jobs/730022866 (scroll all the way down)

> It would be good if a new feature or change size is reported by CI (e.g. to add 4k bytes), the maintainers can then decide ..

> we should really stay in the ballpark of the existing footprint [...] when a new large feature show up it has to be opt-in and selected only as needed.

This is exactly the idea of this demo. The "ballpark of the existing footprint" is stored in a simple .conf file (see example). When the code grows bigger than the ballpark, the new check fails with the messages demoed in https://travis-ci.org/github/thesofproject/sof/jobs/730022866

Then the developer can decide to either turn off the feature with a new Kconfig or increase the "ballpark" values in the config file.

For demo purposes I added the check at the end of `xtensa-build-all.sh` but it could be only in Travis if desired, all other CI tests would then still run the same.


This with < 75 lines of Python code and a few simple config files.

**Comment by cujomalainey** [comment]
I wonder if we should start running rand builds since we can't fit all components on a single image and as the number of non-trivial components continues to grow its only going to get worse.

**Comment by marc-hb** [comment]
> I wonder if we should start running rand builds ...

There is no such thing as too little testing - except for the small matter of finite time and resources (unless you're Google of course ;-)

**Comment by cujomalainey** [comment]
> > I wonder if we should start running rand builds ...
> 
> There is no such thing as too little testing - except for the small matter of finite time and resources (unless you're Google of course ;-)

Lol, let me get oss-fuzz and static analysis setup and then we can see if i have time, I might be back trying to fix our UCM situation in CRAS.

**Comment by ktrzcinx** [comment]
We already have sof-ri-info.py (https://thesofproject.github.io/latest/developer_guides/debugability/ri-info/index.html), where memory usage is shown in %. I think it's mandatory feature for such an tool, to see how close we are at first glance.

**Comment by lgirdwood** [comment]
@marc-hb I'm looking for something that help me decide if a feature needs a kconfig ot not. i.e. I need to know the feature size delta from the nightly build e.g. compare rimage nightly total vs PR rimage totals.

Fwiw, the largest items for APL are (and I'm not sure if they all have kconfigs) 
```
xtensa-apl-elf-nm --size-sort -S  build_apl_gcc/sof
e01149c 000002b2 t src_copy
be00fb5c 000002b8 t volume_prepare
be01f080 000002cc t _balloc_unlocked$isra$0
be01b198 000002d9 t test_keyword_cmd
be01e694 000002f7 T asrc_calc_impulse_response_n7
be0379a0 00000300 b mod_block256
be027f34 00000320 t schedule_ll_tasks_run
be02b2ac 00000320 R src_int16_25_24_1814_5000_fir
be01796c 00000344 t dai_config
be011a00 0000034a t src_params
be0336d0 0000034c R fir_int32_04_4375_5100_010_095
be018e04 0000036c t kpb_prepare
be0169c8 00000394 t demux_copy
be016d60 000003bc t mux_copy
be02b5cc 000003c0 R src_int16_24_25_1814_5000_fir
be032760 000003c4 R fir_int32_12_4156_6018_010_090
be019494 000003c7 t kpb_event_handler
be00e560 000003d6 T comp_verify_params
be01c9d8 000003d8 t asrc_copy
be032b24 000003dc R fir_int32_08_4156_5380_010_090
be036048 000003dc b hda
be032f00 000003e4 R fir_int32_06_4156_5100_010_095
be01c3e0 000003e5 t asrc_prepare
be0332e4 000003ec R fir_int32_05_4331_5100_010_095
be019ec8 000003f9 t kpb_copy
be037ea0 00000400 b mod_block64
be038340 00000400 b sys_rt_0_block64
be0136ec 00000478 t eq_iir_cmd
be02400c 00000498 t dmic_trigger
be012250 00000499 t eq_fir_cmd
be00c1c4 000004da t host_params
be0103fc 00000510 T src_polyphase_stage_cir
be01090c 00000514 T src_polyphase_stage_cir_s16
be019978 00000520 t kpb_draining_task
be03113c 00000540 r coeff48000to48000
be025e80 00000577 t dw_dma_set_config
be015408 000005b3 t tone_cmd
be00fe38 000005c4 t volume_cmd
be017cf4 000005e7 t dai_params
be02f3bc 00000600 r coeff48000to11025
be02edbc 00000600 r coeff48000to12000
be02dffc 00000640 r coeff48000to22050
be02d9bc 00000640 r coeff48000to24000
be03167c 00000700 r coeff44100to48000
be02cb3c 00000700 r coeff48000to44100
be0301bc 00000780 r coeff24000to16000
be02e63c 00000780 r coeff48000to16000
be02d23c 00000780 r coeff48000to32000
be037130 00000800 b buf_block
be03093c 00000800 r coeff24000to08000
be02f9bc 00000800 r coeff48000to08000
be031d7c 00000804 R sine_table
be02263c 00000973 t ssp_set_config
be036688 00000aa8 b lp_buf_block
be024544 00001203 t dmic_set_config
be00a66c 000015c2 T ipc_cmd
be0388f0 00002020 B master_core_data
```

**Comment by marc-hb** [comment]
Thanks @ktrzcinx , I didn't know about `tools/sof_ri_info/sof_ri_info.py`, interesting. I tried it on the outputs of `scripts/xtensa-build-all.sh` and unfortunately it fails to parse 10 .ri files out of 14 with some error like this:
```
0x0     error: CSE Manifest NOT found ...)
```

I had a quick look at the `sof_ri_info.py` code and I noticed it does not seem to import `pyelftools`. Instead it relies entirely on the manifest to find ELF information, can you confirm? I find this manifest/signature indirection and dependency a bit problematic: even if all the failures above were fixed, you could still not check basic ELF information in (Travis) CI for TGL because it is not supported by rimage. With a direct pyelftools-based solution you can import the script and (interactively!) access anything ELF without changing anything in rimage or C code.

Signing also happens _after_ linking in the build (for an obvious reason) which means `sof_ri_info.py` has nothing to analyze when things don't fit. While this script wouldn't report anything either right now, with a direct `pyelftools` approach it would be very easy to check the .o files too if desired.

**Comment by ktrzcinx** [comment]
@marc-hb 
> 0x0     error: CSE Manifest NOT found ...)

Perhaps for platforms like `bdw`, `bsw`, `byt` `cht`, `hsw`, because they image starts directly from `snd_sof_fw_header` (`Reef` value in hexdump), there's `--no-cse` flag in `sof-ri-info`. 

>Instead it relies entirely on the manifest to find ELF information, can you confirm?

`sof-ri-info` parse .ri file, without any information about elf, so it can be used where elf file is inaccessible.

> With a direct pyelftools-based solution you can import the script and (interactively!) access anything ELF without changing anything in rimage or C code

This tools is also rimage/C-code independent. rimage and sof-ri-info write/reads manifests on theirs own way, there no even single shared file between those tools.

> Signing also happens after linking in the build (for an obvious reason) which means sof_ri_info.py has nothing to analyze when things don't fit.

When it doesn't fit, then threshold for sure is overcome and I suppose something like `xtensa-apl-elf-nm --size-sort -S  build_apl_gcc/sof` can be done, then there won't be additional tools to maintain. We already have so many scripts, that perhaps nobody knows them all.

Adding scripts witch needs to know memory regions size for each platform is quite heavy in maintenance, it's why we should reduce number of them. Possible solution would be dependency to rimage/config/*.toml files, where we already store such an information, and this place has to be maintained with care. But still, there will be one one script more.

When we like to have dedicated script, then as @lgirdwood said it before, during PR/feature acceptance/conditional compilation we should care more footprint delta than raw value. Footprint delta is something what can't be simply read with binutils. Similar approach is some kind of memory footprint in time graph, which could be helpful to find heavy features (feature with great number of small functions won't be as easy to find with nm in opposite to one big struct/function). On graph it easier to relatively compare footprint growth.

**Comment by marc-hb** [comment]
Thanks @ktrzcinx  (and @lgirdwood ) for the additional info and feedback, appreciated. I made a number of changes.


> as @lgirdwood said it before, during PR/feature acceptance/conditional compilation we should care more footprint delta than raw value. 
 
I added the requested delta feature, see new demo at https://travis-ci.org/github/thesofproject/sof/builds/731781126 Now the only thing missing is a pointer to the nightly build.

The problem with looking _only_ at the delta is that it is oblivious to small feature creep. That can still cause sizes to go ever the limit(s) without anyone noticing. I left the "absolute soft limit" warning feature because it shares most of the code and it could catch small feature creep if desired.



> We already have so many scripts, that perhaps nobody knows them all.

I don't think the number of files is an issue. We have many C files too and I bet very few people know all of them either. I think the very valid concern you're alluding to is duplication; something I always take very seriously. A another, related concern is "bitrot" = code that is never used and starts failing without anyone noticing - like   sof_ri_info.py does. The solution to keep bitrot under control is well-known and conceptually simple: maximum code coverage in CI and validation - unlike sof_ri_info.py which fails on 10 configurations out of 14.

Back to duplication: the only thing this new script does is to read some ELF values and compare them. This does not duplicate sof_ri_info.py because sof_ri_info.py does not check ELF files but manifest information instead - a small part of it happening to hold ELF values. So if anything this new script would duplicate the parts of rimage that read ELF values (in fact I consider implement these checks inside rimage at some point in time). But the new script doesn't duplicate the ELF bits of code in rimage either because it relies on pyelftools which provides all the ELF code for free. This is why this script is small. So the only real code addition here is dealing with user input (config file) to figure out what the user wants to check.

Taking a closer look at the rimage source I see ELF code duplicated (and untracked?) from some other project(s).

By the way C is a strange language choice for a tool like rimage because of all the tedious memory management, manual error checking and resulting crashes - just look at the recent rimage git log (and there's still one crash issue open)


> This [sof_ri_info.py] tool is also rimage/C-code independent.

When I worried about requiring rimage C code changes it was only in the hypothetical case where extra ELF details would be needed and added to the manifest (assuming it would even make sense to add extra ELF details to the manifest). Forget it.

Code changes aside, sof_ri_info.py is very dependent on rimage in the sense that it doesn't support (for instance) TGL in CI as long as rimage doesn't support TGL whereas this script does, see demo at https://travis-ci.org/github/thesofproject/sof/builds/731781126


> Adding scripts witch needs to know memory regions size for each platform is quite heavy in maintenance, 

You mean adding per-platform configuration files, not code (the script itself is completely generic, it barely cares which sections to check). I kinda expected these files could be somewhat shared across some platforms but you pushed me to go further: there's no configuration file needed anymore, everything is optional. Now if you don't provide any configuration file then the script defaults to a single check: `max_increase = 100` bytes for .text, .bss and .data. Very easily tuned.


>  Possible solution would be dependency to rimage/config/*.toml files, where we already store such an information, and this place has to be maintained with care. 

I looked at rimage/**/*.toml files and they seem to describe memory regions without any knowledge of or relevance to ELF code sections like .text, .bss etc. Post-linker stuff.

Anyway config file(s) are optional now.


> Similar approach is some kind of memory footprint in time graph, which could be helpful to find heavy features (feature with great number of small functions won't be as easy to find with nm in opposite to one big struct/function). On graph it easier to relatively compare footprint growth.

Graphs et al. would be totally awesome but one reason the "perfect is the enemy of the good" is because the perfect tends to not happen because it takes too much time.

**Comment by ktrzcinx** [comment]
> Now the only thing missing is a pointer to the nightly build

It should be pointer to version where the PR starts - to get delta from PR changes only.

> Now if you don't provide any configuration file then the script defaults

Nice

>I looked at rimage/**/*.toml files and they seem to describe memory regions without any knowledge of or relevance to ELF code sections like .text, .bss etc. Post-linker stuff.

in toml file each memory region has defined base address and size, same as in the elf file, so it's shouldn't be a problem to calculate memory usage for each memory type.

**Comment by marc-hb** [comment]
> It should be pointer to version where the PR starts - to get delta from PR changes only.

Ideally yes. But it would be much, much more complicated because now you have to either build every commit in advance (with a possible race condition if it takes too long) or check out the PR merge base and build it on the fly which is fraught with peril in CI.

We talked about this with @lgirdwood and he said last night's build would be a "good enough" approximation.

Note I'm not going to implement either because I don't know anything about Jenkins.

**Pull request closed without merging**
