### PR TITLE
[DO NOT MERGE] [SKIPTEST]test for RFC labels

### PR DESCRIPTION
**Pull request by xiulipan**
A TEST FOR SOF CI SKIPTEST tag to skip on-device test.

### CODE REVIEW

**Comment by xiulipan** [comment]
SOFCI TEST

**Comment by xiulipan** [comment]
SOFCI TEST

**Comment by xiulipan** [comment]
Reopen to test build node

**Comment by zrombel** [comment]
Due to PR#2029 merge and CI bit depth conversion tests changes, this PR require rebase.

**Comment by xiulipan** [comment]
SOFCI TEST

**Comment by xiulipan** [comment]
repoen for test

**Pull request closed without merging**
