### PR TITLE
audio: volume: optimize volume component with HIFI3[test]

### PR DESCRIPTION
**Pull request by andrula-song**

### CODE REVIEW

**Review by lgirdwood — COMMENTED** [review]
@andrula-song will the other optimisation come as subsequent PRs ?
@singalsu pls review

**Comment by andrula-song** [comment]
>

**Comment by andrula-song** [comment]
> @andrula-song will the other optimisation come as subsequent PRs ? @singalsu pls review

@lgirdwood  This PR is just for checking whether there is any bug in OPT１．Because I mistakenly thought we had to process the entire period data while copy() has been called, So I tried to use both OPT1 & OPT2 to fix the unaligned with 8-byte bug. With this PR I can ensure the OPT1 is clean and at least we have one optimized method now. I am trying to fix bug in OPT2 with the suggestion from @singalsu , still recorded in PR 5169.

**Comment by andrula-song** [comment]
since the 5619 has been merged to main branch, and optimized performance of that PR is much better than this， close this PR now.

**Pull request closed without merging**
