### PR TITLE
cherry-pick: smart_amp fix and pdm1 topology from main

### PR DESCRIPTION
**Pull request by johnylin76**
cherry-picking #7048, #7075, #7076 from main.

94a816735c6c35a0ae1518484df9bb5219fb882d has fixed the merge conflict

### CODE REVIEW

**Comment by marc-hb** [comment]
@singalsu the testbench is reporting some worrying memory errors in this branch

https://github.com/thesofproject/sof/actions/runs/4209803419/jobs/7307029813

**Comment by marc-hb** [comment]
> https://github.com/thesofproject/sof/commit/94a816735c6c35a0ae1518484df9bb5219fb882d has fixed the merge conflict

The conflict happened because this PR skips @lyakh's commit 6c94904f3d13 "smart_amp: fix buffer acquisition".

https://github.com/thesofproject/sof/commits/main/src/audio/smart_amp

Are you sure you want to skip that commit? It says "fix" :-)

**Comment by singalsu** [comment]
> @singalsu the testbench is reporting some worrying memory errors in this branch
> 
> https://github.com/thesofproject/sof/actions/runs/4209803419/jobs/7307029813

Unrelated to this PR but similar has happened before too. I have not been able to replicate it. How can I see which SOF commit was used for test build?

**Comment by johnylin76** [comment]
> > [94a8167](https://github.com/thesofproject/sof/commit/94a816735c6c35a0ae1518484df9bb5219fb882d) has fixed the merge conflict
> 
> The conflict happened because this PR skips @lyakh's commit [6c94904](https://github.com/thesofproject/sof/commit/6c94904f3d130bae67f4f4897a4a7e2a9196c4b5) "smart_amp: fix buffer acquisition".
> 
> https://github.com/thesofproject/sof/commits/main/src/audio/smart_amp
> 
> Are you sure you want to skip that commit? It says "fix" :-)

Thanks @marc-hb I think you're right. It's more effective and secure to cherry-pick https://github.com/thesofproject/sof/commit/6c94904f3d130bae67f4f4897a4a7e2a9196c4b5 "smart_amp: fix buffer acquisition" back as well prior to https://github.com/thesofproject/sof/pull/7048. There is no merge conflict to solve then.

**Comment by lgirdwood** [comment]
@mwasko fyi, should this go to cavs 2.5 branch only now ?

**Comment by mwasko** [comment]
> @mwasko fyi, should this go to cavs 2.5 branch only now ?

@johnylin76 we are completing the transition to cavs2.5-001-drop-stable, so please submit any new backport commits there.

**Comment by cujomalainey** [comment]
closing since we can't move branches, need to remake this

**Comment by marc-hb** [comment]
> > https://github.com/thesofproject/sof/actions/runs/4209803419/jobs/7307029813

> Unrelated to this PR but similar has happened before too. I have not been able to replicate it. How can I see which SOF commit was used for test build?

The "build testbench" build logs show the full SHA1 of the merge commit; I made sure of that for situations like these. github.com lets you fetch full, 40-digit SHA1 directly. Put a branch or tag on it after fetching it because github will likely garbage collect it after a while.

**Pull request closed without merging**
