### PR TITLE
Dockerfile: add AMD/Vangogh gcc toolchain

### PR DESCRIPTION
**Pull request by saisurya-ch**
Add AMD/Vangogh gcc toolchain in Dockerfile.

### CODE REVIEW

**Review by sunilkumardommati — APPROVED** [review]

**Review by kv2019i — APPROVED** [review]

**Review by dbaluta — APPROVED** [review]

**Comment by dbaluta** [comment]
One thing to notice is that for previous AMD boards you used  short form `rn rmb` and  now `vangogh` long form.

**Comment by kv2019i** [comment]
@marc-hb  or @fredoh9 , can one of you ack?

**Comment by saisurya-ch** [comment]
> One thing to notice is that for previous AMD boards you used short form `rn rmb` and now `vangogh` long form. But other than that looks good to me.

There is no short form defined for the vangogh platform in our organization, we are using the keyword 'vangogh' itself.

**Review by lgirdwood — APPROVED** [review]
@kv2019i @marc-hb reminds me we need to remove old Intel platforms after this PR is merged.

**Comment by marc-hb** [comment]
> @kv2019i @marc-hb reminds me we need to remove old Intel platforms after this PR is merged.

If you look at the git log you can see this was done by @lyakh (probably without testing) and then it took a significant effort to undo it so we don't have to branch the docker image for stable-v2.2. Let's please not go through that again :-)

**Review by btian1 — APPROVED** [review]

**Comment by lgirdwood** [comment]
@fredoh9 is out. Lets take this forward.

**Comment by fredoh9** [comment]
I have started the build for new docker image. I will update the docker image tomorrow.

**Comment by fredoh9** [comment]
As of 2:30 PM PST, thesofproject/sof:latest_ubuntu22.04 has this change
Different tag is thesofproject/sof:20230716_ubuntu22.04.

**Pull request merged**
