### PR TITLE
Math: FFT: Save RAM in bit reverse lookup and fix a potential build issue

### PR DESCRIPTION
**Pull request by singalsu**

### CODE REVIEW

**Comment by ShriramShastry** [comment]
> @ShriramShastry @andrula-song any comments ? @singalsu can we build this module in Kconfig menu or does it need a user to SELECT it ?

This module, in my opinion, should be built into the Kconfig menu. Because it is compatible with any audio component.

However, I don't see a Kconfig menu build option having any affect. So it appears to me that it is up to the user to SELECT it.

Say alsabat-test.sh requires analysis of audio components such as DC information, signal harmonics, noise duration, and new features like as MFCC. It would be beneficial if we used FFT, but I don't believe we are currently doing so.

**Comment by singalsu** [comment]
> > @ShriramShastry @andrula-song any comments ? @singalsu can we build this module in Kconfig menu or does it need a user to SELECT it ?
> 
> This module, in my opinion, should be built into the Kconfig menu. Because it is compatible with any audio component.
> 
> However, I don't see a Kconfig menu build option having any affect. So it appears to me that it is up to the user to SELECT it.
> 
> Say alsabat-test.sh requires analysis of audio components such as DC information, signal harmonics, noise duration, and new features like as MFCC. It would be beneficial if we used FFT, but I don't believe we are currently doing so.

Currently MFCC component select does select of FFT and other dependencies. So when MFCC is selected the firmware builder does not need to know the dependencies. I think everything in FFT in that aspect is OK. There also a unit test.

**Comment by andrula-song** [comment]
Looks good to me.

**Review by aiChaoSONG — APPROVED** [review]

**Comment by ShriramShastry** [comment]
> 

Then we are good with the change!!

**Pull request merged**
