### PR TITLE
RTNR: Remove unused variable that will cause the failure of compiling

### PR DESCRIPTION
**Pull request by MingJenTai**

### CODE REVIEW

**Review by lgirdwood — APPROVED** [review]
@MingJenTai thanks, fwiw we do need some stubs for the 3rd party wrappers that we can add to the CIU and catch this sort of issue.

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by MingJenTai** [comment]
> @MingJenTai thanks, fwiw we do need some stubs for the 3rd party wrappers that we can add to the CIU and catch this sort of issue.

We will provide RTNR stub libraries. Thanks.

**Review by lyakh — CHANGES_REQUESTED** [review]
oh, this is a result of some bad rebase on my side, sorry... Please, drop this, I'll push a fix ASAP

**Comment by lyakh** [comment]
@MingJenTai please check #6067

**Comment by MingJenTai** [comment]
> @MingJenTai thanks, fwiw we do need some stubs for the 3rd party wrappers that we can add to the CIU and catch this sort of issue.
Hi @lgirdwood, could the stubs provided in binary form and put in a separate sub-folder under `src/audio/rtnr/rtklibs` ?

**Pull request closed without merging**
