### PR TITLE
west.yml: update Zephyr to 460c2167e4f3

### PR DESCRIPTION
**Pull request by kv2019i**
Contains 800+ commits merged after 3.5.0 release, including following directly affecting SOF targets:

f4cb487b79f9 modules: sof: Options only when module is available
02deea0e806a ace: alh: Only ACE1.5 has OSEL feature
f0326f72498c tests: dma_loopback: Intel ADSP ACE15 disable PM
adf6d0e3d80e soc: intel_adsp: lpsram enable retention mode
eeb4f2f76d6d soc: intel_adsp: hpsram enable retention mode
16f729214b50 soc: intel_adsp: lpsram init refactor
112611378f85 soc: intel_adsp: hpsram init refactor
cdd4d8470323 xtensa: add custom mem range check functions

### CODE REVIEW

**Comment by kv2019i** [comment]
This should fix https://github.com/thesofproject/sof/issues/8345

**Review by plbossart — APPROVED** [review]
Blanket approval since it enables LNL in CI

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
@keqiaozhang @marc-hb fyi - not seeing any results in CI, however status is reported.

**Comment by kv2019i** [comment]
@tmleman There's a fail in Intel QB with test_113_02_simple_internal_loopback on two platforms. Any idea if this could be related to the SRAM retention patches? Seems a bit farfetched, but I can't see other PRs on Zephyr side having on impact here.

**Comment by marc-hb** [comment]
SOFCI TEST

**Comment by tmleman** [comment]
> @tmleman There's a FrequencyMismatch / LowQuality fail in Intel QB with test_113_02_simple_internal_loopback on two platforms. Any idea if this could be related to the SRAM retention patches? Seems a bit farfetched, but I can't see other PRs on Zephyr side having on impact here.
> 
> https://sof-ci.01.org/sof-pr-viewer/#/build/PR8386/build13001973

Indeed farfetched when you take into account that there are changes that directly affect the ssp :) it will work if you will revert this https://github.com/zephyrproject-rtos/zephyr/pull/62596

Retention mode can affect performance, but I made manual test and there is regression on MTL in terms of SSP introduced by the PR mentioned above.

There was a question about the correct value of `DAI_INTEL_SSP_FIFO_DEPTH` that no one answered. Maybe this is the problem?

**Comment by kv2019i** [comment]
Thanks @tmleman , I had missed that patch. @ujfalusi can you take a look?

**Comment by kv2019i** [comment]
More time is needed to find a good fix for the SSP drain problem, so for now, we'll revert the SSP changes https://github.com/zephyrproject-rtos/zephyr/pull/64458 and @ujfalusi will follow-up with a version of the patch that passes QB loopback test. This will unblock the Zephyr update to SOF in the meantime, but we'll need to wait until 64458 is merged.

**Comment by kv2019i** [comment]
v2 update:
 - one SSP driver PR reverted, this should fix the QB test for now (base don test runs down with just revert alone)

**Comment by kv2019i** [comment]
All clean now, proceeding with merge.

**Pull request merged**
