### PR TITLE
west.yml: upgrade Zephyr to 2e66fac6d3ff 

### PR DESCRIPTION
**Pull request by kv2019i**
Update to newer Zephyr baseline,ssee details in commit description.

### CODE REVIEW

**Comment by kv2019i** [comment]
Sparse/build results look a lot better with this newer Zephyr baseline.

It seems we do have some new sparse problem that is not really related to cache-correctness:
```
/zep_workspace/zephyr/include/zephyr/toolchain.h:133:2: error: "Endiannes mismatch"
/zep_workspace/zephyr/include/zephyr/toolchain.h:133:2: error: "Endiannes mismatch"
/zep_workspace/zephyr/include/zephyr/toolchain.h:133:2: error: "Endiannes mismatch"
```

**Comment by marc-hb** [comment]
> It seems we do have some new sparse problem that is not really related to cache-correctness:

Easily bisected and reproduced without SOF, see: https://github.com/zephyrproject-rtos/zephyr/pull/51666#issuecomment-1304269131

**Comment by marc-hb** [comment]
"Don't blame the messenger" - the new check seems to reveal an old but hidden problem with `-DSPARSE=y`. When compiling with additional `#error` details added by
- https://github.com/zephyrproject-rtos/zephyr/pull/51979

you get:
```
west build  -p -b intel_adsp_cavs25 samples/hello_world/ -- -DSPARSE=y

zephyr/toolchain.h: error: "Kconfig/toolchain endianness mismatch:"
zephyr/toolchain.h: error: "CONFIG_LITTLE_ENDIAN but __ORDER_BIG_ENDIAN__"
```

**Review by abonislawski — CHANGES_REQUESTED** [review]
Do not merge yet, Internal CI fw load tests failed for this PR, make sure it will pass along with copier test.

The new revision is very important to update (great progress in our tests pass rate for MTL) but there is a bug somewhere

On MTL drop stable branch we have fresh zephyr revision with one commit reverted in zephyr:
https://github.com/thesofproject/sof/tree/mtl-002-drop-stable

**Comment by abonislawski** [comment]
Fix pushed here:
https://github.com/zephyrproject-rtos/zephyr/pull/52014

**Comment by lgirdwood** [comment]
@abonislawski Zephyr PR now merged. Good to approve ?

**Comment by kv2019i** [comment]
@lgirdwood  Let me update the PR, I need to update this to include the fix.

**Comment by kv2019i** [comment]
V2 update
- updated to newer Zephyr (includes the critical fix from Adrian)
- sparse failures still there -> I don't think we should block upstream rebase to this, we need to sort out the sparse failures in parallel

**Review by abonislawski — APPROVED** [review]
@lgirdwood @kv2019i MTL CI pass (fwload, copiers, src, etc), good for me

**Review by iuliana-prodan — APPROVED** [review]

**Comment by kv2019i** [comment]
Proceeding with merge. Sparse is now broken and needs fixes urgently, but we can't stay on old Zephyr for this.

**Pull request merged**
