### PR TITLE
[SKIP CI] TEST phantom check "gcc-build-only (sue jsl tgl)" IGNORE

### PR DESCRIPTION
**Pull request by marc-hb**
Testing github actions after #6227 merge

Signed-off-by: Marc Herbert <marc.herbert@intel.com>

### CODE REVIEW

**Comment by marc-hb** [comment]
Still a phantom "gcc-build-only (sue jsl tgl)" line after it's been removed from .github/workflows/pull-request.yml in #6227... this is crazy

Screenshot 2022-08-31 at 14 13 27

**Comment by fredoh9** [comment]
@marc-hb if you are looking at "gcc-build-only (sue jsl tgl)" , it is from jenkins job.
Current GCC platforms to build from local server are byt cht bdw apl cnl icl jsl tgl tgl-h. Don't remember where "sue jsl tgl" are came from.(still searching)

**Comment by marc-hb** [comment]
Phantom line still present in (unrelated) #6238

**Comment by marc-hb** [comment]
Thanks to a tip I noticed that the phantom and never running check `gcc-build-only (sue jsl tgl)` is marked as "required" while the newer and shorter version `Main Actions / gcc-build-only (tgl)` is not!

@lgirdwood or any other admin please share the "required checks" that should be found somewhere near https://github.com/thesofproject/sof/settings/branches

**Comment by lgirdwood** [comment]
> @lgirdwood or any other admin please share the "required checks" that should be found somewhere near https://github.com/thesofproject/sof/settings/branches

aha - there was a lingering "check" for jsl which has now been deleted. Lets see if this works for next PRs

**Comment by marc-hb** [comment]
Indeed this was all caused by `main` branch protection rules in https://github.com/thesofproject/sof/settings/branches.

Removing the corresponding protection rules made the problem instantly go away on all affected PRs (no need to force push or anything).

**Pull request closed without merging**
