### PR TITLE
Fix test bench scripts

### PR DESCRIPTION
**Pull request by xiulipan**
Add status check and fix type size check.
re-enable the test bench check in Travis

fix https://github.com/thesofproject/sof/issues/2752

### CODE REVIEW

**Comment by xiulipan** [comment]
@singalsu It seems we got vol host test bench failed 

```
error: loading controls
error: parsing topology
debug: ipc and scheduler initialized
debug: topology parsing start
debug: type: 8, size: 0x70 count: 1 index: 0
debug: type: 5, size: 0x680 count: 6 index: 1
debug: number of DAPM widgets 6
debug: loading widget PCM0P id 11
debug: registered file comp driver
debug: file_new()
debug: loading widget PGA1.0 id 4
debug: registered comp driver for volume
debug: opening shared lib libsof_volume.so
debug: loading widget BUF1.0 id 16
debug: loading widget  id 4
debug: loading widget  id 0
info: Widget type not supported 0
error: loading widget
debug: topology parsing end
```

**Comment by singalsu** [comment]
Strange, I'm able to run volume component tests this way:

```
cd tools/test/audio
octave
process_test('volume', 16, 16, 48e3);

```
Though I have not rebased today. Is your testbench binary up-to-date?

**Comment by singalsu** [comment]
@xiulipan @lgirdwood I had the testbench up-to-date but used old test topologies, maybe two weeks old. After I re-ran today "scripts/build-tools.sh -t" the testbench volume topology parsing failed. I'll start to debug what has happened. Thanks for reporting this!

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by singalsu** [comment]
The volume volume topology parsing fix is in #2824. I'd assume the PR is in quite good shape now after some review rounds.

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by singalsu** [comment]
Why are we waiting to merge #2824 and this?

**Comment by lgirdwood** [comment]
@singalsu can you check the CI output, I'll run it again.

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by singalsu** [comment]
@lgirdwood The fails above look unrelated. I tested it also locally. With git master from today and this patch applied this run passes now:

```
$ scripts/host-testbench.sh 
==========================================================
test volume with ./volume_run.sh 16 16 48000 zeros_in.raw volume_out.raw
volume test passed!
volume_out size check passed!
==========================================================
test src with ./src_run.sh 32 32 44100 48000 zeros_in.raw src_out.raw
src test passed!
src_out size check passed!
==========================================================
test eqiir with ./eqiir_run.sh 16 16 48000 zeros_in.raw eqiir_out.raw
eqiir test passed!
eqiir_out size check passed!


```

**Comment by xiulipan** [comment]
@lgirdwood @singalsu I re trigger the Travis test check if the testbench can work now.

**Comment by lgirdwood** [comment]
@xiulipan looks like the CI version of xtensa-buildall.sh is missing some machines from the build. It's an unrelated failure. Jenkins is usual issues.

**Comment by xiulipan** [comment]
@lgirdwood What is missed here? I do not see any issue in `sof-ci/jenkins`

**Comment by lgirdwood** [comment]
@xiulipan it could be a stale result. I've seen this before.

**Pull request merged**
