### PR TITLE
cherry-pick: cavs: memory bank powerup flow adjustment

### PR DESCRIPTION
**Pull request by johnylin76**
cherry-pick #7083 from rpl-001-drop-stable

### CODE REVIEW

**Comment by lgirdwood** [comment]
@mwasko backport from main.

**Review by lgirdwood — APPROVED** [review]

**Comment by mwasko** [comment]
@johnylin76 I think @abonislawski was faster and already backported this commit, please check branch tree.

**Comment by cujomalainey** [comment]
I can see it on this branch already, thanks @johnylin76

**Comment by cujomalainey** [comment]
@mwasko does this affect non cavs25 platforms? I.e. does it need to go into stable v2.x branches?

**Comment by mwasko** [comment]
> @mwasko does this affect non cavs25 platforms? I.e. does it need to go into stable v2.x branches?

That is a good point, this fix apply to all cAVS targets. @lgirdwood will you coordinate backport of this fix to our stable v2.x branch?

**Pull request closed without merging**
