### PR TITLE
Stable v2.2: Cherry pick topology updates for SoundWire, APL/GLK with ES8336,  and RPL

### PR DESCRIPTION
**Pull request by mengdonglin**
Cherry pick the following topology updates from main branch to stable-v2.2 branch:
- 3e2ccba070a2f076f5b1bf3c1a48ebe84cba994e topology: add sof-rpl-nocodec.tplg
- 1ae91d17e7d5452c3bc9821f4324bf36162dc359 topology: add sof-rpl-rt711 and sof-rpl-rt711-4ch topologies
- 3de7d2b0d186d94bed8ca938c209dd679cb5cac8 topology: Add platform definition file for Intel Raptor Lake
- 5cdc25babc639621d34b00ec5b58255c68f88d43 topology1: add SSP1 for all ES8336, SSP5 for APL/GLK
- ed43328f46b1e7b6440f80eb51c18506bb24619b topology1: CMakeLists: add missing APL/GLK support for ES8336 with DMIC.
- b262943a33a22ec8849f3a9dbdc7f6bf70a3a011 topology1: sof-tgl-rt711-rt1308: use EXT_AMP_REF for rt1316
- 0a72a066d5460c95b4b928e3f9f5815989d17d9d topology1: sof-tgl-rt711-rt1308: make BT_OFFLOAD a CMakeFiles parameter
- 4d93b4e14b1053e6aab30d0182d8678c55934a0d topology1: CMakeLists: add topology for HP Omen 16
- 2830b81825d3bbf473c3d841012b4a3334317c38 topology1: sof-tgl-rt711-rt1308: make amplifier link configuration
- fb422aca69ca5e0fcd1fcc97f9f543903ace141d topology1: generate new sof-hda-generic version for 2ch PDM1
- c8c8212876616b63bec8da600da91b7c7f9a0310 topology1: intel-generic-dmic: add macro to enable PDM1 for 2ch cases
- 5a015ca85298a2326cf53919302c75235191b659 topology1: sof-tgl-rt711-rt1308: add missing switch

### CODE REVIEW

**Comment by mengdonglin** [comment]
@plbossart @kv2019i Can you please review if these topology updates are good for SOF v2.2? Thanks!

**Review by kv2019i — APPROVED** [review]
Thanks @mengdonglin !

**Comment by keqiaozhang** [comment]
SOFCI TEST

**Comment by mengdonglin** [comment]
@kv2019i @plbossart @lgirdwood  Jenkins CI test fails because the Jenkins CI has compatible issue to support old building scripts for Zephyr before #6005. @keqiaozhang is fixing CI so that CI will check SOF code base and support both Zephyr building scripts. It may take a few more days.

**Review by lgirdwood — APPROVED** [review]
@plbossart wont merge until you can check and are happy we are not missing any topology.

**Review by plbossart — APPROVED** [review]

**Comment by marc-hb** [comment]
BTW @aborisovich this is exactly why I requested a new `--version` flag in #6005, thanks for it.

**Pull request merged**
