### PR TITLE
[DO NOT MERGE]topology: sof-apl-pcm-512x: remove HDMI pipelines

### PR DESCRIPTION
**Pull request by ranj063**
Remove the HDMI pipelines from the topology. These will be added when the iDisp topology is loaded.

This change is to test the linux PR https://github.com/thesofproject/linux/pull/1200 which separates the SSP audio and iDisp audio into separate clients.

### CODE REVIEW

**Comment by ranj063** [comment]
SOFCI TEST

**Comment by xiulipan** [comment]
@ranj063 can you try to remove the draft flag for this PR? it seems the SOFCI is sitll using https://github.com/thesofproject/sof/commit/99e33cdce28990d28fc3bae5c44cb59b1e20c5cf which do not have sof-dmic* files.

```
This branch has conflicts that must be resolved
Only those with write access to this repository can merge pull requests.
Conflicting files
tools/topology/sof-apl-nocodec.m4
tools/topology/sof-glk-da7219.m4
```

And no-wonder why ci is not testing the latest code, the merge is blocked.

**Comment by lgirdwood** [comment]
@ranj063 any ETA on when this will be mergeable status ?

**Comment by ranj063** [comment]
> @ranj063 any ETA on when this will be mergeable status ?

@lgirdwood the first part of the multi-client is almost ready now. This should follow right after.

**Comment by paulstelian97** [comment]
Any progress? You will need to resubmit it due to changed base branch.

**Pull request closed without merging**
