### PR TITLE
audio: google: Fix AEC mock

### PR DESCRIPTION
**Pull request by mtrulsson**
Backport from main to fix aec mock.
Main branch commit
https://github.com/thesofproject/sof/commit/74fd2914991a59eeb7229aeed321294434ce03e9

### CODE REVIEW

**Comment by sofci** [comment]
Can one of the admins verify this patch?
> reply **test&nbsp;this&nbsp;please** to run this test once

**Comment by gkbldcig** [comment]
Can one of the admins verify this patch?

**Comment by lgirdwood** [comment]
test this please

**Review by lgirdwood — APPROVED** [review]
@mwasko fyi backport.

**Pull request merged**
