### PR TITLE
Audio: Copier: optimize the usage of read frag

### PR DESCRIPTION
**Pull request by andrula-song**
Optimize the read frag of copier module in function
apply_attenuation. By using the optimized function
audio_stream_samples_without_wrap_s32, we can reduce
the address judgment and save about 60% cycles.

Signed-off-by: Andrula Song <xiaoyuan.song@intel.com>

### CODE REVIEW

**Comment by andrula-song** [comment]
There is the test result by xtensa testbench, the apply_attenuation is the old version, the apply_attenuation1 is the new version, save about 60% cycles.
copier-60%

**Comment by andrula-song** [comment]
SOFCI TEST

**Comment by lgirdwood** [comment]
@ArsenEloglian @mwasko @abonislawski @mwasko fyi - something to locally try.

**Review by abonislawski — APPROVED** [review]

**Review by lyakh — APPROVED** [review]

**Comment by lgirdwood** [comment]
@wszypelt can you check the CI, not expecting this to fail on the copy to DUT. Thanks
@marcinszkudlinski fyi - one to backport for DMIC work.

**Comment by wszypelt** [comment]
@lgirdwood Sure, It should work now, unfortunately there is a long queue for testing, so it will take a while, up to two hours.

**Comment by andrula-song** [comment]
@lgirdwood 
sorry， the previous comment didn't show up again.
@andrula-song will copier benefit from hifi3/4 updates ?
-->the main thing that copier does is pcm converter and apply_attenuation. The HiFi version of pcm converter we are using now can be optimized by reducing the address check, but not from HiFi 4 intrinsic.

**Comment by andrula-song** [comment]
> @lgirdwood Sure, It should work now, unfortunately there is a long queue for testing, so it will take a while, up to two hours.

**Comment by andrula-song** [comment]
@wszypelt 
can you help check the CI again？ the failed case seems to be a FPGA loading error

**Comment by andrula-song** [comment]
I wanna use a new PR to add hifi version implementation of function apply_attenuation, which can save 74% cycles than the original version, but there is a error in rimage/src/pkcs1_5.c in latest code. So I will generate new PR after this fixed.

**Comment by lgirdwood** [comment]
> I wanna use a new PR to add hifi version implementation of function apply_attenuation, which can save 74% cycles than the original version, but there is a error in rimage/src/pkcs1_5.c in latest code. So I will generate new PR after this fixed.

Some rimage fixes recently merged, pls make sure your rimage submodule is up to date.

**Pull request merged**
