### PR TITLE
topology1: development: add generic sof-tgl-max98373-rt5682 for SOF CI

### PR DESCRIPTION
**Pull request by fredoh9**
TGL Delbin/Voxel chromebook use sof-tgl-max98373-rt5682. Same devices
is SOF CI need generic and 3rd party library free topology. This is a
copy from cab732872 and commented Maxim Smart Amp. If I pick up latest
commit, it has build time errors or runtime errors.

Signed-off-by: Fred Oh <fred.oh@linux.intel.com>

### CODE REVIEW

**Comment by fredoh9** [comment]
This is original sof-tgl-max98373-rt5682.tplg
sof-tgl-max98373-rt5682 tplg

This is my sof-tgl-max98373-rt5682-ci.tplg
sof-tgl-max98373-rt5682-ci tplg

**Comment by fredoh9** [comment]
This is why I go down to cab732872(and disable MAXIM Smart amp).
```
fredoh@fred-coffee:~/work/sof/20210601/tools/topology$ git log --oneline sof-tgl-max98373-rt5682.m4
9ae018b9f topology: max98373-rt5682: define dmic 48k core id  ==> topology DMIC loading error
926661400 audio: igo_nr: igo_nr support 48k
776977852 topology: Added IGO_NR in sof-tgl-max98373-rt5682 topology.
05eb73e4c topology: sof-tgl-max98373-rt5682: add Bluetooth audio offload support   ==> aplay on PCM hw:0,6 failed at 1/1.
cab732872 topology: adding support for IIR component
```

**Comment by plbossart** [comment]
sorry, what?
There's already a generic file for this, I use it for my Volteer device. What's different between Volteer and Delbin?

**Comment by plbossart** [comment]
> sorry, what?
> There's already a generic file for this, I use it for my Volteer device. What's different between Volteer and Delbin?

Sorry, which version of delbin is this? SoundWire or I2S? 

If this is I2S, why can't you use tools/topology/topology1/sof-tgl-max98373-rt5682.m4
If this is SoundWire, why can't you use tools/topology/topology1/sof-tgl-sdw-max98373-rt5682.m4

**Comment by plbossart** [comment]
> sof-tgl-max98373-rt5682.m4 need maxim library included fw.

No it doesn't. We use it TODAY in our daily tests for Volteer, and there're a mockup of the Maxim library.

Could it be that you are confusing the OEM version of the topology with the one we have in our public tree?

**Comment by fredoh9** [comment]
> Could it be that you are confusing the OEM version of the topology with the one we have in our public tree?

https://github.com/thesofproject/sof/blob/63eda919d3fd5f40d097804bdd13c25fb3ac24ac/tools/topology/topology1/sof-tgl-max98373-rt5682.m4#L69

Is this OEM version of topology? Due to this line, sof-tgl-max98373-rt5682.tplg is only for maxim smart amp. It looks like this topology is hard-coded for OEM chrome device.

Do we need to make this configurable based on a parameter?

**Comment by plbossart** [comment]
I can't figure out what the issue is.

I am 100% positive that for the Volteer SoundWire version we did include a mockup of the smartamp, see topology below.

It could very well be that the Volteer I2S version makes an explicit reference to the 3rd party library. That would be a bug. The SOF public tree SHALL NOT make any references to private libraries.

@ranj063 @sathya-nujella can you help on this one?

sof-tgl-sdw-max98373-rt5682

**Comment by fredoh9** [comment]
Closing this, new pr is submitted. https://github.com/thesofproject/sof/pull/4637

**Pull request closed without merging**
