### PR TITLE
 Topology: HDA-generic: Use +20 dB EQ gain for DMIC capture pipelines

### PR DESCRIPTION
**Pull request by singalsu**
This pull request adds to stable-v1.5 the updates for DMIC capture gain those have been applied to master branch.

### CODE REVIEW

**Comment by lgirdwood** [comment]
@zrombel we have 2 PRs now for stable-v1.5 branch that are failing some CI tests. How does CI deal with the stable branch and how do we bisect the 6 commits to find out which one is breaking the tests.

**Comment by zrombel** [comment]
Hi, the 1.5 branch is missing SOF_VOLUME_LINEAR_ZC ramp implementation and pyhon tests are aligned to it that is why so many test are failing. I will check it manually and give you feedback.

**Comment by zrombel** [comment]
Ok, I forced older test repo to run and now all test pass.

**Comment by lgirdwood** [comment]
Jenkins showing a failed DUT for CML.

**Pull request merged**
