### PR TITLE
intel_adsp: ace: enable clock gating

### PR DESCRIPTION
**Pull request by tmleman**
Zephyr version update + enabling of the clock gating in ACE platforms

### CODE REVIEW

**Review by lgirdwood — COMMENTED** [review]
LGTM

**Comment by tmleman** [comment]
`codestyle/checkpatch` reports a problem only to the word used in the commit title in zephyr.

**Review by kv2019i — APPROVED** [review]

**Review by dnikodem — APPROVED** [review]

**Review by jxstelter — APPROVED** [review]

**Review by softwarecki — APPROVED** [review]

**Comment by kv2019i** [comment]
Ready to go, but need to analyze why Intel System/merge/build CI step failed.

**Comment by abonislawski** [comment]
Please verify this failing test before merge

**Review by btian1 — APPROVED** [review]

**Comment by kv2019i** [comment]
I can see @tmleman you triggered a new build. Let's see the results. Looking at the previous run, there seems to be this:

```
[    4.178738] <err> zephyr: cpu_disable_core: core 1 did not enter idle state
[    4.178745] <err> ipc: ipc4_module_process_dx: failed to disable core 1
[    4.178748] <err> ipc: ipc_cmd: ipc4: MODULE_MSG failed with err 6
```

This seems like a case of https://github.com/thesofproject/sof/issues/8588 so not specific to this PR necessarily.

**Comment by tmleman** [comment]
@kv2019i Yes, previous Fail seems to be not related to the enabling of the clock gating. I wasn't able to reproduce it locally and CI test rerun shows that it has sporadic nature.

**Comment by kv2019i** [comment]
Need to check the one fail in https://sof-ci.01.org/sofpr/PR8597/build1037/devicetest/index.html to see if it's a known thing, otherwise this looks good to go.

**Comment by kv2019i** [comment]
@kv2019i wrote:
> Need to check the one fail in https://sof-ci.01.org/sofpr/PR8597/build1037/devicetest/index.html to see if it's a known thing, otherwise this looks good to go.

So that seems to be a case of 8510. No DSP or kernel error, but no data received in user-space in one case (and on a secondary core, like 8510). So I'll proceed with merge.

**Pull request merged**
