### PR TITLE
TEST IGNORE BREAK topologies with some whitespace

### PR DESCRIPTION
**Pull request by marc-hb**
This breaks newer ALSA versions.

This is a test for
- #5640

### CODE REVIEW

**Comment by marc-hb** [comment]
ICL is failing again in https://sof-ci.01.org/sof-pr-viewer/#/build/PR5639/build8993664 @kkarask ... really unreliable.

**Comment by marc-hb** [comment]
- It's possible to find what failed in https://github.com/thesofproject/sof/runs/5795828416 but the output is a bit confusing. 
https://github.com/thesofproject/sof/runs/5795952965 is now more verbose and not interleaved, easier to read.


- The failures in the highly parallel installer "checktree" target are TOTALLY impossible to find:
https://github.com/thesofproject/sof/runs/5795828482
When combined with #5640 the first failure is now very clear: https://github.com/thesofproject/sof/runs/5795952923


- testbench logs https://github.com/thesofproject/sof/runs/5795828928 (before) and https://github.com/thesofproject/sof/runs/5795953370 (after) are both truncated and way too short the same, not sure why. This works for me locally.

**Comment by marc-hb** [comment]
https://sof-ci.01.org/sofpr/PR5639/build12607/devicetest/ shows a very misleading "not available (hardware)"

**Comment by sys-pt1s** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
