### PR TITLE
Topology: Topology2: Add sof-hda-benchmark-src32-<platform>

### PR DESCRIPTION
**Pull request by andrula-song**
This patch adds build of hda-generic development topologies to test SRC component with s32 format.

### CODE REVIEW

**Comment by andrula-song** [comment]
SOFCI TEST

**Comment by andrula-song** [comment]
SOFCI TEST

**Review by singalsu — APPROVED** [review]
Looks good, thanks! Is it possible to add also test topologies for other than s32 format?

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
> Looks good, thanks! Is it possible to add also test topologies for other than s32 format?

Lets add incrementally.

**Pull request merged**
