### PR TITLE
tools: tune: eq: abi bumb

### PR DESCRIPTION
**Pull request by juimonen**
Bump abi for eq to match firmware.

Signed-off-by: Jaska Uimonen <jaska.uimonen@intel.com>

### CODE REVIEW

**Comment by juimonen** [comment]
@lgirdwood the blob contains the abi header. so changing the header changes the blob

**Comment by lgirdwood** [comment]
So are we saying that this change is needed for EQ to work or is this only to align minor ABI numbers ?

**Comment by ranj063** [comment]
@juimonen @singalsu will this make the data incompatible with previous fw versions?

**Comment by juimonen** [comment]
@lgirdwood @ranj063 so currently the eq doesn't work at all, because fw is in 3.1.0 and eq is in 3.0.0. I'm not totally aware of the design. I guess the eq blob abi header is compared against the firmware abi header, if mismatch -> no work. I'm not sure how the backwards compatibility is supposed to work.

**Comment by ranj063** [comment]
> @lgirdwood @ranj063 so currently the eq doesn't work at all, because fw is in 3.1.0 and eq is in 3.0.0. I'm not totally aware of the design. I guess the eq blob abi header is compared against the firmware abi header, if mismatch -> no work. I'm not sure how the backwards compatibility is supposed to work.

@juimonen if you look in the fw (i think the ipc handler does it), it checks if the FW ABI version matches exactly  with that of the data. Does this need a bit of tweaking? I'd assume 3:0:0 eq data might still be compatible with 3:X:0? isn it?
Also, I'd assume that the same eq data might be compatible with multiple versions of the FW right? so should we add mix/max abi versions in the eq data and check against that in the fw?

**Comment by juimonen** [comment]
@ranj063 yes the eq data hasn't changed at all. But the eq abi hdr is in 3.0.0 and fw in 3.1.0. So yes eq data should and will work with multiple fw abi versions.

**Comment by ranj063** [comment]
> @ranj063 yes the eq data hasn't changed at all. But the eq abi hdr is in 3.0.0 and fw in 3.1.0. So yes eq data should and will work with multiple fw abi versions.

@juimonen sounds good. could you please fix it :)

**Comment by juimonen** [comment]
seppo made a pr that's fixing this issue: https://github.com/thesofproject/sof/pull/1014
bumbing up eq abi version was wrong solution, even though it helped.

**Pull request closed without merging**
