### PR TITLE
topology1: add DMIC 48K Core ID flag to CMake for RTNR

### PR DESCRIPTION
**Pull request by sathyap-chrome**
For builds with no Hotword on DSP, generic dmic m4 is used.
RTNR is running on DMIC CORE ID 1. Hence adding the flag.

Signed-off-by: Jairaj Arava <jairaj.arava@intel.com>

### CODE REVIEW

**Comment by sofci** [comment]
Can one of the admins verify this patch?
> reply **test&nbsp;this&nbsp;please** to run this test once

**Comment by sathyap-chrome** [comment]
cc @cujomalainey

**Comment by gkbldcig** [comment]
Can one of the admins verify this patch?

**Review by cujomalainey — APPROVED** [review]

**Comment by cujomalainey** [comment]
@sathyap-chrome random question, any reason you are not part of the sof org?

**Comment by sathyap-chrome** [comment]
@cujomalainey will check with Liam on this. thanks :)

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
test this please

**Comment by lgirdwood** [comment]
Run the CI. @cujomalainey yeah, I also thought @sathyap-chrome was a member given his activity level. Now fixed.

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by lgirdwood** [comment]
Try the other CI command and try and unblock.

**Comment by cujomalainey** [comment]
@lgirdwood well based on the name I am pretty sure he is a Intel member :)

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by lgirdwood** [comment]
Restart CI to unblock

**Comment by lgirdwood** [comment]
@kkarask @wszypelt looks like CI could be blocked ? Could someone check. Thanks !

**Comment by cujomalainey** [comment]
CI is failing even though change is not tested by it. Merging as this is needed for milestone @jairaj-arava please cherry-pick to ADL-004

**Pull request merged**
