### PR TITLE
[TEST] decompose "trace: move CONFIG_TRACEM implementation up a couple levels"

### PR DESCRIPTION
**Pull request by plbossart**
DO NOT MERGE

This is just a split in 3 of @marc-hb 's changes. I believe the changes impacting suspend-resume are in the last patch.

@ranj063 can you try this on CML_HELIOS? I will try on CML_SDW.

### CODE REVIEW

**Comment by plbossart** [comment]
And no joy without the third commit, so now the only hypothesis is the use of va_args that might be problematic?

**Comment by marc-hb** [comment]
Tried va_copy but it didn't work, see https://github.com/thesofproject/sof/issues/4558#issuecomment-888684096

**Comment by lgirdwood** [comment]
> And no joy without the third commit, so now the only hypothesis is the use of va_args that might be problematic?

Could be - I'm seeing different trace output between GCC and XCC on #4566 based on latest dmesg.

**Comment by plbossart** [comment]
I also get a fail on device hw:0,4 with the first patch that changes the va_args. I will redo the test since this is very surprising.

````
2021-07-28 21:56:03 UTC [COMMAND] arecord -Dhw:0,4 -r 48000 -c 2 -f S16_LE /dev/null -q
process: 8333 status: interruptible sleep (waiting for an event to complete)
2021-07-28 21:56:04 UTC Sub-Test: [INFO] Current suspend/resume type mode: [s2idle] deep
2021-07-28 21:56:05 UTC Sub-Test: [INFO] ===== Round(1/100) =====
2021-07-28 21:56:05 UTC Sub-Test: [COMMAND] Run the command: rtcwake -m mem -s 5
rtcwake: assuming RTC uses UTC ...
rtcwake: wakeup from "mem" using /dev/rtc0 at Wed Jul 28 21:56:12 2021
2021-07-28 21:56:12 UTC Sub-Test: [COMMAND] sleep for 5
2021-07-28 21:56:17 UTC Sub-Test: [INFO] Check for the kernel log status
declare -- cmd="journalctl_cmd --since=@1627509360"
2021-07-28 21:56:17 UTC [ERROR] Caught kernel log error
===========================>>
[ 1223.546644] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: error: hda_dsp_stream_trigger: cmd 0: timeout on STREAM_SD_OFFSET read
<<===========================

````

**Comment by lgirdwood** [comment]
@plbossart fwiw, I think the va_ code is all in libgcc, so is compiler dependent - I would bet that the Cadence XCC version is optimized for xtensa. The other thing is we seem to be getting more trace messages coming in GCC mode, meaning there is more data (maybe due to va_list parsing ??)

**Comment by plbossart** [comment]
I can confirm that the commit using va_args is enough to fail this test.

````
commit 6faa9c39a57a6e3f463f4626a634b135bc1397e1 (HEAD -> fix/cml_suspend_resume_2)
Author: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
Date:   Wed Jul 28 16:11:05 2021 -0500

    trace: use va_args
    
    First part of trace: move CONFIG_TRACEM implementation up a couple levels
    
    Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
````

At this point I would recommend a revert and redo. It's rather unlikely that we are going to figure this one out.

@ranj063 @lgirdwood any objection?

**Comment by plbossart** [comment]
Revert added in #4573

**Pull request closed without merging**
