### PR TITLE
KPB: add dummy .params method

### PR DESCRIPTION
**Pull request by mrajwa**
Signed-off-by: Marcin Rajwa <marcin.rajwa@linux.intel.com>

### CODE REVIEW

**Comment by lgirdwood** [comment]
Why ? Can you explain in commit message why we need this (especially since it does nothing).

**Comment by mrajwa** [comment]
@lgirdwood, its not about what it does but rather whether it exist at all - when the pipeline is mounted it looks like .params method of all components is called. The lack of it, of course causes DSP error. 
So as for now, I don't need any action in this method but we need it to exist (have valid pointer).

**Comment by ranj063** [comment]
@mrajwa thats exactly the reason. You need it because it is propagated through the pipeline and every component in the pipeline needs to define it even if it doesnt do anything. I filed an issue to fix this: https://github.com/thesofproject/sof/issues/1087

Basically, if the ops are not defined, we should return 0

**Comment by lgirdwood** [comment]
@mrajwa ok, #1087 is the preferred fix.

**Comment by keyonjie** [comment]
> @mrajwa ok, #1087 is the preferred fix.

@lgirdwood #1087 is the issue, this PR is the fix for it.

**Comment by ranj063** [comment]
@keyonjie this PR is a workaround not the real fix. We need to cover the bases.

**Comment by mrajwa** [comment]
@ranj063, this PR isn't workaround is it? Of course .params doesn't do much now but that's because we haven't agreed on its use.

**Comment by ranj063** [comment]
@mrajwa sorry what I meant was we shouldnt need an empty params callback in a component. We should return a 0 or a pertinent error in case it is a mandatory callback like new() for example instead of adding methods which do nothing just to avoid errors.

**Comment by mrajwa** [comment]
@ranj063, yes, that would be more elegant way.  However in case of KPB I am sure we will need it at some point anyway. After all there is a reason why this method is called on every component by default.

**Comment by ranj063** [comment]
> @ranj063, yes, that would be more elegant way. However in case of KPB I am sure we will need it at some point anyway. After all there is a reason why this method is called on every component by default.

if you ask me params is probably not a mandatory callback for every component. We propagate the params upstream/downstream and copy the params for every component before invoking this callback. Some comps might not want to do anything in this callback.

**Comment by ranj063** [comment]
BTW this isnt anything new that I'm asking for. We do this for every single ops in the kernel.

**Comment by ranj063** [comment]
@mrajwa so I'd say if you absolutely need this dummy params for integration, we should merge it to the integration branch but really fix #1087 for master

**Comment by lgirdwood** [comment]
@mrajwa this wont be merged into master. The correct fix is to check the ops before the call.

**Comment by mrajwa** [comment]
@lgirdwood, yes I agree.

**Pull request closed without merging**
