### PR TITLE
boards: ace20/ace30: disable KCPS dynamic clock control

### PR DESCRIPTION
**Pull request by abonislawski**
KCPS must be disabled until full perf measurement data for audio modules is provided.

Copier example:

> #if CONFIG_METEORLAKE
> 	mod_cfg = [1, 0, 0, 0, 280, 4918000, 768, 768, 0, **4918**, 0,
> 			2, 0, 0, 0, 280, 6526000, 768, 768, 0, **6526**, 0,
> 			...
> 			42, 0, 0, 0, 280, 5350000, 384, 192, 0, **5350**, 0]
> #elif defined(CONFIG_LUNARLAKE) || defined(CONFIG_PANTHERLAKE)
> 	mod_cfg = [ 0, 0, 0, 0, 280, 640100, 45, 60, 0, **0**, 0,
> 			...
> 			9, 0, 0, 0, 280, 4941000, 192, 256, 0, **0**, 0]
> #endif

### CODE REVIEW

**Review by marcinszkudlinski — APPROVED** [review]

**Review by dnikodem — APPROVED** [review]

**Review by tmleman — APPROVED** [review]

**Review by wszypelt — APPROVED** [review]

**Review by lgirdwood — APPROVED** [review]
@abonislawski I guess a python script that could read logs and determine the KCPS for each format, config ?

**Comment by abonislawski** [comment]
> @abonislawski I guess a python script that could read logs and determine the KCPS for each format, config ?

I remember there was additional run in linux CI for performance build tests and I can see "daily_performance" run on MTL only but not sure if there was something developed to parse it

**Comment by wszypelt** [comment]
Internal Intel CI System/merge/build - all green, good to merge

**Comment by kv2019i** [comment]
sof-docs fail and Intel LNL fails all known and tracked in https://github.com/thesofproject/sof/issues?q=is%3Aissue+is%3Aopen+label%3ACI

**Pull request merged**
