### PR TITLE
cmake: don't trust CI to record time and versions and log ourselves

### PR DESCRIPTION
**Pull request by marc-hb**
In an ideal world, every CI engine records and shares the most important
CI information:
- current date and time in a well identified timezone
- git version of the pull request
- git version of the moving branch the PR is being merged with

In the real world we have multiple CI solutions and they unfortunately
cannot not all be trusted to perform their most basic job
correctly. Fortunately, they all make at least build logs available so
these very few lines of code adding very few lines of output cost near
zero extra build time and solve the problem once for all. I feel stupid
I didn't do this sooner, this would have saved me hours and hours in
vain requests and discussions and in trying to puzzle that information
together.

Sample outputs
```
-- Preparing Xtensa toolchain
version.cmake starting SOF build at 2021-03-31T18:09:46Z UTC
Building git commit with parent(s):
150fd1e4c968 4249bdb1b305 [2nd parent if merge] (HEAD -> main) cmake: ...
-- GIT_TAG / GIT_LOG_HASH : v1.7-rc1-174-g150fd1e4c968-dirty / 150fd1e4c968
```

From https://github.com/thesofproject/sof/pull/3996/checks?check_run_id=2239525672, xtensa-build-all.sh
```
-- version.cmake starting SOF build at 2021-03-31T20:01:47Z UTC
-- Building git commit with parent(s):
5ad5c7d0c eb459078f 83d425817 (HEAD, pull/3996/merge) Merge 83d42581779c4da872e9d635962436ab1752c853 into eb459078f3023f6762428f38976547576eeae59f
-- GIT_TAG / GIT_LOG_HASH : v1.7-rc1-166-g5ad5c7d0c573 / 5ad5c7d0c
-- Source content hash: 55ed85fe
```
Other examples at https://sof-ci.01.org/sofpr/PR3996/build8556/build/

Signed-off-by: Marc Herbert <marc.herbert@intel.com>

### CODE REVIEW

**Comment by marc-hb** [comment]
https://sof-ci.01.org/sofpr/PR3996/build8553/devicetest/ has many failures on TGLH_RVP_HDA and many devices unavailable, @fredoh9 is looking into it.

https://github.com/thesofproject/sof/runs/2240264557?check_suite_focus=true has some wrong checkpatch about the commit message that I really cannot fix.

Everything else was green but I just force-pushed version 2 (83d4258) with some enhancements.

**Comment by marc-hb** [comment]
The main (but not only) offender is of course QuickBuild. Results like https://sof-ci.01.org/sof-pr-viewer/#/build/PR3993/build6245042 have no (or very well hidden) version or date information which is especially time consuming considering the QuickBuild scheduler takes hours to run or is sometimes completely stuck like it was in the last ~24h. Looks like @zrombel got it running again.

See sample waste of time in https://github.com/thesofproject/sof/pull/3993#issuecomment-811247580

**Comment by marc-hb** [comment]
SOFCI TEST

**Comment by marc-hb** [comment]
> https://sof-ci.01.org/sofpr/PR3996/build8553/devicetest/ has many failures on TGLH_RVP_HDA and many devices unavailable, @fredoh9 is looking into it.

General CI outage quickly fixed by @fredoh9 , thanks a lot !

https://sof-ci.01.org/sofpr/PR3996/build8557/devicetest/?model=CML_HEL_RT5682&testcase=check-suspend-resume-5 is the usual suspend/resume TIMEOUT and https://sof-ci.01.org/sofpr/PR3996/build8557/devicetest/?model=CML_RVP_SDW&testcase=check-suspend-resume-with-playback is
```
[  893.168194] kernel: e1000e 0000:00:1f.6 enp0s31f6: Hardware Error
```
I think we don't use `e1000e`, we should probably disable it. No other errors at https://sof-ci.01.org/sofpr/PR3996/build8557/devicetest and these two are obviously unrelated to this PR.

**Review by lgirdwood — APPROVED** [review]

**Review by dbaluta — APPROVED** [review]

**Comment by marc-hb** [comment]
See below "you need to rebase" most common CI misconception and confusion between `pull/12345/head` and `pull/12345/head`:

https://github.com/thesofproject/sof/pull/3990#issuecomment-811942451

**Pull request merged**
