### PR TITLE
[DO NOT MERGE] A test PR

### PR DESCRIPTION
**Pull request by xiulipan2**
A test PR

Signed-off-by: Pan Xiuli <xiuli.pan@linux.intel.com>

### CODE REVIEW

**Comment by sofci** [comment]
Can one of the admins verify this patch?

**Comment by xiulipan2** [comment]
> Can one of the admins verify this patch?

@lgirdwood @plbossart @mengdonglin @marc-hb Please check the auto generated question commit from Jenkins CI.
Please check the following guide about this feature.

```
Commands: 

When a new pull request is opened in the project and the author of the pull request isn't white-listed, builder will ask "Can one of the admins verify this patch?".

"ok to test" to accept this pull request for testing
"test this please" for a one time test run
"add to whitelist" to add the author to the whitelist

If the build fails for other various reasons you can rebuild.

"retest this please" to start a new build
```

**Comment by xiulipan** [comment]
test this please

**Comment by xiulipan** [comment]
It worked. I accept the test for one time https://sof-ci.01.org/sofpr/PR3661/build7731/
I will force push and update this PR to let you have a try too.

**Comment by plbossart** [comment]
> > Can one of the admins verify this patch?
> 
> @lgirdwood @plbossart @mengdonglin @marc-hb Please check the auto generated question commit from Jenkins CI.
> Please check the following guide about this feature.
> 
> ```
> Commands: 
> 
> When a new pull request is opened in the project and the author of the pull request isn't white-listed, builder will ask "Can one of the admins verify this patch?".

What does this mean and what are you trying to fix @xiulipan?
To create a pull request, you have to be a member of the SOF project.
Why do we need to vouch for our own contributors?
This seems like extra work for no good reason.

Also please use denylist/allowlist if this is actually needed.

**Comment by lgirdwood** [comment]
@xiulipan2 @xiulipan I assume you are expecting CI not to run as success ? If so, it looks correct to me.

**Comment by gkbldcig** [comment]
test comment

**Comment by gkbldcig** [comment]
TESTING

**Comment by gkbldcig** [comment]
TESTING2

**Comment by gkbldcig** [comment]
TESTING2

**Comment by gkbldcig** [comment]
TESTING

**Comment by gkbldcig** [comment]
Can one of the admins verify this patch? - test

**Comment by zrombel** [comment]
test comment to be deleted

**Comment by gkbldcig** [comment]
Can one of the admins verify this patch? - test

**Comment by xiulipan** [comment]
test this please

**Pull request closed without merging**
