### PR TITLE
xtensa-build-zephyr.py: objcopy --remove-section .comment zephyr.strip

### PR DESCRIPTION
**Pull request by marc-hb**
Make stripped ELF files compiled by XCC identical across different machines.

Some Xtensa compilers (ab?)use the .ident / .comment section and append the typically absolute and not
reproducible /path/to/the.c file after the usual
compiler ID.

https://sourceware.org/binutils/docs/as/Ident.html

strip --strip-all does not remove the .comment section. Remove ourselves like some gcc test scripts do:

 https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=c7046906c3ae

Signed-off-by: Marc Herbert <marc.herbert@intel.com>

### CODE REVIEW

**Comment by marc-hb** [comment]
Note this commit does not affect `.ri` files at all, it only makes finding differences easier.

**Comment by lgirdwood** [comment]
@marc-hb I assume this wont strip the image ELF file (i.e. the file we point gdb to when debugging) ?

**Comment by marc-hb** [comment]
> @marc-hb I assume this wont strip the image ELF file (i.e. the file we point gdb to when debugging) ?

Correct, unstripped files are left unmodified, always have been.

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
@aborisovich good for Windows ?

**Comment by marc-hb** [comment]
We need this for the 2.4 release branch

**Review by kv2019i — APPROVED** [review]

**Pull request merged**
