### PR TITLE
installer: (re)build firmware, topologies and user space tools

### PR DESCRIPTION
**Pull request by marc-hb**
Multiple commits, see commit messages

One-touch "make -C installer stage rsync" combines fast incremental build,
staging and deploy in one command.

None of the errors in  https://sof-ci.01.org/sofpr/PR3862/build8189/devicetest/ are related.

### CODE REVIEW

**Comment by cujomalainey** [comment]
how hard would it be to give the installer a remote target?

**Comment by marc-hb** [comment]
Thanks @cujomalainey  for looking at this, really appreciated. It's hard to find reviewers in general and for some reason this sort of change is even less popular :-)

> how hard would it be to give the installer a remote target?

This was already implemented in previous PR #3845 and how I performed some final tests again for this PR.

If you expand `installer/sample-config.mk` here you will see achieving this is just a couple lines of configuration away.

If you have corrections or suggestions on that part of the code then please feel free commenting on #3845. Unlike other people I do pay attention to comments on closed/merged reviews and bugs, even more so when I was the one submitting them.

**Comment by cujomalainey** [comment]
> Thanks @cujomalainey for looking at this, really appreciated. It's hard to find reviewers in general and for some reason this sort of change is even less popular :-)

No worries, i wouldnt have seen the change actually if you hadn't stealth added me as a code review in #3791 😉 I think github might have a bug there.

> 
> > how hard would it be to give the installer a remote target?
> 
> This was already implemented in previous PR #3845 and how I performed some final tests again for this PR.
> 
> If you expand `installer/sample-config.mk` here you will see achieving this is just a couple lines of configuration away.

Awesome! @bzhg @johnylin76 FYI (who also a lot of remote device work.)

> 
> If you have corrections or suggestions on that part of the code then please feel free commenting on #3845. Unlike other people I do pay attention to comments on closed/merged reviews and bugs, even more so when I was the one submitting them.

I will do a deeper reviewer later today/tomorrow, but I wont deny, I am by not means a bash expert.

**Comment by marc-hb** [comment]
> No worries, i wouldnt have seen the change actually if you hadn't stealth added me as a code owner in #3791 😉 I think github might have a bug there.

Off-topic sorry but did you double-check your notification settings?

**Comment by marc-hb** [comment]
I re-submitted the first 2 commits independently in PR #3870 . 3870 is just some basic un-hardcoding in `scripts/xtensa-build-all.sh` and `scripts/build-tools.sh`. It's much smaller and hopefully easier and faster to review  and would get some (minor) git conflict with something else out of the way. Thanks in advance!

**Review by lgirdwood — APPROVED** [review]

**Comment by marc-hb** [comment]
Thanks @lgirdwood . BTW I successfully tested this with xt-xcc, meaning this one liner compiles and stages a directory ready to deploy to /lib/firmware or sof-bin:

```
XTENSA_TOOLS_ROOT=/my/Xtensa make -C installer/

make -C installer/ rsync
```
You can even use `make -j3` for building multiple platforms concurrently. Github Actions now do that in 2 minutes. It makes the logs unreadable though, remove `-j` in case of error.

@fredoh9 could you add or show me how to add `tree` to the docker image?

**Comment by cujomalainey** [comment]
> > No worries, i wouldnt have seen the change actually if you hadn't stealth added me as a code owner in #3791 😉 I think github might have a bug there.
> 
> Off-topic sorry but did you double-check your notification settings?

Forgot to reply to this, im set for all mentions, but i wasn't mentioned in the PR itself, only in the code, and github doesn't seem to auto cc affected codeowners on the owners file

**Pull request merged**
