### PR TITLE
topology2: cavs-nocodec-multicore: run DMIC pipelines on core1

### PR DESCRIPTION
**Pull request by yongzhi1**
For MTL platform, config DMIC pipeline on coreX for CI test.

### CODE REVIEW

**Comment by ranj063** [comment]
@yongzhi1 this is not ready for prime time yet with SOF main. @Rander has a separate PR with a test topology for this

**Comment by yongzhi1** [comment]
V2:

Add DMIC option to sof-mtl-nocodec-multicore for CI test.
Verified DMIC working 1st time, same issue as reported in https://github.com/thesofproject/sof/issues/7108

**Comment by yongzhi1** [comment]
V3:

Rebased, verified with 005-drop-stable.

**Comment by yongzhi1** [comment]
V4:
- Start with PASSTHROUGH=true.

**Review by RanderWang — APPROVED** [review]

**Review by ranj063 — APPROVED** [review]

**Comment by kv2019i** [comment]
https://sof-ci.01.org/sofpr/PR7580/build9453/devicetest/index.html and https://sof-ci.01.org/sofpr/PR7580/build9454/devicetest/index.html have known errors, proceednig with merge.

**Pull request merged**
