### PR TITLE
dmic: switch to use uncached dmic_prm[]

### PR DESCRIPTION
**Pull request by keyonjie**
When multi-core introduced, we need to use uncached address for the
global configuration variables, to make sure they are consistent for all
DSP cores.

Signed-off-by: Keyon Jie <yang.jie@linux.intel.com>

### CODE REVIEW

**Comment by aiChaoSONG** [comment]
verified on one TGLU NOCODEC RVP device

**Review by singalsu — APPROVED** [review]
Looks good, thanks Keyon!

**Comment by keyonjie** [comment]
looks it lead to some regression on APL platforms, let me debug it.

**Review by lgirdwood — APPROVED** [review]
Good work everybody !

**Comment by lgirdwood** [comment]
@keyonjie looks like this is failing on unrelated tests ?

**Comment by keyonjie** [comment]
> @keyonjie looks like this is failing on unrelated tests ?

It is actually :), looks there is no write back mechanism on APL, now I change the PR to do write through when dmic_prm[] is changing and the APL works now at my end.

Let's wait for the PR validation result.

**Review by aiChaoSONG — APPROVED** [review]

**Comment by keyonjie** [comment]
looks good now @lgirdwood

**Pull request merged**
