### PR TITLE
submodule: update rimage to its main branch

### PR DESCRIPTION
**Pull request by mrajwa**
This updates SoF rimage submodule to the current TOP
of main branch. Namely from 246ea64 to 8960097, delta change log:

8960097 (HEAD -> main, upstream/main) Revert "ext_manifest: Fix incorrect signature"
0d7f2d4 Do not exit(0) on invalid options or parameters
6e22944 README.md: explain how to run SOF tests on new rimage code
a9faf85 remove '-x' option
241af31 ext_manifest: Fix incorrect signature
4823e87 pkcs: quote the name of key file when logging it
dcfcef8 config: Remove unused, platform specific, memory region definitions
fc4d7b8 rimage: Fix error message content after adsp malloc fail
3e20076 config: Return error value in parse_uint32_* functions when key is not found
ada30c1 config: Explicit state return value for error cases in parse_uint32_* functions
de9177b config: Adjust return type with function name
c4a7456 config: Remove machine_id field
916fc2c config: Remove unused adsp structs
9bf46d3 rimage: Add support for mt8195
aea1969 adsp_config: fix potential overflow in strtol()
9716e10 (origin/master, origin/main) config: Add imx8ulp.toml
b28b993 fixing incorrect data offset in ri_manifest_sign_v1_5
d1553e9 config: add rn toml file to support renoir build
246ea64 config: skl: change image_size to the real SRAM size

Signed-off-by: Marcin Rajwa <marcin.rajwa@linux.intel.com>

### CODE REVIEW

**Comment by mrajwa** [comment]
@marc-hb, I have updated both commit message and PR description with the commits delta between current version and the one we update to.

**Review by marc-hb — APPROVED** [review]
Thanks! Having the last SHA in the Subject would be even better but having everything in the commit message is good and enough. So much easier than jumping around the two repos.

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
Looks like CI got stuck. rerun it.

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by marc-hb** [comment]
https://sof-ci.01.org/sofpr/PR4792/build10445/devicetest is all green

(earlier https://sof-ci.01.org/sofpr/PR4792/build10440/devicetest/ did not complete indeed)

**Comment by plbossart** [comment]
merging at @marc-hb 's request to make sure we still have one full business day to revert before the week-end.

**Pull request merged**
