### PR TITLE
dp: start DP tick fixup

### PR DESCRIPTION
**Pull request by marcinszkudlinski**
This is fixup for 689e8e999f220356f69b8532216790fed18a9da4

Incorrect list pointer has been used

### CODE REVIEW

**Review by tmleman — APPROVED** [review]

**Review by kv2019i — APPROVED** [review]

**Comment by kv2019i** [comment]
Hmm, the MTLP_RVP_HDA fail is a bit odd. Let me rerun the SOF driver CI once. Otherwise good to go.

**Comment by kv2019i** [comment]
SOFCI TEST

**Review by btian1 — APPROVED** [review]

**Comment by kv2019i** [comment]
Hmm, no responses. :( I'll rerun CI third time, but unless somebody confirm HDA fail can be ok'ed, I'm not going to merge this.

**Comment by kv2019i** [comment]
SOFCI TEST

**Comment by kv2019i** [comment]
Ok, test passed now, merging.

**Pull request merged**
