### PR TITLE
Fix kmod scripts

### PR DESCRIPTION
**Pull request by plbossart**
Deal with missed codecs, new ones for SoundWire support and renaming of PCI/ACPI modules done by Jaroslav (the last part is required for tests with this week's upstream merge).

### CODE REVIEW

**Comment by plbossart** [comment]
> LGTM, just please add missing dot at end of 2nd sentence in 1st commit's description.

wow, we've come a long ways from not having any commit description in most of SOF patches to tracking periods at the end of the 2nd sentence :-)

**Comment by plbossart** [comment]
> > LGTM, just please add missing dot at end of 2nd sentence in 1st commit's description.

@jajanusz done

**Comment by jajanusz** [comment]
SOFCI TEST

**Comment by jajanusz** [comment]
SOFCI TEST

**Pull request merged**
