### PR TITLE
Add Waves codec into the main branch

### PR DESCRIPTION
**Pull request by CyKuei**
Add Waves codec into the main branch

Add Waves override config for tigerlake_chrome.
Enable codec_adapter and Waves codec.

Signed-off-by: CY Kuei <cyk@waves.com>

### CODE REVIEW

**Comment by sofci** [comment]
Can one of the admins verify this patch?
> reply **test&nbsp;this&nbsp;please** to run this test once

**Review by dbaluta — APPROVED** [review]

**Comment by gkbldcig** [comment]
Can one of the admins verify this patch?

**Comment by lgirdwood** [comment]
test this please

**Review by lgirdwood — APPROVED** [review]

**Comment by CyKuei** [comment]
Is this PR ready for being merged?

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by lgirdwood** [comment]
@CyKuei sorry, it looks like CI got stuck, I've restarted it.

**Comment by lgirdwood** [comment]
@kkarask @wszypelt looks like CI is stuck, can you restart. Thanks !

**Pull request merged**
