### PR TITLE
UUID trace

### PR DESCRIPTION
**Pull request by lyakh**
implement and use "%pU[bBlL]" kernel style UUID format strings

### CODE REVIEW

**Review by lgirdwood — APPROVED** [review]
I guess this aligns SOF UUID printf formatters with standard UUID formatters ?

**Comment by lyakh** [comment]
> I guess this aligns SOF UUID printf formatters with standard UUID formatters ?

@lgirdwood I don't know whether there are "standard" UUID formatters. POSIX printf(3) https://www.unix.com/man-page/POSIX/3posix/snprintf/ doesn't have anything like that. Looks like the Linux kernel implementation is an extension, and yes, this patch follows it.

**Comment by lgirdwood** [comment]
@lyakh can you fix the conflicts - I think we are good to merge

**Comment by lyakh** [comment]
> @lyakh can you fix the conflicts - I think we are good to merge

@lgirdwood done, waiting for CI

**Pull request merged**
