### PR TITLE
Transfer rimage git history to subdirectory tools/rimage/ in the sof git repo

### PR DESCRIPTION
**Pull request by marc-hb**
DO NOT "REBASE and MERGE" this PR! See below.

This PR merges rimage back into the sof git repo, see #8178, #7270 + others why.

The Github interface has always struggled with large PRs. It also shows the oldest commits first :-( But some of it can still be used: go to the "Files Changed" tab, click on "Changes from all commits" then scroll all the way down past all the original rimage commits. Then review only the last 8 commits, one by one.

Every commit can build Zephyr, XTOS and user space tools. It is possible to `git checkout` back and forth across this transfer without any submodule error and git bisectability is preserved. Each commit was tested one by one in test PR #8286

DO NOT "REBASE and MERGE" this PR!

This PR includes the entire rimage history (about 300 commits) thanks to `git merge --allow-unrelated-histories`. Trying to rebase merge commits fails at best and results in some non-sensical git history at worse. So, do not "rebase and merge" this PR, it must be merged _as is_. If that's not possible, a maintainer with WRITE permission must manually push it like this:
```
git fetch origin pull/8297/merge
git checkout FETCH_HEAD
git log --graph
# Very rare race condition with other maintainers merging other PRs.
# If that push is not fast-forward then just restart from the top.
# Do NOT force push!
git push origin HEAD:refs/heads/main 
```

cc:
- #8178
- #7270
- #8243
- #7304

### CODE REVIEW

**Comment by marc-hb** [comment]
Fix for unrelated LP64 failure https://github.com/thesofproject/sof/actions/runs/6461743791/job/17542047048?pr=8297 already submitted in #8295

**Review by RanderWang — APPROVED** [review]
LGTM

**Review by kv2019i — APPROVED** [review]

**Review by aiChaoSONG — APPROVED** [review]
Thanks, Marc

**Review by softwarecki — APPROVED** [review]
Impressive work!

**Comment by kv2019i** [comment]
Merged with a direct push, closing the PR.

**Comment by marc-hb** [comment]
Note you can easily import/cherry-pick code changes from the old standalone rimage repo into SOF:

```shell
cd sof
git remote add old-location rimage
git fetch old-location
git cherry-pick HEAD..old-location/main
```

This works because I imported the whole rimage history and because file renames are very easy for git to find in this particular case.

**Comment by cujomalainey** [comment]
glad to see im not the only one who likes to preserve history :)

**Pull request merged**
