### PR TITLE
V2.8.1 candidate

### PR DESCRIPTION
**Pull request by jsarha**
The PR has contents of #8741 and #8740 PRs cherry-picked (with -xs and in this order) on top of current stable-v2.8.

### CODE REVIEW

**Review by kv2019i — APPROVED** [review]

**Review by lgirdwood — APPROVED** [review]

**Comment by kv2019i** [comment]
Uh, @marc-hb  this is a bit of a problem -> https://sof-ci.01.org/sofpr/PR8855/build2660/build/firmware_community/tgl.log .. probably we need to cherry-pick the deployable-build changes as well or otherwise we can't build stable-2.8 binaries anymore....

**Comment by marc-hb** [comment]
New --deployable flag cherry-picked in #8858, which fixes the "unknown deployable flag" build failure. However this now fails later at deployment time, let's discuss in #8858.

**Comment by marc-hb** [comment]
#8858 fixes the --deployable issue but it exposes the next issue: we need @ujfalusi to backport the sof-ace-tplg + sof-avs-tplg merge.

**Comment by marc-hb** [comment]
SOFCI TEST

**Comment by marc-hb** [comment]
> https://github.com/thesofproject/sof/pull/8858 fixes the --deployable issue but it exposes the next issue: we need @ujfalusi to backport the sof-ace-tplg + sof-avs-tplg merge.

I did a tentative, minimal backport in #8861. It's passing the tests.

**Comment by marc-hb** [comment]
SOFCI TEST

**Comment by marc-hb** [comment]
Unfortunately, neither ACE results in https://sof-ci.01.org/sofpr/PR8855/build2720/devicetest/index.html nor CAVS results in https://sof-ci.01.org/sofpr/PR8855/build2721/devicetest/index.html are looking good with a similarly looking ASSERTION FAIL in both:

```
[  546.262043] <inf> ll_schedule: zephyr_ll_task_schedule_common: task add 0xa01167c0 0x20210U priority 0 flags 0x0
[  546.262073] <inf> ll_schedule: zephyr_domain_register: zephyr_domain_register domain->type 1 domain->clk 3 domain->ticks_per_ms 38400 period 1000
[  546.262263] <inf> dma_intel_adsp_gpdma: intel_adsp_gpdma_power_on: intel_adsp_gpdma_power_on: dma dma@7c000 initialized
[  546.262448] <inf> pipe: pipeline_trigger: pipe:0 0x0 pipe trigger cmd 7
[  546.262458] <inf> ll_schedule: zephyr_ll_task_schedule_common: task add 0xa0117440 0x20210U priority 0 flags 0x0
[  546.263228] <inf> host_comp: host_get_copy_bytes_normal: comp:0 0x4 no bytes to copy, available samples: 0, free_samples: 192
[  547.285151] <inf> ll_schedule: zephyr_domain_thread_fn: ll core 0 timer avg 1418, max 3871, overruns 0
[  548.309151] <inf> ll_schedule: zephyr_domain_thread_fn: ll core 0 timer avg 1401, max 1827, overruns 0
[  549.333150] <inf> ll_schedule: zephyr_domain_thread_fn: ll core 0 timer avg 1401, max 1830, overruns 0
[  550.357151] <inf> ll_schedule: zephyr_domain_thread_fn: ll core 0 timer avg 1402, max 1825, overruns 0
[  551.381151] <inf> ll_schedule: zephyr_domain_thread_fn: ll core 0 timer avg 1401, max 1827, overruns 0
[  551.475780] <inf> ipc: ipc_cmd: rx	: 0x48000000|0x12
ASSERTION FAIL [!z_smp_cpu_mobile()] @ ZEPHYR_BASE/subsys/pm/pm.c:133
[  552.215233] <err> os: print_fatal_exception:  ** FATAL EXCEPTION
[  552.215241] <err> os: print_fatal_exception:  ** CPU 0 EXCCAUSE 63 (zephyr exception)
[  552.215248] <err> os: print_fatal_exception:  **  PC 0xa0065dfb VADDR (nil)
[  552.215253] <err> os: print_fatal_exception:  **  PS 0x60020
[  552.215270] <err> os: print_fatal_exception:  **    (INTLEVEL:0 EXCM: 0 UM:1 RING:0 WOE:1 OWB:0 CALLINC:2)
[  552.215276] <err> os: xtensa_dump_stack:  **  A0 0xa0064418  SP 0xa010b310  A2 0x4  A3 0xa010b320
[  552.215281] <err> os: xtensa_dump_stack:  **  A4 0xa010b300  A5 0x4  A6 0xfffbfff0  A7 0x4
[  552.215288] <err> os: xtensa_dump_stack:  **  A8 0xa0064362  A9 0xa010b2a0 A10 0xa00d9467 A11 0xa010b320
[  552.215293] <err> os: xtensa_dump_stack:  ** A12 0xa010b300 A13 0x4 A14 (nil) A15 0xffffffff
[  552.215298] <err> os: xtensa_dump_stack:  ** LBEG 0xa006344b LEND 0xa0063458 LCOUNT 0xa003669e
[  552.215305] <err> os: xtensa_dump_stack:  ** SAR 0xc
```

**Comment by kv2019i** [comment]
One known multicore fail in https://sof-ci.01.org/sofpr/PR8855/build2720/devicetest/index.html?model=MTLP_RVP_NOCODEC&testcase=multiple-pause-resume-50 , rest looks good. Merging.

**Comment by marc-hb** [comment]
> One known multicore fail...

Is it #8642? Logs look a bit different...

The massive "no bytes to copy" log spam (#8761) admittedly makes it very hard to identify anything

**Pull request merged**
