### PR TITLE
[skip ci] installer: add tgl-h

### PR DESCRIPTION
**Pull request by marc-hb**
add tgl-h

Signed-off-by: Marc Herbert <marc.herbert@intel.com>

### CODE REVIEW

**Review by fredoh9 — APPROVED** [review]
looks good.

**Review by keyonjie — APPROVED** [review]

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
@zrombel fyi - looks like the pr codec test is failing here for unrelated. Btw, this one should skip the CI too.

**Comment by lgirdwood** [comment]
@marc-hb btw, which CIs should this skip ? look like some have run, so I'm assuming this is for skipping runtime testing only ?

**Comment by zrombel** [comment]
@lgirdwood QB is not looking at [skip ci] in PR title, but i've added 'installer' folder to list that testing will be skipped for. BTW there was a QB issue and all tests was failing. Right now reruns are in progress. But this PR looks like good to be merged.

**Comment by marc-hb** [comment]
> BTW there was a QB issue and all tests were failing. Right now reruns are in progress.

https://sof-ci.01.org/sof-pr-viewer/#/build/PR3910/build6149818 shows no CODEC test at all?!

**Comment by marc-hb** [comment]
> [skip ci] should have been called [skip sof-ci/jenkins] or something similar and shorter.

Forgot this sorry: `[skip ci]` _does_ leave `sof-ci/jenkins` in a "hanging forever" state for now, that's expected. @aiChaoSONG / @fredoh9 do we already have internal (and low priority...) issue to address this eventually? I see 486 but it is a bit different.

**Comment by zrombel** [comment]
@marc-hb About missing tests in https://sof-ci.01.org/sof-pr-viewer/#/build/PR3910/build6149818 - I already posted a comment to Process Team task that you've created. I will make sure that there will be an appropriate info in sof_pr_viewer that test were skipped.

Regarding previous question - test are skipped if code changes are made only in ignored folders, if there is change in any file outside those folders tests will be run.

**Comment by marc-hb** [comment]
>  I will make sure that there will be an appropriate info in sof_pr_viewer that test were skipped.

Thank you this will be much better.

When nothing at all runs then it's easy to guess that everything was skipped.
When only one half is skipped without explicitly saying it was skipped then it looks like a failure because it's similar to actual failure https://sof-ci.01.org/sof-pr-viewer/#/build/PR3902/build6136537 (PTS-31172)

Long story short sof-pr-viewer should not just drop bits of the page on failure or skip, it should say "error" or "skip" instead. 

> test are skipped if code changes are made only in ignored folders, if there is change in any file outside those folders tests will be run.

👍🏼

**Pull request merged**
