### PR TITLE
[DNM]: drivers: imx: Move SAI MCLK enablement to sai_config()

### PR DESCRIPTION
**Pull request by LaurentiuM1234**
Due to the fact that MCLK is enabled after I2C's SCLK signal, the WM8962 codec seems to reach a wrong state, leading to "DC servo timeout" issue on first playback. This was observed on i.MX93 and i.MX8MP with WM8962. This commit attempts to fix this by simply moving the MCLK enablement to sai_config().

### CODE REVIEW

**Comment by LaurentiuM1234** [comment]
Made commit description and comment a bit more clearer.

**VERY IMPORTANT**: this patch was only tested on i.MX93 with simple playback, simple capture and playback with PAUSE/RESUME.

**Review by paulstelian97 — APPROVED** [review]
The change looks good. Once it's tested on 8MP with WM8962 as well I'd say it's good to merge.

**Comment by LaurentiuM1234** [comment]
Marked as [DNM] until it can also be tested on 8MP.

**Comment by sys-pt1s** [comment]
Can one of the admins verify this patch?

**Review by lgirdwood — APPROVED** [review]

**Comment by LaurentiuM1234** [comment]
Marked this as a draft because it doesn't solve the issue on 8MP with WM8962.

**Comment by LaurentiuM1234** [comment]
Will close this and let @iuliana-prodan handle it as this seems to be more problematic for 8MP with WM8962.

**Pull request closed without merging**
