### PR TITLE
topology: sof-glk-da7219: add support for cs42l42

### PR DESCRIPTION
**Pull request by brentlu**
Add support for cs42l42 running on GLK boards. There is a 10 ms BCLK
delay in the master branch version to avoid the noise on TX path.
However, this feature is not supported on GLK production branch yet so
we remove it for now.

Signed-off-by: Brent Lu <brent.lu@intel.com>

### CODE REVIEW

**Comment by brentlu** [comment]
Backport https://github.com/thesofproject/sof/pull/4121 to GLK production branch

**Comment by plbossart** [comment]
the change is fine, but I am not sure the 'glk production branch' is actually maintained by anyone. Shouldn't those devices transition to the regular 'stable' branches after the initial release? I don't think anyone has a burning desire to keep maintaining one branch per device, that's quickly going to be problematic.
@cujomalainey thoughts?

**Comment by cujomalainey** [comment]
@plbossart i agree that is the plan long term once we begin kernel uprevs, but these devices are still pinned at 4.14 and we are getting new codec support so I think for the sake of handling ABI changes, I think merging to this branch is probably the best solution for integration BUT it should land on main first.

**Comment by plbossart** [comment]
> @plbossart i agree that is the plan long term once we begin kernel uprevs, but these devices are still pinned at 4.14 and we are getting new codec support so I think for the sake of handling ABI changes, I think merging to this branch is probably the best solution for integration BUT it should land on main first.

ok, it's already on main, I wasn't sure who maintains this 'glk-012-stable' branch. it's not really stable by any stretch of imagination...

**Review by plbossart — APPROVED** [review]

**Comment by lgirdwood** [comment]
@slawblauciak are you to merge into glk-012 ?

**Review by cujomalainey — APPROVED** [review]

**Review by fredoh9 — APPROVED** [review]

**Comment by brentlu** [comment]
The 10ms delay is no longer needed since COE team is working on enabling bclk earlier in hw_params. I will update the commit message.

**Review by plbossart — APPROVED** [review]
this looks good but then we will have to modify this topology immediately to add the bclk early start. So either this is merged first, and other PRs such as #4219 will have to rebase. Or we drop this PR and add the changes in #4219. please clarify how you want to proceed with the merges.

**Comment by plbossart** [comment]
> this looks good but then we will have to modify this topology immediately to add the bclk early start. So either this is merged first, and other PRs such as #4219 will have to rebase. Or we drop this PR and add the changes in #4219. please clarify how you want to proceed with the merges.

Sorry, it was meant to be https://github.com/thesofproject/sof/pull/4249 since you are requesting a merge into a product branch, not main.

**Comment by lgirdwood** [comment]
@plbossart probably best for you to also merge FW if you need to orchestrate between kernel, FW and topologies.

**Comment by plbossart** [comment]
> @plbossart probably best for you to also merge FW if you need to orchestrate between kernel, FW and topologies.

Actually I don't even think the kernel PR is required for testing since it does nothing other than exposing bitfields we don't use.
I would like one SOF PR with firmware+topology changes, so far my tests are not successful. see https://github.com/thesofproject/sof/pull/4219#issuecomment-848915644

**Comment by brentlu** [comment]
I thins we can drop this PR and use #4249 instead. Thanks.

**Pull request closed without merging**
