### PR TITLE
[DO NOT MERGE YET]topology: change HDA topologies to use dynamic pipelines

### PR DESCRIPTION
**Pull request by ranj063**
Switch HDA topologies to use dynamic pipelines

Signed-off-by: Ranjani Sridharan <ranjani.sridharan@linux.intel.com>

### CODE REVIEW

**Review by lgirdwood — APPROVED** [review]
Simple !

**Review by kv2019i — APPROVED** [review]
Kernel #2794 starts to approach merge-readiness.

**Comment by lgirdwood** [comment]
@ranj063 pleas ping when it's ready to merge.

**Comment by paulstelian97** [comment]
Please resubmit with "main" as PR base branch.

**Pull request closed without merging**
