### PR TITLE
codec_adapter: remove term "dummy" from adapters

### PR DESCRIPTION
**Pull request by cujomalainey**
Following move of open source to remove oppressive language from open
source, dummy is one of the terms to avoid. Also the term does a poor
job of describing what the adapter actually does.

Signed-off-by: Curtis Malainey <cujomalainey@chromium.org>

### CODE REVIEW

**Comment by cujomalainey** [comment]
This was only compile tested FYI with configs enabled.

**Review by dbaluta — APPROVED** [review]

**Comment by dbaluta** [comment]
I wonder if maybe `simple` codec would be a better naming. While now it only has the passtrough functionality in the future it might be used for other simple stuff.

**Review by lgirdwood — APPROVED** [review]
Passthrough is a good description.

**Comment by lgirdwood** [comment]
Unrelated kernel issue on Jenkins.

**Comment by marc-hb** [comment]
> Following move of open source to remove oppressive language from open source, dummy is one of the terms to avoid

I think you meant "offensive" here, not "oppressive".

@deb-intel can you confirm American English and culture is our reference for that purpose? That was already my impression because of terms like "blacklist"; this one seems to confirm.

In the computing context I've always seen "dummy" used in the British meaning of the world, not in the American one.

American English has a slightly different (and much larger) set of offensive terms so this question matters.

**Comment by cujomalainey** [comment]
Its on Google's list of terms to remove from chromium, since we have a mirror figured it would be best to remove it. See https://chromium.googlesource.com/chromiumos/third_party/adhd/+/3c247a7808bd47381a89ddb9e00c2459bd4fe7e1

**Comment by marc-hb** [comment]
I don't understand that adhd commit message : even in American English "dummy" does not refer to a category of people, does it? I understand American English "dummy" as: "as stupid as a [British/crash test] dummy", correct? "Stupid" does not refer to a disability or a category of people.

I understand this is not "hard science" but there has to be some logic otherwise it's very difficult to be compliant; even more so for non-Americans.

> Also the term does a poor job of describing what the adapter actually does.

I'm not questioning that  BTW, sorry for "hi-jacking" this PR with more general questions.

**Comment by cujomalainey** [comment]
I did not pick the terms so I cannot say definitely why it is on the list. That being said definition #3 when you search define dummy is "a stupid person"

**Comment by dbaluta** [comment]
@cujomalainey @marc-hb  as a non-native english speaker this discussion looks rather confusing. All my life I learned from books titled 'X for dummies' and they were really practical.

first world problems :)

**Comment by marc-hb** [comment]
> That being said definition #3 when you search define dummy is "a stupid person"

Of course telling a _person_ they're as smart as a toaster is _offensive_ and totally unacceptable. That does not make the word "toaster" offensive when referring to a toaster. And there's obviously no _group of persons oppressed_ because of their toaster level of intelligence.

I hope I'm missing something cultural here about that particular word but for now it looks like banning "dummy" is counter-productive because discrediting the action on other words that are actually insensitive to actual groups of people.

**Comment by paulstelian97** [comment]
> > That being said definition #3 when you search define dummy is "a stupid person"
> 
> Of course telling a _person_ they're as smart as a toaster is _offensive_ and totally unacceptable. That does not make the word "toaster" offensive when referring to a toaster. And there's obviously no _group of persons oppressed_ because of their toaster level of intelligence.
> 
> I hope I'm missing something cultural here about that particular word but for now it looks like banning "dummy" is counter-productive because discrediting the action on other words that are actually insensitive to actual groups of people.

Yeah, the master/slave conundrum and the blacklist/whitelist is also like that, only a few very vocal people are actually bothered by those words. These appear to me like just changes made for the sake of change, not actually helpful for the people who would normally be oppressed (could in fact do the opposite actually, you can't tell a black guy that he's black because it's offensive nowadays even when you refer to it in a medical form or as a disambiguation, with no malicious intent)

**Comment by deb-intel** [comment]
@marc-hb  @lgirdwood Hi all. Sorry I'm late to the discussion.

Yes, in U.S English vernacular, "dummy" has very offensive connotations and we need to remove it just as we are removing "master." Can we use another term to better describe dummy? With respect to dummy adaptor, does it refer to test or prototype? When everyone decides on a replacement word, we can modify the Woke script to include the added suggestion.

@dbaluta, yes, I've read the same "Dummies" books.  It's probably more 21st-century enlightenment than first-world problems. :)

All, please realize that the list of offensive words might grow, even if you do not yet see them listed as "Intel violators." For example, if a random search reveals that our website used the terms "retard" (meaning slow) or "niggardly" (meaning "stingy"). they will be immediately added to the Woke list and removed. 

I know this might seem annoying or silly, but it's something we need to do as representatives of Intel's inclusive-language policy.

**Comment by lgirdwood** [comment]
@deb-intel ack and thanks for your inputs. All, the TSC and SOF member companies all have inclusive language policies, lets please use them and abide by them. Please email me directly for any clarification or further discussion on this topic.

**Comment by marc-hb** [comment]
Thanks @deb-intel for the clarifications.

> Can we use another term to better describe dummy? With respect to dummy adaptor, does it refer to test or prototype? 

In the past the word "dummy" was used in code with the same meaning as a crash-test dummy: anything used instead of the real thing. I'm sure there are various alternatives depending on the context.

> When everyone decides on a replacement word, we can modify the Woke script to include the added suggestion.

Thanks, that's exactly the kind of checkpatch-style automation that is required to nail this problem. We can't ask developers from all across the world to spend a lot of time guessing about US vernacular and fragmented language policies from other companies and regularly getting it wrong. Copy/paste/diverge works neither for computer code nor for this. @deb-intel can you please point at the location of the most recent version of this script and its list of suggested alternatives? Thanks!

**Pull request merged**
