### PR TITLE
LLEXT: automatically calculate module addresses (first part of #9430)

### PR DESCRIPTION
**Pull request by lyakh**
The important change here is an automatic module address calculation, simplifies modularisation a lot.

### CODE REVIEW

**Comment by lyakh** [comment]
CI: IIUC https://sof-ci.01.org/sofpr/PR9439/build7624/devicetest/index.html unrelated, https://sof-ci.01.org/sofpr/PR9439/build7626/devicetest/index.html - one device missing

**Comment by lyakh** [comment]
Since we decided to split #9430 and since this passes tests, let's merge it

**Review by kv2019i — APPROVED** [review]

**Review by lgirdwood — APPROVED** [review]

**Comment by lyakh** [comment]
pr-build seems stuck, restarting

**Comment by lyakh** [comment]
SOFCI TEST

**Comment by lyakh** [comment]
CI: unrelated LNL failures https://sof-ci.01.org/sofpr/PR9439/build7780/devicetest/index.html

**Comment by abonislawski** [comment]
Are we now unable to set module address to IMR for one module and HPSRAM for another?

**Comment by lyakh** [comment]
> Are we now unable to set module address to IMR for one module and HPSRAM for another?

@abonislawski with this - no, with this module addresses are calculated automatically. Running in IMR needs to be added separately

**Pull request merged**
