### PR TITLE
dw-dma: revert recent changes for Baytrail

### PR DESCRIPTION
**Pull request by lyakh**
Fixes https://github.com/thesofproject/linux/issues/873

Two recent commits:

7275e422d86 ('dw-dma: handle interrupts per core')
433de9fb50c ('dw-dma: clear block/transfer irq after stop')

broke DW-DMA on Baytrail. Though they seem logical, they don't
produce the desired result on that platform. This patch restores the
original behaviour on BYT, CHT, BDW and HSW. It also eliminates the
redundant branch in the loop by replacing it with a simple mask to
restore the original IRQ processing order:

1. clear the source IRQ
2. clear the platform IRQ
3. call the callbacks

### CODE REVIEW

**Comment by plbossart** [comment]
I just tested on a CHT device and even with this PR I still get a distorted sound with beating noise on a sine waves and freq distortion on front left/right tests. This was the same as on a Baytrail device (which seems to RIP).
We'd still need to figure out when the last BKC was on Baytrail/Cherrytrail to bisect further

**Comment by plbossart** [comment]
kernel for my tests: ceec5493a8a69badb177bd24a3009b73317cbdb4
firmware: 7d8cfb7efb508604458d51c638f8d0b9a63352b8 (this PR)

**Comment by tlauda** [comment]
@lyakh Do you also see the distortions?

**Comment by wenqingfu** [comment]
@stevyan @Jiangxinx to test if this fixes thesofproject/linux#873 and if it's also the root cause of thesofproject/linux#933. @fredoh9 do you have a BYT with codec can give it a try, too?

**Comment by Jiangxinx** [comment]
I have tested this PR on BYT rt5651 and BYT nocodec platform. Can not reproduce thesofproject/linux#873 .
By the way, I also can't reproduce thesofproject/linux#933 with or without this PR on BYT rt5651.

***Kernel recipe***
linux (topic/sof-dev) : 901cd2a5

**Comment by plbossart** [comment]
> I have tested this PR on BYT rt5651 and BYT nocodec platform. Can not reproduce [thesofproject/linux#873](https://github.com/thesofproject/linux/issues/873) .
> By the way, I also can't reproduce [thesofproject/linux#933](https://github.com/thesofproject/linux/issues/933) with or without this PR on BYT rt5651.
> 
> _**Kernel recipe**_
> linux (topic/sof-dev) : 901cd2a5

Can you provide a recording of a sine wave showing that the data is correct? It's not about casual listening, you need to use specific test files such as a sine wave or a chip.

**Comment by Jiangxinx** [comment]
@plbossart I have tested on BYT nocodec platform for thesofproject/linux#933 . I still can not hear beating noise. However, the left and right chennels seem to have changed without this PR1451, and it is correct with this PR.

***step***
aplay -Dhw:0,0 -fS16_LE -c2 -r 48000 sine_48k_16bit_10s_stereo_l5_r2.wav & arecord -Dhw:0,0 -fs16_le -c2 -r48000 test_with_1451.wav -vv -i

***sine wave ***
1.original sinewave:
Screenshot from 2019-05-22 15-21-43

2.record without PR1451:
Screenshot from 2019-05-22 15-22-49

3.record with PR1451:
Screenshot from 2019-05-22 15-23-34

***Kernel recipe***
linux (topic/sof-dev) : e3ec7cf1

***sine source***
[sine_source.zip](https://github.com/thesofproject/sof/files/3206129/sine_source.zip)

**Comment by lyakh** [comment]
ping, what's the status of this PR? It fixes a specific problem, no, it does nothing to improve the audio distortion problem on BYT.

**Pull request merged**
