### PR TITLE
[SKIP CI] docker: add AMD/Rembrandt gcc toolchain

### PR DESCRIPTION
**Pull request by fredoh9**
Add AMD/Rembrandt (rmb) gcc toolchain to thesofproject/sof docker image.

Signed-off-by: Fred Oh <fred.oh@linux.intel.com>

### CODE REVIEW

**Comment by fredoh9** [comment]
Docker image thesofproject/sof:20220606 (=thesofproject/sof:latest from a few minutes ago) has this fix.

I picked up https://github.com/thesofproject/sof/pull/5833 and rebased top of today's main. I have build error for rmb with latest docker image.

```
./scripts/docker-run.sh ./scripts/xtensa-build-all.sh rmb
...
[ 43%] No install step for 'smex_ep'
[ 44%] Completed 'smex_ep'
[100%] Linking C executable rimage
[ 44%] Built target smex_ep
[100%] Built target rimage
[ 44%] No install step for 'rimage_ep'
[ 45%] Completed 'rimage_ep'
[ 45%] Built target rimage_ep
make[1]: *** [CMakeFiles/Makefile2:2154: src/arch/xtensa/CMakeFiles/bin.dir/rule] Error 2
make: *** [Makefile:814: bin] Error 2
```

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
> Docker image thesofproject/sof:20220606 (=thesofproject/sof:latest from a few minutes ago) has this fix.
> 
> I picked up #5833 and rebased top of today's main. But I have build error for rmb with latest docker image. Because of this error "./scripts/xtensa-build-all.sh -a" cannot finish the job.
> 
> ```
> ./scripts/docker-run.sh ./scripts/xtensa-build-all.sh rmb
> ...
> [ 43%] No install step for 'smex_ep'
> [ 44%] Completed 'smex_ep'
> [100%] Linking C executable rimage
> [ 44%] Built target smex_ep
> [100%] Built target rimage
> [ 44%] No install step for 'rimage_ep'
> [ 45%] Completed 'rimage_ep'
> [ 45%] Built target rimage_ep
> make[1]: *** [CMakeFiles/Makefile2:2154: src/arch/xtensa/CMakeFiles/bin.dir/rule] Error 2
> make: *** [Makefile:814: bin] Error 2
> ```

@fredoh9 are you saying we have some dependencies before merging ?

**Review by balakishorepati — APPROVED** [review]

**Comment by lgirdwood** [comment]
> @fredoh9 are you saying we have some dependencies before merging ?

Ping  - do we need to merge any other PRs before this one ?

**Comment by fredoh9** [comment]
> > @fredoh9 are you saying we have some dependencies before merging ?
> 
> Ping - do we need to merge any other PRs before this one ?

This doesn't have any dependency but I suspect rmb toolchain may need some fix(es)

**Comment by marc-hb** [comment]
I could be wrong but I believe @fredoh9 is waiting on @@balakishorepati to reproduce the error reported above.

**Comment by balakishorepati** [comment]
> I could be wrong but I believe @fredoh9 is waiting on @balakishorepati to reproduce the error reported above.



> I could be wrong but I believe @fredoh9 is waiting on @balakishorepati to reproduce the error reported above.

@marc-hb : There is no issue in rmb tool chain. But issue is due to gcc compiler was not picking the core-isa.h file which we up streamed.
We are able to compile the rmb code with the up streamed toolchain if gcc compiler is picking the proper core-isa.h file during compilation.
Any inputs are welcome to debug why compiler is taking wrong core-isa.h header file

**Comment by balakishorepati** [comment]
> > Docker image thesofproject/sof:20220606 (=thesofproject/sof:latest from a few minutes ago) has this fix.
> > I picked up #5833 and rebased top of today's main. But I have build error for rmb with latest docker image. Because of this error "./scripts/xtensa-build-all.sh -a" cannot finish the job.
> > ```
> > ./scripts/docker-run.sh ./scripts/xtensa-build-all.sh rmb
> > ...
> > [ 43%] No install step for 'smex_ep'
> > [ 44%] Completed 'smex_ep'
> > [100%] Linking C executable rimage
> > [ 44%] Built target smex_ep
> > [100%] Built target rimage
> > [ 44%] No install step for 'rimage_ep'
> > [ 45%] Completed 'rimage_ep'
> > [ 45%] Built target rimage_ep
> > make[1]: *** [CMakeFiles/Makefile2:2154: src/arch/xtensa/CMakeFiles/bin.dir/rule] Error 2
> > make: *** [Makefile:814: bin] Error 2
> > ```
> 
> @fredoh9 are you saying we have some dependencies before merging ?

@fredoh9 : Need to take below commit into sof git for rimage compilation.
https://github.com/thesofproject/rimage/commit/1b233f68bdee6de24b0447917d8d44c98970efce

**Comment by marc-hb** [comment]
> @marc-hb : There is no issue in rmb tool chain.

You're confusing me with @fredoh9 :-)

> But issue is due to gcc compiler was not picking the core-isa.h file which we up streamed.

Note there are files with all the same "core-isa.h" names everywhere: in SOF, in the toolchains, in qemu, in Zephyr HALs,.... What `#include` could possibly go wrong?

> @fredoh9 : Need to take below commit into sof git for rimage compilation.

@balakishorepati please submit an rimage submodule update in SOF. See recent and good example in 4e1d3ba61abd3bc82df3367

**Comment by balakishorepati** [comment]
> > @marc-hb : There is no issue in rmb tool chain.
> 
> You're confusing me with @fredoh9 :-)
> 
> > But issue is due to gcc compiler was not picking the core-isa.h file which we up streamed.
> 
> Note there are files with all the same "core-isa.h" names everywhere: in SOF, in the toolchains, in qemu, in Zephyr HALs,.... What `#include` could possibly go wrong?
> 
> > @fredoh9 : Need to take below commit into sof git for rimage compilation.
> 
> @balakishorepati please submit an rimage submodule update in SOF. See recent and good example in [4e1d3ba](https://github.com/thesofproject/sof/commit/4e1d3ba61abd3bc82df3367554797c7389f7ac8c)

Please find the below pull request to resolve picking up of proper core-isa.h file.
https://github.com/thesofproject/xtensa-overlay/pull/14

**Comment by lgirdwood** [comment]
> Please find the below pull request to resolve picking up of proper core-isa.h file.
> [thesofproject/xtensa-overlay#14](https://github.com/thesofproject/xtensa-overlay/pull/14)

Now merged. Not sure how CI picks up this update for overlays. @marc-hb @greg-intel what needs done here ?

**Comment by lgirdwood** [comment]
> > Please find the below pull request to resolve picking up of proper core-isa.h file.
> > [thesofproject/xtensa-overlay#14](https://github.com/thesofproject/xtensa-overlay/pull/14)
> 
> Now merged. Not sure how CI picks up this update for overlays. @marc-hb @greg-intel what needs done here ?

@balakishorepati thinking aloud, force pushing this PR again may cause the container to rebuild and pick up the new overlay. It's worth a try as @marc-hb is out atm.

**Comment by lgirdwood** [comment]
> > > Please find the below pull request to resolve picking up of proper core-isa.h file.
> > > [thesofproject/xtensa-overlay#14](https://github.com/thesofproject/xtensa-overlay/pull/14)
> > 
> > 
> > Now merged. Not sure how CI picks up this update for overlays. @marc-hb @greg-intel what needs done here ?
> 
> @balakishorepati thinking aloud, rebase and force pushing this PR again may cause the container to rebuild and pick up the new overlay. It's worth a try as @marc-hb is out atm.

**Comment by fredoh9** [comment]
I will try with latest xtensa-overlay (including https://github.com/thesofproject/xtensa-overlay/pull/14)

**Comment by fredoh9** [comment]
rmb build fine with latest docker build.
20220809 is new tag. Need to do some sanity test with it. Will promote to the latest by the end of today or tomorrow.
Will rebase and update this PR shortly.

**Comment by lgirdwood** [comment]
@fredoh9  pls let me know when this can be merged. Thanks.

**Comment by fredoh9** [comment]
This is tested fine, can be merged now.

https://github.com/thesofproject/sof/pull/6119 also ready to merge also.

**Pull request merged**
