### PR TITLE
platform: refactor: deduplicate code for APL&CNL

### PR DESCRIPTION
**Pull request by jajanusz**
First step of deduplicating platforms code.
1st commit keeps binaries identical with just removing duplicated code.
2nd commit wraps common code into libtool convinence libs, because we don't want to list common source files for each platform with relative paths.

Next step will be removing #ifdefs and moving small chunks of platform-specific code to their folders, then deduplicating header files.

It is critical for maintainability of platform-specific sources (and adding new platforms in the future).

### CODE REVIEW

**Comment by jajanusz** [comment]
What do you mean by missing commit message? There are commit messages for each commit and title of PR, do you mean something else?

**Comment by lgirdwood** [comment]
The commit message is only showing the title and SoB. It should also have a statement saying what is changing and why (especially important for big change sets like this one).

**Comment by jiawang6** [comment]
CI observed building failure.

Failed Platform: baytrail

make[5]: *** No rule to make target '../../platform/baytrail/libplatform.la', needed by 'sof'.  Stop.

**Comment by jajanusz** [comment]
@jiawang6 
Probably you don't have latest commit, looks like your CI ignores amended commit.
I initially did PR that would give error like one that you wrote but within 5 minutes I did commit --amend with fix for that. When is your CI exactly trigerred? Only on pull request? What about updates to PR?

**Comment by jiawang6** [comment]
@jajanusz , sorry, CI was blocked by Jenkins CI maintaining at that time. I have manually  rerun the updated PR and the result is successful.

**Comment by lgirdwood** [comment]
@jajanusz this is fine, but lets merge into -next since we are in code freeze on master. You may need to update your PR so I can merge into -next.

**Comment by jajanusz** [comment]
@lgirdwood I know, just need some changes to make it mergable to next

**Comment by jajanusz** [comment]
Rebased and updated for next

**Pull request merged**
