### PR TITLE
Audio: TDFB: Optimize read/write frag operations

### PR DESCRIPTION
**Pull request by singalsu**
Generic, HiFiEP versions of TDFB are updated by replacing read/write frag functions. The generic C FIR filter is optimized.

### CODE REVIEW

**Review by lgirdwood — APPROVED** [review]

**Review by lgirdwood — APPROVED** [review]

**Comment by singalsu** [comment]
I did tests with slightly different approaches for FIR. The single sample reverse data version in this patch was 2 us slower than forward.  However in dual samples version the forward version was 20 us slower, not much faster than simple sample. So, to keep code simple I chose for both FIR filters the reverse direction (data-- and coef++). I felt this was the best compromise.

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by lgirdwood** [comment]
Rerun CI as it looks like we have a partial result.

**Comment by lgirdwood** [comment]
@kkarask @wszypelt not sure why this is failing as TDFB should not prevent FW boot on TGL ? Any insights here ?

**Comment by wszypelt** [comment]
@lgirdwood Probably There was platform issue. everything is working fine at this point

**Pull request merged**
