### PR TITLE
[mtl-006] Port multicore fix to mtl-006-drop-stable branch

### PR DESCRIPTION
**Pull request by RanderWang**
please check https://github.com/thesofproject/sof/pull/8143 and https://github.com/thesofproject/sof/pull/8149

All CI multi-core tests pass on main branch!

### CODE REVIEW

**Comment by mengdonglin** [comment]
@serhiy-katsyuba-intel @tmleman @abonislawski This PR includes https://github.com/thesofproject/sof/pull/8149 on main branch to fix issue #8155 Can you please review?

**Comment by fredoh9** [comment]
Build failed, can you fix the build errors? I can quickly verify if this really fix the multicore problem.

**Comment by fredoh9** [comment]
I fixed the build error and checking with mtl-006-stable-drop

```diff

diff --git a/src/ipc/ipc4/handler.c b/src/ipc/ipc4/handler.c
index 845b71fa6b9c..443e593f0d76 100644
--- a/src/ipc/ipc4/handler.c
+++ b/src/ipc/ipc4/handler.c
@@ -67,7 +67,7 @@ static struct ipc4_msg_data msg_data;
 /* fw sends a fw ipc message to send the status of the last host ipc message */
 static struct ipc_msg msg_reply = {0, 0, 0, 0, LIST_INIT(msg_reply.list)};

-static struct ipc_msg msg_notify = {0, 0, 0, 0, LIST_INIT(msg_notify.list)}};
+static struct ipc_msg msg_notify = {0, 0, 0, 0, LIST_INIT(msg_notify.list)};

 /*
  * Global IPC Operations.
```

**Comment by fredoh9** [comment]
unfortunately, different IPC timeout came up

```
[  140.239572] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: COPIER (UUID: 9BA00C83-CA12-4A83-943C-1FA2E82F9DDA): No CPC match in the firmware file's manifest (ibs/obs: 384/192)
[  140.239576] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: Please try to update the firmware.
[  140.239578] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: If the issue persists, file a bug at
[  140.239579] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: https://github.com/thesofproject/sof/issues/
[  140.239581] kernel: snd_sof:sof_ipc4_update_resource_usage: sof-audio-pci-intel-mtl 0000:00:1f.3: host-copier.0.capture: ibs / obs / cpc: 384 / 192 / 0
[  140.239585] kernel: snd_sof:sof_ipc4_widget_setup: sof-audio-pci-intel-mtl 0000:00:1f.3: pipeline: 8 memory pages: 2
[  140.239589] kernel: snd_sof:sof_ipc4_widget_setup: sof-audio-pci-intel-mtl 0000:00:1f.3: Create widget pipeline.8 instance 0 - pipe 8 - core 0
[  140.239594] kernel: snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc tx      : 0x11000002|0x0: GLB_CREATE_PIPELINE
[  140.739890] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc timed out for 0x11000002|0x0
[  140.739906] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: IPC timeout
[  140.739925] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: failed to create module pipeline.8
[  140.739931] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: Failed to set up connected widgets
[  140.739941] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: error: failed widget list set up for pcm 0 dir 1
[  140.739946] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ASoC: error at snd_soc_pcm_component_hw_params on 0000:00:1f.3: -110
[  140.739973] kernel:  Port0: ASoC: error at __soc_pcm_hw_params on Port0: -110
```

[dmesg.txt](https://github.com/thesofproject/sof/files/12555686/dmesg.txt)

**Comment by RanderWang** [comment]
> 

Let me check 006, I only tested main. Thanks!

**Comment by fredoh9** [comment]
with 2nd push, there is no build error, but back to MOD_SET_DX error

```
[   60.033925] kernel: snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc tx      : 0x47000000|0x0: MOD_SET_DX [data size: 8]
[   60.535638] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc timed out for 0x47000000|0x0
[   60.535653] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: Attempting to prevent DSP from entering D3 state to preserve context
[   60.535657] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ------------[ IPC dump start ]------------
[   60.535671] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: Host IPC initiator: 0x47000000|0x0|0x0, target: 0x67000000|0x0|0x0, ctl: 0x3
[   60.535675] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ------------[ IPC dump end ]------------
[   60.535678] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ------------[ DSP dump start ]------------
[   60.535680] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: IPC timeout
[   60.535683] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: fw_state: SOF_FW_BOOT_COMPLETE (7)
[   60.535692] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ROM status: 0x5, ROM error: 0x0
[   60.535695] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ROM debug status: 0x50000005, ROM debug error: 0x0
[   60.535701] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ROM feature bit enabled
[   60.535704] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ------------[ DSP dump end ]------------
[   60.535722] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: error: failed to enable target core for widget pipeline.3
[   60.535726] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: Failed to set up connected widgets
[   60.535736] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: error: failed widget list set up for pcm 1 dir 0
[   60.535741] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ASoC: error at snd_soc_pcm_component_hw_params on 0000:00:1f.3: -110
[   60.535763] kernel:  Port1: ASoC: error at __soc_pcm_hw_params on Port1: -110
[   60.535773] kernel:  Port1: ASoC: error at dpcm_fe_dai_hw_params on Port1: -110
[   60.535780] kernel: snd_sof:sof_pcm_hw_free: sof-audio-pci-intel-mtl 0000:00:1f.3: pcm: free stream 1 dir 0
[   60.536233] kernel: snd_sof:sof_pcm_close: sof-audio-pci-intel-mtl 0000:00:1f.3: pcm: close stream 1 dir 0
```

**Comment by RanderWang** [comment]
Add more debug method and find the fw hang after set_dx to disable secondary core. It will be always failed with create_pipeline after set_dx

**Review by serhiy-katsyuba-intel — APPROVED** [review]

**Comment by lgirdwood** [comment]
@mwasko @marcinszkudlinski fyi

**Review by tmleman — APPROVED** [review]
LGTM

**Review by lgirdwood — APPROVED** [review]
@mwasko @marcinszkudlinski fyi merged into main last week and results good.

**Review by abonislawski — APPROVED** [review]

**Review by marcinszkudlinski — APPROVED** [review]

**Comment by mwasko** [comment]
@RanderWang there is quite a lof of CI sof-ci/jenkins/pr-device-test/main-ace failures on MTL, can you clarify this?

**Comment by RanderWang** [comment]
The FW building was failed with error but it has nothing to do with my PR.
````c
/zep_workspace/sof/src/schedule/zephyr_domain.c:26:10: fatal error: zephyr/timeout_q.h: No such file or directory
   26 | #include <zephyr/timeout_q.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
````

**Comment by RanderWang** [comment]
SOFCI TEST

**Comment by RanderWang** [comment]
the error only happened on mtl-sdw device and it is a regression issue on 006branch. @keqiaozhang  is working on it.

**Pull request merged**
