### PR TITLE
topology: sof-adl-max98360a-rt5682-waves: add new topology

### PR DESCRIPTION
**Pull request by malik-hsu**
Add support for max98360a speaker amplifiers with waves function.

Signed-off-by: Malik_Hsu <malik_hsu@wistron.corp-partner.google.com>

### CODE REVIEW

**Comment by sofci** [comment]
Can one of the admins verify this patch?
> reply **test&nbsp;this&nbsp;please** to run this test once

**Comment by gkbldcig** [comment]
Can one of the admins verify this patch?

**Comment by lgirdwood** [comment]
Looks like I need to run the CI. test this please

**Comment by lgirdwood** [comment]
@malik-hsu added you to project so CI should run next PR.

**Review by cujomalainey — APPROVED** [review]

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
CI was down end of last week so rerun.

**Comment by cujomalainey** [comment]
@marc-hb got any ideas why the userspace test is failing? is there a revert they need to rebase on?

**Comment by marc-hb** [comment]
> Maybe cherry-picking some fixes from the main branch would help.

Bisected, done:
- #5491

Once #5491 is merged, @malik-hsu an empty `git commit --amend -C HEAD` + force-push here should be enough.

**Comment by sprewell20051116** [comment]
Hi all, could we CI again to see if passed? Thanks.

**Comment by marc-hb** [comment]
> Once https://github.com/thesofproject/sof/pull/5491 is merged, @malik-hsu an empty git commit --amend -C HEAD + force-push here should be enough.

#5491 is merged, @malik-hsu please do this (no one else can change [malik-hsu:adl-004](https://github.com/malik-hsu/sof/tree/adl-004))

**Comment by sprewell20051116** [comment]
It seems CI encounter another failure. How could we fix this?

**Comment by marc-hb** [comment]
Second fix submitted in #5508

**Comment by marc-hb** [comment]
> Once https://github.com/thesofproject/sof/pull/5491 is merged, @malik-hsu an empty git commit --amend -C HEAD + force-push here should be enough.

Second fix #5508 is merged, @malik-hsu can you do the exact same thing again? Sorry the inconvenience.

**Comment by sprewell20051116** [comment]
It looks CI passed. Please kindly merge this PR. Thanks a lot.

**Comment by sprewell20051116** [comment]
It seems CI encounter another failure. How could we fix?

**Comment by marc-hb** [comment]
There are multiple CIs. The one that just failed (https://quickbuild.igk.intel.com/build/8805764) does not test topologies, it's unrelated.

**Pull request merged**
