### PR TITLE
west.yml: upgrade zephyr to 3024bc5b19

### PR DESCRIPTION
**Pull request by tmleman**
Zepych update to 600e7b7f21: total of 115 commits.

Changes include:

* refactors and fixes in power domains.
* add intel wdt driver.

### CODE REVIEW

**Comment by marc-hb** [comment]
This will likely need this:
- https://github.com/zephyrproject-rtos/zephyr/pull/56547

**Comment by lgirdwood** [comment]
@marc-hb any of your PRs need this as a dependecy ?

**Comment by marc-hb** [comment]
Yes https://sof-ci.01.org/sofpr/PR7366/build5511/build/index.html fails because it's missing https://github.com/zephyrproject-rtos/zephyr/pull/56547

**Comment by tmleman** [comment]
I'm closing this PR, will try again next week.

**Comment by marc-hb** [comment]
@tmleman 56547 was just merged

**Comment by marc-hb** [comment]
I just found two recent regressions in upstream Zephyr though:
- https://github.com/zephyrproject-rtos/zephyr/commit/a5fd0d18
- https://github.com/zephyrproject-rtos/zephyr/commit/408472673ef1a

Last known good Zephyr commit: 408472673ef1a~1

**Comment by tmleman** [comment]
Closing again since the same is done here https://github.com/thesofproject/sof/pull/6480

**Comment by marc-hb** [comment]
> @marc-hb can you help me with the issue introduced with https://github.com/zephyrproject-rtos/zephyr/commit/408472673ef1a.

Here:
- https://github.com/zephyrproject-rtos/zephyr/pull/56790

**Pull request closed without merging**
