### PR TITLE
xtensa-build-zephyr: add option to stop after cloning Zephyr

### PR DESCRIPTION
**Pull request by marc-hb**
2 commits, main one:

xtensa-build-zephyr: add option to stop after cloning Zephyr

This is needed by CI to clone only once and then take control of the
iteration over platform builds. CI already does all that but by
copy/paste/diverge of this clone() function.

Once cloning Zephyr in CI code is de-duplicated and uses this new
clone-only feature instead, it will be possible to submit any Zephyr
commit to SOF testing.  In other words it will make failed attempt
#4728 possible

### CODE REVIEW

**Review by lgirdwood — COMMENTED** [review]
Good to see we can pick by commit. Where would we set the Zephyr commit ? Ideally this should be in a local file that can be updated by PR ?

**Comment by marc-hb** [comment]
> Where would we set the Zephyr commit ? 

This is in the (fairly small) diff :-)

> Ideally this should be in a local file that can be updated by PR ?

I thought about a config file but the problem with config files is that you typically do NOT want them in source control because they're by essence not meant to be shared. I've seen config files stored in source control (by mistake IMHO) and of course this causes conflicts all the time because different people have different config files = the whole purpose of config files. So this would have to be a shared and unusual sort of config file which is not very intuitive.

So in the spirit of getting this working ASAP with almost zero code change I just added a commented out (but fully fonctional) example.

**Comment by marc-hb** [comment]
There are some
```
19:24:39.720       Exception TimeoutError occurred at 'C:\\work\\tools\\pyexecnetcache\\cavs_scripts-py\\utilities\\fw_loader_pci.py':499
                   Cleaning ROM control IPC failed. Platform restart may be required.
```
in https://sof-ci.01.org/sof-pr-viewer/#/build/PR4740/build7214514. That CI does not use this script at all.

@kkarask could you take a look at these failures? As they happened in early SMOKE tests they seem to halt the rest of the validation, so pretty bad.

**Review by lgirdwood — APPROVED** [review]

**Review by cujomalainey — APPROVED** [review]
Mind adding this to sof-docs?

**Review by iuliana-prodan — APPROVED** [review]

**Comment by marc-hb** [comment]
> Mind adding this to sof-docs?

I forgot we had a zephyr section, ignorance is bliss?

So I went there and considered mentioning this "clone-only" option there but eventually I didn't because:
- By nature Zephyr modules are lagging behind. So the option won't be available immediately after this PR gets merged.
- The first thing the docs suggest is to read the usage page.

On the other hand I fixed other and older stuff and made the docs a bit "future-proof" with respect to this PR and other incoming changes: https://github.com/thesofproject/sof-docs/pull/368

**Comment by marc-hb** [comment]
SOFCI TEST

**Comment by kkarask** [comment]
PR passed after restarting platforms and rerun.

**Review by dbaluta — APPROVED** [review]

**Pull request merged**
