### PR TITLE
cmake: make CI builds verbose

### PR DESCRIPTION
**Pull request by jajanusz**
Usually that's spam that we may ignore in local builds, but is valuable for CI logs.

@xiulipan 
We have it in QB. Can you do it for travis?

Signed-off-by: Janusz Jankowski <janusz.jankowski@linux.intel.com>

### CODE REVIEW

**Comment by jajanusz** [comment]
> @lgirdwood
> I have a feeling that CODEOWNERS not always works, it doesn't match anyone for this and my next PR.

Or reason is that it matched me as only reviewer of *.sh but because I'm author of PR it removed me, shouldn't it fallback then to `*` code owners?

**Comment by dbaluta** [comment]
One question, not necessarily related to this. I remember that at some point sof had a rule to create the cscope index. 

One could run make cscope in sof/ directory. How is this handled now?

**Comment by jajanusz** [comment]
Should still work (with less excludes), but I didn't try it so cannot say that it works for sure.

**Comment by lgirdwood** [comment]
@jajanusz I see GH issue now and then, maybe scaling issues since everyone is using it now.

**Comment by xiulipan** [comment]
@jajanusz No change is needed for any CI. All CIs are using the scripts. If you just change the scripts. Then all CI will follow the change.
Please check the log to see if the travis show what you expect.
https://travis-ci.org/thesofproject/sof/jobs/485373590

**Comment by jajanusz** [comment]
@xiulipan 
Thanks for info. Looks good.

**Pull request merged**
