### PR TITLE
board: intel_adsp_ace15_mtpm: Enable AEC mock module by default

### PR DESCRIPTION
**Pull request by yongzhi1**
This patch enables Google RTC mock module by default for CI build tests, etc.

Also avoid manually applying the changes each time to build the FW for AEC sanity check.

### CODE REVIEW

**Review by kv2019i — COMMENTED** [review]
Hmm, not sure about this, whatever is in this conf gets shipped to upstream as-is.

**Comment by yongzhi1** [comment]
> Hmm, not sure about this, whatever is in this conf gets shipped to upstream as-is.

We have RTC_AEC defined in mtl.toml, so AEC enabled tplg will load successfully and exposed to user space, but we cannot use it without a mock module.

**Review by kv2019i — APPROVED** [review]
If it's in the toml, then the cat is already out of the bag. No harm in this I guess, but if we hit binary size issues, this will be high on the list of modules to drop.

**Review by kv2019i — CHANGES_REQUESTED** [review]
Hmm, I see build errors in CI, please take a look @yongzhi1

**Comment by lgirdwood** [comment]
@marcinszkudlinski @ranj063 good for you ?

**Review by lgirdwood — APPROVED** [review]
LGTM, but lets see if Marcin/Ranjani also ready or do we have other dependencies to merge 1st for topology or DP.

**Comment by yongzhi1** [comment]
SOFCI TEST

**Comment by yongzhi1** [comment]
> Hmm, I see build errors in CI, please take a look @yongzhi1

The build errors should be fixed in current main now, thanks,

**Comment by lgirdwood** [comment]
@yongzhi1 there was an issue last week, if CI results dont improve can you rebase and force-push. Thanks.

**Comment by yongzhi1** [comment]
> @yongzhi1 there was an issue last week, if CI results dont improve can you rebase and force-push. Thanks.

Oh, the code is broken again due to https://github.com/thesofproject/sof/commit/a62b7cf1c3f73e3209222d5362a66389e7ae68bf

**Comment by lgirdwood** [comment]
> > @yongzhi1 there was an issue last week, if CI results dont improve can you rebase and force-push. Thanks.
> 
> Oh, the code is broken again due to [a62b7cf](https://github.com/thesofproject/sof/commit/a62b7cf1c3f73e3209222d5362a66389e7ae68bf)
> 
> EDIT: Fixup submitted #8536

Fix now merged, can you try force push now ?

**Comment by yongzhi1** [comment]
Maybe we can use the following one already done by @marcinszkudlinski 
https://github.com/thesofproject/sof/commit/c90eb8b134d68b34a2914e5cc24d5d7af2f81fcc

**Comment by lgirdwood** [comment]
> Maybe we can use the following one already done by @marcinszkudlinski [c90eb8b](https://github.com/thesofproject/sof/commit/c90eb8b134d68b34a2914e5cc24d5d7af2f81fcc)

Do you mean close this PR ? if so , pls close. Thanks !

**Comment by marcinszkudlinski** [comment]
yes. please close this.
I'm still waiting for feedback from 007 before proceeding with AEC upstream.

**Pull request closed without merging**
