### PR TITLE
west.yml: upgrade Zephyr to de9579f29743

### PR DESCRIPTION
**Pull request by ranj063**
To include the DW DMA changes below along with ~900 other patches.

b32b321f50 dma: dw: Poll to check for channel disable with timeout
6226f9e6e4 dma: dw: fix the return value check
08d9efb202 dma: dw: Do not program SAR/DAR and CTL_HI/LO when using HW LLI
045c686734 dma: dw: Add a debug utility function

### CODE REVIEW

**Review by lgirdwood — APPROVED** [review]
CI back on Monday. Will retest.

**Comment by kv2019i** [comment]
Multiple DSP crashes like in
https://sof-ci.01.org/sofpr/PR7301/build4796/devicetest/index.html?model=ADLP_RVP_SDW_IPC4ZPH&testcase=check-capture-10sec
... looking at this now.

**Comment by gkbldcig** [comment]
Can one of the admins verify this patch?

**Comment by kv2019i** [comment]
Stale, closing

**Pull request closed without merging**
