### PR TITLE
cmocka fixes for native host target

### PR DESCRIPTION
**Pull request by lgirdwood**
Update cmocka UT for new comp cmd API update and get cmocka working on host test bench.

### CODE REVIEW

**Comment by lgirdwood** [comment]
@mwierzbix @akloniex there are some updates to pre-processing items in here, please make sure this is fine for host targets.

**Comment by lgirdwood** [comment]
@jajanusz most tests pass, but some processing component tests fail. These can be fixed to pass after merge, but we probably want to check if there is any difference between native host and xtensa UT results.

**Comment by jajanusz** [comment]
@jajanusz 
UTs has been developed with xtensa arch in mind, so someone will have to update what can run on host to run on host and what needs xt simulator should be wrapped in `if BUILD_XTENSA`. For now just to make it all running again I'll wrap all tests that fail on host with `if BUILD_XTENSA` and later someone can update UTs for host. I don't like how UTs are done now and I'd like to do it in different way with kbuild, so I'd not invest too much time into fixing UTs now.

There are still some issues for xtensa UTs caused by #730, I'll fix them after this one is merged.

**Comment by jajanusz** [comment]
@lgirdwood 
Now I see you fixed issue with #730, but xtensa UTs still fail because of #698 changes. I can fix it anyway

**Comment by mengdonglin** [comment]
@lgirdwood Would you please erge this PR? Firmware will cherrypick it to GLK release branch glk-005-drop-stable.

**Pull request merged**
