### PR TITLE
Add support for the MediaTek mt8188 platform

### PR DESCRIPTION
**Pull request by zoran055**
These commits add support for the MediaTek mt8188 platform. Add the mt8188 gcc toolchain.

Many thanks!

### CODE REVIEW

**Comment by sofci** [comment]
Can one of the admins verify this patch?
> reply **test&nbsp;this&nbsp;please** to run this test once

**Review by kv2019i — APPROVED** [review]

**Comment by marc-hb** [comment]
https://github.com/thesofproject/sof/actions/runs/9125459636/job/25100094960?pr=9137 fails because you unfortunately cannot submit these 2 commits in the same PR, it must be done in several steps:

1. Update the docker file
2. @fredoh9 has to regenerate and publish the docker image
3. Then you can build mt8188 by default

**Comment by fredoh9** [comment]
I will re-build the docker image with this PR.

**Comment by zoran055** [comment]
Hi @marc-hb,
Do you mean that I should submit these two commits separately?

**Comment by marc-hb** [comment]
Yes please.

**Comment by fredoh9** [comment]
I made new docker image but there is no xtensa-mt8188-elf generated. Need to take a look at more closely later today

**Comment by fredoh9** [comment]
From new docker image, there is no mt8188 toolchain in `/home/sof/work/xtensa-mt8188-elf`
Looks everything is right, still looking for the problem.

**Comment by fredoh9** [comment]
ahh, I was using wrong image tag. docker-run.sh uses thesofproject/sof:latest_ubuntu22.04 but I tagged new image with 'latest'.
Now ready to test with new image. Will update by this afternoon.

**Comment by fredoh9** [comment]
> Can we get rid of latest_ubuntu22.04 now? I think it was meant to be temporary, I just can't remember why right now...

That's right. it was temporary solution when we had issue with ubuntu 22.04 based image. Time to remove it. Will submit a patch shortly.

**Comment by fredoh9** [comment]
https://github.com/thesofproject/sof/pull/9149 for thesofproject/sof:latest

New docker image is tested. Will be promoted to latest soon.

**Review by fredoh9 — APPROVED** [review]
Looks good. New docker image has mt8188 toolchain.

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
> #9149 for thesofproject/sof:latest
> 
> New docker image is tested well. Will be promoted to latest soon.

#9149 Now merged.

**Comment by lgirdwood** [comment]
@wszypelt @lrudyX good to merge ? this one not tested by Internal CI.

**Comment by wszypelt** [comment]
@lgirdwood CI internal tests all green :)

**Comment by kv2019i** [comment]
SOFCI TEST

**Comment by kv2019i** [comment]
@fredoh9 @marc-hb Seems only the jenkins pr-build is now pending. Tried to rekick it above...

**Pull request merged**
