### PR TITLE
sof: build: Disallow void pointer arithmetic

### PR DESCRIPTION
**Pull request by paulstelian97**
Void pointer arithmetic isn't supported in Zephyr. This pull request removes it.

Signed-off-by: Paul Olaru <paul.olaru@nxp.com>

~Draft because I only added the flag so I get compile errors, without actually removing anything. I believe I should also add the flag on host?~ (no longer draft, host is also covered)

Fixes: #1913

### CODE REVIEW

**Comment by jajanusz** [comment]
@paulstelian97 Yes you can add flag to host also

**Comment by paulstelian97** [comment]
@jajanusz Already done, now I'm on the fixing itself.

**Comment by paulstelian97** [comment]
@jajanusz I think this will conflict with #1849. Will still add the casts to (char *) in those particular places but I have to remember to update.

**Comment by paulstelian97** [comment]
When Travis confirms this builds I will mark this PR ready for review and address checkpatch and splitting.

**Comment by paulstelian97** [comment]
Travis is too slow and everything else but Checkpatch passes, marking as ready for review.

**Comment by paulstelian97** [comment]
Fixed most Checkpatch warnings, not sure how to fix the last one. Should I split this PR into multiple commits, each affecting one component or driver?

**Comment by jajanusz** [comment]
@paulstelian97 yea QB CI may take some time to run, but it will check your code with XCC

**Comment by jajanusz** [comment]
> Fixed most Checkpatch warnings, not sure how to fix the last one. Should I split this PR into multiple commits, each affecting one component or driver?

It can be one commit. Separating it by component is not worth the trouble.

**Comment by paulstelian97** [comment]
@jajanusz I think everything is fine form this point of view? That one line which is 82 characters I don't see the value in trying to fix, and the CamelCase is from the original code so I'm not willing to touch. Not sure about that "unit tests failed" thing, seems to actually be random as I trust this one more than the asserts PR to not change any actual behavior.

**Comment by jajanusz** [comment]
@paulstelian97 Actually unit tests case is valid - they have the same flags as arch they are made for, so they fail for example now in univeral_mocks.c for memcpy, at least that one is shown while building, I guess there may be more.

**Comment by jajanusz** [comment]
@paulstelian97 Regarding checkpatch, feel free to ignore these 2, they are non-issues for me

**Comment by paulstelian97** [comment]
@jajanusz I would like to figure out why they would fail though. The sof-ci site only shows cmake output but not which unit tests are failing. So I cannot actually check.

I will try to look into my code to see if I changed semantics on any line. Although I don't think I did change anything since on-device tests succeed.

**Comment by paulstelian97** [comment]
> @paulstelian97 Actually unit tests case is valid - they have the same flags as arch they are made for, so they fail for example now in univeral_mocks.c for memcpy, at least that one is shown while building, I guess there may be more.

I actually can't see that in SOFCI and again, I'm having that recurring issue with building the unit tests on my own. Will try to see.

**Comment by jajanusz** [comment]
> @jajanusz I would like to figure out why they would fail though. The sof-ci site only shows cmake output but not which unit tests are failing. So I cannot actually check.
> 
> I will try to look into my code to see if I changed semantics on any line. Although I don't think I did change anything since on-device tests succeed.

It doesn't show which unit test failed because it didn't run any, it failed to build them.

**Comment by jajanusz** [comment]
@paulstelian97 I see that web guys didn't make it properly, it gives wrong log file...
Here is error that I can see in QB:
```
19:15:51,076 INFO  - [ 3%] Building C object test/cmocka/CMakeFiles/universal_mock.dir/src/universal_mocks.c.o
19:15:51,076 INFO  - cd /quickbuild/workspace1/24733/SOF_FW/build_ut/test/cmocka && /localdisk/tools/xtensa/RG-2017.8-linux/XtensaTools/bin/xt-xcc -I/quickbuild/workspace1/24733/SOF_FW/src/arch/xtensa/include -I/quickbuild/workspace1/24733/SOF_FW/src/arch/xtensa/xtos -I/quickbuild/workspace1/24733/SOF_FW/src/platform/icelake/include -I/localdisk/tools/xtensa/RG-2017.8-linux/X6H3CNL_2017_8/xtensa-elf/arch/include -I/localdisk/tools/xtensa/RG-2017.8-linux/X6H3CNL_2017_8/xtensa-elf/include -I/quickbuild/workspace1/24733/SOF_FW/src/platform/intel/cavs/include -I/quickbuild/workspace1/24733/SOF_FW/src/include -I/quickbuild/workspace1/24733/SOF_FW/build_ut/generated/include -fno-inline-functions -mlongcalls -O2 -g -Wall -Werror -Wl,-EL -Wmissing-prototypes -Wpointer-arith -mtext-section-literals -o CMakeFiles/universal_mock.dir/src/universal_mocks.c.o -c /quickbuild/workspace1/24733/SOF_FW/test/cmocka/src/universal_mocks.c
19:15:51,233 WARN  - cc1: warnings being treated as errors
19:15:51,233 WARN  - /quickbuild/workspace1/24733/SOF_FW/test/cmocka/src/universal_mocks.c: In function ‘memcpy_s’:
19:15:51,233 WARN  - /quickbuild/workspace1/24733/SOF_FW/test/cmocka/src/universal_mocks.c:16: warning: pointer of type ‘void *’ used in arithmetic
19:15:51,233 WARN  - /quickbuild/workspace1/24733/SOF_FW/test/cmocka/src/universal_mocks.c:17: warning: pointer of type ‘void *’ used in arithmetic
19:15:51,234 INFO  - test/cmocka/CMakeFiles/universal_mock.dir/build.make:62: recipe for target 'test/cmocka/CMakeFiles/universal_mock.dir/src/universal_mocks.c.o' failed
19:15:51,234 WARN  - make[2]: *** [test/cmocka/CMakeFiles/universal_mock.dir/src/universal_mocks.c.o] Error 2
19:15:51,234 INFO  - make[2]: Leaving directory '/quickbuild/workspace1/24733/SOF_FW/build_ut'
```

**Comment by paulstelian97** [comment]
Ah, seems like UT requires xcc, that's why I had issues testing locally. Well, guess I found issues other than that one which also cause build errors. Those not related to this change I shall send as a separate PR.

**Comment by jajanusz** [comment]
@paulstelian97 yes, UT are for xcc only now

**Comment by paulstelian97** [comment]
Oof, new build errors. Coming back on it.

**Comment by paulstelian97** [comment]
SOFCI TEST

**Comment by paulstelian97** [comment]
@jajanusz Any feedback on whether the on-device tests failures are related to my change or not?

**Comment by jajanusz** [comment]
SOFCI TEST

**Comment by jajanusz** [comment]
> @jajanusz Any feedback on whether the on-device tests failures are related to my change or not?

void* arithmetic assume that element size is 1 byte and you used char* everywhere so your changes didn't change logic/execution at all, compilation result should be the same, just pointer type is explicit. I think these are just random test issues - also when I run test again then different cases fail, so yea, it's pretty random ...

**Comment by jajanusz** [comment]
@tlauda @dbaluta @lgirdwood ping

**Pull request merged**
