### PR TITLE
dai: add DAI driver "hw_params" callback

### PR DESCRIPTION
**Pull request by ViorelSuman**
Add "hw_params" callback in order to provide the
stream information like stream rate, number of channels
and format to DAI IP driver.

Signed-off-by: Viorel Suman <viorel.suman@nxp.com>

### CODE REVIEW

**Comment by iuliana-prodan** [comment]
LGTM

**Review by iuliana-prodan — APPROVED** [review]

**Comment by dbaluta** [comment]
@ViorelSuman looks good to me!

@keyonjie @lgirdwood this hopes open the way for dynamically configuring DAI parameters.

Just right now DAI is configured using parameters from topology! We want to be able to get parameters at runtime from userspace applications.

Like for example calling aplay -Dhw:0,0 -f S32_LE -c 2 -r 48000.

Ideally, the topology will define the range of possible parameters and aplay() -> through hw_params function in the Linux kernel will setup the runtime params in firmware.

**Comment by plbossart** [comment]
we need @juimonen, @kv2019i and @ranj063 to chime in on this one. We recently added multiple configurations per DAI.

@dbaluta this will only work for pipelines without any mixers (on playback) or demux (on capture). If you start having mixers/demux, you will have to define at what rate the mixer operates, and to adjust whatever comes from user space to the mixer/demux rate.

**Comment by ViorelSuman** [comment]
> we need @juimonen, @kv2019i and @ranj063 to chime in on this one. We recently added multiple configurations per DAI.
> 
> @dbaluta this will only work for pipelines without any mixers (on playback) or demux (on capture). If you start having mixers/demux, you will have to define at what rate the mixer operates, and to adjust whatever comes from user space to the mixer/demux rate.

Isn't the mixer or demux able to support a range of rates and channels ? Currently in a pipeline we are able to define a min rate and a max rate, and a max number of channels - how this pipeline flexibility correlates with a mixer or demux ?

**Comment by ViorelSuman** [comment]
Note "pcm_min_rate", "pcm_max_rate", "max channels" in tools/topology/m4/pipeline.m4 :

dnl PIPELINE_PCM_ADD(pipeline,
dnl     pipe id, pcm, max channels, format,
dnl     period, priority, core,
dnl     pcm_min_rate, pcm_max_rate, pipeline_rate,
dnl     time_domain, sched_comp, dynamic)
define(`PIPELINE_PCM_ADD',

**Comment by marc-hb** [comment]
https://sof-ci.01.org/sofpr/PR4030/build8674/devicetest failed because TGLU_SKU0A32_SDCA was added to PR testing before being ready, sorry for the inconvenience. I removed it.

**Comment by marc-hb** [comment]
SOFCI TEST

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
CI shows known TGL kernel PM issue.

**Review by keyonjie — APPROVED** [review]
Thanks for adding this, it is what I have been advocating. We have back-end fixed up params configured in the Linux SOF driver at the moment(and that's why we have .dai_get_hw_params in the dai ops now), but if it is aligned with the FW Back-end hardware driver, e.g. Intel ssp.c doesn't do anything in this new added hw_params, it looks fine to me.

**Comment by juimonen** [comment]
@ViorelSuman @keyonjie sorry to chime in late...I'm little bit puzzled what this does or is used for...? AFAIK previously we had "fixed" dai config and then all other components we're adapting/adjusting to dai parameters. Lately we added the driver fixup for selecting different SSP dai configs to the driver.

So this is mainly as I don't want to preserve multiple configs on the dsp side, and we don't have good ipc mechanism currently to transfer multiple "big" config data -> so we might get to the limit of our ipc size very quickly.

So current code should do the same thing as I understand is suggested here.... I maybe understanding something wrong.

**Comment by juimonen** [comment]
@ViorelSuman @plbossart the sample rate propagation was one of the first things I did when joining the team. So it is the responsibility of the component  (like SRC) to allow different sample rates and then propagate that up to the pcm. I think currently the assumption was that for e.g. SRC to DAI connection rate is fixed to the max sample rate (as we didn't have DAI rate changing before). However I don't see why this would not work with alternating samplerate in the DAI -> should be tested.

**Comment by ViorelSuman** [comment]
> @ViorelSuman @keyonjie sorry to chime in late...I'm little bit puzzled what this does or is used for...?

It is similar to "hw_params" callback in Linux Kernel ALSA layer - used to allow DAI IP driver (like "sai.c" or "esai.c" in NXP case, or "ssp.c" in Intel case) to configure the IP for all the range of IP supported rates, number of channels and formats. Some of our hardware platforms are able to support playback of up to 16 32-bit channels at 768kHz sample rate - my goal is to assess at what degree SOF can be used in a such environment. I need the rate, number of channels and format info being propagated from "aplay" via Linux IPC to SOF in our "sai.c" driver in order to calculate the bit clock, mclk divider in a similar way like it is done in "fsl_sai_hw_params" here: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/sound/soc/fsl/fsl_sai.c

**Comment by ViorelSuman** [comment]
> @ViorelSuman @plbossart the sample rate propagation was one of the first things I did when joining the team. So it is the responsibility of the component (like SRC) to allow different sample rates and then propagate that up to the pcm.

The most simplest passthough playback pipeline may have no SRC, just a "host" and a playback "DAI". And we do have now the option to specify in topology for a such case a range of pipeline supported rates and the maximum number of channels, as mentioned in a comment above.

**Comment by juimonen** [comment]
@ViorelSuman yes. that's why I did the "multi ssp" so that the config (parameters) are saved in kernel side. So currently for example in the case of SSP it is not enough to just set the sample rate, you need to set clocks, alignment etc like 10/20 params. So mapping from sample rate to config is not 1:1, you need to have all related config parameters at hand. Currently we can't send to the dsp dai in topology loading multiple configs (which it would then choose depending on sample rate) -> thus the configs are saved in kernel side and correct config is sent when stream is opened (dai fixup).

So I see this mostly just similar functionality, but doing it differently in different place. I'm saving the configs in kernel, you are probably going for saving all the configs in dsp dai? -> then changing those configs based on sample rate for e.g.?

**Comment by paulstelian97** [comment]
> @ViorelSuman yes. that's why I did the "multi ssp" so that the config (parameters) are saved in kernel side. So currently for example in the case of SSP it is not enough to just set the sample rate, you need to set clocks, alignment etc like 10/20 params. So mapping from sample rate to config is not 1:1, you need to have all related config parameters at hand. Currently we can't send to the dsp dai in topology loading multiple configs (which it would then choose depending on sample rate) -> thus the configs are saved in kernel side and correct config is sent when stream is opened (dai fixup).
> 
> So I see this mostly just similar functionality, but doing it differently in different place. I'm saving the configs in kernel, you are probably going for saving all the configs in dsp dai? -> then changing those configs based on sample rate for e.g.?

Just for context sake, the biggest problem we have to solve on ARM platforms is that we cannot (within SOF) change actual clock frequencies (other than SAI dividers) whatsoever, nor change which MCLK we use, in order to permit changing from 48000-type rates (8000, 16000, 48000 etc) to 44100-type rates (22050, 44100 etc) or vice versa when we only have one stream. So all these changes must be orchestrated kernel side, especially given that codec configuration itself _also_ happens only on the kernel side (so the codec expects the same rate and potentially bit width as the FE, and is configured as such). On the DSP we don't control anything further than the DAI itself.

(of course, power savings: we want to avoid unnecessary rate conversions and all if possible)

**Comment by juimonen** [comment]
@paulstelian97 yeah so me doing this on kernel side was just based on couple of things: 
- I need to change the "whole" dai config with sample rate (in my use case)
- I don't have an array of related dai configs in dsp -> and that might possibly need changes to ipc (if your array size is bigger than ipc max size 384 bytes)
- asoc has already a mechanism to save multiple hw configs
- not sure if it is an issue, but we are currently doing power management (and later dynamic pipelines), so firmware is loaded/unloaded every time stream starts/stops -> so if you have the configs on dsp side, big data chunk is moved to dsp before streaming starts -> then the correct one is chosen.

But yeah, I'm fine with this, just saying that if you want this to work you need to do the mapping to actual dai hw params in the firmware (and send all those configs before the stream starts or hardcode them into the code).

And also I might be misunderstanding something here... :)

**Comment by lgirdwood** [comment]
@juimonen @kv2019i @dbaluta @paulstelian97 @iuliana-prodan I'm assuming everyone is fine with this ? We have an unrelated Jenkins failure so are good to merge.

**Review by paulstelian97 — APPROVED** [review]

**Review by dbaluta — APPROVED** [review]

**Pull request merged**
