### PR TITLE
Switch travis to new rebuild-testbench.sh script

### PR DESCRIPTION
**Pull request by marc-hb**
2 commits, see commit messages.

### CODE REVIEW

**Comment by ymdatta** [comment]
@marc-hb : Thanks, i was working on changing it to rebuild-testbench.sh script on travil, but you beat me to it! :)

LGTM.

**Review by ymdatta — APPROVED** [review]

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
@marc-hb I'm guessing CI is unrelated here too, care to check.

**Comment by marc-hb** [comment]
Yes the other CI failures are unrelated, only Travis uses these files

**Comment by lgirdwood** [comment]
@zrombel server issue ?

**Review by singalsu — APPROVED** [review]

**Comment by marc-hb** [comment]
> @zrombel server issue ?

Very likely the same "platform issue" as https://github.com/thesofproject/sof/pull/3365#issuecomment-683736062

**Comment by zrombel** [comment]
@marc-hb Yes, exactly. After rerun all tests are PASS.

**Pull request merged**
