### PR TITLE
ipc4: fix for mixout not working after reset

### PR DESCRIPTION
**Pull request by serhiy-katsyuba-intel**
Fixes a bug in mixout_reset(): mixin pointers in mixed data info should not be cleared on reset. They should only be set on bind and cleared on unbind.

Signed-off-by: Serhiy Katsyuba <serhiy.katsyuba@intel.com>

### CODE REVIEW

**Comment by kv2019i** [comment]
@serhiy-katsyuba-intel Can you undraft this, this seems very good. Together with kernel PR https://github.com/thesofproject/linux/pull/3917/ , this is getting much better results with mixer topologies.

**Review by kv2019i — APPROVED** [review]

**Review by lyakh — APPROVED** [review]

**Comment by serhiy-katsyuba-intel** [comment]
> @serhiy-katsyuba-intel Can you undraft this, this seems very good. Together with kernel PR [thesofproject/linux#3917](https://github.com/thesofproject/linux/pull/3917) , this is getting much better results with mixer topologies.

The PR is not draft since yesterday. Probably some refresh issue on your side. The PR is ready to merge.
The failure reported by the CI looks like the CI problem and is unrelated to modifications made.

**Comment by kv2019i** [comment]
@serhiy-katsyuba-intel wrote:
> The PR is not draft since yesterday. Probably some refresh issue on your side. The PR is ready to merge. The failure reported by the CI looks like the CI problem and is unrelated to modifications made.

Ack, this is good to now! We need to wait for the few mandatory CI runs to complete and then this should be good to merge. The already reported CI issues are known ones.

**Comment by kv2019i** [comment]
@wszypelt sorry, need to bug you again. I couldn't find this PR at all in Intel CI dashboards, so it appears it was not queued. Need a retrigger?

**Comment by wszypelt** [comment]
@kv2019i 
Hey, it's good to let me know. in fact qb did not queue this pr correctly, I started it manually, within 30 minutes there should be results

**Review by marcinszkudlinski — APPROVED** [review]

**Comment by kv2019i** [comment]
Thank you @wszypelt ! Now all looks good. One known failure (fix in review at https://github.com/thesofproject/sof-test/pull/971 ), so proceeding with merge.

**Pull request merged**
