### PR TITLE
passthrough: fix interface

### PR DESCRIPTION
**Pull request by cujomalainey**
oops, forgot to update interface so build was silently not linking the
passthrough interface to the adapter

Signed-off-by: Curtis Malainey <cujomalainey@chromium.org>

### CODE REVIEW

**Comment by cujomalainey** [comment]
Aside, im looking forward to enabling testbench as a `make allyesconfig` style build in the future to catch this kind of thing

**Review by dbaluta — APPROVED** [review]

**Comment by dbaluta** [comment]
@fredoh9 @zrombel can you help adding a unit test for passthrough interface?

**Comment by fredoh9** [comment]
I don't have quick and easy idea to add passthrough unit test. I understand we can configure and enable Codec adapter and Passthrough, but do we need specific HW to test on? And how to check 'passthrough' is working. @dbaluta @zrombel do you have any suggestion or idea?

**Comment by lgirdwood** [comment]
Please use "main" as PR target.

**Comment by dbaluta** [comment]
Done here: https://github.com/thesofproject/sof/pull/3973

**Pull request closed without merging**
