### PR TITLE
[stable-v2.2 backport] topology1: Use DYNAMIC for ADL and RPL topologies

### PR DESCRIPTION
**Pull request by Vamshigopal**
use dynamic for all the adl and rpl topologies except 3p(waves,DTS), excluded Dell sdw topologies which are not tested.

### CODE REVIEW

**Comment by Vamshigopal** [comment]
This PR is same as #8093(merged in main), direct cherry-pick had conflicts , so pushed the patch without cherry-pick.

**Review by marc-hb — CHANGES_REQUESTED** [review]
> This PR is same as https://github.com/thesofproject/sof/pull/8093(merged in main), direct cherry-pick had conflicts , so pushed the patch without cherry-pick.

We still want the line from the `git cherry-pick -x` command in the commit message even when there are conflicts. You must also explain how you resolved conflicts. These are especially important now because we're trying to get rid of some topology1 in the main branch and we must make sure everything has been backported.

The regular git process is:
1. run `git cherry-pick -x`
2. fix the conflicts using any editor, git tool or copy you like
3. run `git cherry-pick --continue`
4. explain the git conflicts.

This gives you a good commit message with everything required.

Speaking of backports, the easiest way to fix conflicts is often to `git cherry-pick -x` MORE commits = the missing ones. Have you tried that?

**Comment by marc-hb** [comment]
@wszypelt https://sof-ci.01.org/sof-pr-viewer/#/build/PR8229/build12816675 has failed. It cannot be because of this pure topology commit.

**Comment by marc-hb** [comment]
> @wszypelt https://sof-ci.01.org/sof-pr-viewer/#/build/PR8229/build12816675 has failed. It cannot be because of this pure topology commit.

Sorry I forgot quickbuild is only compatible with the main branch, ignore. It should be disabled elsewhere (PTS-45980), that would also make it much faster!

**Comment by marc-hb** [comment]
BTW `git cherry-pick -x` is surprisingly powerful for backports:

```shell
git cherry-pick -x $rev_expr # see git help revisions
```

Or, even more powerful:
```
git log --oneline --format='%h' $rev_expr -- tools/topology* | git cherry-pick -x --stdin
```

> yeah, we need to do backport of some other commits for cherry-pick to apply cleanly.

Can you help?

**Comment by Vamshigopal** [comment]
> > yeah, we need to do backport of some other commits for cherry-pick to apply cleanly.
> 
> Can you help?

It shows 450 patches we need to backport for stable-v2.2 branch from main, to apply the cherry-pick cleanly.

git log --oneline --format=%h  origin/stable-v2.2..6f2475b086ce -- tools/topology*

**Comment by marc-hb** [comment]
> git log --oneline --format=%h origin/stable-v2.2..https://github.com/thesofproject/sof/commit/6f2475b086ce1336a405fea0f9d46429f166b11b -- tools/topology*

This was just a "semi-random" example sorry. `tools/topology*` includes topology2, which we definitely do NOT want in stable-v2.2. The selection needs to be much narrower than this. It may require some manual selection too.

If you find that just a few commits are enough to avoid the current conflicts then maybe go with just that?

**Comment by Vamshigopal** [comment]
> If you find that just a few commits are enough to avoid the current conflicts then maybe go with just that?

Backported 10 commits from main branch which are important and necessary to have them in stable-v2.2 branch. let me know your thoughts.

**Comment by marc-hb** [comment]
I don't have any valuable thoughts about topologies, only about git and backports :-)

From a pure git perspective this looks great!

**Comment by kv2019i** [comment]
Thanks @Vamshigopal , this looks good. 

And yes, it seems we have a bit of a problem with TGL/RPL/ADL tplg1 files as the diff between mainline and stable-v2.2 has grown so big. We should have removed the tplg1 files earlier from mainline, to ensure patches are sent to the correct branch, but alas this was not done, so now backporting is more difficult than it should be.

**Review by kv2019i — APPROVED** [review]

**Comment by mengdonglin** [comment]
> use dynamic for all the adl and rpl topologies except 3p(waves,DTS), excluded Dell sdw topologies which are not tested.

@Vamshigopal @kv2019i Dell SDW topologies are all cherry-picked to v2.2 branch. No worries.

**Pull request merged**
