### PR TITLE
[SKIP SOF-TEST] ci: fix stub build overlay passing

### PR DESCRIPTION
**Pull request by cujomalainey**
~As a result we missed a bad path config~ overlays were not being passed correctly to west

### CODE REVIEW

**Comment by cujomalainey** [comment]
Bash truly is a cursed hammer

This is now ready for review

**Review by marc-hb — CHANGES_REQUESTED** [review]
I was on vacation for #7967 so I didn't catch commit deed9a8808eb212... you should totally not  parse overlay files in bash!!

You can just pass an overlay file to `west` directly, all at once. See example in https://github.com/thesofproject/sof/actions/runs/6223015337/job/16888066452

```
    west build --build-dir build-tgl --board intel_adsp_cavs25 \
   /zep_workspace/sof/app -- -DEXTRA_CFLAGS=-Werror  -DOVERLAY_CONFIG=/zep_workspace/sof/app/overlays/tgl/ipc4_overlay.conf
```

> Bash truly is a cursed hammer

Sure but this one was self-inflicted I'm afraid :-)

**Comment by kv2019i** [comment]
Ping @cujomalainey

**Comment by cujomalainey** [comment]
> Ping @cujomalainey 

Busy internally with planning, feel free to take it over, otherwise it will wait

**Comment by marc-hb** [comment]
OK, will do this week.

**Comment by marc-hb** [comment]
Fixed in:
- #8411

**Pull request closed without merging**
