### PR TITLE
doc: remove README.rst, it's in sof-docs now

### PR DESCRIPTION
**Pull request by jajanusz**
Remove cmocka ut docs, because they are now in sof-docs repo.

Signed-off-by: Janusz Jankowski <janusz.jankowski@linux.intel.com>

### CODE REVIEW

**Comment by xiulipan** [comment]
@jajanusz 
Could we hold this on until the sof-doc is enabled?
We lack docs for newcomers and README maybe still helpful now.

**Comment by jajanusz** [comment]
@xiulipan 
Docs are there: https://github.com/thesofproject/sof-docs

Also this file is just doc for cmocka unit tests, you don't need it if you don't run UT.
There are like 3 README's:
/README
/doc/README.host
/doc/README.rst

We need to clean up it by moving what we can to sof-docs and keep only README in root of repo.

**Comment by mengdonglin** [comment]
CI observed building failure.

Failed Platform: baytrail apollolake cannonlake

configure: error: in `/build/sof/src':
configure: error: C compiler cannot create executables

**Comment by jajanusz** [comment]
@mengdonglin 
How is it related to rst file?

**Comment by lgirdwood** [comment]
@jajanusz no it's related to missing/incorrect CFLAGS (which needs to be fixed ASAP)

**Comment by wenqingfu** [comment]
and it's on you :)  #78  @jajanusz

**Pull request merged**
