### PR TITLE
version.cmake: switch SOF_MAJOR etc. to a new, static `versions.json`

### PR DESCRIPTION
**Pull request by marc-hb**
As discussed in #6952, relying on `git describe` for defining SOF_MAJOR and friends is very brittle and unreliable. Switch to a static `versions.json` file instead.

Note the full `git describe --tags` output is _still_ present in the binary, this is useful and left unchanged. It's just not used any more to guess SOF_MAJOR, SOF_MINOR and SOF_MICRO.

Use JSON because CMake and pretty much every other piece of software has a JSON parser out of the box.

This aligns with linux/Makefile, Zephyr/VERSIONS and probably many others. - except we use JSON because we're in 2023 so we don't spend time having fun re-implementing parsers any more.

### CODE REVIEW

**Comment by marc-hb** [comment]
This is ready for review but merge is blocked on the upgrade of the Docker image (#7513)

**Review by dbaluta — APPROVED** [review]
I think this is a good start from relying on git in order to get the version.

**Review by paulstelian97 — APPROVED** [review]
This is a great change. While it does create issues with redundant information between tags (which won't disappear) and the actual version, I believe we can take enough care to keep it in sync. So I'm more on the "yes this is good" side of the fence, approving.

**Review by kv2019i — APPROVED** [review]
Thanks @marc-hb ! We need to add this to the release checklist for 2.6 once that is created. FYI @mengdonglin @lgirdwood

**Comment by kv2019i** [comment]
One fail in https://sof-ci.01.org/sofpr/PR7532/build6883/devicetest/index.html , not related, proceeding with merge.

**Comment by marc-hb** [comment]
> Thanks @marc-hb ! We need to add this to the release checklist for 2.6 once that is created. FYI @mengdonglin @lgirdwood

Submitted:
- https://github.com/thesofproject/sof-bin/pull/123

Edited:
- https://github.com/thesofproject/sof/issues/7066

**Pull request merged**
