### PR TITLE
audio: volume: initialize variables before using

### PR DESCRIPTION
**Pull request by andrula-song**
initialize variables before using and finalize the
output align register to sink address for aligned
store.

Signed-off-by: Andrula Song <xiaoyuan.song@intel.com>

### CODE REVIEW

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
@andrula-song can we get this merged to main branch too. Thanks !

**Comment by abonislawski** [comment]
@lgirdwood @andrula-song  oh sorry, I thought this PR will merge this to main branch and I have already added this to stable-v2.1 to run all the scans etc, can we just change destination branch?

**Comment by marc-hb** [comment]
> can we just change destination branch?

Pretty sure this requires a new pull request.

**Comment by andrula-song** [comment]
> @andrula-song can we get this merged to main branch too. Thanks !
volume_hifi3.c file of the main branch is different with this one, so I would create a new PR for main branch.

**Comment by abonislawski** [comment]
> Pretty sure this requires a new pull request.
> 
> Force pushes make github diffs messy enough, now imagine changing the target branch mid flight...

Actually it is pretty easy to imagine changing the target branch and in fact it is possible, just click the edit button and you can simply select another branch.

**Comment by marc-hb** [comment]
Thanks @abonislawski for correcting me!

**Pull request merged**
