### PR TITLE
probes: adjust probe points limit

### PR DESCRIPTION
**Pull request by abonislawski**
This patch will adjust probe points limit to value verified
in the worst and corner cases

Signed-off-by: Adrian Bonislawski <adrian.bonislawski@linux.intel.com>

### CODE REVIEW

**Comment by lgirdwood** [comment]
No results for CML - retest.

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by lgirdwood** [comment]
No results for BYT.

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by lgirdwood** [comment]
@abonislawski trying CI again - looks like it got stuck.

**Comment by paulstelian97** [comment]
Is this still needed?

**Pull request closed without merging**
