### PR TITLE
Remove some unnecessary code

### PR DESCRIPTION
**Pull request by ranj063**

### CODE REVIEW

**Review by cujomalainey — APPROVED** [review]

**Review by iuliana-prodan — APPROVED** [review]

**Review by lgirdwood — APPROVED** [review]
Lets rerun CI since BYT DUT had issues yesterday.

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by lgirdwood** [comment]
> Lets rerun CI since BYT DUT had issues yesterday.

BYT fine - but a timout on CML suspend capture, could be network/script but lets retry.

**Comment by lgirdwood** [comment]
SOFCI TEST

**Review by lyakh — APPROVED** [review]
nice clean up! it addresses a comment from me to another PR from @ranj063

**Review by dbaluta — APPROVED** [review]

**Comment by lgirdwood** [comment]
CML known issue and unrelated to this PR.

**Pull request merged**
