### PR TITLE
configs: add ipc4 override config for tgl

### PR DESCRIPTION
**Pull request by aiChaoSONG**
The override config can be used to build tgl
and tgl-h firmware with IPC4 configuration.

Signed-off-by: Chao Song <chao.song@linux.intel.com>

### CODE REVIEW

**Review by marc-hb — COMMENTED** [review]
There is already a generic `-o` option, can we use it instead? We should stop duplicating Kconfig into a shell script, it's messy and does not scale. See how the kernel does it: https://github.com/thesofproject/kconfig

Then we have to duplicate these options in yet another CI interface layer on top. Instead we need the ability to input any kconfig configuration to CI or anything: completely flexible and generic with no options duplicated in multiple layers to maintain. 

EDIT:
- https://github.com/thesofproject/linux/pull/3382

**Review by RanderWang — APPROVED** [review]
LGTM

**Comment by lgirdwood** [comment]
Whats the use case ? I assume its to build for CI tests as this should also enable Zephyr.

**Comment by aiChaoSONG** [comment]
@lgirdwood It is used to build tigerlake firmware with IPC4 for CI and developers. sof+zephyr+ipc4 has build failure now, once it is fixed, it will be added in CI, too.

**Review by marc-hb — APPROVED** [review]

**Comment by lgirdwood** [comment]
@kkarask @wszypelt @mwasko - we can use the config for CI IPC4 mode.

**Review by lgirdwood — APPROVED** [review]

**Comment by plbossart** [comment]
@aiChaoSONG @lgirdwood we need to have a different file name for the result, e.g. sof-tgl.ri4 or sof-tgl.bin4. this needs to be different from sof-tgl.ri, which will lead to confusions and support issues.

**Comment by lgirdwood** [comment]
@marc-hb are you able to update the appropriate CMakefile to use the ```ri4``` file extension for IPC4 binaries (and topologies later) as I think @aiChaoSONG is off now for CNY

**Comment by marc-hb** [comment]
If this is top priority then yes I can. Thanks @ranj063 for @plbossart for providing some context. I need more, let's have a chat.

**Comment by marc-hb** [comment]
I expressed consistency concerns with `.ri4`: it would break `*.ri` scripts when the exact same `rimage` tool(s) are still used.

The current proposal seems to be `sof-tgl-ipc4.ri`

A (slightly) better place to discuss this: https://github.com/thesofproject/sof-test/issues/841

**Pull request merged**
