### PR TITLE
clean up IPC4 overlay for TGL/TGL-H

### PR DESCRIPTION
**Pull request by aiChaoSONG**
For legacy CAVS platforms (TGL/ADL/EHL), the default build config is IPC4 now,
and the overlay file is already emptied. Remove the option in this build script.

### CODE REVIEW

**Review by kv2019i — APPROVED** [review]
Thanks for the cleanup @aiChaoSONG !

**Comment by aiChaoSONG** [comment]
Update: The uses of `-i IPC4` is removed in CI, remove TODO, and force push for test.

**Review by ranj063 — APPROVED** [review]

**Review by marc-hb — APPROVED** [review]

**Comment by aiChaoSONG** [comment]
Please hold on to merge this, github action build need to be fixed.

**Comment by aiChaoSONG** [comment]
SOFCI TEST

**Comment by marc-hb** [comment]
> Please hold on to merge this, ...

Converting to draft which is the simplest and fastest way to block merge - and can be easily filtered out by maintainers. Just one click each way.

**Comment by aiChaoSONG** [comment]
Waiting for QB updates.
@wszypelt Once you have updated TGL/TGL-h firmware build in QB, please comment, then we can merge this PR.

**Comment by wszypelt** [comment]
@aiChaoSONG @kv2019i The changes have been made, I added PR to the queue, I think the results will be available within 30 minutes

**Review by tmleman — APPROVED** [review]

**Comment by dbaluta** [comment]
@aiChaoSONG so we can merge this, right? I wonder why MTL build passes now.

We no longer need: https://github.com/zephyrproject-rtos/zephyr/pull/62854 ?

**Comment by kv2019i** [comment]
@dbaluta So my latest understand: this PR has no relation to Zephyr updates, but this PR needs to go in together with a aCI change on Intel side. I'll do a sync change tomorrow with @wszypelt .

So if we have Zephyr PR update passing CI today, we can proceed to merge that (today).

**Pull request merged**
