### PR TITLE
[RTNR] Fix buffer size calculation

### PR DESCRIPTION
**Pull request by MingJenTai**
The correct frame length should be calculated by
FRAME_LEN = SAMPLING_RATE * PERIODS / 1000000

The macro COMP_PERIOD_FRAMES does the thing.

Signed-off-by: Curtis Malainey <cujomalainey@chromium.org>
Signed-off-by: Ming Jen Tai <mingjen_tai@realtek.com>

cherry-picked from a5fd52ec43f3efe3bea3f3f3a6ee53b71022ad95

### CODE REVIEW

**Review by cujomalainey — CHANGES_REQUESTED** [review]
This is not a direct cherry-pick of what landed on main, is there a reason why? https://github.com/thesofproject/sof/commit/a5fd52ec43f3efe3bea3f3f3a6ee53b71022ad95

**Comment by MingJenTai** [comment]
> This is not a direct cherry-pick of what landed on main, is there a reason why? [a5fd52e](https://github.com/thesofproject/sof/commit/a5fd52ec43f3efe3bea3f3f3a6ee53b71022ad95)

Hi @cujomalainey,

It is the cherry-pick of main, but the title was modified. Changed it back to be the same as the PR on main. Thanks!

**Comment by cujomalainey** [comment]
> > This is not a direct cherry-pick of what landed on main, is there a reason why? [a5fd52e](https://github.com/thesofproject/sof/commit/a5fd52ec43f3efe3bea3f3f3a6ee53b71022ad95)
> 
> Hi @cujomalainey,
> 
> It is the cherry-pick of main, but the title was modified. Changed it back to be the same as the PR on main. Thanks!

Hi MingJen,

The commit has not been updated, the commit should be direct cherry-pick with no modifications unless there is conflicts or a functionality issue

**Comment by MingJenTai** [comment]
> 
Hi @cujomalainey,

Created a new PR( https://github.com/thesofproject/sof/pull/5649 ). Please check if it is OK now. Thanks. 

Closing this one.

**Pull request closed without merging**
