### PR TITLE
Topology: Add HDA generic topologies with DMIC16k or DMIC48k on core 1

### PR DESCRIPTION
**Pull request by singalsu**
This patch enables test of multi-core DMIC pipelines.

Signed-off-by: Seppo Ingalsuo <seppo.ingalsuo@linux.intel.com>

### CODE REVIEW

**Comment by singalsu** [comment]
I'll keep this as draft as support for issue #4266 and likely close later. This change could be done possibly to some existing topology used in CI instead of these new topologies to get this tested.

**Comment by lgirdwood** [comment]
@singalsu how doers this work with @keyonjie PR that changes dmic no codec 48k to core 2 ?

**Comment by singalsu** [comment]
@lgirdwood I made this PR only to support a bug report. We didn't have a topology available that triggered the issue. I was planning to close this after the fix is done. OTOH I think this PR nicer than @keyonjie 's since it allows the CMakeList.txt or top level topology to specify the core IDs for intel-general-dmic.m4. Keyon's patch covers only the single nocodec topology. But since this is more general this is more risky. While we don't really need this test topologies set built, Keyon's is safer to proceed for CI needs.

**Comment by lgirdwood** [comment]
> @lgirdwood I made this PR only to support a bug report. We didn't have a topology available that triggered the issue. I was planning to close this after the fix is done. OTOH I think this PR nicer than @keyonjie 's since it allows the CMakeList.txt or top level topology to specify the core IDs for intel-general-dmic.m4. Keyon's patch covers only the single nocodec topology. But since this is more general this is more risky. While we don't really need this test topologies set built, Keyon's is more safe to proceed for CI needs.

ok, so this is only for further dmic and multicore testing ? I've no problem here - but adding to non test topologies will have power impact.

**Comment by singalsu** [comment]
I think everyone who needs these has got these built and it can opened from the link in the issue. I'll close this PR!

**Pull request closed without merging**
