### PR TITLE
Audio: EQ: Convert assert to normal fail

### PR DESCRIPTION
**Pull request by singalsu**

### CODE REVIEW

**Comment by singalsu** [comment]
Checked that pipeline will fail cleanly with forced NULL function, dmesg gets `HDA Analog: ASoC: trigger FE cmd: 1 failed: -22`.

**Comment by marc-hb** [comment]
https://sof-ci.01.org/sofpr/PR5771/build225/devicetest/?model=ADLP_RVP_NOCODEC&testcase=verify-pcm-list is failing because it's testing IPC4 for some unknown reason, which causes a mismatch:

```
[    4.532829] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: loading topology:intel/avs-tplg/sof-adl-nocodec.tplg
```

```
TPLG=/lib/firmware/intel/sof-tplg/sof-adl-nocodec.tplg MODEL=ADLP_RVP_NOCODEC ~/sof-test/test-case/verify-pcm-list.sh

2022-05-04 14:05:51 UTC [REMOTE_ERROR] Pipeline(s) from topology don't match pipeline(s) from system
```

**Comment by marc-hb** [comment]
> There have been some significant changes to main(codec name), please rebase your branch before checking on CI again

Just found the exact same comment in totally unrelated https://github.com/thesofproject/sof/pull/5324#issuecomment-1117532406 so this appears to be some sort of misdirected automation / spam, can probably be ignored.

cc: @lyakh

**Comment by fredoh9** [comment]
The device used for the test has unexpected conf file. SOF CI create ipc4.conf for ipc4 and delete it for ipc3. But it has ip4.conf, CI itself couldn't clean up.
Instead of blaming developers who borrow devices from SOF CI, as device demand is getting high, we need to have better device setup management.

**Comment by marc-hb** [comment]
SOFCI TEST

**Comment by marc-hb** [comment]
@singalsu still a draft?

The issue found by systemd in https://sof-ci.01.org/sofpr/PR5771/build238/devicetest/?model=TGLU_RVP_SDW&testcase=verify-kernel-boot-log is totally unrelated; working on it. Everything else in that run is green.

**Review by marc-hb — APPROVED** [review]

**Review by kv2019i — APPROVED** [review]

**Comment by wszypelt** [comment]
Thanks for the clear explanation, please ignore my earlier comment. It was written by misunderstanding and haste. As for the internal tests themselves, I added to the queue checking them again. should be done within 2-3 hours

**Comment by singalsu** [comment]
No changes done, just rebase and new push.

**Review by lgirdwood — APPROVED** [review]

**Pull request merged**
