### PR TITLE
Topology: modified initial config for the smart amp

### PR DESCRIPTION
**Pull request by ryans-lee**
Modified initial configuration param for the smart amp.
Total number of feedback channels was changed from 8 to 4.
Assigned 4ch feedback to 0 ~ 3 slots.

Signed-off-by: Ryan Lee <ryans.lee@maximintegrated.com>

### CODE REVIEW

**Review by lgirdwood — APPROVED** [review]

**Review by keyonjie — APPROVED** [review]
LGTM, thanks.

**Comment by lgirdwood** [comment]
CI reports unrelated.

**Comment by keyonjie** [comment]
Sorry, this introduces regression for nocodec mode, @ryans-lee is the feedback channel map change mandatory for Maxim DSM?

```
@@ -38,9 +38,9 @@ CONTROLBYTES_PRIV(SMART_AMP_priv,
 `              0x18,0x00,0x00,0x00,0x00,0x00,0x00,0x03,'
 `              0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,'
 `              0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,'
-`              0x18,0x00,0x00,0x00,0x08,0x00,0x00,0x00,'
+`              0x18,0x00,0x00,0x00,0x04,0x00,0x00,0x00,'
 `              0x00,0x01,0xff,0xff,0xff,0xff,0xff,0xff,'
-`              0xff,0xff,0x00,0x01,0xff,0xff,0xff,0xff"'
+`              0x00,0x01,0x02,0x03,0xff,0xff,0xff,0xff"'
 )

```

**Comment by lgirdwood** [comment]
@ryans-lee ping
@keyonjie @aiChaoSONG do we need to add this into CI and why is nocodec mode important for DSM ?

**Comment by aiChaoSONG** [comment]
@lgirdwood  The previous blob before this change allows us to capture a wave whose channel 0/1 is the playback wave, and channel 2/3 is the replica of channel 0/1 but with some delay.  We can do binary comparison between channel 0/1 and playback wave, channel 2/3 and playback wave in nocodec mode.
After this change, channel 0/1 keeps unchanged, but channel 2/3 is empty, so our test case will fail.

No big deal, we can modify the test case, and set the initial config before test, and recover config after test.

**Comment by lgirdwood** [comment]
Thanks @aiChaoSONG , so IIUC this config is needed for CI but @ryans-lee needs a different config for working DSM hardware ?

**Pull request merged**
