### PR TITLE
[RFC]Mux enum

### PR DESCRIPTION
**Pull request by juimonen**
This is an attempt to use enum control in mux/demux configuration.

For this PR to work properly you need many unmerged PR's:

fw:
https://github.com/thesofproject/sof/pull/3692
https://github.com/thesofproject/sof/pull/3688
https://github.com/thesofproject/sof/pull/3674
https://github.com/thesofproject/sof/pull/3652

driver:
https://github.com/thesofproject/linux/pull/2423

### CODE REVIEW

**Comment by lgirdwood** [comment]
@juimonen any updates here ?

**Comment by juimonen** [comment]
SOFCI TEST

**Comment by lgirdwood** [comment]
@juimonen can you rebase and force push again to pick up the latest CI updates. Otherise we are probably good and just pending kernel.

**Comment by paulstelian97** [comment]
Please resubmit with "main" as PR base branch.

**Pull request closed without merging**
