### PR TITLE
topology2: cavs-rt5682: expose spk core_id for overriding

### PR DESCRIPTION
**Pull request by yongzhi1**
Port from nocodec topology for multi-core validation.

### CODE REVIEW

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
@kv2019i pls review

**Review by kv2019i — APPROVED** [review]

**Comment by lgirdwood** [comment]
@yongzhi1 I think we are good to go, can you rebase. Thanks !

**Comment by yongzhi1** [comment]
Rebased, thanks @lgirdwood and @kv2019i for code review.

**Comment by marc-hb** [comment]
SOFCI TEST

**Pull request merged**
