### PR TITLE
[cavs2.5-001] topology1: tgl: add Waves-integrated topology builds [cherry-picked from stable-v2.2]

### PR DESCRIPTION
**Pull request by johnylin76**
cherry-picking commits from stable-v2.2

### CODE REVIEW

**Review by lgirdwood — APPROVED** [review]
@mwasko fyi - topology backport.

**Review by cujomalainey — APPROVED** [review]

**Comment by johnylin76** [comment]
@mwasko friendly ping

**Comment by cujomalainey** [comment]
Going to submit on monday if no response by then

**Comment by lgirdwood** [comment]
@abonislawski @marcinszkudlinski ping

**Comment by cujomalainey** [comment]
monday has come and gone for all, submitting

**Pull request merged**
