### PR TITLE
Audio: Set default SRC coefficients to 16 bits for APL platform

### PR DESCRIPTION
**Pull request by singalsu**
This patch adds for SRC component rate conversion filters coefficients
set selection to Kconfig. The menu entry allows to select a 16 bit or
32 bit set.

The default for Apollolake is changed to 16 bits to free up .bss for
other development. There's no known critical usage for SRC so the
lower quality and less conversions available should be acceptable.

Signed-off-by: Seppo Ingalsuo <seppo.ingalsuo@linux.intel.com>

### CODE REVIEW

**Comment by singalsu** [comment]
I've seen some of recent PRs to fail APL build so this my RAM save contribution. I feel the SRC configuration is overkill for current usage. If there's need for different compromise with more work there could be more choices between minimal 16 bit and full blown 32 bit set. Currently the code does not allow per conversion fraction level customization.

**Comment by fredoh9** [comment]
The change are straightforward. Just curious, how much RAM can be saved by changing to 16bit.

**Comment by singalsu** [comment]
@fredoh9 The saving is 76 kB but it's also due to dropping a lot of sample rate in / out combinations.

**Comment by lgirdwood** [comment]
Ci known issues.

**Pull request merged**
