### PR TITLE
Topology: HDA-generic: Use +20 dB EQ gain for DMIC capture pipelines

### PR DESCRIPTION
**Pull request by singalsu**
This patch replaces the default EQ 0 dB gain with +20 dB gain in
DMIC pipelines in hda-generic based topologies. It fixes the issues with
too silent capture level.

The gain was changed to 0 dB in a recent change to let UCM set it.
However this change remains needed for a while since the UCM initial gain
patch and remaining development of ALSA/ASoC 4ch capture for devices with
more than two microphones will take longer time to become available.

The impacted topologies are:

sof-hda-generic-2ch.tplg
sof-hda-generic-4ch.tplg
sof-hda-generic-eq-2ch.tplg
sof-hda-generic-eq-4ch.tplg
sof-hda-generic-idisp-2ch.tplg
sof-hda-generic-idisp-4ch.tplg

Note: The 0 dB high-pass version is preferred after all the needed
development is available.

Signed-off-by: Seppo Ingalsuo <seppo.ingalsuo@linux.intel.com>

### CODE REVIEW

**Comment by singalsu** [comment]
@fredoh9 Hi, seems that we still need the +20 dB EQ gain in hda-generic platforms for DMIC. So this reverts from the target arch what we discussed a while ago. Need to retry when new UCM is available.

**Comment by fredoh9** [comment]
> @fredoh9 Hi, seems that we still need the +20 dB EQ gain in hda-generic platforms for DMIC. So this reverts from the target arch what we discussed a while ago. Need to retry when new UCM is available.

sure, your changes are straight-forward. Sorry, I couldn't test that DMIC changes on HDA generic platforms.

**Comment by lgirdwood** [comment]
CI usual reports

**Comment by lgirdwood** [comment]
@singalsu does this need backported to 1.4.x and 1.5.x ? @juimonen does this align with your UCM updates ? @perexg fyi.

**Comment by juimonen** [comment]
@lgirdwood AFAIK this was present in 1.4, but removed from 1.5. So should be back ported probably to 1.5.x.

Background: we didn't have pga's with positive dB volume (amplification) prior to 1.5, so we had eq's configured to boost the mic level. We are little bit uncertain could we boost the dmic volume now with positive volume (so are user space components, ucm, pulseaudio, ui settings ready for it). So this is probably the easiest way to get the dmic volumes back to pre-1.5 levels, although the positive volume levels would be nicer way to "fix" this.

**Comment by singalsu** [comment]
@lgirdwood Thanks, I'll add shortly similar PR for 16k DMIC.

**Pull request merged**
