### PR TITLE
xtensa-build-zephyr.py: restore lost reproducible .ri checksum

### PR DESCRIPTION
**Pull request by marc-hb**
At the end of the build, parse the .ri file and print a reproducible
checksum of the its content.

This feature was in xtensa-build-zephyr.sh but never made it to the .py
conversion. It was lost when the .sh file was deleted in commit
https://github.com/thesofproject/sof/commit/ef028f634a0607d7706149b9248824b43664f9fc ("Removed obsolete xtensa-build-zephyr.sh")

### CODE REVIEW

**Comment by abonislawski** [comment]
It was not lost, it was turned off on internal branch and not included here because sof_ri_info is not ready for mtl, you can fix it firstly :)

**Comment by marc-hb** [comment]
> it was not lost, it was turned off on internal branch and not included here 

I think you're confusing the .sh and the .py files, maybe my commit message should be longer. I just checked both branches and I don't think this feature was ever implemented in the .py file.

> because sof_ri_info is not ready for mtl, you can fix it firstly :)

I will just skip MTL for now, imx needs to be skipped too anyway.

**Comment by marc-hb** [comment]
Fix for unrelated https://github.com/thesofproject/sof/actions/runs/3277791371/jobs/5395463299 failure submitted in #6439

**Review by kv2019i — APPROVED** [review]

**Comment by marc-hb** [comment]
No-change force push to resolve conflict with #6437 

One ADL device unavailable in https://sof-ci.01.org/sofpr/PR6402/build2028/devicetest/, everything else green.

**Comment by lgirdwood** [comment]
@marc-hb can you force push again now CI is back. Thanks !

**Comment by marc-hb** [comment]
Done. Amazingly, absolutely everything is green.

**Review by lgirdwood — APPROVED** [review]

**Pull request merged**
