### PR TITLE
zephyr: move Zephyr IDC implementation to idc-p4wq.c

### PR DESCRIPTION
**Pull request by kv2019i**
SOF uses IDC (Intra DSP Communication) protocol to orchestrate
work across multiple DSP cores.

The interface in sof/drivers/idc.h defines the protocol and
also provides a high-level interface for drivers. On Zephyr,
the SOF IDC protocol is used, but the actual communication
is implemented on top of Zephyr P4WQ workqueue interface,
instead of directly calling into drivers.

Move the Zephyr implementation from src/schedule/ into
src/idc/ which is more suitable place for this code.

Signed-off-by: Kai Vehmanen <kai.vehmanen@linux.intel.com>

### CODE REVIEW

**Comment by lgirdwood** [comment]
@kv2019i can you rebase this PR on HEAD. Thanks. Significant CI update.

**Review by lyakh — APPROVED** [review]
we have zephyr_ll.c, zephyr_domain.c... Maybe zephyr_idc.c would be more uniform? BTW, we could also move zephyr/edf_schedule.c to src/schedule/zephyr_edf.c and maybe also zephyr/schedule.c to src/schedule/zephyr.c?

**Comment by kv2019i** [comment]
@lyakh wrote:
> we have zephyr_ll.c, zephyr_domain.c... Maybe zephyr_idc.c would be more uniform? 

I was leaning towards using "p4wq" instead of "zephyr". Once Zephyr is main interface we use, using "zephyr" prefix everywhere does not seem right. Later on, we could have IDC implemented on something else than P4WQ, right. But, but, I think you are right that given the other files, it makes more sense to start with "zephyr_idc.c" . PR updated now.

> BTW, we could also move zephyr/edf_schedule.c to src/schedule/zephyr_edf.c and maybe also zephyr/schedule.c to src/schedule/zephyr.c?

Yes. I think we should start to empty the "wrapper/" and try to find a "place of least suprise" for all functionality we have. Some parts will be difficult, but I think thinks like scheduling and IDC have clear homes under src, so we should move them.

**Review by lgirdwood — APPROVED** [review]
@kv2019i @aborisovich what's the plan for using the Zephyr native IDC ?

**Pull request merged**
