### PR TITLE
app: remove explicit CONFIG_DW_ICTL_ACE_V1X

### PR DESCRIPTION
**Pull request by nashif**
This config was renamed is automatically selected for this platform, so
no need to include it here.

Signed-off-by: Anas Nashif <anas.nashif@intel.com>

### CODE REVIEW

**Comment by marc-hb** [comment]
Should fix build failure https://github.com/thesofproject/sof/actions/runs/3231144546/jobs/5290350055 , thx @nashif !

**Review by lyakh — APPROVED** [review]

**Review by kv2019i — APPROVED** [review]
D'oh, didn't notice this. Need to update https://github.com/thesofproject/sof/pull/6396 again

**Comment by kv2019i** [comment]
Given I need to update the west.yml PR again (for the dmic issue), @softwarecki @abonislawski are you good to merge this and remove this Kconfig on SOF side. Seems ok as it's enabled on Zephyr side for the board. I did a test build to confirm this indeed is the case.

**Review by abonislawski — APPROVED** [review]
Yes, please remove

**Pull request merged**
