### PR TITLE
audio: google: remove post processor

### PR DESCRIPTION
**Pull request by cujomalainey**
Dead code.

Signed-off-by: Curtis Malainey <cujomalainey@chromium.org>

### CODE REVIEW

**Review by marc-hb — APPROVED** [review]

**Review by dbaluta — APPROVED** [review]

**Review by paulstelian97 — APPROVED** [review]
I suppose that if you're wrong this can be added back as-needed. Removing unneeded code sounds good to me, approving.

**Comment by dbaluta** [comment]
Having a closer look at this @cujomalainey care to provide some context about Post Processor component?

It look like it is used with sof-tgl-max98373-rt5682.m4 -> sof-smart-amplifier.m4 -> pipe-gapp-smart-amplifier-playback.m4 -> google_audio_post_processing.m4

**Comment by cujomalainey** [comment]
@dbaluta thanks for catching that, I will remove that as well.

This was integration from another team that never shipped. If we ever want to use the features it was bringing in we will implement it in a different manner that relies on EQ/DRC backends so we have less code duplication.

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
@wszypelt not expecting this module code removal to fail, can you confirm PR is good ? Thanks !

**Comment by cujomalainey** [comment]
@wszypelt going to merge tomorrow unless I get a signal not to

**Review by johnylin76 — APPROVED** [review]

**Pull request merged**
