### PR TITLE
[SKIP CI] empty PR TEST - Docker image digest 5cffb0b235e0 failing testbench

### PR DESCRIPTION
**Pull request by marc-hb**

### CODE REVIEW

**Comment by marc-hb** [comment]
failure https://github.com/thesofproject/sof/runs/4721266153?check_suite_focus=true was apparently caused by today's docker image 20220105 , just reverted https://hub.docker.com/r/thesofproject/sof/tags

Re-running.

**Comment by marc-hb** [comment]
After reverting to image digest 3bf321bd4fd7 https://github.com/thesofproject/sof/runs/4721605561?check_suite_focus=true is passing again.

**Comment by ranj063** [comment]
https://github.com/thesofproject/sof/pull/5156 should make builds pass with the latest docker image

**Comment by marc-hb** [comment]
https://github.com/thesofproject/sof/runs/4730598907?check_suite_focus=true is passing after `git commit --amend -C HEAD` and force push which runs on the latest, moving `pull/5155/merge` that includes the just merged #5156

**Pull request closed without merging**
