### PR TITLE
xtensa-build-zephyr.py: add flexibility to generate `tools/` only

### PR DESCRIPTION
**Pull request by marc-hb**
Installing most of the tools/ directory does not technically require building any platform, so add that possibility.

This is useful because the Jenkins-based CI builds the (userspace) tools separately. So far it has been picking hardcoded source paths but of course the HWMv2 transition just broke that:
- https://github.com/thesofproject/sof/pull/8913

While it's too late this time (we want to keep CI able to test stable branches for some time), this commit prepares a future where all CIs can stop hardcoding Zephyr source paths and pick the output of the xtensa-build-zephyr.py installer and indirection layer instead.

### CODE REVIEW

**Comment by marc-hb** [comment]
@lrudyX , @wszypelt I can't find any error message in failed https://sof-ci.01.org/sof-pr-viewer/#/build/PR8916/build13686222, can you help?

**Comment by wszypelt** [comment]
@marc-hb hmmm problem when creating compilation and empty logs ;/(I need to analyze it) I have already added this PR to the queue. I think there will be new results within an hour or two

**Comment by marc-hb** [comment]
> I have already added this PR to the queue. I think there will be new results within an hour or two

https://sof-ci.01.org/sof-pr-viewer/#/build/PR8916/build13691475 is reported green but when looking at the internal site I see some red in a mostly green and I discovered that... no tests were run at all

> Triggered build: [SOF_FW_null_01.01.00.6961] build/13691711


I'm going to change the date and force-push to trigger again.

**Comment by marc-hb** [comment]
https://sof-ci.01.org/sof-pr-viewer/#/build/PR8916/build13693983 now ran fine; all green.

Both ACE https://sof-ci.01.org/sofpr/PR8916/build3251/devicetest/index.html and CAVS https://sof-ci.01.org/sofpr/PR8916/build3252/devicetest/index.html are a DSP panic disaster due to #8908

**Comment by marc-hb** [comment]
New, much better results after a lot of Zephyr water under the bridge.

ACE https://sof-ci.01.org/sofpr/PR8916/build3487/devicetest/index.html has only one known and unrelated pause/resume failure

https://sof-ci.01.org/sofpr/PR8916/build3488/devicetest/index.html is 100% green.

Everything else including https://sof-ci.01.org/sof-pr-viewer/#/build/PR8916/build13728357 is green.

**Review by lgirdwood — APPROVED** [review]

**Review by kv2019i — APPROVED** [review]

**Pull request merged**
