### PR TITLE
MTL 005 drop stable: sync topology2 updates with tip of main

### PR DESCRIPTION
**Pull request by mengdonglin**
Please don't merge this PR until we get approval from @ranj063 @jsarha @bardliao @yongzhi1 @udaymb 

This is to align topology2 updates with tip of main branch to integrate 3P modules and internal test. 

Revert 4 previous topology2 updates to avoid conflict:
30f454312ec7e9451c5f14995b0dd160409b240a Topology2: sdw-jack-generic: add 24 bit format support for sdw jack
006f71e212e32b8c0024ec326dbaf66628758f88  topology2: add sof-mtl-cs42l42-l0-max98363-l2-4ch support
8a020dac19e075d1bc009bc79c186ef88e77fb01 topology2: sdw-jack-generic: add SDW_JACK_CAPTURE_CH macro
98bf5212f7c7192a8543b4028b57619f09bd953b Topology2: sdw-jack-generic: add 1 ch format support

And then cherry pick all recent topology2 updates:
b267012f22854ca60b6eed9bb3142271af87befa Topology2: sdw-amp-generic: add missing num_input_pins
2fb0c1d8110eb1ccf643c2e020c62237ebc89d4d Tools: Topology2: Add a development HDA generic MCPS benchmark topology
a6fa09cca79abe40bbff466359218b10fcc46efc Topology2: add sof-tgl-rt711-rt1308-rt715 topology
4fa2ad426142bea9eeae0be5213883edc5bda0e7 Topology2: sdw-amp-generic: add 2nd amp feedback when SDW_AMP_FEEDBACK is true
cc3b75665fc77ec423397f827c3d0d12824c289f Topology2: hdmi: use macro to set HDMI BE name
b1ce311540e0690fb3cb091a3c1fb09d3a6a0185 topology2: pipelines: dai-copier-eqiir-module-copier-capture: Replace audio_format object
511f680b02a68a42daaf1749465e07d1f483e917 topology2: pipelines: io-gateway: Replace audio_format object
914b855d72718ec204138f0bf76b4ba636702718 topology2: components: mixout: Replace audio_format object
7ad6659b9ebd1145343753abb058ca50a7b46a26 topology2: components: mixin: Replace audio_format object
593563b69e44b42168179ab6e9d4efe4f457a3d2 topology2: cavs-mixin-mixout-efx-hda.conf: Uppercase IIR and FIR
50f5c8fbdc567296170ed188dd33aa37441c70b0 topology2: Rename remaining non mixer kcontrols to follow new naming scheme
a3814c58b95285ad9990d9134e9f4fcdfe8fe557 topology2: sdw-jack-generic.conf: Rename mixers
2af91434b54d2c450a5df2ef438ea22b1f7636cc topology2: cavs-sdw-src-gain-mixin.conf: Rename mixers
bda1bcd5bc0b152dd0a943fdde7ce168e31042fd topology2: cavs-rt5682.conf: Rename mixers
2cef521c3672d5f25e4623ef3e87889aa064a889 topology2: cavs-nocodec-multicore.conf: Rename playback volumes
a0b1a391b82ea656b94232be557b3357d5b2796f topology2: cavs-mixin-mixout-efx-hda.conf: Rename Iir and Fir Eqs
ecff8a1d3db2cf198e04421f6fdf275b378d186b topology2: cavs-mixin-mixout-efx-hda.conf: Improve mixer names
3de4a6e5d7b6420813a5e830eafa588f78c709fa topology2: cavs-sdw : Update BT offload SSP for MTL chromebook
584e2f62e5b7dd676c0e865b43f70d6e09d280fc topology2: cavs-nocodec-multicore: Replace audio_format objects
4a64defa9467b8ec4dfa18c18904410c5864d1b1 topology2: cavs-rt5682: Replace audio_format objects
bdd3bf2409f9cbc3d12921336b2124672587e504 topology2: cavs-nocodec-bt: Replace audio_format objects
83ff81984a7a446b779141e2f7845932cecb94b5 topology2: deepbuffer-playback: increase default buffer_size_max
77e3e92157fb70fd749daa7a759500eb639e33bc topology2: cavs-rt5682: Add 2ch DMIC topology
f0f5bddd7b1e7a13bacdf31139153a6d923ea567 topology2: fix dai index in nocodec multicore
f5df5097c802f7bd1a86b0159a38ef634956aa81 topology2: fix nhlt debug binary names
75e8f4b63c168fb7e7ee11b9db60812a57c9f915 topology2: cavs-nocodec: Introduce macros for PCM IDs
f0b44b48549179a76626832d2abf6f6e6d661ef1 Topology2: sdw-jack-generic: add 24 bit format support for sdw jack
b75a94bfd3ac7f2c16113c1a98794fc8c64a9137 topology2: cavs-nocodec: run DMIC pipelines on core1
561f4b036c7ede52e62cd782d225a01d40934f5e topology2: sdw-jack-generic: Fix the number of input pins
d3f8bdc3044b98dbd9f0565758cbe07ab1a897ad topology2: add sof-mtl-cs42l42-l0-max98363-l2-4ch support
8d5e624d03477a1fd825f318584f2af635875674 topology2: intel: hdmi-generic: Replace audio_format objects
8cb7bf1baf15fdf20ac2cdca28d1349281a05978 topology2: cavs-mixin-mixout: Replace audio_format instance
8ef4d51e686106e9d8090cb8c428f16651b5ab3a topology2: sdw-jack-generic: add SDW_JACK_CAPTURE_CH macro
f6f57fe82b2f4487deb4f49674f974c706622c96 Topology2: sdw-jack-generic: add 1 ch format support
a5c0c49707309b54e20ac987586de69d9ba1f45e topology2: add development tplg to test playback with 2 cores
1da18c2caa4693755ec430ba0cd5d3bc5907f081 topology2: cavs-sdw: Build passthrough LNL FPGA topology
f8ad12734db153535d0899f964caa937bbc913e7 topology2: cavs-sdw: Add option for passthrough pipelines
6863eda16832279706224dbe47b6bcf9bdc16621 topology2: add sof-mtl-rt712-l0-rt1712-l3.tplg
b9b030757f47652f47580cbd294a26d1e26b74df topology2: dmic-generic.conf: Rename "DMIC" PCM name to "DMIC Raw"
08acbe4b6f64ccd9e9799a0af5bb2ff7f180328e topology2: cavs-nocodec.conf: Rename ssp-capture and DMIC0 Raw PCMs
6fb22d645ef673034efdcdc1dd7bc94197db5d59 topology2: intel: dmic-generic: Simplify the core ID setting
f1075489cf7d3af169a479d316b77e2bd3a1c934 topology2: dai-copier: Add clarification on input/output format counts
6e2d4973714dee424b60dac7beb29b91d22a03e8 topology2: dai-copier: num_input_pins/num_output_pins shouldn't be mandatory
66aaa599e97536a1d14f5999e3578cd92b2bca8e topology2: dai-copier: Change the naming convention
ab9449fa086ed27f226a1c5e2f8da5de0d94e72f topology2: tokens: Reduce the string length of token names
1b9cb679bb4b27973d18b77fd8fccae44f7c419f topology2: components: Make uuid common for all widgets
96bd6bc62db904d5edf1d9a672c1ce147fecc24d topology2: copier: Rename it to dai-copier
a6984b85030f8712e65d4bd23c44449122601152 topology2: dmic-generic.conf: Rename generic DMIC volume
b918e1f3166574d1b0ee456a900df66e6bd5b168 topology2: nocodec-ssp0-2level.conf: Rename Port0 Aux Volume
bdff11cc7ab8a6205b0a0d91aad40f870a22f436 topology2: cavs-nocodec.conf: Rename DMIC0 post mux volumes
0f7f4e96b8d516f584de64761369d734c70332dc topology2: cavs-nocodec.conf: Rename SSP0 Capture Volumes
76310a0a0e9f8b503d4f25208ccd669eb6938efe topology2: cavs-nocodec.conf: Rename SSP0, SSP1, and SSP2 playback volumes
601d2bc41ec7316231b8472d40b0e4a4b04436d3 topology2: sdw-amp-generic: set virtual widget type output
94f8b0c4d43773fa013aebbad5db4ecea14dbbdd topology2: fix number range between 1 and 1000 used by Regex
fda59fb7d4e983c5d9ce82b908b471755bb516ec topology2: remove cavs-sdw.tplg from avs-tplg
3835846836d43cf142e9e6420ee864b509540ec3 topology2: sdw-amp-generic: Show all aggregated DAIs on the graph
919b402abc6c2acd191c74bd7d01c292d6ec6f0f topology2: dai-copier: Remove ALH support
05628c9c48e416696328011cab6c46583768c2f1 topology2: Use the new ALH dai copier class
e9353b0eedf919f3911950f64ef7cf9a9c8d7db3 topology2: Introduce a new pipeline class
457113a275ab6ba7cd9325e34eb12876a058a26e topology2: components: Introduce a new class definition for ALH DAI copiers
af9bedb63ec4f7e50bbcfdd7dccc0862572201ee topology2: cavs-mixin-mixout-hda: Rename mixin-mixout mixers
e5455775b04120e4f2df9283b96fe06d44939b7f topology2: copier: Remove host gateway type support
b534fc61929dceb3700dacc8911aabbb8c659db1 topology2: host-gateway-playback: Use host-copier
ac26e70d9526e535275d05a12c74eb3ca2433dd7 topology2: host-gateway-capture: use host-copier
81a354e750b38010d3e9da86874e5a8d77e84fda topology2: gain-copier-capture: Use host-copier
3bee3c25fc471bedde04da8429f5c1b3021ded0f topology2: gain-playback: Use host-copier
9e95cd288bc371581dcb0960b556d490bd825913 topology2: gain-capture: Use host-copier
eb157a5c2fecebf36f1109b133d22c130f9ebdab topology2: mixout-gain-host-copier-capture: Use host-copier
b86acaa353bcba13754e16f009fe903c7b82b41f topology2: deepbuffer-playback: Use host-copier
f942a0338aecbff8c702f9b9ab0365e0df2c0e5f topology2: src-gain-mixin-playback: Use host-copier
be825a8581716cc580187ae117f22819dc57aa15 topology2: host-copier-gain-src-mixin-playback: Use host-copier
f211f4c9dae7c9d5aba6a90fdfb9f0d9ec27e9a2 topology2: host-copier-gain-mixin-playback: Use host-copier
f64a424bfd5def42d83d2312cf50f05ef22c5ce2 topology2: components: Add a new class definition for the host copier gateway
d132e25480896c0031432c197389ea9d7f126a28 topology2: cavs-nocodec-bt: Remove duplicate route
d87b5f9d0b748974339c042fe5fa72b908c1ba41 topology2: cavs-nocodec-bt: fix bclk for loopback A2DP case
3436ea54ab740b445bed0a45949230e4923c66b8 topology2: add tgl rt712 topology
a2944ddc51600f210affb0852d571f77acdd27ba topology2: move bt nocodecs to development
004241927f3a52d67e1e0d75b2db04438d43ea90 topology2: sdw-amp-generic: use fixed format on amp feedback io
8c005ef6a909acbc8c886db578ea2499ce8677d9 topology2: sof-lnl-nocodec-fpga: Add 2ch DMIC topologies
9e7ec5a3f2560c29ca809c27078ae40a683932be Revert "topology2: cavs-nocodec: add a module copier to SSP 0 capture pipeline"
406e660a34b6e09298e2d10c3e27cdd60f8cc076 topology2: add google rtc aec support
912408822cc21fd2e6308f55864b7ca91bf8f07c topology2: add google-rtc-aec-reference
4bf7c600615a077e717dfc6609c3526a505ca53c topology2: add google-rtc-aec-capture pipeline
ff5c10337f01f2be6b2dbbb8adb74d7cfaff48c4 topology2: add google rtc aec module support
4123f95353fec40f255675db98dc2ea7486ab14b topology2: cavs-nocodec: Build LNL nocodec topology
142b8de409b568b71a2964a27fdde2b65cb1c436 topology2: intel: dmic-generic: Implement passthrough option
88ead250376a2ad7efcffaa70453330acc2ed82d topology2: intel: dmic-generic: Make processing pipelines optional
fff55d42351f47bf70f807463ae3049a55634066 topology: include: pipelines: ip-gateway-capture: set default direction
19d9cce4cfc404b7e9562abbf74bae53828c4645 topology2: cavs-nocodec: Implement passthrough option
5ea630dbef58d1b0c1e202d99209deac8a0b7d9d topology2: cavs-nocodec: Make the processing pipelines optional
d37da44c39d6c52d6dee42c03830deac1cfecc3d topology2: cavs-nocodec: Make io-gateway for SSP1 capture conditional

### CODE REVIEW

**Comment by lgirdwood** [comment]
@abonislawski fyi.

**Comment by mengdonglin** [comment]
> @mengdonglin I am not sure if chrome kernel works with topology from main branch. Need @udaymb @jairaj-arava @yongzhi1 to verify.

And let's see if a new mtl release branch will branch out that can align topology with main.

**Comment by jsarha** [comment]
When I check diff between this branch and sof/main, I see this:
`diff --git a/tools/topology/topology2/platform/intel/sdw-amp-generic.conf b/tools/topology/topology2/platform/intel/sdw-amp-generic.conf
index c3821d79d..57f3a0891 100644
--- a/tools/topology/topology2/platform/intel/sdw-amp-generic.conf
+++ b/tools/topology/topology2/platform/intel/sdw-amp-generic.conf
@@ -266,7 +266,7 @@ IncludeByKey.NUM_SDW_AMP_LINKS {
                "true" {
                        Object.Base.route [
                                {
-                                       source  "host-copier.0.playback"
+                                       source  "host-copier.2.playback"
                                        sink    "virtual.sdw-amp"
                                }
                        ]
`
@mengdonglin  , @ranj063 , are we missing something?

**Comment by mengdonglin** [comment]
@jsarha Thanks for your review. I'll close this PR and wait for new MTL release branch to align topology with main branch.

**Pull request closed without merging**
