### PR TITLE
[CACHE] generic code: IPC, DMA, DAI, host, pipeline

### PR DESCRIPTION
**Pull request by lyakh**
Another orthogonal part of cache sparse annotation work

### CODE REVIEW

**Comment by lyakh** [comment]
There's a problem with https://github.com/thesofproject/sof/pull/5801/commits/b4abc1adefb785c101a88281e0a065a69b8a8d86 currently: it tries to acquire the same buffer recursively inside `pipeline_for_each_comp()`. This would normally be prevented by checking `.walking` but we cannot check that before acquiring the buffer...

**Comment by marc-hb** [comment]
> Checkpatch is complaining about too long lines, ... and missing empty lines between variable definition and code.

To be clear: you don't want to fix these because it would add whitespace changes to otherwise "pure sparse" commits? Then it makes sense to me. Otherwise they all seem very easy to fix and 100 lines is already very long. People work on other codebases besides the Linux kernel and SOF, 80 is still a standard.

**Comment by lyakh** [comment]
> > @lyakh we should use the `_thread()` calling convention by default for audio processing/pipeline uses as this will be run a a Zephyr thread. This `_thread()` API will need wrapped to the spinlock version for SOF+xtos.
> 
> Where is the #if **XTOS** use irq_version() ? Can we make this part of this PR ?

@lgirdwood we already have that: https://github.com/thesofproject/sof/blob/9d2e82adf043f501fa899e274998c2c7e8c64baf/src/include/sof/coherent.h#L386-L391

**Comment by lyakh** [comment]
CI: one alsabat and 3 suspend-resume failures. Seem unrelated also because the previous version was all green and the only differences are a split and an empty line to fix checkpatch warnings.

**Comment by lgirdwood** [comment]
> > > @lyakh we should use the `_thread()` calling convention by default for audio processing/pipeline uses as this will be run a a Zephyr thread. This `_thread()` API will need wrapped to the spinlock version for SOF+xtos.
> > 
> > 
> > Where is the #if **XTOS** use irq_version() ? Can we make this part of this PR ?
> 
> @lgirdwood we already have that:
> 
> https://github.com/thesofproject/sof/blob/9d2e82adf043f501fa899e274998c2c7e8c64baf/src/include/sof/coherent.h#L386-L391

We need this the opposite way around. Our default will be native Zephyr so ```coherent_acquire()``` will be implemented as the thread version. We do need to have the ```#if !ZEPHYR``` which defines the coherent_acquire() as coherent_acquire_irq() (aka the xtos version).

**Comment by lyakh** [comment]
> We need this the opposite way around. Our default will be native Zephyr so `coherent_acquire()` will be implemented as the thread version. We do need to have the `#if !ZEPHYR` which defines the coherent_acquire() as coherent_acquire_irq() (aka the xtos version).

@lgirdwood it is default. `buffer_acquire()` (note, no `buffer_acquire_thread()`) calls it and it's the only coherent API user ATM. And this isn't something that this PR introduces. I understand that we *should* just use `coherent_acquire()` as the API call and that it then should resolve to the threaded version on Zephyr, and I'll do this, but can we do that as a separate PR? This one seems to me to be big enough as it is already.

**Comment by lgirdwood** [comment]
> > We need this the opposite way around. Our default will be native Zephyr so `coherent_acquire()` will be implemented as the thread version. We do need to have the `#if !ZEPHYR` which defines the coherent_acquire() as coherent_acquire_irq() (aka the xtos version).
> 
> @lgirdwood it is default. `buffer_acquire()` (note, no `buffer_acquire_thread()`) calls it and it's the only coherent API user ATM. And this isn't something that this PR introduces. I understand that we _should_ just use `coherent_acquire()` as the API call and that it then should resolve to the threaded version on Zephyr, and I'll do this, but can we do that as a separate PR? This one seems to me to be big enough as it is already.

Ok, lets do a follow up PR with the incremental change.

**Pull request merged**
