### PR TITLE
tools: ctl: add the ability to append headers directly

### PR DESCRIPTION
**Pull request by cujomalainey**
Sometimes we just want to append a SOF header for a payload to be used later in something like a UCM. Allow sof-ctl to consume just files and append the header for the output.

Signed-off-by: Curtis Malainey <cujomalainey@chromium.org>

### CODE REVIEW

**Review by lgirdwood — COMMENTED** [review]
@cujomalainey I assume this allows users to dump header + payload to file ?

**Comment by cujomalainey** [comment]
@lgirdwood that is correct, its for those who just want to generate a payload to be used outside sof ctl

**Review by lgirdwood — APPROVED** [review]
Still need more testing or good for v2.4 (stable branch will fork soon)

**Comment by cujomalainey** [comment]
This definitely needs more testing still

**Pull request closed without merging**
