### PR TITLE
topology: sof-cht-max98090 move DAI definition above media pipeline

### PR DESCRIPTION
**Pull request by cujomalainey**
The DAI definition needs to come first otherwise the media pipeline with
be parsed incorrectly resulting in a failure to load the topology

Signed-off-by: Curtis Malainey <cujomalainey@google.com>

### CODE REVIEW

**Comment by tlauda** [comment]
@cujomalainey What is the exact problem? @xiulipan has recently fixed DAI_ADD macro, so maybe your change is no longer needed.

**Comment by cujomalainey** [comment]
@tlauda for some reason on ToT the topology will parse out differently and leave the schedule component token in the final conf file which when parsee by the kernel will not be defined properly, I can attach logs and examples in a few hours

**Comment by tlauda** [comment]
@cujomalainey Yes, please. And also what is ToT?

**Comment by ranj063** [comment]
> @cujomalainey What is the exact problem? @xiulipan has recently fixed DAI_ADD macro, so maybe your change is no longer needed.

@tlauda the sof-dai-playback m4 file defines the schedule comp for the media pipeline to use. So the DAI_ADD def has to be before the media pipeline is added.

**Comment by juimonen** [comment]
@tlauda media pipe definition needs the scheduling component definition (in dai), because of branched pipeline. Dai definition takes only 1 pipeline id as argument (which is the low latency). That's why it should be before media pipe... so is this somehow changed now?

**Comment by juimonen** [comment]
@ranj063 ok you we're before me here :)

**Comment by tlauda** [comment]
@ranj063 @juimonen Got it now, thanks.

**Comment by cujomalainey** [comment]
@tlauda fyi ToT (top of tree) :)

**Comment by xiulipan** [comment]
@cujomalainey @tlauda It seems like a workaroud to me. I will look into the issue to check what goes wrong with the m4 framework.

**Comment by tlauda** [comment]
@xiulipan It isn't a workaround.  Media pipeline needs particular DAI as a scheduling component, so it needs to be defined before pipe itself.

**Comment by xiulipan** [comment]
@tlauda Got that, thanks for the explanation, then this is m4 limitation. We will need to add this into some WIKI or readme.

**Pull request merged**
