### PR TITLE
Revert(s) to fix APL nocodec support

### PR DESCRIPTION
**Pull request by plbossart**
recent commits broke APL_NOCODEC CI, revert all of them blindly to restore functionality

### CODE REVIEW

**Comment by lgirdwood** [comment]
> recent commits broke APL_NOCODEC CI, revert all of them blindly to restore functionality

What's the repo rate, I've just merged 3 PRs from today with 100% passes in CI.

**Comment by ranj063** [comment]
> What's the repo rate, I've just merged 3 PRs from today with 100% passes in CI.

100% Liam. My suspicion is on the commit that adds the deep buffer PCMs for the nocodec topology. Let me submit a PR to remove those for APL

**Comment by marc-hb** [comment]
Quoting #4526
> we dont run multiple-pipeline-all test in the device test for PRs. thats why

**Comment by plbossart** [comment]
> Quoting #4526
> 
> > we dont run multiple-pipeline-all test in the device test for PRs. thats why

D'oh. that's crazy. these tests fail immediately when there's a problem, not sure why they were filtered out.

**Comment by plbossart** [comment]
My local tests can narrow the issue to one patch

Revert "topology1: sof-cavs-nocodec: Add the deep buffer PCMs"

The deep buffer PCM never worked for this test it seems.

**Comment by ranj063** [comment]
@plbossart replacement for this one in https://github.com/thesofproject/sof/pull/4534

**Pull request closed without merging**
