### PR TITLE
tools: plugin: modules: Pass device_name with environment variable

### PR DESCRIPTION
**Pull request by yongzhi1**
Add environment variable to compile model for different target device without rebuild.

### CODE REVIEW

**Review by lgirdwood — APPROVED** [review]
LGTM @ranj063  pls review.

**Review by ranj063 — CHANGES_REQUESTED** [review]
@yongzhi1 I have a different patch for this. Let me submit that version

**Comment by yongzhi1** [comment]
> @yongzhi1 I have a different patch for this. Let me submit that version

Ack, let me close this one.

**Comment by ranj063** [comment]
> > @yongzhi1 I have a different patch for this. Let me submit that version
> 
> Ack, let me close this one.



> > @yongzhi1 I have a different patch for this. Let me submit that version
> 
> Ack, let me close this one.

@yongzhi1 here's the replacement https://github.com/thesofproject/sof/pull/9134

**Pull request closed without merging**
