### PR TITLE
scripts/xtensa-build-zephyr.py: checksum [sof_]version.h files

### PR DESCRIPTION
**Pull request by marc-hb**
`git describe` differences happen, especially when trying to optimize cloning and this is for instance what happened in
https://github.com/thesofproject/sof/pull/6950#issuecomment-1396150533 where zephyr tags were fetched on Linux but not on Windows

This also makes plain git version differences more obvious; no need to scroll all the way up and scan the build logs.

Signed-off-by: Marc Herbert <marc.herbert@intel.com>

### CODE REVIEW

**Comment by marc-hb** [comment]
https://github.com/thesofproject/sof/actions/runs/3953435969/jobs/6769706666 shows a `zephyr_version.h` difference which should be fixed by
- #6950

**Review by lgirdwood — APPROVED** [review]
@aborisovich good for Windows ?

**Review by dbaluta — APPROVED** [review]

**Comment by marc-hb** [comment]
While @aborisovich 's review is always desired,  this change is 100% OS-independent and the Windows builds in https://github.com/thesofproject/sof/actions/runs/3953435969/jobs/6769706666 show the versions .h files checksummed as expected.

**Review by kv2019i — APPROVED** [review]

**Comment by aborisovich** [comment]
> While @aborisovich 's review is always desired,  this change is 100% OS-independent and the Windows builds in https://github.com/thesofproject/sof/actions/runs/3953435969/jobs/6769706666 show the versions .h files checksummed as expected.

Sorry guys, I've been on vacation, returning on Monday :-)

**Pull request merged**
