### PR TITLE
Integrate RTNR into sof-adl-max98357a-rt5682

### PR DESCRIPTION
**Pull request by MingJenTai**
Signed-off-by: Ming Jen Tai <mingjen_tai@realtek.com>

### CODE REVIEW

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
@XiaoyunWu6666 fyi - FW oops.
@MingJenTai I think this is probably unrelated as CI does not run topologies with 3rd part processing. Lets rerun to be sure.

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by MingJenTai** [comment]
@lgirdwood  Hi, any update to merge this Pull Request? Thank you!

**Comment by lgirdwood** [comment]
> @lgirdwood Hi, any update to merge this Pull Request? Thank you!

Sorry, it looks like CI git blocked and never completed. Rerun it.

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by lgirdwood** [comment]
CI issue on ALD unrelated to this PR
```
/sys/module/snd_sof_pci/parameters/tplg_path:(null)
----------------------------------------
declare -- cmd="journalctl_cmd"
2021-09-23 11:07:35 UTC [ERROR] Caught kernel log error
===========================>>
[    5.579033] kernel: i915 0000:00:02.0: [drm] *ERROR* rcs'0 reset request timed out: {request: 00000001, RESET_CTL: 00000000}
<<===========================
2021-09-23 11:07:35 UTC [REMOTE_ERROR] Starting func_exit_handler(), exit status=1, FUNCNAME stack:
2021-09-23 11:07:35 UTC [REMOTE_ERROR]  main()  @  /home/ubuntu/sof-test/test-case/verify-kernel-boot-log.sh
2021-09-23 11:07:35 UTC [REMOTE_INFO] Test Result: FAIL!

```

**Comment by MingJenTai** [comment]
Thanks!

**Pull request merged**
