### PR TITLE
Fix wov topology issue

### PR DESCRIPTION
**Pull request by aiChaoSONG**
Minor wov topology issues, fix them in this patch, or the wov feature doesn't work

### CODE REVIEW

**Comment by aiChaoSONG** [comment]
@ranj063 I'd like to add a test topology sof-hda-generic-2ch-kwd.tplg after this PR, but quote your comments in #7106
> why only MTL, why not TGL/ADL too?

For MTL, we have to set `DMIC_DRIVER_VERSION == 3` for MTL, but it is not needed for TGL/ADL, that means we cannot have a single hda-generic topology for all three MTL/TGL/ADL platforms, but can we have two? for example, sof-mtl-hda-generic-2ch-kwd.tplg/sof-tgl-hda-generic-2ch-kwd.tplg

**Comment by juimonen** [comment]
@aiChaoSONG not sure could we have the default driver_version behind platform conditionals in include/dais/dmic.conf?

**Comment by aiChaoSONG** [comment]
> @aiChaoSONG not sure could we have the default driver_version behind platform conditionals in include/dais/dmic.conf?

The problem is that in a single topology binary, we can only have a single driver_version, which can not support MTL/TGL simultaneously.

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
@RanderWang pls review

**Review by ranj063 — APPROVED** [review]

**Pull request merged**
