### PR TITLE
Restore binary file name for sof FWs

### LINKED ISSUE #869: Build result changes from sof-apl.ri to sof_apl.ri
-rw-rw-r-- 1 pxl pxl 188416 1月  23 13:24 build_apl/sof_apl.ri
-rw-rw-r-- 1 pxl pxl  85880 1月  23 13:24 build_bdw/sof_bdw.ri
-rw-rw-r-- 1 pxl pxl  87056 1月  23 13:23 build_byt/sof_byt.ri
-rw-rw-r-- 1 pxl pxl  87848 1月  23 13:23 build_cht/sof_cht.ri
-rw-rw-r-- 1 pxl pxl 163840 1月  23 13:24 build_cnl/sof_cnl.ri
-rw-rw-r-- 1 pxl pxl  85880 1月  23 13:24 build_hsw/sof_hsw.ri
-rw-rw-r-- 1 pxl pxl 163840 1月  23 13:24 build_icl/sof_icl.ri
-rw-rw-r-- 1 pxl pxl 163840 1月  23 13:24 build_kbl/sof_kbl.ri
-rw-rw-r-- 1 pxl pxl 163840 1月  23 13:24 build_skl/sof_skl.ri
-rw-rw-r-- 1 pxl pxl 323584 1月  23 13:24 build_sue/sof_sue.ri

The final result for FW is renamed after https://github.com/thesofproject/sof/pull/845

### PR DESCRIPTION
**Pull request by xiulipan**
restore the names for the build result binaries.
Change some scripts related things.

Fix #869

### CODE REVIEW

**Comment by xiulipan** [comment]
@lgirdwood Restore name for cmake is done.
I suppose both CI will need time to support that. Let wait @jajanusz to do that first.
And I will bring back sof-ci with the build system change together after this is merged.

**Comment by jajanusz** [comment]
@xiulipan 
Something is wrong with qemu-check on travis. Before your change it worked, so I guess that you just missed some renames in this PR (maybe related to rom-/rom_).

**Comment by xiulipan** [comment]
@jajanusz 
reorder the scripts patches. Need to update the qume after the build scripts update. miss the build folder part in qemu check patch.
Fixed and re-push the PR.

**Comment by xiulipan** [comment]
@lgirdwood 
If any failure happen, either this PR need re-work or CI need to be updated due to the name restore.
Bring sof-ci back online based on changes of this PR. sof-ci should pass this.

**Comment by jajanusz** [comment]
QB CI is ok, you can merge it when travis is ok

**Comment by xiulipan** [comment]
@lgirdwood sof-ci is ok. small issues with binary storage server deploy.
travis for my own branch is passed. https://travis-ci.org/xiulipan/sof/builds/483311800

**Pull request merged**
