### PR TITLE
[TEST] Zephyr PR Intel_adsp_ace1x: Meteorlake board upstream

### PR DESCRIPTION
**Pull request by marc-hb**
Testing https://github.com/zephyrproject-rtos/zephyr/pull/46323

### CODE REVIEW

**Comment by marc-hb** [comment]
Hardware test results will be at https://sof-ci.01.org/sofpr/PR5980/build803/devicetest. To re-run on hardware/jenkins (and NOT in any other CI, enter the magic words "SOFCI TEST" _alone_ in a new comment)

**Comment by keqiaozhang** [comment]
> @keqiaozhang could you check the network connection of `sh-adlp-rvp-sdw-02`? Maybe try a different adapter?

Done! I have replaced the USB network adapter with a new one.

**Comment by marc-hb** [comment]
Thanks but no difference unfortunately. Can you try a different cable and a different port on the switch?
```
journalctl -t kernel -g enx000ec6706fb6

Jul 07 01:08:00 sh-adlp-rvp-sdw-02 kernel: asix 3-8.1:1.0 enx000ec6706fb6: Link is Down
Jul 07 01:08:12 sh-adlp-rvp-sdw-02 kernel: asix 3-8.1:1.0 enx000ec6706fb6: Link is Down
Jul 07 01:08:14 sh-adlp-rvp-sdw-02 kernel: asix 3-8.1:1.0 enx000ec6706fb6: Link is Up - 100Mbps/Full - flow control off
Jul 07 01:08:24 sh-adlp-rvp-sdw-02 kernel: asix 3-8.1:1.0 enx000ec6706fb6: Link is Down
Jul 07 01:08:24 sh-adlp-rvp-sdw-02 kernel: asix 3-8.1:1.0 enx000ec6706fb6: Link is Down
Jul 07 01:08:36 sh-adlp-rvp-sdw-02 kernel: asix 3-8.1:1.0 enx000ec6706fb6: Link is Down
Jul 07 01:08:38 sh-adlp-rvp-sdw-02 kernel: asix 3-8.1:1.0 enx000ec6706fb6: Link is Up - 100Mbps/Full - flow control off
Jul 07 01:08:48 sh-adlp-rvp-sdw-02 kernel: asix 3-8.1:1.0 enx000ec6706fb6: Link is Down
Jul 07 01:08:48 sh-adlp-rvp-sdw-02 kernel: asix 3-8.1:1.0 enx000ec6706fb6: Link is Down
Jul 07 01:08:53 sh-adlp-rvp-sdw-02 kernel: asix 3-8.1:1.0 enx000ec6706fb6: Link is Up - 100Mbps/Full - flow control off
Jul 07 01:09:05 sh-adlp-rvp-sdw-02 kernel: asix 3-8.1:1.0 enx000ec6706fb6: Link is Down
Jul 07 01:09:05 sh-adlp-rvp-sdw-02 kernel: asix 3-8.1:1.0 enx000ec6706fb6: Link is Down
Jul 07 01:09:17 sh-adlp-rvp-sdw-02 kernel: asix 3-8.1:1.0 enx000ec6706fb6: Link is Down
Jul 07 01:09:19 sh-adlp-rvp-sdw-02 kernel: asix 3-8.1:1.0 enx000ec6706fb6: Link is Up - 100Mbps/Full - flow control off
Jul 07 01:09:29 sh-adlp-rvp-sdw-02 kernel: asix 3-8.1:1.0 enx000ec6706fb6: Link is Down
Jul 07 01:09:29 sh-adlp-rvp-sdw-02 kernel: asix 3-8.1:1.0 enx000ec6706fb6: Link is Down
Jul 07 01:09:41 sh-adlp-rvp-sdw-02 kernel: asix 3-8.1:1.0 enx000ec6706fb6: Link is Down
Jul 07 01:09:43 sh-adlp-rvp-sdw-02 kernel: asix 3-8.1:1.0 enx000ec6706fb6: Link is Up - 100Mbps/Full - flow control off
Jul 07 01:09:53 sh-adlp-rvp-sdw-02 kernel: asix 3-8.1:1.0 enx000ec6706fb6: Link is Down
Jul 07 01:09:53 sh-adlp-rvp-sdw-02 kernel: asix 3-8.1:1.0 enx000ec6706fb6: Link is Down
Jul 07 01:09:58 sh-adlp-rvp-sdw-02 kernel: asix 3-8.1:1.0 enx000ec6706fb6: Link is Up - 100Mbps/Full - flow control off
Jul 07 01:10:10 sh-adlp-rvp-sdw-02 kernel: asix 3-8.1:1.0 enx000ec6706fb6: Link is Down
Jul 07 01:10:10 sh-adlp-rvp-sdw-02 kernel: asix 3-8.1:1.0 enx000ec6706fb6: Link is Down
Jul 07 01:10:22 sh-adlp-rvp-sdw-02 kernel: asix 3-8.1:1.0 enx000ec6706fb6: Link is Down
Jul 07 01:10:24 sh-adlp-rvp-sdw-02 kernel: asix 3-8.1:1.0 enx000ec6706fb6: Link is Up - 100Mbps/Full - flow control off
Jul 07 01:10:34 sh-adlp-rvp-sdw-02 kernel: asix 3-8.1:1.0 enx000ec6706fb6: Link is Down
Jul 07 01:10:34 sh-adlp-rvp-sdw-02 kernel: asix 3-8.1:1.0 enx000ec6706fb6: Link is Down
Jul 07 01:10:46 sh-adlp-rvp-sdw-02 kernel: asix 3-8.1:1.0 enx000ec6706fb6: Link is Down
Jul 07 01:10:48 sh-adlp-rvp-sdw-02 kernel: asix 3-8.1:1.0 enx000ec6706fb6: Link is Up - 100Mbps/Full - flow control off
Jul 07 01:10:58 sh-adlp-rvp-sdw-02 kernel: asix 3-8.1:1.0 enx000ec6706fb6: Link is Down
Jul 07 01:10:58 sh-adlp-rvp-sdw-02 kernel: asix 3-8.1:1.0 enx000ec6706fb6: Link is Down
Jul 07 01:11:03 sh-adlp-rvp-sdw-02 kernel: asix 3-8.1:1.0 enx000ec6706fb6: Link is Up - 100Mbps/Full - flow control off
-- Reboot --
Jul 07 01:11:39 sh-adlp-rvp-sdw-02 kernel: asix 3-8.1:1.0 enx000ec6706fb6: renamed from eth0
Jul 07 01:11:39 sh-adlp-rvp-sdw-02 kernel: asix 3-8.1:1.0 enx000ec6706fb6: Link is Down
Jul 07 01:11:47 sh-adlp-rvp-sdw-02 kernel: IPv6: ADDRCONF(NETDEV_CHANGE): enx000ec6706fb6: link becomes ready
Jul 07 01:11:47 sh-adlp-rvp-sdw-02 kernel: asix 3-8.1:1.0 enx000ec6706fb6: Link is Up - 100Mbps/Full - flow control off
```

**Comment by keqiaozhang** [comment]
The network link error is gone after replacing the network cable and switching the USB and network port.

**Pull request closed without merging**
