### PR TITLE
dmic: cleanup the state management

### PR DESCRIPTION
**Pull request by keyonjie**
Remove the useless COMP_STATE_PAUSED state for dmic, handle pause and
stop (so as for release and start) exactly same, change the state and
dmic_active_fifos in dmic_start()/_stop().

Signed-off-by: Keyon Jie <yang.jie@linux.intel.com>

### CODE REVIEW

**Comment by ranj063** [comment]
sorry @keyonjie the paused state is not useless. It was added deliberately to fix an issue:
commit 6f54150eae4ef401a3a087861e994c8ffe6bda1d
Author: Seppo Ingalsuo <seppo.ingalsuo@linux.intel.com>
Date:   Fri Mar 5 17:36:44 2021 +0200

    Drivers: DMIC: Fix FW panic when stopping both paused FIFO streams

**Comment by keyonjie** [comment]
> sorry @keyonjie the paused state is not useless. It was added deliberately to fix an issue:
> commit [6f54150](https://github.com/thesofproject/sof/commit/6f54150eae4ef401a3a087861e994c8ffe6bda1d)
> Author: Seppo Ingalsuo [seppo.ingalsuo@linux.intel.com](mailto:seppo.ingalsuo@linux.intel.com)
> Date: Fri Mar 5 17:36:44 2021 +0200
> 
> ```
> Drivers: DMIC: Fix FW panic when stopping both paused FIFO streams
> ```

Thanks for pointing out this, let me think it more to understand why that needed.

**Comment by singalsu** [comment]
I feel the dmic_active_fifos counter should be changed to bit mask set based on dai->index (0 for FIFOA, 1 for FIFOB). Then multiple successive start, pause, stop commands for dai can't mess up the control for resources and start/stop sequence.

**Comment by keyonjie** [comment]
@singalsu @ranj063 I am not convinced why the commit 6f54150 is really needed, @ranj063 told me that address some dynamic pipeline issue, but before I can get and understand the theory there I will stick to use simpler logic for this part.

**Comment by singalsu** [comment]
@keyonjie The issue that's described in the commit is easy to replicate. If it doesn't happen, the patch for pause is not needed. I recall the power management somehow interfered stopped DAI though I never understood why exactly.

**Comment by keyonjie** [comment]
> @keyonjie The issue that's described in the commit is easy to replicate. If it doesn't happen, the patch for pause is not needed. I recall the power management somehow interfered stopped DAI though I never understood why exactly.

Thanks for information, then let me close this and revisit it when needed.

**Pull request closed without merging**
