### PR TITLE
Tools:Tune: Update drc_gen_coefs.m

### PR DESCRIPTION
**Pull request by ShriramShastry**
While converting floating point to fixed point
-  Observed underflow during the calculation of  slope_at function
Below table display underflow condition 

slope = (y2_db - y_db) / (x2_db - x_db);  % This line of code fails due to  underflow
```
+------------------+-----------------+-----+----------------+------------------+--------------------+--------------------+-------------------+
|linear_threshold  | x               | k   |x2              | x_db             |    x2_db           |  y_db              | y2_db             |
+------------------+-----------------+-----+----------------+------------------+--------------------+--------------------+-------------------+
|0.0630957344480193| 1.99526231496888| 5   |1.99725757728385| 5.99999994039536 |    6.00868153572083|  -11.5981445908546 | -11.5981404185295 |
+------------------+-----------------+-----+----------------+------------------+--------------------+--------------------+ ------------------+

```

```
function slope = slope_at(linear_threshold, x, k);

if x < linear_threshold
	slope = 1;
else
	x2 = x * 1.001;
	x_db  = mag2db(x);
	x2_db = mag2db(x2);
	y_db = mag2db(knee_curve(linear_threshold, x, k));
	y2_db = mag2db(knee_curve(linear_threshold, x2, k));

	slope = (y2_db - y_db) / (x2_db - x_db);
end

```
New proposal is under progress!

### CODE REVIEW

**Comment by lgirdwood** [comment]
@singalsu fyi

**Comment by johnylin76** [comment]
The simplified original code is as follows:

function slope = slope_at(linear_threshold, x, k);
	x2 = x * 1.001;
	x_db  = mag2db(x);
	x2_db = mag2db(x2);
	y_db = mag2db(knee_curve(linear_threshold, x, k));
	y2_db = mag2db(knee_curve(linear_threshold, x2, k));
	slope = (y2_db - y_db) / (x2_db - x_db);
end
function y = knee_curve(linear_threshold, x, k);
	y = linear_threshold + (1 - exp(-k * (x - linear_threshold))) / k;
end

"knee_curve" is the equation y = f(x) in linear domain. My first idea is to obtain slope by differentiation dy/dx = f'(x)
However, "slope_at" is to obtain in decibel domain, not in linear domain...
So it would be tougher than I think...

**Comment by singalsu** [comment]
Should this be an issue instead since there is code improvement proposed (yet), only a comment add?

**Comment by singalsu** [comment]
@ShriramShastry I don't get the problem, there's no divide by zero or anything particularly challenging float math in that equation. Can you explain?

**Comment by cujomalainey** [comment]
Yes, if there is no code, this should have been an issue rather than a PR

**Pull request closed without merging**
