### PR TITLE
1.4-stable: backport LPRO switch in WAITI

### PR DESCRIPTION
**Pull request by jajanusz**
As requested in https://github.com/thesofproject/sof/issues/2806
After it will be merged I may tag top of it as 1.4.3

### CODE REVIEW

**Comment by lgirdwood** [comment]
@jajanusz looks good, but I'm not sure which CI tests are supported in v1.4 ? @zrombel any ideas ?

**Comment by zrombel** [comment]
Some test are not applicable for this branch:

TestPtpPlaybackBitDepthConversion48000Hz32b32b4ch - Test not applicable - pcm_converter not inclued in 1.4-stable
TestChannelSelectorCapture16000Hz16b16b2chOn1ch - Test not applicable - channel selector was not enabled to work without KPB
TestMuxSimplePlayback48000Hz32b32b4ch - Test not applicable, major changes to mux/demux on master
TestDemuxSynchronizedCapture48000Hz24b32b4ch- Test not applicable, major changes to mux/demux on master
TestHdaSimpleLoopback48000hz24b32b2ch - Test not applicable - pcm_converter not inclued in 1.4-stable
**TestSdwAlhLoopback48000Hz32b32b4ch** -  Test not applicable - changes in SdW dai configuration
**TestAlhLoopbackVolume48000Hz16b16b8ch** -  Test not applicable - changes in SdW dai configuration
**TestKdDmic16000Hz24b32b2ch** - Silence was recorded. This one I would need to look closer to. I will give you feedback when I try to reproduce it.

**Comment by jajanusz** [comment]
Many of tests are not valid in CI, because it's based on very old branch.
However @mengdonglin confirmed that they tested it and it's good to merge, so I'm going to merge it so we can do more testing for release of 1.4.3.

**Comment by lgirdwood** [comment]
@jajanusz please tag and sign when all is good.

**Pull request merged**
