### PR TITLE
Fix -Werror=declaration-after-statement and add flag

### PR DESCRIPTION
**Pull request by marc-hb**
Automate current (and unwritten?) coding guidelines. Let's not waste
considerable time in code reviews discussing problems computers can
catch automatically.

Note this goes against CERT-C recommendations DCL00-C, DCL19-C and many
others but it's the current policy so let's apply and automate it. Can
be changed later.

Signed-off-by: Marc Herbert <marc.herbert@intel.com>

### CODE REVIEW

**Review by paulstelian97 — APPROVED** [review]

**Review by dbaluta — APPROVED** [review]

**Comment by cujomalainey** [comment]
Thanks for the fixes, i just have one nit, that the fixes and the flag change be two separate patches. Otherwise LGTM

**Review by cujomalainey — APPROVED** [review]
Thanks more bot info always a win :+1:

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
@marc-hb can you check CI, this should not break UT (unless it break UT build) ?

**Comment by marc-hb** [comment]
This PR does break `test/cmocka/src/audio/buffer/buffer_new.c` and others, see https://sof-ci.01.org/sof-pr-viewer/#/build/PR3995/build6248558

Downgrading to draft for now.

**Comment by sys-pt1s** [comment]
Can one of the admins verify this patch?

**Comment by marc-hb** [comment]
The Linux kernel has moved to C99 (even higher actually but not relevant here), we should do the same. Closing
https://lwn.net/Articles/885941/ `Moving the kernel to modern C`

**Pull request closed without merging**
