### PR TITLE
volume: refactor volume to support variable processing sizes

### PR DESCRIPTION
**Pull request by tlauda**
Refactors generic and HiFi3 volume processing implementations
to support variable processing sizes. The volume_copy method
will also be refactored in the near future to take advantage
of this feature.

### CODE REVIEW

**Comment by tlauda** [comment]
@singalsu Can you take a look and, after the patch is accepted, make the similar changes to fir, iir and src components? For generic implementations you can use the new buffer methods to get the right buffer fragment. For HiFi implementations you can use native circular buffer functionality, but I'm not sure if you don't already use it in some of your algorithms, so the choice of usage is up to you.

**Comment by singalsu** [comment]
@tlauda Sure, I'll enter enhancement issues for EQs and tone generator to mark the task and assign myself. SRC already supports this, though I need to add a test case for it and file a bug if it doesn't work.

**Comment by lgirdwood** [comment]
@tlauda I may do a 1.3 release in the next day or two after speaking with @michalgrodzicki and will merge after this is done.

**Comment by tlauda** [comment]
@lgirdwood Can we merge it or still waiting for 1.3?

**Comment by lgirdwood** [comment]
@tlauda Lets merge and do 1.3 when I'm back. Can you comment on CI failure

**Comment by tlauda** [comment]
@lgirdwood KW server was down. Now all checks have passed.

**Pull request merged**
