### PR TITLE
SoundWire topology update for v2.1.1

### PR DESCRIPTION
**Pull request by libinyang**
cherrypick v1.9.3-tplg2 patches

This is to fix https://github.com/thesofproject/sof-bin/issues/76 by adding SoundWire topology for some Dell devices to v2.1.1 release.

### CODE REVIEW

**Comment by libinyang** [comment]
porting patches in tag v1.9.3-tplg2 to branch v2.1

**Comment by libinyang** [comment]
There is 2 warnings in the code style check of the patches. One is a typo: configuraiton = > configuration. The other is a fake warning. Should I fix the warning or we just keep it as the original patches has the typo too?

**Comment by mengdonglin** [comment]
> There is 2 warnings in the code style check of the patches. One is a typo: configuraiton = > configuration. The other is a fake warning. Should I fix the warning or we just keep it as the original patches has the typo too?

Can you help submit a PR to main branch to fix the typo?  And then cherry pick the typo fix to v2.1.1 as well?

**Comment by lgirdwood** [comment]
> > There is 2 warnings in the code style check of the patches. One is a typo: configuraiton = > configuration. The other is a fake warning. Should I fix the warning or we just keep it as the original patches has the typo too?
> 
> @libinyang Can you help submit a PR to main branch to fix the typo? And then cherry pick the typo fix to v2.1.1 as well?

Ok, we can merge to v2.1.1 after typo fix is added to this PR.

**Comment by libinyang** [comment]
patch is submitted: https://github.com/thesofproject/sof/pull/5874

**Comment by marc-hb** [comment]
> And then cherry pick the typo fix to v2.1.1 as well?

checkpatch runs on each patch individually, so this will not turn checkpatch green.

Fixing checkpatch warnings at cherry-picking time is too late.

**Comment by libinyang** [comment]
patches updated. Typo fixed.

**Review by lgirdwood — APPROVED** [review]

**Comment by libinyang** [comment]
ping

**Review by bardliao — APPROVED** [review]

**Review by plbossart — APPROVED** [review]

**Comment by keqiaozhang** [comment]
SOFCI TEST

**Comment by keqiaozhang** [comment]
@lgirdwood  and @libinyang 
The alarm has been cleared. Confirmed that this is a hardware issue and has nothing to do with this PR.
It seems that some registers were wrong and cannot be cleared by reboot. 
I tried to AC the device and power on the device after a few minutes, then the issue disappears.

I triggered another round of test on TGLH_SKU0A5E_SDW and got 'ALL PASS'.
http://sof-ci.sh.intel.com/#/result/planresultdetail/13168

This PR has passed the validation on all our SDW devices.

**Pull request merged**
