### PR TITLE
Dw dma cosmetic

### PR DESCRIPTION
**Pull request by lyakh**
By mistake PR 826 was closed, this is the same code, rebased on the current master.

### CODE REVIEW

**Comment by lyakh** [comment]
is this the reason for the KW failure?
19:24:48,046 INFO  - ERROR: Failed to synchronize project https://klocwork-igk4.devtools.intel.com:8090/SOF_FW - Database error occurred: No operations allowed after connection closed.Connection was implicitly closed due to underlying exception/error:
19:24:48,046 INFO  - 
19:24:48,046 INFO  - 
19:24:48,046 INFO  - ** BEGIN NESTED EXCEPTION ** 
19:24:48,046 INFO  - 
19:24:48,046 INFO  - com.mysql.jdbc.exceptions.jdbc4.CommunicationsException
19:24:48,046 INFO  - MESSAGE: Communications link failure

**Comment by lyakh** [comment]
@lgirdwood sorry, not sure what that KW error is...

**Comment by lgirdwood** [comment]
@zrombel can you restart CI for this one too. Thanks !

**Comment by lgirdwood** [comment]
@lyakh please force push again to restart CI, the build CI should be fixed now.

**Comment by lyakh** [comment]
The KW error is correct, but it isn't introduced by this patch series. It triggered because one of the patches in the series moved the dw-dma.c file to a new location, so, the entire file was checked as "added code." And in fact I have a patch, fixing that issue in my tree, but it is on top of this series, it applies to dma.c at its new location, so, once we merge this series I will push those fixes.

**Comment by lyakh** [comment]
Here's my patch for that issue:
https://github.com/thesofproject/sof/commit/c3f043f8377007522f3a285906fe09cdfaf4455e

**Comment by lgirdwood** [comment]
SOFCI TEST

**Pull request merged**
