### PR TITLE
ext_man: prevent removal of cavs-specific element

### PR DESCRIPTION
**Pull request by abonislawski**
This patch will allow to keep cavs-specific elements

### CODE REVIEW

**Comment by fredoh9** [comment]
I can see ext_man_cavs_config in .fw_metadata now.

```
 .fw_metadata   0x220001a0       0x28 src/platform/intel/cavs/libcavs_ext_manifest.a(ext_manifest.c.o)
                0x220001a0                ext_man_cavs_config
```

**Review by ktrzcinx — APPROVED** [review]

**Comment by fredoh9** [comment]
***DON'T MERGE this PR yet***

I have a question on .fw_ready section as well.
I used to see ext_man_config in fw_ready as well. I only see up to user_abi_version.
```
.fw_ready       0xbe05e518      0x284
 *(.fw_ready)
 .fw_ready      0xbe05e518       0x6c CMakeFiles/sof.dir/src/platform/intel/cavs/platform.c.o
 *(.fw_ready_metadata)
 .fw_ready_metadata
                0xbe05e584      0x190 CMakeFiles/sof.dir/src/platform/intel/cavs/platform.c.o
 .fw_ready_metadata
                0xbe05e714       0x5c src/ipc/libdata_structs.a(cc_version.c.o)
                0xbe05e714                cc_version
 .fw_ready_metadata
                0xbe05e770       0x1c src/ipc/libdata_structs.a(probe_support.c.o)
                0xbe05e770                probe_support
 .fw_ready_metadata
                0xbe05e78c       0x10 src/ipc/libdata_structs.a(user_abi_version.c.o)
                0xbe05e78c                user_abi_version
```

And 2nd question, getting extended metadata from linux driver is broken. It read wrong MAGIC NUMBER and return failure. After inspection of the data, it has totally corrupted data.

```
/* In ASCII `XMan` */
#define SOF_EXT_MAN_MAGIC_NUMBER	0x6e614d58
```

Kernel debugging log,
```
[    2.727552] sof-audio-pci 0000:00:1f.3: request_firmware intel/sof/community/sof-cml.ri successful
[    2.727554] Error: MAGIC NUMBER is wrong, 0x44504324
[    2.727559] sof-audio-pci 0000:00:1f.3: magic=0x44504324 full_size=3 header_size=3507486977 header_version=50534441
[    2.727562] sof-audio-pci 0000:00:1f.3: remaining=787480322 ext_man_size=0
[    2.727564] sof-audio-pci 0000:00:1f.3: firmware doesn't contain extended manifest
[    2.727567] sof-audio-pci 0000:00:1f.3: sof_probe_continue: call snd_sof_run_firmware

```

**Comment by ktrzcinx** [comment]
@fredoh9 
1. >Can we include ext_man_config and ext_man_cavs_config in fw_ready section
Why? Data from fw_ready/fw_ready_metadata has been ported to ext_manifest to make it fully functional. Adding compile-time known elements to fw_ready_metadata is deprecated (leads to unnecessary FW binary growth). Some exception may be, when something is not known at compilation time, eg. some HW specific staff, then fw_ready_metadata may be right place for such a thing.

2.  >Error: MAGIC NUMBER is wrong, 0x44504324

This number it's `$CPD` in ascii, did you cherry-pick this patch: https://github.com/thesofproject/sof/pull/2957 before FW compilation?

**Review by ktrzcinx — APPROVED** [review]

**Review by lgirdwood — COMMENTED** [review]
@abonislawski Not following the commit message. This looks like we are adding config to a linker section (which one) for parsing by the kernel at FW load ?
@kv2019i @fredoh9 are all the kernel pieces in place ?

**Comment by abonislawski** [comment]
@lgirdwood we are adding EXTERN info, to inform linker that this variable is used and prevent from deleting unused variables because in fact ext manifest structs are not used anywhere and linker will not include them.
Currently this works with the same way (EXTERN(ext_man_fw_ver)) and Im adding another extern because introduced cavs part of ext manifest is compiled into another lib

**Comment by lgirdwood** [comment]
@abonislawski sorry, I was asking why we are adding this data (who will use it). My understanding is that @kv2019i would like to integrate the kernel parts of the extended manifest after v1.6 (so this may pend on a kernel patch too) ?

**Comment by abonislawski** [comment]
@lgirdwood this PR is more like fix for this PR #2893 to work properly, we can merge this anytime we want because ext_manifest is not included without PR #2957 (this one is waiting for a proper time)

**Comment by fredoh9** [comment]
I wasn't clear about FW_READY metadata vs extended manifest. Ever since i saw `firmware doesn't contain extended manifest`, I was referring FW_READY metadata also part of ext manifest.

Without PR #2957, if ext manifest not included, https://github.com/thesofproject/linux/issues/2434 is not v1.6 release blocker. I agree, it won't break any kernel driver. I will remove "DON'T merge this PR yet" comment.

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
@abonislawski ok, whats the plan for #2957 ? @kv2019i is now good or extended manifest ?

**Pull request merged**
