### PR TITLE
[Stable v1.7] Backport some fixes for v1.7 final release

### PR DESCRIPTION
**Pull request by iuliana-prodan**
Cherry-pick some fixes from DAI and IMX for v1.7 final release.

Original pull request was #3867
Fixes: #3809

### CODE REVIEW

**Review by paulstelian97 — APPROVED** [review]
I assume Intel was OK with the ordering change in the original PR so approving based on that.

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
@paulstelian97 @iuliana-prodan please confirm all patches are in master ?

**Comment by paulstelian97** [comment]
> @paulstelian97 @iuliana-prodan please confirm all patches are in master ?

It's exactly the 4 commits from #3867.

**Comment by iuliana-prodan** [comment]
> > @paulstelian97 @iuliana-prodan please confirm all patches are in master ?
> 
> It's exactly the 4 commits from #3867.

Yes, are the exact patches from master.

**Comment by lgirdwood** [comment]
CI showing docker build timeout and known issue on BYT

**Comment by marc-hb** [comment]
> It's exactly the 4 commits from #3867.

Next time use the `-x` option: `git cherry-pick -x [ --stdin ]`

More backporting tips learned from backporting tens of thousands of commits: https://chromium.googlesource.com/chromiumos/docs/+/master/kernel_development.md#How-do-I-backport-an-upstream-patch
Some tips are ChromeOS-specific (ignore them), others are not.

**Comment by iuliana-prodan** [comment]
> Next time use the `-x` option: `git cherry-pick -x [ --stdin ]`. Example in #3925
> 
> More backporting tips learned from backporting tens of thousands of commits: https://chromium.googlesource.com/chromiumos/docs/+/master/kernel_development.md#How-do-I-backport-an-upstream-patch
> Some tips are ChromeOS-specific (ignore them), others are not.

@marc-hb Thanks! I'll use -x option next time.

**Pull request merged**
