### PR TITLE
Revert "dai: dai_config refinement" to fix multiple pipelines case

### LINKED ISSUE #4069: [BUG][APL] multiple-pipeline failed on APL_UP2_NOCODEC , buffer_alloc error after initiating the 9th pipeline
**Describe the bug**
multiple-pipeline test failed on APL_UP2_NOCODEC , show "Unable to install hw params"when doing arecord on DMIC.

**To Reproduce** [revised ]
ssh ubuntu@jf-apl-up2-nocodec-1.jf.intel.com
TPLG=/lib/firmware/intel/sof-tplg/sof-apl-nocodec.tplg ~/sof-test/test-case/multiple-pipeline.sh -f p -c 20
(also run  'arecord   -D hw:0,6 -c 2 -r 48000 -f S32_LE /dev/null -q' and  'arecord   -D hw:0,5 -c 2 -r 48000 -f S32_LE /dev/null -q' remotely,which may cause connection termination)

**Test log**
image

**Kernel log**
    
image

**Sof-logger**
ubuntu@sh-apl-up2-nocodec-04:~/xywu$ sudo sof-logger -l sof-apl.ldc
         TIMESTAMP              DELTA C# COMPONENT          LOCATION                      CONTENT
[663583167.760417] (        0.000000) c0 dma-trace             src/trace/dma-trace.c:331  ERROR FW ABI 0x3012001 DBG ABI 0x5003000 tag v1.7-rc1-260-g6c2cdffd0239-dirty src hash 0xa0d5ec17 (ldc hash 0xa0d5ec17)
[   246451.666667] (   246451.671875) c0 buffer                   src/audio/buffer.c:44   ERROR buffer_alloc(): could not alloc structure
[   246458.072917] (        6.406250) c0 host         13.52         src/audio/host.c:738  ERROR host_params(): failed to alloc dma buffer
[   246463.645833] (        5.572917) c0 pipe         13.55 ....../pipeline-params.c:235  ERROR pipeline_params(): ret = -12, host->comp.id = 52
[   246469.687500] (        6.041667) c0 ipc                  src/ipc/handler-ipc3.c:284  ERROR ipc: pipe 13 comp 52 params failed -12
[  5783372.500000] (  5536903.000000) c0 wait                         src/lib/wait.c:46   ERROR ewt
[  5786158.333333] (     2785.833252) c0 wait                         src/lib/wait.c:46   ERROR ewt
[  5788008.489583] (     1850.156250) c0 wait                         src/lib/wait.c:46   ERROR ewt
[  5789436.614583] (     1428.125000) c0 wait                         src/lib/wait.c:46   ERROR ewt

**Reproduction Rate**
100%

**Environment**
    * Kernel:3043605a
    * SOF: dc0ab8a449d6
    * Topology: sof-apl-nocodec.tplg
    * Platform: APL_UP2_NOCODEC

### PR DESCRIPTION
**Pull request by marc-hb**
This reverts commit 6c2cdffd0239 ("dai: dai_config refinement") because
it broke the following test (and maybe others):
```
TPLG=sof-apl-nocodec.tplg \
      ~/sof-test/test-case/multiple-pipeline.sh -f c -c 10 -s
```
Local reproduction is 100% before the revert and 0% after the revert.
The kernel version does not seem to matter.

Note the -c(ount) needs to be high enough to reproduce, 9 seems to be
the minimum.

Fixes #4069, thanks Xiaoyun Wu for the quick bisect!

Signed-off-by: Marc Herbert <marc.herbert@intel.com>

### CODE REVIEW

**Review by plbossart — APPROVED** [review]
unless there is an alternate fix within the next 2 business days, I vote for a revert.

This is not a technical judgement on the merits of this change, just that when CI is broken we go back to a stable state.

**Comment by aiChaoSONG** [comment]
@marc-hb Please fix the commit message, it should be `0% after the revert`, rather than `0% before the revert`

**Comment by aiChaoSONG** [comment]
SOFCI TEST

**Comment by aiChaoSONG** [comment]
SOFCI TEST

**Comment by keyonjie** [comment]
the SRAM Heap buffer is used up when running 9/10 pipelines simultaneously, it happens with my change only as I allocate a dai_config struct for each dai/pipeline where it uses about 200 Bytes each.

I will try to add a decent fix soon.

**Comment by lgirdwood** [comment]
@keyonjie thanks, can you link your fix PR here.

**Comment by keyonjie** [comment]
> @keyonjie thanks, can you link your fix PR here.

Sure, here it is: https://github.com/thesofproject/sof/pull/4074

**Comment by lgirdwood** [comment]
@keyonjie @marc-hb @aiChaoSONG still need this ? Can we close ?

**Comment by keyonjie** [comment]
> @keyonjie @marc-hb @aiChaoSONG still need this ? Can we close ?

I think we can close this now.

**Comment by marc-hb** [comment]
I tested commit 966e37bc7568 "increase runtime heap" and confirm this test passes again.

**Pull request closed without merging**
