### PR TITLE
[DNM] Zephyr Dec 12th update + one in-progress fix for SOF builds

### PR DESCRIPTION
**Pull request by kv2019i**

### CODE REVIEW

**Comment by kv2019i** [comment]
Delta between Zephyr main and what we use in SOF is growing again with multiple regressions (and fixes) in Zephyr main. Let's do an intermediate check with SOF CI to see whether any other issues are lurking...

**Comment by wszypelt** [comment]
@kv2019i Unfortunately, it's PR's fault, it causes a timeout while creating the pipeline, on all our test machines, the same two tests are crashing

**Comment by kv2019i** [comment]
> @kv2019i Unfortunately, it's PR's fault, it causes a timeout while creating the pipeline, on all our test machines, the same two tests are crashing

Thank you for the check. Now suspicoun is p4wq, potential fix candidate at https://github.com/zephyrproject-rtos/zephyr/pull/82551

**Comment by kv2019i** [comment]
Replaced with https://github.com/thesofproject/sof/pull/9712

**Pull request closed without merging**
