### PR TITLE
Make sure we have enough room in the output local buffer

### PR DESCRIPTION
**Pull request by dbaluta**

### CODE REVIEW

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
@dbaluta some build errors
```
[100%] Linking C executable sof
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/sof.dir/link.txt --verbose=1
/localdisk/tools/xtensa/RG-2017.8-linux/XtensaTools/bin/xt-xcc    CMakeFiles/sof.dir/src/platform/cannonlake/lib/clk.c.o CMakeFiles/sof.dir/src/platform/intel/cavs/lib/clk.c.o CMakeFiles/sof.dir/src/platform/intel/cavs/lib/dai.c.o CMakeFiles/sof.dir/src/platform/intel/cavs/lib/dma.c.o CMakeFiles/sof.dir/src/platform/intel/cavs/lib/memory.c.o CMakeFiles/sof.dir/src/platform/intel/cavs/lib/pm_runtime.c.o CMakeFiles/sof.dir/src/platform/intel/cavs/lib/pm_memory.c.o CMakeFiles/sof.dir/src/platform/intel/cavs/lib/mem_window.c.o CMakeFiles/sof.dir/src/platform/intel/cavs/platform.c.o CMakeFiles/sof.dir/src/arch/xtensa/drivers/interrupt.c.o CMakeFiles/sof.dir/src/arch/xtensa/drivers/timer.c.o CMakeFiles/sof.dir/src/arch/xtensa/lib/notifier.c.o CMakeFiles/sof.dir/src/arch/xtensa/lib/cpu.c.o CMakeFiles/sof.dir/src/arch/xtensa/schedule/schedule.c.o CMakeFiles/sof.dir/src/arch/xtensa/schedule/task.c.o CMakeFiles/sof.dir/src/arch/xtensa/xtos/crt1-boards.S.o CMakeFiles/sof.dir/src/arch/xtensa/xtos/_vectors.S.o CMakeFiles/sof.dir/src/arch/xtensa/init.c.o CMakeFiles/sof.dir/src/arch/xtensa/exc-dump.S.o CMakeFiles/sof.dir/src/arch/xtensa/main-entry.S.o CMakeFiles/sof.dir/src/ipc/handler-ipc3.c.o CMakeFiles/sof.dir/src/ipc/helper-ipc3.c.o CMakeFiles/sof.dir/src/ipc/ipc-common.c.o CMakeFiles/sof.dir/src/ipc/dma-copy.c.o CMakeFiles/sof.dir/src/audio/host.c.o CMakeFiles/sof.dir/src/audio/component.c.o CMakeFiles/sof.dir/src/audio/buffer.c.o CMakeFiles/sof.dir/src/audio/channel_map.c.o CMakeFiles/sof.dir/src/audio/volume/volume_generic.c.o CMakeFiles/sof.dir/src/audio/volume/volume_hifi3.c.o CMakeFiles/sof.dir/src/audio/volume/volume.c.o CMakeFiles/sof.dir/src/audio/src/src_generic.c.o CMakeFiles/sof.dir/src/audio/src/src_hifi2ep.c.o CMakeFiles/sof.dir/src/audio/src/src_hifi3.c.o CMakeFiles/sof.dir/src/audio/src/src.c.o CMakeFiles/sof.dir/src/audio/eq_fir/eq_fir.c.o CMakeFiles/sof.dir/src/audio/eq_fir/eq_fir_generic.c.o CMakeFiles/sof.dir/src/audio/eq_fir/eq_fir_hifi2ep.c.o CMakeFiles/sof.dir/src/audio/eq_fir/eq_fir_hifi3.c.o CMakeFiles/sof.dir/src/audio/eq_iir/eq_iir.c.o CMakeFiles/sof.dir/src/audio/eq_iir/iir.c.o CMakeFiles/sof.dir/src/audio/dcblock/dcblock.c.o CMakeFiles/sof.dir/src/audio/dcblock/dcblock_generic.c.o CMakeFiles/sof.dir/src/audio/tdfb/tdfb.c.o CMakeFiles/sof.dir/src/audio/tdfb/tdfb_generic.c.o CMakeFiles/sof.dir/src/audio/tdfb/tdfb_hifiep.c.o CMakeFiles/sof.dir/src/audio/tdfb/tdfb_hifi3.c.o CMakeFiles/sof.dir/src/audio/tone.c.o CMakeFiles/sof.dir/src/audio/mixer.c.o CMakeFiles/sof.dir/src/audio/mux/mux.c.o CMakeFiles/sof.dir/src/audio/mux/mux_generic.c.o CMakeFiles/sof.dir/src/audio/switch.c.o CMakeFiles/sof.dir/src/audio/dai.c.o CMakeFiles/sof.dir/src/audio/kpb.c.o CMakeFiles/sof.dir/src/audio/selector/selector_generic.c.o CMakeFiles/sof.dir/src/audio/selector/selector.c.o CMakeFiles/sof.dir/src/audio/pcm_converter/pcm_converter.c.o CMakeFiles/sof.dir/src/audio/pcm_converter/pcm_converter_generic.c.o CMakeFiles/sof.dir/src/audio/pcm_converter/pcm_converter_hifi3.c.o CMakeFiles/sof.dir/src/audio/asrc/asrc.c.o CMakeFiles/sof.dir/src/audio/asrc/asrc_farrow.c.o CMakeFiles/sof.dir/src/audio/asrc/asrc_farrow_generic.c.o CMakeFiles/sof.dir/src/audio/asrc/asrc_farrow_hifi3.c.o CMakeFiles/sof.dir/src/audio/codec_adapter/codec_adapter.c.o CMakeFiles/sof.dir/src/audio/codec_adapter/codec/generic.c.o CMakeFiles/sof.dir/src/audio/codec_adapter/codec/cadence.c.o CMakeFiles/sof.dir/src/audio/pipeline/pipeline-graph.c.o CMakeFiles/sof.dir/src/audio/pipeline/pipeline-stream.c.o CMakeFiles/sof.dir/src/audio/pipeline/pipeline-params.c.o CMakeFiles/sof.dir/src/audio/pipeline/pipeline-xrun.c.o CMakeFiles/sof.dir/src/audio/pipeline/pipeline-schedule.c.o CMakeFiles/sof.dir/src/lib/agent.c.o CMakeFiles/sof.dir/src/lib/lib.c.o CMakeFiles/sof.dir/src/lib/alloc.c.o CMakeFiles/sof.dir/src/lib/notifier.c.o CMakeFiles/sof.dir/src/lib/pm_runtime.c.o CMakeFiles/sof.dir/src/lib/clk.c.o CMakeFiles/sof.dir/src/lib/dma.c.o CMakeFiles/sof.dir/src/lib/dai.c.o CMakeFiles/sof.dir/src/lib/wait.c.o CMakeFiles/sof.dir/src/math/numbers.c.o CMakeFiles/sof.dir/src/math/trig.c.o CMakeFiles/sof.dir/src/math/decibels.c.o CMakeFiles/sof.dir/src/math/iir_df2t_generic.c.o CMakeFiles/sof.dir/src/math/iir_df2t_hifi3.c.o CMakeFiles/sof.dir/src/math/fir_generic.c.o CMakeFiles/sof.dir/src/math/fir_hifi2ep.c.o CMakeFiles/sof.dir/src/math/fir_hifi3.c.o CMakeFiles/sof.dir/src/samples/audio/smart_amp_test.c.o CMakeFiles/sof.dir/src/samples/audio/detect_test.c.o CMakeFiles/sof.dir/src/spinlock.c.o CMakeFiles/sof.dir/src/drivers/intel/cavs/interrupt.c.o CMakeFiles/sof.dir/src/drivers/intel/cavs/timer.c.o CMakeFiles/sof.dir/src/drivers/intel/cavs/timestamp.c.o CMakeFiles/sof.dir/src/drivers/intel/cavs/ipc.c.o CMakeFiles/sof.dir/src/drivers/intel/cavs/idc.c.o CMakeFiles/sof.dir/src/drivers/intel/hda/hda-dma.c.o CMakeFiles/sof.dir/src/drivers/intel/hda/hda.c.o CMakeFiles/sof.dir/src/drivers/intel/ssp/ssp.c.o CMakeFiles/sof.dir/src/drivers/intel/ssp/mn.c.o CMakeFiles/sof.dir/src/drivers/intel/alh.c.o CMakeFiles/sof.dir/src/drivers/intel/dmic.c.o CMakeFiles/sof.dir/src/drivers/dw/dma.c.o CMakeFiles/sof.dir/src/drivers/interrupt.c.o CMakeFiles/sof.dir/src/trace/dma-trace.c.o CMakeFiles/sof.dir/src/trace/trace.c.o CMakeFiles/sof.dir/src/debug/panic.c.o CMakeFiles/sof.dir/src/init/init.c.o CMakeFiles/sof.dir/src/schedule/dma_single_chan_domain.c.o CMakeFiles/sof.dir/src/schedule/edf_schedule.c.o CMakeFiles/sof.dir/src/schedule/ll_schedule.c.o CMakeFiles/sof.dir/src/schedule/schedule.c.o CMakeFiles/sof.dir/src/schedule/task.c.o CMakeFiles/sof.dir/src/schedule/timer_domain.c.o CMakeFiles/sof.dir/src/idc/idc.c.o  -o sof -Wl,-Map=sof.map -T/quickbuild/workspace1/24733/SOF_FW/build_fw/cannonlake.x src/platform/intel/cavs/lib/libpdown.a src/platform/intel/cavs/libcavs_ext_manifest.a src/arch/xtensa/xtos/libxtos.a src/arch/xtensa/hal/libhal.a src/arch/xtensa/xtos/libxlevel2.a src/arch/xtensa/xtos/libxlevel5.a src/init/libext_manifest.a -nostdlib -lgcc -Wl,--no-check-sections -ucall_user_start -Wl,-static 
CMakeFiles/sof.dir/src/audio/codec_adapter/codec/cadence.c.o:(.data+0x2c): undefined reference to `cadence_api_function'
CMakeFiles/sof.dir/build.make:1769: recipe for target 'sof' failed
```

**Review by cujomalainey — APPROVED** [review]

**Review by paulstelian97 — APPROVED** [review]
Looks good, didn't check tests though so do take a look if they're fine.

**Comment by dbaluta** [comment]
Minor update: removed 'min' from newly introduce interface function name:  `cadence_codec_get_min_samples -> cadence_codec_get_samples`.

**Comment by dbaluta** [comment]
@lgirdwood build issue is very strange. It means that .config has CONFIG_CADENCE_CODEC_WRAPPER activated which shouldn't happen as DAP library is not available to public release. 

I started a new CI to see what happens now.

@mrajwa

**Comment by dbaluta** [comment]
Looks like build is OK https://sof-ci.01.org/sofpr/PR4033/build8694/build/.

Not sure about `Internal Intel CI System/merge/build`

**Review by iuliana-prodan — APPROVED** [review]

**Comment by lgirdwood** [comment]
@dbaluta thanks for the update, Internal CI is down this mroning and should be up in the evening. We can rerun and merge later today.

**Comment by dbaluta** [comment]
@lgirdwood sure. thanks!

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by dbaluta** [comment]
@zrombel this still fails with

```
CMakeFiles/sof.dir/src/audio/codec_adapter/codec/cadence.c.o:(.data+0x2c): undefined reference to `cadence_api_function'
```
This means that you internally have a config which defines CONFIG_CADENCE_CODEC_WRAPPER but there is no library providing the 'cadence_api_function' symbol.

Can you please have a look.

Cc: @mrajwa @lgirdwood

**Comment by lgirdwood** [comment]
@zrombel can you report on this, I'm not seeing any def_configs with this set ? I'm assuming internal CI has another set of def_configs for building teh codec_adapter ?

**Comment by dbaluta** [comment]
SOFCI TEST

**Comment by lgirdwood** [comment]
@zrombel any comment here ? XCC is building on Jenkins but failing here and it looks like a different kconfig is being used ?

**Comment by zrombel** [comment]
Hi, sorry for late update. 
This is the problem with code patch that we are using for testing FW with codec library. This PR changes files cadence.c and cadence.h which patch refers to and does not longer apply correctly. Patch have to be updated for this PR. I will try to test it manually ale give feedback. 

There was a conversation about this patch but problem was not solved.

**Comment by dbaluta** [comment]
@zrombel so it is about your internal testing patch right? This commits still applies correctly on the top of main branch?

**Comment by zrombel** [comment]
Yes, this PR applies correctly. It is internal patach that fails to apply.

**Comment by dbaluta** [comment]
@zrombel do you think you would be able to get a chance to look at this by the end of next week? We plan to have v1.8-rc1 at the beginning of May. 
They will be some more patches to codec_adapter and we want to make sure everything works by then.

**Comment by lgirdwood** [comment]
@kkarask @wszypelt fyi - any update ?

**Comment by zrombel** [comment]
I'm already on it. I will have results soon.

**Comment by zrombel** [comment]
I've just finished manual testing and everything is ok, all tests are PASS. 
This PR is good to merge, however if you willing to merge it today I will have to turn off codec tests for the weekend since patch update needs to be done on QB, and I don't suppose that QB support team will make it today.

**Comment by lgirdwood** [comment]
@dbaluta ok to merge on Monday ? This is good for me.

**Comment by zrombel** [comment]
Monday will be the best time to do it. Lets synchronize then merge and QB update on Monday :)

**Comment by dbaluta** [comment]
@zrombel @zrombel Monday is fine! Thanks!

**Comment by zrombel** [comment]
@lgirdwood, @dbaluta: I have the pach ready, so you can merge this PR and CI will be updated.

**Comment by dbaluta** [comment]
@zrombel  thanks! @lgirdwood can you go on with the merge? On my side the 'Merge' button is grayed out :)

**Comment by lgirdwood** [comment]
> @zrombel thanks! @lgirdwood can you go on with the merge? On my side the 'Merge' button is grayed out :)

Will do - it's grey as a required CI says "fail" .

@zrombel @dbaluta now merged.

**Pull request merged**
