### PR TITLE
src: make coefficients constant

### PR DESCRIPTION
**Pull request by lyakh**
Make coefficients and their tables constant.

### CODE REVIEW

**Review by singalsu — APPROVED** [review]
Reminder to myself, update the generator script to produce header files with this change.

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
@singalsu btw, all the SRC coefficients are loaded into uncache memory IIUC i.e. from binutils nm
```
400a9ca8 D src_in_fs
400a9cc4 D src_int16_0_0_0_0
400a9cec D src_int16_1_1_0_0
400a9f1c D src_int16_1_2_1814_5000
400a9ef4 D src_int16_1_3_1814_5000
400a9ecc D src_int16_1_6_1814_5000
400a9d8c D src_int16_20_21_1667_5000
400a9ea4 D src_int16_2_1_1814_5000
400a9d64 D src_int16_21_20_1667_5000
400a9e7c D src_int16_2_3_1814_5000
400a9d3c D src_int16_24_25_1814_5000
400a9d14 D src_int16_25_24_1814_5000
400a9e54 D src_int16_3_1_1814_5000
400a9e2c D src_int16_3_2_1814_5000
400a9e04 D src_int16_6_1_1814_5000
400a9ddc D src_int16_7_8_1814_5000
400a9db4 D src_int16_8_7_1814_5000
400aa098 D src_lite_tr
400a9c8c D src_out_fs
400a9bc8 D src_table1
400a9b04 D src_table2
400aa090 D src_tr
```
This means we need to ucache_to_cache then when we set up the pointers for coeffs.

**Comment by lyakh** [comment]
> @singalsu btw, all the SRC coefficients are loaded into uncache memory IIUC i.e. from binutils nm
> 
> ```
> 400a9ca8 D src_in_fs
> 400a9cc4 D src_int16_0_0_0_0
> 400a9cec D src_int16_1_1_0_0
> 400a9f1c D src_int16_1_2_1814_5000
> 400a9ef4 D src_int16_1_3_1814_5000
> 400a9ecc D src_int16_1_6_1814_5000
> 400a9d8c D src_int16_20_21_1667_5000
> 400a9ea4 D src_int16_2_1_1814_5000
> 400a9d64 D src_int16_21_20_1667_5000
> 400a9e7c D src_int16_2_3_1814_5000
> 400a9d3c D src_int16_24_25_1814_5000
> 400a9d14 D src_int16_25_24_1814_5000
> 400a9e54 D src_int16_3_1_1814_5000
> 400a9e2c D src_int16_3_2_1814_5000
> 400a9e04 D src_int16_6_1_1814_5000
> 400a9ddc D src_int16_7_8_1814_5000
> 400a9db4 D src_int16_8_7_1814_5000
> 400aa098 D src_lite_tr
> 400a9c8c D src_out_fs
> 400a9bc8 D src_table1
> 400a9b04 D src_table2
> 400aa090 D src_tr
> ```
> 
> This means we need to ucache_to_cache then when we set up the pointers for coeffs.

@lgirdwood this is before this commit, right? After it I see these in `.rodata` with cached aliases

**Comment by singalsu** [comment]
@lgirdwood @lyakh Wait, do you mean that const C arrays are potentially corrupt if accessed without those address conversions?

**Comment by singalsu** [comment]
Also, fast coefficients access is key for good performance. If memory where these are located is slow, the tables that the active x to y kHz rate conversion uses should be copied to a memory where the SIMD MAC instructions work efficiently.

**Comment by lyakh** [comment]
> @lgirdwood @lyakh Wait, do you mean that const C arrays are potentially corrupt if accessed without those address conversions?

so weird, I thought I'd replied, sorry. No, it isn't about corruption. And I don't think any conversion is needed. After this commit I see all those arrays accessed via cached aliases, but maybe I'm missing some build configuration @lgirdwood ?

BTW, there's one more thing to check - explicit type conversions like https://github.com/thesofproject/sof/blob/45dc968cb26663a5debb51e65efbfee99b31089a/src/audio/src/src_hifi2ep.c#L59 - that's already a bug. That one explicitly removes the `const` qualifier from exactly those coefficients IIUC, so it can then in principle be used to corrupt them, yes. I assume we have a few of such conversions in the sources...

**Comment by lyakh** [comment]
Replying to myself: I found `-Wcast-qual` - @singalsu please try building the sources with it, and maybe @marc-hb we should add it to SOF in general

**Comment by lgirdwood** [comment]
> > This means we need to ucache_to_cache then when we set up the pointers for coeffs.
> 
> @lgirdwood this is before this commit, right? After it I see these in `.rodata` with cached aliases

ok, great good to know RO is properly mapped here.

**Comment by singalsu** [comment]
> Replying to myself: I found `-Wcast-qual` - @singalsu please try building the sources with it, and maybe @marc-hb we should add it to SOF in general

I tried but I have no idea how to fix container_of() macro.

**Comment by lyakh** [comment]
> > Replying to myself: I found `-Wcast-qual` - @singalsu please try building the sources with it, and maybe @marc-hb we should add it to SOF in general
> 
> I tried but I have no idea how to fix container_of() macro.

@singalsu we could add a
```
#define const_container_of(ptr, type, member) \
	({const typeof(((type *)0)->member)*__memberptr = (ptr); \
	(const type *)((const char *)__memberptr - offsetof(type, member)); })
```
and use it for `const` pointers instead of the usual `container_of()`

**Comment by singalsu** [comment]
Thanks @lyakh I'll try it if I can proceed with it!

**Pull request merged**
