### PR TITLE
drivers: dw: Poll with timeout after disabling channel

### PR DESCRIPTION
**Pull request by ranj063**
It is recommended to poll with timeout after disabling the channel to ensure that the channel has been actually disabled.

### CODE REVIEW

**Review by abonislawski — APPROVED** [review]
For xtos platforms it should go somewhere to legacy branch too? @kv2019i @lgirdwood 
This is very good patch actually

**Comment by kv2019i** [comment]
Matching change on Zephyr side https://github.com/zephyrproject-rtos/zephyr/pull/55891

**Comment by lgirdwood** [comment]
CI is down, lets retest on Monday.
@mwasko fyi - this will need to land in cavs-2.5 branch too.

**Comment by keqiaozhang** [comment]
SOFCI TEST

**Comment by kv2019i** [comment]
The PR CI checks don't mean much as this configuration is no longer covered by the CI checks (we don't even build the XTOS configuration for Intel platforms). So just have to trust the reviews and code author to have tested the patch. https://sof-ci.01.org/sofpr/PR7297/build4859/devicetest/index.html fails, but not related to this PR. Proceeding with merge.

**Pull request merged**
