### PR TITLE
cherry-pick #6612 from main to rpl-001-drop-stable

### PR DESCRIPTION
**Pull request by johnylin76**
cherry-pick #6612 from main to rpl-001-drop-stable

### CODE REVIEW

**Review by lgirdwood — APPROVED** [review]
@mwasko fyi code and topology backports.

**Review by abonislawski — APPROVED** [review]

**Comment by johnylin76** [comment]
rebased and fixed conflicts

**Comment by johnylin76** [comment]
testbench is failed on heap memory leakage but I don't think it's relevant to this change.

**Comment by marc-hb** [comment]
I think you mean https://github.com/thesofproject/sof/actions/runs/3538859073/jobs/5940117891 

@singalsu this looks worrying...

```
(ipc-common.c:239) ipc_init()
(ll_schedule.c:310) ll_scheduler_init()
(edf_schedule.c:115) edf_scheduler_init()
(helper.c:149) get_drv(), found driver type 1, uuid (nil)U
(helper.c:309) comp new (nil)U type 1 id 1.0
==20210== Thread 2:
==20210== Invalid read of size 8
==20210==    at 0x486AA79: get_drv (helper.c:130)
==20210==    by 0x486AA79: comp_new (helper.c:[29](https://github.com/thesofproject/sof/actions/runs/3538859073/jobs/5940117891#step:7:30)9)
==20210==    by 0x486B9EF: ipc_comp_new (helper.c:656)
==20210==    by 0x48B0022: load_process (process.c:507)
==20210==    by 0x48AEB55: load_widget (widget.c:146)
==20210==    by 0x1101B7: parse_topology (topology.c:472)
==20210==    by 0x10C5F7: test_pipeline_load (testbench.c:659)
==20210==    by 0x10C5F7: pipline_test (testbench.c:765)
==20210==    by 0x48C0608: start_thread (pthread_create.c:477)
==20210==    by 0x49FA132: clone (clone.S:95)
==20210==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==20210== 
==20210== 
==20210== Process terminating with default action of signal 11 (SIGSEGV)
==20210==  Access not within mapped region at address 0x0
==20210==    at 0x486AA79: get_drv (helper.c:1[30](https://github.com/thesofproject/sof/actions/runs/3538859073/jobs/5940117891#step:7:31))
==20210==    by 0x486AA79: comp_new (helper.c:299)
==20210==    by 0x486B9EF: ipc_comp_new (helper.c:656)
==20210==    by 0x48B0022: load_process (process.c:507)
==20210==    by 0x48AEB55: load_widget (widget.c:146)
==20210==    by 0x1101B7: parse_topology (topology.c:472)
==20210==    by 0x10C5F7: test_pipeline_load (testbench.c:659)
==20210==    by 0x10C5F7: pipline_test (testbench.c:765)
==20210==    by 0x48C0608: start_thread (pthread_create.c:477)
==20210==    by 0x49FA1[32](https://github.com/thesofproject/sof/actions/runs/3538859073/jobs/5940117891#step:7:33): clone (clone.S:95)
==20210==  If you believe this happened as a result of a stack
==20210==  overflow in your program's main thread (unlikely but
==20210==  possible), you can try to increase the size of the
==20210==  main thread stack using the --main-stacksize= flag.
==20210==  The main thread stack size used in this run was 16777216.
pipeline run 0/1
```

**Comment by singalsu** [comment]
> I think you mean https://github.com/thesofproject/sof/actions/runs/3538859073/jobs/5940117891
> 
> @singalsu this looks worrying...

Thanks Marc, yep, I will try to replicate this.

**Comment by sathyap-chrome** [comment]
@mwasko Can we merge this in ?

**Pull request merged**
