### PR TITLE
git: fix the rimage submodule to mask 0xffff

### PR DESCRIPTION
**Pull request by xiulipan**
Update the rimage to latest feature with 0xffff mask.

NOTE: the rimage version need to be committed for each update
otherwise the rimage submodule will not update.
Also please take care when make commit, check if mis-add commit
for submoudle.

Tips to work with submodule:
* Do not use git commit -a
* Run git submodule update before make new commit

Fix issue caused by mis-add old rimage submodule.

Signed-off-by: Pan Xiuli <xiuli.pan@linux.intel.com>

### CODE REVIEW

**Comment by xiulipan** [comment]
@marc-hb @jajanusz It seems we did not actually use the latest 3 update in rimage for quite long time since Jun 24th.
```
-Subproject commit 9f3f2d7d714908c1f8f3f77baebe9175682f02bc
+Subproject commit 7317f2af3901991becaecaa48400611b1a532cd5
```

Every time we update submodule we need add the change and commit it to the sof.

Fix https://github.com/thesofproject/sof/issues/3173

**Comment by xiulipan** [comment]
Update with some new findings.

**Comment by lgirdwood** [comment]
@xiulipan looks like a kernel bug on BYT/CHT module loading from CI ? @plbossart any idea

**Comment by plbossart** [comment]
> @xiulipan looks like a kernel bug on BYT/CHT module loading from CI ? @plbossart any idea

looks like the wrong kernel is used here maybe? there should be SOF modules in there.

**Comment by marc-hb** [comment]
>  It seems we did not actually use the latest 3 update in rimage for quite long time since Jun 24th.

Incorrect: rimage was accidentally downgraded only yesterday in unrelated (and not well reviewed) PR #3184 

> always give all the SHA1s involved in all repos in the commit message when something wrong happen.

Done in #3202 which supersedes this while @xiulipan gets some sleep (different timezone; I'm just starting my day). Please review it very carefully.

> Do not use git commit -a

Agreed 200%, this option should be removed.

> Run git submodule update before make new commit

Good idea yes but not strictly required.

PS: I hate submodules too.

**Comment by xiulipan** [comment]
@marc-hb Looks like this https://github.com/thesofproject/sof/pull/3202 is a more clean fix. Will close my PR here.

**Comment by marc-hb** [comment]
> more clean fix. 

I only changed the commit message :-) But I think it matters for submodules.

PS: can you review it?

**Pull request closed without merging**
