### PR TITLE
Fix sof_bootone script

### PR DESCRIPTION
**Pull request by ranj063**

### CODE REVIEW

**Comment by ranj063** [comment]
> not sure why Intel CI throws an error here?

@plbossart checking now. it had passed all checks last night. not sure whats broken.

**Comment by ranj063** [comment]
@lgirdwood fixed CI issue now.

**Comment by lgirdwood** [comment]
@zrombel can you kick the internal CI here, not seeing any status or otherwise.

**Comment by xiulipan** [comment]
@plbossart Network issue xcc compiler failed. Fixed now.

**Pull request merged**
