### PR TITLE
clk: use LPRO instead of WOVCRO

### PR DESCRIPTION
**Pull request by slawblauciak**
Signed-off-by: Slawomir Blauciak <slawomir.blauciak@linux.intel.com>

### CODE REVIEW

**Review by lgirdwood — COMMENTED** [review]
@slawblauciak looks like you have an rimage change too ?
So it looks like we are saying WOVCRO should not be used in this use case ?

**Comment by slawblauciak** [comment]
> @slawblauciak looks like you have an rimage change too ?
> So it looks like we are saying WOVCRO should not be used in this use case ?

This change is suggested by @ranj063 
There appear to be some issues related to D0Ix, I haven't had time to look into those yet, which is why this is just a test for now.

And yes, the rimage change is accidental.

**Review by lgirdwood — APPROVED** [review]

**Comment by ranj063** [comment]
> This change is suggested by @ranj063
> There appear to be some issues related to D0Ix

@slawblauciak I did not suggest this change. Thisnwil have implications on power for S0ix and it is not acceptable. What I suggested nwas to turn off DSP D0i3 in S0.

**Comment by lgirdwood** [comment]
@slawblauciak @mwasko does anyone have the residency rate of WOVCRO for playback, speaker and HDMI ? I would suspect we would only be using this under very minimal processing load (and hence the minority of the time if we are using DSM and IGO) ?

**Comment by sys-pt1s** [comment]
Can one of the admins verify this patch?

**Comment by kv2019i** [comment]
No activity in a year, closing.

**Pull request closed without merging**
