### PR TITLE
west.yml: update Zephyr to 9d1df132b1c + one revert

### PR DESCRIPTION
**Pull request by kv2019i**
Modified https://github.com/thesofproject/sof/pull/8901 to address the failures seen in CI.

### CODE REVIEW

**Comment by kv2019i** [comment]
SOF Ci test looks good. There's is one pause-resume fail on a multicore MTL configuration, but this is somethign we can live with as we have fixed coming up via newer Zephyr -> https://sof-ci.01.org/sofpr/PR8903/build3114/devicetest/index.html?model=MTLP_RVP_NOCODEC&testcase=multiple-pause-resume-50

cAVS2.5 run has one system-pm fail https://sof-ci.01.org/sofpr/PR8903/build3115/devicetest/index.html -> we can ignore.

Let's wait for Internal Intel CI results (still running) and if good, we can merge this.

**Comment by kv2019i** [comment]
@dbaluta @LaurentiuM1234 Assuming all tests pass, ok to go with this PR (use a local copy of Zephyr so we can revert one upstream patch )?

**Comment by kv2019i** [comment]
Bug filed for the revert https://github.com/zephyrproject-rtos/zephyr/issues/69807

**Review by lyakh — APPROVED** [review]

**Comment by LaurentiuM1234** [comment]
> @dbaluta @LaurentiuM1234 Assuming all tests pass, ok to go with this PR (use a local copy of Zephyr so we can revert one upstream patch )?

Should be fine. I'm assuming this is only temporary (i.e: by 2.10 we'll go back to mainline Zephyr), right?

Prepared https://github.com/thesofproject/sof/pull/8904 for the 64-bit CI build failure caused by this. Should we include it in this PR or merge it later on?

**Comment by kv2019i** [comment]
@LaurentiuM1234 wrote:
> @kv2019i wrote:
> > @dbaluta @LaurentiuM1234 Assuming all tests pass, ok to go with this PR (use a local copy of Zephyr so we can revert one upstream patch )?
> 
> Should be fine. I'm assuming this is only temporary (i.e: by 2.10 we'll go back to mainline Zephyr), right?

At least for now temporary, although comments are welcome on how to improve the process. This is not the first time when we've had a cascade of issues blocking Zephyr updates for a longer time in SOF, and we really need to tackle these faster. One concrete improvement has been getting rid of some internal API use in SOF (like the SMP API that is now removed with this PR), and ideally these decouple SOF and Zephyr better in the future, but this still leaves a category of problems that, if caught too late, will cause  problem to all SOF users. 

> Prepared #8904 for the 64-bit CI build failure caused by this. Should we include it in this PR or merge it later on?

Thanks, I cherry-picked that and pushed one more update. I didn't merge the git commits, but at least these are in the same pull request. Let's see if the CI is happy with this.

**Review by lyakh — APPROVED** [review]

**Review by LaurentiuM1234 — APPROVED** [review]

**Review by dbaluta — APPROVED** [review]

**Comment by iuliana-prodan** [comment]
> @LaurentiuM1234 wrote:
> 
> > @kv2019i wrote:
> > > @dbaluta @LaurentiuM1234 Assuming all tests pass, ok to go with this PR (use a local copy of Zephyr so we can revert one upstream patch )?
> > 
> > 
> > Should be fine. I'm assuming this is only temporary (i.e: by 2.10 we'll go back to mainline Zephyr), right?
> 
> At least for now temporary, although comments are welcome on how to improve the process. This is not the first time when we've had a cascade of issues blocking Zephyr updates for a longer time in SOF, and we really need to tackle these faster. One concrete improvement has been getting rid of some internal API use in SOF (like the SMP API that is now removed with this PR), and ideally these decouple SOF and Zephyr better in the future, but this still leaves a category of problems that, if caught too late, will cause problem to all SOF users.

I understand this is temporary, but having a fork for zephyr in `thesofproject` is not OK, IMO.
We also have a `sof` in `zephyrproject-rtos`. And we need to cherry pick fixes from one repo to the other.

Maybe we should monitor closer the `zmain` from CI:
image
and try to fix those issues when they appear.

Also, when we create a stable branch in sof, can we do that also in Zephyr ?
Create a stable branch, in [Zephyr](https://github.com/zephyrproject-rtos/zephyr), for SOF and use that one in SOF's `west.yml`. And push on that branch the fixes we need for a release.

**Comment by kv2019i** [comment]
@iuliana-prodan thanks for the response. Let's take this into discussiong at https://github.com/orgs/thesofproject/discussions/8909 -- I answered some of the points there.

W.r.t. stable branches, that we do already. E.g. for SOF2.9, I now backported a couple of fixes from Zephyr upstream to sof/stable-v2.9 branch of Zephyr:
https://github.com/thesofproject/sof/pull/8907

I do think in upstream releases we need to keep a strick policy of only having patches that have been merged to upstream (either SOF or Zephyr) and not have patches in the stable branches that are not in main.

**Comment by marc-hb** [comment]
#8913 was next and just merged.

**Pull request merged**
