### PR TITLE
xtensa-build-zephyr.py:  default to subprocess.run(check=True) . Disable some pylint warnings.

### PR DESCRIPTION
**Pull request by marc-hb**
2 commits, see commit messages.

### CODE REVIEW

**Review by lgirdwood — APPROVED** [review]
@aborisovich good for Windows ?

**Review by greg-intel — APPROVED** [review]
I'm surprised you're disabling some lint warnings.  
Why do we want mixed indentation?

**Comment by marc-hb** [comment]
From the commit message:
> Disable W0312 because the entire file uses tabs.

Dunno why pylint warns about it like this but we have 350 more urgent (and with less intrusive fixes) pylint warnings to deal with :-)

**Comment by sys-pt1s** [comment]
Can one of the admins verify this patch?

**Comment by aborisovich** [comment]
Yes it is perfectly fine on Windows. I had checked it but forgot to approve, my bad.

**Pull request merged**
