### PR TITLE
tools: Support multi-output component playback testing on testbench

### PR DESCRIPTION
**Pull request by johnylin76**
This patch is currently followed on top of crossover component PR: https://github.com/thesofproject/sof/pull/2802

This patch supports testbench playback testing for single-input-multi-output component, e.g. crossover. Test playback m4 file (tools/test/topology/test-playback.m4) is extended to generate up to 4 output pipelines test topologies, where argument "TEST_PIPE_AMOUNT" is provided for identifying the number of pipelines.

While building test topologies, 2way, 3way, and 4way crossover playback topology files will be generated under build_tools/test/topology/ with names as follows:
`test-playback-ssp5-mclk-0-I2S-2way-crossover-s16le-s16le-48k-24576k-codec.*`
`test-playback-ssp5-mclk-0-I2S-3way-crossover-s16le-s16le-48k-24576k-codec.*`
`test-playback-ssp5-mclk-0-I2S-4way-crossover-s16le-s16le-48k-24576k-codec.*`
and so on.

**Testbench Run**
For example of running 4way-crossover playback, the coefficient file with 4-sink crossover should be generated under tools/tune/crossover/ by

`octave example_crossover.m`

Then after building, run testbench by the following command:

`testbench -i input -o output_1,output_2,output_3,output_4 -t test-playback-ssp5-mclk-0-I2S-4way-crossover-s16le-s16le-48k-24576k-codec.tplg -r 48000 -R 48000 -c 1 -b S16_LE -a crossover=libsof_crossover.so`

where argument "-o" now accepts specifying up to 4 output file names delimited by comma (in 4way case 4 files should be given), and "-c" specifies channels. The 4way topology file should be specified.

### CODE REVIEW

**Comment by cujomalainey** [comment]
Mind if we either cherry-pick your changes to a new branch or rebase @sebcarlucci's changes out of your branch so that we only review the related testbench changes in this PR? Just to keep things simple and also so we won't be gated by the UUID PR.

**Comment by cujomalainey** [comment]
Also, I recommend adding your @google and @chromium emails to your github so the commits are associated to your account so they can be easily related back to you.

**Comment by johnylin76** [comment]
> Mind if we either cherry-pick your changes to a new branch or rebase @sebcarlucci's changes out of your branch so that we only review the related testbench changes in this PR? Just to keep things simple and also so we won't be gated by the UUID PR.

I created https://github.com/sebcarlucci/sof/pull/3 rebased on @sebcarlucci's changes. However, I couldn't add any reviewers?

**Comment by cujomalainey** [comment]
You will need to close that and make the PR in the SOF repo since Seb's fork is essentially archived now

**Comment by johnylin76** [comment]
Got it. I have created https://github.com/thesofproject/sof/pull/3210 in SOF repo, thanks.

**Comment by lgirdwood** [comment]
Thanks @johnylin76 please close the PR you no longer need (since we now have two with the same title).

**Pull request closed without merging**
