### PR TITLE
topology: kwd: update detector configure blob to align with default settings

### PR DESCRIPTION
**Pull request by keyonjie**
Aim to fix https://github.com/thesofproject/linux/issues/929

We should load_mips to be 0 as commented from @slawblauciak , Here align values with default settings, that is:

load_mips = 0, load_memory_size = 0, keyphrase_length = 0x780,
activation_shift = 0x3, activation_threshold = 0x3fff.

Signed-off-by: Keyon Jie <yang.jie@linux.intel.com>

### CODE REVIEW

**Comment by keyonjie** [comment]
this PR is used to fix:
https://github.com/thesofproject/linux/issues/929

**Comment by tlauda** [comment]
@keyonjie pr-device-test failed.

**Comment by keyonjie** [comment]
> @keyonjie pr-device-test failed.

That is an existed issue, not introduce by this PR?

**Comment by tlauda** [comment]
@keyonjie @xiulipan Sure, but at least we see there is something weird going on with CI.

**Comment by wenqingfu** [comment]
SOFCI TEST

**Comment by xiulipan** [comment]
@wenqingfu thanks for retrigger the test. I see the fail for byt_rt5651, it seems the codec is not probed through I2C. Maybe some hardware issues there, will move the problem device into maintain list and trigger again.

**Comment by xiulipan** [comment]
@keyonjie @tlauda 
What do you mean here by the pr-device-test failed?

The first wrong failed build with two cases in https://sof-ci.01.org/sofpr/PR1427/build1970/
apl nocodec failed wired, not known yet why the aplay failed by failed open
```
[INFO]: playback checking with params [hw:0,0, 48000, 2, s16_le] ...
ALSA lib pcm_hw.c:1713:(_snd_pcm_hw_open) Invalid value for card
aplay: main:788: audio open error: No such file or directory
```

byt_rt5651 it seems to be hw issue, the codec is not probed by codec driver.
`[   15.772855 <    0.825764>] rt5651: probe of i2c-10EC5651:00 failed with error -121`

**Pull request merged**
