### PR TITLE
buffer: Move code with tracing/assertions from headers to .c files

### PR DESCRIPTION
**Pull request by ktrzcinx**
After change there is proper location in assert and trace message.

### CODE REVIEW

**Comment by paulstelian97** [comment]
Did you analyze the performance impact of those functions no longer being inline?

**Comment by ktrzcinx** [comment]
I didn't do it here, but sd long as we use `-fno-inline-functions` I guess there shouldn't be any performance difference

**Comment by paulstelian97** [comment]
> I didn't do it here, but sd long as we use `-fno-inline-functions` I guess there shouldn't be any performance difference

I wasn't aware this flag was used actually. I mean, sure, this PR fixes the problem of wrong line numbers, but the functions themselves are hotspots and thus it might matter if we don't inline them.

**Comment by ktrzcinx** [comment]
I have checked code disassembly and it seems `buffer_zero` is expanded into `smart_amp_trigger` function (before changes), so inline works as expected. `-fno-inline-functions` prevents optimizer from handling standard functions as inline. 
Even so, `buffer_set_params` and `buffer_params_match` are called in preparation stage, where time-performance is not critical. `buffer_zero`, excluding preparation stage, is called on dai trigger release for capture pipeline, smar_amp release trigger and after capture dai xrun. I didn't find any call to those function during normal processing stage, where performance matters.

**Comment by paulstelian97** [comment]
Unit tests failure is a red herring? (I see "build not found" on the page)

**Comment by paulstelian97** [comment]
SOFCI TEST

**Review by paulstelian97 — CHANGES_REQUESTED** [review]
From my cursory read of the test results, unit tests on APL are failing because of linker errors. Can you check them?

**Review by paulstelian97 — APPROVED** [review]
Leave it for another 24 hours, just in case CI unfreezes itself and reports some error. Everything else looks good now.

**Comment by lgirdwood** [comment]
Try CI again.

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by paulstelian97** [comment]
All checks passed? Nice.

**Review by lgirdwood — APPROVED** [review]

**Pull request merged**
