### PR TITLE
topology: fix DMIC device names

### PR DESCRIPTION
**Pull request by plbossart**
DMIC01 is just useless for a user, change to DMIC48kHz to align with
existing HDaudio case. Change DMIC16k to DMIC16kHz for consistency.

Also make sure we only use 'DMIC' for 'PCH-attached DMICs'. For
RT715-based solutions, the microphones can be analog, so use more
generic 'Microphones' description.

Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>

### CODE REVIEW

**Comment by juimonen** [comment]
@plbossart so should we change this also in platform/intel/intel-generic-dmic.m4? I think they are a now called Dmic0 and Dmic1 and this is what we've been using in ucm. I'm fine with the change, @singalsu had some dislike for having the samplerate in the name. But if it is defacto standard, let's change...

**Comment by kv2019i** [comment]
@juimonen wrote:
> @plbossart so should we change this also in platform/intel/intel-generic-dmic.m4? I think they are > a now called Dmic0 and Dmic1 and this is what we've been using in ucm. I'm fine with the change,

Yikes. Let's not break the UCMs we already have upstream. I guess current upstream UCM refers to the PGA name which is now defined as:

define(`PGA_NAME', Dmic0)

... as long as we keep this, existing (upstream) UCMs will continue to work. If we still want to change, we need to first send if-else patches to upstream UCM repo and only then release a new FW.

**Comment by plbossart** [comment]
> @juimonen wrote:
> 
> > @plbossart so should we change this also in platform/intel/intel-generic-dmic.m4? I think they are > a now called Dmic0 and Dmic1 and this is what we've been using in ucm. I'm fine with the change,
> 
> Yikes. Let's not break the UCMs we already have upstream. I guess current upstream UCM refers to the PGA name which is now defined as:
> 
> define(`PGA_NAME', Dmic0)
> 
> ... as long as we keep this, existing (upstream) UCMs will continue to work. If we still want to change, we need to first send if-else patches to upstream UCM repo and only then release a new FW.

I strongly recommend we fix names. DMIC0, DMIC01, DMIC16k are just misleading. I suggested 48 and 16kHz since it's self-explanatory, if you have a better naming please suggest it. It's high time we look at the user-visible names and avoid a legacy.

**Comment by singalsu** [comment]
How about DMIC_primary, DMIC_secondary if DMIC0, DMIC1 style is not good? I'm not so keen with  a sample rate in the device name. The SOF driver supports supports configuring them both for 8 - 96 kHz. Also referring to other as generic and other voice is misleading since the roles can be swapped if desired due to symmetrical HW.

Though mixed style naming is the most confusing way and this is PR addressing that. I'm okay with that too.

**Comment by singalsu** [comment]
Would we change the name in topology again if we configure one of the FIFOs to 96 kHz and what parts of the stack does this impact? I worked a while ago with 96 kHz requirement (PR #1598 that works but isn't merged yet) due to a request to us.

**Comment by plbossart** [comment]
> How about DMIC_primary, DMIC_secondary if DMIC0, DMIC1 style is not good? I'm not so keen with a sample rate in the device name. The SOF driver supports supports configuring them both for 8 - 96 kHz. Also referring to other as generic and other voice is misleading since the roles can be swapped if desired due to symmetrical HW.
> 
> Though mixed style naming is the most confusing way and this is PR addressing that. I'm okay with that too.

primary and secondary can be understood as front/back and that would be misleading.

DMIC0 and DMIC1 is also hard to understand, people would understand it as first microphone and second microphone.

DMIC01 is an absolute nonsense, and mixed DMIC1 and DMIC16k is also bad.

In practice, one of the two interfaces is higher frequency than the other, so we should recognize this and not used numerals that can be confused with spatial arrangement.

if there is no consensus for 48/16, then we have to use something like hf/lf, hp/lp?

**Comment by singalsu** [comment]
If we can change the name if we change the used sample rate then this proposed naming with xxkHz is quite clear.

**Comment by sathya-nujella** [comment]
> LGTM @plbossart. Do the device names also feature in the UCM's?
No, UCM will not use this name. It is only using card name.
For e.g. UCM change for DMIC is like this,
SectionDevice."Internal Mic".0 {
	Value {
		CapturePCM "hw:sofrt5682,99"

CRAS is expecting these names in UCM:
https://chromium.googlesource.com/chromiumos/third_party/adhd/+/refs/heads/master/cras/src/server/cras_alsa_io.c#45

> @sathya-nujella @sathyap-chrome FYI
Thank you @ranj063. I will update my pending topology based on this. This change is good and more readable.

**Comment by plbossart** [comment]
> If we can change the name if we change the used sample rate then this proposed naming with xxkHz is quite clear.

@singalsu you can change the PCM device name to match what the topology can do on the direct capture path, e.g. if your topology captures at 96kHz you can change to DMIC96kHz. If you have some SRC in the middle then change the name to Media to something that is no longer tied to the capture rate.

**Comment by juimonen** [comment]
@plbossart @singalsuo I guess singalsuo meant can the name dynamically change to represent the sample rate when re-configuring from topology... personally I don't see why we should embed the samplerate to the name. We don't have Speaker96kHz or Headphones48kHz in alsa, the user has to find out what rate it supports. Also I see risk for bugs/confusion if for some configuration the dmic48kHz does support only 16kHz. So I'm not sure what's the best naming if we have 2 or more similar outputs (like if we would have 2 headphone outputs for some reason).

**Comment by jajanusz** [comment]
@plbossart Is it ok to merge? I see there is some discussion going on and IDK if you want to address these problems in this PR.

**Comment by plbossart** [comment]
> @plbossart @singalsuo I guess singalsuo meant can the name dynamically change to represent the sample rate when re-configuring from topology... personally I don't see why we should embed the samplerate to the name. We don't have Speaker96kHz or Headphones48kHz in alsa, the user has to find out what rate it supports. Also I see risk for bugs/confusion if for some configuration the dmic48kHz does support only 16kHz. So I'm not sure what's the best naming if we have 2 or more similar outputs (like if we would have 2 headphone outputs for some reason).

@juimonen if you have a better proposal then please describe it. for now we have DMIC01 which is just useless. 48kHz is not great but it's at least more intuitive.

**Comment by juimonen** [comment]
@plbossart @jajanusz 
We have	a case where we have 1 dmic hw with 2 fifos, where it is possible	to configure these fifos with different parameters like samplerate. And there are limitations to the configuration, so for example if the other one is 48khz the other one needs to be lower rate like 16kHz.

As I understood from @singalsuo, currently it is the same actual digital microphones that are connected to the other end, but also we could mix/shuffle the connections of the possible 4 dmics to these fifos. So in other words, depending on dmic ip configuration we can have multiple different setups for these 2 inputs: hence it can be really hairy to try to incorporate this setup in the alsa element naming so that the user would somehow immediately understand what is going on.

So for example currently we could record from both fifos at the same time and the user should understand that it is the same signal coming from same microphones just with different rate (not for example from different microphones). What I'm saying here is that this is a case where there is really no clear solution for naming.

So still my suggestion is pretty neutral "Dmic0" and "Dmic1", although I do understand the possible confusion these can also cause. So despite I should know something about audio, It is not obvious what is connected behind these elements and what signal am I recording even though it would read the samplerate.

If something I claim above is wrong, just correct me.

**Comment by kv2019i** [comment]
> So still my suggestion is pretty neutral "Dmic0" and "Dmic1", although I do understand the possible 
> confusion these can also cause. So despite I should know something about audio, It is not obvious 

You may a valid point @juimonen . This can also be compared to the HDMI PCMs. There too attempts to assign semantics to PCM nodes (e.g. that specific PCM node numbers would indicate DP-MST) have failed and we are back to HDMI1+HDMI2+HDMI3. Other means (like ELD data in case of HDMI) have to be used to provide semantics that end-user can actually understand.

**Comment by plbossart** [comment]
> > So still my suggestion is pretty neutral "Dmic0" and "Dmic1", although I do understand the possible
> > confusion these can also cause. So despite I should know something about audio, It is not obvious
> 
> You may a valid point @juimonen . This can also be compared to the HDMI PCMs. There too attempts to assign semantics to PCM nodes (e.g. that specific PCM node numbers would indicate DP-MST) have failed and we are back to HDMI1+HDMI2+HDMI3. Other means (like ELD data in case of HDMI) have to be used to provide semantics that end-user can actually understand.

with HDMI 1,2,3 there is an expectation that you connect to monitors. 
That's different to microphones where 0 and 1 hints at spatial position.

**Comment by lgirdwood** [comment]
@juimonen @perex meaningful PCM names may not always be possible if hw_params can change, but this may need something in ALSA proc where we could list the capabilities for each PCM to help users ? Also including listing the PCMs current runtime hw_params if any ?

**Comment by juimonen** [comment]
@plbossart at least I don't associate 0 and 1 to spatial position... :) but could be just me. I understand it firstly as 2 separate mics (which is also wrong in this case, as it is 2 separate fifos from same physical mic).

@lgirdwood we should be able to get the formats, supported rates etc from alsa api I guess? And we should be able to limit those in topology..

**Comment by juimonen** [comment]
@plbossart and yes sure 2 separate mics = usually 2 different spatial positions. Let's put it this way, I also associate mic names with 2 different sampling rates in the names as separate, so it doesn't give me immediate enlightenment of 1 hw with 2 different parameters in input . And if there's an explanation provided, I'm immediately asking, why can't you just open 1 device with different sample rate.

**Comment by plbossart** [comment]
> @plbossart and yes sure 2 separate mics = usually 2 different spatial positions. Let's put it this way, I also associate mic names with 2 different sampling rates in the names as separate, so it doesn't give me immediate enlightenment of 1 hw with 2 different parameters in input . And if there's an explanation provided, I'm immediately asking, why can't you just open 1 device with different sample rate.

so what now, we are going to stick with DMIC01 because nothing else works?

**Comment by kv2019i** [comment]
@plbossart wrote:
> so what now, we are going to stick with DMIC01 because nothing else works?

Re-reading the comments, I don't think there's a clear winner. For @juimonen  -- the sampling rates are hardcoded for both DMICs currently, so the possibility to modify the sampling rate is a bit theoretical at this point. The case where the one fixed rate of the primary dmic is something else than 48kHz is more likely though, so that argument is more pressing.

How about "DMIC" and "DMIC16kHz"? Both PCMs will have fixed sampling rate set in topology (48kHz for most, but can be 96kHz as well), no spatial hint is given by the name and "DMIC16kHz" yells that "I'm special" and most people will ignore it (as they should). Least worst? @lgirdwood @singalsu ?

**Comment by juimonen** [comment]
@plbossart @kv2019i  I'm fine with whatever as there is no best option (still my own preference is Dmic0 and Dmic1). But if you decide something else, unify then also the existing generic dmic pipeline and send PR to the alsa-ucm-conf repo to change the naming. Otherwise we have only partly unified names...

**Comment by plbossart** [comment]
> @plbossart wrote:
> 
> > so what now, we are going to stick with DMIC01 because nothing else works?
> 
> Re-reading the comments, I don't think there's a clear winner. For @juimonen -- the sampling rates are hardcoded for both DMICs currently, so the possibility to modify the sampling rate is a bit theoretical at this point. The case where the one fixed rate of the primary dmic is something else than 48kHz is more likely though, so that argument is more pressing.
> 
> How about "DMIC" and "DMIC16kHz"? Both PCMs will have fixed sampling rate set in topology (48kHz for most, but can be 96kHz as well), no spatial hint is given by the name and "DMIC16kHz" yells that "I'm special" and most people will ignore it (as they should). Least worst? @lgirdwood @singalsu ?

Good suggestion @kv2019i. I will update the PR and use this naming

**Comment by lgirdwood** [comment]
@plbossart any ETA for update ?

**Comment by plbossart** [comment]
> @plbossart any ETA for update ?

Done.

**Comment by lgirdwood** [comment]
@zrombel can you check the CI, I cant see it. Thanks

**Comment by plbossart** [comment]
CI seems to be in the weeds?

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by lgirdwood** [comment]
Lets try again.

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by lgirdwood** [comment]
@plbossart seeing a lot of CI errors with this one, could be CI though. Rescheduling again as it may be due to the planned CI updates.

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
> @plbossart seeing a lot of CI errors with this one, could be CI though. Rescheduling again as it may be due to the planned CI updates.

CI looks good now?

**Comment by lgirdwood** [comment]
@plbossart it does indeed :). Merged. Usual suspects for module reload on jenkins.

**Pull request merged**
