### PR TITLE
 ssp: quirks for byt and hsw

### LINKED ISSUE #1443: [BUG][BYT] nocodec loopback recording has only silence
**Describe the bug**
For BYT Minnowboard, Loopback recording has only silence. Daily CI build, 5.1.0-daily-nocodec-20190516 is used. Loopback in APL UP2 nocodec mode worked fine. Linux driver parse the tplg and set ssp.quirks(=64).

[   13.852957] sof-audio-acpi 80860F28:01: tplg: config SSP2 fmt 0x4001 mclk 19200000 bclk 2400000 fclk 48000 width (24)25 slots 2 mclk id 0 quirks 64

sof dsp may not utilize this quirks bit.

**To Reproduce**
Try loopback recording and check output wave file.
Terminal1)
$ arecord -vv -Dhw:0,0 -f S16_LE -c 2 -r 48000 mb_nocodec_s16.wav
Terminal2)
$ aplay -vv -Dhw:0,0 -f S16_LE -c 2 -r 48000 ~/Music/short_48000.wav

**Expected behavior**
Recorded wave file should have playback sound.

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

**Environment**
BYT Minnowboard Nocodec mode.

**Screenshots or console output**
[mb_0515_nocodec_booting_dmesg.log](https://github.com/thesofproject/sof/files/3184906/mb_0515_nocodec_booting_dmesg.log)
[mb_0515_nocodec_loopback.log](https://github.com/thesofproject/sof/files/3184907/mb_0515_nocodec_loopback.log)
[mb_0515_sof_logger.log](https://github.com/thesofproject/sof/files/3184908/mb_0515_sof_logger.log)
[mb_nocodec_s16.wav.zip](https://github.com/thesofproject/sof/files/3184932/mb_nocodec_s16.wav.zip)

### PR DESCRIPTION
**Pull request by jajanusz**
Fixes #1443 

It adds quirk support that was so far enabled only for CAVS platforms. Registers for BYT & HSW were already there.

### CODE REVIEW

**Comment by jajanusz** [comment]
@xiulipan @Jiangxinx @fredoh9 Can you please check if it helps with your issue? I have no device to test it.

**Comment by jajanusz** [comment]
@xiulipan But CI fails on `On-device Test Failed:BYT_MB_NOCODEC`.
Is it CI issue ? Please note this PR adds something to BYT and if you f.e. send unsupported quirks from topology it will response with error instead of (like previously) going on.

**Comment by xiulipan** [comment]
@jajanusz 
Just go through the dmesg and it seems more like a machine driver issue

> [   14.082088 <    0.000018>] sof-audio-acpi 80860F28:01: tplg: load pcm Low Latency 0
> [   14.082111 <    0.000023>] sof-audio-acpi 80860F28:01: error: no platforms
> [   14.082130 <    0.000019>] sof-audio-acpi 80860F28:01: ASoC: FE link loading failed
> [   14.082148 <    0.000018>] sof-audio-acpi 80860F28:01: tplg: load pcm Media Playback 1
> [   14.082160 <    0.000012>] sof-audio-acpi 80860F28:01: error: no platforms
> [   14.082172 <    0.000012>] sof-audio-acpi 80860F28:01: ASoC: FE link loading failed

I will try to check it manually and give you feedback

**Comment by plbossart** [comment]
On 6/11/19 1:58 AM, xiulipan wrote:
> @jajanusz <https://github.com/jajanusz>
> Just go through the dmesg and it seems more like a machine driver issue
> 
>     [ 14.082088 < 0.000018>] sof-audio-acpi 80860F28:01: tplg: load pcm
>     Low Latency 0
>     [ 14.082111 < 0.000023>] sof-audio-acpi 80860F28:01: error: no platforms
>     [ 14.082130 < 0.000019>] sof-audio-acpi 80860F28:01: ASoC: FE link
>     loading failed
>     [ 14.082148 < 0.000018>] sof-audio-acpi 80860F28:01: tplg: load pcm
>     Media Playback 1
>     [ 14.082160 < 0.000012>] sof-audio-acpi 80860F28:01: error: no platforms
>     [ 14.082172 < 0.000012>] sof-audio-acpi 80860F28:01: ASoC: FE link
>     loading failed
> 
> I will try to check it manually and give you feedback

Looks like you're using PR1018 which hasn't been merged yet?

**Comment by jajanusz** [comment]
@xiulipan Let me know when you checked if it works.

**Comment by fredoh9** [comment]
I tested with this patch on MB NOCODEC mode. it worked fine. Looks good to me.

**Comment by jajanusz** [comment]
@fredoh9 thanks for testing

**Pull request merged**
