### PR TITLE
platform: posix: dma: place api in iterable section

### PR DESCRIPTION
**Pull request by jilaypandya**
this commit refactors dma_driver_api in iterable_section

### CODE REVIEW

**Comment by sofci** [comment]
Can one of the admins verify this patch?
> reply **test&nbsp;this&nbsp;please** to run this test once

**Review by kv2019i — APPROVED** [review]
Thank you @jilaypandya ! Let's have the CI test this out as well.

**Comment by jilaypandya** [comment]
I think I would need some help to get CI done correctly.

**Comment by kv2019i** [comment]
@jilaypandya I know what's the problem, SOF doesn't have "device: Add DEVICE_API macros" yet. We are struggling with a series of regressions that has blocked our Zephyr updates, so we are stuck at e59289d89999 for Zephyr. But this should be solved soon, I had almost clean CI with https://github.com/thesofproject/sof/pull/9705 ... still need one more fix on Zephyr side before we can upgrade (and then your PR should pass SOF CI).

**Comment by lyakh** [comment]
test this please

**Comment by kv2019i** [comment]
@jilaypandya Can you rebase now? #9712 merged to SOF, so Zephyr should be new enough for this PR to pass CI tests.

**Comment by jilaypandya** [comment]
> @jilaypandya Can you rebase now? #9712 merged to SOF, so Zephyr should be new enough for this PR to pass CI tests.

Done

**Review by lgirdwood — APPROVED** [review]

**Comment by kv2019i** [comment]
SOFCI TEST

**Comment by kv2019i** [comment]
Thank you @jilaypandya , all mandatory now passing, proceeding with merge.

**Pull request merged**
