### PR TITLE
drivers: intel: remove remaining references to MN driver

### PR DESCRIPTION
**Pull request by kv2019i**
The Zephyr SSP driver has had dependency to CONFIG_INTEL_NM defined in SOF, so this has not been removed before. This is now cleaned up on Zephyr side, so we can proceed to remove the remaining bits of the Intel MN driver on SOF side.

### CODE REVIEW

**Comment by kv2019i** [comment]
Found in review of https://github.com/thesofproject/sof/pull/9667

**Review by lgirdwood — APPROVED** [review]
LGTM to merge when ready.

**Comment by lgirdwood** [comment]
> Unfortunately we have a problem on TGL with IPC4, the test with SSP does not pass. The question is what do we do about it or should we throw away this test? I would like it to be agreed with the developers
> 
> Issue: E TimeoutError: Play stream timed out after 6.003951072692871 seconds

@wszypelt pls disable this test. I would not fully delete though, just disable.

**Comment by kv2019i** [comment]
@lgirdwood @wszypelt This is an expected result that some SSP tests will fail on cAVS2.5. This PR removes the SOF side CONFIG option, but we are still using old Zephyr here. so the SSP driver code for SSP2.5 clocks will be then partially disabled. I expect the tests to pass when Zephyr part is merged and can test together with this PR (and thus the DNM for this).
FYI @lyakh

**Comment by kv2019i** [comment]
New version pushed:
- contains Zephyr update (first commit)
- MN removal in SOF as second commit

**Comment by kv2019i** [comment]
DSP crashes on ace30, probably caused by latest Zephyr main:
```
[00:00:01.946,936] <inf> main: sof_app_main: SOF initialized
[00:00:02.037,930] <err> os: print_fatal_exception:  ** FATAL EXCEPTION
[00:00:02.038,041] <err> os: print_fatal_exception:  ** CPU 0 EXCCAUSE 29 (store prohibited)
[00:00:02.038,071] <err> os: print_fatal_exception:  **  PC 0xa007f894 VADDR 0xa00303bc
```

FYI @lyakh @wszypelt

**Comment by kv2019i** [comment]
Fix is identified for Zephyr upstream regression, but I'll mark this PR with DNM until the Zephyr part is merged and we can try again.

**Comment by kv2019i** [comment]
I'll rebase this once https://github.com/thesofproject/sof/pull/9712 is merged.

**Comment by kv2019i** [comment]
New version uploaded:
- dropped the Zephyr update (no longer needed as Zephyr has been upgraded in separate PRs)
- rebased to latest SOF main, no changes to code

**Comment by lgirdwood** [comment]
@wszypelt @lrudyX good to merge ?
@kv2019i can you check LNL, looks like a topology or SW error and unrelated ?

**Comment by kv2019i** [comment]
@lgirdwood Ack, I think the LNL fails are unrelated. I think the BIOS update broke this DUT and it's loading the wrong config:
```
Dec 09 13:40:41 ba-lnlm-rvp-sdw-01 kernel: sof-audio-pci-intel-lnl 0000:00:1f.3: error: can't connect DAI alh-copier.SDW2-Playback.0 stream SDW2-Playback
Dec 09 13:40:41 ba-lnlm-rvp-sdw-01 kernel: sof-audio-pci-intel-lnl 0000:00:1f.3: failed to add widget type 27 name : alh-copier.SDW2-Playback.0 stream SDW2-Playback
```

**Review by lyakh — APPROVED** [review]

**Comment by wszypelt** [comment]
@kv2019i @lgirdwood Internal Intel CI System, all green

**Pull request merged**
