### PR TITLE
xtensa-build-zephyr.py: cleanup and re-organize to prepare for installing more files

### PR DESCRIPTION
**Pull request by marc-hb**
This is preparing the addition of zephyr.elf, zephyr.lst and possibly other files to `build-sof-staging`. For now this PR should make no difference, the purpose is to make the actual addition much smaller and easier to review and to find any bugs in this one _before_ the actual change.

No difference except maybe one small bugfix in the final "tree" listing - depending on whether pathlib.glob(**/*) was ever random and where.

This also makes `pylint xtensa-build-zephyr.py` finally usable.

### CODE REVIEW

**Review by kv2019i — APPROVED** [review]

**Comment by marc-hb** [comment]
Only unrelated failure https://sof-ci.01.org/sofpr/PR6437/build1947/devicetest/?model=TGLU_RVP_NOCODEC_IPC4ZPH&testcase=check-sof-logger will be fixed by https://github.com/thesofproject/sof-test/pull/971, everything else green.

**Comment by marc-hb** [comment]
SOFCI TEST

**Comment by marc-hb** [comment]
Unrelated suspend/resume failure in https://sof-ci.01.org/sofpr/PR6437/build2014/devicetest/?model=TGLU_UP_HDA_ZEPHYR&testcase=check-suspend-resume-5 everything else green

**Comment by kv2019i** [comment]
Unrelated failure on DUT suspend/resume (not related to build script cleanup), merging.

**Pull request merged**
