### PR TITLE
topology: add TGL tplg for Max98373 amp and ALC5682 Headset codec

### PR DESCRIPTION
**Pull request by jairaj-arava**
TGL topology for the machine with the below codec configuration:
	Max98373 speaker (I2S), ALC5682 headset codec (I2S),	DMIC, 4 HDMI devices.

### CODE REVIEW

**Comment by sathya-nujella** [comment]
> LGTM
> I see this m4 is almost same with https://github.com/thesofproject/sof/blob/master/tools/topology/sof-tgl-max98357a-rt5682.m4. Maybe we can use a simple ifelse and merge this 2 tplg later?

Thank you @xiulipan . We would like to keep separate files as this tplg needs to be updated with many other pipelines, so keeping it separate will help us. Thanks!

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by xiulipan** [comment]
@lgirdwood The pending status is still pending even after the test is done.
Please check the deatils directly. I find the issue to be the GitHub has restriction on description message but we have too many fail device. Thus the GitHub status update always failed.

**Comment by lgirdwood** [comment]
Jenkins known issues.

**Pull request merged**
