### PR TITLE
cherry-pick: topology1: Align DAI format as SSP config to 24-bit for rt1019

### PR DESCRIPTION
**Pull request by johnylin76**
Cherry-picked from main

This commit fixes Speakers audio issue by aligning bitwidth format of DAI config to 24-bit as SSP config, which has been modified by
commit c8fe1927c <topology1: change audio format to 24 bit for rt1019>

### CODE REVIEW

**Review by lgirdwood — APPROVED** [review]
@mwasko topology cherry-pick, should this be for cavs25 branch ?

**Comment by johnylin76** [comment]
> @mwasko topology cherry-pick, should this be for cavs25 branch ?

IMO it should be. This commit is the fix for rt1019-codec topologies.

**Comment by mwasko** [comment]
> > @mwasko topology cherry-pick, should this be for cavs25 branch ?
> 
> IMO it should be. This commit is the fix for rt1019-codec topologies.

I recommend to cherry-pick to cavs25 branch. We are currently only waiting for E2E validation results (delayed due to CNY) to officially announce cavs25.

**Review by kv2019i — APPROVED** [review]

**Comment by johnylin76** [comment]
> > > @mwasko topology cherry-pick, should this be for cavs25 branch ?
> > 
> > 
> > IMO it should be. This commit is the fix for rt1019-codec topologies.
> 
> I recommend to cherry-pick to cavs25 branch. We are currently only waiting for E2E validation results (delayed due to CNY) to officially announce cavs25.

cherry-picked and merged on cavs2.5 (#7031). Could this PR be merged now? @mwasko

**Pull request merged**
