### PR TITLE
platform: ace: enable Zephyr counter drivers

### PR DESCRIPTION
**Pull request by abonislawski**
This will allow to build and enable ace art and rtc counter drivers

Required patch:

- [x] https://github.com/zephyrproject-rtos/zephyr/pull/54789

### CODE REVIEW

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
@juimonen I assume good for you ?

**Review by marcinszkudlinski — APPROVED** [review]

**Review by kv2019i — APPROVED** [review]
Change looks good. We'd probably need some "waiting-for-dependencies" flag/label to help track these faster.

**Comment by lgirdwood** [comment]
@abonislawski @kv2019i I assume we need a west Zephyr sync to test with CI ?

**Comment by kv2019i** [comment]
@abonislawski The dependency is now being pulled into to SOF in https://github.com/thesofproject/sof/pull/6939/

**Comment by lgirdwood** [comment]
@kv2019i #6939 now merged

**Comment by abonislawski** [comment]
Internal CI is fine after rebuild

**Comment by lgirdwood** [comment]
> Internal CI is fine after rebuild

Lets also retest E2E with Linux driver.

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by lgirdwood** [comment]
@abonislawski conflicts.

**Review by tmleman — APPROVED** [review]

**Review by dnikodem — APPROVED** [review]

**Pull request merged**
