### PR TITLE
west.yml: update Zephyr to ca3310145f8f

### PR DESCRIPTION
**Pull request by iuliana-prodan**
Contains 1131 commits, including the NXP hal update.

### CODE REVIEW

**Review by dbaluta — APPROVED** [review]

**Comment by dbaluta** [comment]
@lgirdwood can you help us merge this? Without it our internal CI cannot run and we are very close.to an internal milestone.

**Comment by tmleman** [comment]
It has the same [problems](https://sof-ci.01.org/sofpr/PR8264/build13486/devicetest/index.html) as [mine](https://github.com/thesofproject/sof/pull/8182).

Maybe with a smaller jump in zephyr revision it will work? https://github.com/thesofproject/sof/pull/8268
I don't know how long it will take to resolve issue in our CI.

**Comment by iuliana-prodan** [comment]
> It has the same [problems](https://sof-ci.01.org/sofpr/PR8264/build13486/devicetest/index.html) as [mine](https://github.com/thesofproject/sof/pull/8182).
> 
> Maybe with a smaller jump in zephyr revision it will work? #8268 

We need this commit 492517b918 ("west.yml: Update NXP HAL SDK to 2.14") in Zephyr, so #8268 is good for our internal CI.

**Comment by dbaluta** [comment]
So, with a smaller jump like #8268 the CI will pass? We ca use that so that we get our zephyr version updated?

**Comment by tmleman** [comment]
> So, with a smaller jump like #8268 the CI will pass? We can use that so that we get our zephyr version updated?

There are other problems but not as serious.

**Comment by iuliana-prodan** [comment]
> > So, with a smaller jump like #8268 the CI will pass? We can use that so that we get our zephyr version updated?
> 
> There are other problems but not as serious.

I'll close this as soon as https://github.com/thesofproject/sof/pull/8268 is merged.

**Comment by iuliana-prodan** [comment]
https://github.com/thesofproject/sof/pull/8268

**Pull request closed without merging**
