### PR TITLE
Rename codec_adapter to module_adapter

### PR DESCRIPTION
**Pull request by ranj063**
Just a whole lot of renames. No functional changes.

### CODE REVIEW

**Comment by ranj063** [comment]
@dbaluta @kkarask Please note that the kconfig menu has changes to COMP_MODULE_ADAPTER with this PR.

**Comment by keqiaozhang** [comment]
SOFCI TEST

**Review by kv2019i — APPROVED** [review]
That has been some work to split this into small patches. But easy to review this way. I'd have been happy with one big patch as well.

**Review by dbaluta — APPROVED** [review]

**Review by paulstelian97 — APPROVED** [review]

**Review by dbaluta — CHANGES_REQUESTED** [review]
This looks good to me, but I prefer to have the renaming done after my dynamic codec patches are in. 

See:
https://github.com/thesofproject/sof/pull/5596

**Comment by ranj063** [comment]
> There is a need to change build file. We should sync to adjust this change to CI process.

@kkarask can you please change the QB CI to use the new config CONFIG_MODULE_ADAPTER instead of CONFIG_CODEC_ADAPTER. It will be needed for this PR to pass.

**Comment by kkarask** [comment]
I will be ready today - is it ok?

**Review by dbaluta — APPROVED** [review]

**Comment by ranj063** [comment]
> I will be ready today - is it ok?

@kkarask sure, let me know if you have any other issues with this PR

**Comment by lgirdwood** [comment]
@dbaluta does this mean you are OK to merge whilst part 2 of your coded work is testing ? Just clarifying.

**Comment by sys-pt1s** [comment]
Can one of the admins verify this patch?

**Comment by wszypelt** [comment]
@ranj063 @sys-pt1s @lgirdwood 
We ran the first tests, unfortunately the problem is probably still here:
image

Because we have errors with the file not found

**Comment by ranj063** [comment]
> Because we have errors with the file not found

@wszypelt what is the error you're seeing? Can you please paste the error log ? Is it during build?

**Review by cujomalainey — APPROVED** [review]

**Comment by dbaluta** [comment]
> @dbaluta does this mean you are OK to merge whilst part 2 of your coded work is testing ? Just clarifying.

@lgirdwood lets wait a little bit more time until we merge this PR. part 2 of my codec work has a problem with Intel internal tests and I will try to debug it but it will take a while.

Also, since @ranj063 is not in the office this week I don't think would be a problem to wait a little bit until we merge this current PR.

**Comment by wszypelt** [comment]
@ranj063 
```
13:46:15,096 INFO  - In file included from /quickbuild/workspace1/24733/SOF_FW/src/audio/module_adapter/module_adapter.c:16:
13:46:15,096 INFO  - /quickbuild/workspace1/24733/SOF_FW/src/include/sof/audio/module_adapter/module_adapter.h:11:52: error: sof/audio/codec_adapter/module/generic.h: No such file or directory
13:46:15,100 INFO  - CMakeFiles/sof.dir/build.make:995: recipe for target 'CMakeFiles/sof.dir/src/audio/module_adapter/module_adapter.c.o' failed
13:46:15,100 INFO  - make[3]: *** [CMakeFiles/sof.dir/src/audio/module_adapter/module_adapter.c.o] Error 2
```

**Comment by ranj063** [comment]
> src/include/sof/audio/module_adapter/module_adapter.h

@wszypelt I have fixed the above error. Could you please try again?

**Comment by wszypelt** [comment]
@ranj063 Sure, I will check it today

**Comment by lgirdwood** [comment]
@ranj063 part 3 now merged so this PR is next.

**Comment by ranj063** [comment]
> @ranj063 part 3 now merged so this PR is next.

@lgirdwood conflicts fixed now. @wszypelt could you please update the config in QB and retry this one?

**Review by dbaluta — APPROVED** [review]

**Comment by lgirdwood** [comment]
@ranj063 can you check CI. Thanks !

**Comment by ranj063** [comment]
> @ranj063 can you check CI. Thanks !

Sure. I cant seem to load any of them but its also quite surprising the regular tests fail. This PR doesnt touch anything outside of the codec_adapter. @wszypelt any ideas?

**Comment by lgirdwood** [comment]
> > @ranj063 can you check CI. Thanks !
> 
> Sure. I cant seem to load any of them but its also quite surprising the regular tests fail. This PR doesnt touch anything outside of the codec_adapter. @wszypelt any ideas?

Could be the DUT needing a reboot ? @wszypelt good to merge ?

**Comment by wszypelt** [comment]
@lgirdwood @ranj063  Yes, one of the DUTs needed a reset, PR is under testing. there should be results soon.

**Comment by wszypelt** [comment]
@ranj063 @lgirdwood I don't really understand what happened, do we no longer need a configuration file change to get the codec build to work? (COMP_MODULE_ADAPTER) Even if, as you can see there was a problem with ipc error -22 on codec tests.

**Comment by ranj063** [comment]
> @ranj063 @lgirdwood I don't really understand what happened, do we no longer need a configuration file change to get the codec build to work? (COMP_MODULE_ADAPTER) Even if, as you can see there was a problem with ipc error -22 on codec tests.

@wszypelt yes, you do need a configuration change when building to include COMP_MODULE_ADAPTER and CADENCE_CODEC selected. Could you please send me the config from your build?

**Comment by wszypelt** [comment]
@ranj063 Unfortunately, the changes can be made together with the team from the internal service, additionally I'm now on ooo, back to work at Wednesday

**Review by dbaluta — APPROVED** [review]

**Comment by dbaluta** [comment]
@ranj063 thanks! Looks good to me.

**Comment by lgirdwood** [comment]
@wszypelt any ETA on CI updates ?

**Comment by wszypelt** [comment]
@lgirdwood The case was reported and explained, I am waiting for a move from the internal service, I hope that everything will be done within an hour.

**Pull request merged**
