### PR TITLE
topology: cht-max98090 add missing virtual widgets

### PR DESCRIPTION
**Pull request by cujomalainey**
Topology will fail to probe without these widgets

Signed-off-by: Curtis Malainey <cujomalainey@google.com>

### CODE REVIEW

**Comment by plbossart** [comment]
> @cujomalainey the change itself looks fine but what do you mean by "topology will fail to probe". Previously, we've added virtual widgets only to suppress errors ugh(harmless though) due to the widgets added in the machine driver.

wondering if the recent changes from Morimoto-san treat bad routes using non-existent widgets as errors. I think we saw this for HDaudio/iDISP as well.

**Comment by ranj063** [comment]
> wondering if the recent changes from Morimoto-san treat bad routes using non-existent widgets as errors. I think we saw this for HDaudio/iDISP as well.

@plbossart I've reviewed every one of his patches lately but cant recollect anything that touches non-existent widgets. I can remove the virtual widgets from our topology for iDisp and see whats going on

**Comment by plbossart** [comment]
On 9/18/19 6:43 PM, Ranjani Sridharan wrote:
>     wondering if the recent changes from Morimoto-san treat bad routes
>     using non-existent widgets as errors. I think we saw this for
>     HDaudio/iDISP as well.
> 
> @plbossart <https://github.com/plbossart> I've reviewed every one of his 
> patches lately but cant recollect anything that touches non-existent 
> widgets. I can remove the virtual widgets from our topology for iDisp 
> and see whats going on

There's one where if the route_add fails then it's now an error.

**Comment by plbossart** [comment]
for iDISP the kernel patch that cause the error was (' ASoC: soc-core: tidyup for snd_soc_dapm_add_routes()')

**Comment by cujomalainey** [comment]
@ranj063 these are the failures I am seeing on ToT
```
[   36.507756] cht-bsw-max98090 cht-bsw-max98090: snd-soc-dummy-dai <-> Low Latency 0 mapping ok
[   36.507821] cht-bsw-max98090 cht-bsw-max98090: ASoC: no source widget found for ssp2 Tx
[   36.507827] cht-bsw-max98090 cht-bsw-max98090: ASoC: Failed to add route ssp2 Tx -> direct -> HiFi Playback
[   36.507834] cht-bsw-max98090 cht-bsw-max98090: ASoC: no sink widget found for ssp2 Tx
[   36.507839] cht-bsw-max98090 cht-bsw-max98090: ASoC: Failed to add route codec_out0 -> direct -> ssp2 Tx
[   36.507845] cht-bsw-max98090 cht-bsw-max98090: ASoC: no sink widget found for ssp2 Tx
[   36.507850] cht-bsw-max98090 cht-bsw-max98090: ASoC: Failed to add route codec_out1 -> direct -> ssp2 Tx
[   36.507856] cht-bsw-max98090 cht-bsw-max98090: ASoC: no source widget found for ssp2 Rx
[   36.507861] cht-bsw-max98090 cht-bsw-max98090: ASoC: Failed to add route ssp2 Rx -> direct -> codec_in0
[   36.507868] cht-bsw-max98090 cht-bsw-max98090: ASoC: no source widget found for ssp2 Rx
[   36.507872] cht-bsw-max98090 cht-bsw-max98090: ASoC: Failed to add route ssp2 Rx -> direct -> codec_in1
[   36.507879] cht-bsw-max98090 cht-bsw-max98090: ASoC: no sink widget found for ssp2 Rx
[   36.507883] cht-bsw-max98090 cht-bsw-max98090: ASoC: Failed to add route HiFi Capture -> direct -> ssp2 Rx
[   36.508180] cht-bsw-max98090 cht-bsw-max98090: snd_soc_register_card failed -19
[```

**Pull request merged**
