### PR TITLE
smart amp: Added Maxim DSM static library

### PR DESCRIPTION
**Pull request by ryans-lee**
Maxim Dynamic Speaker Management Library is added.
- License information can be found in LICENSE.dsm
- Usage information can be found in README.dsm

Signed-off-by: Ryan Lee <ryans.lee@maximintegrated.com>

### CODE REVIEW

**Comment by ryans-lee** [comment]
This PR is separate from [3373](https://github.com/thesofproject/sof/pull/3373)

**Review by mwasko — CHANGES_REQUESTED** [review]
I am not sure if the Sound Open Firmware master branch is the right place for proprietary closed source library.

**Comment by paulstelian97** [comment]
> I am not sure if the Sound Open Firmware master branch is the right place for proprietary closed source library.

+1 on that, what if someone else wants to use another proprietary library and they have incompatible licenses? That's a big nope.

I think you can do that on platform-specific release branches though, those with full control over the platform can add such libraries if they have the rights to distribute the binaries like that.

**Comment by lgirdwood** [comment]
> > I am not sure if the Sound Open Firmware master branch is the right place for proprietary closed source library.
> 

This is allowed providing the binary license does not impose any additional restrictions on the users (and this one does impose new restrictions - it's under review and I'll be commenting more shortly).

> +1 on that, what if someone else wants to use another proprietary library and they have incompatible licenses? That's a big nope.

Agree, the license is key here and NOT whether the feature is binary.

> 
> I think you can do that on platform-specific release branches though, those with full control over the platform can add such libraries if they have the rights to distribute the binaries like that.

Yes, I would agree here too where we have binaries that can impose some incompatible restrictions, these would be penalised by only being merged in a product branch.

**Comment by marc-hb** [comment]
There is a LICENCE file at the top of the sof tree right now: https://github.com/thesofproject/sof/blob/master/LICENCE
I (naively?) assumed this file was valid for the entire git repo. I would find it very inconvenient to have license "surprises" buried 4 directories level down.

The Zephyr project has a multi-repo tool to help keep a clear licence picture:
https://docs.zephyrproject.org/latest/guides/west/why.html#multiple-git-repositories
> Zephyr intends to provide all required building blocks needed to deploy complex IoT applications. This in turn means that the Zephyr project is much more than an RTOS kernel, and is instead a collection of components that work together. In this context, there are a few reasons to work with multiple Git repositories in a standardized manner within the project:

- Clean separation of Zephyr original code and imported projects and libraries
- Avoidance of license incompatibilities between original and imported code
- Reduction in size and scope of the core Zephyr codebase, with additional repositories containing optional components instead of being imported directly into the tree
- Safety and security certifications
- Enforcement of modularization of the components
- Out-of-tree development based on subsets of the supported boards and SoCs

**Comment by jajanusz** [comment]
I would go against adding any static libs to the repo.
Cannot we just create nice mechanism for external modules? We don't need dynamic loading for that (like in kernel ext modules) we can add a way to merge code+static libs into sof binary and components made like that can register/init themselves independently in the similar way to how our components do it already (with `DECLARE_MODULE`).

**Comment by marc-hb** [comment]
> I would go against adding any static libs to the repo.

BTW I'm curious whether the different toolchains and toolchain versions supported by SOF are compatible with each other. This is a frequent issue in C (and even more in C++). Some compiler flags are even enough to break compatibility.

**Comment by lgirdwood** [comment]
> > I would go against adding any static libs to the repo.
> 
> BTW I'm curious whether the different toolchains and toolchain versions supported by SOF are compatible with each other. This is a frequent issue in C (and even more in C++). Some compiler flags are even enough to break compatibility.

I'm 90% sure GCC and xcc wont be, IIRC calling convention may be different. CC flags will also likely break stuff, especially due to code generation for the different ISAs (they are not trapped and will result in a panic).

**Comment by lgirdwood** [comment]
@ryans-lee it looks like we are safer using the sof-bin repo for binary blobs (given the license differences). I'll be in touch when we have this worked out.

**Comment by ryans-lee** [comment]
> @ryans-lee it looks like we are safer using the sof-bin repo for binary blobs (given the license differences). I'll be in touch when we have this worked out.

@lgirdwood Understood. Thank for your support.

**Comment by lgirdwood** [comment]
@ryans-lee fwiw @xiulipan is working on the sof-bin repo now. 
@xiulipan at top level sof-bin can you create a 
```sof/module/maxim``` 
directory. This can be where the DSM library can go.
@ryans-lee you should be able to put your LICENCE file at the top level, but please wait until @xiulipan has created the v1.6 branch. We can then update the SOF CMakeFile to link to DSM in the sof-bin repo.

**Pull request closed without merging**
