### PR TITLE
Topology: EQ IIR: Allow capture with all formats with pipe-eq-capture

### PR DESCRIPTION
**Pull request by singalsu**
This patch adds to IIR EQ capability to convert from s32 source
to s16/s24/s32 sink formats in normal PCM samples
equalization. The feature is useful in microphone equalization
where input dynamic range is high but where pipeline needs to be
lower word length. A typical IIR high-pass response when combined
with gain will reduce the dynamic range by suppressing lowest
frequencies from signal to better fit the smaller sample word
length.
    
The PCM capability in topology macro pipe-eq-capture.m4 is
changed to allow the s16/s24/s32 formats.
    
The patch also includes 4096 bytes increase to SOF_TEXT_SIZE for
CNL platform.
    
Signed-off-by: Seppo Ingalsuo <seppo.ingalsuo@linux.intel.com>

### CODE REVIEW

**Comment by singalsu** [comment]
Update: I improved the commit message to better describe why this change is proposed. It's also an improvement option for future to use DMIC for 16 bit capture. The high-pass and gain provides better SNR for speech than raw 16 bit capture with DMIC.

**Comment by singalsu** [comment]
Update 2: I just fixed some strange accented l character in the commit message title.

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by ranj063** [comment]
@singalse LGTM

**Comment by lgirdwood** [comment]
@singalsu can you re-check CI failure.

**Comment by singalsu** [comment]
The error is about growth of the .text section

`/localdisk/tools/xtensa/RF-2016.4-linux/XtensaTools/bin/xt-ld: sof section `.text' will not fit in region `sof_text'`

I'll see if I can repeat this.

**Comment by singalsu** [comment]
I increased in the updated version CNL platform SOF_TEXT_SIZE to avoid the build fail with it. I don't know why the (x - y + z) arithmetic is called out in the macro but I increased "z" by 4096.

**Pull request merged**
