### PR TITLE
Fix DSP_A mode

### PR DESCRIPTION
**Pull request by bkokoszx**
Refinement and fix for DSP_A and I2S. We don't have to use SSPSP_STRTDLY(start_delay) macro to distinguish DSP_A - DSP_B and I2S - LEFT_J modes. We can only set FSRT flag in SSPSP to set delay between frame sync and data. Frame Sync Relative Timing (FSRT) bit says:
0: Data starts the same with frame sync
1: Data starts 1 clock after frame sync (Normal Mode)

### CODE REVIEW

**Comment by bkokoszx** [comment]
@plbossart With Wojciech we've tested that fix for DSP_A in master/slave mode (also we've tested LEFT_J and I2S modes) - they are correct.
In slave/master tests there is still problem with 24/32 format with tdm_per_slot_padding_flag set to 1 (simple playback tests with that configuration are ok).

**Comment by plbossart** [comment]
@lrgirdwo the change are fine, it's what I had in mind.
@bkokoszx are you saying the slave mode only works with this fix? If yes @keqiaozhang can you retest with the AP setup.

**Comment by bkokoszx** [comment]
@plbossart slave with DSP_A mode. DSP_B works fine also without this fix (I think the problem was setting SSPSP_STRTDLY and FSRT together).

**Comment by plbossart** [comment]
@lrgirdwo why not merge in master? This fixes a commit for DSP_A done a couple of weeks back.

**Comment by lgirdwood** [comment]
@bkokoszx can you send a PR for this into master too. Please cherry-pick to preserve commit ID.

**Comment by keqiaozhang** [comment]
I tested the latest gp20-alpha-drop-stable branch on UP^2, but failed to load sof-apl-nocodec.tplg. 
but it works on GP, tplg can load with tdf8532 and audio works well.
rmbox -t:
0xce0 [0.095606]        delta [0.000007]        host new
0xcf0 [0.095611]        delta [0.000005]        mem eMm
0xd00 [0.095613]        delta [0.000002]        value 0x0000000000000100
0xd10 [0.095614]        delta [0.000001]        value 0x0000000000000001
0xd20 [0.095617]        delta [0.000003]        comp eCN
0xd30 [0.095618]        delta [0.000001]        ipc eCn
dmesg:
[    6.045542] sof-audio sof-audio: error: ipc error for 0x30010000 size 0x14
[    6.045552] sof-audio sof-audio: error: DSP failed to add widget id 0 type 23 name : PCM5P stream Passthrough Playback 5 reply -22
[    6.045556] sof-audio sof-audio: ASoC: failed to load widget PCM5P
[    6.045560] sof-audio sof-audio: error: tplg component load failed -22
[    6.045574] sof-audio sof-audio: error: failed to load DSP topology -22
[    6.045577] sof-audio sof-audio: ASoC: failed to probe component -22
[    6.045589] sof-nocodec sof-nocodec: ASoC: failed to instantiate card -22
[dmesg.log](https://github.com/thesofproject/sof/files/2308670/dmesg.log)
[rmbox-t.log](https://github.com/thesofproject/sof/files/2308671/rmbox-t.log)

**Comment by keqiaozhang** [comment]
@plbossart @lgirdwood 
Retested the ssp salve mode with AP on UP^2, both playback and capture work well when clock is alive from AP，I also checked the loopback on SSP5, the waveform is quite clean.
Test env:
sof-dev: up to date-c465461
sof-master: up to date-83ed9f
soft-master: up to date-53e8c47(changed the codec to master mode)

**Comment by plbossart** [comment]
this is good news. @keqiaozhang can you test all the modes (I2S, LEFT_J, DSP_A, DSP_B) to make sure we have 100% coverage.
Also can your AP generate a bitclock but not the frame sync (to test CBM_CFS). Likewise for CBS_CFM, this is not tested atm.

**Pull request merged**
