### PR TITLE
 DSP clock switching refining

### PR DESCRIPTION
**Pull request by keyonjie**
1. add notification event for the clock switching.
2. use the event to notify KPB to start draining.

### CODE REVIEW

**Comment by keyonjie** [comment]
we have 2 place to ask for clock switching, here the KPB draining part is done to make sure there is no race/possibility to run the subsequent task with a uncertain clock, maybe worth to add similar logic for the PM_GATE IPC if we are aligned on this.

**Comment by mwasko** [comment]
The refinement will not address the scenario when pm runtime request will arrive once the KD draining task has already been started. That is why additional mechanism is required to prevent pm runtime enable during draining.

**Review by lgirdwood — CHANGES_REQUESTED** [review]
We should really have a
```c
kpb_drain_start()
{
    pm_runtime_get(DSP_CLOCK, PLATFORM_KPB_MIN_CLOCK);
    // do the drain
}

kpb_drain_complete()
{
    // drain is done
    pm_runtime_put(DSP_CLOCK, PLATFORM_KPB_MIN_CLOCK);
}
```
This way any IPC request from kernel is dealt with via a ```-EBUSY``` and each platform has a required frequency defined for KPB clock.

**Comment by keyonjie** [comment]
@lgirdwood the point is that the get/put will not really change the clock immediately, the clock switching will happen at the next WFI.

**Comment by lgirdwood** [comment]
> @lgirdwood the point is that the get/put will not really change the clock immediately, the clock switching will happen at the next WFI.

Why not ? can the clock only be changed during WFI ? if so, we need
```
1) set CCOUNT timer IRQ for short time from now
2) set clock to X
3) eneter WFI
4) IRQ from CCOUNT timer in 1 wakes us.
5) Kpb can drain 
```

**Comment by keyonjie** [comment]
let me close this one, will submit new one to the master branch.

**Comment by keyonjie** [comment]
The one for master branch is here: https://github.com/thesofproject/sof/pull/3773
closing this one...

**Pull request closed without merging**
