### PR TITLE
topology: sdw: fix dmic issue on tgl sdw platforms

### PR DESCRIPTION
**Pull request by RanderWang**
Port commit a716056 ("tgl: use additional CHANNEL
define in rt711 + rts1308 tplg") to all tgl sdw platforms

Signed-off-by: Rander Wang <rander.wang@intel.com>

### CODE REVIEW

**Comment by RanderWang** [comment]
@ClarexZhou  this is for DMIC issue

**Comment by RanderWang** [comment]
> how does the kernel select the 2 or 4ch topology? we currently don't have any mechanism to do so.
we need to select the correct topology and remove the postfix of 2ch & 4ch.

**Comment by plbossart** [comment]
> > how does the kernel select the 2 or 4ch topology? we currently don't have any mechanism to do so.
> > we need to select the correct topology and remove the postfix of 2ch & 4ch.



> > how does the kernel select the 2 or 4ch topology? we currently don't have any mechanism to do so.
> > we need to select the correct topology and remove the postfix of 2ch & 4ch.

Oh man, that's really hard to maintain with a build that can support multiple options.

**Comment by RanderWang** [comment]
> > > how does the kernel select the 2 or 4ch topology? we currently don't have any mechanism to do so.
> > > we need to select the correct topology and remove the postfix of 2ch & 4ch.
> 
> > > how does the kernel select the 2 or 4ch topology? we currently don't have any mechanism to do so.
> > > we need to select the correct topology and remove the postfix of 2ch & 4ch.
> 
> Oh man, that's really hard to maintain with a build that can support multiple options.

@plbossart  Actually I investigated this issue in kernel driver. We can check NHLT table but is it supported by coreboot ? Second now all NHLT related function are encapsulated by CONFIG_SND_SOC_SOF_HDA and the intel-nhlt.c is included in sound/hda. It is not suitable for SSP + DMIC only case.

**Pull request merged**
