### PR TITLE
[DEMO] new elf-size-range.py to monitor ELF sections sizes

### PR DESCRIPTION
**Pull request by marc-hb**
[transferred from `master` PR #3459, see previous discussions there]

This is a _demo_ to start a discussion following yet another
linking size issue in #3452:

  RD-2012.5-linux/XtensaTools/bin/xt-ld:
    sof section `.text' will not fit in region `sof_text_start'

Do _not_ waste your time reviewing code style details yet, not before
the high-level approach has been discussed and agreed. This is just to
show what's possible in less than 75 lines of Python.

The purpose of this script is to address situations like this one:

Maximum size before the linker breaks is say 80,000 bytes

- Developer A adds new feature which increases usage from 70,000 bytes
  to 79,800 bytes. No one notices.
- One month later, developer B submits a small and urgent fix which
  requires 300 extra bytes and that can't be merged because it goes over
  the limit and breaks the build.

This commit implements two "soft limit", optional features to address
this issue. They can catch developer A red-handed LONG before the linker
fails.  If needed, the soft limits can be raised and/or a new Kconfig
created but all only after code review and discussion.

1. Relative limit: compare ELF section sizes with a reference (e.g.:
nightly) build + some max_increase tolerance to allow minor fixes and
other small changes.

2. Absolute limits to stop "feature creep" of multiple minor changes
under max_increase tolerance.

For completeness the implementation also supports "min" values so
anything that reduces code size (compiler flags, compiler versions,
heroes,...) can be flagged too. When they get noticed, soft limits can
be brought down.

Signed-off-by: Marc Herbert <marc.herbert@intel.com>

### CODE REVIEW

**Review by lgirdwood — COMMENTED** [review]
Can you show the output of the script here. Thanks

**Comment by marc-hb** [comment]
Disclaimer: I don't have time to work on this right now. I just re-opened this after the deletion of the `master` branch. It's a draft; please ignore drafts thanks to `draft:false` when listing pull requests.

> Can you show the output of the script here. Thanks

From https://travis-ci.org/github/thesofproject/sof/jobs/731781130

```
-------- ELF size DEMO 1 --------
+ /home/sof/work/sof.git/scripts/elf-size-range.py -r /home/sof/work/sof.git/sof_nightly_build_pretend sof
Checking section .text relative size compared to reference +/- deltas: 79409 < 79601 + 100
Checking section .bss relative size compared to reference +/- deltas: 15960 < 15960 + 100
Checking section .data relative size compared to reference +/- deltas: 3576 < 3344 + 100
FAIL: 3576 > 3444

 -------- ELF size DEMO 2 --------
+ /home/sof/work/sof.git/scripts/elf-size-range.py -r /home/sof/work/sof.git/sof_nightly_build_pretend -l /home/sof/work/sof.git/src/platform/cht_limits.conf sof
Checking section .text size is within absolute limit(s): None < 79409 < 79000
FAIL: 79409 > 79000
Checking section .text relative size compared to reference +/- deltas: 79409 < 79601 + 200
FAIL: Section '.bogus' not found in sof
Checking section .bss size is within absolute limit(s): 15000 < 15960 < 16000
Checking section .data size is within absolute limit(s): 3400 < 3576 < 3600
Checking section .data relative size compared to reference +/- deltas: 3344 - 100 < 3576 < 3344 + 200
FAIL: 3576 > 3544
```

**Comment by lgirdwood** [comment]
> Disclaimer: I don't have time to work on this right now. I just re-opened this after the deletion of the `master` branch. It's a draft; please ignore drafts thanks to `draft:false` when listing pull requests.
> 
> > Can you show the output of the script here. Thanks
> 
> From https://travis-ci.org/github/thesofproject/sof/jobs/731781130
> 
> ```
> -------- ELF size DEMO 1 --------
> + /home/sof/work/sof.git/scripts/elf-size-range.py -r /home/sof/work/sof.git/sof_nightly_build_pretend sof
> Checking section .text relative size compared to reference +/- deltas: 79409 < 79601 + 100
> Checking section .bss relative size compared to reference +/- deltas: 15960 < 15960 + 100
> Checking section .data relative size compared to reference +/- deltas: 3576 < 3344 + 100
> FAIL: 3576 > 3444
> 
>  -------- ELF size DEMO 2 --------
> + /home/sof/work/sof.git/scripts/elf-size-range.py -r /home/sof/work/sof.git/sof_nightly_build_pretend -l /home/sof/work/sof.git/src/platform/cht_limits.conf sof
> Checking section .text size is within absolute limit(s): None < 79409 < 79000
> FAIL: 79409 > 79000
> Checking section .text relative size compared to reference +/- deltas: 79409 < 79601 + 200
> FAIL: Section '.bogus' not found in sof
> Checking section .bss size is within absolute limit(s): 15000 < 15960 < 16000
> Checking section .data size is within absolute limit(s): 3400 < 3576 < 3600
> Checking section .data relative size compared to reference +/- deltas: 3344 - 100 < 3576 < 3344 + 200
> FAIL: 3576 > 3544
> ```

Thanks @marc-hb . When time permits this looks good to integrate. It would also be good to include an ordered list (using nm) of all the text, data, rodata sections when the issue is reported.

**Comment by kv2019i** [comment]
@marc-hb Over a year without activity, still open?

**Comment by marc-hb** [comment]
Would still be useful for XTOS but I think Zephyr already has tools to do this, I've spotted something named like this in Zephyr CI.

PS: ignore drafts with `draft:false`

**Pull request closed without merging**
