### PR TITLE
west.yml: update Zephyr to 2f90ef488a4e

### PR DESCRIPTION
**Pull request by kv2019i**
Contains 75+ commits, including following directly affecting SOF targets:

f0fd9f171342 drivers: hda: insert an empty ";" statement before switch() labels

### CODE REVIEW

**Comment by kv2019i** [comment]
This should fix the most-recent new sparse warning. Let's see the results...

**Comment by kv2019i** [comment]
... and sparse is good.

**Comment by marc-hb** [comment]
Harmless checkpatch warnings in https://github.com/thesofproject/sof/actions/runs/6076032638/job/16483352908?pr=8147

The failures in https://sof-ci.01.org/sofpr/PR8147/build12545/devicetest and https://sof-ci.01.org/sofpr/PR8147/build12546/devicetest are few and seem unfortunately intermittent and common but re-running to make sure.

**Comment by marc-hb** [comment]
SOFCI TEST

**Review by marc-hb — APPROVED** [review]
After re-run cavs2.5 https://sof-ci.01.org/sofpr/PR8147/build12594/devicetest is all green and MTL has only 2 suspend/resume failures.

Good to go.

**Review by ranj063 — APPROVED** [review]

**Pull request merged**
