### PR TITLE
Stabilize Fuzzer

### PR DESCRIPTION
**Pull request by cujomalainey**
These functions complete enabling the base framework for the oss-fuzz fuzzer to run on. This allows libfuzzer to hammer the ipc_cmd with bad date to find bugs and vulnerabilities.

TODO
* Enable audio components - blocked by #3617
* Stub out timers, dai, dma
* refactor testbench linking of audio components, also blocked by #3617
* Fix clang markers #3612

Once this lands and I acquire seed corpus for the IPC i can enable builds upstream and automated fuzzing can begin

### CODE REVIEW

**Review by singalsu — APPROVED** [review]
Looks good, thanks!

**Review by lgirdwood — APPROVED** [review]

**Comment by cujomalainey** [comment]
Seed corpus acquired, will upload in another PR

**Comment by cujomalainey** [comment]
correction, added to this PR

**Comment by lgirdwood** [comment]
CI showing a docker timeout.

**Review by lgirdwood — APPROVED** [review]

**Pull request merged**
