### PR TITLE
Workaround for alsatplg hardcoded permissions

### PR DESCRIPTION
**Pull request by marc-hb**
Workaround for bug alsa-project/alsa-utils#126

~DRAFT until dependency and bug fix #5071 is merged, must be rebased on top of #5071~ Rebased.

### CODE REVIEW

**Comment by marc-hb** [comment]
sof/jenkins is down this weekend, will have to SOFCI TEST

**Comment by marc-hb** [comment]
CML not available in https://sof-ci.01.org/sofpr/PR5072/build11350/devicetest/, everything else green.

**Comment by lgirdwood** [comment]
@marc-hb this looks like it contains the same topology build move patch as your other PR ? #5071 is merged.

**Comment by marc-hb** [comment]
> @marc-hb this looks like it contains the same topology build move patch as your other PR ? #5071 is merged.

Yes, rebased now. Please don't look at drafts :-)

Non-drafts without review:
https://github.com/thesofproject/sof/pulls?q=is%3Apr+is%3Aopen+review%3Anone+isdraft%3Afalse

**Review by ranj063 — APPROVED** [review]

**Comment by marc-hb** [comment]
https://sof-ci.01.org/sofpr/PR5072/build11359/devicetest is amazingly all green.

qemu-boot-test is failing on some platforms in https://github.com/thesofproject/sof/runs/4508240036?check_suite_focus=true which is very new and very worrying but completely unrelated to a topology build fix.

**Review by lgirdwood — APPROVED** [review]

**Comment by marc-hb** [comment]
Note there has never been any permission issue when using `make -C installer` because it uses `install -D -p -m 0664`

**Comment by marc-hb** [comment]
A heads-up that @ranj063 has been experiencing an extremely weird .tplg file corruption that is solved by reverting this commit, see bug #5113 

We don't plan on doing anything yet because CI has been perfectly happy with this commit for 6 days, I cannot reproduce and no one else has complained either but please keep an eye on any .tplg issues and share any detail in #5113 if relevant.

**Comment by marc-hb** [comment]
Revert submitted in #5132 :-(

**Pull request merged**
