### PR TITLE
rtnr: merge period settings for rtnr back to mt8195/v0.4

### PR DESCRIPTION
**Pull request by MingJenTai**
This PR merges the following modifications of periods settings from main branch to mt8195/v0.4:

8496d585d1cf1ce75a84680de91a9fed92bcf1b6 [Modify periods setting for RTNR capturing pipeline](https://github.com/thesofproject/sof/commit/8496d585d1cf1ce75a84680de91a9fed92bcf1b6) 

1. With the release of RTNR version 20220728, period for capturing pipeline requires at least 5ms.
2. Periods setting for 16KHz capturing pipeline is also removed since RTNR is currently running in 48KHz capturing pipeline only.

### CODE REVIEW

**Review by kuanhsuncheng — APPROVED** [review]

**Review by yaochunhung — APPROVED** [review]

**Comment by lgirdwood** [comment]
@thesofproject/google @thesofproject/mediatek pls feel free to merge and ignore Intel CI

**Comment by marc-hb** [comment]
CI is tested only on the main branch. On other branches anything can happen :-(

**Comment by yaochunhung** [comment]
It is ok for me to merge. @afq984 @Zames-Chang please let us know if you have any concern to merge this PR. Thanks.

**Comment by Zames-Chang** [comment]
I see. LGTM

**Pull request merged**
