### PR TITLE
[DNM] west.yml: Zephyr update Feb14

### PR DESCRIPTION
**Pull request by kv2019i**
Like https://github.com/thesofproject/sof/pull/8864 but we take absolute minimum new stuff from Zephyr.

cc:
- #8818

### CODE REVIEW

**Comment by kv2019i** [comment]
Wrong Zephyr commit, reuploading.

**Comment by marc-hb** [comment]
https://sof-ci.01.org/sofpr/PR8865/build2733/devicetest/index.html and https://sof-ci.01.org/sofpr/PR8865/build2734/devicetest/index.html are not perfect but pretty good.

**Comment by marc-hb** [comment]
@dbaluta , @LaurentiuM1234 there is an IMX compilation failure in
https://github.com/thesofproject/sof/actions/runs/7906600378/job/21581809437?pr=8865

```
/opt/toolchains/zephyr-sdk-0.16.4/xtensa-nxp_imx_adsp_zephyr-elf/bin/../lib/gcc/xtensa-nxp_imx_adsp_zephyr-elf/12.2.0/../../../../xtensa-nxp_imx_adsp_zephyr-elf/bin/ld.bfd: zephyr/zephyr_pre0.elf section `.DoubleExceptionVector.literal' will not fit in region `vector_double_lit'
/opt/toolchains/zephyr-sdk-0.16.4/xtensa-nxp_imx_adsp_zephyr-elf/bin/../lib/gcc/xtensa-nxp_imx_adsp_zephyr-elf/12.2.0/../../../../xtensa-nxp_imx_adsp_zephyr-elf/bin/ld.bfd: section .DoubleExceptionVector.text LMA [00000000596f863c,00000000596f8655] overlaps section .DoubleExceptionVector.literal LMA [00000000596f8638,00000000596f863f]
/opt/toolchains/zephyr-sdk-0.16.4/xtensa-nxp_imx_adsp_zephyr-elf/bin/../lib/gcc/xtensa-nxp_imx_adsp_zephyr-elf/12.2.0/../../../../xtensa-nxp_imx_adsp_zephyr-elf/bin/ld.bfd: region `vector_double_lit' overflowed by 4 bytes
zephyr/arch/arch/xtensa/core/libarch__xtensa__core.a(xtensa_asm2_util.S.obj): in function `_DoubleExceptionVector':
/zep_workspace/zephyr/arch/xtensa/core/xtensa_asm2_util.S:485:(.DoubleExceptionVector.text+0xe): dangerous relocation: windowed longcall crosses 1GB boundary; return may fail: xtensa_fatal_log
collect2: error: ld returned 1 exit status
```

**Comment by dbaluta** [comment]
@marc-hb this is interesting at least. I will have a look on tomorrow I'm just leaving for the day now.

**Comment by iuliana-prodan** [comment]
> @dbaluta , @LaurentiuM1234 there is an IMX compilation failure in https://github.com/thesofproject/sof/actions/runs/7906600378/job/21581809437?pr=8865
> 
> ```
> /opt/toolchains/zephyr-sdk-0.16.4/xtensa-nxp_imx_adsp_zephyr-elf/bin/../lib/gcc/xtensa-nxp_imx_adsp_zephyr-elf/12.2.0/../../../../xtensa-nxp_imx_adsp_zephyr-elf/bin/ld.bfd: zephyr/zephyr_pre0.elf section `.DoubleExceptionVector.literal' will not fit in region `vector_double_lit'
> /opt/toolchains/zephyr-sdk-0.16.4/xtensa-nxp_imx_adsp_zephyr-elf/bin/../lib/gcc/xtensa-nxp_imx_adsp_zephyr-elf/12.2.0/../../../../xtensa-nxp_imx_adsp_zephyr-elf/bin/ld.bfd: section .DoubleExceptionVector.text LMA [00000000596f863c,00000000596f8655] overlaps section .DoubleExceptionVector.literal LMA [00000000596f8638,00000000596f863f]
> /opt/toolchains/zephyr-sdk-0.16.4/xtensa-nxp_imx_adsp_zephyr-elf/bin/../lib/gcc/xtensa-nxp_imx_adsp_zephyr-elf/12.2.0/../../../../xtensa-nxp_imx_adsp_zephyr-elf/bin/ld.bfd: region `vector_double_lit' overflowed by 4 bytes
> zephyr/arch/arch/xtensa/core/libarch__xtensa__core.a(xtensa_asm2_util.S.obj): in function `_DoubleExceptionVector':
> /zep_workspace/zephyr/arch/xtensa/core/xtensa_asm2_util.S:485:(.DoubleExceptionVector.text+0xe): dangerous relocation: windowed longcall crosses 1GB boundary; return may fail: xtensa_fatal_log
> collect2: error: ld returned 1 exit status
> ```


I just tested locally, with SOF/main, just:
```
$ git diff
diff --git a/west.yml b/west.yml
index 37418754d..24459c89a 100644
--- a/west.yml
+++ b/west.yml
@@ -43,7 +43,7 @@ manifest:
 
     - name: zephyr
       repo-path: zephyr
-      revision: 9852e8e15bc8536aa1a49cc2697c1e8f802e331f
+      revision: 2f04a8c91edc41d25d52a1d0f72c20ebd2c068a1
       remote: zephyrproject
 
       # Import some projects listed in zephyr/west.yml@revision
```
which is `zephyr/main` and is all good.

I see in this PR:
```
      revision: 40fa69d5778c3b6f57dde62104644847aa8299fc
      remote: zephyrprojectkv2019i
```
are there any other changes on top of `zephyr/main`?
Probably I should also take the `cpu.c` changes from his PR.

**Comment by marc-hb** [comment]
Sorry for the noise @dbaluta and @iuliana-prodan , I didn't expect that Kai's work in progress could interfere with IMX but now I see that it definitely can.

Thanks for giving it a try - Zephyr is at the RC2 stage right now so it's good timing.

**Comment by kv2019i** [comment]
Stale, closing

**Pull request closed without merging**
