### PR TITLE
Revert "soundwire: initial work"

### PR DESCRIPTION
**Pull request by xiulipan**
Reverts thesofproject/sof#1244

ABI changes in this PR caused a blocking regression now. As no decision is made to update the kernel to align the ABI now. 

Revert and have more discussion is a good option.

### CODE REVIEW

**Comment by xiulipan** [comment]
@plbossart @lgirdwood @tlauda @jajanusz 
Please have some decision and action about the recent blocking regression.
I think a simple revert first and discuss later is a good idea to make other feature and validation continue.

**Comment by jajanusz** [comment]
@xiulipan Please specify what do you mean by regression. All things look like they have no impact on driver that is not even aware of soundwire. We bumped minor version what means it should be backward compatible.

**Comment by xiulipan** [comment]
@jajanusz 
Regression means all platform now is not able to load tplg with the dev branches
https://github.com/thesofproject/linux/issues/822

**Comment by plbossart** [comment]
> NAK, this is a kernel bug. Kernel should not reject minor ABI differences (only reject major ABI differences)

It doesn't help to just close bugs and push the issues under the rug. It's not a minor change and we need a process for ABI changes. I completely disagree with just waving things through on the grounds that things are minor.

**Comment by lgirdwood** [comment]
@plbossart https://github.com/thesofproject/linux/issues/822 is showing only a minor ABI difference unless we are meaning another issue ?

**Comment by plbossart** [comment]
@lgirdwood exactly my point, the PR 822 is showing a minor ABI difference but I don't think it is. The classification looks wrong since by adding a DAI type you can end-up with a configuration that does not work. It's different from a field that gets ignored.
And it didn't have a matching kernel PR so there is still no process to align.

**Pull request closed without merging**
