### PR TITLE
Use DIV_ROUND_UP() macro

### PR DESCRIPTION
**Pull request by caseorum**
Replace some open coding with the new macro

Signed-off-by: Joseph Burt <caseorum@gmail.com>

### CODE REVIEW

**Comment by sofci** [comment]
Can one of the admins verify this patch?

**Comment by caseorum** [comment]
@lgirdwood This is a very tiny change.

**Review by paulstelian97 — APPROVED** [review]

**Review by lgirdwood — APPROVED** [review]
@caseorum thanks, fwiw I think the Linux driver may have a similar calculation.

**Review by cujomalainey — APPROVED** [review]

**Review by plbossart — APPROVED** [review]

**Comment by lgirdwood** [comment]
test this please

**Comment by caseorum** [comment]
@lgirdwood Kernel side, pcm.c already uses uses the PFN_UP() macro and utils.c uses the snd_sgbuf_aligned_pages() function, which are functionally identical.

**Pull request merged**
