### PR TITLE
[RFC][WIP] Drivers: Intel: Add support for NHLT blob based configuration

### PR DESCRIPTION
**Pull request by singalsu**
This patch adds to DMIC driver support for NHLT DMIC blob based
setup. The driver mode is selected in Kconfig. This WIP version
carries the needed part of the blob in the header file
nhlt_dmic_cfg.h. It needs to be replaced by a IPC passed blob. The
hard coded blob can work only in 38.4 MHz rate IOclock devices.

TODO: 2ch device with microphones connection to PDM1 is not handled
correctly. Also the start() and stop() for version 2 and version 3 HW
are not handled properly. A lot of patch code cleanup is needed.

Warning: This the is first apparently working version and bugs are
likely present.

Signed-off-by: Seppo Ingalsuo <seppo.ingalsuo@linux.intel.com>

### CODE REVIEW

**Comment by singalsu** [comment]
@plbossart @ranj063 Hi, here's my work for FW side DMIC driver to support NHLT DMIC blob part. The blob is compiled-in and works only with 2 microphones 38.4 MHz IOclock compatible device (e.g. TGL). I still need to add missing details, test and fix bugs but this should be good enough to start develop IPC for binary data (about 3 kB for max 4ch) and plan how to shrink / replace the current IPC for DAI new().

**Review by lgirdwood — COMMENTED** [review]
This looks like the existing files ? Have they been moved ? (git mv should be used here so that moves are detected).
I would have expected NHLT support to add a blob parser only ?

**Comment by singalsu** [comment]
@lgirdwood I think I need to split the patch to three commits 1) move dmic.c to dmic/dmic.c 2) move parameters based blob computation functions to separate module 3) add NHLT blob parsing module.

I was iterating with the structure and how to handle global bookkeeping of resources so there's more changes done than necessary, e.g. functions order changed after shuffling then around.

**Comment by lgirdwood** [comment]
Please use "main" as PR target.

**Pull request closed without merging**
