### PR TITLE
Update Zephyr to include CONFIG_MODULES support

### PR DESCRIPTION
**Pull request by lyakh**
Update to a Zephyr version, including CONFIG_MODULES support. This is needed for #8180, but is now also a general long overdue Zephyr upgrade

cc:
- #8818

### CODE REVIEW

**Comment by lyakh** [comment]
bisected CI failures on ACE in https://sof-ci.01.org/sofpr/PR8732/build1816/devicetest/index.html?model=MTLP_RVP_NOCODEC&testcase=verify-kernel-boot-log to https://github.com/zephyrproject-rtos/zephyr/pull/67393/commits/e6f35f4f37dcecedcb75cbaece6a5d5df344c258

**Comment by marc-hb** [comment]
> https://github.com/zephyrproject-rtos/zephyr/commit/e6f35f4f37dcecedcb75cbaece6a5d5df344c258

Rebased commit?

**Comment by marc-hb** [comment]
Newer attempt that includes @lyakh 's fix for the DSP panics:
- #8747

**Comment by lgirdwood** [comment]
@lyakh lot of red on the CI, do you think this is the Zephyr upgrade ?

**Comment by lyakh** [comment]
"Internal Intel CI" results look good for both cAVS and ACE, but QB caught a DSP panic...

**Comment by marc-hb** [comment]
Hooray! Some successful Zephyr update at last. I see there are still a couple hacks and the west.yml manifest still points at a personal branch but the latest test results look very promising:

- Only 1 suspend/resume failure in CAVS https://sof-ci.01.org/sofpr/PR8732/build2952/devicetest/index.html, everything else green.

- ACE https://sof-ci.01.org/sofpr/PR8732/build2951/devicetest/index.html is 100% green.

- QB failed but that's only because all runs are failing because of some PUBLISH issue (cc: @lrudyX , @wszypelt ), the tests themselves are all green.
```
09:33:49,529 ERROR - Step 'master>PUBLISH LOGS>GENERATE build.json' is failed:
java.lang.IllegalArgumentException: The provided File object is not a directory: /localdisk/processteam/qba1/workspace/24733/Logs/dwmix/stdout.log
```

**Comment by lyakh** [comment]
SOFCI TEST

**Comment by kv2019i** [comment]
The fails all seem to relate to errors returned by HDA-DMA driver's dma_reload(). I suspect these are now triggered by @lyakh your commit https://github.com/zephyrproject-rtos/zephyr/pull/68945  . That -EIO return is visible in multiple failure case FW logs.

**Comment by kv2019i** [comment]
Excellent, now the mandatory tests are passing! I will mark this with DNM for now, as this points to unmerged Zephyr PRs, and this is not evident in the title. Please remove when ready.

**Comment by marc-hb** [comment]
Superseded by #8903 and others?

**Pull request closed without merging**
