### PR TITLE
[Skip CI] owners: remove departed users

### PR DESCRIPTION
**Pull request by cujomalainey**
Make the codeowners check happy

Signed-off-by: Curtis Malainey <cujomalainey@chromium.org>

### CODE REVIEW

**Review by lgirdwood — APPROVED** [review]
@mwasko @kv2019i need to update Intel users.
@thesofproject/amd @thesofproject/google @thesofproject/nxp @thesofproject/mediatek fyi - if you have any other codeowner cleanup

**Comment by lgirdwood** [comment]
@cujomalainey looks like a conflict with your previous commit.

**Comment by cujomalainey** [comment]
@lgirdwood we should do an org purge before that so we catch any users lingering that might not be relevant. Also I think we should rely on teams over people, but that is just my opinion

**Comment by cujomalainey** [comment]
Also, I have no need to land this, I just wanted to point out the issues

**Review by mwasko — CHANGES_REQUESTED** [review]
By default please replace @mrajwa with @abonislawski as a new codeowner from Intel.

**Comment by marc-hb** [comment]
> By default please replace @mrajwa with @abonislawski as a new codeowner from Intel.

Done in #6949 because this was blocking #6949 (cause the  @mrajwa  account does not exist anymore, I didn't understand this from this PR).

This removal of @mrajwa can be abandoned.

**Pull request closed without merging**
