### PR TITLE
topology: Add support for buffer flags

### PR DESCRIPTION
**Pull request by cujomalainey**
Flags have been a part of IPC3 for ages, add support for them in the topology.

### CODE REVIEW

**Comment by cujomalainey** [comment]
@andyross FYI

**Review by lgirdwood — APPROVED** [review]
Good find - I guess we missed that one. @ranj063 good for you ?

**Review by kv2019i — COMMENTED** [review]
Code looks good but I wonder why we did not expose this in the end. The two flags we have in FW in buffer flags are SOF_BUF_UNDERRUN_PERMITTED and SOF_BUF_OVERRUN_PERMITTED . I have no personal recollection of what these are but these were added in 2020 in commit ee3f7d9737f00246a0ea881624c4335e5e3a5c3a and as far as I can tell, never used (either via IPC, or by setting the underrun/overrun permitted flag with internal logic).

Do we have some fresh need for these flags, or need to add more flags?

I ask because in IPC4, the buffers get added by FW and @marcinszkudlinski  has been working on the "audio stream" replacement of buffers -- to allow more complex implementations of buffers (e.g. to save SRAM by pooling memory of buffers in a single pipeline). So I wonder if such behaviour changing flags would better be put to the pipeline nodes versus in the connections (buffers).

OTOH, no harm, so if there's concrete need, I see no issue in proceeding with.

**Comment by plbossart** [comment]
I could be wrong, IIRC the flags were added so that "complicated cases" such as the echo reference stream would be allowed to overrun if the stream is not opened by the host.
Indeed it's anyone's guess what this means for IPC4....

**Comment by cujomalainey** [comment]
> I could be wrong, IIRC the flags were added so that "complicated cases" such as the echo reference stream would be allowed to overrun if the stream is not opened by the host. Indeed it's anyone's guess what this means for IPC4....

That was my assumption too, hence my comment in the other PR about "how is echo ref even working?"

**Comment by ranj063** [comment]
> > I could be wrong, IIRC the flags were added so that "complicated cases" such as the echo reference stream would be allowed to overrun if the stream is not opened by the host. Indeed it's anyone's guess what this means for IPC4....
> 
> That was my assumption too, hence my comment in the other PR about "how is echo ref even working?"

@cujomalainey but how does this PR help? Adding this token in topology means the job is still only half done isnt it? Don't you also need a kernel counterpart?

**Review by ranj063 — APPROVED** [review]

**Pull request merged**
