### PR TITLE
topology: add nau8825 headphone variant boards support on ADL

### PR DESCRIPTION
**Pull request by macchian**
sof-adl-nau8825.tplg:
    headphone connects SSP0 link.
    bluetooth offload uses SSP2 link.

With nau8825 headphone, enabled MCLK/BCLK early start.
Add smart amp and dumb speakers support separately.

sof-adl-max98373-nau8825.tplg:
sof-adl-max98360a-nau8825.tplg:
    headphone connects SSP0 link.
    speakers connects SSP1 link.
    bluetooth offload uses SSP2 link.

sof-adl-rt1019-nau8825.tplg:
    headphone connects SSP0 link.
    speakers connects SSP2 link.

Co-developed-by: David Lin <CTLIN0@nuvoton.com>
Signed-off-by: David Lin <CTLIN0@nuvoton.com>
Signed-off-by: Mac Chiang <mac.chiang@intel.com>

### CODE REVIEW

**Comment by lgirdwood** [comment]
@mwasko fyi

**Comment by mwasko** [comment]
@ranj063 may I ask you or some other SW maintainer to review the listed topology changes?

**Comment by macchian** [comment]
> @ranj063 may I ask you or some other SW maintainer to review the listed topology changes?

FYI. This was in main branch #4932 topology: add nau8825 headphone variant boards support on ADL

**Review by plbossart — APPROVED** [review]
we need a better process to merge such patches from main to release branches.

**Comment by lgirdwood** [comment]
@mwasko fyi.

**Comment by gkbldcig** [comment]
Can one of the admins verify this patch?

**Comment by plbossart** [comment]
> Can one of the admins verify this patch?

what is this about @mwasko ? we've already approved those patches.

**Review by ranj063 — APPROVED** [review]

**Comment by mwasko** [comment]
@plbossart thank you for your patience, notification that this change was approved somehow slipped through my mail filters.

Generally I have already pointed out that storing topology configuration files as a part of FW repo is not the best solution. Topology is not a part of FW but an input to SW Driver and most FW engineering folks have no expertise to review topology content (including me).

**Comment by plbossart** [comment]
> Generally I have already pointed out that storing topology configuration files as a part of FW repo is not the best solution. Topology is not a part of FW but an input to SW Driver and most FW engineering folks have no expertise to review topology content (including me).

the topology is not just an input to the SW driver, it really defines what will get tested, and as such it exposes issues in the firmware, typically with concurrency.

initially we had separate repos, and we had all kinds of synchronization issues with the firmware and topology moving separately. It was so bad I wanted to use the 'repo' tool so that we could use the same configuration.

So yes it's not really related to the firmware per se, but not having a single commit with topology+firmware proved to be a testing nightmare.

**Comment by cujomalainey** [comment]
>  It was so bad I wanted to use the 'repo' tool so that we could use the same configuration.

Oof that hurts

**Pull request merged**
