### PR TITLE
Topology: BDW, BYT, CHT: Reduce buffer size max for media PCM

### PR DESCRIPTION
**Pull request by singalsu**
This change prevents the IPC error that happens if aplay or
speaker-test uses larger than 64 kB buffer size. The buffer
setting in PCM_CAPABILITIES() is now the same as for low latency
PCM.

Signed-off-by: Seppo Ingalsuo <seppo.ingalsuo@linux.intel.com>

### CODE REVIEW

**Comment by singalsu** [comment]
I realized now that this change impacts APT, BDW, BYT, and CHT. I need to edit the commit message since I though it was only for BYT.

```
$ grep -r pipe-pcm-media | sort
sof-apl-nocodec.m4:PIPELINE_PCM_ADD(sof/pipe-pcm-media.m4,
sof-apl-pcm512x.m4:PIPELINE_PCM_ADD(sof/pipe-pcm-media.m4,
sof-bdw-codec.m4:PIPELINE_PCM_ADD(sof/pipe-pcm-media.m4,
sof-bdw-nocodec.m4:PIPELINE_PCM_ADD(sof/pipe-pcm-media.m4,
sof-byt-codec.m4:PIPELINE_PCM_ADD(sof/pipe-pcm-media.m4,
sof-cht-max98090.m4:PIPELINE_PCM_ADD(sof/pipe-pcm-media.m4,
sof-cht-nocodec.m4:PIPELINE_PCM_ADD(sof/pipe-pcm-media.m4,

```

**Comment by lgirdwood** [comment]
@singalsu commit message still says APL

**Comment by singalsu** [comment]
Thanks, I've now fixed the commit message.

**Comment by lgirdwood** [comment]
Jenkins CI known issues.

**Pull request merged**
