### PR TITLE
klocwork: fix kw issues

### PR DESCRIPTION
**Pull request by dabekjakub**
Fixed issues:

341

### CODE REVIEW

**Comment by lgirdwood** [comment]
@dabekjakub which issue does this fix, I cant see a #341

**Comment by dabekjakub** [comment]
I should rewrite this - i fixed 341 Klocwork issue not 341 github issue. Do we even want KW issue number in commits ? And do we want to create issues on repo for KW issues ?

**Comment by lgirdwood** [comment]
@dabekjakub best to not include any internal tool data and just use "pipeline: fix potential pointer deref" just like a regular patch.

**Comment by dabekjakub** [comment]
Will do.

**Pull request closed without merging**
