### PR TITLE
Add multi-core coverage to CI

### PR DESCRIPTION
**Pull request by keyonjie**
1. change the sof-adl-nocodec.m4 to assign pipelines on all 4 DSP cores, this will enable "PR multi-core + dynamic pipeline" validation coverage.
2. change the sof-tgl-nocodec.m4 to assign pipelines on all DSP cores for tgl-nocodec, which will be run on daily test as comparison with ADL one.

### CODE REVIEW

**Comment by lgirdwood** [comment]
@keyonjie one of the ADL DUTR has a lot of failures, but the other ADL and TGL are good. I will rerun to get more data.

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by lgirdwood** [comment]
Clicked the wrong button.

**Comment by keyonjie** [comment]
> @keyonjie one of the ADL DUTR has a lot of failures, but the other ADL and TGL are good. I will rerun to get more data.

@lgirdwood the ADL nocodec has a lot of failures is as expected as this PR change that platform to use multi-core, and that's why we need the https://github.com/thesofproject/sof/pull/4981 to address the failure we see here.

**Comment by lgirdwood** [comment]
Lets merge after #4981

**Review by kv2019i — APPROVED** [review]
This will make some Zephyr tests fail in our daily plan, but I think it's better to get better multicore coverage in CI, so I'd say let's go with this.

**Comment by keyonjie** [comment]
Let's merge it to break the CI daily tomorrow.

**Pull request merged**
