### PR TITLE
topology: nhlt: intel: support m/n divider and xtal/cardinal/pll clock source

### PR DESCRIPTION
**Pull request by brentlu**
By sending xtal/cardinal/pll frequencies to alsatplg, we could select a proper clock source according to mclk/bclk frequency as well as m n number.

PR of alsatplg is here: https://github.com/alsa-project/alsa-utils/pull/220

I tested the code on ADL brya device with following setting:
1.
MCLK: 24.576MHz
BCLK: 3.072Mz (m 1 n 1)

[   37.489143] Message payload: 00000000: 0000066f 00000180 00000180 00000001
[   37.489145] Message payload: 00000010: 0000bb80 00000020 ffffff10 00000001
[   37.489147] Message payload: 00000020: 00000000 00002002 0000bb80 00000020
[   37.489148] Message payload: 00000030: ffffff10 00000001 00000000 00002002
[   37.489149] Message payload: 00000040: 00000000 00000c00 00000300 0000001f
[   37.489150] Message payload: 00000050: 00000000 ee000105 0000007c ffffff10
[   37.489151] Message payload: 00000060: ffffff10 ffffff10 ffffff10 ffffff10
[   37.489151] Message payload: 00000070: ffffff10 ffffff10 ffffff10 c1d0077f
[   37.489152] Message payload: 00000080: d0700000 00000000 02200000 00000003
[   37.489153] Message payload: 00000090: 00000003 00004002 00000000 07070000
[   37.489154] Message payload: 000000a0: 00000020 **00110001** 00000001 **00000fff**
=> clock source: 1
=> mclk divider: bypass (oxfff)
[   37.489155] Message payload: 000000b0: 00000000 00000008 **00000001** **00000001**
=>m = 1, n = 1
[   37.489156] Message payload: 000000c0: 00000007 00000004 00000001

2.
MCLK: 19.2MHz
BCLK: 3.072Mz (m 24 n 25)

[   21.090181] Message payload: 00000000: 0000066f 00000180 00000180 00000001
[   21.090183] Message payload: 00000010: 0000bb80 00000020 ffffff10 00000001
[   21.090185] Message payload: 00000020: 00000000 00002002 0000bb80 00000020
[   21.090186] Message payload: 00000030: ffffff10 00000001 00000000 00002002
[   21.090186] Message payload: 00000040: 00000000 00000c00 00000300 0000001f
[   21.090187] Message payload: 00000050: 00000000 ee000105 0000007c ffffff10
[   21.090188] Message payload: 00000060: ffffff10 ffffff10 ffffff10 ffffff10
[   21.090189] Message payload: 00000070: ffffff10 ffffff10 ffffff10 c1d00b7f
[   21.090190] Message payload: 00000080: d0700000 00000000 02200000 00000003
[   21.090191] Message payload: 00000090: 00000003 00004002 00000000 07070000
[   21.090192] Message payload: 000000a0: 00000020 **00000001** 00000001 **00000000**
 => clock source: 0
=> mclk divider: 1/2
[   21.090193] Message payload: 000000b0: 00000000 00000008 **00000018** **00000019**
=>m = 24, n = 25
[   21.090193] Message payload: 000000c0: 00000007 00000004 00000001
(current fw does not handle m/n registers, need small patch)

### CODE REVIEW

**Comment by brentlu** [comment]
I know, it's only a test to prove the m/n code logic is correct. By choosing mclk and bclk frequency carefully, the code will not use m/n counter at all. I can revert the m/n code and keep the mclk/bclk source selection code. How do you think?

**Comment by plbossart** [comment]
> I know, it's only a test to prove the m/n code logic is correct. By choosing mclk and bclk frequency carefully, the code will not use m/n counter at all. I can revert the m/n code and keep the mclk/bclk source selection code. How do you think?

That's fine. Just don't use 124/125, that's a recipe for poor audio quality. And that's no longer available anyways on newer hardware.

**Review by lgirdwood — APPROVED** [review]
LGTM @jsarha @ranj063 pls review

**Comment by brentlu** [comment]
We could close this PR if we decide to use cardinal clock as the only one clock source. It should be fine since 24.576MHz is popular.

**Comment by lgirdwood** [comment]
> We could close this PR if we decide to use cardinal clock as the only one clock source. It should be fine since 24.576MHz is popular.

@plbossart what's your take, I guess we should mark 124/125 as a "dont use" in the comments ?

**Comment by plbossart** [comment]
I suggest we only use 24.576 MHz for the clock source, this comes 'for free' since MTL and is the best option for us. Besides M/N dividers are removed in newer hardware so all that work would be for one single generation of products.

**Comment by brentlu** [comment]
It seems this PR does not benefit us. Let's close this PR and thanks for the review.

**Pull request closed without merging**
