### PR TITLE
Revert "pcm_converter: Convert linear memory regions"

### PR DESCRIPTION
**Pull request by plbossart**
https://github.com/thesofproject/sof/pull/3156 does not work, so if we can't get a quick fix let's revert and redo. Nothing personal, just that we can't break CI for a month and keep going this way.

This reverts commit 1f092df4012def1c541bf7c627ecffd51584093b.

Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>

### CODE REVIEW

**Comment by paulstelian97** [comment]
I would like to discuss about the situation of turning circular buffers into linear memory regions, especially when the buffer size might not be a multiple of the conversion unit size. That is very interesting for compressed playback since the available algorithms expect linear buffers of a certain minimum size and might not even consume all of the data if there's something.

**Comment by lgirdwood** [comment]
CI does show cliiping and that looks due to PGA2.0 on the capture path being > 0dB.
@aiChaoSONG good work on the CI, can we check/change that the audio config for all capture paths to be 0dB

**Comment by plbossart** [comment]
> CI does show cliiping and that looks due to PGA2.0 on the capture path being > 0dB.

how did you find this?

> @aiChaoSONG good work on the CI, can we check/change that the audio config for all capture paths to be 0dB

I am still worried about kmod tests failed with no obvious failure reported.

**Comment by lgirdwood** [comment]
> > CI does show cliiping and that looks due to PGA2.0 on the capture path being > 0dB.
> 
> how did you find this?

An alsa-bat wav file is available when you click on the test results which can be loaded into audacity. Then checked the topology diagram and logs for PGA gains and could see the gain value for each PGA
```c
#define VOL_QXY_Y 16

/** \brief Volume 0dB value. */
#define VOL_ZERO_DB	BIT(VOL_QXY_Y)
```
The volume for PGA2.0 was above this value.

**Comment by plbossart** [comment]
> > > CI does show cliiping and that looks due to PGA2.0 on the capture path being > 0dB.
> > 
> > 
> > how did you find this?
> 
> An alsa-bat wav file is available when you click on the test results which can be loaded into audacity. Then checked the topology diagram and logs for PGA gains and could see the gain value for each PGA

I must be really think, I can't see any wav files - 
> 
> ```c
> #define VOL_QXY_Y 16
> 
> /** \brief Volume 0dB value. */
> #define VOL_ZERO_DB	BIT(VOL_QXY_Y)
> ```
> 
> The volume for PGA2.0 was above this value.



> > > CI does show cliiping and that looks due to PGA2.0 on the capture path being > 0dB.
> > 
> > 
> > how did you find this?
> 
> An alsa-bat wav file is available when you click on the test results which can be loaded into audacity. Then checked the topology diagram and logs for PGA gains and could see the gain value for each PGA

Well of course I clicked on the Cyan case where there are no results. When I click on Minnowboard w/ rt5682 then my browser downloads a wav file. But if I click on other test cases that passed, then also no wav results and some really strange error messages.

Try different columns for check-alsabat-headset-playback.sh in https://sof-ci.01.org/sofpr/PR3159/build6557/devicetest/

**Comment by plbossart** [comment]
> Try different columns for check-alsabat-headset-playback.sh in https://sof-ci.01.org/sofpr/PR3159/build6557/devicetest/

Update: if I use Firefox then I get the two files for the two cases that fail. There's a nice menu that selects Audacity by default. But with Chrome it looks random and there's no menu at all. @aiChaoSONG FYI, you may want to look into HTML generation issues here?

**Comment by marc-hb** [comment]
> I am still worried about kmod tests failed with no obvious failure reported

I started with a cleanup of this particular test, please help review: https://github.com/thesofproject/sof-test/pull/368

No functional change yet.

**Pull request merged**
