### PR TITLE
Add xrun notification initialization

### PR DESCRIPTION
**Pull request by makarukp**
- Add separate file for notifications initializations. All generic
initializations could be stored in one place
- Add initialization for generic xrun notification message which can be sent
by gateway.

### CODE REVIEW

**Review by softwarecki — CHANGES_REQUESTED** [review]

**Comment by softwarecki** [comment]
This is a very good idea! When I added the notification for a watchdog I wondered where to put the function that initiates the ipc4 notification structure. However, I didn't want to create a new file for only one function. Now that we've collected a bit of them, we can move them all to one place.

**Review by softwarecki — APPROVED** [review]

**Comment by tmleman** [comment]
@makarukp  will it be developed later? Because from what I can see, it's a dead code.

**Comment by makarukp** [comment]
> @makarukp will it be developed later? Because from what I can see, it's a dead code.

This is dependency required by chain dma and is going to be used in #6887

**Comment by tmleman** [comment]
> @tmleman This is dependency required by chain dma and is going to be used in #6887

This is not a blocker for me but I think this should be one PR.

**Comment by makarukp** [comment]
> > @tmleman This is dependency required by chain dma and is going to be used in #6887
> 
> This is not a blocker for me but I think this should be one PR.

@tmleman I think it could be perceived as separated PR because it introduces generic gateway notification. This is not only specific for chain dma.

**Comment by marc-hb** [comment]
> > @makarukp will it be developed later? Because from what I can see, it's a dead code.

> @tmleman This is dependency required by chain dma and is going to be used in https://github.com/thesofproject/sof/pull/6887

@makarukp please submit a draft, no-reviewer, throw-away test PR that combines and tests these two.

**Comment by marc-hb** [comment]
> I think it could be perceived as separated PR because it introduces generic gateway notification.

The Zephyr project is about to publish guidelines for this question:
- https://github.com/zephyrproject-rtos/zephyr/pull/52731

Spoiler alert: I don't think 52731 would provide a definitive answer in this particular case. Code review is not an exact science.

If the code in this first PR was "alive" alone before the second PR then they should definitely be two different PRs merged with at least 1 day interval to maximize CI coverage.

**Comment by juimonen** [comment]
@makarukp and should you just combine the 2 commits into 1 in this PR? don't see too much benefit first committing "empty" file...

**Comment by makarukp** [comment]
@marc-hb Please checkout test PR combining PR with hda chain. 
#7177

**Review by dabekjakub — APPROVED** [review]

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
> @marc-hb Please checkout test PR combining PR with hda chain. #7177

@makarukp will you be merging #7177 into this PR as an API user ?

**Comment by marc-hb** [comment]
> @makarukp will you be merging https://github.com/thesofproject/sof/pull/7177 into this PR as an API user ?

I recommended this for pure testing purposes.

**Comment by makarukp** [comment]
SOFCI TEST

**Comment by makarukp** [comment]
@lgirdwood @marc-hb #7177 is combination of this generic PR (#7164)  and API user (#6887). From my point of view this looks like pure testing.
My intention was to merge #7164 into main as first step, then reopen and finalize #6887 asap.

Ofcourse there is no big problem to merge it into one PR combining generic notification and API user in #6887 if you have any objections.

**Comment by keqiaozhang** [comment]
SOFCI TEST

**Pull request merged**
