### PR TITLE
topology1: adl-sdw-cs42l42: support CS42L42-SDW codec

### PR DESCRIPTION
**Pull request by davidrau-renesas-opensource**
Add a new topology sof-adl-sdw-cs42l42 for CS42L42 which supports SDW1 for headset on ADL board.

### CODE REVIEW

**Comment by sofci** [comment]
Can one of the admins verify this patch?
> reply **test&nbsp;this&nbsp;please** to run this test once

**Review by kv2019i — APPROVED** [review]
Thansk @davidrau-renesas-opensource , looks good!

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
test this please

**Comment by keqiaozhang** [comment]
SOFCI TEST

**Comment by keqiaozhang** [comment]
SOFCI TEST

**Comment by keqiaozhang** [comment]
SOFCI TEST

**Comment by keqiaozhang** [comment]
SOFCI TEST

**Comment by keqiaozhang** [comment]
SOFCI TEST

**Comment by lgirdwood** [comment]
PM Failures on non ADL unrelated here.

**Pull request merged**
