### PR TITLE
Backport bclk clock control to JSL branch

### PR DESCRIPTION
**Pull request by brentlu**
Backport the PR to JSL branch to support cs42l42 headphone codec on JSL Chromebooks.

https://github.com/thesofproject/sof/pull/4391

### CODE REVIEW

**Comment by brentlu** [comment]
Not sure we can merge the the jsl-004 branch or need to create an new one like jsl-004-hot-fix-1 ?

**Comment by lgirdwood** [comment]
@mwasko @bkokoszx fyi.

**Comment by brentlu** [comment]
rebase due to branch change

**Comment by lgirdwood** [comment]
@mwasko @abonislawski @sathya-nujella fyi.

**Comment by mwasko** [comment]
> Not sure we can merge to the jsl-004 branch or need to create an new one like jsl-004-hot-fix-1 ?

@brentlu I would recommend creating jsl-004-hot-fix-1 branch. I assume that you will maintain and validate the hot fix branch?

**Comment by brentlu** [comment]
@mwasko yes, we work with ODM to validate the FW and TPLG for Chromebooks.

**Pull request merged**
