### PR TITLE
Rename version.h to sof_versions.h to fix missing git versions when using Zephyr

### PR DESCRIPTION
**Pull request by marc-hb**
See commit messages

### CODE REVIEW

**Comment by marc-hb** [comment]
Good old `rtc_cmos Alarms can be up to one month in the future` error in
https://sof-ci.01.org/sofpr/PR5207/build11616/devicetest/?model=APL_UP2_NOCODEC&testcase=check-suspend-resume-with-capture-5  long time no see! https://github.com/thesofproject/linux/issues/3011

First time on APL?

**Comment by marc-hb** [comment]
SOFCI TEST

**Comment by marc-hb** [comment]
I have a number of git related fixes conditioned / blocked by this rename.

**Review by lgirdwood — APPROVED** [review]

**Comment by greg-intel** [comment]
@marc-hb [created a ticket](https://github.com/thesofproject/sof-test/issues/838) for the TPM kernel error.

**Pull request merged**
